### ISSUE TITLE
[UI] glitch in dark ui

### ISSUE THREAD

**Issue by cybre-finn** [go-gitea/gitea#5677] opened 2019-01-09 13:38 UTC
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [x] Not relevant
- Log gist:

## Description

That's a leftover from the original theme in the upper right corner if you view this in horizontal window scaling.

## Screenshots
![asda](https://user-images.githubusercontent.com/20602537/50902747-0bbbaf00-141c-11e9-8277-461868c37205.png)

**Comment by lunny** [comment] 2019-02-06 01:41
@mdanzinger please.

**Comment by mdanzinger** [comment] 2019-02-11 04:48
@ikarulus I'm not seeing this on my end (https://i.imgur.com/gawQhPa.png), can you please provide some more information, namely;

1. Device / Browser / Version
2. Resolution 

Thanks!

**Comment by techknowlogick** [comment] 2019-02-11 04:53
@ikarulus I'm on latest commit in master (1.8.0-dev), and I also can seem to replicate (I'm FF on OSX)

**Comment by mdanzinger** [comment] 2019-02-11 05:00
@techknowlogick Which version FF are you using? I'm on the tip of master too.

**Comment by techknowlogick** [comment] 2019-02-11 05:10
FF 65.0

**Comment by mdanzinger** [comment] 2019-02-11 05:18
Just tested FF 65.0 on Windows 10 and Ubuntu, I don't see the issue on either. I'll test on OSX tomorrow.


![0886a7dbacf958a6bc995de6e526e793](https://user-images.githubusercontent.com/14279788/52547103-cf6ccd00-2d92-11e9-82b2-f089cb94c242.png)

**Comment by mdanzinger** [comment] 2019-02-11 17:44
@techknowlogick @ikarulus  Just tested on FF 65.0 on OSX and I'm still not able to reproduce the issue. If there's any additional information you can provide that'd be great.


![](https://i.gyazo.com/68705f30564e07cfec02527449580013.mp4)

**Comment by techknowlogick** [comment] 2019-02-11 23:28
Going to close this as it seems to be resolved, please re-open if it is still an issue. If re-opening please provide version of Gitea in use, browser, and OS.

**Closed as completed by techknowlogick** 2019-02-11 23:28 UTC
Labels: topic/ui
