### ISSUE TITLE
login log and operation log

### ISSUE THREAD

**Issue by MrLin-619** [go-gitea/gitea#10860] opened 2020-03-28 06:39 UTC
Hello, do you have any plans to add login log and operation log?

**Comment by Joolun** [comment] 2020-04-08 05:14
I think too, login log is necessary

**Comment by lunny** [comment] 2020-04-08 05:28
I think this should be saved into audit log. There is already an issue to request a feature for that.

**Comment by MrLin-619** [comment] 2020-04-09 13:21
Save as file? Will it be saved to the database?

**Comment by lafriks** [comment] 2020-04-09 13:41
Audit log (user authorizations/sessions) should probably be saved to database so that it could be possible for user to display it's active sessions and close them if needed

**Comment by lafriks** [comment] 2020-04-09 13:43
Duplicate of #5312 and #8

**Closed as completed by lafriks** 2020-04-09 13:43 UTC
Labels: issue/duplicate
