### ISSUE TITLE
Moving project panels results in 500 `GetProjectBoard: project board does not exist`

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#29853] opened 2024-03-16 18:40 UTC
### Description

1. Create Project
2. Create two panels in it
3. Drag-and-drop the panels, swapping them. Observe 500 error from `PUT` request:

```
...web/repo/projects.go:526:checkProjectBoardChangePermissions() [E] GetProjectBoard: project board does not exist [id: 0]
...eb/routing/logger.go:102:func1() [I] router: completed PUT /silverwind/symlink-test/projects/1/0 for 127.0.0.1:56716, 500 Internal Server Error in 30.2ms @ repo/projects.go:546(repo.EditProjectBoard)
```

Reproduced on https://try.gitea.io/silverwind/symlink-test/projects/3308.

### Gitea Version

main

**Comment by lunny** [comment] 2024-03-17 14:05
I cannot reproduce it on my local main branch.

**Comment by lng2020** [comment] 2024-03-17 15:44
@lunny It only happens when sorting the default project board

**Comment by lunny** [comment] 2024-03-19 03:54
This will be resolved by #29874 but that cannot be backport to v1.21. Should we have another PR to do a quick fix for v1.21?

**Comment by silverwind** [comment] 2024-03-19 10:16
It's not a critical thing, so I would not backport.

**Closed as completed** 2024-03-27 20:54 UTC
Labels: type/bug, issue/confirmed, topic/projects
