### ISSUE TITLE
Issue update branch selection disable

### ISSUE THREAD

**Issue by ejouvin** [go-gitea/gitea#11266] opened 2020-05-01 09:35 UTC
- Gitea version (or commit ref): 1.11.4
- Git version:
- Operating system:
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Why on an existing issue, the branch dropdown box is disabled ?
We can affect branch during creation, but not during update.
...

## Screenshots
![image](https://user-images.githubusercontent.com/8817923/80796544-c9355d00-8b9f-11ea-90ba-510d01ef1387.png)

**Comment by jolheiser** [comment] 2020-05-01 15:50
Duplicate of #3620

**Closed as completed by jolheiser** 2020-05-01 15:50 UTC
Labels: issue/duplicate
