### ISSUE TITLE
Github Actions for gitea

### ISSUE THREAD

**Issue by zuhairamahdi** [go-gitea/gitea#13206] opened 2020-10-18 21:26 UTC
## Description

is there any way that we can mimic the features available in Github actions for deploying applications (or triggering an event) based on an event (other than using hooks) for Gitea?

**Comment by techknowlogick** [comment] 2020-10-19 04:11
Closing as dupe of #12673

I'll repost what I said there:
> Thanks for this request. Currently we are attempting to keep the scope of gitea limited as we only have so much developer capacity for the project and recommend utilizing a purpose built CI/CD tool (there are several that support Gitea listed here: https://docs.gitea.io/en-us/ci-cd/). We are very happy with Drone specifically and use it for the Gitea project itself (some Gitea contributors also contribute to drone)

**Closed as completed by techknowlogick** 2020-10-19 04:11 UTC
Labels: issue/duplicate
