### ISSUE TITLE
gitea lfs Storage error

### ISSUE THREAD

**Issue by WangZhongDian** [go-gitea/gitea#31351] opened 2024-06-13 03:31 UTC
### Description

# question
I created a test repository to describe my problem. After completing the initialization work of LFS, there was a ttf file and a pth file inside, both of which were tracked by LFS. When uploaded to Gitea, the ttf file was normal, while the pth error was `500`. However, there was a pointer to the pth file in the backend`/data/git/lfs`. I compared this on Github, which is completely normal
![图片](https://github.com/go-gitea/gitea/assets/103353084/7cf0fe0e-f252-4fe7-a3df-6d1b29a30219)
![图片](https://github.com/go-gitea/gitea/assets/103353084/829b99e6-12ee-4714-90a4-2bdfa4956e96)
![图片](https://github.com/go-gitea/gitea/assets/103353084/2cba6bb7-f0b1-4a88-862d-c74313cf1e3c)

## github
![图片](https://github.com/go-gitea/gitea/assets/103353084/91d9eacd-81af-41e4-ab39-fff3c23257c1)
![图片](https://github.com/go-gitea/gitea/assets/103353084/c4892e03-2600-434e-aa7b-02198019fc9e)

### Gitea Version

1.22

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

2.43.0

### Operating System

ubuntu24.04

### How are you running Gitea?

docker

### Database

SQLite

**Comment by MaxWaldorf** [comment] 2024-06-15 22:20
I confirm same behavior here... pushing lfs is impossible...

**Comment by wxiaoguang** [comment] 2024-06-16 02:08
I am also using Gitea LFS in my team, and haven't encounter any problem.

Could you provide a reproducible setup (a docker-compose) with detailed steps (step by step and the files)? If I could reproduce it on my machine, then I could try to debug it.

**Comment by WangZhongDian** [comment] 2024-06-16 09:44
@wxiaoguang 
I feel that there is only a problem with the. pth file. Have you tried uploading the. pth file in pytorch format

**Comment by WangZhongDian** [comment] 2024-06-16 09:47
It seems that this issue only occurs when tracking` *. pth` files

**Comment by wxiaoguang** [comment] 2024-06-16 09:48
> @wxiaoguang I feel that there is only a problem with the. pth file. Have you tried uploading the. pth file in pytorch format

I do not think it is a general problem, because Gitea itself have no special code for "file extension" or "file content".

So the question is: how to reproduce? Is it related to the file size? File content (deleted by antivirus software)? Or something else? 

Does every pth file get lost in your environment, or one some special ones get lost?

**Comment by WangZhongDian** [comment] 2024-06-16 09:51
@wxiaoguang 
I am currently unable to determine the root cause of the problem. When I click on this file, an error of `500` will appear
![图片](https://github.com/go-gitea/gitea/assets/103353084/d74fd8d5-e2e3-4294-aea4-c760a29ac3a7)

**Comment by wxiaoguang** [comment] 2024-06-16 09:52
> @wxiaoguang
> I am currently unable to determine the root cause of the problem. When I click on this file, an error of `500` will appear

So could you provide a reproducible setup (a docker-compose) with detailed steps (step by step and the files)? If I could reproduce it on my machine, then I could try to debug it.

**Comment by wxiaoguang** [comment] 2024-06-16 09:55
ps: if you couldn't reproduce on your local setup either, then it should be related to your server environment (eg: antivirus software, firewall, etc)

**Comment by WangZhongDian** [comment] 2024-06-16 10:02
[yolov5_s_v6.1.zip](https://github.com/user-attachments/files/15857311/yolov5_s_v6.1.zip)
You can try this file
@wxiaoguang 
Docker did not use any special settings, I did not use `Docker Compose` for orchestration

![图片](https://github.com/go-gitea/gitea/assets/103353084/09bfd483-6351-49de-921e-598f3a967b54)
![图片](https://github.com/go-gitea/gitea/assets/103353084/d4a94f4f-74ff-43a7-ad70-62559d9d302e)

**Comment by WangZhongDian** [comment] 2024-06-16 10:04
My computer is 
ubuntu24.04 
Kernel: 6.8.0-35 generic 
Architecture: x86_64

**Comment by WangZhongDian** [comment] 2024-06-16 10:05
If you are unable to reproduce this error, it may be my problem. This Gitea has been upgraded from an old version and I am not sure what internal errors it has experienced

**Comment by wxiaoguang** [comment] 2024-06-16 12:05
It works perfectly on my side.

![image](https://github.com/go-gitea/gitea/assets/2114189/87c42521-8f5f-4390-812d-603322f22e6f)

![image](https://github.com/go-gitea/gitea/assets/2114189/e4db2c42-59c2-4870-b36e-d333e2e44aac)

![image](https://github.com/go-gitea/gitea/assets/2114189/26938e62-45c1-4c6f-8e96-ee5d3457d482)

![image](https://github.com/go-gitea/gitea/assets/2114189/3dd024de-515c-4a15-af2a-d11973c4ed7a)

**Comment by wxiaoguang** [comment] 2024-06-16 12:15
And one more thing, if a file is lost on server, you could try to re-push all LFS contents by `git lfs push origin main`

**Comment by MaxWaldorf** [comment] 2024-06-16 12:18
Potentially there is an issue with Wasabi...

**Comment by wxiaoguang** [comment] 2024-06-16 12:22
I will close this issue since it doesn't seem to be directly related to Gitea. Feel free to reopen if it could be reproduced on a Gitea setup.

**Closed as completed by wxiaoguang** 2024-06-16 12:22 UTC
Labels: issue/needs-feedback, topic/lfs
