### ISSUE TITLE
Resolving Pull Request conflicts from web editor

### ISSUE THREAD

**Issue by antonlnz** [go-gitea/gitea#23705] opened 2023-03-25 19:21 UTC
### Feature Description

I think it would be a very nice feature to be able to resolve pull request conflicts GitHub style. If I'm not wrong this is not supported right now. [This website](https://www.cloudbees.com/blog/resolve-github-merge-conflicts) shows what I am referring to in the "Resolve within GitHub's Web Editor" section. I attach photos anyway

### Screenshots

![https___rollout io_blog_wp-content_uploads_sites_2_2018_06_resolve-merge-conflict-step1 en tamaño pequeño](https://user-images.githubusercontent.com/59964501/227737117-0c32869c-12aa-4dbb-ac25-4051f76e3ce0.jpeg)
![https___rollout io_blog_wp-content_uploads_sites_2_2018_06_resolve-merge-conflict-step2 en tamaño pequeño](https://user-images.githubusercontent.com/59964501/227737148-c7ad324a-e82b-43d1-ba86-dad09db8914c.jpeg)
![https___rollout io_blog_wp-content_uploads_sites_2_2018_06_resolve-merge-conflict-step3 en tamaño pequeño](https://user-images.githubusercontent.com/59964501/227737145-a54c2d16-39a8-4b55-813d-da0f708dc8bd.jpeg)
![Captura de pantalla 2023-03-25 a las 20 20 07](https://user-images.githubusercontent.com/59964501/227737179-69ff5316-6ef9-4c97-bd3e-c020e86db142.png)

**Comment by delvh** [comment] 2023-03-25 19:27
Duplicate of at least #https://github.com/go-gitea/gitea/issues/9014, and probably others.

**Closed as not planned by delvh** 2023-03-25 19:27 UTC
Labels: issue/duplicate, type/proposal, type/feature
