### ISSUE TITLE
Git LFS bugs with SSH authentication

### ISSUE THREAD

**Issue by Vuregu** [go-gitea/gitea#2690] opened 2017-10-11 21:23 UTC
I've noticed some odd behaviour upon trying out SSH authentication with Git LFS on Gitea.

- Pushing
You can push LFS files to the LFS server with just SSH authentication, although it will ask you for authentication the first time around, which you can cancel once or twice upon which it will continue to upload them successfully.
Any subsequent pushes of LFS files will log "WARNING: Authentication error: Authorization required... Check that you have propoer access to the repository" but LFS will initialize and upload all of the files succesfully.
I've verified that in both initial and subsequent pushes the LFS files do end up on the repository and are stored in the LFS cache.

- Checking out
Cloning/checking out a repository with LFS files using just SSH authentication does not come with any warnings, LFS starts to do its thing and files are being downloaded. However, after a dozen files or so finish downloading and checking out, authentication is asked for all of a sudden, and if you do not provide it, LFS halts further downloading. The first dozen files however do succesfully download and check out. This is very odd behaviour.

Because you can successfully push an entire repository with just SSH authentication over LFS, my initial verdict was that indeed LFS with SSH was supported on Gitea. But upon realizing that check outs do not complete, strangely they do however start to a certain extent, I must admit that SSH authentication is not supported by Gitea with Git LFS.

**Comment by lunny** [comment] 2017-10-12 06:47
duplicated with #2475 ?

**Comment by Vuregu** [comment] 2017-10-13 13:36
I'm not entirely sure it is a duplicate, because I thought it was supposed to be implemented here: https://github.com/go-gitea/gitea/pull/122 and also because it works when you try to push, albeit with the warnings and the prompt.

**Comment by bkcsoft** [comment] 2017-10-15 06:31
Yes this is a duplicate of #2475 :)

**Closed as completed by bkcsoft** 2017-10-15 06:31 UTC
Labels: type/bug, issue/duplicate
