### ISSUE TITLE
Cannot send mail through mail server with "Let's Encrypt"'s ssl cert.

### ISSUE THREAD

**Issue by yhvicey** [go-gitea/gitea#3769] opened 2018-04-08 05:30 UTC
- Gitea version (or commit ref): 1.3.2 built with: bindata, sqlite
- Git version: 2.14.1
- Operating system: Ubuntu 17.10
- Database:
  - [x] SQLite

## Description

Cannot send mail through mail server with "Let's Encrypt"'s ssl cert.
Notification:
```
Failed to send test email to 'xxx@xxx.com': gomail: could not send email 1: StartTLS: x509: certificate signed by unknown authority
```

**Comment by techknowlogick** [comment] 2018-06-27 22:22
@yhvicey can you try using StartTLS except with a service that doesn't sign with LE to help narrow down the cause?

**Comment by techknowlogick** [comment] 2018-09-09 04:49
Closing this ticket. Please feel welcome to reopen it.

**Closed as completed by techknowlogick** 2018-09-09 04:49 UTC

**Comment by thomai** [comment] 2019-08-15 16:32
I tried it with multiple providers. Same problem with all of them. It seems like it does not depend on the certificate authority.

My tests included the following providers (with the openssl output regarding the certificate chain):

gmail.com (gmail-smtp-in.l.google.com:25):
```
Certificate chain
 0 s:C = US, ST = California, L = Mountain View, O = Google LLC, CN = mx.google.com
   i:C = US, O = Google Trust Services, CN = GTS CA 1O1
 1 s:C = US, O = Google Trust Services, CN = GTS CA 1O1
   i:OU = GlobalSign Root CA - R2, O = GlobalSign, CN = GlobalSign
```

mailbox.org (mxext1.mailbox.org:25):
```
Certificate chain
 0 s:OU = Domain Validated Only, CN = *.mailbox.org
   i:C = CH, O = SwissSign AG, CN = SwissSign Server Silver CA 2014 - G22
 1 s:C = CH, O = SwissSign AG, CN = SwissSign Server Silver CA 2014 - G22
   i:C = CH, O = SwissSign AG, CN = SwissSign Silver CA - G2
 2 s:C = CH, O = SwissSign AG, CN = SwissSign Silver CA - G2
   i:C = CH, O = SwissSign AG, CN = SwissSign Silver CA - G2
```

gmx.com (mx01.gmx.net:25):
```
Certificate chain
 0 s:C = DE, O = 1&1 Mail & Media GmbH, ST = Rheinland-Pfalz, L = Montabaur, CN = mx.gmx.net
   i:C = DE, O = T-Systems International GmbH, OU = T-Systems Trust Center, ST = Nordrhein Westfalen, postalCode = 57250, L = Netphen, street = Untere Industriestr. 20, CN = TeleSec ServerPass Class 2 CA
 1 s:C = DE, O = T-Systems International GmbH, OU = T-Systems Trust Center, ST = Nordrhein Westfalen, postalCode = 57250, L = Netphen, street = Untere Industriestr. 20, CN = TeleSec ServerPass Class 2 CA
   i:C = DE, O = T-Systems Enterprise Services GmbH, OU = T-Systems Trust Center, CN = T-TeleSec GlobalRoot Class 2
```

All of those providers are very well-known. Do you have any idea what the problem is here?

**Comment by thomai** [comment] 2019-08-15 20:26
I was able to solve the issue by providing the full certificate chain on port 587 of the mailserver. My fault.
