### ISSUE TITLE
Project Repository Grouping Function

### ISSUE THREAD

**Issue by yijiangchengming** [go-gitea/gitea#32875] opened 2024-12-17 13:35 UTC
### Feature Description

Now more and more projects are separated from the front-end and back-end. I hope there is a project group function to collect different repositories of the project. Instead of displaying all projects at the same level. For example, there is a project named project, which has a front-end repository front, a back-end repository backend, and an Android repository. Their repository addresses are 
https://xxx.xxx.com/user/project/front.git, 
https://xxx.xxx.com/user/project/backend.git, 
https://xxx.xxx.com/user/project/android.git.
You can create a new project and then create different repositories in it.

**Comment by lunny** [comment] 2024-12-17 19:30
Duplicate of #1872

**Closed as not planned** 2024-12-17 19:30 UTC
Labels: type/proposal
