### ISSUE TITLE
"repository already exists" but not

### ISSUE THREAD

**Issue by strahe** [go-gitea/gitea#7154] opened 2019-06-07 14:18 UTC
- Gitea version (or commit ref): 1.8.2
- Git version:
- Operating system: Linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

There is a repository called `template/name1`,  then I fork it to `myorg/name1` and change the name to `myorg/other1-name` through the API.

I am sure both operations (fork and change name) are successful, and there is no repository in `myorg` organization called `myorg/name1`.

When I fork `template/name1` to `myorg` again, the API returns an error: `repository already exists [uname: myorg, name: myorg/name1]`

**Comment by jolheiser** [comment] 2019-06-07 18:09
The error may be a little misleading.  
A repo with that name doesn't exist, however you cannot fork a project twice. Just because you renamed it doesn't make it *not* a fork, so what Gitea is really mad about is the attempt to fork it a second time.

**Comment by strahe** [comment] 2019-06-08 03:51
@jolheiser 
Hi, thank you for answering my question. Is this a bug or is it originally designed?

**Comment by lunny** [comment] 2019-06-08 07:51
This should be fixed. We need a more accurate error type and message.

**Comment by strahe** [comment] 2019-06-08 08:10
![s](https://user-images.githubusercontent.com/7932644/59144255-ba820c80-8a07-11e9-8073-b3e77a42165a.png)
![s1](https://user-images.githubusercontent.com/7932644/59144256-c077ed80-8a07-11e9-8a7b-16813b2ab4db.png)

I only got this information. @lunny

**Comment by jolheiser** [comment] 2019-06-12 21:28
Since #7185 is merged, is there anything further to discuss here?

@strahe By design, a repo can only be forked once per user/org, regardless of name changes.

**Closed as completed** 2019-06-13 00:33 UTC
