### ISSUE TITLE
Feature: Allow custom webhooks with custom http header + body

### ISSUE THREAD

**Issue by izelnakri** [go-gitea/gitea#12340] opened 2020-07-27 18:52 UTC
## Description

Hi there,

I wanted to implement a gitea<->argo CI/CD system, and for this I need to make a HTTP POST request to my argo server with a Bearer token. 

In other words in the UI we need a way to add custom http headers and http body(the argo workflow template to trigger via json), not just url and http methods. I think this is an essential feature that gitea needs to support. I can create a simple node.js server that parses the webhooks and makes my requests to the argo server but thats very hacky.

**Comment by jolheiser** [comment] 2020-07-27 18:54
Related or duplicate of #1089?

**Comment by izelnakri** [comment] 2020-07-27 20:25
Yes I had seen/skimmed that issue, the suggestion there seemed more complex and handles more cases. I didn't want to give an impression that I endorse all the suggestions there, although I dont mean I agree or disagree with their approach. 

What Im suggesting here is rather adding 2 form sections to Gitea webhooks: http headers and http body(with default prefilled perhaps)

**Comment by techknowlogick** [comment] 2021-08-01 21:46
Merging this into https://github.com/go-gitea/gitea/issues/1089 (and the contents of the template can be covered there, incl. headers)

**Closed as completed by techknowlogick** 2021-08-01 21:46 UTC
Labels: issue/confirmed
