### ISSUE TITLE
SSH cloning not working on Windows

### ISSUE THREAD

**Issue by martintalero** [go-gitea/gitea#25218] opened 2023-06-13 00:33 UTC
### Description

Gite clone using ssh doesn't seem to work.

 *****///////////////////////////////////////////////////**********
--DOESN"T WORK:

C:\Users\Carambolo\Desktop\testrepo>git clone ssh://git@192.168.1.100:1111/T/T-Airflow.git
Cloning into 'T-Airflow'...
git@192.168.1.100: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
 *****///////////////////////////////////////////////////**********

--WORKS:
 *****///////////////////////////////////////////////////**********
C:\Users\Carambolo\Desktop\testrepo>ssh -vvv git@192.168.1.100 -p 1111 git-receive-pack t/t-Airflow.git
OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2
debug3: Failed to open file:C:/Users/Carambolo/.ssh/config error:2
debug3: Failed to open file:C:/ProgramData/ssh/ssh_config error:2
debug2: resolve_canonicalize: hostname 192.168.1.100 is address
debug2: ssh_connect_direct
debug1: Connecting to 192.168.1.100 [192.168.1.100] port 1111.
debug1: Connection established.
debug3: Failed to open file:C:/Users/Carambolo/.ssh/id_rsa error:2
debug3: Failed to open file:C:/Users/Carambolo/.ssh/id_rsa.pub error:2
debug1: identity file C:\\Users\\Carambolo/.ssh/id_rsa type -1
debug3: Failed to open file:C:/Users/Carambolo/.ssh/id_rsa-cert error:2
debug3: Failed to open file:C:/Users/Carambolo/.ssh/id_rsa-cert.pub error:2
debug1: identity file C:\\Users\\Carambolo/.ssh/id_rsa-cert type -1
debug3: Failed to open file:C:/Users/Carambolo/.ssh/id_dsa error:2
debug3: Failed to open file:C:/Users/Carambolo/.ssh/id_dsa.pub error:2
debug1: identity file C:\\Users\\Carambolo/.ssh/id_dsa type -1
debug3: Failed to open file:C:/Users/Carambolo/.ssh/id_dsa-cert error:2
debug3: Failed to open file:C:/Users/Carambolo/.ssh/id_dsa-cert.pub error:2
debug1: identity file C:\\Users\\Carambolo/.ssh/id_dsa-cert type -1
debug3: Failed to open file:C:/Users/Carambolo/.ssh/id_ecdsa error:2
debug3: Failed to open file:C:/Users/Carambolo/.ssh/id_ecdsa.pub error:2
debug1: identity file C:\\Users\\Carambolo/.ssh/id_ecdsa type -1
debug3: Failed to open file:C:/Users/Carambolo/.ssh/id_ecdsa-cert error:2
debug3: Failed to open file:C:/Users/Carambolo/.ssh/id_ecdsa-cert.pub error:2
debug1: identity file C:\\Users\\Carambolo/.ssh/id_ecdsa-cert type -1
debug3: Failed to open file:C:/Users/Carambolo/.ssh/id_ed25519 error:2
debug3: Failed to open file:C:/Users/Carambolo/.ssh/id_ed25519.pub error:2
debug1: identity file C:\\Users\\Carambolo/.ssh/id_ed25519 type -1
debug3: Failed to open file:C:/Users/Carambolo/.ssh/id_ed25519-cert error:2
debug3: Failed to open file:C:/Users/Carambolo/.ssh/id_ed25519-cert.pub error:2
debug1: identity file C:\\Users\\Carambolo/.ssh/id_ed25519-cert type -1
debug3: Failed to open file:C:/Users/Carambolo/.ssh/id_xmss error:2
debug3: Failed to open file:C:/Users/Carambolo/.ssh/id_xmss.pub error:2
debug1: identity file C:\\Users\\Carambolo/.ssh/id_xmss type -1
debug3: Failed to open file:C:/Users/Carambolo/.ssh/id_xmss-cert error:2
debug3: Failed to open file:C:/Users/Carambolo/.ssh/id_xmss-cert.pub error:2
debug1: identity file C:\\Users\\Carambolo/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_8.1
debug1: Remote protocol version 2.0, remote software version OpenSSH_9.1
debug1: match: OpenSSH_9.1 pat OpenSSH* compat 0x04000000
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to 192.168.1.100:1111 as 'git'
debug3: put_host_port: [192.168.1.100]:1111
debug3: hostkeys_foreach: reading file "C:\\Users\\Carambolo/.ssh/known_hosts"
debug3: record_hostkey: found key type ED25519 in file C:\\Users\\Carambolo/.ssh/known_hosts:1
debug3: load_hostkeys: loaded 1 keys from [192.168.1.100]:1111
debug3: Failed to open file:C:/Users/Carambolo/.ssh/known_hosts2 error:2
debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts error:2
debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts2 error:2
debug3: order_hostkeyalgs: prefer hostkeyalgs: ssh-ed25519-cert-v01@openssh.com,ssh-ed25519
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,ext-info-c
debug2: host key algorithms: ssh-ed25519-cert-v01@openssh.com,ssh-ed25519,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: sntrup761x25519-sha512@openssh.com,curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256
debug2: host key algorithms: ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com
debug2: compression stoc: none,zlib@openssh.com
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ssh-ed25519
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug3: send packet: type 30
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug3: receive packet: type 31
debug1: Server host key: ssh-ed25519 SHA256:LVAUoIzLGssRlvIr6zIUKBXCY/GtN+0y6ZVwkREAfgg
debug3: put_host_port: [192.168.1.100]:1111
debug3: put_host_port: [192.168.1.100]:1111
debug3: hostkeys_foreach: reading file "C:\\Users\\Carambolo/.ssh/known_hosts"
debug3: record_hostkey: found key type ED25519 in file C:\\Users\\Carambolo/.ssh/known_hosts:1
debug3: load_hostkeys: loaded 1 keys from [192.168.1.100]:1111
debug3: Failed to open file:C:/Users/Carambolo/.ssh/known_hosts2 error:2
debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts error:2
debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts2 error:2
debug3: hostkeys_foreach: reading file "C:\\Users\\Carambolo/.ssh/known_hosts"
debug3: record_hostkey: found key type ED25519 in file C:\\Users\\Carambolo/.ssh/known_hosts:1
debug3: load_hostkeys: loaded 1 keys from [192.168.1.100]:1111
debug3: Failed to open file:C:/Users/Carambolo/.ssh/known_hosts2 error:2
debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts error:2
debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts2 error:2
debug1: Host '[192.168.1.100]:1111' is known and matches the ED25519 host key.
debug1: Found key in C:\\Users\\Carambolo/.ssh/known_hosts:1
debug3: send packet: type 21
debug2: set_newkeys: mode 1
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug3: receive packet: type 21
debug1: SSH2_MSG_NEWKEYS received
debug2: set_newkeys: mode 0
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: info@t.com.au RSA SHA256:4gYdcOvjo9TVPoNAc2ukdIE0lg762IsutjWfypkF/PY agent
debug1: Will attempt key: C:\\Users\\Carambolo/.ssh/id_rsa
debug1: Will attempt key: C:\\Users\\Carambolo/.ssh/id_dsa
debug1: Will attempt key: C:\\Users\\Carambolo/.ssh/id_ecdsa
debug1: Will attempt key: C:\\Users\\Carambolo/.ssh/id_ed25519
debug1: Will attempt key: C:\\Users\\Carambolo/.ssh/id_xmss
debug2: pubkey_prepare: done
debug3: send packet: type 5
debug3: receive packet: type 7
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,sk-ssh-ed25519@openssh.com,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com,webauthn-sk-ecdsa-sha2-nistp256@openssh.com>
debug1: kex_input_ext_info: publickey-hostbound@openssh.com (unrecognised)
debug3: receive packet: type 6
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug3: send packet: type 50
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey
debug3: start over, passed a different list publickey
debug3: preferred publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Offering public key: info@t.com.au RSA SHA256:4gYdcOvjo9TVPoNAc2ukdIE0lg762IsutjWfypkF/PY agent
debug3: send packet: type 50
debug2: we sent a publickey packet, wait for reply
debug3: receive packet: type 60
debug1: Server accepts key: info@t.com.au RSA SHA256:4gYdcOvjo9TVPoNAc2ukdIE0lg762IsutjWfypkF/PY agent
debug3: sign_and_send_pubkey: RSA SHA256:4gYdcOvjo9TVPoNAc2ukdIE0lg762IsutjWfypkF/PY
debug3: sign_and_send_pubkey: signing using rsa-sha2-512
debug3: send packet: type 50
debug3: receive packet: type 52
debug1: Authentication succeeded (publickey).
Authenticated to 192.168.1.100 ([192.168.1.100]:1111).
debug1: channel 0: new [client-session]
debug3: ssh_session2_open: channel_new: 0
debug2: channel 0: send open
debug3: send packet: type 90
debug1: Requesting no-more-sessions@openssh.com
debug3: send packet: type 80
debug1: Entering interactive session.
debug1: pledge: network
debug3: receive packet: type 80
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug3: receive packet: type 4
debug1: Remote: /data/git/.ssh/authorized_keys:2: key options: command
debug3: receive packet: type 4
debug1: Remote: /data/git/.ssh/authorized_keys:2: key options: command
debug3: receive packet: type 91
debug2: channel_input_open_confirmation: channel 0: callback start
debug2: fd 3 setting TCP_NODELAY
debug2: client_session2_setup: id 0
debug1: Sending command: git-receive-pack t/t-Airflow.git
debug2: channel 0: request exec confirm 1
debug3: send packet: type 98
debug2: channel_input_open_confirmation: channel 0: callback done
debug2: channel 0: open confirm rwindow 0 rmax 32768
debug2: channel 0: rcvd adjust 2097152
debug3: receive packet: type 99
debug2: channel_input_status_confirm: type 99 id 0
debug2: exec request accepted on channel 0
00c0fe977da48b473652a8b88682936411ad4e556fd2 refs/heads/master

 *****///////////////////////////////////////////////////**********

Thank you in advance.

### Gitea Version

1.19.3

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Docker+Windows

### How are you running Gitea?

Docker

### Database

PostgreSQL

**Comment by martintalero** [comment] 2023-06-13 00:48
version: '3.3'

services:
    gitea:
        external_links:
            - Tekra-Postgres:db
        container_name: T-Gitea
        restart: always
        image: gitea/gitea:1.19.3
        ports:
            - "3000:3000"
            - "1111:22"
        environment:
            - USER_UID=1000
            - USER_GID=1000
            - GITEA__database__DB_TYPE=postgres
            - GITEA__database__HOST=172.20.0.2:5432
            - GITEA__database__NAME=g_db
            - GITEA__database__USER=g
            - GITEA__database__PASSWD=g
            - GITEA__mailer__ENABLED=true
            - GITEA__mailer__MAILER_TYPE=smtp
            - GITEA__mailer__FROM=s@t.com.au
            - GITEA__mailer__HOST=smtp.office365.com:587
            - GITEA__mailer__IS_TLS_ENABLED=false
            - GITEA__mailer__USER=s@t.com.au
            - GITEA__mailer__PASSWD=T123
            - GITEA__repository__DISABLE_HTTP_GIT=True
            - GITEA__repository__GO_GET_CLONE_URL_PROTOCOL=ssh
            - GITEA__repository__USE_COMPAT_SSH_URI=True
            - GITEA__repository__DISABLE_DOWNLOAD_SOURCE_ARCHIVES=True
            - GITEA__server__SSH_DOMAIN=192.168.1.100:1111
            - GITEA__server__ROOT_URL=https://gitea.t.synology.me/
            - GITEA__log__ENABLE_SSH_LOG=True
        volumes:
            - /volume1/TDocker/Gitea/data:/data
            - /volume1/TDocker/Gitea/etc/localtime:/etc/localtime:ro
            - /volume1/TDocker/Gitea/etc/timezone:/etc/timezone:ro
        logging:
            options:
                max-size: 10m
                max-file: "3"
        networks:
            Tekra:
               ipv4_address: 172.20.0.7 
networks:
    Tekra:
        external: true

**Comment by wxiaoguang** [comment] 2023-06-13 03:37
That's really strange.

`git clone ssh://git@192.168.1.100:1111/T/T-Airflow.git` reports `git@192.168.1.100: Permission denied (publickey)`, but `ssh -vvv git@192.168.1.100 -p 1111 git-receive-pack t/t-Airflow.git` reports SSH auth succeeded.

Are your SSH and GIT use the same ssh keys?

**Comment by martintalero** [comment] 2023-06-13 03:43
Yes. I only have one set of Keys located in C:\Users\Carambolo/.ssh/ . One with the extension .pub and the other one without extension.

**Comment by martintalero** [comment] 2023-06-13 03:46
![image](https://github.com/go-gitea/gitea/assets/68879161/c377e034-b50c-4d59-98d7-5c5c60287bfe)

**Comment by wxiaoguang** [comment] 2023-06-13 03:46
What does Gitea's log say and what's the difference in log if you run these two commands?

**Comment by martintalero** [comment] 2023-06-13 03:47
Please tell me which commands and how to get the log?

**Comment by wxiaoguang** [comment] 2023-06-13 03:48
https://docs.gitea.com/help/seek-help


```
docker logs  ...
```

**Comment by martintalero** [comment] 2023-06-13 03:49
When cloning: 
![image](https://github.com/go-gitea/gitea/assets/68879161/7b18ee36-0462-4d51-9855-310d229be4ca)

**Comment by martintalero** [comment] 2023-06-13 03:51
When not cloning:
<html>
<body>


2023/06/13 13:48:40 | stdout | 2023/06/13 03:48:40 [6487e718] router: completed GET /api/internal/serv/command/20/tekra/tekra-airflow?mode=2&verb=git-receive-pack for 172.20.0.1:0, 200 OK in 8.9ms @ private/serv.go:80(private.ServCommand)
-- | -- | --
2023/06/13 13:48:40 | stdout | Accepted publickey for git from 172.20.0.1 port 45460 ssh2: RSA SHA256:4gYdcOvjo9TVPoNAc2ukdIE0lg762IsutjWfypkF/PY
2023/06/13 13:44:29 | stdout | 2023/06/13 03:44:29 [6487e2ed] router: polling   GET /user/events for 192.168.1.1:0, elapsed 3180.2ms @ events/events.go:18(events.Events)
2023/06/13 13:44:25 | stdout | 2023/06/13 03:44:25 [6487e619] router: completed GET /user/settings/keys for 192.168.1.1:0, 200 OK in 12.4ms @ setting/keys.go:25(setting.Keys)
2023/06/13 13:44:25 | stdout | 2023/06/13 03:44:25 [6487e618-2] router: completed GET /user/events for 192.168.1.1:0, 200 OK in 1098.1ms @ events/events.go:18(events.Events)
2023/06/13 13:44:24 | stdout | 2023/06/13 03:44:24 [6487e618] router: completed GET /user/settings for 192.168.1.1:0, 200 OK in 9.4ms @ setting/profile.go:44(setting.Profile)
2023/06/13 13:44:24 | stdout | 2023/06/13 03:44:24 [6487e611-3] router: completed GET /user/events for 192.168.1.1:0, 200 OK in 6973.9ms @ events/events.go:18(events.Events)
2023/06/13 13:44:21 | stdout | 2023/06/13 03:44:21 [6487e2ed] router: polling   GET /user/events for 192.168.1.1:0, elapsed 3861.1ms @ events/events.go:18(events.Events)
2023/06/13 13:44:17 | stdout | 2023/06/13 03:44:17 [6487e611-2] router: completed GET /Tekra/Tekra-Airflow.rss for 192.168.1.1:0, 404 Not Found in 3.5ms @ context/repo.go:429(context.RepoAssignment)
2023/06/13 13:44:17 | stdout | 2023/06/13 03:44:17 [6487e611] router: completed GET /Tekra/Tekra-Airflow.atom for 192.168.1.1:0, 404 Not Found in 3.5ms @ context/repo.go:429(context.RepoAssignment)
2023/06/13 13:44:16 | stdout | 2023/06/13 03:44:16 [6487e610] router: completed GET /Tekra/Tekra-Airflow for 192.168.1.1:0, 200 OK in 91.2ms @ repo/view.go:703(repo.Home)
2023/06/13 13:44:16 | stdout | 2023/06/13 03:44:16 [6487e60f-3] router: completed GET /user/events for 192.168.1.1:0, 200 OK in 1220.4ms @ events/events.go:18(events.Events)
2023/06/13 13:44:15 | stdout | 2023/06/13 03:44:15 [6487e60f-2] router: completed GET /repo/search?sort=updated&order=desc&uid=4&team_id=0&q=&page=1&limit=15&mode=&archived=false for 192.168.1.1:0, 200 OK in 15.8ms @ repo/repo.go:472(repo.SearchRepo)
2023/06/13 13:44:15 | stdout | 2023/06/13 03:44:15 [6487e60f] router: completed GET /repo/search?count_only=1&uid=4&team_id=0&q=&page=1&mode= for 192.168.1.1:0, 0  in 13.5ms @ repo/repo.go:472(repo.SearchRepo)
2023/06/13 13:44:14 | stdout | 2023/06/13 03:44:14 [6487e60e-2] router: completed GET / for 192.168.1.1:0, 200 OK in 91.5ms @ web/home.go:32(web.Home)
2023/06/13 13:44:14 | stdout | 2023/06/13 03:44:14 [6487e60e] router: completed GET /user/events for 192.168.1.1:0, 200 OK in 559.8ms @ events/events.go:18(events.Events)
2023/06/13 13:44:13 | stdout | 2023/06/13 03:44:13 [6487e60d-2] router: completed GET /issues for 192.168.1.1:0, 200 OK in 42.5ms @ user/home.go:308(user.Issues)
2023/06/13 13:44:13 | stdout | 2023/06/13 03:44:13 [6487e60d] router: completed GET /user/events for 192.168.1.1:0, 200 OK in 572.3ms @ events/events.go:18(events.Events)
2023/06/13 13:44:12 | stdout | 2023/06/13 03:44:12 [6487e60c-2] router: completed GET /milestones for 192.168.1.1:0, 200 OK in 29.0ms @ user/home.go:121(user.Milestones)
2023/06/13 13:44:12 | stdout | 2023/06/13 03:44:12 [6487e60c] router: completed GET /user/events for 192.168.1.1:0, 200 OK in 525.7ms @ events/events.go:18(events.Events)
2023/06/13 13:44:12 | stdout | 2023/06/13 03:44:12 [6487e60b] router: completed GET /pulls for 192.168.1.1:0, 200 OK in 49.5ms @ user/home.go:294(user.Pulls)
2023/06/13 13:44:11 | stdout | 2023/06/13 03:44:11 [6487e609] router: completed GET /user/events for 192.168.1.1:0, 200 OK in 2918.8ms @ events/events.go:18(events.Events)
2023/06/13 13:44:08 | stdout | 2023/06/13 03:44:08 [6487e608-4] router: completed GET /repo/search?sort=updated&order=desc&uid=4&team_id=0&q=&page=1&limit=15&mode=&archived=false for 192.168.1.1:0, 200 OK in 12.5ms @ repo/repo.go:472(repo.SearchRepo)
2023/06/13 13:44:08 | stdout | 2023/06/13 03:44:08 [6487e608-3] router: completed GET /repo/search?count_only=1&uid=4&team_id=0&q=&page=1&mode= for 192.168.1.1:0, 0  in 14.0ms @ repo/repo.go:472(repo.SearchRepo)
2023/06/13 13:44:08 | stdout | 2023/06/13 03:44:08 [6487e608-2] router: completed GET / for 192.168.1.1:0, 200 OK in 87.4ms @ web/home.go:32(web.Home)
2023/06/13 13:44:08 | stdout | 2023/06/13 03:44:08 [6487e608] router: completed POST /user/login for 192.168.1.1:0, 303 See Other in 184.9ms @ auth/auth.go:170(auth.SignInPost)
2023/06/13 13:44:05 | stdout | 2023/06/13 03:44:05 [6487e605] router: completed GET /user/login?redirect_to=%2f for 192.168.1.1:0, 200 OK in 5.0ms @ auth/auth.go:141(auth.SignIn)
2023/06/13 13:44:04 | stdout | 2023/06/13 03:44:04 [6487e604-5] router: completed GET / for 192.168.1.1:0, 200 OK in 3.3ms @ web/home.go:32(web.Home)
2023/06/13 13:44:04 | stdout | 2023/06/13 03:44:04 [6487e604-4] router: completed GET /user/login for 192.168.1.1:0, 200 OK in 6.5ms @ auth/auth.go:141(auth.SignIn)
2023/06/13 13:44:04 | stdout | 2023/06/13 03:44:04 [6487e604-2] router: completed GET / for 192.168.1.1:0, 200 OK in 4.1ms @ web/home.go:32(web.Home)
2023/06/13 13:44:04 | stdout | 2023/06/13 03:44:04 [6487e604-3] router: completed GET /user/settings/keys for 192.168.1.1:0, 303 See Other in 0.5ms @ context/auth.go:27(context.Toggle)
2023/06/13 13:44:04 | stdout | 2023/06/13 03:44:04 [6487e601-2] router: completed GET /user/events for 192.168.1.1:0, 200 OK in 2614.1ms @ events/events.go:18(events.Events)
2023/06/13 13:44:04 | stdout | 2023/06/13 03:44:04 [6487e604] router: completed POST /user/logout for 192.168.1.1:0, 303 See Other in 3.4ms @ auth/auth.go:379(auth.SignOut)
2023/06/13 13:44:01 | stdout | 2023/06/13 03:44:01 [6487e601] router: completed GET /user/settings/keys for 192.168.1.1:0, 200 OK in 38.1ms @ setting/keys.go:25(setting.Keys)
2023/06/13 13:44:01 | stdout | 2023/06/13 03:44:01 [6487e600-2] router: completed GET /user/events for 192.168.1.1:0, 200 OK in 1116.4ms @ events/events.go:18(events.Events)
2023/06/13 13:44:00 | stdout | 2023/06/13 03:44:00 [6487e600] router: completed GET /user/settings for 192.168.1.1:0, 200 OK in 10.2ms @ setting/profile.go:44(setting.Profile)
2023/06/13 13:43:59 | stdout | 2023/06/13 03:43:59 [6487e5f5-3] router: completed GET /user/events for 192.168.1.1:0, 200 OK in 10793.8ms @ events/events.go:18(events.Events)
2023/06/13 13:43:53 | stdout | 2023/06/13 03:43:53 [6487e2ed] router: polling   GET /user/events for 192.168.1.1:0, elapsed 3968.6ms @ events/events.go:18(events.Events)
2023/06/13 13:43:49 | stdout | 2023/06/13 03:43:49 [6487e5f5] router: completed GET /Tekra/Tekra-Airflow.rss for 192.168.1.1:0, 404 Not Found in 7.7ms @ context/repo.go:429(context.RepoAssignment)
2023/06/13 13:43:49 | stdout | 2023/06/13 03:43:49 [6487e5f5-2] router: completed GET /Tekra/Tekra-Airflow.atom for 192.168.1.1:0, 404 Not Found in 5.1ms @ context/repo.go:429(context.RepoAssignment)
2023/06/13 13:43:48 | stdout | 2023/06/13 03:43:48 [6487e5f4] router: completed GET /Tekra/Tekra-Airflow for 192.168.1.1:0, 200 OK in 113.3ms @ repo/view.go:703(repo.Home)
2023/06/13 13:43:48 | stdout | 2023/06/13 03:43:48 [6487e5f2-2] router: completed GET /user/events for 192.168.1.1:0, 200 OK in 2587.9ms @ events/events.go:18(events.Events)
2023/06/13 13:43:46 | stdout | 2023/06/13 03:43:46 [6487e5f2] router: completed GET /repo/search?sort=updated&order=desc&uid=1&team_id=0&q=&page=1&limit=15&mode=&archived=false for 192.168.1.1:0, 200 OK in 15.9ms @ repo/repo.go:472(repo.SearchRepo)
2023/06/13 13:43:45 | stdout | 2023/06/13 03:43:45 [6487e5f1-4] router: completed GET /repo/search?count_only=1&uid=1&team_id=0&q=&page=1&mode= for 192.168.1.1:0, 0  in 18.7ms @ repo/repo.go:472(repo.SearchRepo)
2023/06/13 13:43:45 | stdout | 2023/06/13 03:43:45 [6487e5f1-3] router: completed GET /avatar/95632599eddc423388acd18e20a05cba?size=84 for 192.168.1.1:0, 303 See Other in 15.9ms @ user/avatar.go:48(user.AvatarByEmailHash)
2023/06/13 13:43:45 | stdout | 2023/06/13 03:43:45 [6487e5f1-2] router: completed GET /avatar/95632599eddc423388acd18e20a05cba?size=72 for 192.168.1.1:0, 303 See Other in 15.6ms @ user/avatar.go:48(user.AvatarByEmailHash)
2023/06/13 13:43:45 | stdout | 2023/06/13 03:43:45 [6487e5f1] router: completed GET / for 192.168.1.1:0, 200 OK in 108.7ms @ web/home.go:32(web.Home)


</body>
</html>

**Comment by wxiaoguang** [comment] 2023-06-13 03:55
If you add the key to your GitHub account, does your "git clone ssh://" work?

**Comment by martintalero** [comment] 2023-06-13 03:57
How do I add the key?

**Comment by wxiaoguang** [comment] 2023-06-13 03:59
Create a test github repo, and add your SSH key to https://github.com/settings/keys to test whether your "git clone" really works. Just like what you did in Gitea.

**Comment by martintalero** [comment] 2023-06-13 04:00
Let me try and report back.

**Comment by martintalero** [comment] 2023-06-13 04:05
![image](https://github.com/go-gitea/gitea/assets/68879161/34531016-4c37-40f2-b2bc-14ba5e93d484)

**Comment by martintalero** [comment] 2023-06-13 04:05
Same issue.

**Comment by wxiaoguang** [comment] 2023-06-13 04:06
So .... you need to check you SSH key first. It's quite unlikely related to Gitea.

Maybe you can try to re-generate or try to use RSA 4096.

**Comment by martintalero** [comment] 2023-06-13 04:07
Let me regenerate, please.

**Comment by martintalero** [comment] 2023-06-13 04:22
Same issue. When I run ssh -vvv git@github.com  git-receive-pack martintalero/test_repo.git it works. But when I run clone it doesn't.

**Comment by wxiaoguang** [comment] 2023-06-13 04:22
Then you need to check you git + ssh system.

**Comment by wolfogre** [comment] 2023-06-13 05:27
Have you set up a different SSH command for Git? You can check it by

```bash
git config --get core.sshCommand
echo $GIT_SSH_COMMAND
```

**Comment by martintalero** [comment] 2023-06-13 22:27
Am I doing this wrong?
![image](https://github.com/go-gitea/gitea/assets/68879161/6675b9b2-5b65-4bb9-87e5-105b09d389b2)

**Comment by martintalero** [comment] 2023-06-13 22:29
I have noticed that when using git bash the results are different than from using cmd in windows. With git bash I am able to clone repository but with cmd I am unable. Furthermore, I am trying to clone the repository from Pycharm but it fails as if I was issuing the clone command from cmd in windows.

**Comment by XeonG** [comment] 2023-06-13 23:51
Having the same problem and its driving me nuts trying to get server on ubuntu with gitea setup and using windows to clone ssh ... can't http as that breaks trying to push a large repo (6gb -not large to me) but the only thing that uploaded properly were the LFS files while it gave an error I don't have now, but kept failing to send seems to be a known git issue..  so now I'm wanting to see if it will transfer with ssh better...

but trying to get ssh to work with gitea is proving to be insane.. and I can't help but think that its broken

**Comment by jonhadfield** [comment] 2023-06-23 16:59
I had the same issue (SSH fine but clone failing with same error as above) and eventually found that I'd not set: LOCAL_ROOT_URL. Turns out an internal API call is made using that as a prefix to determine access to the repo.   
I was tempted to create a PR to improve the error handling as the log error is very generic.

**Comment by lunny** [comment] 2023-06-24 02:22
ref from the documentation:

```
LOCAL_ROOT_URL: %(PROTOCOL)s://%(HTTP_ADDR)s:%(HTTP_PORT)s/: Local (DMZ) URL for Gitea workers (such as SSH update) accessing web service. In most cases you do not need to change the default value. Alter it only if your SSH server node is not the same as HTTP node. Do not set this variable if PROTOCOL is set to http+unix.
```

**Comment by lunny** [comment] 2023-06-24 02:36
> Thanks lunny. I saw that, but it doesn't indicate that it is related to this problem - that ssh works, but git clone fails. I also saw you improved it in the latest dev milestone.
> 
> Do you think it could be related?

I don't know maybe you can run `ssh -vvv` to test whether it's a auth

> Thanks lunny. I saw that, but it doesn't indicate that it is related to this problem - that ssh works, but git clone fails. I also saw you improved it in the latest dev milestone.
> 
> Do you think it could be related?

I don't think so. I mention that because the LOCAL_ROOT_URL should be accessed by `openssh` and `gitea serv` and other sub commands.

**Comment by wxiaoguang** [comment] 2023-06-24 02:39
IMO there are different problems in this issue:

* for martintalero (the author): their keys don't work, they can't work from GitHub either, not Gitea's problem.
* for jonhadfield , it's caused by incorrect LOCAL_ROOT_URL in config.
* for lonix1 , it might be caused by incorrect START_SSH_SERVER in config (I guess)

So, to keep things clear, do not mix different problems ..... I will close this issue soon because too many voices in it now.

For problem 2 and 3, if the users just use default installation config and do not change anything, the SSH should work out-of-box. But, if you decide to change any config option, then you should know what the config option affects

**Closed as completed** 2023-06-24 02:49 UTC
Labels: issue/needs-feedback
