### ISSUE TITLE
Working folder for windows service

### ISSUE THREAD

**Issue by udoliess** [go-gitea/gitea#2795] opened 2017-10-27 14:07 UTC
- Gitea version (or commit ref): 1.2.2
- Git version: 2.14.3.windows.1
- Operating system: Win7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Following the installation instructions I tried to setup Gitea as windows service. But at least two directories are created in System32 folder: "data" and "indexers". Setting the enviroment variable GITEA_WORK_DIR did not help.
(How else can I set the working folder for Gitea service? I would prefer a command line parameter but other solutions are welcome.)

## Screenshots

---
Thanks,
Udo

**Comment by cez81** [comment] 2017-10-31 09:08
I think this https://github.com/go-gitea/gitea/pull/2192 will fix this bug.

Duplicate of https://github.com/go-gitea/gitea/issues/2159

**Closed as completed** 2017-10-31 09:28 UTC
Labels: issue/duplicate
