### ISSUE TITLE
Update go-macaron/cache and go-macaron/session

### ISSUE THREAD

**Issue by tamalsaha** [go-gitea/gitea#7670] opened 2019-07-30 02:57 UTC
I would like to update the go-macaron/cache and go-macaron/session packages to use the latest version of go-redis client. The latest client has support for Redis cluster. I opened prs against the macaron repos for 2 months which have not been merged.

- https://github.com/go-macaron/cache/pull/12
- https://github.com/go-macaron/session/pull/28

How can gitea use my updated version of the macaron libraries?

**Comment by techknowlogick** [comment] 2019-07-30 15:52
There has been some discussion on switching away from macaron due to several issues, one of which you mentioned (pending PRs not being merged for >2mos). The issue is #7403. 

I think while we work on the above, we may need to fork macaron in the interim so we can add fixes, such as the ones above. Maybe we create a new org on gitea.com (we'd need to rename macaron to something else) with the macaron repos in it that Gitea project can maintain itself.

@lunny @zeripath thoughts?

**Comment by lunny** [comment] 2019-07-30 15:56
I suggest we convert to gin web framework and we can maintain some gin's middlewares. I think we can do something on v1.10 and v1.11

**Comment by techknowlogick** [comment] 2019-07-30 16:04
I like gin, but that will take time to convert. I think short-term fork of macaron would be good while we wait for #7403

**Comment by lunny** [comment] 2019-07-30 23:45
For a short-term target, I like your idea to create a new org in gitea.com to fork macaron's repositories.

**Comment by tamalsaha** [comment] 2019-07-31 01:35
I also agree with maintaining forked repos for now.

**Comment by lunny** [comment] 2019-07-31 01:51
I have created fork organization https://gitea.com/macaron and I think we can move some gitea internal middlewares to that organization

**Comment by tamalsaha** [comment] 2019-08-01 19:53
@techknowlogick / @lunny / @zeripath , it seems that the following macaron repos a should be forked also, since the main macaron repo has been forked.

- github.com/go-macaron/binding
- github.com/go-macaron/cors
- github.com/go-macaron/i18n
- github.com/go-macaron/inject
- github.com/go-macaron/toolbox

**Comment by lunny** [comment] 2019-08-02 15:02
All above forked, but need PRs.

**Comment by tamalsaha** [comment] 2019-08-02 17:53
@lunny , can you please add drone for the repos? I can send pr for the go.mod stuff.

**Comment by lunny** [comment] 2019-08-03 02:06
@tamalsaha all drone added.

**Closed as completed** 2019-08-23 16:40 UTC
