### ISSUE TITLE
Toolbar notifications for issues, PRs

### ISSUE THREAD

**Issue by give-me-my-toblerone** [go-gitea/gitea#279] opened 2016-11-27 11:29 UTC
Labels in my toolbar where it shows is I have new requests or comments or messages or anything new worth of my attention

**Comment by andreynering** [comment] 2016-11-27 12:24
Closing as duplicate of #145

Feel free to comment there if there's anything worth adding.

**Closed as completed by andreynering** 2016-11-27 12:24 UTC
Labels: issue/duplicate
