### ISSUE TITLE
Issue count not decreasing when issue closed via `git push` and using 'Fix #$ISSUE_NUMBER' as commit message

### ISSUE THREAD

**Issue by 4oo4** [go-gitea/gitea#11786] opened 2020-06-07 00:52 UTC
- Gitea version (or commit ref): 1.11.6
- Git version: 2.27.0
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes
    - https://try.gitea.io/4oo4/test-repo/issues
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
I have noticed an issue where if you push a commit with the commit message as 'Fix #1' (or whatever issue number), the issue is closed but it does not decrement the number of open issues. However if I reopen and reclose one of these issues, that decrements the count like expected.

## Screenshots
![Selection_012](https://user-images.githubusercontent.com/15698835/83957589-96dee580-a858-11ea-93c7-7032dec00941.png)

**Comment by JustAnotherArchivist** [comment] 2020-06-08 01:36
Duplicate of #10536

**Closed as completed** 2020-06-08 03:03 UTC
Labels: issue/duplicate
