### ISSUE TITLE
Docker image has no git-lfs path, and adding one will lead to an error without manual intervention

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#1717] opened 2017-05-13 14:59 UTC
- Gitea version (or commit ref): latest docker image
- Git version: latest docker image
- Operating system: Ubuntu 17.04 (Host) / latest docker image
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
The default install when launching the docker image has an empty path for LFS (why?).
If I add `/data/git-lfs` which is inside the docker volume, I get this:

`
invalid_lfs_path%!(EXTRA *os.PathError=mkdir /data/git-lfs/: permission denied)
`

If the docker image has no permissions to add paths, then I suggest there should be one preconfigured that actually works. (otherwise, at this point the user will be confused and/or required to manually open up a shell in the container to create a path for LFS storage which is a bit annoying)

## Screenshots

**If this issue involves the Web Interface, please include a screenshot**

**Comment by evilstiefel** [comment] 2017-05-16 10:31
This is a duplicate of #1221

**Closed as completed** 2017-05-17 08:31 UTC
Labels: issue/duplicate
