### ISSUE TITLE
Adding issue dependencies is defunct in 1.6.0

### ISSUE THREAD

**Issue by tinxx** [go-gitea/gitea#5483] opened 2018-12-06 16:02 UTC
- Gitea version (or commit ref):
- Git version: 1.6.0
- Operating system: Debian Buster
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Can you confirm that adding dependencies is broken in Gitea version 1.6.0?

When trying to add a dependent issue to another issue I always get the result:

> No results found.

I get the following message when I try adding a dependency by it's id (`11` or `#11`). 

> Dependent issue does not exist.

## Screenshots

![screenshot from 2018-12-06 16-58-01](https://user-images.githubusercontent.com/13608545/49595634-b7cf2d80-f978-11e8-9d8a-18685fe63b97.png)
![screenshot from 2018-12-06 16-58-10](https://user-images.githubusercontent.com/13608545/49595638-b7cf2d80-f978-11e8-9b18-68a7862310fe.png)

**Comment by Akcaxup** [comment] 2018-12-08 13:16
On PostgreSQL also
![2580 _cr](https://user-images.githubusercontent.com/32159064/49686376-9a2ecf00-fb04-11e8-927e-3a9ff5483b12.png)

**Comment by markusamshove** [comment] 2018-12-08 13:53
Thie is a duplicate of #5389

**Comment by lunny** [comment] 2018-12-08 14:04
@tinxx please confirm https://github.com/go-gitea/gitea/pull/5392 fix this.

**Comment by tinxx** [comment] 2018-12-08 14:14
I can confirm that it is the same API error on my instance. I am not a Gitea developer though and cannot confirm if the patch solves the issue.

**Comment by markusamshove** [comment] 2018-12-08 19:51
My workaround (which should be able to confirm if it is the same issue), which I'm not sure if it is recommended, is to create a file called `sidebar.tmpl` in `custom/templates/repo/issue/view_content` with this [content](https://gist.github.com/MarkusAmshove/f66652074b44e3c8d6bf7710f0d858f4).

The workaround is in this [line](https://gist.github.com/MarkusAmshove/f66652074b44e3c8d6bf7710f0d858f4#file-sidebar-tmpl-L342).

Note that it is not quite the same change as in the PR, because I didn't also want to change the JS file.
I've added a `/` at the start to emulate the change in JS and changed `RepoLink` to `RepoRelPath`

If you look at the [diff](https://github.com/go-gitea/gitea/pull/5392/files) in the PR it shows the leading `/` in JS and change to `RepoRelPath` in the template.

**Closed as completed** 2018-12-09 01:03 UTC
Labels: type/bug, issue/duplicate

**Comment by tinxx** [comment] 2018-12-09 09:54
I reviewed the differences between your version and [1.6.0 version](https://raw.githubusercontent.com/go-gitea/gitea/release/v1.6/templates/repo/issue/view_content/sidebar.tmpl) and found that only the `/` was added (next to format changes).

Adding the slash really fixed the problem for me. There are, however, strange layout glitches:
![screenshot from 2018-12-09 10-44-41](https://user-images.githubusercontent.com/13608545/49695789-55587600-fba0-11e8-8ac6-b0243f74cc65.png)

What's more, I tried adding `#31` as dep for `#32` but the menu only allowed me to add `#32` itself: Whenever I type `#31` into the dependencies filter / search field of ticket `#32`, it displays only `#32`. :confused:
