### ISSUE TITLE
Pull request link in organization project is broken

### ISSUE THREAD

**Issue by PaulBol** [go-gitea/gitea#25971] opened 2023-07-18 19:14 UTC
### Description

I have set up a project for the organization that's accessible at a URL like https://gitea.myorg.com/myorg/-/projects/1.

The boards show issues with links to pull request, if applicable.

These links have the form https://gitea.myorg.com/pulls/456 and don't work. The correct link would be https://gitea.myorg.com/myorg/repo1/pulls/456

I am not able to reproduce the issue on try.gitea.io because I can't set up an organization.

### Gitea Version

1.20.0

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![grafik](https://github.com/go-gitea/gitea/assets/38468549/c144b200-ad3b-4dba-a697-2060a86128f9)

Highlighted link goes to https://gitea.myorg.com/pulls/456 (status 404 page) instead of https://gitea.myorg.com/myorg/repo1/pulls/456

### Operating System

Linux

### How are you running Gitea?

Official build running with systemd. I doubt that this matters of the link, though.

### Database

MySQL

**Comment by delvh** [comment] 2023-07-18 19:16
Duplicate of both #25954 and #23318.

**Closed as completed by delvh** 2023-07-18 19:16 UTC
Labels: type/bug
