### ISSUE TITLE
Email Notifications - Assign User to Issue

### ISSUE THREAD

**Issue by HerrHase** [go-gitea/gitea#2141] opened 2017-07-11 10:38 UTC
- Gitea version (or commit ref): 1.1.2
- Git version: 2.7.4
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
I'm not sure if this a Bug or it is simply not implemented, if i change the assign of a issue, users getting no email notifications, and also no other notifications. For Reviewing Bugs or Features it is a little bit annoying ;-)

The Mailer is running and throws no bugs, so sending Emails is not a Problem. And the users are all Watching the Repo.

**Comment by gruo** [comment] 2019-02-28 13:09
Same here, but:
1. i am not watching the respository
2. another user assigns an issue to me
3. i get no notification about that

Is this intended behaviour? For us it would be better when user notifications get fired if

- user is assigned to issue/PR
- user is mentioned in comment with @gruo

and he is not watching the repository.

**Comment by mrsdizzie** [comment] 2020-09-07 15:19
We send notifications on user assignment now

**Closed as completed by mrsdizzie** 2020-09-07 15:19 UTC
Labels: type/proposal

**Comment by pmusa** [comment] 2020-10-20 11:07
> We send notifications on user assignment now

Sorry, to highjack the closed issue, but how did you manage to do that?
