### ISSUE TITLE
Branches page still shows no. of commits ahead after merging to master branch

### ISSUE THREAD

**Issue by RichardBrookhuis** [go-gitea/gitea#31472] opened 2024-06-24 08:56 UTC
### Description

After upgrading from 1.21 to 1.22 I noticed the branches page shows merged branches with the same number of commits ahead as before merging. See screenshot for an example.
Step to reproduce: create a PR, merge it. Branches page will show the branch is merged, but the number of commits ahead is not 0.

### Gitea Version

1.22

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![afbeelding](https://github.com/go-gitea/gitea/assets/44212254/3048c033-694b-4615-a69b-ae3c9dcda81a)

### Git Version

2.39.2

### Operating System

Windows

### How are you running Gitea?

gitea-1.22.0-gogit-windows-4.0-amd64.exe, downloaded from dl.gitea.com, running as a windows service.

### Database

SQLite

**Comment by greuelpirat** [comment] 2024-07-03 08:52
I also noticed that when I merge a branch outside of Gitea into the default branch and push it to gitea, the branch is not marked as _Included_ in the branch overview. This seems to be the same issue.

**Comment by RichardBrookhuis** [comment] 2024-07-08 09:59
I just upgraded to 1.22.1, this seems to be fixed now

**Comment by RichardBrookhuis** [comment] 2024-07-08 14:12
Unfortunately, after merging a PR, the problem is back again...
![afbeelding](https://github.com/go-gitea/gitea/assets/44212254/0c6b2f4e-6f8b-4a48-837c-07122455d024)

**Comment by lunny** [comment] 2024-07-11 17:48
This should be caused by #29577

**Comment by RichardBrookhuis** [comment] 2024-07-12 08:05
So I guess the cache should be invalidated after merging?

**Comment by lunny** [comment] 2024-07-14 18:23
> So I guess the cache should be invalidated after merging?

Yes. I will send a PR to fix it.

**Comment by Zettat123** [comment] 2024-07-22 01:57
Closed by #31659

**Closed as completed by Zettat123** 2024-07-22 01:57 UTC
Labels: type/bug
