### ISSUE TITLE
Changing branch does not update files view

### ISSUE THREAD

**Issue by mqudsi** [go-gitea/gitea#3185] opened 2017-12-13 15:50 UTC
- Gitea version (or commit ref): 1.1.0+885-g9f033bf2
- Git version: n/a
- Operating system: FreeBSD
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes: https://try.gitea.io/mqudsi/futuretest/
  - [ ] No
  - [ ] Not relevant
- Log gist: ??

## Description
Changing the viewed branch to another updates the "last commit" snippet for the repository, but the file view and the "last changed in commit" information persists from `master`.

e.g.

https://try.gitea.io/mqudsi/futuretest/src/branch/rust-%2346606 and https://try.gitea.io/mqudsi/futuretest/src/branch/master both show the same files and file history in the file summary, but if you compare the actual files at each branch, you'll see they are different and have different "last commits": https://try.gitea.io/mqudsi/futuretest/src/branch/master/cargo.out vs https://try.gitea.io/mqudsi/futuretest/src/branch/rust-%2346606/cargo.out

**Comment by ethantkoenig** [comment] 2017-12-15 18:51
Seems related to, maybe even a duplicate of, #3202.

**Comment by lunny** [comment] 2018-12-09 13:11
Since #3202 closed by #3240, I will close this one. Please feel free to reopen it.

**Closed as completed by lunny** 2018-12-09 13:11 UTC
Labels: type/bug
