### ISSUE TITLE
Using external issue tracker causes errors in pull request page

### ISSUE THREAD

**Issue by webjoel** [go-gitea/gitea#2668] opened 2017-10-06 18:04 UTC
- Gitea version (or commit ref): ffab139
- Git version: 2.7.4
- Operating system: Linux Ubuntu 16.04
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL): https://try.gitea.io/webjoel/teste/pulls/3
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When enabled external tracker issue in the repository settings (Settings > Options> Advanced Settings > Use external issue tracker) in the pull request it is no longer possible to comment, start time tracker and add time tracker, error page 404 is returned.

In my opinion, using external or internal issue tracker should not be related to the functionality of the pull request, the comment part is undisputed, in the case of the time tracker I may want to record activities in the pull request with no relation to an issue, just record of the work itself. However if this is not accepted, at least the time tracker options in the pull request should be hidden as well as enabled external tracker issue.

**Comment by lafriks** [comment] 2017-10-06 18:12
Duplicate of #2441

**Closed as completed by lafriks** 2017-10-06 18:12 UTC
Labels: issue/duplicate

**Comment by lafriks** [comment] 2017-10-06 18:26
Duplicate of #2447
