### ISSUE TITLE
Plantuml highlighting doesn't work anymore

### ISSUE THREAD

**Issue by Sepphod** [go-gitea/gitea#14219] opened 2021-01-02 16:53 UTC
I updated recently to 1.13.1. I am not sure if either the issue existed already in 1.13.0 as I discovered it by coincidence with 1.13.1. But I am pretty sure with 1.12.6 everything was working.

My gitea uses an external plantuml server to render plantuml code blocks within markdown files. Now it doesn't anymore. I have seen that the names of the html classes with the rendered plantuml code was changed from "language-plantuml" to "chroma language plantuml". I changed this in the javascript (example from gitea customize page). Even I escaped it. It doesn't work. But I detected in the javascript console in the safari that the custom javascript is not called anymore. Could it be that with the changing to server side highlighting this feature was removed? I have seen in the discourse a similar issue with ASCIDOC. 

Otherwise I am open to any other proposals. Or I have to switch back to 1.12.6. 
thx

**Comment by zeripath** [comment] 2021-01-02 17:45
I have a feeling that this would be easier to solve on #configuration on Discord following which we could update the webpage

**Comment by Sepphod** [comment] 2021-01-02 17:47
I don't understand this feeling. Is it a bug? or must the configuration be adapted?

**Comment by zeripath** [comment] 2021-01-02 17:54
It's very likely a configuration issue. One which will require live debugging. 

Once it's fixed we can come back here and suggest updates to the docs as necessary.

**Comment by Sepphod** [comment] 2021-01-02 18:00
why are you assuming that it is an configuration issue? I mean it was working. And it was working very well. Or do you mean the configuration be updated due to the new feature of the server-side highlighting? 
I mean it seems for me that the rendering isn't called anymore due to the enabling of the mermaid -stuff. Which is BTW working like hell for me. Seems like the client-side highlighting was disabled at all. OK I will check the PR for that. But I won't spend much effort. Otherwise I will go back to 1.12.6

**Comment by zeripath** [comment] 2021-01-02 18:19
Just come to discord - it'll be easier to work this out there

**Comment by lunny** [comment] 2021-01-03 02:51
Maybe related with #12047 ?

**Comment by Sepphod** [comment] 2021-01-03 08:23
thnx that was the merge I was looking for. And now I remember I skipped 1.13.0 as I never trust a zeroed version. And I remember that a friend of mine mentioned something like the plantuml is suddenly not working anymore.

**Comment by Sepphod** [comment] 2021-01-03 16:02
Ok somewhere here https://github.com/ydelafollye/gitea/commit/845b9f1dc48c71bbcf4891267dc973066bf04d55 it should be happened. the change to chroma IMO seems fine. For me it is weird that the footer.tmpl won't be added anyhow. So the js-function to establish the communication with the external plantuml server won't work - even if I added the "chroma " to the call. 
https://github.com/go-gitea/gitea/issues/9553 is open anyway
I will roll back to 1.12.6 as my plantuml sketches are not rendered anymore :(

**Comment by zeripath** [comment] 2021-01-03 19:16
dude seriously I asked you to come to discord so we could work out how to fix this.

**Comment by Sepphod** [comment] 2021-01-03 19:22
Yeah we could do this - Otherwise it seems I will be doomed. 
But I roll back anyhow. BTW I already did it. And for what do you need me? IMO you should add some plantuml example in a markdown file and let it render in a test gitea. You may debug it.

**Comment by Sepphod** [comment] 2021-01-04 05:52
OK roll back doesn't seem to be the best way as `Downgrading database version from '156' to '141' is not supported and may result in loss of data integrity.` :(

**Comment by lunny** [comment] 2021-01-04 06:10
You have to change the version on database manually.

**Comment by Sepphod** [comment] 2021-01-04 06:36
Yes I habe read ist too thx. But I saw that the issue may be fixed. So I will wart for a while

**Comment by 6543** [comment] 2021-01-23 12:50
@Sepphod can you provide some files to test agains?

just create a repo on https://try.gitea.io/

**Comment by Sepphod** [comment] 2021-01-23 17:51
check https://try.gitea.io/sepphod/plantumltest/src/branch/master/README.md => seems not working for me. but maybe I did something wrong

**Comment by 6543** [comment] 2021-01-23 18:36
@Sepphod it works if you use `cmd` or something supported ... -> https://github.com/go-gitea/gitea/pull/14222#issuecomment-766157872

**Comment by 6543** [comment] 2021-01-23 18:41
@Sepphod upstream issue: https://github.com/alecthomas/chroma/issues/443

**Comment by Sepphod** [comment] 2021-01-23 19:47
sorry I don't understand your comment. I used it the same way it was working before. If this won't work I have to rework several markdown files in my repos.

**Comment by 6543** [comment] 2021-01-23 19:50
@Sepphod we migrated to a new syntax-highlighter (chroma) witch do not support PlantUML yet ... so I created an issue on there project ...

**Comment by Sepphod** [comment] 2021-01-23 19:53
yeah I created the ticket for ;) but I wrongly assumed it is already fixed. But you just wanted some test files - my mistake ;)

**Comment by alecthomas** [comment] 2021-01-23 20:26
Unless I misunderstand the goal here, this is out of scope for Chroma. What @Sepphod is asking for is for a PlantUML _renderer_ that will take PlantUML blocks and render UML in their place. Even if Chroma adds support for it it won't do this.

It sounds like Gitea used to support custom block renderers through some plugin system, but no longer does. That regression is unrelated to Chroma.

**Comment by Sepphod** [comment] 2021-01-23 20:30
OK - with Gitea < 1.13.1 it was possible to do client-side rendering. the MD parser detected the keyword "plantuml" and created a HTML class with the type of plantuml. an embedded java script was called which transmit all plantuml data to a given plantuml server - which renders an image and send it back... that's all

**Comment by 6543** [comment] 2021-01-23 21:07
Yes looks like I mussunderstood it ... :/

I know we have [mermaid-js](https://mermaid-js.github.io/mermaid/) integration ... how did PlantUML integration worked on your side before, I'm not aware we officialy did add support for it? @Sepphod

**Comment by Sepphod** [comment] 2021-01-29 10:11
I Dont know if i like your proposal. Everything was working before. Why this decision with that mermaid stuff?
plantuml is widely used...
and there was a PR  some weeks ago: https://github.com/go-gitea/gitea/pull/14222 what will happen with that one?

**Comment by lunny** [comment] 2021-01-29 15:16
@Sepphod #14222 doesn't finished there are some bugs. I think I will continue that work.

**Comment by zeripath** [comment] 2021-06-23 19:26
Sorry peeps - I think I've finally worked this out.

You should change the languages that you're looking for.

`` ```cmd ``  will be detected and rendered as cmd language so - what I would recommend is that you use `` ```plantuml-cmd `` instead and change your code to make that work.

An alternative fix would be for us to include the raw unrendered text within a hidden `<pre><code>` element.

**Closed as completed** 2021-06-23 20:45 UTC
Labels: type/bug, type/upstream
