### ISSUE TITLE
The repository names listing at home page is empty by default  after upgrading to 1.12.6. 

### ISSUE THREAD

**Issue by biju-ps** [go-gitea/gitea#13843] opened 2020-12-04 07:17 UTC
- Gitea version :1.12.6 
- Git version: 2.17
- Operating system: Ubuntu 18.04

- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:
## Description
The repository names listing is empty by default  after upgrading to 1.12.6. 
The List will populate once you play around with the filter option. 
FYI *All my repositories are private*
Screen capture attached
...

## Screenshots

![gitea_issue3](https://user-images.githubusercontent.com/2868701/101133382-a59f2d00-362e-11eb-9475-640c2f89ffe1.gif)

**Comment by francois-artwai** [comment] 2021-02-26 13:40
Similar problem for me with Gitea 1.12.6 on Debian 4.9 and Git 2.11.

All repositories are private.
Only the ones I created after the upgrade appear.

To display all non-archived repositories, I have to check both boxes (archived and private).
But it also displays the archived repositories which does not interest me.

Especially since the order of display is according to the date of last operation and the last operation performed is an archiving, so they appear first .

**Comment by zeripath** [comment] 2021-02-26 15:12
I suspect that this is a duplicate of another already solved issues and due to is_archived fields being NULL. I'm not certain how this has happened as it should not and won't happen in future.

Run:

```go
gitea doctor --run check-db-consistency
```

To check what is inconsistent

and

```go
gitea doctor --run check-db-consistency --fix
```

to fix them.

**Comment by francois-artwai** [comment] 2021-03-01 10:52
> I suspect that this is a duplicate of another already solved issues and due to is_archived fields being NULL. I'm not certain how this has happened as it should not and won't happen in future.
> 
> Run:
> 
> ```go
> gitea doctor --run check-db-consistency
> ```
> 
> To check what is inconsistent
> 
> and
> 
> ```go
> gitea doctor --run check-db-consistency --fix
> ```
> 
> to fix them.

Thanks but nothing's returned from `gitea doctor --run check-db-consistency`

**Comment by zeripath** [comment] 2021-03-01 11:57
You need to run the doctor command with the appropriate environment and flags for your system. That is, you are likely to need to set  `-c` for the path to the config file etc.

You could also check your db to see if the is_archived field in the repository table contains any nulls? It should not and they should all be false or true. (with true/false mapped appropriately for your db.)

If you are running 1.12.6 I recommend you upgrade to 1.13.2 in any case.

**Closed as completed** 2022-04-13 03:42 UTC
