### ISSUE TITLE
Gitea crash when indexer is run (database error, data too long for column language)

### ISSUE THREAD

**Issue by furai** [go-gitea/gitea#13013] opened 2020-10-02 07:27 UTC
- Gitea version (or commit ref): Gitea version 1.12.5 built with GNU Make 4.1, go1.14.9 : bindata, sqlite, sqlite_unlock_notify
- Git version: 2.28.0
- Operating system: Ubuntu 18.04.5 LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:
```
./gitea.log:2562:2020/10/02 09:12:07 ...dexer/stats/queue.go:24:handle() [E] stats queue indexer.Index(24) failed: Error 1406: Data too long for column 'language' at row 1
```

## Description
I've upgraded Gitea today the usual way by stopping the service, replacing binary and starting the service again. (From 1.12.4 to 1.12.5)

Gitea crashes when indexer runs. I have no idea why this happened. Maybe failed database migration on my end? That's the only relevant log I could find above.

I've disabled repo indexer and things started working again.

**Comment by zeripath** [comment] 2020-10-02 11:17
This is a duplicate of #12379

You will need to run the following SQL on the database: 

```sql
ALTER TABLE language_stat MODIFY COLUMN language VARCHAR(50)
```

This is fixed in 1.13 with a migration using #12396, (with additional fixes in #12427, #12445) but migrations are not backportable.

**Comment by lunny** [comment] 2020-10-02 12:25
Maybe we could add a doctor or fix sub command `gitea doctor fix 12379` which is backportable.

**Comment by lunny** [comment] 2021-01-06 04:20
closed as duplicated.

**Closed as completed by lunny** 2021-01-06 04:20 UTC
Labels: type/bug, issue/duplicate
