### ISSUE TITLE
Migrating from 1.14 to 1.15.6

### ISSUE THREAD

**Issue by ndelpuppo** [go-gitea/gitea#17708] opened 2021-11-18 11:22 UTC
### Gitea Version

gitea-1.15.6

### Git Version

git-2.29.3

### Operating System

centos7

### How are you running Gitea?

I am using the binary release downloaded from https://dl.gitea.io/gitea

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

Hi All,
I am facing issues while trying to upgrade Gitea from release 1.14 to 1.15.6.
Looking at the logs, it seems a db migration-related problem:

ORM engine initialization attempt #5/10 failed. Error: migrate: do migrate: pq: column "message" of relation "task" already exists

I would like to avoid wiping the database, is there anything I could do to fix this issue?

PLease see attached the log file.
[giteamigration.txt](https://github.com/go-gitea/gitea/files/7562305/giteamigration.txt)

**Comment by wxiaoguang** [comment] 2021-11-18 11:25
Please do not re-install on an installed database.

You should use your old `app.ini`.


To bypass this error, you may either:

1. Use your 1.14 backup database and use your old `app.ini` to do the upgrade again.
2. Drop the duplicated column and use the old `app.ini` to continue to migrate.

The old app.ini is a must.

**Comment by wxiaoguang** [comment] 2021-11-18 11:27
Duplicate of #17328

**Closed as completed by wxiaoguang** 2021-11-18 11:27 UTC

**Comment by ndelpuppo** [comment] 2021-11-18 12:56
> Please do not re-install on an installed database.
> 
> You should use your old `app.ini`.
> 
> To bypass this error, you may either:
> 
> 1. Use your 1.14 backup database and use your old `app.ini` to do the upgrade again.
> 2. Drop the duplicated column and use the old `app.ini` to continue to migrate.
> 
> The old app.ini is a must.

Thank you very much for your quick answer, I went for solution (2) and it worked!
Just for information, I was already using the original app.ini file, I simply replaced the gitea executable with the new one.
