### ISSUE TITLE
Disable the "Comment" button after the click to prevent duplicate comments

### ISSUE THREAD

**Issue by melmus** [go-gitea/gitea#12524] opened 2020-08-18 14:24 UTC
- Gitea version (or commit ref):
1.13.0+dev-295-g16980d13c

- Git version:
2.17.1

- Operating system:
Ubuntu 18.04.3 LTS

- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
If I add comments, sometimes the comments can duplicate.

## Screenshots
![4](https://user-images.githubusercontent.com/15018126/90524858-3d0f6b80-e177-11ea-9d49-f3f644d3423c.png)

**Comment by zeripath** [comment] 2020-10-05 20:13
The issue is a double-click of the submit button.

We need to disable the submit buttons on a submit (at least for a period of time.)

**Comment by melmus** [comment] 2021-01-26 09:34
The problem is still there.

**Comment by wxiaoguang** [comment] 2021-12-08 07:49
Duplicate of

* https://github.com/go-gitea/gitea/issues/17111 (with more details)

Unfortunately, no ideal plan to fix it yet ....

**Closed as completed by wxiaoguang** 2021-12-08 07:49 UTC
Labels: type/enhancement, topic/ui
