### ISSUE TITLE
Only show commit title in issue history when referencing an issue

### ISSUE THREAD

**Issue by mbger** [go-gitea/gitea#3626] opened 2018-03-05 10:35 UTC
- Gitea version (or commit ref): 171914e
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] [Yes](https://try.gitea.io/mbger/TestRepo/issues/1) 
  - [ ] No
  - [ ] Not relevant

## Description

I couldn't find an issue which already mentions this but this may have come up before (and it's obviously not a bug). 

According to the [Git Book](https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project) it's good practice that commit messages should contain a concise title followed by a more detailed description separated with a blank line:

>... As a general rule, your messages should start with a single line that’s no more than about 50 characters and that describes the changeset concisely, followed by a blank line, followed by a more detailed explanation.

When following this suggestion, gitea's UI for any referenced issue gets somewhat bloated. I think it may be a good idea to only show the title of the commit message to keep the history timeline more compact. Optionally, there could be an ellipses button (or sth similar) which expands the complete commit message. Below is a screenshot using [Tim Pope's commit message template](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html)

## Screenshots
<img width="650" alt="commit-reference" src="https://user-images.githubusercontent.com/5991861/36970411-cafd2dce-2068-11e8-9df9-bdbdfa0c8ab3.png">

**Comment by adelowo** [comment] 2019-02-08 14:03
___Unstale___

> Good bot :)

**Comment by mrsdizzie** [comment] 2020-09-07 19:01
Duplicate of #12541 (this one came first but the other has more recent activity/likely to get the issue fixed)

**Closed as completed by mrsdizzie** 2020-09-07 19:01 UTC
Labels: type/enhancement, issue/confirmed
