### ISSUE TITLE
MIlestones with 2/29 due date display as 2/28

### ISSUE THREAD

**Issue by steve4650** [go-gitea/gitea#29034] opened 2024-02-03 16:56 UTC
### Description

As simple as it sounds. Create a milestone with due date 2/29/2024, and it will display as 2/28/2024.

![image](https://github.com/go-gitea/gitea/assets/61095764/082bc9a1-d473-40c4-8c6e-37838f611d5f)

### Gitea Version

1.21.4

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

2.40.1

### Operating System

Gentoo

### How are you running Gitea?

Gentoo gitea package

### Database

SQLite

**Comment by eeyrjmr** [comment] 2024-02-03 17:06
uuur leapyear bug

**Comment by yardenshoham** [comment] 2024-02-03 17:44
Hmmm I can't reproduce
![image](https://github.com/go-gitea/gitea/assets/20454870/fcc61bb6-4e59-4c0a-81b9-60c9c15df779)

Can you give a link to the demo site with reproduction?

**Comment by janie314** [comment] 2024-02-03 17:45
See https://try.gitea.io/janie314/SDFSDF/milestones @yardenshoham

**Comment by yardenshoham** [comment] 2024-02-03 17:46
Looks ok on my side

![image](https://github.com/go-gitea/gitea/assets/20454870/88f9545c-9807-4571-ba70-59605ff1aab7)

What's your timezone?

**Comment by techknowlogick** [comment] 2024-02-03 19:21
Yup. This is based on timezone. The value is stored as a date in the db, but then the time library displays it as a datetime and due to midnight utc being different it shows as a different day.

**Comment by janie314** [comment] 2024-02-03 23:57
I see- thanks all!

Looks like there is no per-user timezone setting for Gitea. I suppose we can either close this or leave this issue open as an enhancement request for that.

**Comment by techknowlogick** [comment] 2024-02-04 00:43
I'd suggest keeping this open, as the due *date* should probably be treated as a date.

**Comment by yardenshoham** [comment] 2024-02-04 17:14
How to reproduce? Should I set a different timezone in my OS? Currently on GMT+2

**Comment by techknowlogick** [comment] 2024-02-04 17:31
@yardenshoham yeah, likely changing your timezone to any one lower than UTC-0. As then "midnight" utc will a different day.

**Comment by yardenshoham** [comment] 2024-02-04 17:41
Thanks, I was able to reproduce. How should we handle this? Maybe parse the user's timezone and set the milestone to the user's midnight?

**Comment by janie314** [comment] 2024-02-04 19:35
Hmhm. Currently, Gitea does not have an default timezone setting and uses its server's timezone, as I understand.

I suggest:

- Next to this date input (and other similar date inputs), we note the Gitea server's timezone (America/Chicago, UTC, etc.) 

Because with the original issue submitted- the issue was that the date I chose was secretly converted to a date in the server's timezone. So- server-timezone dates are the dates we use, in reality, so just making a small note of that will be a straightforward resolution.

**Comment by lunny** [comment] 2024-02-05 05:26
Or we can have a timezone selection near the date.

**Comment by yp05327** [comment] 2024-02-07 06:45
`issue` also have `dealine`, maybe have same problem.

**Comment by silverwind** [comment] 2024-03-09 17:17
Imho we should reduce this `datetime` in the database to `date` via migration.

**Closed as completed** 2024-03-12 22:37 UTC
Labels: type/bug, issue/confirmed
