### ISSUE TITLE
Multiple Issue Creation

### ISSUE THREAD

**Issue by TBSliver** [go-gitea/gitea#10458] opened 2020-02-25 14:39 UTC
- Gitea version (or commit ref): 1.11.1
- Git version: Irrelevant
- Operating system: Ubuntu 18.04.4 LTS
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/TBSliver/Testing/issues
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When creating an issue, clicking the create button more than once (either accidentally or otherwise) will create duplicate Issues. See my example at https://try.gitea.io/TBSliver/Testing/issues where I created 9 issues by clicking create multiple times.

**Comment by jolheiser** [comment] 2020-02-25 16:41
Duplicate of #6859

**Closed as completed by jolheiser** 2020-02-25 16:41 UTC
Labels: issue/duplicate
