### ISSUE TITLE
Expanding diff view broken

### ISSUE THREAD

**Issue by noerw** [go-gitea/gitea#18281] opened 2022-01-15 11:52 UTC
### Gitea Version

1.16.0+dev-841-gd413a1f8a d413a1f8a

### Git Version

-

### Operating System

latest firefox

### How are you running Gitea?

irrelevant

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

Expanding a diff results in broken rendering of the diff, see also attached video.

afaik this happens on PR diff page, as well as commit diff page.

### Screenshots

https://user-images.githubusercontent.com/7880552/149620722-e04edca2-fa83-4a52-8474-414dd610cd72.mp4

**Comment by silverwind** [comment] 2022-01-15 16:28
Weird one, the JS spews some apparently escaped HTML into the DOM.

<img width="707" alt="image" src="https://user-images.githubusercontent.com/115237/149629495-18361cc0-648e-49ec-a48a-3e144af9edc8.png">

**Comment by wxiaoguang** [comment] 2022-01-15 17:18
The bug is caused by we wrote `<code class="code-inner">{{$.section.GetComputedInlineDiffFor $line}}</code>` ( Add warning for BIDI characters in page renders and in diffs (#17562) )

Before, `GetComputedInlineDiffFor` returns HTML text.

Now, `GetComputedInlineDiffFor` returns `DiffInline` struct, so we should change all `{{$.section.GetComputedInlineDiffFor $line}}` callings to output the `DiffInline.Content`

**Comment by zeripath** [comment] 2022-01-15 18:28
agh this is due to an interaction between the BIDI pr and the diff PR.

When the diff PR was created the BIDI PR wasn't merged and when the BIDI PR was created the diff PR wasn't merged.

**Comment by zeripath** [comment] 2022-01-15 18:32
Actually no it's a bit of debugging code that got left in.

**Comment by andre161292** [comment] 2022-02-01 06:50
This is still broken. Please have a look at https://try.gitea.io/testerxxx/gitea/pulls/1/files (or any other diff on try.gitea.io). 

I'm also experiencing the issue in the gitea/gitea:1.16.0-linux-amd64 docker image.

**Comment by wxiaoguang** [comment] 2022-02-01 09:03
I managed to reproduce the bug:

<img width="1353" alt="image" src="https://user-images.githubusercontent.com/2114189/151939957-d32d55e6-db08-43a0-97a9-06fd199e969f.png">

**Comment by wxiaoguang** [comment] 2022-02-01 09:05
> This is still broken. Please have a look at https://try.gitea.io/testerxxx/gitea/pulls/1/files (or any other diff on try.gitea.io).
> 
> I'm also experiencing the issue in the gitea/gitea:1.16.0-linux-amd64 docker image.

@andre161292 if you meet other bugs, please help to tell the Gitea team how to reproduce it and get a screenshot. Thank you very much ~~

**Comment by lunny** [comment] 2022-02-01 09:08
#18516 and #18517 have reported the problem.

**Comment by zeripath** [comment] 2022-02-01 20:32
Fixed by #18502

**Closed as completed by zeripath** 2022-02-01 20:32 UTC
Labels: type/bug, topic/ui
