### ISSUE TITLE
[Feature request] Pull requests: Lazy loading for diffs

### ISSUE THREAD

**Issue by 3l73** [go-gitea/gitea#6380] opened 2019-03-19 21:11 UTC
Gitea: 1.7

Current situation:
If the amount of changed files reached a specific count, gitea shows the message that more files changed.
It is not possible to which files are affected. 

This behaviour may a result of performance and memory issues. 

Idea:
If the amount of files reach a specific count, all affected files are displayed collapsed. The user had to click on a specific file to see the difference.

**Comment by kdumontnu** [comment] 2021-07-12 18:14
This would be a great feature to work on for `v1.16`

**Comment by delvh** [comment] 2021-11-19 12:18
Fixed in #16829?

**Closed as completed by delvh** 2021-11-19 12:18 UTC
Labels: type/enhancement, issue/confirmed

**Comment by jpraet** [comment] 2021-11-19 19:58
I'm trying it out but it's not working for me: https://try.gitea.io/jpraet-org/test-repo/pulls/1/files
When clicking "Show More" I see this error in the console:
XHR GET https://try.gitea.io/jpraet-org/test-repo/pulls/1/files?skip-to=101.txt&file-only=true
[HTTP/2 500 Internal Server Error 190ms]

**Comment by zeripath** [comment] 2021-11-19 20:20
@jpraet please open new issues instead of commenting on old ones and give us logs for what went wrong.

**Comment by zeripath** [comment] 2021-11-19 20:27
I cannot reproduce this locally therefore I need the logs.

**Comment by jpraet** [comment] 2021-11-19 20:36
I'll open another ticket, but in the meantime, here's the log output when reproducing it locally:

```
2021/11/19 21:30:27 Started GET /jpraet/test/pulls/33/files?skip-to=101.txt&file-only=true for 127.0.0.1:54238
usage: git diff [<options>] [<commit> [<commit>]] [--] [<path>...]
2021/11/19 21:30:28 ...ers/web/repo/pull.go:641:ViewPullFiles() [E] GetDiffRangeWithWhitespaceBehavior: Wait: exit status 129
2021/11/19 21:30:28 ...s/gitdiff/gitdiff.go:1328:func1() [E] Unable to open checker for 3ce2ba0f0b457f8407c698581e1fc05f42dda2d7. Error: failed to run attr-check. Error: exit status 1
        Stderr:
2021/11/19 21:30:28 Completed GET /jpraet/test/pulls/33/files?skip-to=101.txt&file-only=true 500 Internal Server Error in 727.5449ms
```

I don't think the "Unable to open checker" error is the actual problem, as I also see that error when just opening the files tab on the PR. That one seems like a non-blocking error (that maybe should be looked into nonetheless?).

**Comment by zeripath** [comment] 2021-11-19 20:49
What version of git do you have?

**Comment by zeripath** [comment] 2021-11-19 20:55
damn I misread the git documentation - it looks like skip-to only appeared in git 2.31!!

**Comment by jpraet** [comment] 2021-11-19 21:01
Bug report created: #17731

I'm using quite an old git version 2.18 on this machine. try.gitea.io is also on an older version then?
