### ISSUE TITLE
Getting 500 error when adding a member on restricted branches

### ISSUE THREAD

**Issue by derekdpk** [go-gitea/gitea#17978] opened 2021-12-14 09:10 UTC
### Gitea Version

1.15.7 built with GNU Make 4.1, go1.16.10 : bindata, sqlite, sqlite_unlock_notify

### Operating System

Ubuntu 20.04 LTS

### Browser Version

Version 94.0.4606.81 (Official Build) (64-bit)

### Can you reproduce the bug on the Gitea demo site?

No

### Description

Getting 500 errors when adding a member on restricted branches in gitea. tried with updating with the latest version of gitea server but still, the problem is the same.

### Screenshots

![image](https://user-images.githubusercontent.com/95911951/145967032-3406181c-653f-4a77-9188-d0238238deba.png)

**Comment by zeripath** [comment] 2021-12-14 17:06
We need logs.

Unfortunately I don't understand your description so I can't even attempt to reproduce the problem.

PLEASE GIVE US LOGS.

**Comment by derekdpk** [comment] 2021-12-15 07:30
Hi Zeripath,

I have a repository and I have restricted branches on that for push and merge. so when I am trying to add a user in the restricted branch it throws an error with 500.  I have updated the Gitea server version with 1.15.7 but the problem is still the same. The main logs for this I found :

1. ...s/issue_stopwatch.go:71:GetUserStopwatches() [I] [SQL] SELECT `id`, `issue_id`, `user_id`, `created_unix` FROM `stopwatch` WHERE (stopwatch.user_id = ?) [226] - 459.686µs
2. rm.io/xorm/engine.go:1139:Get() [I] [SQL] SELECT `id`, `owner_id`, `owner_name`, `lower_name`, `name`, `description`, `website`, `original_service_type`, `original_url`, `default_branch`, `num_watches`, `num_stars`, `num_forks`, `num_issues`, `num_closed_issues`, `num_pulls`, `num_closed_pulls`, `num_milestones`, `num_closed_milestones`, `num_projects`, `num_closed_projects`, `is_private`, `is_empty`, `is_archived`, `is_mirror`, `status`, `is_fork`, `fork_id`, `is_template`, `template_id`, `size`, `is_fsck_enabled`, `close_issues_via_commit_in_any_branch`, `topics`, `trust_model`, `avatar`, `created_unix`, `updated_unix` FROM `repository` WHERE `owner_id`=? AND `lower_name`=? LIMIT 1

The screenshot is shared above for the issue. Thank you! :+1:

**Comment by zeripath** [comment] 2021-12-15 09:53
Why do I always have to repeat this?! The issue proforma clearly states:

> It really is important to provide pertinent logs
> Please read https://docs.gitea.io/en-us/logging-configuration/#debugging-problems
> In addition, if your problem relates to git commands set RUN_MODE=dev at the top of app.ini

To be more explicit:

### Debugging problems

When submitting logs in Gitea issues it is often helpful to submit merged logs obtained by either by redirecting the console log to a file or copying and pasting it. To that end it is recommended to set your logging to:

```ini
[database]
LOG_SQL = false ; SQL logs are rarely helpful unless we specifically ask for them

...

[log]
MODE = console
LEVEL = debug ; please set the level to debug when we are debugging a problem
ROUTER = console
COLORIZE = false ; this can be true if you can strip out the ansi coloring
```

Sometimes it will be helpful get some specific `TRACE` level logging restricted to messages that match a specific `EXPRESSION`. Adjusting the `MODE` in the `[log]` section to `MODE = console,traceconsole` to add a new logger output traceconsole and then adding its corresponding section would be helpful:

```ini
[log.traceconsole] ; traceconsole here is just a name
MODE = console ; this is the output that the traceconsole writes to
LEVEL = trace
EXPRESSION = ; putting a string here will restrict this logger to logging only those messages that match this expression
```

(It’s worth noting that log messages that match the expression at or above debug level will get logged twice so don’t worry about that.)

`STACKTRACE_LEVEL` should generally be left unconfigured (and hence kept at none). There are only very specific occasions when it useful.

## Summary

The logs you've provided above do not contain the error. They're SQL logs and are irrelevant to the problem. Please set your app.ini to match the first section to give us some useful logs. I will repeat it again here:

```ini
[database]
LOG_SQL = false ; SQL logs are rarely helpful unless we specifically ask for them

...

[log]
MODE = console
LEVEL = debug ; please set the level to debug when we are debugging a problem
ROUTER = console
COLORIZE = false ; this can be true if you can strip out the ansi coloring
```

The screenshot is completely useless. It does not give us any helpful information about what is going on. It does not even show the requested URL.

Thank you for the description but we still need the logs.

**Comment by zeripath** [comment] 2021-12-18 05:33
Please can you give me the logs I've requested above. I still can't reproduce the problem from your description.

**Comment by zeripath** [comment] 2021-12-20 15:10
If you do not provide the requested logs within 2 days I will close this issue as I cannot reproduce.

Please provide the requested logs. 

Please update your app.ini as follows:

```ini
[database]
LOG_SQL = false ; SQL logs are rarely helpful unless we specifically ask for them

...

[log]
MODE = console
LEVEL = debug ; please set the level to debug when we are debugging a problem
ROUTER = console
COLORIZE = false ; this can be true if you can strip out the ansi coloring
```

And give us the logs reproducing the problem.

**Comment by zeripath** [comment] 2022-01-01 11:12
Without logs and a clear description to reproduce we cannot move any further forward with fixing this bug.

Please reopen if you can provide the requested logs.

**Closed as completed by zeripath** 2022-01-01 11:12 UTC
Labels: issue/needs-feedback
