### ISSUE TITLE
[Protected branches] Add commit status check

### ISSUE THREAD

**Issue by pando85** [go-gitea/gitea#5961] opened 2019-02-04 12:57 UTC
I will like to propose a new feature: Block merge PR if build does not pass like in Github. This could be a protected branch option and if not commit status pass you cannot merge it.
Jenkins and Drone have implementations of commit status.

**Comment by lunny** [comment] 2019-02-06 01:48
This should be duplicated issue.

**Comment by pando85** [comment] 2019-02-06 10:58
I didn't find it, sorry. If you give me ticket number I could follow it. Thanks!

**Comment by markusamshove** [comment] 2019-02-06 11:54
#996 and #3588 are similar. Searched for ci. 
I'm not sure if #996 covers approval

**Comment by lafriks** [comment] 2019-02-06 12:20
Duplicate of #3588

**Closed as completed** 2019-02-06 12:20 UTC
Labels: issue/duplicate
