### ISSUE TITLE
Swagger absolute paths make API not working when serving on subpath

### ISSUE THREAD

**Issue by OndrejSpanel** [go-gitea/gitea#4907] opened 2018-09-11 09:00 UTC
- Gitea version (or commit ref): 1.5.1
- Git version: 1.9.1
- Operating system: Debian 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [x] Not relevant
- Log gist:

## Description

I am serving my gitea on URL like https://www.myserver.net/gitea, configured using Apache reverse proxy mapping this URL to http://localhost:3000. Main reason for this is my current SSL certificate does not allow subdomains. Everything works fine, the only problem I have is with Swagger.

As Swagger API URLs start with /, they override the /gitea part of the base part, forming URLs like https://www.myserver.net/api/v1/ instead of https://www.myserver.net/gitea/api/v1/.

The APIs themselves work fine in the form https://www.myserver.net/gitea/api/v1/version, it is only the Swagger demo which does not.

## Screenshots

![image](https://user-images.githubusercontent.com/6927223/45349721-59312800-b5b2-11e8-8b3b-4bde59b979c5.png)

![image](https://user-images.githubusercontent.com/6927223/45349473-a791f700-b5b1-11e8-81c3-216f206b6571.png)

**Comment by lafriks** [comment] 2018-09-12 05:38
Duplicate of #3499

**Closed as completed** 2018-09-12 05:38 UTC
Labels: issue/duplicate
