### ISSUE TITLE
Issue number will not be updated by closing an issue

### ISSUE THREAD

**Issue by luwol03** [go-gitea/gitea#11308] opened 2020-05-05 21:51 UTC
- Gitea version (or commit ref): 99082eebd76019fc608e44c4464da6398f51dccd
- Git version: 2.20.1
- Operating system: Linux Debian buster
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
If I automatically close issues via a reference in a pull request, the issue will be closed, but the number next to the issues tab will not be updated! Only if I restart gitea!
![IMG_20200505_002924](https://user-images.githubusercontent.com/60048565/81119478-1e1ffd00-8f2b-11ea-8b38-a881d2066bfb.png)

**Comment by jolheiser** [comment] 2020-05-05 22:33
Are there any errors in the logs? I cannot reproduce this on try with the latest commit.

Admittedly try uses SQLite, so this could be specific to MySQL, but I'm not sure why that would be.

**Comment by luwol03** [comment] 2020-05-05 22:37
Where I can find the log?

**Comment by jolheiser** [comment] 2020-05-05 22:37
Seems I spoke too soon.

Closing an issue from the PR description works, however when I closed the issue via a _commit_ the number didn't change.  
https://try.gitea.io/jolheiser/ciw/issues

**Comment by silverwind** [comment] 2020-05-06 08:44
Duplicate of https://github.com/go-gitea/gitea/issues/10536

**Comment by zeripath** [comment] 2020-05-06 09:26
So eventually when a commit is parsed that closes an issue we reach:

https://github.com/go-gitea/gitea/blob/a1f11a05e900f3d1130729b2095dbf1b3037658e/modules/repofiles/action.go#L61-L149

This calls 

https://github.com/go-gitea/gitea/blob/a1f11a05e900f3d1130729b2095dbf1b3037658e/modules/repofiles/action.go#L34-49

**Comment by zeripath** [comment] 2020-05-06 09:34
`issue.ChangeStatus` calls `issue.changeStatus` which does call:

https://github.com/go-gitea/gitea/blob/a1f11a05e900f3d1130729b2095dbf1b3037658e/models/issue.go#L622

which attempts to update the row - but I suspect is not because the value is not being looked up from within the changed table.

The thing that all the other routes do is that they add a comment after the changestatus - not before - which will look at the committed changes to the issue table.

**Comment by zeripath** [comment] 2020-05-06 09:36
The simplest solution is to move the createRefComment to after the attempt to close the issue.

**Comment by lunny** [comment] 2020-09-18 08:01
Close as duplicated, see #10536

**Closed as completed by lunny** 2020-09-18 08:01 UTC
Labels: type/bug, issue/confirmed
