### ISSUE TITLE
Error: failed to run attr-check

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#19037] opened 2022-03-09 11:18 UTC
### Gitea Version

1.16.3

### Git Version

2.25.1

### Operating System

Ubuntu 20.04.4

### How are you running Gitea?

Self hostet

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

I my gitea logs I see often this

```
2022/03/09 12:15:39 ...age_stats_nogogit.go:86:func2() [E] Unable to open checker for ecf4c1c52d7a60d64f78013371075e731e1ea647. Error: failed to run attr-check. Error: context canceled
        Stderr:
        /source/modules/git/repo_language_stats_nogogit.go:86 (0xaeef8f)
        /usr/local/go/src/runtime/asm_amd64.s:1581 (0x471520)
```

error log entry.

**Comment by zeripath** [comment] 2022-03-09 19:47
This is a duplicate of #18997 which has already been fixed with #19006 and its backport #19027

**Closed as completed by zeripath** 2022-03-09 19:47 UTC
Labels: issue/duplicate
