### ISSUE TITLE
Gitea in Synology docker restarts and enters the setup page after setting the boot setup page (using MySQL). Using SQLite does not have this problem

### ISSUE THREAD

**Issue by caifenglin** [go-gitea/gitea#17921] opened 2021-12-06 13:10 UTC
### Gitea Version

1.15.7

### Operating System

Docker x86

### Browser Version

Chrome 96.0.4664.45

### Can you reproduce the bug on the Gitea demo site?

No

### Description

Can you provide a tutorial for synology to install gitea? I install gitea through synology's docker. I normally enter the setting page. After setting the parameters, I can't find the page. After restarting gitea, I'm still on the setting page. What should I do? The version is 1.15.7。Gitea in Synology docker restarts and enters the setup page after setting the boot setup page (using MySQL). Using SQLite does not have this problem

### Screenshots

![image](https://user-images.githubusercontent.com/78671821/144851298-2d4dedb2-773e-4eb0-ae6d-11a610877f66.png)
![image](https://user-images.githubusercontent.com/78671821/144851393-39823a5b-317f-4550-84ff-8b946181621d.png)
[Gitea.csv](https://github.com/go-gitea/gitea/files/7660875/Gitea.csv)

**Comment by zeripath** [comment] 2021-12-06 22:52
We need to see the logs.

**Comment by caifenglin** [comment] 2021-12-07 01:08
The log folder is empty. Synology logs are like gitea.csv above

**Comment by zeripath** [comment] 2021-12-07 06:31
It's not really fair to provide logs in a nonstandard format. 

The provided logs in gitea.csv only appear to show that gitea gets killed by Synology when it tries to talk to the mysql server.

This implies to me that you haven't allowed the docker to talk to the mysql server or haven't provided a mysql docker for it to run with.

**Comment by caifenglin** [comment] 2021-12-07 11:22
My MySQL service is in another docker environment. What you said is very possible, but how can I deal with this situation to avoid being prohibited from communicating by Synology

**Comment by caifenglin** [comment] 2021-12-07 11:27
Should I try to let MySQL use the host network and report the results when my test is completed

**Comment by caifenglin** [comment] 2021-12-07 11:47
Can anyone provide a tutorial on the installation of Synology  gitea，Thank you very mach

**Comment by wxiaoguang** [comment] 2021-12-07 11:50
You may join the QQ Group 328432459 to find more users to ask for help. I will close this issue since it is not a bug, but it's environment related.

**Closed as completed by wxiaoguang** 2021-12-07 11:50 UTC

**Comment by wxiaoguang** [comment] 2021-12-07 11:55
ps: if you see the install page again and again (while you have ever installed it), I think it might be caused by that the generated config file `app.ini` is lost during restart. Some files of Gitea need to be store correctly.  I would suggest you try to install Gitea in a simple Linux server to get familiar to it and then debug the installation in Synology Nas.

**Comment by caifenglin** [comment] 2021-12-07 12:57
![image](https://user-images.githubusercontent.com/78671821/145032626-2e09c670-e601-4b5b-8fcf-12eca014e546.png)
![image](https://user-images.githubusercontent.com/78671821/145032667-e48a7a1c-a63c-4f92-b33a-cb3bbc84790f.png)
![image](https://user-images.githubusercontent.com/78671821/145032691-50c11ffa-ea05-4055-8959-3df7ed07c05a.png)
![image](https://user-images.githubusercontent.com/78671821/145032727-3c39e31f-9776-45f4-96f4-f4c663e32620.png)
I still failed. I don't know how you can do it. I used MySQL with GIT and root users, but they didn't work. 21 tables were generated, which seems wrong

**Comment by caifenglin** [comment] 2021-12-07 12:58
I still failed. I don't know how you can do it. I used MySQL with GIT and root users, but they didn't work. 21 tables were generated, which seems wrong

**Comment by caifenglin** [comment] 2021-12-07 12:59
The app.in file has content. It is indeed mounted in the / data directory, and the data also has content

**Comment by caifenglin** [comment] 2021-12-07 13:10
Originally, I wanted to ask a question. I wanted someone to help my platform. It seems that the problem can't be solved well, so it was closed. I'm sorry I can't understand this kind of behavior of solving the problem in order to close it

**Comment by wxiaoguang** [comment] 2021-12-07 13:34
GitHub issues are mainly used for bug reports and feature discussions.

If you have read the documents (https://docs.gitea.io/en-us/seek-help/ , https://docs.gitea.io/zh-cn/seek-help/ ), you could understand that  Discord / Discourse Forum / QQ Group are the places for questions and helps.

**Comment by caifenglin** [comment] 2021-12-07 13:57
I'm sorry
