### ISSUE TITLE
The button to merge the code can be double-clicked

### ISSUE THREAD

**Issue by ffbh123456** [go-gitea/gitea#14242] opened 2021-01-04 12:25 UTC
When I quickly click the button for merging code multiple times, the webpage will get 404. I suggest that this button can refer to GitHub button, and it can only be clicked once. When I click this button, the button will change to another color and this button is not clickable
![image](https://user-images.githubusercontent.com/20750357/103534796-8bc16600-4eca-11eb-972c-b757ab021403.png)

**Comment by lunny** [comment] 2021-01-05 12:41
Not only this button ...

**Comment by ZhouJiaZhi** [comment] 2021-01-09 04:18
@lunny 
Yes, this seems to be a lot of work, are you planning to fix this recently?

**Comment by wxiaoguang** [comment] 2021-12-08 07:47
Duplicate of

* https://github.com/go-gitea/gitea/issues/17111 (with more details)

Unfortunately, no ideal plan to fix it yet ....

**Closed as completed by wxiaoguang** 2021-12-08 07:47 UTC
Labels: type/bug, topic/ui
