### ISSUE TITLE
Ability to completely disable Issues, Pull Requests, Milestones

### ISSUE THREAD

**Issue by lzrdblzzrd** [go-gitea/gitea#20960] opened 2022-08-25 21:56 UTC
### Feature Description

In the config file, it is possible to disable the Stars function so that it is impossible to put stars to repositories.
It would be nice if it were possible to disable the functions specified in the title if you host your own Gitea and do not use these functions.

### Screenshots

![image](https://user-images.githubusercontent.com/32615368/186776099-5dfa2b74-7f05-4f7c-9028-d47642a84bd1.png)

**Comment by andreas-bulling** [comment] 2022-10-30 10:25
This would be great to have!

**Comment by dieselburner** [comment] 2023-04-18 14:35
Duplicate of https://github.com/go-gitea/gitea/issues/4750?

**Closed as completed** 2023-05-06 09:39 UTC
Labels: type/proposal, type/feature
