### ISSUE TITLE
Upgrade to 1.5.0 fails during database migration

### ISSUE THREAD

**Issue by fgtham** [go-gitea/gitea#4694] opened 2018-08-13 14:49 UTC
- Gitea version (or commit ref): 1.4.3
- Git version: 2.11.0
- Operating system: Raspbian 9.4 (stretch)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I'm trying to upgrade from 1.4.3 to 1.5.0 following the docs. Starting gitea 1.5.0 triggers DB migration, which then fails to complete and gitea crashes instead. From gitea.log:

```
2018/08/13 16:06:29 [I] Log Mode: File(Info)
2018/08/13 16:06:29 [I] XORM Log Mode: File(Info)
2018/08/13 16:06:29 [I] Cache Service Enabled
2018/08/13 16:06:29 [I] Session Service Enabled
2018/08/13 16:06:29 [I] Migration: Reformat and remove incorrect topics
2018/08/13 16:06:29 [I] This migration could take up to minutes, please be patient.
2018/08/13 16:06:30 [...itea/routers/init.go:60 GlobalInit()] [E] Failed to initialize ORM engine: migrate: do migrate: Sync2: Error 1071: Specified key was too long; max key length is 767 bytes
```

The problem might be the MySQL DB character set:

```
# mysql -e 'show create database gitea'
+----------+-------------------------------------------------------------------+
| Database | Create Database                                                   |
+----------+-------------------------------------------------------------------+
| gitea    | CREATE DATABASE `gitea` /*!40100 DEFAULT CHARACTER SET utf8mb4 */ |
+----------+-------------------------------------------------------------------+
```

According to [this stackoverflow answer](https://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes#16820166), the problem lies within the fact that `utf8mb4` uses up to 4 bytes per char. Creating a unique index on a `varchar(255)` field then exceeds the max key length of 767 bytes, as 4*255 = 1020.

The [MySQL docs](https://dev.mysql.com/doc/refman/5.7/en/create-index.html) state that:

> Prefix limits are measured in bytes. However, prefix lengths for index specifications in CREATE TABLE, ALTER TABLE, and CREATE INDEX statements are interpreted as number of characters for nonbinary string types (CHAR, VARCHAR, TEXT) and number of bytes for binary string types (BINARY, VARBINARY, BLOB). Take this into account when specifying a prefix length for a nonbinary string column that uses a multibyte character set. 

Is there any way to keep using gitea with a utfmb4 character set, or is this simply not supported (yet)?

**Comment by SagePtr** [comment] 2018-08-13 15:52
> Is there any way to keep using gitea with a utfmb4 character set, or is this simply not supported (yet)?

Setting ```innodb_large_prefix``` option in my.cnf for example. Or update MySQL to 5.7.7 or more recent version where this option is on by default.

**Comment by Pofilo** [comment] 2018-08-13 17:03
You should take a look of other issues before !

Duplicate of https://github.com/go-gitea/gitea/issues/4663 which is already a duplicate ;)

**Closed as completed** 2018-08-13 17:41 UTC
Labels: issue/duplicate
