### ISSUE TITLE
Cannot upload jar file

### ISSUE THREAD

**Issue by tomposmiko** [go-gitea/gitea#7266] opened 2019-06-20 10:43 UTC
- Gitea version (or commit ref): 1.8.3
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Despite this setting:
ALLOWED_TYPES = image/jpeg|image/png|application/zip|application/gzip|application/java-archive

I does not allow upload jar files.
If I set */*, then the upload is allowed.

application/* also does not allow me to do that.

What should be the appropriate setting?
...

**Comment by PeterAS17** [comment] 2019-08-08 21:01
_application/java-archive_ not working on Gitea 1.9.0 either

**Comment by tomposmiko** [comment] 2019-08-16 08:37
What is the severity of this issue from your perspective?

**Comment by lunny** [comment] 2019-08-16 12:59
should fixed by #7890

**Comment by lunny** [comment] 2019-08-16 13:00
Where did you upload? Releases or issues?

**Comment by lunny** [comment] 2019-08-16 13:04
There are two allowed_types, you may changed the wrong section. I uploaded successfully on my local instance both the releases and issues.

```ini
[repository.upload]
ALLOWED_TYPES = "application/zip|application/gzip|application/x-gzip|application/x-gtar|application/x-tgz|application/x-compressed-tar|application/java-archive"

[attachment]
ALLOWED_TYPES = "application/zip|application/gzip|application/x-gzip|application/x-gtar|application/x-tgz|application/x-compressed-tar|application/java-archive"

```

**Comment by tomposmiko** [comment] 2019-08-16 17:09
> Where did you upload? Releases or issues?

releases

**Comment by tomposmiko** [comment] 2019-08-23 09:20
Hmm, this is interesting.

$ mkdir -p data/tmp/uploads
$ chown ...
$ service gitea restart

And it starts working.
However, after second restart, it stops working, because the tmp directory is gone!
In fact I investigated the following scenarios:

1. no [repsitory.upload] section in app.ini
-> no success, even if the directory is created.

2. 
[repository.upload]
ENABLED = true
TEMP_PATH = data/tmp/uploads
FILE_MAX_SIZE = 3
MAX_FILES = 5
ALLOWED_TYPES = image/jpeg|image/png|application/zip|application/gzip|application/java-archive

It works after first service restart if the directory is created. It does not work after the second restart, the tmp directory is gone.

3. [repository.upload]
ENABLED = true
TEMP_PATH = /data/gitea/data/tmp/uploads
FILE_MAX_SIZE = 3
MAX_FILES = 5
ALLOWED_TYPES = image/jpeg|image/png|application/zip|application/gzip|application/java-archive

Directory created, service restarted.
No success 


4. TEMP_PATH = tmp/uploads
Directory created, service restarted.
No success 

So I got lost, I have no idea

**Comment by lafriks** [comment] 2019-08-24 14:35
You should mount tmp as volume in docker

**Comment by tomposmiko** [comment] 2019-08-24 20:16
I don't use docker.

**Comment by tomposmiko** [comment] 2019-08-27 09:35
Hmm, this is interesting.

$ mkdir -p data/tmp/uploads
$ chown ...
$ service gitea restart

And it starts working.
However, after second restart, it stops working, because the tmp directory is gone!
In fact I investigated the following scenarios:

1. no [repsitory.upload] section in app.ini
-> no success, even if the directory is created.

2. 
[repository.upload]
ENABLED = true
TEMP_PATH = data/tmp/uploads
FILE_MAX_SIZE = 3
MAX_FILES = 5
ALLOWED_TYPES = image/jpeg|image/png|application/zip|application/gzip|application/java-archive

It works after first service restart if the directory is created. It does not work after the second restart, the tmp directory is gone.

3. [repository.upload]
ENABLED = true
TEMP_PATH = /data/gitea/data/tmp/uploads
FILE_MAX_SIZE = 3
MAX_FILES = 5
ALLOWED_TYPES = image/jpeg|image/png|application/zip|application/gzip|application/java-archive

Directory created, service restarted.
No success 


4. TEMP_PATH = tmp/uploads
Directory created, service restarted.
No success 

So I got lost, I have no idea

**Comment by tomposmiko** [comment] 2019-08-27 09:36
Is it a bug or do I miss something?

**Comment by sapk** [comment] 2019-08-28 07:42
Gitea should support upload of java archive so it must be a configuration or system problem.
To be able to debug, do you have any log of the failed upload ?

**Comment by reikjarloekl** [comment] 2020-01-14 20:09
I have the same issue but with .zip files. Can be reproduced on try.giteo.io using a Windows 10 PC and Chrome or Firefox. 
It works using iOS! So apparently, mime type is set differently/ incorrectly using Windows 10/ Chrome or Firefox?

**Comment by sapk** [comment] 2020-01-14 20:51
Yes, It is possible that browser/os use different value. You can debug the mime type in gitea log or with the network inspector on firefox and chrome.
For Chrome: https://developers.google.com/web/tools/chrome-devtools/network#load

**Comment by reikjarloekl** [comment] 2020-01-14 20:57
There is no activity in the network tab. Possibly the javascript is already blocking the file from being uploaded?

**Comment by sapk** [comment] 2020-01-14 22:19
You need to open the network tab before uploading the file

**Comment by reikjarloekl** [comment] 2020-01-14 22:25
I did...

![gitea-upload-invalid-type](https://user-images.githubusercontent.com/839540/72388012-2ad2d800-3725-11ea-976b-e61afc31a01f.gif)

**Comment by zeripath** [comment] 2020-01-15 07:18
It'll be dropzone.js that is blocking the zip directly.

**Comment by dochan-consultis** [comment] 2020-01-30 09:17
I have also same issue with zip files. It is because of mime-types from code of dropzone.js. Allowed are these `image/jpeg,image/png,application/zip,application/gzip` and from Win10 with chrome when uploading zip is `application/x-zip-compressed`.

**Closed as completed** 2020-10-05 05:49 UTC
Labels: type/question, issue/confirmed
