### ISSUE TITLE
Can't push on normal user's repo with admin account

### ISSUE THREAD

**Issue by edoaxyz** [go-gitea/gitea#4292] opened 2018-06-21 13:00 UTC
- Gitea version (or commit ref): 1.4.2
- Git version: 2.7.4
- Operating system: Ubuntu
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
```
2018/06/21 12:53:45 [...routers/repo/http.go:205 HTTP()] [E] User permission denied
```

## Description
When I want to push some files with my admin account on a repo created by a normal user using https git gives me error 403 (Forbidden). I tried both password and token API but the outcome was always the same. The strange fact is that in the Web Interface admins can act freely on any repo.

**Comment by edoaxyz** [comment] 2018-06-21 14:58
Problem can be there 
https://github.com/go-gitea/gitea/blob/ec0ae5d50c59315a3c597b1cf24d4c5508c718e5/models/access.go#L62
There's nothing that handles admins account

**Comment by lunny** [comment] 2018-06-22 02:54
You could add yourself as that repo's collaboration.

**Comment by lafriks** [comment] 2018-06-22 04:53
That is currently expected behaviour to not allow admins clone/push to repositories only if explicitly allowed just as other users

**Comment by edoaxyz** [comment] 2018-06-22 07:05
If I need to do something automated adding always  myself to every repo's collaboration group is really frustrating. Anyway that doesn't make any sense because in web interface admins can do whatever they want in any repo while in git they are limited to act only in their own repos.

**Comment by gastaldi** [comment] 2018-10-25 13:44
I am facing the same problem and would be interested to know how to make that work

**Comment by lunny** [comment] 2018-10-25 13:45
Maybe we could add a config to enable admin user could clone and push to any repository.

**Comment by xplosionmind** [comment] 2022-04-07 08:17
+1, having the same issue here

**Comment by audibleptr** [comment] 2023-07-31 12:16
This seems to be resolved as of `gitea 1.19.4`. I'm able to push to a regular user's repo if I provide admin's username and password when pushing to the user's repo via a git remote like `http://<ip>:3000/user/repo`.

**Comment by puni9869** [comment] 2023-07-31 12:20
Since you are at localhost, could you share the logs 
Enable LOGGING=trace in app.ini.

**Comment by edoaxyz** [comment] 2023-08-02 08:52
That's fine! I'm not using gitea anymore but I'm trusting this, @puni9869 I leave you the decision of closing this one

**Comment by puni9869** [comment] 2023-08-23 07:52
As of now, closing this issue. Feel free to reopen in future

**Closed as completed by puni9869** 2023-08-23 07:52 UTC
Labels: type/proposal
