### ISSUE TITLE
handleCreateError()] [E] CreatePost: database table is locked: repository'

### ISSUE THREAD

**Issue by typeless** [go-gitea/gitea#1398] opened 2017-03-28 08:51 UTC
- Gitea version (or commit ref):
Gitea 1.10

- Git version:
it version 2.7.4

- Operating system:
"Ubuntu 16.04.2 LTS"

- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:
In log/gitea.log
`routers/repo/repo.go:103 handleCreateError()] [E] CreatePost: database table is locked: repository`

## Description
Creating a new repo would occasionally return HTTP code 500.
...

**Comment by lunny** [comment] 2017-03-31 12:20
I cannot reproduce in master version

**Comment by typeless** [comment] 2017-03-31 12:32
@lunny yes, this is not easy to reproduce. I'll provide more details (or solve it myself ) when I encounter the problem again.

**Comment by typeless** [comment] 2017-03-31 12:34
By the way, maybe many users accessing the server simultaneously can trigger it.

**Comment by lunny** [comment] 2017-03-31 12:36
maybe

**Comment by typeless** [comment] 2017-03-31 12:41
Once the new integration test is merged, we can add certain stress tests for such scenario. I am also thinking about migrate all global maps to syncmap gradually. That makes sense because gitea is a highly concurrent application.

**Comment by plessbd** [comment] 2017-04-03 16:49
Similar to #1434 and #1372 
At least for #1372 it doesn't have to do with load as I was the only one using the system at that point.

**Comment by typeless** [comment] 2017-04-05 02:26
The pattern used at https://github.com/go-gitea/gitea/blob/master/models/repo.go#L2000 is probably related.

See the pattern at the beginning of several related functions:
```Go
	if taskStatusTable.IsRunning(gitFsck) {
		return
	}
	taskStatusTable.Start(gitFsck)
	defer taskStatusTable.Stop(gitFsck)
```
It looks like the intention is to emulate some kind of mutex lock, but the problem is the read and lock is not combined into an atomic operation. They are separated into `IsRunning()` and `Start()` respectively. That could be problematic because there is no guarantee that, at the very moment after the call to `IsRunning` and before `Start`, another goroutine wouldn't be launched and calling into the same sequence.

**Comment by strk** [comment] 2017-04-05 08:26
The code is full of such patterns, I've seen it used for example
when setting a user email (to check that no other user has that
same email). Fixes for all these cases are really welcome !

**Comment by typeless** [comment] 2017-04-06 02:25
@strk I am still not sure that is the root cause of the problem despite it's not quite correct.

Before replacing it with something else, I would try to figure out *what* resources are shared and supposed to be concurrency-safe.

One thing does confuse me though. There are several tables of the database with duplicate information. For example, there is a `watch_num` column for each repository, but a table named `watch` has the the `repo_id` and `watch_num` mapping as well. As a result, there is a background goroutine for syncing the two, which I can not understand its purpose and think it'd better be simplified. See https://github.com/go-gitea/gitea/blob/master/models/repo.go#L2009. I guess that would probably be for performance reason, like speeding up some kind of queries. I am not familiar with database management, so please correct me if I am wrong.

**Comment by lunny** [comment] 2017-04-06 02:36
I agree @typeless. We need a queue to do that jobs, and for SQLITE, we could add a config item to disable this check running and provide a button on admin panel to run it manually.

**Comment by typeless** [comment] 2017-04-06 02:48
@lunny If possible (and reasonable), I'd like to eliminate those tables with redundant information and the 'syncing' thing altogether. I expect the queries serviced by those extra tables can be done with some slightly sophisticated SQLs and probably indexes can help with performance if that really matters.

P.S. Otherwise, keeping the tables and removing the columns with the same information in the other tables.

**Comment by typeless** [comment] 2017-04-07 06:43
Another data point.
```
Apr 07 14:24:40 DIR-101 gitea[31691]: ==================
Apr 07 14:24:40 DIR-101 gitea[31691]: WARNING: DATA RACE
Apr 07 14:24:40 DIR-101 gitea[31691]: Write at 0x00c421d72ba8 by goroutine 228:
Apr 07 14:24:40 DIR-101 gitea[31691]:   os/exec.(*Cmd).Wait()
Apr 07 14:24:40 DIR-101 gitea[31691]:       /home/mura/tools/go/src/os/exec/exec.go:439 +0x15d
Apr 07 14:24:40 DIR-101 gitea[31691]:   code.gitea.io/gitea/vendor/code.gitea.io/git.(*Command).RunInDirTimeoutPipeline.func1()
Apr 07 14:24:40 DIR-101 gitea[31691]:       /home/mura/devel/go/src/code.gitea.io/gitea/vendor/code.gitea.io/git/command.go:71 +0x38
Apr 07 14:24:40 DIR-101 gitea[31691]: Previous read at 0x00c421d72ba8 by goroutine 135:
Apr 07 14:24:40 DIR-101 gitea[31691]:   code.gitea.io/gitea/vendor/code.gitea.io/git.(*Command).RunInDirTimeoutPipeline()
Apr 07 14:24:40 DIR-101 gitea[31691]:       /home/mura/devel/go/src/code.gitea.io/gitea/vendor/code.gitea.io/git/command.go:77 +0x3fe
Apr 07 14:24:40 DIR-101 gitea[31691]:   code.gitea.io/gitea/vendor/code.gitea.io/git.(*Command).RunInDirTimeout()
Apr 07 14:24:41 DIR-101 gitea[31691]:       /home/mura/devel/go/src/code.gitea.io/gitea/vendor/code.gitea.io/git/command.go:96 +0xd1
Apr 07 14:24:41 DIR-101 gitea[31691]:   code.gitea.io/gitea/vendor/code.gitea.io/git.Fsck()
Apr 07 14:24:41 DIR-101 gitea[31691]:       /home/mura/devel/go/src/code.gitea.io/gitea/vendor/code.gitea.io/git/git.go:78 +0x103
Apr 07 14:24:41 DIR-101 gitea[31691]:   code.gitea.io/gitea/models.GitFsck.func1()
Apr 07 14:24:41 DIR-101 gitea[31691]:       /home/mura/devel/go/src/code.gitea.io/gitea/models/repo.go:1943 +0xe4
Apr 07 14:24:41 DIR-101 gitea[31691]:   code.gitea.io/gitea/vendor/github.com/go-xorm/xorm.(*Session).Iterate()
Apr 07 14:24:41 DIR-101 gitea[31691]:       /home/mura/devel/go/src/code.gitea.io/gitea/vendor/github.com/go-xorm/xorm/session_iterate.go:35 +0x1a1
Apr 07 14:24:41 DIR-101 gitea[31691]:   code.gitea.io/gitea/models.GitFsck()
Apr 07 14:24:41 DIR-101 gitea[31691]:       /home/mura/devel/go/src/code.gitea.io/gitea/models/repo.go:1951 +0x1fe
Apr 07 14:24:41 DIR-101 gitea[31691]:   code.gitea.io/gitea/vendor/github.com/gogits/cron.FuncJob.Run()
Apr 07 14:24:41 DIR-101 gitea[31691]:       /home/mura/devel/go/src/code.gitea.io/gitea/vendor/github.com/gogits/cron/cron.go:92 +0x34
Apr 07 14:24:41 DIR-101 gitea[31691]:   code.gitea.io/gitea/vendor/github.com/gogits/cron.(*Cron).runWithRecovery()
Apr 07 14:24:41 DIR-101 gitea[31691]:       /home/mura/devel/go/src/code.gitea.io/gitea/vendor/github.com/gogits/cron/cron.go:152 +0x68
Apr 07 14:24:41 DIR-101 gitea[31691]: Goroutine 228 (running) created at:
Apr 07 14:24:41 DIR-101 gitea[31691]:   code.gitea.io/gitea/vendor/code.gitea.io/git.(*Command).RunInDirTimeoutPipeline()
Apr 07 14:24:41 DIR-101 gitea[31691]:       /home/mura/devel/go/src/code.gitea.io/gitea/vendor/code.gitea.io/git/command.go:72 +0x25c
Apr 07 14:24:41 DIR-101 gitea[31691]:   code.gitea.io/gitea/vendor/code.gitea.io/git.(*Command).RunInDirTimeout()
Apr 07 14:24:41 DIR-101 gitea[31691]:       /home/mura/devel/go/src/code.gitea.io/gitea/vendor/code.gitea.io/git/command.go:96 +0xd1
Apr 07 14:24:41 DIR-101 gitea[31691]:   code.gitea.io/gitea/vendor/code.gitea.io/git.Fsck()
Apr 07 14:24:41 DIR-101 gitea[31691]:       /home/mura/devel/go/src/code.gitea.io/gitea/vendor/code.gitea.io/git/git.go:78 +0x103
Apr 07 14:24:41 DIR-101 gitea[31691]:   code.gitea.io/gitea/models.GitFsck.func1()
Apr 07 14:24:41 DIR-101 gitea[31691]:       /home/mura/devel/go/src/code.gitea.io/gitea/models/repo.go:1943 +0xe4
Apr 07 14:24:41 DIR-101 gitea[31691]:   code.gitea.io/gitea/vendor/github.com/go-xorm/xorm.(*Session).Iterate()
Apr 07 14:24:41 DIR-101 gitea[31691]:       /home/mura/devel/go/src/code.gitea.io/gitea/vendor/github.com/go-xorm/xorm/session_iterate.go:35 +0x1a1
Apr 07 14:24:41 DIR-101 gitea[31691]:   code.gitea.io/gitea/models.GitFsck()
Apr 07 14:24:41 DIR-101 gitea[31691]:       /home/mura/devel/go/src/code.gitea.io/gitea/models/repo.go:1951 +0x1fe
Apr 07 14:24:41 DIR-101 gitea[31691]:   code.gitea.io/gitea/vendor/github.com/gogits/cron.FuncJob.Run()
Apr 07 14:24:41 DIR-101 gitea[31691]:       /home/mura/devel/go/src/code.gitea.io/gitea/vendor/github.com/gogits/cron/cron.go:92 +0x34
Apr 07 14:24:41 DIR-101 gitea[31691]:   code.gitea.io/gitea/vendor/github.com/gogits/cron.(*Cron).runWithRecovery()
Apr 07 14:24:41 DIR-101 gitea[31691]:       /home/mura/devel/go/src/code.gitea.io/gitea/vendor/github.com/gogits/cron/cron.go:152 +0x68
Apr 07 14:24:41 DIR-101 gitea[31691]: Goroutine 135 (running) created at:
Apr 07 14:24:41 DIR-101 gitea[31691]:   code.gitea.io/gitea/vendor/github.com/gogits/cron.(*Cron).run()
Apr 07 14:24:41 DIR-101 gitea[31691]:       /home/mura/devel/go/src/code.gitea.io/gitea/vendor/github.com/gogits/cron/cron.go:185 +0x661
Apr 07 14:24:41 DIR-101 gitea[31691]: ==================
```
Followed by the message below every time when doing `git push -f`:

**Comment by lunny** [comment] 2017-04-20 08:50
Is this resolved already?

**Comment by typeless** [comment] 2017-04-20 09:22
I haven't seen the problem for a while after upgrade but I am not sure if it's 100% clean (there is a pending PR for issues probably related to this).

**Comment by lunny** [comment] 2017-04-20 09:28
Which one? I find all the three links issues to this one are merged or closed.

**Comment by typeless** [comment] 2017-04-20 09:47
@lunny #1470

**Comment by lunny** [comment] 2017-06-20 05:08
database lock is still exist on sqlite3 and move this to v1.3

**Comment by lunny** [comment] 2017-06-23 01:50
continue via #2040

**Closed as completed by lunny** 2017-06-23 01:50 UTC
Labels: type/bug
