### ISSUE TITLE
gitlab migrate mergerequests+issues fail

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#13884] opened 2020-12-07 07:43 UTC
gitea version: v1.13.0 - master

error message: `Migrate repository from https://gitlab.com/troyengel/archbuild failed: Error 1062: Duplicate entry '284-2' for key 'UQE_issue_repo_index'`

to reporduce:
 * create toke at gitlab.com
 * migrate https://gitlab.com/troyengel/archbuild with pulls and issues

if you only migrate one of them it works. so the problem is related to the workaround for new pull indexes

**Comment by troyengel** [comment] 2020-12-07 16:52
Hi all, for reference I reported this downstream in Codeberg, @6543 has extended that issue back upstream after pulling the logs above with their admin powers.

It appears to be Merge Requests; if I perform the webUI based import process (Gitlab -> Codeberg) and if I do not select the Merge Requests checkbox, everything else migrates in fine. I see that the MRs we in fact missing in the migrated-in repo on Codeberg, however the commits associated to them did come along OK. I have a second repo which had the exact same problem: https://gitlab.com/troyengel/Preloader  (both are open/public repos).

These repos were converted from Github -> Gitlab about 2 years ago so if there's something actually broken in the source data on Gitlab it may have sourced from that previous conversion. IIRC the MRs for `archbuild` were PRs on Github only, and the MRs on `Preloader` were some from Github and some from Gitlab both.

**Comment by techknowlogick** [comment] 2020-12-09 01:18
This is rather unusual, does that mean Gitlab doesn't maintain that issues and PRs must have unique numbers?

**Comment by rsnyman** [comment] 2020-12-20 17:54
@techknowlogick as far as I can tell, in GitLab issues and merge requests are completely separate, so they can easily have "clashing" IDs because they never share data (different tables in the DB I'm guessing). This is in contrast with GitHub which seems to make PRs and Issues the same thing.

**Comment by lunny** [comment] 2020-12-21 08:36
So we may have to change the id

**Comment by techknowlogick** [comment] 2020-12-28 20:19
> So we may have to change the id

We would need ensure that we modify comments/issues that link to PR use updated ID

**Comment by fortressia** [comment] 2021-12-15 09:53
Reproduced this on Docker. Slightly different log but same meaning. Running on v1.15.7.

```
gitea       | 2021/12/15 15:56:58 modules/task/task.go:54:handle() [E] Run task failed: pq: duplicate key value violates unique constraint "UQE_issue_repo_index"
```

Repository used for this: https://gitlab.com/EchidnaHQ/Echidna

**Comment by fortressia** [comment] 2021-12-15 10:07
> > So we may have to change the id
> 
> We would need ensure that we modify comments/issues that link to PR use updated ID

Don't forget about MR and issue references in Git commits. Of course we can't change them, because it will cause the commit to lose its original hash and thus making commit references in other commits problematic and it will unsign the signed commits, which is not nice because that's the only way to verify that a commit actually came from its author and not people spoofing the git author email and username.

**Comment by fortressia** [comment] 2021-12-15 14:13
Reproduced on Docker running version v1.16.0+dev-692-gf58e687a8.

```
gitea     | 2021/12/15 21:11:22 ...ervices/task/task.go:56:handle() [E] Run task failed: pq: duplicate key value violates unique constraint "UQE_issue_repo_index"
```

**Comment by fortressia** [comment] 2021-12-18 03:12
Wait, there's a fix for this already.

https://github.com/go-gitea/gitea/blob/8662ff68dae103f010dd634275d07b17d313d7de/services/migrations/gitlab.go#L589-L590

**Comment by douglasparker** [comment] 2023-06-27 09:38
This is still a major issue when migrating from GitLab. I had to drop all merge requests to avoid this error and successfully import my repositories.

**Comment by wetneb** [comment] 2023-12-08 21:35
This issue is fixed in Forgejo 1.21.2+0.

**Comment by delvh** [comment] 2023-12-08 21:55
I mean, this isn't forgejo, but yes, if it is fixed there, it most likely will be here too.

**Comment by wetneb** [comment] 2023-12-08 21:57
@delvh as far as I am aware, this is not fixed in Gitea yet: I submitted the corresponding pull requests to Forgejo, and I don't think they got cherry-picked by Gitea. So I would keep this issue open.

**Comment by hramrach** [comment] 2023-12-24 10:44
Can you link to the fix in forgejo?

Anyway, I suppose if this is to be fixed then

- An arbitrary prefix needs to be configured for # or ! references for the project (eg. 1000000). 
- #666 would map to #666, and !666 to #1000666 with 1000000 prefix configured for !
- All issues and PRs can be converted, and references in commit messages resolved as well.

This could be hardcoded but making it per-project configuration sounds more reasonable.

**Comment by wetneb** [comment] 2023-12-26 14:42
The fix is here: https://codeberg.org/forgejo/forgejo/pulls/1790

**Comment by lunny** [comment] 2023-12-26 15:02
> The fix is here: https://codeberg.org/forgejo/forgejo/pulls/1790

Can you send a PR to Gitea too?

**Closed as completed** 2023-12-26 17:57 UTC
Labels: type/bug, topic/repo-migration

**Comment by wxiaoguang** [comment] 2023-12-26 18:11
> The fix is here: https://codeberg.org/forgejo/forgejo/pulls/1790

That change doesn't seem ideal. For example, the `?` in filename breaks all Windows developers' workspace.

**Comment by hramrach** [comment] 2024-01-02 09:47
It's not ideal indeed. It's very explicit about inability to migrate more issues once any PRs are migrated.

In particular mirroring a repository cannot work this way.

Also it is not clear to me how the !1 reference to a PR in the commit message would be resolved with this solution.
