### ISSUE TITLE
Repo mirroring doesn't mirror LFS data.

### ISSUE THREAD

**Issue by damomurf** [go-gitea/gitea#849] opened 2017-02-06 00:42 UTC
- Gitea version (or commit ref): 1.0.0+220-g027591a3
- Git version:  2.11.0
- Operating system: Ubuntu 16.04 (Docker)
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=41700547)](https://www.bountysource.com/issues/41700547-repo-mirroring-doesn-t-mirror-lfs-data)

## Description

In a clean install of Gitea I have attempted to mirror a Bitbucket server repository that I know has LFS enabled and stores LFS data. The LFS data appears to not being mirrored in Gitea. (The configured LFS data directory remains empty, even though the repository mirroring *appears* to be successful).

**Comment by lunny** [comment] 2017-02-15 15:47
This is the same reason with #732. Let's close this and discuss there.

**Comment by fabian-z** [comment] 2017-02-24 01:03
I'm afraid I have to disagree: #732 is not related. Gitea cannot currently retrieve LFS objects from another server. This would basically require adding a complete LFS client on top of the current implementation.

@damomurf: Please see GitHub documentation regarding [repository mirroring with LFS](https://help.github.com/articles/duplicating-a-repository/#mirroring-a-repository-that-contains-git-large-file-storage-objects)

**Comment by lunny** [comment] 2017-02-24 01:40
Seems you are right.

**Comment by fabian-z** [comment] 2017-02-24 14:38
I'd suggest to tag this as a feature request. Current behaviour is basically expected imho and supporting LFS mirrors will be challenging in some regards:

* Need LFS client implementation
  * CLI client not developed for interactive use
  * Reusing source would require rewriting to some extent
* Using CLI client
  * Would use at least double the disk space for the LFS objects during mirror
  * Continuous mirror pulling would likely need double the disk space all the time
* The operation will need to scan all files in every commit for LFS meta files, potentially taking very long for large repositories

Just out of interest, does somebody know whether GitHub support automated LFS object mirroring?

For future reference: 
[GitLab issue](https://gitlab.com/gitlab-org/gitlab-ee/issues/1252), [git-lfs issue](https://github.com/git-lfs/git-lfs/issues/1762)

**Comment by lunny** [comment] 2017-02-24 14:59
Maybe put a notice on migrating UI at first.

**Comment by fabian-z** [comment] 2017-02-24 15:07
I'll look into adding a note to the UI when LFS support is enabled.

**Comment by boskiv** [comment] 2018-03-27 10:27
What is steps for mirroring LFS now? Is there some hook to make LFS pull with cmd ?
Or may be I need to setup some cron task ?

**Comment by fabian-z** [comment] 2019-02-27 11:52
@boskiv
You will currently have to manually mirror the repository if you wish to transfer the LFS objects, too.
It may or may not be (easily) possible to setup a custom mirror using cronjobs and shell scripts, but you would need to plan for double the disk space usage (permanently) and possibly use a separate local user account.

Please also see the [GitHub docs](https://help.github.com/articles/duplicating-a-repository/#mirroring-a-repository-that-contains-git-large-file-storage-objects) for manual steps.

**Comment by mloskot** [comment] 2019-04-26 11:09
BTW, the GitHub docs is what currently Git LFS recommends as per https://github.com/git-lfs/git-lfs/issues/2342#issuecomment-310323647

------

@fabian-z Forgive me if I'm hijacking the issue, but could you explain your last comment in more details, in the context explained below?

I have a GitHub repo with files in Git LFS.
I'm looking for solution to have Gitea serve mirror that repo (just Git repo).

TL;TR: Is it possible?

Would something along these lines work?

1. Mirror GitHub repo with LFS

    ```
    git clone --bare <GITHUB-URL> <GITHUB-DIR>
    git lfs fetch origin --all
    git push --mirror <GITEA-URL>
    git lfs push --all <GITEA-URL>
    ```

2. Attach Gitea to serve the files pushed to `<GITEA-URL>`

3. Frequently run

    ```
    cd <GITHUB-DIR>
    git fetch origin --all
    git lfs fetch origin --all
    git push --all <GITEA-URL>
    git lfs push --all <GITEA-URL>
    ```

**Comment by GlassedSilver** [comment] 2020-02-29 13:30
Is there anyone kinda sorta working on it? Or is there anyone who figured out a way how to do this manually/scripted externally for the time being?

I'm using Gitea to keep backups of software I use or just find interesting, just in case... Obviously having the LFS objects as well is often very handy, many times necessary.

**Comment by zeripath** [comment] 2020-02-29 14:25
No one is working on this. A bounty on bountysource might spur someone to look at it.

From a quick glance we would need to implement an LFS client - possibly through vendoring git-lfs/git-lfs. There would need to be significant changes to the mirroring UI too.

**Comment by GlassedSilver** [comment] 2020-05-28 13:07
Chipped in 70 bucks into the bounty: https://www.bountysource.com/issues/41700547-repo-mirroring-doesn-t-mirror-lfs-data

**Comment by GlassedSilver** [comment] 2020-06-02 04:04
Is it rude for me to ask for a maintainer of the repo to add the bounty tag and maybe declare the bounty value in the title?

Cheers and overall many many thanks for this lovely project to everyone who is working on it. It's of great use to me. :)

**Comment by techknowlogick** [comment] 2020-06-02 04:40
@GlassedSilver thanks for your support :) I've just applied the bounty label to make this easier to find.

**Comment by theAkito** [comment] 2020-07-05 13:27
I've upgraded from 6af13dbac to 15d3aa7b95e37cc2e9a06208089169cbe04383b5, because I had this issue on the former version. Now the issue is gone and mirroring works.

**Comment by kdumontnu** [comment] 2021-01-26 21:39
I added to this bounty. [![Bountysource](https://api.bountysource.com/badge/issue?issue_id=41700547)](https://www.bountysource.com/issues/41700547-feature-request-formatting-for-csv-diff)

Feel free to add the following code to the Issue:
```
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=41700547)](https://www.bountysource.com/issues/41700547-feature-request-formatting-for-csv-diff)
```

**Closed as completed** 2021-04-08 22:25 UTC
Labels: type/feature, issue/bounty, issue/confirmed
