### ISSUE TITLE
License display

### ISSUE THREAD

**Issue by Artem13327** [go-gitea/gitea#21125] opened 2022-09-09 17:09 UTC
### Feature Description

I suggest adding display licenses. It will be very convenient

### Screenshots

![изображение](https://user-images.githubusercontent.com/68551925/189405611-03112b80-a9f8-44bf-8554-c1bf61ca95a1.png)

**Comment by jolheiser** [comment] 2022-09-09 17:19
Duplicate of #278

**Closed as not planned by jolheiser** 2022-09-09 17:19 UTC
Labels: type/proposal, type/feature
