### ISSUE TITLE
Release 1.16.9 miss update of docker tags

### ISSUE THREAD

**Issue by nemunaire** [go-gitea/gitea#20354] opened 2022-07-13 09:46 UTC
### Description

Docker tags [`gitea/gitea:1`](https://hub.docker.com/layers/gitea/gitea/gitea/1/images/sha256-500c844373565654b72e882becc6d9e0cc010b3c71dd8df49be7e5942eb3ce60?context=explore) and [`gitea/gitea:1.16`](https://hub.docker.com/layers/gitea/gitea/gitea/1.16/images/sha256-500c844373565654b72e882becc6d9e0cc010b3c71dd8df49be7e5942eb3ce60?context=explore) (+`*-rootless`) still point to the `1.16.8` release. They don't have been updated to point to the `1.16.9` image.

Intermediate tags, arch specific ([`1.16-linux-amd64`](https://hub.docker.com/layers/gitea/gitea/gitea/1.16-linux-amd64/images/sha256-e769e9bf7cd634e83992d35b5b8c6705def2096a825f504149fa21d29f003a03?context=explore), ...) are presents, so it seems it's the docker manifest step for `:1.16` that's missing. Regarding `:1` tag, I don't see any arch specific tag neither.

### Gitea Version

1.16.9

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://user-images.githubusercontent.com/682394/178701107-5b544106-5b2f-46b0-ac79-c79a3539288f.png)

### How are you running Gitea?

Through Docker

**Comment by zeripath** [comment] 2022-07-13 17:40
Tag 1 is not being updated by 1.16.9

1.16 should have been updated.

**Comment by zeripath** [comment] 2022-07-13 18:14
what's interesting is that 1.16-linux-amd64 and 1.16-linux-arm64-rootless did get updated.

**Comment by zeripath** [comment] 2022-07-13 19:55
OK I've manually pushed 1.16 separately.

**Comment by nbr23** [comment] 2022-07-14 00:00
Thanks @zeripath! Looks like only the amd64 architecture image was tagged with 1.16 btw, not the arm64.
1.16.9 has both architectures.

**Comment by SuNNjek** [comment] 2022-07-14 09:35
Is there a reason that tag "1" is not being updated to 1.16.9? It has previously pointed to the latest patch and currently points to 1.16.8. Is there an alternative tag that can be pulled to get the latest stable release instead?

**Comment by zeripath** [comment] 2022-07-14 15:24
I had been told that 1 was pointing to 1.17-rc1 but it appears that that is not the case...

**Comment by zeripath** [comment] 2022-07-14 15:29
I've pushed  1.16.9 as 1.16 and 1 
and I've push 1.16.9-rootless as 1.16-rootless and 1-rootless

I hope that this is everything correct now.

**Comment by zeripath** [comment] 2022-07-14 15:30
ugh it looks like the arm64 ones also need to be pushed... ffs.

**Comment by lunny** [comment] 2022-07-14 15:34
> I've pushed 1.16.9 as 1.16 and 1 and I've push 1.16.9-rootless as 1.16-rootless and 1-rootless
> 
> I hope that this is everything correct now.

You should not push to 1.

**Comment by zeripath** [comment] 2022-07-14 16:33
It was fine. 1 was pointing at 1.16.8 not 1.17-rc1.

**Comment by zeripath** [comment] 2022-07-14 16:34
The issue is that I cannot push an arm64 tag as those need manifests.

We could just release 1.16.10 once I have restored auto_tagging.

**Comment by techknowlogick** [comment] 2022-07-14 17:58
@daschu117 Yeah, sadly working with docker manifests is troublesome. I'm attempting to get both archs copied over using the skopeo cli tool. Will update here once I have something to report.

**Comment by techknowlogick** [comment] 2022-07-14 20:55
closing this as sync is done. for future reference the skopeo command I used was something like `skopeo copy -a --policy temp.json docker://gitea/gitea:1.16.9-rootless docker://gitea/gitea:1-rootless` for the images I updated.

**Closed as completed by techknowlogick** 2022-07-14 20:55 UTC
Labels: type/bug, topic/build
