### ISSUE TITLE
Issues filter not working for parts of the words

### ISSUE THREAD

**Issue by stuzer05** [go-gitea/gitea#25251] opened 2023-06-14 08:13 UTC
### Description

When you search for issues, filter should work as SQL LIKE query "%query%" for issue title and description. Currenty in order to find anything you have to type the whole word. Otherwise, unless you know the whole word (in singular o plural) the search is pretty useless.

### Gitea Version

trunk

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker

### Database

None

**Comment by lunny** [comment] 2023-06-15 01:33
It depends on your issue indexer engine. If you are using `db` engine, this should not be a problem.

**Comment by wolfogre** [comment] 2023-07-27 08:04
As lunny said, "if you are using `db` engine, this should not be a problem." Because `db` is not a real search engine like Bleve/Elasticsearch/Meilisearch.

A real search engine need to divide words and build [inverted index](https://en.wikipedia.org/wiki/Inverted_index), that's why it has better performance then "db like". Some engines could handle plural or even typo well, but It requires additional configuration for specific languages.

Think about this, when you search "git" on Google, why can't you see "**git**ea"? It's not a bug of Google, just like it's not a bug of Gitea either.

I'm going to close this issue, please feel free to comment or reopen.

**Closed as not planned by wolfogre** 2023-07-27 08:04 UTC
Labels: issue/not-a-bug
