### ISSUE TITLE
Webhooks on mirrored repositories broken

### ISSUE THREAD

**Issue by serverwentdown** [go-gitea/gitea#5441] opened 2018-12-01 13:34 UTC
- Gitea version (or commit ref): bc42b3a
- Git version: 2.18.1
- Operating system: Docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No (try.gitea.io won't sync the mirror)
  - [ ] Not relevant
- Log gist:

## Description

Gitea synchronizes mirrors but triggering the webhooks fails with no error and the webhook does not get called, contuary to #4127. Pressing "Test Delivery" however, triggers the webhook successfully and causes previous failed webhooks to succeed. 

## Screenshots

<img src="https://user-images.githubusercontent.com/1705906/49328760-a8369a00-f5b0-11e8-9cb5-8434193fff4d.png" width="240">

**Comment by stormmore** [comment] 2018-12-03 21:31
I am also facing this issue and I am using a PG backed instance. I have found that restarting Gitea has the resulting effect of sending the "missed" deliveries!

(Edit: FYI my instance's commit is `0da8bc9`)

**Comment by stormmore** [comment] 2018-12-17 07:06
This is also happening on commit `ad9f9cd` and to confirm only for events that come in from the mirrors being synced.

I have an Org level webhook that works properly for other repos that are not mirrors.

**Comment by ericsgagnon** [comment] 2019-01-07 20:09
still an issue on v1.7 release - commit 41a2bfe, docker image deployment with PG backend. Mirroring from a gitlab repo.

**Comment by stefanak-michal** [comment] 2019-01-16 07:21
Hi. 
I've same problem. I have webhook for create/delete repository in organization. Its working only for delete repository.

- Gitea version (or commit ref): 1.7 (41a2bfe)
- Git version: 2.18.0
- Operating system: CentOS 7
- Database (use [x]):
  * [ ] PostgreSQL
  * [x] MySQL (MariaDB 15.1)
  * [ ] MSSQL
  * [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  * [ ] Yes (provide example URL)
  * [x] No (It's running on private network)
  * [ ] Not relevant
- Log gist:

![vystrizek](https://user-images.githubusercontent.com/5502917/51232337-9e050b00-1966-11e9-8dec-e79367b53559.PNG)

I created webhook for it, because new created repository is not automatically assigned to all teams of owner organization. I'm just doing few API request with webhook target php script. If there is another option how to achieve it, I'll be glad for response.

**Comment by tgly307** [comment] 2019-01-22 01:50
Same problem in 1.6.2 release.

**Comment by stefanak-michal** [comment] 2019-01-22 09:15
One more information, I have this problem with normal repositories, not mirror.

**Comment by ryan-harper-dentsu** [comment] 2019-03-13 11:34
same issue her for me as @stefanak-michal . Delete works but not the create for a repository.

**Closed as completed** 2019-07-06 20:01 UTC
Labels: type/bug, issue/confirmed
