### ISSUE TITLE
Cross Repo Issue Dependencies

### ISSUE THREAD

**Issue by jag3773** [go-gitea/gitea#7405] opened 2019-07-09 19:44 UTC
## Description

As a follow on to https://github.com/go-gitea/gitea/pull/2531, it would be excellent if this could be extended to allow cross repo dependencies.  Being able to link across different projects would be a powerful way to model dependencies between projects.

Use case: as a project manager I want to be able to create a dependency between issues in different projects (repos).  For example, I may have an API codebase in a separate repo than a UI codebase.  I have a feature request to add something to the UI that depends on building the API component first.

## Implementation Notes

I wouldn't want the suggestion list to explode to any possible issue on a server but it would seem reasonable to suggest issues that the user has recently visited (Trello uses this method in their attachment UI).  However, even without that, simply being able to paste in any issue URL would be acceptable functionality (for me).

**Comment by bhalbright** [comment] 2019-08-12 13:42
Hello, just wanted to post that I am working on this in a fork. I haven't pushed any changes up yet but changing to query across repos that the user has access to seems straightforward, but some of the things that fall out afterwards require some thought. For example, when a user looks at an issue with a dependency to an issue in another repo that they can't access, what do they see? Also I think the view in the search to add a dependency (and the list of dependencies) should indicate what repo the issue originated from (like possibly show the repo's avatar). Anyway, any thoughts please let me know, thanks!

**Comment by lunny** [comment] 2019-08-13 12:37
Users who have read permission of issues units on both repositories could do a reference.

**Comment by jag3773** [comment] 2019-08-14 12:40
Somewhat related, probably using GitHub's `org/repo#1234` syntax would be good for showing and maybe even typing in relations (in addition to straight urls).

For example, this issue is go-gitea/gitea#7405 (`go-gitea/gitea#7405`).

This regex `(?P<org>[a-zA-Z0-9_-]+)/(?P<repo>[a-zA-Z0-9_-]+)#(?P<id>[0-9]+)` should map into `https://example.com/%(org)s/%(repo)s/issues/%(id)s`.

**Comment by bhalbright** [comment] 2019-08-24 19:39
Thoughts on this layout of showing the dependencies? This is the same as how the issues are displayed on the issues page at http://<url>/issues. 

![view](https://user-images.githubusercontent.com/32200834/63641972-ec0c8a80-c67c-11e9-8a4f-303b87fc579c.png)

**Comment by guillep2k** [comment] 2019-08-25 00:23
The gray button style looks very much like topics do (those are not bold, though). What about something like this?:

![image](https://user-images.githubusercontent.com/18600385/63643999-0746bc80-c6b4-11e9-91ec-ab1d58628f84.png)

I think that it's useful that the color palette is the same as for "normal" issues.

In my company repository names are much longer than "repo2",  though. For example, "lib-comunicaciones" or "ProductDesignNotes". I don't know how would that look. Another possibility is to use only the issue number and leave some visual indication that the issue is not local (e.g. instead of `#236` use `#235*`) and use some kind of mouseover tooltip for the full repository name.

Anyway, this is just for the sake of leaving you some feedback. I'm cool with leaving it the way you propose.

**Comment by bhalbright** [comment] 2019-08-25 19:04
Thanks for the feedback, I like your suggestions, what do you think about this idea that emphasizes the issue name and shows the repo name on a separate line...

![image](https://user-images.githubusercontent.com/32200834/63654527-f98b4880-c740-11e9-829b-b76236cc29de.png)

**Comment by bhalbright** [comment] 2019-08-25 20:14
also, FWIW here is a possible view of the search results

![image](https://user-images.githubusercontent.com/32200834/63655203-fb5a0980-c74a-11e9-9046-7f3899607370.png)

**Comment by guillep2k** [comment] 2019-08-25 20:32
It looks OK. The fact that the issue titles are all made up might confuse a little, because they look less relevant than the numbers (i.e. `[#1]` looks more relevant than `this is a cool issue!`), but in real life the issues will have better titles.

I'd separate the repository name from the number with a space (`balbright/Repo2 #2` vs. `balbright/Repo2#2`) because when they are together the look like HTTP anchored links.

**Comment by bhalbright** [comment] 2019-09-03 03:05
@guillep2k  thanks, sorry for the delay didn't have much time last week to work on this...wanted to run one more by you guys, hope I'm not beating a dead horse. The layout in the view where you list the dependencies below is based on what github does when you search for issues across all of github. I wanted to do the same in the search dropdown but floating the issue # to the right didn't look right in the small box so I put it to the left of the title there. 


![image](https://user-images.githubusercontent.com/32200834/64141409-8a12fa00-cdcd-11e9-9358-022ac3590f0e.png)

**Comment by guillep2k** [comment] 2019-09-03 03:23
Looks good to me.

**Comment by mappu** [comment] 2020-01-16 01:26
Cross-repository dependencies have appeared in my 1.11.0-rc1 installation.

But there is a problem with mentions - the inline "X added a new dependency" message still links to the current repository, not the target repository

**Comment by lunny** [comment] 2020-01-16 01:44
@mappu could you fire another issue to report that? I will close this one since it has been implemented.

**Comment by guillep2k** [comment] 2020-01-16 03:53
> 
> 
> Cross-repository dependencies have appeared in my 1.11.0-rc1 installation.
> 
> But there is a problem with mentions - the inline "X added a new dependency" message still links to the current repository, not the target repository

@mappu that bug was already reported at #9765 👍

**Comment by 6543** [comment] 2020-01-17 06:20
does #7901 not close this issue ?!?

**Comment by bhalbright** [comment] 2020-01-17 14:22
> does #7901 not close this issue ?!?

yeah I would agree the issue could be closed

**Closed as completed** 2020-01-17 14:45 UTC
Labels: type/proposal
