### ISSUE TITLE
Commits using non-primary email address don't show up in heatmap

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#14284] opened 2021-01-07 22:10 UTC
- Gitea version (or commit ref): 1.13.1
- Git version: 2.20.1
- Operating system: Debian 10.6
  - Gitea binary downloaded from GitHub releases
  - Gitea is being run using systemd
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description

Commits made using a non-primary email address don't show up as contributions on the contribution heatmap.

As stated above, I couldn't repro on try.gitea.io, was this fixed in 1.14?

**Comment by AstroBadger** [comment] 2021-01-07 22:22
Okay, I think that's actually working as it should, but the graph is off by one day.

Both the server and the clients are on Central Time, does Gitea have it's own timezone settings?

**Comment by noerw** [comment] 2021-01-09 10:12
duplicate of #6087

**Closed as completed by noerw** 2021-01-09 10:12 UTC
Labels: issue/duplicate
