### ISSUE TITLE
PR comment causes 500 server error

### ISSUE THREAD

**Issue by otbutz** [go-gitea/gitea#7113] opened 2019-06-03 07:56 UTC
- Gitea version (or commit ref): 1.8.1
- Git version: 2.21
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

```
2019/06/03 07:48:37 [.../repo/pull_review.go:80 CreateCodeComment()] [E] CreateCodeComment: pq: invalid byte sequence for encoding "UTF8": 0xb3
```

## Description
No matter which file i'm trying to comment in this particular PR, the same error happens. Simply writing `test` in the comment generates the same issue.

**Comment by zeripath** [comment] 2019-06-03 09:30
I suspect the issue is that the underlying code line and Patch component here is not UTF-8: https://github.com/go-gitea/gitea/blob/45f588e85dbd3004334718dc9fbbb27675814ee0/models/issue_comment.go#L938

**Comment by zeripath** [comment] 2019-06-03 10:13
OK looking at:

https://github.com/go-gitea/gitea/blob/45f588e85dbd3004334718dc9fbbb27675814ee0/models/issue_comment.go#L922-L926

The issue is that `patchBuf.String()` doesn't actually guarantee that the String is a valid UTF-8 string. (Thanks Go(!)) Git diff gives you the raw bytes - it doesn't care about the encoding.

**Comment by zeripath** [comment] 2019-06-03 12:36
@otbutz is there any chance you could upload a minimal test file to try.gitea.io it would be nice to know which encoding breaks this.

**Comment by otbutz** [comment] 2019-06-03 12:48
Not really. Corporate project.

**Comment by lafriks** [comment] 2019-06-07 21:48
Duplicate of #6236

**Closed as completed** 2019-06-07 21:49 UTC
Labels: issue/duplicate
