### ISSUE TITLE
Home page for large repositories is slow

### ISSUE THREAD

**Issue by tonycoz** [go-gitea/gitea#8882] opened 2019-11-08 14:09 UTC
- Gitea version (or commit ref):1.9.4
- Git version:2.22.0
- Operating system:Debian Linux (but using the official docker container)
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Loading the index page for large repositories is slow, loading:

https://try.gitea.io/tonycoz/perl5

takes 15000 to 19000 ms, the similar page on github:

https://github.com/perl/perl5

loads in 2000ms

## Screenshots

![image](https://user-images.githubusercontent.com/166429/68481997-ae3afd80-028c-11ea-9680-d1ca1c224884.png)

**Comment by davidsvantesson** [comment] 2019-11-08 15:25
Duplicate of #491. 
It is the combination of many files/directories and many commits that makes it slow.

**Closed as completed** 2019-11-08 15:44 UTC
Labels: issue/duplicate
