### ISSUE TITLE
Webhook is not triggered by mirror updated

### ISSUE THREAD

**Issue by tgly307** [go-gitea/gitea#4659] opened 2018-08-10 02:40 UTC
- Gitea version (or commit ref): 0e04a20  and 1.5.0-rc2
- Git version: 2.18.0
- Operating system: windows 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/freemagico/test)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
I created an mirror from github and set up a webhook for all events for this mirror . There is an update after mirror synchronization but it does not trigger webhook. This update will also not be displayed on the dashboard.
I also tried this on https://try.gitea.io, the same thing happened.
I want to trigger webhook when the mirror is updated and display this event on the dashboard. 
Does gitea support this feature? Or what do I need to set up?

**Comment by lafriks** [comment] 2018-08-10 06:32
Duplicate of #1002

**Closed as completed by lafriks** 2018-08-10 06:32 UTC
Labels: issue/duplicate
