### ISSUE TITLE
Tag text unreadable

### ISSUE THREAD

**Issue by MGChecker** [go-gitea/gitea#18659] opened 2022-02-07 17:43 UTC
### Gitea Version

1.16.1

### Operating System

Linux

### Browser Version

Firefox

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

After the tag design change done in 1.16.x, many tag texts are rendered in black which were rendered in white before. For some colors, for example #207de5, this leads to text which is barely readable at best, especially if the tag is seen on white background.

In my opinion, an (at least) partial rollback of this text color change would be helpful.

### Screenshots

![Screenshot from 2022-02-07 18-42-29](https://user-images.githubusercontent.com/11667092/152842718-8d7d2afd-9020-4779-a9ed-ed31a99496f5.png)
![Screenshot from 2022-02-07 18-42-07](https://user-images.githubusercontent.com/11667092/152842739-1fbc1ce5-dada-4f5e-9e55-eca8a78f8a54.png)

**Comment by wxiaoguang** [comment] 2023-04-26 18:34
It should have been fixed in 1.19/1.20

**Comment by MGChecker** [comment] 2023-04-26 21:53
In 1.19.1, there is no improvement of the situation.

**Comment by wxiaoguang** [comment] 2023-04-27 02:42
The improved code is here, do you have ideas about your case?


https://github.com/go-gitea/gitea/blob/eea23bbc8ebb7589b4291d23b37106a32d81a834/modules/templates/helper.go#L543-L568

**Comment by MGChecker** [comment] 2023-04-27 08:14
To me, this is not really related to scoped labels. It's just about using white text on dark labels more aggresively.
![Screenshot from 2023-04-27 10-12-43](https://user-images.githubusercontent.com/11667092/234801415-240fee7b-1537-4c4e-a484-7c95b59ceab1.png)
![Screenshot from 2023-04-27 10-13-02](https://user-images.githubusercontent.com/11667092/234801459-d486ce16-9df7-4b94-857c-f62037ec99cc.png)

**Comment by MGChecker** [comment] 2023-04-27 08:17
I would expect an improvement from a change in
https://github.com/go-gitea/gitea/blob/58b414380371a4419f909491700673d43ae6b4ff/models/issues/label.go#L182
increasing this number slightly to `0.4` or something.

**Comment by wxiaoguang** [comment] 2023-04-27 08:20
> I would expect an improvement from a change in
> 
> https://github.com/go-gitea/gitea/blob/58b414380371a4419f909491700673d43ae6b4ff/models/issues/label.go#L182
> 
> increasing this number slightly to `0.4` or something.

Since it was contributed by #22585  .... @brechtvl  do you have some ideas about this issue? I am not color expert 😁

**Comment by wxiaoguang** [comment] 2023-05-11 11:29
After #24586 , `#207de5` looks good now

https://try.gitea.io/wxiaoguang/test/labels

![image](https://github.com/go-gitea/gitea/assets/2114189/1ebbe95d-eece-47f7-a41d-cb11f222b800)

**Comment by brechtvl** [comment] 2023-05-11 11:43
On that same page, this one is still not readable:
<img width="195" alt="enhancement" src="https://github.com/go-gitea/gitea/assets/450909/9c3525b6-6cab-46e4-8414-26c1e4dfc22e">

But I think this issue can't be fully solved by tweak the logic to decide between black and white text. For some label color neither of those will be have good contrast. This can be seen playing around with:
https://www.myndex.com/APCA/

Another thing is that the theme background color matters quite a bit for readability, something that's readable with a dark background may not be on a light background. GitHub uses a completely different rendering style in dark themes. To fully solve the problem I think either that is needed, or the label color should be automatically darkened or lightened and not be exactly what the user chose.

**Comment by MGChecker** [comment] 2023-05-11 12:06
For me, this seems to be due to the fact that the color of the text is not white, but grey for some reason (only really noticable with white background). The greyness reduces the contrast significantly. Still, generally it is an improvement over the status quo ante.

On dark background, the label is fine.

**Comment by wxiaoguang** [comment] 2023-05-11 12:11
The latest code in #24586 is `GetLuminance(r, g, b) < 0.453` (quote: " increasing this number slightly to 0.4 or something.")

So I guess this issue as a regression bug report it could be closed?  It could have new issues to make detailed plans for the further improvements, to make the discussion more focused.

**Comment by wxiaoguang** [comment] 2023-05-14 11:59
I think this issue could be closed. Thank you all.

**Closed as completed by wxiaoguang** 2023-05-14 11:59 UTC
Labels: topic/ui, issue/needs-feedback, issue/regression
