### ISSUE TITLE
Edit Authentication Source drops LDAPS

### ISSUE THREAD

**Issue by scs-kno** [go-gitea/gitea#18857] opened 2022-02-22 09:45 UTC
### Gitea Version

1.17.0+dev-175-gbd71245c5

### Operating System

"Ubuntu 20.04.2 LTS"

### How are you running Gitea?

docker-compose

### Database

SQLite

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

-

### Description

Using an "Authentication Source" with LDAP connecting to active-directory with "Enable LDAP groups". 

Making any changes, i.e. Edit Authentication Source, to any field will reset the `Security Protocol` field from `LDAPS` to `Unencrypted`.

**Comment by tcpluess** [comment] 2022-02-22 10:15
duplicate of #18766

**Closed as completed** 2022-02-22 11:45 UTC
