### ISSUE TITLE
Gitea stop without any message if redis is not available

### ISSUE THREAD

**Issue by 3l73** [go-gitea/gitea#6547] opened 2019-04-09 06:39 UTC
- Gitea version (or commit ref): 1.7
- Git version: N/A
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
  - [x] Redis
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

No log information.

## Description

Redis is used as indexer queue. In case the redis service is not up and running, gitea would not start.
This currently did not lead to any log entries (syslog or gitea log) or other informations.
In case gitea is start by hand, no error information is shown on the terminal.

**Comment by zeripath** [comment] 2019-04-09 15:19
This is due to the output of `log.Fatal` never actually being printed before `os.Exit()` is called in `modules/log/log.go`. This is fixed in #6095 - which will be in 1.9.

**Comment by zeripath** [comment] 2019-04-09 15:30
I don't think we can realistically backport the new logging infrastructure to 1.8 (or 1.7 for that matter).

If really required a simple hacky fix would be to change the level of the log to `log.Critical` and then `panic()`, or possibly replace the `os.Exit` in `log.Fatal` with a `panic()`

**Comment by lunny** [comment] 2019-04-09 16:03
@zeripath I also don't think it's necessary to back port that PR.

**Comment by zeripath** [comment] 2019-04-09 16:36
OK I think I'll close this issue as the issue is already fixed.

**Closed as completed by zeripath** 2019-04-09 16:36 UTC
Labels: type/bug
