### ISSUE TITLE
when i use gitmoji as comment to push，webhook push failed

### ISSUE THREAD

**Issue by itmisx** [go-gitea/gitea#13232] opened 2020-10-21 03:48 UTC
- Gitea version (or commit ref): 1.12.5
- Git version: 2.27.0
- Operating system: maxos
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x ] No
- Log gist:

## Description
when i use gitmoji as comment to push，webhook push failed
...

## Screenshots
![image](https://user-images.githubusercontent.com/5791324/96671020-6c1ea500-1393-11eb-8d5b-5f5dd76e6fb5.png)

**Comment by techknowlogick** [comment] 2020-10-21 03:49
@smally84 please complete the standard issue template with information about your instance so we know the version of software you use.

**Comment by techknowlogick** [comment] 2020-10-21 04:10
I see you use `MySQL` what charset do you use? utf8 or utf8mb4?

**Comment by smally84** [comment] 2020-10-21 04:45
> I see you use `MySQL` what charset do you use? utf8 or utf8mb4?

utf8mb4_general_ci

**Comment by zeripath** [comment] 2020-10-21 04:59
There is far too little detail in this issue report to even begin thinking of how to help you. 

> when i use gitmoji as comment to push，webhook push failed

What do you mean by push here?

Did you write a comment on a pull request, an issue or something else? Was it a code comment? A reply to a comment? Was it a code review? Presumably the comment was successfully created - it's just the webhook failed to send?

When you say webhook push - which type of webhook to what service? Is there any information about why it failed?

What about in the logs? 

Have you adjusted your logging to increase the log level to debug as described in our documentation and found the webhook logs?

**Comment by smally84** [comment] 2020-10-21 05:19
> There is far too little detail in this issue report to even begin thinking of how to help you.
> 
> > when i use gitmoji as comment to push，webhook push failed
> 
> What do you mean by push here?
> 
> Did you write a comment on a pull request, an issue or something else? Was it a code comment? A reply to a comment? Was it a code review? Presumably the comment was successfully created - it's just the webhook failed to send?
> 
> When you say webhook push - which type of webhook to what service? Is there any information about why it failed?
> 
> What about in the logs?
> 
> Have you adjusted your logging to increase the log level to debug as described in our documentation and found the webhook logs?

![image](https://user-images.githubusercontent.com/5791324/96676520-13093e00-13a0-11eb-9930-2969e6b7b660.png)

**Comment by smally84** [comment] 2020-10-21 05:38
> I see you use `MySQL` what charset do you use? utf8 or utf8mb4?

just now,i download the log.when i push code,there print the info contains these info
![image](https://user-images.githubusercontent.com/5791324/96677561-71cfb700-13a2-11eb-8436-2f1e8598a195.png)
and find the  err info.
![image](https://user-images.githubusercontent.com/5791324/96677624-9a57b100-13a2-11eb-87f2-305684d1e38b.png)
i check the table hook_task of the database,character set is utf8mb4

**Comment by zeripath** [comment] 2020-10-21 06:06
This is yet another duplicate of the MySQL UTF8 issues.

Despite having set the database and the tables to utf8mb4 you actually have to go through manually and change all of the columns to utf8mb4 too.

https://mathiasbynens.be/notes/mysql-utf8mb4

gitea convert does only the first two. 

On 1.13 there is a command: `gitea doctor recreate-tables` that would if you had called `gitea convert` first recreate the tables with the correct collation.

**Comment by smally84** [comment] 2020-10-21 08:00
> This is yet another duplicate of the MySQL UTF8 issues.
> 
> Despite having set the database and the tables to utf8mb4 you actually have to go through manually and change all of the columns to utf8mb4 too.
> 
> https://mathiasbynens.be/notes/mysql-utf8mb4
> 
> gitea convert does only the first two.
> 
> On 1.13 there is a command: `gitea doctor recreate-tables` that would if you had called `gitea convert` first recreate the tables with the correct collation.

![image](https://user-images.githubusercontent.com/5791324/96690519-5d95b500-13b6-11eb-9196-63cb6e2563e4.png)
there is no problem with column

**Comment by zeripath** [comment] 2020-10-21 11:09
The error with its code 1366 comes directly from MySQL itself. The text of the error reports the utf8 char bytes for :green_heart: : http://www.ltg.ed.ac.uk/~richard/utf-8.cgi?input=1F49A&mode=hex so its very clear that Gitea is sending the correct bytes to the DB.

There is a problem with the collation of the column, table, database or its connection.

If you have set the `CHARSET=utf8mb4` in the app.ini and run `gitea convert` already then you will need to change the columns manually or recreate the tables using the `gitea doctor recreate-table` command I mentioned above.

**Comment by smally84** [comment] 2020-10-22 12:28
> The error with its code 1366 comes directly from MySQL itself. The text of the error reports the utf8 char bytes for 💚 : http://www.ltg.ed.ac.uk/~richard/utf-8.cgi?input=1F49A&mode=hex so its very clear that Gitea is sending the correct bytes to the DB.
> 
> There is a problem with the collation of the column, table, database or its connection.
> 
> If you have set the `CHARSET=utf8mb4` in the app.ini and run `gitea convert` already then you will need to change the columns manually or recreate the tables using the `gitea doctor recreate-table` command I mentioned above.

thank you!
the problem is now resolved!
i setup gitea by docker,i modify the app.ini and run gitea convert and now is ok!

**Closed as completed** 2020-10-22 12:39 UTC
