### ISSUE TITLE
Avatars missing after upgrade

### ISSUE THREAD

**Issue by dpedu** [go-gitea/gitea#21677] opened 2022-11-04 03:57 UTC
### Description

I upgraded gitea and when I visited the UI again my avatar was broken. I had never uploaded an avatar, it was using a generated one though whichever mechanism is on by default.

Browsing directly to the avatar, at a URL like `http://myhost.com/avatars/724e29c9082c63514b653c5950f5f6fe?size=72`, would show the text "file not found".

I'm using the docker image to run gitea and many defaults from it. `AVATAR_UPLOAD_PATH = /data/gitea/avatars` and permissions look OK. The directory is empty, however. 

Turning up logging to `Trace` and attempting to load the above URL yielded simply:

```
2022/11/03 20:33:48 routers/web/base.go:99:2() [W] [6364881c] Unable to find avatars 724e29c9082c63514b653c5950f5f6fe
```

I didn't see anything else about avatars in the log, besides this which looked OK: 

```
2022/11/03 20:37:50 ...s/storage/storage.go:170:initAvatars() [I] Initialising Avatar storage with type:
2022/11/03 20:37:50 ...les/storage/local.go:46:NewLocalStorage() [I] Creating new Local Storage at /data/gitea/avatars
2022/11/03 20:37:50 ...s/storage/storage.go:188:initRepoAvatars() [I] Initialising Repository Avatar storage with type:
2022/11/03 20:37:50 ...les/storage/local.go:46:NewLocalStorage() [I] Creating new Local Storage at /data/gitea/repo-avatars
```

I went to my user settings and clicked "Delete Current Avatar", and when the page reloaded my avatar was loading again. I think it looks different than before, but I don't remember positively. 

Current version: 1.18.0+rc0 

I was using docker image version `gitea/gitea@sha256:75e556f3561804e9bcca0d860c2f0c475f1c21581f9aaf344e1e232f9aa4862d` previously
Upgraded to `gitea/gitea@sha256:e9509d44c94d3f8bc533e0d17d2ab3fe2b84aefe27d56b1857eebc2e6ab81b9e`

### Gitea Version

1.18.0+rc0 

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Docker / Ubuntu

### How are you running Gitea?

Docker / Ubuntu

### Database

SQLite

**Comment by russoj88** [comment] 2022-11-28 01:40
I backed up from a Gitea instance running on Arch, and restored to the docker container (both 1.17.3). I'm seeing the same issue. The attachments are also missing.

Uploading an avatar seems to put it in /app/gitea/data/avatars instead of /data/gitea/avatars.

**Comment by wxiaoguang** [comment] 2023-04-23 09:25
It seems an inconsistent path problem.

Do you have detailed reproducible steps for this problem?

**Comment by russoj88** [comment] 2023-04-23 18:48
> It seems an inconsistent path problem.
> 
> Do you have detailed reproducible steps for this problem?

I don't. This was about 5 months ago. I'm not sure how many upgrades I've done since then, and they've all been successful.

**Comment by wxiaoguang** [comment] 2023-04-24 06:22
Gitea's path system has a lot of technical debts .... I have no idea about how to reproduce it either .... maybe we could close this issue, until some more clues appear?

**Closed as completed** 2023-04-25 01:12 UTC
Labels: type/bug, issue/needs-feedback
