### ISSUE TITLE
Ui bug with nginx proxypass

### ISSUE THREAD

**Issue by alsoGAMER** [go-gitea/gitea#5461] opened 2018-12-04 10:42 UTC
- Gitea version (or commit ref): 1.6.0
- Git version: 2.11.0
- Operating system: Debian amd64 stable 9.6
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:
Idk what is it, i've attached gitea.log
[gitea.log](https://github.com/go-gitea/gitea/files/2643529/gitea.log)

## Description
I've proxypassed gitea under nginx, but the ui is pretty gone...

## Screenshots
With proxypass:
![image](https://user-images.githubusercontent.com/35269770/49436443-75132700-f7b9-11e8-8df7-866ca52fef60.png)

Without:
![image](https://user-images.githubusercontent.com/35269770/49436481-89572400-f7b9-11e8-89c3-7b3ce53fd305.png)

**Comment by lafriks** [comment] 2018-12-04 23:10
Can not reproduce such behaviour. Looks like something wrong in ngix configuration

**Comment by techknowlogick** [comment] 2018-12-04 23:12
Could be a missing (or an extra) trailing slash. Here are some basic recomendations for nginx https://docs.gitea.io/en-us/reverse-proxies/

I'm going to close this ticket, but if you have any follow ups please feel free to start a discussion in the forum https://discourse.gitea.io/

**Comment by alsoGAMER** [comment] 2018-12-04 23:12
@lafriks the nginx configuration is copied and pasted from the docs

**Closed as completed by techknowlogick** 2018-12-04 23:12 UTC
Labels: type/question
