### ISSUE TITLE
Show commits in conversation area for pull requests

### ISSUE THREAD

**Issue by russelltg** [go-gitea/gitea#3465] opened 2018-02-06 02:55 UTC
One feature that I find particurally useful on github is how when you add commits to a pull request, it shows the commits in the conversation view. This helps get a response-reply relationship with a reviewer and the pull-requester:

![image](https://user-images.githubusercontent.com/7105082/35839609-8d7e88e6-0aae-11e8-8e14-7a3d46d88659.png)

**Comment by lafriks** [comment] 2018-02-06 06:22
Duplicate of #2830

**Closed as completed** 2018-02-06 06:23 UTC
Labels: issue/duplicate
