### ISSUE TITLE
Error DB when I try to create a new command or add a user to a command

### ISSUE THREAD

**Issue by thisisusernameforgit** [go-gitea/gitea#14620] opened 2021-02-09 11:09 UTC
- Gitea version: 1.13.2 _(recently there was a migration from version 1.12.3 to 1.13.1 and then 1.13.2)_
- Git version: 2.22.0
- Operating system: Centos 7
- Database (use `[x]`):
  - [x] PostgreSQL
## Description

when I try to create a new command or add a user to a command, I can't. gives 500 error http and in the logs of the gitea I see the following lines:

```
2021/02/09 13:05:28 routers/org/teams.go: 114: TeamsAction () [E] Action (add): pq: duplicate key value violates unique constraint "org_user_pkey"
2021/02/09 13:06:00 routers/org/teams.go: 114: TeamsAction () [E] Action (add): pq: Duplicate key value violates unique constraint "org_user_pkey"
2021/02/09 13:07:51 routers/org/teams.go: 236: NewTeamPost () [E] NewTeam: pq: duplicate key value violates unique constraint "team_pkey"
2021/02/09 13:07:55 routers/org/teams.go: 236: NewTeamPost () [E] NewTeam: pq: duplicate key value violates unique constraint "team_unit_pkey"
2021/02/09 13:08:06 routers/org/teams.go: 236: NewTeamPost () [E] NewTeam: pq: duplicate key value violates unique constraint "team_pkey"
2021/02/09 13:23:12 routers/org/teams.go: 114: TeamsAction () [E] Action (add): pq: Duplicate key value violates unique constraint "org_user_pkey"
2021/02/09 13:23:27 routers/org/teams.go: 236: NewTeamPost () [E] NewTeam: pq: duplicate key value violates unique constraint "team_pkey"
2021/02/09 13:24:15 routers/org/teams.go: 236: NewTeamPost () [E] NewTeam: pq: duplicate key value violates unique constraint "team_unit_pkey"
2021/02/09 13:30:36 routers/org/teams.go: 236: NewTeamPost () [E] NewTeam: pq: duplicate key value violates unique constraint "team_pkey"
```

console commands "doctor"
**./gitea doctor recreate-table user**
```
2021/02/09 14:01:04 ... dules/setting/git.go: 91: newGit () [I] Git Version: 2.22.0, Wire Protocol Version 2 Enabled
2021/02/09 14:01:04 ... rm/session_schema.go: 25: Ping () [I] PING DATABASE postgres
2021/02/09 14:01:04 ... ations/migrations.go: 364: func1 () [I] Recreating Table: user for Bean: User
2021/02/09 14:01:05 ... rm/session_schema.go: 360: Sync2 () [W] Table user Column max_repo_creation db default is (-1), struct default is -1
```

the check says that everything is in order.
**./gitea doctor --all --fix -c /opt/gitea/custom/conf/app.ini**
```
[1] Check paths and basic configuration
- Configuration File Path: '/opt/gitea/custom/conf/app.ini'
- Repository Root Path: '/opt/20gb/git'
- Data Root Path: 'data'
- Custom File Root Path: '/opt/gitea/custom'
- Work directory: '/opt/gitea'
- Log Root Path: '/var/log/gitea'
OK.
[2] Check Database Version
OK.
[3] Check consistency of database
OK.
[4] Check if OpenSSH authorized_keys file is up-to-date
OK.
[5] Check if SCRIPT_TYPE is available
- ScriptType bash is on the current PATH at / bin / bash
OK.
[6] Check if hook files are up-to-date and executable
OK.
[7] Recalculate merge bases
- 0 PR mergebases updated of 0 PRs total in 149 repos
OK.
[8] Recalculate Stars number for all user
OK.
[9] Enable push options
- Enabled push options for 149 repositories.
OK.
```

What can be wrong? how can i fix this?

**Comment by zeripath** [comment] 2021-02-09 22:08
Your postgres sequences are out of sync. You're going to have to go in to postgres to sort them all out manually.

Take a look at:

https://stackoverflow.com/questions/244243/how-to-reset-postgres-primary-key-sequence-when-it-falls-out-of-sync

How did this happen? Did you use gitea dump and then restore at some point? I suspect dump doesn't update the sequences.

**Comment by graceastrid** [comment] 2021-02-09 22:37
> Your postgres sequences are out of sync. You're going to have to go in to postgres to sort them all out manually.
> 
> Take a look at:
> 
> https://stackoverflow.com/questions/244243/how-to-reset-postgres-primary-key-sequence-when-it-falls-out-of-sync
> 
> How did this happen? Did you use gitea dump and then restore at some point? I suspect dump doesn't update the sequences.

I don't remember anymore, but most likely it could be that I was restoring the database from a dump. i will try your advice, thanks

**Comment by graceastrid** [comment] 2021-02-10 09:33
> Your postgres sequences are out of sync. You're going to have to go in to postgres to sort them all out manually.
> 
> Take a look at:
> 
> https://stackoverflow.com/questions/244243/how-to-reset-postgres-primary-key-sequence-when-it-falls-out-of-sync
> 
> How did this happen? Did you use gitea dump and then restore at some point? I suspect dump doesn't update the sequences.

Thank you for your help! helped this:
SELECT pg_catalog.setval (pg_get_serial_sequence ('table_name', 'id'), (SELECT MAX (id) FROM table_name) +1);

from https://stackoverflow.com/questions/244243/how-to-reset-postgres-primary-key-sequence-when-it-falls-out-of-sync

**Comment by zeripath** [comment] 2021-02-10 14:08
OK I'll close this issue as the issue is solved. I think there may be an underlying issue with dump not sending the sequences but I think that should be left for a different issue.

**Closed as completed by zeripath** 2021-02-10 14:08 UTC
Labels: type/question
