### ISSUE TITLE
Markdown tables are rendered bellow the footer

### ISSUE THREAD

**Issue by Tagadda** [go-gitea/gitea#4212] opened 2018-06-10 16:23 UTC
- Gitea version (or commit ref): 1.4.2
- Git version: 2.17.1
- Operating system: Debian
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Description

I tried to include a table into my README.md and here is the problem :

https://git.cant.at/Tagada/FederationBot/src/commit/5f634760eace02a6516c8022f2bddd22c0403495/README.md

You can see that the table is way before the end of file in the source : https://git.cant.at/Tagada/FederationBot/raw/commit/5f634760eace02a6516c8022f2bddd22c0403495/README.md

I can't test on try.gitea.io since I don't receive the confirmation email to register...

This issue appear on [Gogs too](https://github.com/gogs/gogs/issues/5284).

## Screenshots

![](https://cant.at/i/OWk551Mh)

**Comment by SagePtr** [comment] 2018-09-13 00:46
This issue seems to be fixed in PR #3354 (doesn't reproduce after commit 535445c3, reproduces before it)

**Comment by lunny** [comment] 2018-09-13 03:31
Yes, it should be resolved. See https://try.gitea.io/lunny/FederationBot/src/commit/5f634760eace02a6516c8022f2bddd22c0403495 .

**Closed as completed by lunny** 2018-09-13 03:31 UTC
Labels: type/bug, topic/ui
