### ISSUE TITLE
init.d not works

### ISSUE THREAD

**Issue by Paul75** [go-gitea/gitea#4592] opened 2018-08-01 21:59 UTC
- Gitea version (or commit ref): 1.4.3
- Git version: 2.11.°
- Operating system: Debian 9 (arm)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I use your exemple to start automatically program : init/debian/gitea

but it failed : got : 

insserv: warning: current start runlevel(s) (empty) of script `gitea' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script `gitea' overrides LSB defaults (0 1 6).

Thanks

**Comment by andresbott** [comment] 2018-08-12 08:25
@Paul75  can you show startup example?

**Comment by lunny** [comment] 2018-11-07 11:10
Close this one since this should be a config problem not a bug of gitea I think. Please feel free to reopen it.

**Closed as completed by lunny** 2018-11-07 11:10 UTC
Labels: type/miscellaneous
