### ISSUE TITLE
[Bug] markdown link formater cant pars issue-url including comment-link

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#13842] opened 2020-12-04 06:38 UTC
Copy from https://codeberg.org/Codeberg/Community/issues/212
---
I just commented including this code:

`and https://codeberg.org/Codeberg/Community/issues/140#issuecomment-49756 is now`
-> `and #140 now`

so both the issue is not linked and the word after the URL is removed.

Inserting a second space after the url like so works:
`and https://codeberg.org/Codeberg/Community/issues/140#issuecomment-49756  is now`
-> `and [#140](https://codeberg.org/Codeberg/Community/issues/140#issuecomment-49756) now`

---

- Gitea version (or commit ref): 1.12.6 - master (1.14.0+dev-311-g3512c7e40)
- Can you reproduce the bug at https://try.gitea.io:
  - https://try.gitea.io/abcKing/noReaction/issues/1#issuecomment-70736

**Comment by noerw** [comment] 2021-09-25 10:44
In 1.16.0+dev-248-g45ebcb0d1 a new regression exists (not present in 1.15 as far as i can tell):

For a URL like `https://gitea.com/gitea/tea/pulls/410#issue-97552` a reference is correctly detected, but the URL is empty

![image](https://user-images.githubusercontent.com/7880552/134768660-ca428f2f-1c53-41a0-b546-b406bf3ea0d6.png)

**Comment by fnetX** [comment] 2021-11-20 16:48
The original issue seems to be fixed in 1.15, does the regression still exist?

**Comment by lunny** [comment] 2021-11-22 11:12
@fnetX I think no. It's reported in v1.14. Let's close and feel free to reopen it if it's not resolved.

**Closed as completed by lunny** 2021-11-22 11:12 UTC
Labels: type/bug

**Comment by wxiaoguang** [comment] 2021-11-22 11:15
I remember that I fixed a markdown bug:

* https://github.com/go-gitea/gitea/pull/17411

Are they related?

**Comment by fnetX** [comment] 2021-11-22 11:28
Yeah, #17394 is a dupe.
