### ISSUE TITLE
Mirror: Labels will be not migrated thru /repos/migrate API call

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#15090] opened 2021-03-21 16:08 UTC
- Gitea version (or commit ref): 1.13.4
- Git version:
- Operating system:
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

I'm using python script to migrate mirrors into Gitea

```
for (u, n) in zip(repo_urls, repo_names):
    print("repo_url=", u," / repo_name=", n)

    # Mirror to Gitea if I haven't forked this repository from elsewhere
    m = {
        "repo_name"         : n,
        "clone_addr"        : u,
        "mirror"            : True,
        "private"           : False,
        "issues"            : True,
        "labels"            : True,
        "milestones"        : True,
        "pull_requests"     : True,
        "releases"          : True,
        "wiki"              : True,
        "uid"               : 284
    }

    jsonstring = json.dumps(m)

    print("jsonstring...", jsonstring)

    r = session.post("{0}/repos/migrate".format(gitea_url), data=jsonstring)
    if r.status_code != 201:            # if not CREATED
        if r.status_code == 409:        # repository exists
            continue
        print(r.status_code, r.text, jsonstring)
```

Labels is set to TRUE, but labels will be not migrated. If I do the same thru Gitea UI -> Github mirror than labels are migrated.

Are all the values for the boolean parameters default values?

![image](https://user-images.githubusercontent.com/8334250/111912220-00875380-8a69-11eb-9035-b400c2e358ec.png)

**Comment by lunny** [comment] 2021-03-22 03:29
For mirrors, only git data and wiki data transfer are implemented. Other options is only for github/gitlab/gitea/gogs migrations.

**Comment by somera** [comment] 2021-03-22 10:00
> For mirrors, only git data and wiki data transfer are implemented. Other options are only for github/gitlab/gitea/gogs migrations.

ok. But if "service" isn't set in json request and it's an GitHub URL, which settings will be used?

**Comment by noerw** [comment] 2021-03-26 09:29
`service` defaults to `"git"`, as it is a common denominator.
If you want to autodetect service based on repo URL, you're very welcome to implement that! ;)
Relevant code:
https://github.com/go-gitea/gitea/blob/dc56fb7c84bb123614fb190319081e5a9bc18133/modules/convert/utils.go#L26

**Comment by somera** [comment] 2021-03-26 09:43
> `service` defaults to `"git"`, as it is a common denominator.
> If you want to autodetect service based on repo URL, you're very welcome to implement that! ;)

Lerning go is on my ToDo list ;)

**Comment by zeripath** [comment] 2021-03-26 10:40
OK so this is actually a feature request and not a bug - therefore I'm going to close this as not-a-bug @somera please consider re-opening with a feature request.

**Closed as completed by zeripath** 2021-03-26 10:40 UTC
Labels: issue/not-a-bug
