### ISSUE TITLE
Official arm/rpi docker image

### ISSUE THREAD

**Issue by schvabodka-man** [go-gitea/gitea#2607] opened 2017-09-26 08:05 UTC
Hello, there are currently only gitea images for x86. Would be cool if someone would build one for arm platforms. Gogs, for example has seperate image for rpi

**Comment by lafriks** [comment] 2017-09-26 09:04
There is already built binaries already for all platforms both on GitHub for releases and in https://dl.gitea.io/gitea/

**Comment by Kunde21** [comment] 2017-10-31 10:41
It's not official, but [this container](https://hub.docker.com/r/kunde21/gitea-arm/) is built (with sqlite support) for arm and is running on my rpi3.

**Comment by funkyfuture** [comment] 2018-01-31 21:33
a multi-arch manifest on the Hub would be a nice topping on this.

**Comment by sapk** [comment] 2018-02-01 15:25
@funkyfuture I plan to do a multi-arch setup (allready had but I separated it to ease the review process). Now, I wait for #2927 to be merged to go to next phase multi-arch.

**Comment by techknowlogick** [comment] 2018-05-10 04:37
This is a dupe of #531 

Can this issue be closed?

**Closed as completed** 2018-05-10 05:47 UTC
Labels: issue/duplicate, type/question
