### ISSUE TITLE
error migrate 1.14.7 to 1.15.11

### ISSUE THREAD

**Issue by tipsang** [go-gitea/gitea#21344] opened 2022-10-05 13:15 UTC
### Description

I want to migrate from version 1.14.7 to 1.15.11.
The platform is well accessed but when accessing any repository I get a 500 error.
The log shows this:
Render Failed: template: repo/branch_dropdown:12:126: executing "repo/branch_dropdown" at <.root.CommitId>: invalid value; expected string 
Template: status/500
What can happen?

### Gitea Version

1.15.11

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

1.15.11

### Operating System

windows Server

### How are you running Gitea?

Windows server + SQL Server

### Database

MSSQL

**Comment by wxiaoguang** [comment] 2022-10-05 13:46
The latest supported release is 1.17.x, please try to upgrade to 1.17.2

**Comment by tipsang** [comment] 2022-10-05 14:24
> The latest supported release is 1.17.x, please try to upgrade to 1.17.2

Error with 1.17.2
2022/10/05 16:19:51 cmd/web.go:95:func1() [F] PANIC: template: repo/home:67: function "EscapePound" not defined
	/usr/local/go/src/html/template/template.go:374 (0x240fab5)
	/go/pkg/mod/github.com/unrolled/render@v1.4.1/render.go:322 (0x240f836)
	/go/pkg/mod/github.com/unrolled/render@v1.4.1/render.go:202 (0x240ebee)
	/go/pkg/mod/github.com/unrolled/render@v1.4.1/render.go:146 (0x240e7c1)
	/source/modules/templates/base.go:86 (0x24bf73e)
	/source/routers/web/base.go:127 (0x2fbbe69)
	/source/routers/web/web.go:123 (0x2fbefab)
	/source/routers/init.go:174 (0x2fdeedc)
	/source/cmd/web.go:177 (0x30abc66)
	/go/pkg/mod/github.com/urfave/cli@v1.22.9/app.go:524 (0x29ef75f)
	/go/pkg/mod/github.com/urfave/cli@v1.22.9/command.go:173 (0x29f036b)
	/go/pkg/mod/github.com/urfave/cli@v1.22.9/app.go:277 (0x29ed333)
	/source/main.go:116 (0x30e2766)
	/usr/local/go/src/runtime/proc.go:250 (0x132fc00)
	/usr/local/go/src/runtime/asm_386.s:1326 (0x135ce70)

**Comment by techknowlogick** [comment] 2022-10-05 14:24
Are you using custom templates?

**Comment by tipsang** [comment] 2022-10-05 14:29
> Are you using custom templates?

I don't think so. How can I be sure?

**Comment by wxiaoguang** [comment] 2022-10-05 14:50
You must be using customized templates. https://docs.gitea.io/en-us/customizing-gitea/#customizing-gitea-pages-and-resources

Remove your customized templates then Gitea will work well.

**Comment by wxiaoguang** [comment] 2022-10-07 03:02
Since it doesn't seem to be a Gitea bug, I will close this issue.

Feel free to re-open if you can reproduce it with a fresh setup and confirm it's a bug, or if you would propose some solutions for the edge cases or update the documents to help to future users to get rid of similar problems.

**Closed as completed by wxiaoguang** 2022-10-07 03:02 UTC
Labels: issue/needs-feedback
