### ISSUE TITLE
[Feature] Add option to remove worked time from issue

### ISSUE THREAD

**Issue by delvh** [go-gitea/gitea#14351] opened 2021-01-15 14:53 UTC
- Gitea version (or commit ref): 1.13.1
- Git version: -
- Operating system: -

## Description
As far as I am aware, it currently is impossible to remove time a collaborator has (not) spent working on an issue/ a PR.
This is not exactly appreciable as humans are error prone. The moment you enter a wrong time or the moment you stop (instead of cancel) a timer that was forgotten to be stopped i.e. yesterday, you have no way of undoing it, at least to my knowledge.
If you enter a negative number in the popup behind the `Add time` button, a `RangeError` gets thrown, which is totally fine.
But the option to manually remove worked time should at least somewhere be present for the average user.

## What should be implemented
When the timer has not been activated, a (most-likely red) `Remove time` button should be displayed, at best to the right of the `Add time` button.

### Tangentially related time tracking problem
If a user cancels a timer, the corresponding start and cancel event in the issue/ PR history should be removed.

**Comment by noerw** [comment] 2021-01-17 20:39
duplicate of #2642 and will be fixed by #14100

**Closed as completed by noerw** 2021-01-17 20:39 UTC
Labels: issue/duplicate, outdated/theme/timetracker
