### ISSUE TITLE
Link at dashboard wrong

### ISSUE THREAD

**Issue by gsantner** [go-gitea/gitea#9954] opened 2020-01-23 19:19 UTC
- Gitea version (or commit ref): gbfdfa9a8b
- Git version: ka
- Operating system: ka
- Database (use `[x]`): ka
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/     (dashboard
  - [ ] No
  - [ ] Not relevant
- Log gist: ka

## Description
The links to repos from dashboard point to wrong place, resulting in not found error.

Wrong example: <https://try.gitea.io/%5C%22/gsantner/wefwqefw%5C%22>  
Correct: <https://try.gitea.io/gsantner/wefwqefw>

## Screenshots

![screenrecord](https://user-images.githubusercontent.com/6735650/73016187-47ea6380-3e15-11ea-939f-3c7ad0019a8c.gif)

**Comment by jolheiser** [comment] 2020-01-23 19:33
Is there any chance this is a browser issue somehow??

I cannot reproduce on try on my own dashboard or your public activity page.

**Comment by techknowlogick** [comment] 2020-01-23 19:34
Could be a translation file issue. Perhaps the sprintf for german has issues.

@gsantner thanks for gif, this really helps :)

**Comment by jolheiser** [comment] 2020-01-23 19:35
🤦‍♂ I didn't even think of that, but yes now I can reproduce with other languages

**Comment by gsantner** [comment] 2020-01-23 19:51
no problem, did the video soecifically so bottom-left is visible

**Comment by philippbeckmann** [comment] 2020-01-24 09:24
Seems like the commit https://github.com/go-gitea/gitea/commit/0e8b27afe8aaa9055be24f71e8543f2701f18291 from Crowdin introduced the escaped quotes. It also added a quote to the end of many strings.

**Comment by NiTRoeSE** [comment] 2020-01-24 21:06
I have the same problem with Dashboard links / i can confirm this bug. 
( All other links in Gitea are working well on my side.. )

Links for repository (red) and branch(red) are false. Link for user (green) works.

![Bildschirmfoto 2020-01-24 um 22 00 44](https://user-images.githubusercontent.com/24574743/73103895-6aec4480-3ef5-11ea-90a9-62854431e649.png)


This links are as follows ..."%5C%22" is added two times..
`https://gitea.domain.de/%5C%22/nitro/nativefier_docker_py%5C%22`

- Gitea Version: 1.12.0+dev-151-g3185a13ea (docker)
- Proxy Apache

Thanks 4 help & your work :)

**Comment by jolheiser** [comment] 2020-01-30 03:44
I think this has been fixed by #9969 and #9977

**Comment by techknowlogick** [comment] 2020-01-30 05:13
yes, I think so as well. I will close this issue. If it remains an issue after upgrading please re-open this issue for us to investigate more.

**Closed as completed by techknowlogick** 2020-01-30 05:13 UTC
Labels: type/bug
