### ISSUE TITLE
Not able to merge commit in PR when branches content is same, but different commit id

### ISSUE THREAD

**Issue by jedi7** [go-gitea/gitea#19603] opened 2022-05-04 07:55 UTC
### Description

Hi,
there is missing button for commit in pull request, when branches are same but there is commit to merge.
steps to reproduce:

1) "**merge --no-ff**"  from "develop" to "master"
2) create tag on master
3) create PR from "master" to "develop"
4) missing button for merge
PR says the files diff is empty (that is correct).
But also **in PR is 1 commit** with the merge info and created tag, which should be merged into "develop"
(just usual git flow)

### Gitea Version

1.16.7

### Can you reproduce the bug on the Gitea demo site?

Yes

https://try.gitea.io/jedi7/test_19603/pulls/1

### Git Version

2.25.1

### Operating System

ubuntu

### How are you running Gitea?

docker container

### Database

MySQL

**Comment by delvh** [comment] 2022-05-04 08:26
I think you misunderstood Git slightly:
When you create a tag, you don't create a (new) commit (with changes).
You instead create a pointer to an existing commit.
There is nothing to commit because no changes were made.
So it makes sense that the branches are equal... because they are.
Git simply knows then that the tag to that commit exists.

**Comment by jedi7** [comment] 2022-05-04 08:43
can you please try the steps to reproduce? You will see it is real scenario, where the commit is created "

See:
`commit 64dc9f325959c7d56f8c48c68b47607d1442d8ed (tag: RELEASE-4.0.0, origin/master, origin/develop, origin/HEAD, develop)
Merge: 24d4a6bcd fbc80940a
Author: censored
Date:   Wed May 4 08:44:03 2022 +0200

    Merge pull request 'release/v4.0' (#135) from release/v4.0 into master

commit fbc80940ac8d6a2fe1ddcfc988865eefda5b94a4 (origin/release/v4.0)
Merge: bffcadfe4 0fc5acd6e
Author: censored
Date:   Fri Apr 29 09:24:24 2022 +0200
`
$ git diff fbc80940ac8d6a2fe1ddcfc988865eefda5b94a4 64dc9f325959c7d56f8c48c68b47607d1442d8ed
$

As you can see, there is empty commit. But the commit is still valid and it carry the tag.

**Comment by jedi7** [comment] 2022-05-04 08:45
I must did manual merge and push to develop without PR, to be able get the tag into develop.

**Comment by wxiaoguang** [comment] 2022-05-04 08:50
Are the commit IDs the same when you doing step 3 `create PR from "master" to "develop"`? If yes, that's expected behavior.

If you consider there is something unclear, please show your git branches history before merge.

**Comment by jedi7** [comment] 2022-05-04 09:06
steps to reproduce:
```
git init
git add  README.md
git commit -m "initial"
git checkout -b develop
echo "test" > ./README.md
git commit -a -m "test"
git checkout master
git merge --no-ff develop
git log
# now you can see the merge commit, but diff is empty between them, see bellow
git tag MyTag
# tag will be on the merge commit, so no visible in develop

# so I need to merge master into develop, but not possible with gitea PR (bug)
git checkout develop
git merge master
```
```
jedi@tpol 11:05:51 ~/Projects-tests/tests-git/xx $ git co master
Switched to branch 'master'
jedi@tpol 11:05:54 ~/Projects-tests/tests-git/xx $ git log
commit 3b2220b16b9a542d2879eebdc7e9bd0f8a6a72d6 (HEAD -> master, tag: MyTag)
Merge: df1d83b fd437e0
Author: Ing. Jaroslav Safka <devel@safka.org>
Date:   Wed May 4 11:02:28 2022 +0200

    Merge branch 'develop'

commit fd437e0498d75cc25d9494f8ff4d807510d72d92 (develop)
Author: Ing. Jaroslav Safka <devel@safka.org>
Date:   Wed May 4 10:57:55 2022 +0200

    test

commit df1d83b5339dfe1155a12e0cc86085e3432addf1
Author: Ing. Jaroslav Safka <devel@safka.org>
Date:   Wed May 4 10:56:09 2022 +0200

    initial
jedi@tpol 11:05:56 ~/Projects-tests/tests-git/xx $ git co develop
Switched to branch 'develop'
jedi@tpol 11:06:02 ~/Projects-tests/tests-git/xx $ git log
commit fd437e0498d75cc25d9494f8ff4d807510d72d92 (HEAD -> develop)
Author: Ing. Jaroslav Safka <devel@safka.org>
Date:   Wed May 4 10:57:55 2022 +0200

    test

commit df1d83b5339dfe1155a12e0cc86085e3432addf1
Author: Ing. Jaroslav Safka <devel@safka.org>
Date:   Wed May 4 10:56:09 2022 +0200

    initial
jedi@tpol 11:06:05 ~/Projects-tests/tests-git/xx $ git diff fd437e0498d75cc25d9494f8ff4d807510d72d92 3b2220b16b9a542d2879eebdc7e9bd0f8a6a72d6
jedi@tpol 11:06:19 ~/Projects-tests/tests-git/xx $
```

**Comment by jedi7** [comment] 2022-05-04 09:08
> Are the commit IDs the same when you doing step 3 `create PR from "master" to "develop"`? If yes, that's expected behavior.
> 
> If you consider there is something unclear, please show your git branches history before merge.

They are not same, there is 1 commit. (the merge commit)

**Comment by wxiaoguang** [comment] 2022-05-04 09:12
There seems some misunderstanding.

> # tag will be on the merge commit, so no visible in develop

tag is not binded to branch. it's visible to the whole git repository after push.

> # so I need to merge master into develop, but not possible with gitea PR (bug)

you shouldn't, because now develop is the parent of master and there is no change at all.

**Comment by wxiaoguang** [comment] 2022-05-04 09:14
ps: I suspect that you were a `hg` users, which binds tags to branches. 😂

**Comment by jedi7** [comment] 2022-05-04 09:30
that is not about tags, sorry if I confuse you. It is about the empty merge commit, which I need merge by PR to develop branch.
Please see the example which I posted

**Comment by wxiaoguang** [comment] 2022-05-04 09:31
Sorry but it's beyond my knowledge. Let's re-open the issue to see if there are other suggestions.

**Comment by jedi7** [comment] 2022-05-04 09:33
![image](https://user-images.githubusercontent.com/24191306/166656520-18fd04ed-332d-4cf1-a0d9-47f95d56c1dd.png)

**Comment by Gusted** [comment] 2022-05-04 20:48
The code responsible for this:
https://github.com/go-gitea/gitea/blob/f034ee6cf0ab0806ef0b8edb5f38e6a5c37f2f7c/services/pull/patch.go#L295-L297

More or less because the SHA1 of the merge commit is the same as the develop branch it thinks the pull request is empty... I'm not sure what the correct behavior would be here(maybe add a extra check here, or completely removing it? Changing this check to be more explicit about equal last commit of the branches?)

**Comment by jedi7** [comment] 2022-05-05 04:23
What about to just take last commit id from the branches and compare them? Is it possible?
If I understand, the write-tree recreates id from files (which are same in this situation), so no usable here :(

**Comment by Gusted** [comment] 2022-05-05 22:19
> What about to just take last commit id from the branches and compare them?

The commitID's are equal. I think we should check here if the amount of commits in the tree's aren't equal. Not sure about generating the diff, but seems like that would be more trickier(what's Github/Gitlab's behavior in this situation?)

**Comment by jedi7** [comment] 2022-05-06 04:15
> > What about to just take last commit id from the branches and compare them?
> 
> The commitID's are equal. I think we should check here if the amount of commits in the tree's aren't equal. Not sure about generating the diff, but seems like that would be more trickier(what's Github/Gitlab's behavior in this situation?)

Good thing is, they are not equal :) If we take them exactly as they are by "git rev-parse" for example.
They are equal only when are recreated by "git write-tree" (because diff / files content are the same).

**Comment by Gusted** [comment] 2022-05-08 03:00
> Good thing is, they are not equal :) If we take them exactly as they are by "git rev-parse" for example.
> They are equal only when are recreated by "git write-tree" (because diff / files content are the same).

I personally don't feel comfortable with messing the conflict checker. It's quite specialized in it's setup. So I don't think it's easy to simply change some commands to change the git repo's. AFAIK the commitID's will always be the same, no matter what. We simply have to add another check here that exclude this case.

**Comment by jedi7** [comment] 2022-05-08 04:26
@Gusted Not sure what you mean by commits id will be always the same. When you try the example above, you can compare them and see they have different ID's. 
Do you have idea, why the commits ID's are recreated from files (by write-tree) and are not used the real already present ID (taken by rev-parse for example) ?

**Comment by Gusted** [comment] 2022-05-08 04:53
> @Gusted Not sure what you mean by commits id will be always the same. When you try the example above, you can compare them and see they have different ID's.

In sense of `write-tree` it will always be the same CommitID, which the current code relies on.


> Do you have idea, why the commits ID's are recreated from files (by write-tree) and are not used the real already present ID (taken by rev-parse for example) ?

No idea, most likely it was the best solution then.

**Comment by jedi7** [comment] 2022-05-10 04:07
Tests are done on this git repo:
You can try merge branch paralel into master. Or master into develop.

[test-empty-merge-commit2.tar.gz](https://github.com/go-gitea/gitea/files/8657336/test-empty-merge-commit2.tar.gz)

**Comment by jedi7** [comment] 2022-05-10 04:12
@zeripath Maybe as author will be interested?

**Comment by wxiaoguang** [comment] 2022-07-14 00:22
Fixed by:
* #20290
* #20352

**Closed as completed by wxiaoguang** 2022-07-14 00:22 UTC
Labels: type/bug
