### ISSUE TITLE
 Implement Markdown Callouts for Enhanced Documentation Clarity

### ISSUE THREAD

**Issue by miztizm** [go-gitea/gitea#29032] opened 2024-02-03 05:54 UTC
### Feature Description

I propose the implementation of Markdown callouts in Gitea to enhance the clarity and effectiveness of documentation, issue discussions, and markdown files within repositories. Callouts, such as notes, tips, warnings, and cautions, are crucial for emphasizing important information, guiding users successfully through documentation, and ensuring critical warnings are not overlooked.

Markdown callouts would allow users to highlight various types of information distinctly, making it easier for readers to find and heed advice, warnings, and tips. The proposed syntax follows an intuitive format, leveraging Markdown's extensibility to include custom identifiers for different callout types:

- **Note (`!NOTE`)**: Highlights information that users should take into account, even when skimming.
- **Tip (`!TIP`)**: Provides optional information to help users be more successful.
- **Important (`!IMPORTANT`)**: Marks crucial information necessary for users to succeed.
- **Warning (`!WARNING`)**: Signals critical content that demands immediate attention due to potential risks.
- **Caution (`!CAUTION`)**: Indicates negative potential consequences of an action.

> [!NOTE]
> This is a note.

> [!TIP]
> This is a tip.

> [!IMPORTANT]
> This is an important note.

> [!WARNING]
> This is a warning.

> [!CAUTION]
> This is a caution.` 

#### Benefits

- **Enhanced Documentation Quality**: By making it easier to create visually distinct, categorized informational blocks, we can improve the overall quality and user-friendliness of documentation in Gitea.
- **Increased User Success**: Callouts can guide users more effectively through complex documentation, increasing their success and reducing frustration.
- **Improved Safety and Awareness**: Clearly marked warnings and cautions can prevent users from making mistakes that could have serious consequences.

**Comment by yardenshoham** [comment] 2024-02-03 08:26
Duplicate of https://github.com/go-gitea/gitea/issues/28316

**Closed as completed** 2024-02-04 03:29 UTC
Labels: type/proposal

**Comment by yardenshoham** [comment] 2024-02-10 18:46
It's ready. It will be part of version 1.22.0
