### ISSUE TITLE
Organisation repos are not changed order

### ISSUE THREAD

**Issue by Akcaxup** [go-gitea/gitea#6745] opened 2019-04-24 19:51 UTC
- Gitea version (or commit ref): 1.8.0 arm v6
- Git version: 2.1.4
- Operating system: Raspbian GNU/Linux 8
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Organisation repos are not changed order

## Screenshots
![Снимок экрана (3119)_cr](https://user-images.githubusercontent.com/32159064/56689032-cf6a4100-66e2-11e9-8695-56fc322d2668.png)
![Снимок экрана (3120)_cr](https://user-images.githubusercontent.com/32159064/56689039-d1cc9b00-66e2-11e9-8bab-9a0200e1d0ca.png)

**Comment by lafriks** [comment] 2019-04-24 21:11
Duplicate of #6511

**Closed as completed by lafriks** 2019-04-24 21:11 UTC
Labels: issue/duplicate
