### ISSUE TITLE
Actions, all steps success, but show running

### ISSUE THREAD

**Issue by seepine** [go-gitea/gitea#27635] opened 2023-10-16 02:54 UTC
### Gitea Version

1.20.4

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

<img width="420" alt="image" src="https://github.com/go-gitea/gitea/assets/93666053/7580dca1-fe3a-433f-b882-9aa99b28c012">

<img width="420" alt="image" src="https://github.com/go-gitea/gitea/assets/93666053/7a92a9d4-dab4-46a7-ae73-5d556bf20a79">

### How are you running Gitea?

docker

### Database

None

**Comment by CaiCandong** [comment] 2023-10-16 08:43
duplicate of #26559

**Closed as completed** 2023-10-19 15:05 UTC
Labels: type/bug
