### ISSUE TITLE
Is it possible for a Github-like version of Discussions to be added to Gitea?

### ISSUE THREAD

**Issue by C-EO** [go-gitea/gitea#20258] opened 2022-07-05 18:43 UTC
### Feature Description

I think it would bring Gitea a lot more people if it had Discussions.
The Discussions db could be hosted locally or in some other db like Redis, PostgreSQL, AWS S3 etc. and be called throught the API.

**Comment by Gusted** [comment] 2022-07-05 18:50
Duplicate of https://github.com/go-gitea/gitea/issues/17858

**Closed as not planned by Gusted** 2022-07-05 18:50 UTC
Labels: type/proposal, type/feature
