### ISSUE TITLE
Feature Request: Add a "Create New Issue" Button in Project/Board Pages

### ISSUE THREAD

**Issue by ekianjo** [go-gitea/gitea#17534] opened 2021-11-03 11:34 UTC
Hi, I find the Kanban board very useful to organize issues on Gitea, however the workflow is currently not ideal - you can only create an issue from the Issues tab, and very often I find myself wanting to creating issues when looking at the Project boards as well - this causes several back and forth between Issues and Project tabs which could be avoided by having a create issue button within the project page. 

Such a button would by default be assigned the "Project" variable from where you create the issue, to save a few clicks as well.

**Comment by wxiaoguang** [comment] 2021-11-03 15:36
Please try on try.gitea.io, it is there (for the latest release):

<img width="1189" alt="image" src="https://user-images.githubusercontent.com/2114189/140092459-eac3213d-48e5-494e-bec2-64d089a50340.png">

**Comment by sebthom** [comment] 2021-12-06 16:25
I think this is a duplicate of https://github.com/go-gitea/gitea/issues/14824

**Closed as completed** 2021-12-06 17:07 UTC
Labels: issue/duplicate
