### ISSUE TITLE
Performance / User Experience for Issue Dependencies

### ISSUE THREAD

**Issue by lhinderberger** [go-gitea/gitea#12827] opened 2020-09-13 20:26 UTC
- Gitea version (or commit ref): 1.12.4

## Description
Hello everyone! 👋

First of all, thank you for providing a mechanism to define issue dependencies. I think this is a very useful way to help to maintain an overview.

Unfortunately there's a performance / user experience problem with the current state of this feature, of which I want to make you aware:

In larger instances, such as Codeberg, defining issue dependencies can be very slow. It takes about ten seconds until the list of issues for the current repository is shown when clicking into the "Add Dependency" box. Searching for issue titles takes a few seconds too. It's also not possible to add an issue dependency by referring to the issue ID similar to how it would be done in Markdown (which at least to me is the most natural way of referring to an issue). This makes the process of adding dependencies rather hard to use.

The original discussion can be found at https://codeberg.org/Codeberg/Community/issues/244

Thank you!

**Comment by 6543** [comment] 2021-03-11 18:49
`time curl 'https://try.gitea.io/api/v1/repos/issues/search?q=&priority_repo_id=14718&type=all&_=1615487205723' > /dev/zero`
-> 0m54,040s

**Comment by zeripath** [comment] 2021-03-27 15:45
OK the issue is that /api/v1/repos/issues/search is just seriously inefficient.

**Comment by zeripath** [comment] 2021-03-29 19:09
Looking at try.gitea.io it appears that the improvement from 15179 could actually be sufficient to close this issue! Although I would still argue that the API is still too non-performant.

**Comment by lunny** [comment] 2021-11-14 14:03
I think we can close this now. And if there is still new performance problem. We can create a new one.

**Closed as completed by lunny** 2021-11-14 14:03 UTC
Labels: type/bug, performance/speed
