### ISSUE TITLE
Markdown file can not show exactly when ``` start or end with a blank line

### ISSUE THREAD

**Issue by lotus-king** [go-gitea/gitea#411] opened 2016-12-19 02:05 UTC
- Gitea version (or commit ref):
latest version
- Git version:
2.3
- Operating system:
CentOS 
- Database (use `[x]`):
  - [ x] MySQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
put this markdown file [https://try.gitea.io/lotus-king/tls/src/master/openssl.md](https://try.gitea.io/lotus-king/tls/src/master/openssl.md) to gogs or gitea, will reporduce the bug.
- Log gist:

## Description
put this markdown file [https://try.gitea.io/lotus-king/tls/src/master/openssl.md](https://try.gitea.io/lotus-king/tls/src/master/openssl.md) to gogs or gitea .
gogs or gitea cannot correctly show the markdown file, it just show the markdown source file at  code (``` start or end with a blank line) ,but github can show it correctly.

**Comment by bkcsoft** [comment] 2016-12-25 13:39
@lotus-king could you try running it through blackfriday directly and see if that works? otherwise it's an upstream bug 🙁

**Comment by lunny** [comment] 2017-02-24 04:43
This is not resolved by #186 also. @andrew-boyarshin :) let's move it to v1.2

**Comment by andrew-boyarshin** [comment] 2017-02-24 10:42
@lunny If I'm not very much mistaken I've already pointed out that this markdown file has multiple issues and blackfriday is not responsible for fixing invalid markdown.

**Comment by ethantkoenig** [comment] 2017-08-27 03:58
This issues seems to be fixed (https://try.gitea.io/ethantkoenig/sandbox/src/master/README.md). Someone please close

**Comment by lunny** [comment] 2017-08-27 06:35
see https://try.gitea.io/lotus-king/tls/src/master/openssl.md, it seems the problem is not fixed?

**Comment by ethantkoenig** [comment] 2017-08-27 06:43
@lunny As far as I can tell, that's how it should be rendered. I don't see any ``` blocks that aren't being rendered.

**Comment by lunny** [comment] 2017-08-27 06:52
It ignored "   ```".

**Comment by ethantkoenig** [comment] 2017-08-27 07:12
@lunny Oh, I see

**Comment by bkcsoft** [comment] 2017-08-27 20:21
It misses it because of invalid indentation. See https://try.gitea.io/bkc/tls/src/master/openssl.md and specifically https://try.gitea.io/bkc/tls/commit/c22378418a700bba1380581be58dc04320b29340

Closing as NotABug 🙂

**Closed as completed by bkcsoft** 2017-08-27 20:21 UTC
Labels: type/bug, topic/ui, status/blocked

**Comment by lunny** [comment] 2017-08-28 01:13
@bkcsoft But github could render it correctly.

**Comment by bkcsoft** [comment] 2017-08-28 04:42
@lunny GitHub is not using the same markdown renderer as we do, and in any case it's an upstream issue and not an issue with Gitea itself. And the point still stands that the example given is invalid syntax (invalid indentation)

**Comment by lunny** [comment] 2017-08-28 13:01
@bkcsoft OK.
