### ISSUE TITLE
Proposal: Handling of issue priority?

### ISSUE THREAD

**Issue by Kreyren** [go-gitea/gitea#14377] opened 2021-01-18 11:45 UTC
Proposing to implement issue priority handling such as:

![image](https://user-images.githubusercontent.com/11302521/104911175-bdd2cd80-598a-11eb-925b-9ae1068c1c0f.png)

Where the idea is to allow coordination in bigger groups so that instead of communicating about which issue to work on the maintainers could just set issue priority where higher the priority the more attention is the issue going to get.

Currently we can only set issue labels that get out of hand when the repository receives lots of issues per day.

**Comment by delvh** [comment] 2021-01-18 12:27
Just wanted to create my own issue, good that I saw this beforehand. I have a few notes here:
I'd say, storing an `uint8` should be enough to assign priorities in between, both to disable assigning astronomical priorities like 200000, and to reduce space consumption.
This would allow to sort issues according to their priority (same priority issues should be ordered using the creation time of the issues to encourage solving issues that have been open for a longer time - no one should have to navigate to page 265, just to see the specific issue he is looking for, unless this issue is not prioritized at all).
Another potential of using this system is that prior to creating a new issue, each user can most likely assess a range of priorities for his would-be issue (I'd say we do not assume that users are idiots), and in this range he can then more quickly navigate, if the issue he is proposing has already been filed, thus avoiding many duplicate issues. (Because to be honest, when opening this issue I myself had no interest to filter through about 30-40 pages of issues to see if it is already opened - thank god this issue was opened 30 Minutes ago).
Using this mechanism, it is likelier that highly requested issues will be quickly implemented.
I'd suggest giving the issue creator the option to specify the priority on issue creation (unless disabled).
Afterwards, the issue creator and system admins/ (collaborators?) should be able to manually change this issues priority.
We could even think of adding the option for users to react with a `+1`, that automatically increases the priority of the issue by one, automatically making this issue more requested (in that case, we do have to keep the maximum of the chosen datatype in our eyes, as we do not want that priority to be automatically set to the lowest value by data overflow).
One question that should be answered in advance is:
What order should priorities have (is 0 the highest or the lowest priority)?
Depending on the answer, if the issue is not initialized, the lowest priority should be assigned to the issue

**Comment by jolheiser** [comment] 2021-01-18 14:57
This is fairly duplicate of https://github.com/go-gitea/gitea/issues/2616 and the subsequent PR https://github.com/go-gitea/gitea/pull/4823.
Also somewhat similar to https://github.com/go-gitea/gitea/issues/9401 and PR https://github.com/go-gitea/gitea/pull/11669.

**Closed as completed by jolheiser** 2021-01-18 14:57 UTC
Labels: type/proposal
