### ISSUE TITLE
Duplicated/empty row on My Repositories on Organization dashboard

### ISSUE THREAD

**Issue by jomp16** [go-gitea/gitea#695] opened 2017-01-18 21:31 UTC
- Gitea version (or commit ref): 1.0.0+133-gd2bb8ef5
- Git version: 2.11.0
- Operating system: Arch Linux
- Database (use `[x]`):
  - [x] MySQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] No (not sure tho).

## Description

I created a new organization and changed the owner of repository to that organization. That worked perfectly.

But I found something strange on Organization dashboard:  
![](http://i.imgur.com/SaO43fm.png)

The empty row on "my repositories" just links to the Organization url.

Excepted result is:  
![](http://i.imgur.com/7HdDGAl.png)
(I removed the empty rows with Chrome inspector).

I don't know if the way I did to change ownership from me to a organization is wrong, or this is a Gitea bug.

**Comment by tboerger** [comment] 2017-01-18 23:32
Duplicate of https://github.com/go-gitea/gitea/issues/56, please try to reproduce a big first on try.gitea.io which is always running latest master.

**Closed as completed by tboerger** 2017-01-18 23:32 UTC
Labels: issue/duplicate

**Comment by jomp16** [comment] 2017-01-18 23:58
I **_guess_** I didn't ask for theme support? Maybe you linked the wrong issue number?

And I also **_guess_** try.gitea.io isn't always updated, because version: 1.0.0+116-g69b86378.

But yeah, I don't see it on try.gitea.io. Update it to latest master and I can check it again.

I'll build with commit 69b86378cef6e4e72a563ca029a06932838484fe (to match try.gitea.io) and check if issue is on my side or some recent commit broke it.

--

Not a bug on my side, I build with version: 1.0.0+116-g69b86378 and it correctly show all the six repositories, without any empty `<li>` tag.

Did you misunderstand my issue?

--

I guess I need to find the faulty commit...

**Comment by jomp16** [comment] 2017-01-19 00:25
I found the faulty commit: 302fa4298008cf2e5d52d442b16c8e598551200b.

Tested the commit before that (which is 88f45ce38ccc93dccb5bbffea9ff6328d7612275) and it didn't give out empty `<li>` tags.

I'm not sure why this commit gives an empty `<li>` tags, because it **never** touched the template file.

Maybe this line? https://github.com/go-gitea/gitea/commit/302fa4298008cf2e5d52d442b16c8e598551200b#diff-97681c8a2932ea3c23325d3518374d98R608

I'll revert this commit and see the results

--

Yep, reverting that commit renders the "My repositories" correctly without any extra empty `<li>` , but I really not sure the why.

--

@tboerger can you reopen this?

**Comment by tboerger** [comment] 2017-01-19 05:57
https://github.com/go-gitea/gitea/issues/564 is the correct issue and the referenced pull request should have fixed that.

**Comment by tboerger** [comment] 2017-01-19 06:02
And try.gitea.io is always the latest version... It shows 1.0.0 + 116 commits. 

If your issue still isn't resolved please explain more details.

**Comment by jomp16** [comment] 2017-01-19 08:01
You sure? Because seems try.gitea.io is at version 1.0.0+116-g69b86378.

See the commit after the g and search GitHub commits for that commit.
Commit: 69b8637 name: "docs: update zh-tw translation".

See how many new commits Gitea team have made (16 new commits), and the the
commit that is faulty for me, is in the middle of the new commits.

So... Update try.gitea.io to point to the literally latest master which
is d2bb8ef5 name: "Notifications: trying to get a better layout". And
I'll check again.

Ping @lunny, because you made that commit that's supposed to fix. But for
some reason it does not for me. Reverting that commit does not generate
empty lines alongside of the repositories links. See the first image on
issue.

Maybe I should record or create a test user and Organization on my
Gitea instance running latest master and you see by yourselves?

**Comment by lunny** [comment] 2017-01-19 09:31
`try.gitea.io` seems not the latest version. It's `1.0.0+116-g69b86378`, but it should `1.0.0+134-g3c4d5e1e`.

**Comment by bkcsoft** [comment] 2017-01-20 08:02
^ I've noticed that `try.` isn't always updated as well, though I assumed it was drone being slow on the builds...

**Comment by lunny** [comment] 2017-01-20 11:24
@tboerger

**Comment by jomp16** [comment] 2017-01-25 13:43
And since try.gitea.io is updated (1.0.0+149-g8bc43195). I **can** reproduce this bug on it.

http://i.imgur.com/XHg2PyK.png

@tboerger now reopen this. You can reproduce this bug by switching to Organization on Dashboard. Like I said.

All teh info is on comments above.

**Comment by Bwko** [comment] 2017-01-25 13:45
Possible duplicate of #746?

**Comment by jomp16** [comment] 2017-01-25 13:47
Possible, but I reported first, and nobody believed me :)

Anyways, if it's a known issue now. Good :)

**Comment by Bwko** [comment] 2017-01-25 14:04
@jomp16 I agree #746 is a duplicate of this issue :wink: 
Could you test if #749 solves your issue?
