### ISSUE TITLE
Cannot creat indexers for newly import repositories

### ISSUE THREAD

**Issue by MFYDev** [go-gitea/gitea#9190] opened 2019-11-28 06:43 UTC
- Gitea version (or commit ref): 1.10.0
- Git version: 2.17.1
- Operating system: Ubuntu 18.04 LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No 
  **P.S.: The reason why I cannot reproduce this issue is try.gitea.io doesn't turn on the function of code indexers.**
  - [ ] Not relevant
- Log gist:

## Description

Hi there,

I found that when I turn on the code indexer function and import a new repository from an URL, the code index cannot be created by Gitea itself. I found that because every time after the import procession done, and I input some code right inside the repository it cannot be found and Gitea just display nothing on the search page.

I have to delete the indexers of repositories on my server and restart the Gitea, only in this way can it be created. That is so weird which I really do not know whether it is my own server's problem or Gitea's Bug, so I highly recommend you to have a check on it.

Here is the my custom configuration in the app.ini in the following:

 [indexer]
ISSUE_INDEXER_TYPE = db
STARTUP_TIMEOUT=30s
REPO_INDEXER_ENABLED = true
REPO_INDEXER_PATH = /hdd2/gitea/indexers/repos.bleve
UPDATE_BUFFER_LEN = 20
MAX_FILE_SIZE = 1048576

[repository]
ROOT = /hdd2/gitea/gitea-repositories 

## Screenshots
Only screenshots cannot demonstrate this problem clearly. Just have a try please.

**Comment by vvrein** [comment] 2020-01-07 12:16
+1 for this issue.

My setup:
- Gitea version (or commit ref): 1.11.0+dev-566-g143f88d97
- Git version: 2.24.1
- Operating system: Arch Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
P.S.: The reason why I cannot reproduce this issue is try.gitea.io doesn't turn on the function of code indexers.
  - [ ] Not relevant
- Log gist:

## Description
1) After turning on repo indexing, and committing new changes to the existing repo, changes don't get to the index. 
2) Also creating new repo, and committing changes there don't get to the index. 

However, when I delete dir `/home/gitea/app/indexers/repos.bleve` with repo indexes, and restart gitea - all repo are indexed well. But then I got step 1. 
Such feel, like repo indexing runs only once at start, and only if index dir is empty. Restarts without deletion `repos.bleve` don't give any results.

**Comment by vvrein** [comment] 2020-01-25 10:53
@FanyangMengDev can you check now with latest gitea binary from https://dl.gitea.io/gitea/master/ ? It seems to be fixed in #9946

**Comment by zeripath** [comment] 2020-01-25 11:16
as per @vvrein I'm gonna close this as Fixed by #9965 and #9957 

Please reopen if this remains an issue.

**Closed as completed by zeripath** 2020-01-25 11:16 UTC
Labels: type/bug

**Comment by FanyangMengDev** [comment] 2020-01-25 11:18
@vvrein Hi there, this is the first time that I see the master version release on this official website.
Now I am using 1.11-rc2 and the problem happenes, if I change to the master version, will it have some impact on my future use? If it will not cause any problem I could have a try for the newest version, cause I use gitea in my production VPS, really do not wanna get any trouble

**Comment by FanyangMengDev** [comment] 2020-01-25 11:23
I just install the dev version. All the pages become display unproperly. the login button becomes disappear and all the things cannot load normally. It scares me a lot and now I am switch back to 1.11-rc2

**Comment by FanyangMengDev** [comment] 2020-01-25 11:27
@zeripath If it is possible please reopen this issue, cause I cannot even find where is the import button when I change it from 1.11-rc2 to 1.12 dev under that cluttered page

**Comment by guillep2k** [comment] 2020-01-25 11:30
@FanyangMengDev `master` is the latest, unpolished work... we're building 1.12.0 there. In a few days 1.11.0 will come out (or perhaps 1.11.rc3?). That will be much more stable and will contain the fixes from  #9965 and #9957.

**Comment by FanyangMengDev** [comment] 2020-01-25 11:33
@guillep2k Thank you so much for your reply. I see now. Looking forward to the next version, and I just donate 1 dollar to you guys on PayPal. Please understand as a undergraduate student 1 dollar per month is the most money I can donate cause I do not have so much money every month.
Thank you for your hard working again! : )

**Comment by zeripath** [comment] 2020-01-25 12:01
We've still got an issue with our translations in master - I'm not sure why they haven't updated since we attempted to fix this.

**Comment by zeripath** [comment] 2020-01-25 12:02
@FanyangMengDev try the release/v1.11 branch - as that will become 1.11-rc3 or 1.11 soon.
