### ISSUE TITLE
Postgres issue after docker container update

### ISSUE THREAD

**Issue by henry-nicolas** [go-gitea/gitea#10807] opened 2020-03-23 21:51 UTC
- Gitea version (or commit ref): 1.12.0+dev-33-gc61b90253
- Git version: 2.24.1
- Operating system: Docker container
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:
```
2020/03/23 21:42:20 ...rm/session_schema.go:25:Ping() [I] PING DATABASE postgres
2020/03/23 21:42:20 ...m.io/xorm/core/db.go:150:QueryContext() [I] [SQL] SELECT tablename FROM pg_tables WHERE tablename = $1 [version] - 4.338196ms
2020/03/23 21:42:20 ...m.io/xorm/core/db.go:150:QueryContext() [I] [SQL] SELECT column_name FROM INFORMATION_SCHEMA.COLUMNS WHERE table_name = $1 AND column_name = $2 [version id] - 14.310184ms
2020/03/23 21:42:20 ...m.io/xorm/core/db.go:150:QueryContext() [I] [SQL] SELECT column_name FROM INFORMATION_SCHEMA.COLUMNS WHERE table_name = $1 AND column_name = $2 [version version] - 6.544237ms
2020/03/23 21:42:20 ...m.io/xorm/core/db.go:150:QueryContext() [I] [SQL] SELECT "id", "version" FROM "version" WHERE "id"=$1 LIMIT 1 [1] - 998.329µs
2020/03/23 21:42:20 ...m.io/xorm/core/db.go:150:QueryContext() [I] [SQL] SELECT tablename FROM pg_tables [] - 1.166538ms
2020/03/23 21:42:20 ...m.io/xorm/core/db.go:150:QueryContext() [I] [SQL] SELECT column_name, column_default, is_nullable, data_type, character_maximum_length,
	    CASE WHEN p.contype = 'p' THEN true ELSE false END AS primarykey,
	    CASE WHEN p.contype = 'u' THEN true ELSE false END AS uniquekey
	FROM pg_attribute f
	    JOIN pg_class c ON c.oid = f.attrelid JOIN pg_type t ON t.oid = f.atttypid
	    LEFT JOIN pg_attrdef d ON d.adrelid = c.oid AND d.adnum = f.attnum
	    LEFT JOIN pg_namespace n ON n.oid = c.relnamespace
	    LEFT JOIN pg_constraint p ON p.conrelid = c.oid AND f.attnum = ANY (p.conkey)
	    LEFT JOIN pg_class AS g ON p.confrelid = g.oid
	    LEFT JOIN INFORMATION_SCHEMA.COLUMNS s ON s.column_name=f.attname AND c.relname=s.table_name
	WHERE n.nspname= $1 AND c.relkind = 'r'::char AND c.relname = $2 AND s.table_schema = $3 AND f.attnum > 0 ORDER BY f.attnum; [ user ] - 24.952711ms
2020/03/23 21:42:20 ...m.io/xorm/core/db.go:150:QueryContext() [I] [SQL] SELECT indexname, indexdef FROM pg_indexes WHERE tablename=$1 [user] - 4.55381ms
2020/03/23 21:42:20 cmd/migrate.go:38:runMigrate() [F] Failed to initialize ORM engine: sync database struct error: Unknown col created_unix seq 0, in index created_unix of table user, columns []

```

## Description

After upgrading my docker container to run gitea version 1.12.0+dev-33-gc61b90253 the web service no longer comes up as the application keeps on crashing and restarting every minute with the above ORM error. Note that the column reported in the error may vary (different names) but it always points out to the user table.

**Comment by resamaraschi** [comment] 2020-03-24 09:08
Facing the same issue when scaling our app from one gitea instance to two instances. The second one does not start with the same error.

**Comment by lafriks** [comment] 2020-03-24 10:40
Duplicate of #10802

**Closed as completed by lafriks** 2020-03-24 10:40 UTC
Labels: type/bug, issue/duplicate

**Comment by henry-nicolas** [comment] 2020-03-24 11:52
Here I am refering to an upgrade while the other issue refers to a new install.

Question then for me becomes: will I be ok to upgrade as is to the next release that has the bugfix or is my database schema left broken now?

**Comment by adasauce** [comment] 2020-03-24 13:01
@henry-nicolas i'm seeing the same behaviour on the same table after a docker-compose pull and up.

**Comment by lafriks** [comment] 2020-03-24 18:55
It is same issue both for install and update. Database schema is not broken, it is just Gitea xorm migration thinks that schema changes are needed and tries to add index that already exists
