### ISSUE TITLE
Activity Heatmap: Begin week with Monday in countries where it is the first day of the week

### ISSUE THREAD

**Issue by evur** [go-gitea/gitea#24608] opened 2023-05-09 14:43 UTC
### Feature Description

It feels weird for people of countries, which have Monday as the first day of the week, to look at a heatmap beginning with Sunday.

**Comment by yardenshoham** [comment] 2023-05-09 17:26
Duplicate of https://github.com/go-gitea/gitea/issues/6058

**Closed as not planned by yardenshoham** 2023-05-09 17:26 UTC
Labels: type/proposal, type/feature
