### ISSUE TITLE
Link to pull request within mail points to external issue tracker

### ISSUE THREAD

**Issue by otbutz** [go-gitea/gitea#14326] opened 2021-01-13 15:18 UTC
- Gitea version (or commit ref): 1.13.1
- Git version: 2.30
- Operating system: Ubuntu 20.04

- Database:
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No

## Description

I've enabled mail notifications for our repository and also configured an external issue tracker. Everything seems to work except for the URLs of PR references by number in the mail notifications.

Example:

```
Requested to review #3507.

---
View it on Gitea: Git with a cup of tea.
```

The link behind `#3507` is wrong as it points to our issue tracker:
```html
<p>Requested to review <a href="https://redmine.example.com/issues/3507" rel="nofollow nofollow noopener noreferrer" target="_blank">#3507</a>.</p>
```

I'd expect gitea to link to the PR page which would have the following URL:

```
https://git.example.com/myorg/myrepo/pulls/3507
```

The other URL at the bottom is correct though:

```html
<a href="https://git.example.com/myorg/myrepo/pulls/3507#issuecomment-32580" target="_blank" rel="nofollow noopener noreferrer">View it on Gitea: Git with a cup of tea</a>.</p>
```

**Comment by jpraet** [comment] 2021-01-13 16:00
Duplicate of #13720 (already fixed in 1.14).

**Closed as completed** 2021-01-13 16:03 UTC
Labels: type/bug, issue/duplicate
