### ISSUE TITLE
LDAP call results in status 500: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by tvannahl** [go-gitea/gitea#5139] opened 2018-10-22 14:35 UTC
- Gitea version (or commit ref): 1.5.2
- Git version: 1.8.3.1
- Operating system: CentOS 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Active Directory Authentication
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [] Not relevant
- Log gist:

[gitea_crash.log](https://github.com/go-gitea/gitea/files/2501775/gitea_crash.log)

## Description

Everything related to LDAP/Active Directory appears to cause crashes in the gitea server. This problem occured after a recent migration from sqlite3 to mariadb 10.2 and the upgrade from 1.5.1 -> 1.5.2.
 From what I have tested, can be triggered by the following tasks:

 - Login of Active Directory Users
 - Editing the `LDAP (via BindDN)` authentication source.

**Comment by lunny** [comment] 2018-10-22 15:07
Is your installation a fresh one or upgraded from an old one?

**Comment by tvannahl** [comment] 2018-10-22 15:19
Oh sorry, forgot to add that: The installation has recently been migrated from sqlite3 to mariadb 10.2 and after that migration the update from 1.5.1 to 1.5.2 has been done.

**Comment by lafriks** [comment] 2018-10-22 18:30
Can you give anonymized ldap settings you are using?

**Comment by tvannahl** [comment] 2018-10-22 19:29
Got the settings strait from the database:

```
| id | type | name                 | is_actived | is_sync_enabled | cfg                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | created_unix | updated_unix |
+----+------+----------------------+------------+-----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+--------------+
|  3 |    2 | SWW Active Directory |          1 |               0 | {"Name":"SWW Active Directory","Host":"nori.erk•••.de","Port":636,"SecurityProtocol":1,"SkipVerify":false,"BindDN":"gitea@erk••••.de","BindPassword":"••••••••","UserBase":"DC=erk•••••,dc=de","UserDN":"","AttributeUsername":"cn","AttributeName":"givenName","AttributeSurname":"sn","AttributeMail":"userPrincipalName","AttributesInBind":false,"Filter":"(u0026(objectClass=user)(sAMAccountName=%s))","AdminFilter":"(u0026(sAMAccountName=tvannahl))","Enabled":true} |   1529599875 |   1529678111 |
```

I am a little worried about those `u0026` within the filters. But changing them to `&` did help either - this looks now a lot like #4888 only with runtime error as a bonus.

**Comment by lafriks** [comment] 2018-10-24 16:07
Yes, closing as duplicate of #4888

**Closed as completed by lafriks** 2018-10-24 16:07 UTC
Labels: type/bug
