### ISSUE TITLE
Checkbox color is not correct after click

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#30916] opened 2024-05-09 11:57 UTC
### Description

![image](https://github.com/go-gitea/gitea/assets/18380374/2f757d90-568a-4ccc-a508-64c6cd7c8903)
reproduce: just click it

### Gitea Version

1.21.11

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

*

### Database

None

**Comment by wxiaoguang** [comment] 2024-05-09 14:44
It has been fixed in 1.22 ( Admin config page UI regression #30524 )

Maybe we do not need to fix it for 1.21 since it doesn't block daily usage, and 1.22 is releasing soon.

**Closed as completed** 2024-05-09 14:46 UTC
Labels: type/bug, topic/ui
