### ISSUE TITLE
Use a period of time to start a problem

### ISSUE THREAD

**Issue by guonaihe1994** [go-gitea/gitea#8390] opened 2019-10-06 03:16 UTC
```
goroutine 1 [running]:


code.gitea.io/gitea/modules/git.init.0()


	/go/src/code.gitea.io/gitea/modules/git/git.go:101 +0xc8b


panic: Failed to set git user.name(exec(2:git.Init(set user.name)) failed: exit status 4(<nil>) stdout:  stderr: error: failed to write new configuration file /data/git/.gitconfig.lock


): error: failed to write new configuration file /data/git/.gitconfig.lock






goroutine 1 [running]:


code.gitea.io/gitea/modules/git.init.0()


	/go/src/code.gitea.io/gitea/modules/git/git.go:101 +0xc8b


panic: Failed to set git user.name(exec(2:git.Init(set user.name)) failed: exit status 4(<nil>) stdout:  stderr: error: failed to write new configuration file /data/git/.gitconfig.lock


): error: failed to write new configuration file /data/git/.gitconfig.lock






goroutine 1 [running]:


code.gitea.io/gitea/modules/git.init.0()


	/go/src/code.gitea.io/gitea/modules/git/git.go:101 +0xc8b


panic: Failed to set git user.email(exec(2:git.Init(set user.email)) failed: exit status 4(<nil>) stdout:  stderr: error: failed to write new configuration file /data/git/.gitconfig.lock


): error: failed to write new configuration file /data/git/.gitconfig.lock






goroutine 1 [running]:


code.gitea.io/gitea/modules/git.init.0()


	/go/src/code.gitea.io/gitea/modules/git/git.go:101 +0xc8b


panic: Failed to set git user.name(exec(2:git.Init(set user.name)) failed: exit status 4(<nil>) stdout:  stderr: error: failed to write new configuration file /data/git/.gitconfig.lock


): error: failed to write new configuration file /data/git/.gitconfig.lock






goroutine 1 [running]:


code.gitea.io/gitea/modules/git.init.0()


	/go/src/code.gitea.io/gitea/modules/git/git.go:101 +0xc8b


panic: Failed to set git user.name(exec(2:git.Init(set user.name)) failed: exit status 4(<nil>) stdout:  stderr: error: failed to write new configuration file /data/git/.gitconfig.lock


): error: failed to write new configuration file /data/git/.gitconfig.lock






goroutine 1 [running]:


code.gitea.io/gitea/modules/git.init.0()


	/go/src/code.gitea.io/gitea/modules/git/git.go:101 +0xc8b


panic: Failed to set git user.name(exec(2:git.Init(set user.name)) failed: exit status 4(<nil>) stdout:  stderr: error: failed to write new configuration file /data/git/.gitconfig.lock


): error: failed to write new configuration file /data/git/.gitconfig.lock






goroutine 1 [running]:


code.gitea.io/gitea/modules/git.init.0()


	/go/src/code.gitea.io/gitea/modules/git/git.go:101 +0xc8b


panic: Failed to set git user.name(exec(2:git.Init(set user.name)) failed: exit status 4(<nil>) stdout:  stderr: error: failed to write new configuration file /data/git/.gitconfig.lock


): error: failed to write new configuration file /data/git/.gitconfig.lock



goroutine 1 [running]:


code.gitea.io/gitea/modules/git.init.0()


	/go/src/code.gitea.io/gitea/modules/git/git.go:101 +0xc8b


panic: Failed to set git user.email(exec(2:git.Init(set user.email)) failed: exit status 4(<nil>) stdout:  stderr: error: failed to write new configuration file /data/git/.gitconfig.lock


): error: failed to write new configuration file /data/git/.gitconfig.lock






goroutine 1 [running]:


code.gitea.io/gitea/modules/git.init.0()


	/go/src/code.gitea.io/gitea/modules/git/git.go:101 +0xc8b
```

**Comment by guillep2k** [comment] 2019-10-06 04:23
`/data/git/.gitconfig.lock` is this path OK? `/data` at the root of your system? Perhaps `app.ini` is not correctly configured?

**Comment by guonaihe1994** [comment] 2019-10-06 04:44
/ Data/git/.gitconfig.lock is normal, app.ini configuration has not been moved, suddenly today, boot is not good.

**Comment by guillep2k** [comment] 2019-10-06 13:01
If this happened suddenly on a previously working installation, it sounds like a support problem rather than a bug (this form is intended for reporting Gitea bugs). Please ask questions or configuration/deploy problems on our Discord server (https://discord.gg/gitea) or forum (https://discourse.gitea.io).

At least please also give:

- Gitea version (or commit ref): ***This one is essential***
- Git version:
- Operating system: ***This one is essential***
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

And some extra context: does this error show up on the instance start? When you attempt a particular operation? Have you made any changes to your system lately, like upgrading any libraries?

**Comment by guonaihe1994** [comment] 2019-10-07 00:25
The problem is that my LINUX system is full of disks, causing write not to go in.

**Comment by zeripath** [comment] 2019-10-10 19:40
Yup a completely full disk would cause this.

I think we've found the cause of this presentation so I'm going to close this.

**Closed as completed by zeripath** 2019-10-10 19:40 UTC
