### ISSUE TITLE
Cannot run Gitea web on new versions on Raspbian stretch

### ISSUE THREAD

**Issue by ChrisB85** [go-gitea/gitea#6367] opened 2019-03-19 06:49 UTC
- Gitea version (or commit ref):
- Git version: 
- Operating system: Raspbian stretch
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

I'm running Gitea web as a service (version 7780ea8) and it's working fine. When i try to upgrade (versions from 15.03 and above) service fails to start. In syslog i see only this:

```
Mar 19 07:34:42 raspberrypi systemd[1]: Started Gitea (Git with a cup of tea).
Mar 19 07:34:42 raspberrypi systemd[1]: gitea.service: Main process exited, code=killed, status=4/ILL
Mar 19 07:34:42 raspberrypi systemd[1]: gitea.service: Unit entered failed state.
```
No errors in Gitea logs. What can be a reason of this behavior and how can I provice more info to investigate?

**Comment by lunny** [comment] 2019-03-19 06:52
Any error information from your log files?

**Comment by ChrisB85** [comment] 2019-03-19 06:55
Unfortunately there are no new entries in gitea.log, http.log or xorm.log when i try to run service.

**Comment by lunny** [comment] 2019-03-19 07:02
Could you run `./gitea` on your terminal?

**Comment by zeripath** [comment] 2019-03-19 07:05
Try to replicate as much of the systemd environment as possible when running it from the terminal.

**Comment by ChrisB85** [comment] 2019-03-19 07:07
> Could you run `./gitea` on your terminal?

```
root@raspberrypi:/home/git/gitea# ./gitea
Błędna instrukcja
```
```
root@raspberrypi:/home/git/gitea# sudo -u git ./gitea
Błędna instrukcja
```
which means:
`Bad instruction/Bad command`

**Comment by zeripath** [comment] 2019-03-19 07:13
Ok. What is the contents of the systemd unit file? Use the executable command that is in there.

Paste the systemd unit file here and we should be able to walk you through.

**Comment by ChrisB85** [comment] 2019-03-19 07:15
```
[Unit]
Description=Gitea (Git with a cup of tea)
After=syslog.target
After=network.target

[Service]
RestartSec=2s
Type=simple
User=git
Group=git
WorkingDirectory=/home/git/gitea
ExecStart=/home/git/gitea/gitea web
Restart=always
Environment=USER=git HOME=/home/git

[Install]
WantedBy=multi-user.target
```

**Comment by zeripath** [comment] 2019-03-19 07:20
Ok

```bash
sudo -H -u git -i
cd /home/git/gitea
/home/git/gitea/gitea web 
```

**Comment by ChrisB85** [comment] 2019-03-19 07:22
```
root@raspberrypi:/home/git/gitea# sudo -H -u git -i
git@raspberrypi:~$ cd /home/git/gitea
git@raspberrypi:~/gitea$ /home/git/gitea/gitea web
Błędna instrukcja
git@raspberrypi:~/gitea$
```
Still the same effect.

**Comment by lunny** [comment] 2019-03-19 07:23
maybe you build wrong architecture binary?

**Comment by ChrisB85** [comment] 2019-03-19 07:25
I'm using always the same version which is gitea-master-linux-arm-7.
Here is my update script:

```
service gitea stop
mv /home/git/gitea/gitea-master-linux-arm-7 /home/git/gitea/gitea-master-linux-arm-7.bak
wget -P /home/git/gitea/ https://dl.gitea.io/gitea/master/gitea-master-linux-arm-7
chown git /home/git/gitea/gitea-master-linux-arm-7
chmod 755 /home/git/gitea/gitea-master-linux-arm-7
service gitea start
```

**Comment by zeripath** [comment] 2019-03-19 07:43
Well there's your issue. Your executable is called `/home/git/gitea/gitea-master-linux-arm-7` not `/home/git/gitea/gitea`. Either add a link or change the unit file to run `/home/git/gitea/gitea-master-linux-arm-7`

**Comment by ChrisB85** [comment] 2019-03-19 07:45
`/home/git/gitea/gitea` is a simlink to `/home/git/gitea/gitea-master-linux-arm-7`
```
root@raspberrypi:/home/git/gitea# sudo -u git ./gitea-master-linux-arm-7
Błędna instrukcja
```

Once again: everything is working fine when i downgrade to version  7780ea8 by replacing gitea-master-linux-arm-7 file.

**Comment by zeripath** [comment] 2019-03-19 08:01
Right so it looks like the the raspberry pi build is broken.

I'll relabel.

**Comment by zeripath** [comment] 2019-03-19 08:09
Does `file` give you any more information? Is it even an arm build?

**Comment by ChrisB85** [comment] 2019-03-19 08:12
Working version:
```
root@raspberrypi:/home/git/gitea# file ./gitea-master-linux-arm-7.bak
./gitea-master-linux-arm-7.bak: ELF 32-bit LSB executable, ARM, EABI5 version 1 (GNU/Linux), statically linked, for GNU/Linux 3.2.0, BuildID[sha1]=4601fe52b9c95357c16de62fd7d18a195f655203, not stripped
```

New (not working) version:
```
root@raspberrypi:/home/git/gitea# file ./gitea-master-linux-arm-7
./gitea-master-linux-arm-7: ELF 32-bit LSB executable, ARM, EABI5 version 1 (GNU/Linux), statically linked, for GNU/Linux 3.2.0, BuildID[sha1]=33a3450862210ffba3ed3675d0bb6b6f1c8932ef, not stripped
```

**Comment by KillerLink** [comment] 2019-03-30 17:43
I have the same issue. gitea-1.7.3 is running, neither gitea-1.8.0-rc1 nor gitea-1.8.0-rc2 are.
I have tried to investigate a little, here are my current findings:
-> According to gdb, it segfaults before the main function
-> According to strace on gitea-1.8.0-rc2, it looks like a system call might be the problem:
```
execve("./gitea-1.8.0-rc2-linux-arm-7", ["./gitea-1.8.0-rc2-linux-arm-7"], 0xbe974740 /* 19 vars */) = 0
syscall_0x101cc(0x1fb0d6, 0x5f, 0x1, 0xff8b44, 0x101c4, 0xfe15bd) = -1 (errno 38)
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0xffffffd8} ---
+++ killed by SIGSEGV +++
Segmentation fault
```
compared to the first 4 lines of strace on gitea-1.7.3 (which is working):
```
execve("./gitea-1.7.3-linux-arm-7", ["./gitea-1.7.3-linux-arm-7"], 0xbec84740 /* 19 vars */) = 0
uname({sysname="Linux", nodename="odroid", ...}) = 0
brk(NULL)                               = 0x2b50000
brk(0x2b50d0c)                          = 0x2b50d0c
```
Note that gitea-1.8.0-rc2 appears to perform a syscall (`syscall_0x101cc`) which seems to be unknown to strace here.

If i can help to gather additional information, please let me know.

**Comment by sapk** [comment] 2019-03-30 22:12
Can you try to run the latest 1.7 binary (https://github.com/go-gitea/gitea/releases/tag/v1.7.5) ? 
The goal is to know if it is related to the build chain or a change in 1.8 version.

**Comment by KillerLink** [comment] 2019-03-30 22:28
I just tried, 1.7.5 runs fine for me.

**Comment by KillerLink** [comment] 2019-04-16 12:22
Providing an update to the current situation:
The downloadable version 1.7.6 is working as expected.
The downloadable version 1.8.0-rc3 is still segfaulting.

**Comment by ChrisB85** [comment] 2019-04-30 05:56
Are there any news about that issue?

**Comment by zeripath** [comment] 2019-05-02 06:25
There's a workaround if using the arm6 binary.

We think the issue is either: something to do with the glibc version used on our xgo branch or possibly some incompatibility between the arm 7 GCC used on our xgo fork and raspbian.

It's weird and debugging it is going to be a several hour job replicating the build environments I suspect.

**Comment by KillerLink** [comment] 2019-05-10 13:02
Update on version 1.8.1: still segfaulting.
Also there is a duplication of this issue (https://github.com/go-gitea/gitea/issues/6700), which is newer but has a more accurate title than this issue.

**Comment by zeripath** [comment] 2019-05-10 13:49
I think I'll mark this as duplicate then and close this one.

For anyone wanting to run Gitea on a pi who finds this issue in future: Try the arm6 build.

**Closed as completed by zeripath** 2019-05-10 13:49 UTC
Labels: issue/duplicate, topic/build, issue/confirmed
