### ISSUE TITLE
404 on Organization's repo

### ISSUE THREAD

**Issue by the-holger** [go-gitea/gitea#3180] opened 2017-12-13 09:43 UTC
- Gitea version (or commit ref): 1.3.1
- Git version: 2.7.4
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist: 
gitea.log for error in webview: https://gist.github.com/the-holger/ef9c4668606190eb6e3820db7293d066
serv.log for error when trying to push: https://gist.github.com/the-holger/6af2b64a6ab7370367ee799cc76a4d8f

## Description
I created (multiple) repos for an organization using user "holger". Now at least one of the repos won't let user "holger" (admin user, owner of the organization) push commits, trying to view it in the browser gives me a 404.

This is fixed by [this, adapted to the new DB structure](https://github.com/go-gitea/gitea/issues/1794#issuecomment-316613399)

**Comment by lafriks** [comment] 2017-12-13 09:47
Duplicate of #1794

**Closed as completed by lafriks** 2017-12-13 09:47 UTC
Labels: issue/duplicate
