### ISSUE TITLE
[Feature Request] Pinned issues

### ISSUE THREAD

**Issue by renaissance14** [go-gitea/gitea#18595] opened 2022-02-04 09:05 UTC
GitHub has the feature to pin issues that will be shown at the top of the issue list

![image](https://user-images.githubusercontent.com/97637661/152501647-9b95b0d3-ffd1-45d6-8cd9-28a67c477939.png)

It would be nice to implement this in gitea as well.

**Comment by Gusted** [comment] 2022-02-04 10:13
Duplicate of #2175

**Closed as completed by Gusted** 2022-02-04 10:13 UTC
