### ISSUE TITLE
Wrong style of tree view in pull requests 

### ISSUE THREAD

**Issue by happyxhw** [go-gitea/gitea#23656] opened 2023-03-23 12:20 UTC
### Description

The side panel height of tree view in pull requests is very small in chrome and firefox.

### Gitea Version

v1.19.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots
https://try.gitea.io/risadmin/t25/commit/f8d30e30ce9b640979bd181c2a825dba7d311a4f
![image](https://user-images.githubusercontent.com/44490504/227202346-ae5ef7a6-1f68-441e-a0d2-969f2f4792ca.png)

### Git Version

2.40.0

### Operating System

EndeavourOS

### How are you running Gitea?

docker

### Database

PostgreSQL

**Comment by wxiaoguang** [comment] 2023-03-23 12:52
The fix for 1.19 (#23616) has been merged.

You can get 1.19 latest from https://dl.gitea.com/gitea/1.19/ , or docker gitea:1.19-dev

These contain the fix.

Duplicate of #23593

**Closed as completed** 2023-03-23 13:08 UTC
Labels: type/bug
