### ISSUE TITLE
Gitea Internal Error when pulling from non-existing ref using ssh

### ISSUE THREAD

**Issue by skyline75489** [go-gitea/gitea#14264] opened 2021-01-06 03:03 UTC
- Gitea version (or commit ref): 1.13.0
- Git version: 2.29.0
- Operating system: Windows
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No (not exactly the same because try.gitea.io does not provide ssh)
- Log gist:

## Description

I was pulling from my mirrored repos hosted on gitea using SSH. Mistakenly I pulled from the wrong branch:

```plaintext
(base) PS D:\Projects\terminal> git pull upstream master
fatal: couldn't find remote ref master
(base) PS D:\Projects\terminal> fatal: the remote end hung up unexpectedly
Gitea: Internal error
Failed to execute git command: exit status 128
```

The correct ref should be `main`. There's the log:

```plaintext
2021/01/06 10:56:34 Started GET /api/internal/serv/command/1/mirrors/terminal?mode=1&verb=git-upload-pack for [::1]
2021/01/06 10:56:34 Completed GET /api/internal/serv/command/1/mirrors/terminal?mode=1&verb=git-upload-pack 200 OK in 18.4336ms
2021/01/06 10:56:35 modules/ssh/ssh.go:127:sessionHandler() [E] SSH: Wait: exit status 1
```

I tried this on try.gitea.io. The issue does not happen. Only `fatal: couldn't find remote ref master`. I cannot use SSH on try.gitea.io. According to the log I suspect it has something to do SSH.

You don't need the exact repo to reproduce this. Any repo would do, AFAIK.

**Comment by lunny** [comment] 2021-01-06 03:50
Have you tried v1.13.1 ?

**Comment by zeripath** [comment] 2021-01-06 20:03
(can't reproduce on master)

**Comment by zeripath** [comment] 2021-06-21 20:39
This has been waiting for further feedback since January without further response therefore I'm going to close this issue.

Please reopen if this is still a problem.

**Closed as completed by zeripath** 2021-06-21 20:39 UTC
Labels: issue/needs-feedback
