### ISSUE TITLE
[Feature Request] Cherry-picking changes

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#9012] opened 2019-11-15 08:02 UTC
this is part of https://github.com/go-gitea/gitea/issues/5158 summary ...

@pjebs can you describe how it should work with a litle bit more detail ... thx

**Comment by 6543** [comment] 2020-01-14 11:05
ping

**Comment by pjebs** [comment] 2020-01-14 12:16
If you download sourcetree by atlassian, you will get a feel for how cherry picking should work.
sourcetree is a git client.

**Comment by lunny** [comment] 2020-01-18 05:12
I think it's a duplicate of #3880

**Closed as completed** 2020-01-18 10:36 UTC
Labels: type/feature, issue/confirmed
