### ISSUE TITLE
Disabling IMPORT_LOCAL_PATHS does not work

### ISSUE THREAD

**Issue by rugk** [go-gitea/gitea#898] opened 2017-02-10 23:49 UTC
see
https://github.com/gogits/gogs/issues/4033#issuecomment-275539518
https://github.com/gogits/gogs/commit/ae319da5fd91c102b387296f9884401e120f9b79

ref https://github.com/go-gitea/gitea/issues/715

---

Is this option already integrated or does Gitea behave in a similar way (just without an option to change the behaviour?)?

**Comment by rugk** [comment] 2017-02-10 23:50
As far as I see in 1.0.1 the local server path import is still possible at least for admins. As said, I also want to disable that.

**Comment by minecrafter** [comment] 2017-02-11 01:01
In Gitea, the option is called `IMPORT_LOCAL_PATHS`: https://github.com/go-gitea/gitea/blob/master/conf/app.ini#L181

**Comment by rugk** [comment] 2017-02-11 01:12
Even after setting it to false in the UI is is sill shown "or a local server path". (German version)

**Comment by minecrafter** [comment] 2017-02-11 01:28
The UI still shows but the `app.ini` setting does work, even trumping the user's permission.

**Comment by lunny** [comment] 2017-02-11 04:29
So this is not an issue?

**Comment by rugk** [comment] 2017-02-11 11:38
A wrong UI is IMHO an issue.

**Comment by lunny** [comment] 2017-02-11 15:18
Which UI? Could you change this issue's title and put some screenshot here? Or maybe you can fire another issue and close this one?

**Comment by rugk** [comment] 2017-02-11 15:22
See @minecrafter replies…

**Comment by lunny** [comment] 2017-02-14 06:57
I cannot reproduce it on current master 7eb8daf, please see https://github.com/go-gitea/gitea/blob/7eb8daffa3181f6bae7aac95d536c68c6bed0e33/templates/repo/migrate.tmpl#L15 and https://github.com/go-gitea/gitea/blob/7eb8daffa3181f6bae7aac95d536c68c6bed0e33/models/user.go#L235 . Please feel free to reopen it.

**Closed as completed by lunny** 2017-02-14 06:57 UTC
Labels: issue/not-a-bug

**Comment by rugk** [comment] 2017-02-14 11:29
Ah indeed it is no UI issue, the option does not work in any way. In the config I've set `IMPORT_LOCAL_PATHS = false` under `[security]` but as a non-admin user I can still import local repos!

So please reopen. Users cannot do so on GitHub if repo admins close an issue.

Gitea v1.0.1

**Comment by Bwko** [comment] 2017-02-14 11:43
@rugk This feature is added to the latest master not to Gitea v1.0.1

**Comment by rugk** [comment] 2017-02-14 13:37
Ah, that's the issue, I see…

**Comment by tboerger** [comment] 2017-02-14 13:41
Marked as invalid as it correctly works on master.

**Comment by rugk** [comment] 2017-06-24 20:21
I can confirm it is fixed, however changing the UI would still be nice. It is not useful to first offer the user to "import local repos" and then say, they do not have the privileges to do so, when they actually (try to) do it.
