### ISSUE TITLE
Adding a CI/CD feature to Gitea

### ISSUE THREAD

**Issue by axeloz** [go-gitea/gitea#21618] opened 2022-10-27 21:25 UTC
### Feature Description

Hello guys, 
I'm using Gitea since the beginning of the project (after Gogs), love it, so thanks for your hard work. 

Yesterday I was looking for a self-hosted CI/CD app that would run smoothly with Gitea and I came accros Abstruse (https://github.com/bleenco/abstruse). The UI is fantastic and the project is quite advanced. Unfortunately the maintainer (@jkuri) can't keep working on the project full time. Because Abstruse is written in Go, I thought of Gitea. I wonder if you guys would be interested in taking over in order to create a fully integrated Gitea/CI/CD app. 
I would love to help, unfortunately I know very few in Go.

My introduction job is done 😃
Thanks

**Comment by lunny** [comment] 2022-10-27 23:41
It's on the plan.

**Comment by techknowlogick** [comment] 2022-10-28 01:45
thanks for suggestion. closing as dupe of https://github.com/go-gitea/gitea/issues/13539 (generally integrate CI into Gitea)

**Closed as completed by techknowlogick** 2022-10-28 01:45 UTC
Labels: issue/duplicate
