### ISSUE TITLE
office 365 workflow migration failed

### ISSUE THREAD

**Issue by sw2io** [go-gitea/gitea#31645] opened 2024-07-17 02:31 UTC
### Description

![image](https://github.com/user-attachments/assets/b6996284-fff1-48e6-b7b5-adeda68fe5f0)
When a message is received via webhook, a warning is added that the connector feature in office365 is being deprecated.
https://aka.ms/O365ConnectorDeprecation

So after migrating to the workflow, when I add a new webhook, I get a 202 response and the message is not seen in Teams.
![image](https://github.com/user-attachments/assets/7387be02-3e87-4e79-8f08-9087c6b038cb)

On the edit workflow page, you can see the following failure messages
'Send_each_adaptive_card' working failed .: The execution of template action 'Send_each_adaptive_card' failed: the result of the evaluation of 'foreach' expression '@triggerOutputs()?['body']?['attachments']' is of type 'Null'. The result must be a valid array.

Can someone help me with this?

### Gitea Version

v1.22.1

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

on premise

### Database

None

**Comment by thecicco** [comment] 2024-08-29 15:15
Look this workaround:
https://github.com/go-gitea/gitea/issues/31615#issuecomment-2317932638

**Comment by lunny** [comment] 2024-08-29 16:13
Duplicate of #31615

**Closed as completed by lunny** 2024-08-29 16:13 UTC
Labels: type/bug
