### ISSUE TITLE
Submodules dont linked in subdirs

### ISSUE THREAD

**Issue by tantetoni2** [go-gitea/gitea#3232] opened 2017-12-19 10:26 UTC
- Gitea version (or commit ref):
- Git version: 5332052
- Operating system: debian 8 with docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Submodules only linked in the root of the repo
reproduce on https://try.gitea.io

Submodules
https://try.gitea.io/tantetoni2/submodule
https://try.gitea.io/tantetoni2/private-submodule

In the root submodules are linked
https://try.gitea.io/tantetoni2/repo

but in subdirs they not linked 
https://try.gitea.io/tantetoni2/repo/src/branch/master/submodules

...

**Comment by tantetoni2** [comment] 2018-10-01 15:52
when is the bugfix coming?

**Comment by lafriks** [comment] 2018-10-01 18:00
Nobody is currently working on this so if you can help to fix this that would be great

**Comment by lunny** [comment] 2018-10-06 15:03
Can't visit https://try.gitea.io/tantetoni2/submodule and https://try.gitea.io/tantetoni2/private-submodule

**Comment by biesalsk** [comment] 2018-10-19 08:06
Please fix this bug...
Links in root of projects are working:
![giteabugcorrect](https://user-images.githubusercontent.com/15630628/47205388-07847600-d386-11e8-8e81-571eb6ba738f.PNG)
But links in subdirs are dead:
![giteabugincorrect](https://user-images.githubusercontent.com/15630628/47205533-7b268300-d386-11e8-9960-4f77bf7c7f5c.PNG)

**Comment by paranoico** [comment] 2019-01-11 20:09
I need also this functionality.

Same as previous issue, why is it marked as Stale if nobody in Gitea team is working on it?

**Comment by salco** [comment] 2019-03-13 12:40
It's a huge issue in my opinion, I'm sure it could be quickly fix.
I created a repo to validate the issue since other seems to doesn't work.
https://try.gitea.io/salco/SuperProject
Tell me if it's doesn't work.

**Comment by salco** [comment] 2019-03-13 13:18
From what I can find the issue is cause by the code inside [repo.go](modules/context/repo.go) , the function RedirectToRepo. 
I've also find a commit that try to fix this issue: 237df2f33987073fdaa1d773faa4c9e87221f9ea .
Maybe it could help someone to fix it.

**Comment by mrsdizzie** [comment] 2019-03-27 04:02
This looks to be fixed / working as expected based on https://try.gitea.io/salco/SuperProject right? Particularly the fact that https://try.gitea.io/salco/SuperProject/src/branch/master/folder shows the submodule linked as expected.

**Comment by techknowlogick** [comment] 2019-03-27 04:09
Closing per above comment. Please re-open if needed

**Closed as completed by techknowlogick** 2019-03-27 04:09 UTC
Labels: type/bug, issue/confirmed

**Comment by mp-pinheiro** [comment] 2019-04-14 03:28
Hi there.

I am still unable to link nested submodules. They work as intended if they're on the root directory, however.

I have the exact same setup as the try.gitea project.

.gitmodules file:

`[submodule "steamlua"]
	path = steamlua
	url = https://gitea.yfrit.com:2053/yfrit/steamlua.git
[submodule "src/Utils"]
	path = src/Utils
	url = https://gitea.yfrit.com:2053/yfrit/Utils.git
	branch = master`

Root submodule works:
![image](https://user-images.githubusercontent.com/17935077/56087934-f8214980-5e4b-11e9-8ed1-007467e7bf0b.png)

Nested one does not:
![image](https://user-images.githubusercontent.com/17935077/56087938-1ab36280-5e4c-11e9-823f-294685bcf5c9.png)

Not sure if I'm doing anything wrong.

**Comment by mp-pinheiro** [comment] 2019-04-14 03:29
Hi there.

I am still unable to link nested submodules. They work as intended if they're on the root directory, however.

I have the exact same setup as the try.gitea project.

.gitmodules file:

`[submodule "steamlua"]
	path = steamlua
	url = <SENSTIVE>/steamlua.git
[submodule "src/Utils"]
	path = src/Utils
	url = <SENSTIVE>/Utils.git
	branch = master`

Root submodule works:
![image](https://user-images.githubusercontent.com/17935077/56087934-f8214980-5e4b-11e9-8ed1-007467e7bf0b.png)

Nested one does not:
![image](https://user-images.githubusercontent.com/17935077/56087938-1ab36280-5e4c-11e9-823f-294685bcf5c9.png)

Not sure if I'm doing anything wrong.

**Comment by salco** [comment] 2019-06-20 16:47
If you look on the try gitea the version is 1.9.0... i'm not sure if it solve it the 1.8.0. On my setup it still doesnt work, I will wait the 1.9.0 to be sure this issue is still there.

**Comment by chrissly90** [comment] 2019-08-23 12:51
is there any update on this?
