### ISSUE TITLE
Pull Mirrors: Option to disable force-push

### ISSUE THREAD

**Issue by mio-19** [go-gitea/gitea#29604] opened 2024-03-05 06:18 UTC
### Feature Description

I use pull mirrors for backup repos that have risks of removal. One way to remove a repo is to force push one commit and in this case my backup will be deleted as well.

There is no document about if gitea does or does not force push on pull mirrors. I did an experiment and found out that it did force push.

**Comment by KN4CK3R** [comment] 2024-03-05 14:23
Duplicate of #14076

**Closed as completed** 2024-03-06 00:00 UTC
Labels: type/proposal
