### ISSUE TITLE
How to mirror another git repo with ssh public-key auth. only access?

### ISSUE THREAD

**Issue by angsuman** [go-gitea/gitea#5331] opened 2018-11-14 02:27 UTC
- Gitea version (or commit ref): All
- Git version: Any
- Operating system: Ubuntu
- Database (use `[x]`): 
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
I cannot mirror a git repository with ssh access only and which uses public key based authorization.

**Comment by techknowlogick** [comment] 2018-11-14 02:28
Closing as duplicate of #1635

**Closed as completed** 2018-11-14 02:28 UTC
Labels: issue/duplicate

**Comment by angsuman** [comment] 2018-11-14 03:31
> Closing as duplicate of #1635

This is not a duplicate of #1635. I am trying to mirror repositories so the original repo remains the primary repo.
In description I mentioned mirror. The title was ambiguous so I changed the word "access" to "mirror".

The solution provided is for one time migration and not mirror. So I request that this be re-opened.

**Comment by lafriks** [comment] 2018-11-14 05:01
Migration and mirroring are using same auth functionality
