### ISSUE TITLE
Search in private repositories

### ISSUE THREAD

**Issue by deanpcmad** [go-gitea/gitea#390] opened 2016-12-14 23:51 UTC
The same as https://github.com/gogits/gogs/issues/3947

I'd like to be able to easily search my private repos. Maybe like the way GitHub does it on the home page when logged in?

**Comment by Bwko** [comment] 2016-12-15 07:17
Duplicate of #207 and already fixed by #222

**Comment by lunny** [comment] 2016-12-15 08:45
So I will close this one. Please discuss on #222. And @Bwko, maybe you should change #222's title?

**Closed as completed by lunny** 2016-12-15 08:45 UTC
Labels: issue/duplicate

**Comment by deanpcmad** [comment] 2016-12-15 17:48
Ah I missed that! Thanks :)
