### ISSUE TITLE
organization repository sort order

### ISSUE THREAD

**Issue by fragfutter** [go-gitea/gitea#6511] opened 2019-04-04 15:11 UTC
- Gitea version (or commit ref): 1.7.2, 28fcbf3 
- Git version:
- Operating system: rhel
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

The sort order of organization repositories doesn't work for logged in users.

## Reproduce
- create organization
- add mutliple repos to organization
- go to organization overview
- change sort order, for example switch between alphabetical and revers alphabetical
- log out
- change sort order

https://try.gitea.io/order_issue?sort=reversealphabetically
https://try.gitea.io/order_issue?sort=alphabetically

notice different URLs but same order of repositories

![alphabetical](https://user-images.githubusercontent.com/531718/55566700-86832600-56fc-11e9-90a0-3bf0849caadc.png)
![reverse alphabetical](https://user-images.githubusercontent.com/531718/55566708-88e58000-56fc-11e9-904c-4126831f3b23.png)

**Comment by fragfutter** [comment] 2019-04-08 07:01
update: sorting also works if the logged in user is superuser/admin

**Comment by saitho** [comment] 2019-04-20 16:03
Seems to work now. Can you check again? ^^

**Comment by lunny** [comment] 2019-04-21 03:56
I cannot reproduce this on https://gitea.com/gitea, will close this and please feel free to reopen.

**Comment by fragfutter** [comment] 2019-04-24 14:40
issue is still open for 1.8.0 (local installed) and for try.gitea.com (08d8ea9). 

Please note that this is not an issue for accounts with admin privileges.

**Closed as completed** 2019-04-24 18:20 UTC
Labels: type/bug, topic/ui

**Comment by leafney** [comment] 2019-05-07 02:03
Cannot search except sort on org home page login with non-admin，gitea version is 1.8.0 (799f5e0) .
After switching to Administrator privileges, it's all right.
Maybe this is the same issues.

**Comment by fragfutter** [comment] 2019-05-10 13:24
confirming sort order issue is fixed with 1.8.1
