### ISSUE TITLE
bug: the history page of WIKI can't open

### ISSUE THREAD

**Issue by a1012112796** [go-gitea/gitea#11057] opened 2020-04-13 06:26 UTC
- Gitea version (or commit ref): 1.12.0+dev-72-g2c25e75dc
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
see Screenshots
https://gitea.com/gitnex/GitNex/wiki/How-to/_revision

## Screenshots
<img width="950" alt="jfd" src="https://user-images.githubusercontent.com/25342410/79097628-cca0aa00-7d92-11ea-9f6e-487a330660ac.png">

**Comment by guillep2k** [comment] 2020-04-13 13:19
Closing as duplicate of #11041

**Closed as completed by guillep2k** 2020-04-13 13:19 UTC
Labels: issue/duplicate
