### ISSUE TITLE
Bug: Issue and PR are given same counters when using SQLite3

### ISSUE THREAD

**Issue by ohsayan** [go-gitea/gitea#9249] opened 2019-12-04 07:11 UTC
With the latest version of Gitea, let's say there are 0 PRs and 0 issues. We create an issue, and now there is one issue, however when we create a PR, it is labelled as #2, even though there is no first PR.
What I want to say is that the counters are shared across PRs and issues

**Comment by sntdevco** [comment] 2019-12-04 07:12
Gitea version: 1.10

**Comment by guillep2k** [comment] 2019-12-04 08:06
This is by design.

**Comment by sntdevco** [comment] 2019-12-04 08:08
@guillep2k So it happens on issues and pull requests, despite the type of database?

**Comment by guillep2k** [comment] 2019-12-04 10:11
Yes. Conceptually, for Gitea a pull request is also an issue, like in GitHub. I believe that there are other systems that don't follow this pattern.

**Comment by sntdevco** [comment] 2019-12-04 14:37
Right then, closing

**Closed as completed by sntdevco** 2019-12-04 14:37 UTC
