### ISSUE TITLE
Can't find branch named "QA" as a target for merging PR

### ISSUE THREAD

**Issue by retched** [go-gitea/gitea#28746] opened 2024-01-09 18:46 UTC
### Description

There is a branch within my repo named `QA`. It has been receiving pushes and pulls for the duration of the last two months at a minimum. 

Trying to use the web portal to accept and a merge request but I cannot set "QA" as a target that PR.

I can't even find the branch named "QA" in the branch listing BUT I can visit the QA branch page by directly typing the web address to it into my browser. But I cannot select it in any way.

### Gitea Version

1.21.3

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/1572532/4a093f94-0662-462a-bd3b-f47fb5da22be)
![image](https://github.com/go-gitea/gitea/assets/1572532/9f4ac48e-b705-4916-8073-94279ac0aa28)
![image](https://github.com/go-gitea/gitea/assets/1572532/1ed4455a-6950-4c14-8893-915a7f5f2bfc)

### Git Version

2.43.0

### Operating System

Windows

### How are you running Gitea?

Self Hosted, using the pre-built download "gitea-1.21.3-gogit-windows-4.0-amd64.exe"

### Database

SQLite

**Comment by KN4CK3R** [comment] 2024-01-10 18:56
From your screenshot it looks like you are trying to search for `Rebirth:QA` but the repo is called `bin`?

**Comment by retched** [comment] 2024-01-10 19:10
Even typing in just QA yields the same:

![image](https://github.com/go-gitea/gitea/assets/1572532/a6e2fdc6-2617-448c-aff4-1b0f060c1132)

Again, there is a branch named QA... I can navigate to it by using the direct URL.... but the name QA is missing from all views and switches. Even trying to make a branch named QA yields an error.

**Comment by lunny** [comment] 2024-01-16 08:03
Please sync the branches on admin panel first. This maybe caused by a previous bug but fixed.
And a further bug fixes has been merged into 1.22 but it's difficult to be backported to 1.21 which can fix the Case Insensitive problems about branch names.

**Closed as completed** 2024-01-29 22:17 UTC
Labels: issue/needs-feedback
