### ISSUE TITLE
Wrong OAuth2 Form target when running on modified root URL

### ISSUE THREAD

**Issue by PeterNerlich** [go-gitea/gitea#8461] opened 2019-10-11 09:41 UTC
- Gitea version (or commit ref): v1.9.4
- Git version: 2.22.0
- Operating system: gitea/gitea on Docker on Ubuntu 18.04.3 LTS
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No (because its root matches the server root)
  - [ ] Not relevant
- Log gist: https://gist.github.com/PeterNerlich/275d199733c38d2aee8a607b5d7bf84a

## Description

I have set gitea up in docker behind a reverse proxy (Traefik). We are not given subdomains so we have to work with prefixes like `/git/`. When trying to integrate drone into our setup, granting authorization to it fails. I think I traced it down to the "grant or cancel" form action url leading to `/login/oauth/grant` instead of `/git/login/oauth/grant`. Manipulating the HTML and clicking the button then worked.

## Screenshots

![Screenshot from 2019-10-11 11-38-17](https://user-images.githubusercontent.com/10530729/66641984-14941800-ec1c-11e9-9a2f-6ce30aed1478.png)

**Comment by lafriks** [comment] 2019-10-11 20:12
Looking at code I don't see anything wrong, have you set ROOT_URL in app.ini right?

**Comment by h3kker** [comment] 2019-10-15 15:35
I have the same problem (reported in #8466 which I closed now again). My config is

```
ROOT_URL = https://example.com/repo/
```

but the POST also goes to the base (https://example.com/login/oauth/grant)

I also noted this on the configuration page (e.g. https://example.com/repo/user/settings/applications/oauth2/1)

**Comment by VentGrey** [comment] 2019-10-20 02:58
I'm also experiencing this on Drone. The URL redirect forgets the `/git` prefix

**Comment by zeripath** [comment] 2019-10-23 17:15
The problem is here:

https://github.com/go-gitea/gitea/blob/dbd9d8dd54fd3b0ff7b02ae7b7da8369654e3725/templates/user/auth/grant.tmpl#L19

If you change that line to:

https://github.com/go-gitea/gitea/blob/e9ac23ceb562e1badaed7dd476096fa3594b7636/templates/user/auth/grant.tmpl#L19

The problem should be fixed.

You can either wait for #8647 to be merged, or if you can't use 1.11 you should be able to make a custom version of the `user/auth/grant.tmpl` with this fix.

**Closed as completed** 2019-10-23 21:04 UTC
Labels: issue/needs-feedback
