### ISSUE TITLE
Kanban improvements

### ISSUE THREAD

**Issue by KlavsKlavsen** [go-gitea/gitea#27081] opened 2023-09-14 12:23 UTC
### Feature Description

It would be great if Kanban board had a few improvements:
1) Not show closed issues and allow for a column to be marked as "closing column" with a delay 

Both jira and redmine kanban does this: you set f.ex. 3 days - and when you move issue to "in production" column (and its marked as closing) - it will automaticly close issues thats been >3 days in the that column (so its easy to pull back issues that turned out to not really be properly in production - it tends to happen and you notice a bit later, and also you can then enjoy a kanban with a filled right side (in production) - but monday - next weeks kanban - it'll be empty again :)

2) allow ensuring all columns stay in view.. Currently drag and dropping from a column on left side - and more than just a few columns to the right (so its out of view) - is impossible. You have to manually scroll columns first and move it bits at a time - and also makes it impossible to have overview of all issues - no matter state.

depending on screen width - it could put "labels, milestones and project name" details in a popup only - so issue "cards" don't take up too much space...so they only show on hover.

**Comment by lunny** [comment] 2024-03-29 07:39
Duplicate of #27037

**Closed as completed by lunny** 2024-03-29 07:39 UTC
Labels: type/proposal, topic/projects
