### ISSUE TITLE
Push to the protected branch

### ISSUE THREAD

**Issue by aes2000** [go-gitea/gitea#7770] opened 2019-08-06 08:49 UTC
- Gitea version (or commit ref): 1.9.0
- Git version: 2.9.0
- Operating system: Windows Server 2008R2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
```
2019/08/06 15:14:29 ...ters/private/hook.go:74:HookPreReceive() [E] Unable to detect force push between: 58859073725aedb64b9d4ef1550b284df305980b and 180e4b9383c9a15ce62de5b57befac7b1f867a09 in 824719338992:Test/PrTest Error: exit status 128 - fatal: Not a git repository (or any of the parent directories): .git
```

## Description

Hi! I've read #7636 and updated to 1.9 release but error still not fixed.
The error occurs when I push from the local repository or when I try to accept pull request via web UI
...

**Comment by lafriks** [comment] 2019-08-06 08:56
Looks like duplicate of #7754

**Closed as completed by lafriks** 2019-08-06 08:56 UTC
Labels: issue/duplicate
