### ISSUE TITLE
sqlite db  delete user error

### ISSUE THREAD

**Issue by zileyuan** [go-gitea/gitea#1281] opened 2017-03-16 07:30 UTC
admin delete log:
2017/03/16 15:23:00 [...uters/admin/users.go:257 DeleteUser()] [E] DeleteUser: ExternalLoginUser: database table is locked

user delete self:
2017/03/16 15:25:15 [...ters/user/setting.go:707 SettingsDelete()] [E] DeleteUser: ExternalLoginUser: database table is locked

**Comment by crocket** [comment] 2017-03-19 00:22
I couldn't delete a user because of this bug.

**Comment by strk** [comment] 2017-03-20 13:03
Duplicate of #1145

**Comment by lunny** [comment] 2017-03-20 13:27
go #1145 to discuss further.

**Closed as completed by lunny** 2017-03-20 13:27 UTC
Labels: issue/duplicate
