### ISSUE TITLE
Show hide button should be there in review window with files to see file content or not

### ISSUE THREAD

**Issue by atishhamte** [go-gitea/gitea#8864] opened 2019-11-07 04:48 UTC
- Gitea version (or commit ref): 1.9.4
- Git version: 2
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
There has to be show hide toggle button to se file content or not as currently, all files are showing content by default
![showhide](https://user-images.githubusercontent.com/8375139/68360954-f6043c80-0147-11ea-96c4-929bf201fd42.png)

**Comment by guillep2k** [comment] 2019-11-08 01:00
Duplicate of #8579

**Comment by blueworrybear** [comment] 2019-11-09 00:26
I am working on this feature and expand up/down coding. :smile:

**Closed as completed** 2019-11-09 00:27 UTC
Labels: issue/duplicate
