### ISSUE TITLE
Customized Landing Page Doesn't Show Up In Docker Deployment

### ISSUE THREAD

**Issue by vw98075** [go-gitea/gitea#17474] opened 2021-10-28 15:51 UTC
### Gitea Version

1.15.0+dev-593-gafc2fffe2

### Git Version

2.30.1 (Apple Git-130)

### Operating System

MacOS

### How are you running Gitea?

With one customization, we built Gitea ourselves based on the source code from Gitea. For the native deployment, we follow the README documentation.

- TAGS="bindata" make build
- ./gitea web

See the description below for more details.

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

We make changes to the landing page. All code changes are under the custom directory. Running it natively, the customized landing page shows up properly.

We make a docker image with the command "docker build -t abc/gitea ." The Dockerfile comes with the source code without any changes.

We run the command, "docker-compose -f postgresql.yml up", to bring up a Gitea docker container. The content of the postgresql.yml file is copied from https://docs.gitea.io/en-us/install-with-docker/#postgresql-database and we replace "image: gitea/gitea:1.15.5" with "image: abc/gitea:latest". The version # is the same as what we see in the native deployment starting with "a77c1a".

With the same version number, the customized landing page shows up in the native deployment, but not in the Docker deployment.

Update based on a comment from a Gitea team number:

The landing page customization is done based on a guide from the Gitea team. The directory structure is the following: custom->conf, custom->options->locale, custom->templates.
The Gitea version in this ticket is updated with extended information.
It was stated where our docker compose file comes from in the original ticket. Based on the URL of the Gitea online document, it is clear that we use the rootful one as what you call it.

**Comment by wxiaoguang** [comment] 2021-11-03 02:58
`custom` data is not part of Gitea release, it shouldn't be copied into the docker image for a common release.

Users can always use a volume to map their own custom data into docker containers.

As long as the issue has a solution and it is not a bug, we can close this issue.

**Closed as completed by wxiaoguang** 2021-11-03 02:58 UTC
Labels: issue/not-a-bug

**Comment by vw98075** [comment] 2021-11-04 18:47
In our case, there is not any data involved for customization, but application files. The current Dockerfile is a trap for people who need to do such customization given lacking proper documentation on the subject. It should either leave all customization stuff out or have them properly.
