### ISSUE TITLE
[Feature Request] List Repositories with access similar to Gitolite via SSH

### ISSUE THREAD

**Issue by johnnybubonic** [go-gitea/gitea#12704] opened 2020-09-03 21:15 UTC
- Gitea version (or commit ref): N/A
- Git version: N/A
- Operating system: N/A
- Database (use `[x]`): N/A
- Can you reproduce the bug at https://try.gitea.io: N/A
- Log gist: N/A

## Description

In [gitolite](https://gitolite.com/gitolite/index.html), one can ssh directly to the git user and see which repositories they have access to and what level(s) (assuming they're using an authorized keypair).

e.g.:

```bash
$ ssh git@git.foo.bar
PTY allocation request failed on channel 0
hello [REDACTED username], this is git@git.foo.bar running gitolite3 3.6.11 on git 2.27.0

 R W	foo
 R W	bar
 R W	baz
 R    	quux
Connection to git.foo.bar closed.
```

It's generally a much faster and easier way of getting a repository list from the server than via a web interface or API.

Would this be something Gitea would be able to/interested in implementing?

## Screenshots

N/A

**Comment by zeripath** [comment] 2020-09-03 21:22
When you SSH to the server, SSH runs gitea serv key-id which then calls an Web API locally to talk to the Gitea web server...

Have you seen the tea command? (https://gitea.com/gitea/tea)

**Comment by lunny** [comment] 2020-09-03 22:27
Instead, currently gitea will display 
```
Hi there, <you login name>! You've successfully authenticated with the key named <your ssh key email>, but Gitea does not provide shell access.
If this is unexpected, please log in with password and setup Gitea under another user.
```
and then close the SSH connection.

The difference between gitea and the above systems is they listed the repositories but gitea didn't.

Just like @zeripath said, we have `tea` tool, it could do more. So is this necessary?

**Comment by johnnybubonic** [comment] 2020-09-04 03:16
@zeripath The problem is then that one needs an additional/external tool rather than any simple SSH client (which, typically, they need in some fashion anyways to use git).

**Comment by mrsdizzie** [comment] 2020-09-07 19:38
Duplicate of #5124

**Closed as completed by mrsdizzie** 2020-09-07 19:38 UTC
Labels: type/proposal
