### ISSUE TITLE
Mirror from Gitea Instance --> Github

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#9766] opened 2020-01-14 18:39 UTC
Github doesn't seem to have the ability to mirror repository from elsewhere. But,other Git instances can sync the code with github if implemented,thanks to git. Currently only Gitlab can do it afaik.

Gitlab can automatically sync with github repo,thus setting up mirror repo in github.

[https://stackoverflow.com/a/56466021](https://stackoverflow.com/a/56466021)

**Comment by 6543** [comment] 2020-01-14 18:45
bublicate of #2280 ... @varsbhat sadly nobody is working on this at the moment ...

**Comment by techknowlogick** [comment] 2020-01-14 18:49
If you'd like to push from gitea->github using githooks, here is a guide: https://blog.spacebear.ee/post/mirror-gitea-repos-to-github-via-githook/

Closing as a dupe of the ticket listed above.

**Closed as completed by techknowlogick** 2020-01-14 18:49 UTC
Labels: issue/duplicate
