### ISSUE TITLE
Add "tags" to the commits page

### ISSUE THREAD

**Issue by makar112233** [go-gitea/gitea#30159] opened 2024-03-28 13:00 UTC
### Feature Description

Hi. 
Is it possible to add column "tags" to the "commits" page, like in a BitBucket?

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/122980447/f35777b9-a0e6-4cc3-8e14-9a6f81b209c2)

**Comment by silverwind** [comment] 2024-03-28 16:57
No dedicated table "column" please, just a right-aligned list of tags in the same column as the commit message.

**Comment by makar112233** [comment] 2024-03-28 17:12
@silverwind yes, your offer is better than mine.

**Comment by delvh** [comment] 2024-03-28 22:18
Sounds good to me.
We should already offer the necessary route for it, (`$REPO/commit/$SHA/load-branches-and-tags`), so this might be a frontend only feature.
We can of course go the full fledged way and add a batched route that takes a number of commits at the same time and evaluates all of them, but I don't see that as a requirement for the first draft.
That way, all that needs to be done is getting a list of all commit SHAs to query, querying the route, and displaying the result.

**Comment by silverwind** [comment] 2024-03-28 22:25
The question is thought whether we want to re-layout the commits table first before attempting to exend the "mess" further 😆.

**Comment by delvh** [comment] 2024-04-02 12:28
I mean… PRs are always welcome

**Comment by kemzeb** [comment] 2024-05-27 06:20
Closing as this is a duplicate of #10036 and we currently have an open PR for it.

**Closed as completed by kemzeb** 2024-05-27 06:20 UTC
Labels: type/proposal, proposal/accepted
