### ISSUE TITLE
UI Buttons should be disabled once form is submitted

### ISSUE THREAD

**Issue by shijunti19** [go-gitea/gitea#9049] opened 2019-11-17 07:56 UTC
最新1.10版本

- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

...
![image](https://user-images.githubusercontent.com/5392211/69004701-be20a480-0952-11ea-94fd-cac9a2cb5ba8.png)
Click too fast, themes are submitted repeatedly, I can't delete them. I have to turn them off

**Comment by lunny** [comment] 2019-11-17 09:08
Please speak English.

**Comment by wzyxdwll** [comment] 2019-11-25 08:29
兄弟，你这描述的不详细，建议你修改一下标题，内容描述的详细点。
比如你做了一个什么样的操作。导致了什么样的一个结果。
你描述的我虽然明白你是啥意思，但是老外应该不懂。尤其你这图截的还是英语的。截图也不全。

**Comment by zeripath** [comment] 2019-11-25 11:54
I think that he means that we should be disabling the submit button once it has been pressed to prevent double submission.

**Comment by lunny** [comment] 2019-11-26 09:30
@zeripath Right. All buttons should be disabled once clicked. And it's better to add a loading indicator.

**Comment by wxiaoguang** [comment] 2021-12-08 07:50
Duplicate of

* https://github.com/go-gitea/gitea/issues/17111 (with more details)

Unfortunately, no ideal plan to fix it yet ....

**Closed as completed by wxiaoguang** 2021-12-08 07:50 UTC
Labels: topic/ui, issue/confirmed
