### ISSUE TITLE
GitHub Migrations for Enterprise GitHub servers

### ISSUE THREAD

**Issue by coldcoff** [go-gitea/gitea#11815] opened 2020-06-09 11:13 UTC
Hi Gitea Developers,

When using repository migrations (mirroring) there is support for GitHub, that will offer to migrate not only the code, but also Issues, Pull Requests and similar by using the GitHub API to fetch the additional content.

Please make it possible to do the same also when not using the public GitHub, i.e. "github.com".

There are enterprise GitHub instances out there, typically something like "github.company.com" or so, that will work the same, but are some "isolated" GitHub.

Currently unfortunately only the code migration is possible from such enterprise GitHub instances.

Thank you and best regards

@coldcoff

**Comment by alexanderadam** [comment] 2020-06-10 07:40
So @lunny's [PRs 6290](https://github.com/go-gitea/gitea/pull/6290) and [6200](https://github.com/go-gitea/gitea/pull/6200) solved the base functionality and I believe the issue to support more platforms is #8689. So maybe it would be better to add it over there, to have everything at one place?

**Comment by coldcoff** [comment] 2020-06-10 08:19
Good idea. I added a comment to https://github.com/go-gitea/gitea/issues/8689.

This is not really a **new** platform / **new** migration.

As it is just "GitHub with different URLs" (and the software version running there is probably a bit older than the public GitHub) the task is hopefully only to make some hardcoded GitHub URLs configurable/extendable.

So it might be a lower hanging fruit.

**Comment by lunny** [comment] 2020-06-19 01:21
If the only difference between public github and enterprise github is the domain? I would like to send a PR to support enterprise gihtub but I cannot access any enterprise github instance and could not test it. If anyone would like to help test, please let me know.

**Comment by techknowlogick** [comment] 2020-06-19 01:47
@lunny trial can be found here: https://enterprise.github.com/trial

**Comment by jolheiser** [comment] 2020-08-31 14:55
Is this solved by #12619 ?

**Comment by coldcoff** [comment] 2020-09-01 06:49
Probably. Is there some test / nghtly build already I can use to try that? I saw that's just merged to master.

**Comment by jolheiser** [comment] 2020-09-01 12:29
You can use https://try.gitea.io (can make repo private and delete after testing)

**Comment by coldcoff** [comment] 2020-09-01 12:33
Nope, unfortunately not. That one is not able to connect to our companies enterpise GitHub.

**Comment by jolheiser** [comment] 2020-09-01 13:48
Hmm, it may be worth spinning up a local instance of Gitea to see if it generated any errors trying to migrate (the logs on try would probably be a nightmare to parse through)

Theoretically it should use the same API as GitHub, so I'm curious where it's choking.  
If I have some extra time I might try testing with the trial of GH Enterprise.

Thanks for checking! 🙂

**Comment by coldcoff** [comment] 2020-09-03 08:15
Please let me know when there is any "-rc1" or "nightly" or so for me to test.

**Comment by zeripath** [comment] 2020-09-12 01:16
https://dl.gitea.io/gitea/master always has the latest build of the master branch.

We also provide a docker with the tag latest that always has the latest version of Gitea

**Comment by coldcoff** [comment] 2020-09-14 11:40
I downloaded the lastest trunk and gave it a try.

The page says that I need an access token to migrate additional stuff, so I entered some.

Although I specified a path to our enterprise instance:
![image](https://user-images.githubusercontent.com/14311781/93081440-888e3a00-f68f-11ea-9861-231d64c6f6f0.png)

The migration failed and I saw in the log:
2020/09/14 13:31:49 modules/task/task.go:51:handle() [E] Run task failed: GET https://api.github.com/repos/COMPANY/REPO: 401 Bad credentials []

So obviously the auth is tried against (hardcoded?) public GitHub, not the enterprise one?

**Comment by lunny** [comment] 2020-09-14 11:58
Could you try to remove the username on your URL?

**Comment by coldcoff** [comment] 2020-09-14 12:42
Was coming from that :-) Same.

The "Run task" goes against:  https://api.github.com/... instead of  https://api.github.COMPANY.com/

**Comment by jolheiser** [comment] 2020-09-14 13:50
Aha, I believe I know where the issue is. We are creating a new client rather than a new enterprise client. 

I will try to get a PR in sometime today.

**Comment by lunny** [comment] 2020-09-15 00:38
@lafriks We never announced we have already supported Enterprise Github servers, so I think this may be a new feature for v1.13 if @jolheiser 's PR resolve that.

**Comment by jolheiser** [comment] 2020-09-15 18:53
This is (hopefully) fixed by https://github.com/go-gitea/gitea/pull/12863

I will try spinning up a trial version of GHE to test it soon:tm:

**Closed as completed** 2020-09-21 14:36 UTC
Labels: type/bug
