### ISSUE TITLE
config option to make /explore/users private

### ISSUE THREAD

**Issue by noerw** [go-gitea/gitea#10812] opened 2020-03-24 15:57 UTC
The `/explore/users` page may contain information that is unwanted to be publicly visible or scrapable.
There should be an easy option to remove or at least hide that endpoint.

#1475 touches on this, but was closed due to staleness

**Comment by pierre-alain-b** [comment] 2020-06-06 15:35
I agree this would be very useful in many use cases!

**Comment by zeripath** [comment] 2020-08-08 17:34
This is a duplicate of #2908

**Closed as completed by zeripath** 2020-08-08 17:34 UTC
Labels: issue/duplicate
