### ISSUE TITLE
Webhook payload documentation

### ISSUE THREAD

**Issue by JustAnotherArchivist** [go-gitea/gitea#9485] opened 2019-12-24 23:50 UTC
I am currently working on a custom notification system involving Gitea. The details of this setup aren't really relevant to the topic at hand; there'll be an HTTP server that takes events via webhooks and produces notifications to send elsewhere.

My problem: there's hardly any documentation on webhooks. [The doc page](https://docs.gitea.io/en-us/webhooks/) merely lists the different hooks available (Gitea, Gogs, and a few proprietary chat platforms) and gives one example of a payload for push events plus PHP code to securely accept a message. Here's a list of things I'm missing:

- [ ] Other event types (issue changes, PRs, etc.)
- [ ] Which fields are available exactly, what are the data types and values, and which fields might be missing or have unexpected values depending on e.g. configuration or environment?
- [ ] In which Gitea versions were the fields added, changed, or removed, so that I can determine which Gitea versions are compatible with my server?
- [ ] What are the compatibility guarantees for future Gitea versions? Can I be reasonably sure that code written against current Gitea versions will work until the next major release (2.0)?

**Comment by JustAnotherArchivist** [comment] 2020-02-23 00:40
Yes, this issue is still valid...

**Comment by JustAnotherArchivist** [comment] 2020-04-28 18:13
Does any partial documentation on this exist in some obscure place I wasn't able to find, or would it have to be reconstructed from the commit history anyway? If so, it seems it shouldn't be very difficult to generate a documentation covering the first three points from the changes to `modules/structs/hook.go`. That file exists since commit 34eee25b (first released in 1.9.0), and it gets a bit messier before that due to a number of file moves/renames, but that should still be feasible; the structure of the file was the same ever since it was initially added in this repo in commit e378648c (before which it lived in the now obsolete and archived go-sdk repo, but that was all pre-1.0.0 and so probably doesn't really need to be documented). I could give that a shot.

**Comment by techknowlogick** [comment] 2020-04-28 18:14
https://github.com/drone/go-scm/tree/master/scm/driver/gitea provides examples that I refer to when looking into working with receiving webhooks

**Comment by lunny** [comment] 2024-08-02 04:01
Duplicate of #21478

**Closed as completed by lunny** 2024-08-02 04:01 UTC
Labels: type/docs, issue/confirmed
