### ISSUE TITLE
Running Gitea highly available

### ISSUE THREAD

**Issue by garymoon** [go-gitea/gitea#19700] opened 2022-05-13 19:59 UTC
### Feature Description

Hi all,

I'm sorry to knowingly post a dupe, but my hope is to avoid having this question asked again.

I am aware of [numerous tickets](https://github.com/go-gitea/gitea/issues?q=high+availability), the Discord, and the [Discourse](https://discourse.gitea.io/search?q=high%20availability). Everything I've gathered on this subject so far indicates there are some workarounds to enable such a deployment, but they're a mixed bag of tips and tricks, and spread over a very broad time period. There is also commentary indicating that gitea.com itself is being run in a HA manner, but that the process for its deployment remains undocumented.

Naturally a HA deployment would involve a shared file system (ala NFS) and a HA database, so I'm looking specifically for guidance on how to deploy and configure multiple instances Gitea itself in such an environment (I'm aware crons specifically would need to be addressed, but even on that subject it's unclear to me what the recommendation would be).

I would be happy for this issue to become a living document of sorts, or start one in a Discorse thread (or elsewhere) if preferred. I am also happy to take hints in a raw form, work through them myself, and post a more complete write-up at the end if that would be desired.

I would really appreciate any resources at all, no matter how raw.

Thank you for Gitea! :blue_heart:

**Comment by techknowlogick** [comment] 2022-05-13 20:18
Closing as dupe of https://github.com/go-gitea/gitea/issues/13791 However you can see https://gitea.com/gitea/helm-chart/pulls/205 for more info about doing what you'd like right now as the helm chart would handle everything for you.

**Closed as completed by techknowlogick** 2022-05-13 20:18 UTC
Labels: issue/duplicate

**Comment by garymoon** [comment] 2022-05-13 20:31
Oh fantastic, thank you @techknowlogick! Is there anything I should know about running it HA outside of k8s that I wouldn't get from reading that repo please? (I'm expecting a "no", just can't hurt to ask)

Thanks again! :blue_heart:
