### ISSUE TITLE
Opening and Closing the Labels Selector reloads the page

### ISSUE THREAD

**Issue by Empty2k12** [go-gitea/gitea#23545] opened 2023-03-17 14:43 UTC
### Description

When opening and closing the labels selector without selecting new labels reloads the page. This will clear all text that is currently written in any text-fields on the page unexpectedly.

### Gitea Version

1.18.5

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Docker-Image

### Database

None

**Comment by jolheiser** [comment] 2023-03-17 14:49
Duplicate of #12783 and mitigated by #23014

**Closed as not planned by jolheiser** 2023-03-17 14:49 UTC
Labels: type/bug
