### ISSUE TITLE
Feature Request: Turn off source code hosting similar to issue tracker / wiki

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#9985] opened 2020-01-25 20:43 UTC
It would be very nice to have an option in repository settings to disable source code hosting, similar to disabling the wiki or issue tracker. This would be very useful when you are making an issue tracker for projects that do not involve source code, or the source code is not publicly available, but you still do want people to be able to report bugs for your software. The same applies for the wiki too, and the Gitea Wiki is very simple, uses markdown and git under the hood. There are some cases where I just need a few Wiki pages, and I would not like to set up a MediaWiki installation which is quite heavy, and having a Gitea Wiki would be all I need. This feature doesn't sound too to implement. I know GitHub (and probably GitLab) doesn't have this feature, but in my opinion it would be quite handy.

**Comment by davidsvantesson** [comment] 2020-01-25 21:49
Duplicate of #7525

**Closed as completed** 2020-01-25 21:50 UTC
