### ISSUE TITLE
Container Regsitry Pull through cache

### ISSUE THREAD

**Issue by lachnerd** [go-gitea/gitea#26756] opened 2023-08-27 17:50 UTC
### Feature Description

Possibility to use gitea as a [pull through cache/proxy](https://docs.docker.com/registry/recipes/mirror/) for container images.

That would be a great for the container registry feature !

**Comment by KN4CK3R** [comment] 2023-08-27 18:29
Duplicate of #21223

**Closed as completed by KN4CK3R** 2023-08-27 18:29 UTC
Labels: issue/duplicate, type/proposal, topic/packages

**Comment by lachnerd** [comment] 2023-08-27 18:30
sorry i searched but didn't find it
