### ISSUE TITLE
After Update to 1.22.0 LDAP Login is not working anymore

### ISSUE THREAD

**Issue by swiedernix** [go-gitea/gitea#31228] opened 2024-06-03 12:29 UTC
### Description

Hi,
I've upgrade to 1.22.0  and after the update LDAP login is no longer possible.

I see tls handshake failures in the logfile:
2024/06/03 11:18:01 ...dap/source_search.go:424:SearchEntries() [E] LDAP Connect error, our.ldap.server:LDAP Result Code 200 "Network Error": remote error: tls: handshake failure
2024/06/03 11:18:01 .../ldap/source_sync.go:55:Sync() [E] SyncExternalUsers LDAP source failure [ourldapserver], skipped

### Gitea Version

1.22.0

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.39.3

### Operating System

RHEL 8.9

### How are you running Gitea?

running gitea from downloads: gitea-1.22.0-linux-amd64

### Database

PostgreSQL

**Comment by techknowlogick** [comment] 2024-06-03 14:57
Are you using a self-signed certificate, and which LDAP server are you using?

**Comment by silverwind** [comment] 2024-06-03 15:43
Could be a TLS cipher issue. Check if your LDAP server supports TLS 1.2 or higher with tools like https://github.com/drwetter/testssl.sh. golang since  v1.22 requires TLS 1.2 or higher by default.

**Comment by vworldat** [comment] 2024-06-04 07:56
Same here. Self-signed certificate with "skip TLS verification" selected.

Used testssl.sh to check protocols:

```
 Testing protocols via sockets except NPN+ALPN 

 SSLv2      not offered (OK)
 SSLv3      not offered (OK)
 TLS 1      offered (deprecated)
 TLS 1.1    offered (deprecated)
 TLS 1.2    offered (OK)
 TLS 1.3    not offered and downgraded to a weaker protocol
 NPN/SPDY   not offered
 ALPN/HTTP2 not offered

 Testing cipher categories 

 NULL ciphers (no encryption)                      not offered (OK)
 Anonymous NULL Ciphers (no authentication)        not offered (OK)
 Export ciphers (w/o ADH+NULL)                     not offered (OK)
 LOW: 64 Bit + DES, RC[2,4], MD5 (w/o export)      not offered (OK)
 Triple DES Ciphers / IDEA                         not offered
 Obsoleted CBC ciphers (AES, ARIA etc.)            offered
 Strong encryption (AEAD ciphers) with no FS       offered (OK)
 Forward Secrecy strong encryption (AEAD ciphers)  not offered

 Testing server's cipher preferences 

Hexcode  Cipher Suite Name (OpenSSL)       KeyExch.   Encryption  Bits     Cipher Suite Name (IANA/RFC)
-----------------------------------------------------------------------------------------------------------------------------
[..]

TLSv1.2 (no server order, thus listed by strength)
 x9d     AES256-GCM-SHA384                 RSA        AESGCM      256      TLS_RSA_WITH_AES_256_GCM_SHA384                    
 x3d     AES256-SHA256                     RSA        AES         256      TLS_RSA_WITH_AES_256_CBC_SHA256                    
 x35     AES256-SHA                        RSA        AES         256      TLS_RSA_WITH_AES_256_CBC_SHA                       
 x9c     AES128-GCM-SHA256                 RSA        AESGCM      128      TLS_RSA_WITH_AES_128_GCM_SHA256                    
 x3c     AES128-SHA256                     RSA        AES         128      TLS_RSA_WITH_AES_128_CBC_SHA256                    
 x2f     AES128-SHA                        RSA        AES         128      TLS_RSA_WITH_AES_128_CBC_SHA                       
```

**Comment by xoxys** [comment] 2024-06-04 08:21
Same here. I'm using an OpenLDAP proxy. TLS1.2 is supported:

```
 Testing protocols via sockets except NPN+ALPN 

 SSLv2      not offered (OK)
 SSLv3      not offered (OK)
 TLS 1      offered (deprecated)
 TLS 1.1    offered (deprecated)
 TLS 1.2    offered (OK)
 TLS 1.3    not offered and downgraded to a weaker protocol
 NPN/SPDY   not offered
 ALPN/HTTP2 not offered

 Testing cipher categories 

 NULL ciphers (no encryption)                      not offered (OK)
 Anonymous NULL Ciphers (no authentication)        not offered (OK)
 Export ciphers (w/o ADH+NULL)                     not offered (OK)
 LOW: 64 Bit + DES, RC[2,4], MD5 (w/o export)      not offered (OK)
 Triple DES Ciphers / IDEA                         offered
 Obsoleted CBC ciphers (AES, ARIA etc.)            offered
 Strong encryption (AEAD ciphers) with no FS       offered (OK)
 Forward Secrecy strong encryption (AEAD ciphers)  not offered

 Testing server's cipher preferences 
 TLSv1.2 (no server order, thus listed by strength)
 x9d     AES256-GCM-SHA384                 RSA        AESGCM      256      TLS_RSA_WITH_AES_256_GCM_SHA384                    
 x3d     AES256-SHA256                     RSA        AES         256      TLS_RSA_WITH_AES_256_CBC_SHA256                    
 x35     AES256-SHA                        RSA        AES         256      TLS_RSA_WITH_AES_256_CBC_SHA                       
 x84     CAMELLIA256-SHA                   RSA        Camellia    256      TLS_RSA_WITH_CAMELLIA_256_CBC_SHA                  
 x9c     AES128-GCM-SHA256                 RSA        AESGCM      128      TLS_RSA_WITH_AES_128_GCM_SHA256                    
 x3c     AES128-SHA256                     RSA        AES         128      TLS_RSA_WITH_AES_128_CBC_SHA256                    
 x2f     AES128-SHA                        RSA        AES         128      TLS_RSA_WITH_AES_128_CBC_SHA                       
 x96     SEED-SHA                          RSA        SEED        128      TLS_RSA_WITH_SEED_CBC_SHA                          
 x41     CAMELLIA128-SHA                   RSA        Camellia    128      TLS_RSA_WITH_CAMELLIA_128_CBC_SHA                  
 x07     IDEA-CBC-SHA                      RSA        IDEA        128      TLS_RSA_WITH_IDEA_CBC_SHA                          
 x0a     DES-CBC3-SHA                      RSA        3DES        168      TLS_RSA_WITH_3DES_EDE_CBC_SHA       
```

**Comment by silverwind** [comment] 2024-06-04 09:22
Actually it's likely not TLS-version related as per https://tip.golang.org/doc/go1.22#minor_library_changes:

> By default, the minimum version offered by crypto/tls servers is now TLS 1.2 if not specified with [config.MinimumVersion](https://tip.golang.org/pkg/crypto/tls#Config.MinimumVersion), matching the behavior of crypto/tls clients. This change can be reverted with the tls10server=1 GODEBUG setting.

So the TLS client has not changed it's requirement in 1.22, only the server has.

**Comment by JoelKle** [comment] 2024-06-04 14:39
The situation seems clear to me:

> By default, cipher suites without ECDHE support are no longer offered by either clients or servers during pre-TLS 1.3 handshakes. This change can be reverted with the tlsrsakex=1 GODEBUG setting.

https://tip.golang.org/doc/go1.22#minor_library_changes

https://github.com/golang/go/issues/63413

**Comment by adamoutler** [comment] 2024-06-04 14:49
Same issue.  Workaround for me was to disable encryption and change the port from 636 to 389 or from 3289 to 3268.  I use Global Directory LDAP 3268 because it's faster, but I tested with port 389 and it works as well. 
![image](https://github.com/go-gitea/gitea/assets/527919/b3cc27dc-125d-4388-98c0-d9e254c31291)

**Comment by JoelKle** [comment] 2024-06-04 14:52
@adamoutler
Could you test it again with port 636, enabled encryption and `GODEBUG="tlsrsakex=1" `
as mentioned in: https://github.com/go-gitea/gitea/issues/31228#issuecomment-2147709875
?

**Comment by adamoutler** [comment] 2024-06-04 15:05
> @adamoutler Could you test it again with port 636, enabled encryption and `GODEBUG="tlsrsakex=1" ` as mentioned in: [#31228 (comment)](https://github.com/go-gitea/gitea/issues/31228#issuecomment-2147709875) ?

I'm sorry, but I'm using a docker container setup and I'd need to adjust code to do this.  I assume it will be fixed in a month or two.

**Comment by silverwind** [comment] 2024-06-04 15:15
Ok, I'm closing this since it's working as intended and I'll be closing and pinning this for a bit.

People affected should look into upgrading their LDAP server to support modern ciphers and if that's not possible you can workaround preferably with `GODEBUG="tlsrsakex=1"` or worse, by switching to unencrypted. That flag will surely go away in a future golang version, so it won't last forever.

**Closed as not planned by silverwind** 2024-06-04 15:15 UTC
Labels: type/bug, reviewed/wontfix

**Comment by xoxys** [comment] 2024-06-04 18:42
Working OpenLDAP/slapd config:

```
TLSCipherSuite          HIGH:MEDIUM:-SSLv2:-SSLv3
TLSProtocolMin          3.1
TLSECName               secp521r1
```

To enable ECDHE ciphers `TLSECName` is required.

**Comment by reetp** [comment] 2024-08-08 17:00
Just upgraded and hit this.

I don't understand why this isn't a listed as breaking change because it literally fails all logins? No fallback as far as I can see (or rememeber).

Currently running a downloaded binary, not docker.

Have tried adding this to /etc/gitea/app.ini

`GODEBUG="tlsrsakex=1"`

Still fails.

Tried to add it to the systemd unit file (are the quotes required?) eg

```
ExecStart=/usr/local/bin/gitea web --config /etc/gitea/app.ini
Restart=always
Environment=USER=git HOME=/home/git GITEA_WORK_DIR=/var/lib/gitea GODEBUG="tlsrsakex=1"
```

Still fails.

Then tried run gitea from the CLI to try and modify LDAP in any way shape form but I get the dreaded:

`Expect user 'git' but current user is: myuser`

So can't go back, can't go forwards and can't update my LDAP server for another couple of months as it hinges on other software too. Ironically gitea is on a server that COULD run a newer verion of LDAP but I don't want to do that as it breaks all my backend authent, and I can't modify the LDAP settings in any event........

Completely and utterly stuck and no idea what to do :-(

Any advice on this appreciated at least to get it running for now.

**Comment by reetp** [comment] 2024-08-09 14:11
Well after a huge amount of wrangling I got it to work.

First, I could not get this to work and would very much like to know how to get it to work on a binary only install?

`GODEBUG="tlsrsakex=1"`

Next, and this should be better documented, is how to actively modify gitea settings via the CLI. I stumbled over this while looking for something else and modified it for my own use.

On a *buntu box it required this to get around the `Expect user 'git' ` issue:

`sudo -H -u git bash -c '/usr/local/bin/gitea admin auth update-ldap  --id 1 --skip-tls-verify --security-protocol starttls -c /etc/gitea/app.ini'`

I had to read the code here to find the different security protocols as that isn't documented either

unencrypted | starttls | ldaps

Change your comand/directory to suit.

Found those here: admin_auth_ldap_test.go

Would be nice to be able to:

a) query existing settings
b) have expected 'fixed' variables in the docs

Next was to check what Ciphers were loaded.

`nmap --script ssl-enum-ciphers -p636 localhost`

```
PORT    STATE SERVICE
636/tcp open  ldapssl
| ssl-enum-ciphers: 
|   TLSv1.2: 
|     ciphers: 
|       TLS_RSA_WITH_AES_128_CBC_SHA - strong
|       TLS_RSA_WITH_AES_128_CBC_SHA256 - strong
|       TLS_RSA_WITH_AES_128_GCM_SHA256 - strong
|       TLS_RSA_WITH_AES_256_CBC_SHA - strong
|       TLS_RSA_WITH_AES_256_CBC_SHA256 - strong
|       TLS_RSA_WITH_AES_256_GCM_SHA384 - strong
|       TLS_RSA_WITH_CAMELLIA_128_CBC_SHA - strong
|       TLS_RSA_WITH_CAMELLIA_256_CBC_SHA - strong
|     compressors: 
|       NULL
|_  least strength: strong

```

Next was to check the existing non RSA CipherSuites (yes messy but it works for me). I expected to be out of luck:

`openssl ciphers -v |grep v1.2 |grep -v RSA |grep ECDH`

```
ECDHE-ECDSA-AES256-GCM-SHA384 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=AESGCM(256) Mac=AEAD
ECDHE-ECDSA-AES256-SHA384 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=AES(256)  Mac=SHA384
ECDH-ECDSA-AES256-GCM-SHA384 TLSv1.2 Kx=ECDH/ECDSA Au=ECDH Enc=AESGCM(256) Mac=AEAD
ECDH-ECDSA-AES256-SHA384 TLSv1.2 Kx=ECDH/ECDSA Au=ECDH Enc=AES(256)  Mac=SHA384
ECDHE-ECDSA-AES128-GCM-SHA256 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=AESGCM(128) Mac=AEAD
ECDHE-ECDSA-AES128-SHA256 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=AES(128)  Mac=SHA256
ECDH-ECDSA-AES128-GCM-SHA256 TLSv1.2 Kx=ECDH/ECDSA Au=ECDH Enc=AESGCM(128) Mac=AEAD
ECDH-ECDSA-AES128-SHA256 TLSv1.2 Kx=ECDH/ECDSA Au=ECDH Enc=AES(128)  Mac=SHA256
```

Hmmm. A chance?

Next on the LDAP server I added these additional Cipher suites to etc/openldap/slapd.conf to test

ECDH-ECDSA-AES128-GCM-SHA256:ECDH-ECDSA-AES128-SHA256:ECDH-ECDSA-AES256-GCM-SHA384:ECDH-ECDSA-AES256-SHA384

Apparently to use ECDH you need TLSECName as well. So:

```
TLSCipherSuite ECDH-ECDSA-AES128-GCM-SHA256:ECDH-ECDSA-AES128-SHA256:ECDH-ECDSA-AES256-GCM-SHA384:ECDH-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:HIGH@STRENGTH:!SSLv2:!ADH:!aNULL:!MD5:!RC4
TLSECName               secp521r1
```

Restart ldap server and test. Oh.

```
PORT    STATE SERVICE
636/tcp open  ldapssl
| ssl-enum-ciphers: 
|   TLSv1.2: 
|     ciphers: 
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA - strong
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 - strong
|       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 - strong
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA - strong
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 - strong
|       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 - strong
|       TLS_RSA_WITH_AES_128_CBC_SHA - strong
|       TLS_RSA_WITH_AES_128_CBC_SHA256 - strong
|       TLS_RSA_WITH_AES_128_GCM_SHA256 - strong
|       TLS_RSA_WITH_AES_256_CBC_SHA - strong
|       TLS_RSA_WITH_AES_256_CBC_SHA256 - strong
|       TLS_RSA_WITH_AES_256_GCM_SHA384 - strong
|       TLS_RSA_WITH_CAMELLIA_128_CBC_SHA - strong
|       TLS_RSA_WITH_CAMELLIA_256_CBC_SHA - strong
|     compressors: 
|       NULL
|_  least strength: strong

```

I was concerned that the TLS_ECDHE still had RSA but I went to the login page and it worked immediately!

So the answer is it will still work, but needs the correct setup.

Hope that helps someone.
