### ISSUE TITLE
Link to blank page on issues of organization

### ISSUE THREAD

**Issue by Testyourstuff** [go-gitea/gitea#8405] opened 2019-10-06 23:36 UTC
- Gitea version (or commit ref): 1.9.3
- Git version: 2.11.0
- Operating system: debian9
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
  - [x] MariaDb 10.1
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/org/DemoOrga/issues?type=all&repo=13839&sort=&state=open
  - [ ] No
  - [ ] Not relevant
- Log gist:

2019/10/06 23:46:17 .../xorm/session_get.go:99:nocacheGet() [I] [SQL] SELECT `id`, `lower_name`, `name`, `full_name`, `email`, `keep_email_private`, `passwd`, `must_change_password`, `login_type`, `login_source`, `login_name`, `type`, `location`, `website`, `rands`, `salt`, `language`, `description`, `created_unix`, `updated_unix`, `last_login_unix`, `last_repo_visibility`, `max_repo_creation`, `is_active`, `is_admin`, `allow_git_hook`, `allow_import_local`, `allow_create_organization`, `prohibit_login`, `avatar`, `avatar_email`, `use_custom_avatar`, `num_followers`, `num_following`, `num_stars`, `num_repos`, `num_teams`, `num_members`, `visibility`, `diff_view_style`, `theme` FROM `user` WHERE `id`=? LIMIT 1 []interface {}{2}
2019/10/06 23:46:17 .../xorm/session_raw.go:87:queryRow() [I] [SQL] SELECT count(*) FROM `notification` WHERE (user_id = ?) AND (status = ?) []interface {}{2, 0x1}

## Description

> create organisation DemoOrg
> create repository firstrepooforga for organisation DemoOrg
> create firstissueoforga for firstrepooforga

1. select "Issues" (see screenshot)
2. select DemoOrg
3. select firstrepooforgaof DemoOrg

=> links to blank page

Please note:
- The log is from my own gitea instance, while the screenshot is from try.gitea.io
- I can provide whole log of what happens on my instance (log level info atm)
- on the same users, there's another organisation, which oddly works. See second screenshot (the one with organisation1/repo1/issue1)

## Screenshots

![grafik](https://user-images.githubusercontent.com/56236732/66277702-7f52f580-e8a2-11e9-862f-5fc56dccad12.png)
![grafik](https://user-images.githubusercontent.com/56236732/66276572-d9e55500-e894-11e9-81e6-b048d0d75830.png)

**Comment by lafriks** [comment] 2019-10-11 21:15
I can also confirm this issue

**Comment by donou** [comment] 2019-11-21 08:31
To me the issue appears only when the organization is set to a private one. If I configure it as limited or public, all is OK.

Guess, sometimes, gitea trusts no one.

**Comment by zeripath** [comment] 2020-01-20 12:31
Is this still an issue?

**Comment by donou** [comment] 2020-01-27 05:57
In my private environment, running 1.10.3 as a docker stack, the issue is still present.
On try.gitea.io, running 1.12.0+dev-193-g48abe41ea, I cannot repeat the issue.

**Comment by zeripath** [comment] 2020-01-27 10:10
OK, I guess the question is if this has been fixed in 1.11. If it's in the 1.11 rc then we can close this as 1.11 should be released any time now...

**Comment by lafriks** [comment] 2020-02-02 15:51
Closing as fixed, reopen if it is not and can be repeated on try.gitea.io

**Closed as completed by lafriks** 2020-02-02 15:51 UTC
Labels: type/bug
