### ISSUE TITLE
[UX] make more visible warning for setting repo to private

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#25085] opened 2023-06-05 14:48 UTC
## Now

![image](https://user-images.githubusercontent.com/1810977/172717307-aeaf1e21-25dd-46eb-8ba9-510ee3bea53d.png)

_Originally posted by @42wim in https://github.com/go-gitea/gitea/issues/19904#issuecomment-1150417113_

**Comment by 6543** [comment] 2023-06-05 14:53
I propose to move this checkbox to the dangeroups part and convert it into a button.
there we can also describe ireversible processes that will happen if clicked

**Comment by alystair** [comment] 2023-10-11 06:24
Dupe of my request #23826

**Closed as completed** 2023-10-15 12:41 UTC
Labels: issue/duplicate, topic/ui, good first issue, topic/ui-interaction
