### ISSUE TITLE
Gitea version in /api/v1 shown with html-encoded "+" sign

### ISSUE THREAD

**Issue by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [go-gitea/gitea#14950] opened 2021-03-11 00:02 UTC
- Gitea version (or commit ref): `Gite Version: 1.14.0+dev-825-g5b94a07ab`
- Git version: `git version 2.31.0.rc2.261.g7f71774620`
- Operating system: Arch Linux
- Built from: sources
- Run with: `systemd`
- Database:
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes - https://try.gitea.io/api/swagger

## Description
As title tells, Gitea version is getting shown with the "+" sign html-encoded while it should be rendered.
I don't recall this issue being previously present, might have something to do with the recent switch to chi.
Both api (`/api/v1/version`) and footer are getting the string correctly (as they always did), which makes me think this is only specific to how the version string is rendered from the template on *this* page (again, this is new)...

## Screenshots
page footer on my instance:
![image](https://user-images.githubusercontent.com/61180606/110715063-d205af00-8204-11eb-853b-bf4dd540dd9d.png)

swagger on my instance:
![image](https://user-images.githubusercontent.com/61180606/110714866-7a674380-8204-11eb-83bc-7d30e64709de.png)

swagger on try:
![image](https://user-images.githubusercontent.com/61180606/110714769-5277e000-8204-11eb-8109-e132b88c6ec7.png)

`/api/v1/version` on my instance:
![image](https://user-images.githubusercontent.com/61180606/110714928-966ae500-8204-11eb-88bf-906c6e341ee5.png)

since try is atm running the same version as my instance, it shows the same (version) thing as my instance

**Comment by techknowlogick** [comment] 2021-03-11 00:57
This is due to a PR of mine, but I believe this issue is a duplicate of a ticket that @6543 opened as the issue was discovered before my PR was merged.

I'm going to close this, however @6543 please re-open if I am mistaken.

**Closed as completed by techknowlogick** 2021-03-11 00:57 UTC
Labels: issue/duplicate

**Comment by 6543** [comment] 2021-03-11 01:00
a issue of the swagger ui we use to display our swagger json ... there should be an open issue about it

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment] 2021-03-11 10:45
> This is due to a PR of mine, but I believe this issue is a duplicate of a ticket that @6543 opened as the issue was discovered before my PR was merged.

sorry, my bad, there really is an issue open about this.
I was just overly eager with this one. 🙈
