### ISSUE TITLE
[Proposal] Ability to submit reviews for multiple code lines

### ISSUE THREAD

**Issue by ebadfd** [go-gitea/gitea#25492] opened 2023-06-24 13:05 UTC
### Feature Description

When submitting a review it would be good to select multiple lines and submit the pull request, as a example as a user I should be able to select multiple lines and add a review to the pull request.

I am willing to implement this feature , please refer to below screenshot for example from github

### Screenshots

![Screenshot 2023-06-24 at 18 37 02](https://github.com/go-gitea/gitea/assets/66930150/aa87fba2-c14f-4722-9ee8-79aeba2a7949)

**Comment by delvh** [comment] 2023-06-24 13:21
Duplicate of #12640

**Closed as not planned by delvh** 2023-06-24 13:21 UTC
Labels: type/proposal, type/feature
