### ISSUE TITLE
Hide whitespace in comparisons

### ISSUE THREAD

**Issue by rugk** [go-gitea/gitea#716] opened 2017-01-22 12:13 UTC
Similar to GitHub's (AFAIK) new option in comparisons (e.g. pull requests), Gitea should be able to hide the whitespace when doing comparisons (and of course to show it).
There should be a switch in the comparison view.

![](https://cloud.githubusercontent.com/assets/11966684/19623260/37143586-98c3-11e6-8ce2-daa788d2fdc9.png)

---

Upstream issue: https://github.com/gogits/gogs/issues/3795

**Comment by bobheadxi** [comment] 2018-05-16 04:07
I think I might have a crack at this

**Comment by zeripath** [comment] 2019-01-26 14:00
Fixed by #4683

**Comment by PaulBol** [comment] 2019-09-11 06:20
I don't think that the issue is fully addressed. For a PR I see the whitespace dropdown but not for a commit. In fact it took me a while to realize this as I was sure the option existed but couldn't find it - because I was looking at a commit comparison page.

Can the issue be re-opened?

**Comment by lunny** [comment] 2019-09-11 06:56
You could change the options on repository settings.

**Comment by PaulBol** [comment] 2019-09-11 07:16
Thanks for your feedback. I didn't find any setting that seems to be related to the commit view. Could you please give me a hint where to look?

**Comment by e1fueg0** [comment] 2019-10-14 12:32
@lunny I also can't find it, please show.

**Comment by e1fueg0** [comment] 2019-10-14 13:14
I looked into the code and found out the whitespace ignorance is only implemented for pull requests.
Please can it be implemented for regular commits @lunny ?

**Comment by PaulBol** [comment] 2019-11-08 14:19
I must say that I didn't find the option on Github either to ignore whitespace changes on the commit view like https://github.com/go-gitea/gitea/commit/b747501337a50b847631efe0041cf2c994f4a7fa. But I'm having troubles to see why the option exists for a pull request and not for a single commit. @rugk initially talked about comparisons in general.

**Comment by lunny** [comment] 2019-11-09 16:32
@e1fueg0 sorry, I missed this.

**Comment by maximilize** [comment] 2022-04-27 09:22
It seems like this feature is already implemented. However, it would be nice if the last selected option like `Ignore changes in amount of whitespaces` is remembered.

**Comment by wxiaoguang** [comment] 2022-04-27 10:19
It is in latest 1.17
* https://github.com/go-gitea/gitea/pull/15566

**Comment by Ryuno-Ki** [comment] 2022-06-05 15:55
@wxiaoguang Why was this reopened?

**Comment by wxiaoguang** [comment] 2022-06-05 16:03
Oh yes, it can be closed. 😊

If there is anything missing, feel free to reopen.

**Closed as completed by wxiaoguang** 2022-06-05 16:03 UTC
Labels: type/feature, topic/ui, issue/confirmed
