### ISSUE TITLE
Number of lines in the file off by one

### ISSUE THREAD

**Issue by BenGH28** [go-gitea/gitea#29499] opened 2024-02-29 15:48 UTC
### Description

When looking at a file, the top shows the number of lines that the file has.  When you look at the file itself, each line being number, it has one less line than what is reported at the top.

### Gitea Version

1.21.7

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

my instance
 ![image](https://github.com/go-gitea/gitea/assets/45215137/226db03f-db7a-4368-8d78-8e3c2da775e3)

on the test site
![image](https://github.com/go-gitea/gitea/assets/45215137/9fab8ac8-b160-436a-94b3-ab893e243743)

### Git Version

2.40.1

### Operating System

Ubuntu

### How are you running Gitea?

docker image

### Database

MySQL/MariaDB

**Comment by silverwind** [comment] 2024-02-29 17:15
Should be in progress in https://github.com/go-gitea/gitea/pull/29260.

**Comment by delvh** [comment] 2024-02-29 17:16
Does not look related to me

**Comment by silverwind** [comment] 2024-02-29 17:17
> Does not look related to me

See https://github.com/go-gitea/gitea/pull/29260#issuecomment-1963164536 and replies.

**Comment by yp05327** [comment] 2024-03-01 00:00
maybe duplicate of #27377?

**Closed as completed** 2024-03-02 09:55 UTC
Labels: issue/duplicate
