### ISSUE TITLE
Error while drawing the commit graph

### ISSUE THREAD

**Issue by axifive** [go-gitea/gitea#4047] opened 2018-05-25 19:42 UTC
- Gitea version (or commit ref): 2eabf18
- Git version: Go1.10.2
- Operating system: Linux
- Database (use `[x]`):
  - [x] MySQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/go-gitea/gitea/graph
- Log gist:
js error: https://gist.github.com/axifive/c18d8143fc551e6d01e2b563914e521c

## Description
Commit graph with a large number of branches is shifted and drawn incorrectly

## Screenshots
1.
![2018-05-25 22 32 00](https://user-images.githubusercontent.com/844963/40563186-965db0b8-606c-11e8-837c-e23cccb7bcdc.png)
2.
![2018-05-25 22 32 12](https://user-images.githubusercontent.com/844963/40563196-9b8ef7a4-606c-11e8-8dd3-45fa265620c7.png)

**Comment by kjellkvinge** [comment] 2018-05-28 05:42
This might be a duplicate of #3382

**Comment by daviian** [comment] 2018-05-28 06:11
@lunny Can be closed as duplicate

**Closed as completed** 2018-05-28 06:25 UTC
Labels: type/bug
