### ISSUE TITLE
Bug: 8 of my organisations refers to the same avatarID

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#14199] opened 2020-12-30 19:45 UTC
- Gitea version (or commit ref): 1.13.1
- Git version: 2.25.1
- Operating system: Ubuntu 20.04.1
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Description

Today my gitea instance "lost" some avatars. Just started my server and started uodate mirrors task. During the process I created new organisation. Avatar was shown. Than I mirrored some projects to the new organisation and that I see:

![image](https://user-images.githubusercontent.com/8334250/103377224-0f501100-4adf-11eb-927b-374d4932f780.png)

![image](https://user-images.githubusercontent.com/8334250/103377249-27279500-4adf-11eb-8b72-3613c92a9c3e.png)

And in the gitea.log I see for every missing avatar the same Avatar ID

```
2020/12/30 20:41:37 ...ers/routes/routes.go:165:func2() [W] Unable to find avatars d41d8cd98f00b204e9800998ecf8427e
2020/12/30 20:42:24 ...ers/routes/routes.go:165:func2() [W] Unable to find avatars d41d8cd98f00b204e9800998ecf8427e
2020/12/30 20:42:24 ...ers/routes/routes.go:165:func2() [W] Unable to find avatars d41d8cd98f00b204e9800998ecf8427e
2020/12/30 20:42:24 ...ers/routes/routes.go:165:func2() [W] Unable to find avatars d41d8cd98f00b204e9800998ecf8427e
2020/12/30 20:42:24 ...ers/routes/routes.go:165:func2() [W] Unable to find avatars d41d8cd98f00b204e9800998ecf8427e
2020/12/30 20:42:24 ...ers/routes/routes.go:165:func2() [W] Unable to find avatars d41d8cd98f00b204e9800998ecf8427e
2020/12/30 20:42:25 ...ers/routes/routes.go:165:func2() [W] Unable to find avatars d41d8cd98f00b204e9800998ecf8427e
2020/12/30 20:42:25 ...ers/routes/routes.go:165:func2() [W] Unable to find avatars d41d8cd98f00b204e9800998ecf8427e
2020/12/30 20:42:25 ...ers/routes/routes.go:165:func2() [W] Unable to find avatars d41d8cd98f00b204e9800998ecf8427e
2020/12/30 20:42:41 ...ers/routes/routes.go:165:func2() [W] Unable to find avatars d41d8cd98f00b204e9800998ecf8427e
2020/12/30 20:42:41 ...ers/routes/routes.go:165:func2() [W] Unable to find avatars d41d8cd98f00b204e9800998ecf8427e
2020/12/30 20:42:41 ...ers/routes/routes.go:165:func2() [W] Unable to find avatars d41d8cd98f00b204e9800998ecf8427e
2020/12/30 20:42:42 ...ers/routes/routes.go:165:func2() [W] Unable to find avatars d41d8cd98f00b204e9800998ecf8427e
2020/12/30 20:42:42 ...ers/routes/routes.go:165:func2() [W] Unable to find avatars d41d8cd98f00b204e9800998ecf8427e
2020/12/30 20:42:42 ...ers/routes/routes.go:165:func2() [W] Unable to find avatars d41d8cd98f00b204e9800998ecf8427e
2020/12/30 20:42:42 ...ers/routes/routes.go:165:func2() [W] Unable to find avatars d41d8cd98f00b204e9800998ecf8427e
2020/12/30 20:42:42 ...ers/routes/routes.go:165:func2() [W] Unable to find avatars d41d8cd98f00b204e9800998ecf8427e
2020/12/30 20:42:48 ...ers/routes/routes.go:165:func2() [W] Unable to find avatars d41d8cd98f00b204e9800998ecf8427e
2020/12/30 20:42:48 ...ers/routes/routes.go:165:func2() [W] Unable to find avatars d41d8cd98f00b204e9800998ecf8427e
2020/12/30 20:42:49 ...ers/routes/routes.go:165:func2() [W] Unable to find avatars d41d8cd98f00b204e9800998ecf8427e
2020/12/30 20:42:49 ...ers/routes/routes.go:165:func2() [W] Unable to find avatars d41d8cd98f00b204e9800998ecf8427e
2020/12/30 20:42:49 ...ers/routes/routes.go:165:func2() [W] Unable to find avatars d41d8cd98f00b204e9800998ecf8427e
2020/12/30 20:42:49 ...ers/routes/routes.go:165:func2() [W] Unable to find avatars d41d8cd98f00b204e9800998ecf8427e
2020/12/30 20:42:49 ...ers/routes/routes.go:165:func2() [W] Unable to find avatars d41d8cd98f00b204e9800998ecf8427e
```

During the update mirrors task I deleted an empty organisation.

Looks like all the organizations has the same avatar. Cause after I added new organisation the avatar with the ID d41d8cd98f00b204e9800998ecf8427e was created and all the 8 organisations refers to the same avatar ID.

![image](https://user-images.githubusercontent.com/8334250/103378169-bb92f700-4ae1-11eb-8682-d3dfe2def8e9.png)

**Comment by techknowlogick** [comment] 2020-12-31 00:14
I feel like this could be related to https://github.com/go-gitea/gitea/issues/14176, at the very least be caused by something similar

**Comment by somera** [comment] 2020-12-31 01:09
> I feel like this could be related to #14176, at the very least be caused by something similar

Every new organisation overwrites the one Avatar ID with the new binary data. Looks like the bug was first in Gitea 1.13.0.

**Comment by somera** [comment] 2020-12-31 01:14
The avatar column in the user table for the last organisations

![image](https://user-images.githubusercontent.com/8334250/103389220-e1ce8c00-4b0d-11eb-8be8-d158972dda7f.png)

**Comment by lunny** [comment] 2021-01-02 03:26
I think this is related with #13649

**Comment by silverwind** [comment] 2021-01-03 14:22
Should be fixed by https://github.com/go-gitea/gitea/pull/14217.

**Closed as completed by silverwind** 2021-01-03 14:22 UTC
Labels: type/bug, topic/ui

**Comment by somera** [comment] 2021-01-03 14:49
> Should be fixed by #14217.

Will the fix repair the affected organisations?

In which release will be the fix available?

**Comment by lunny** [comment] 2021-01-03 15:04
@somera Will be the incoming v1.13.2

**Comment by somera** [comment] 2021-02-02 15:48
> @somera Will be the incoming v1.13.2

Thx. I updated to 1.13.2. And what I should do, to repair the affected organisations?

**Comment by lunny** [comment] 2021-02-03 01:35
@somera I think you can try `updated use_custom_avatar from t to f for those organization stored id in column avatar.`

**Comment by somera** [comment] 2021-02-03 03:22
> @somera I think you can try `updated use_custom_avatar from t to f for those organization stored id in column avatar.`

Is there an hidden regenerate random avatar function?
