### ISSUE TITLE
Disable Submit button once clicked

### ISSUE THREAD

**Issue by biju-ps** [go-gitea/gitea#17775] opened 2021-11-23 05:50 UTC
### Gitea Version

All Versions

### Operating System

All OS

### Browser Version

Chrome

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

On a slow network , once the user click the comment or some submit button, The button is still enabled. Some user thinks the page is not posted and re-try by clicking the button again and again. In result multiple issues/comments will be created. 

Sample [here at try.gitea.io](https://try.gitea.io/biju-ps/Test/issues/1#issuecomment-112251)

Sample screenshots attached
## How to reproduce 
On Chrome, Change network to slow 3g and post a comment to this issue. While the page is loading click on the button 2-3 times. *Multiple copy of the same issue will be posted !!* 
## Resolution
Disable all post buttons immediately once clicked 

### Screenshots

![Uploading image.png…]()

**Comment by biju-ps** [comment] 2021-11-23 05:52
![image](https://user-images.githubusercontent.com/2868701/142976882-6af6686b-0513-4f25-9ed7-ca29f70b654f.png)

**Comment by wxiaoguang** [comment] 2021-11-23 05:59
Duplicate of

* https://github.com/go-gitea/gitea/issues/17111

Still no agreement about how to fix it  elegantly.

* https://github.com/go-gitea/gitea/pull/16157

**Closed as completed** 2021-11-23 07:24 UTC
Labels: issue/duplicate
