### ISSUE TITLE
Error 500 in package view after uploading pypi package

### ISSUE THREAD

**Issue by gd197** [go-gitea/gitea#21495] opened 2022-10-18 06:46 UTC
### Description

Error 500 is shown when trying to get list of package for an organization.
This occurred after uploading some python packages (wheels) with twine.
Logs show this error:
`
2022/10/18 08:27:00 .../web/user/package.go:58:ListPackages() [E] [634e4734-29] GetPackageDescriptors: pypi.Metadata.Description: readStringSlowPath: unexpected end of input, error found in #10 byte of ...|coon:\")\n|..., bigger context ...|:vampire: :pile_of_poo: :thumbs_up: :raccoon:\")\n|...
`
I created this ticket to not forget but I'm still checking what could have been happened, I will update the ticket accordingly.
First feeling is that a user tried to upload a corrupted package.

### Gitea Version

1.17.1

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.27

### Operating System

RHEL7

### How are you running Gitea?

executable from GitHub delivery

### Database

MySQL

**Comment by lunny** [comment] 2022-10-18 06:52
Could you try to upgrade to v1.17.3?

**Comment by gd197** [comment] 2022-10-18 06:56
Yep that is my plan, will do that in the next coming hours.

**Comment by gd197** [comment] 2022-10-18 09:29
same issue on 1.17.3 :(
![image](https://user-images.githubusercontent.com/25028540/196392860-e8fcbe1e-ddc3-4727-9f6e-7052b71749ac.png)

**Comment by gd197** [comment] 2022-10-18 09:32
one of these wheels caused the issue
- bleach-5.0.1
- commonmark-0.9.1
- readme_renderer-37.2
- rfc3986-2.0.0
- rich-12.6.0
- twine-4.0.0
- wheel-0.37.1

I'm setting up a new instance to reproduce

**Comment by gd197** [comment] 2022-10-18 09:45
the package causing the issue is rich-12.6.0
https://files.pythonhosted.org/packages/32/60/81ac2e7d1e3b861ab478a72e3b20fc91c4302acd2274822e493758941829/rich-12.6.0-py3-none-any.whl
still checking whether the dl from user was not corrupted

**Comment by gd197** [comment] 2022-10-18 10:02
no issue / not reproducible in a new  1.17.1 environment.
Looks like there were an issue when the user dl the package from pypi or when publishing it with twine in gitea.
Nevertheless, it is not possible to delete the package in the gitea registry nor updating it.

**Comment by gd197** [comment] 2022-10-18 10:23
here is a snapshot of the metadata rendered by gitea.
please note that according to the log, gitea is failing after the 
`>>> console.print `  comment.
Note also that external png references are rendered out of the box
![image](https://user-images.githubusercontent.com/25028540/196404629-ce7b8d40-9a0f-4bfe-aaad-a6d3e1c92565.png)

**Comment by lunny** [comment] 2022-10-18 10:31
Did you use utf8mb4 in your MySQL?

**Comment by gd197** [comment] 2022-10-18 11:46
CHARSET is utf8 in gitea.ini

**Comment by gd197** [comment] 2022-10-18 13:55
The database where the issue occurs looks correctly set to utf8mb4 anyways
```
MariaDB [(none)]> SELECT * FROM INFORMATION_SCHEMA.SCHEMATA;
+--------------+--------------------+----------------------------+------------------------+----------+
| CATALOG_NAME | SCHEMA_NAME        | DEFAULT_CHARACTER_SET_NAME | DEFAULT_COLLATION_NAME | SQL_PATH |
+--------------+--------------------+----------------------------+------------------------+----------+
| def          | information_schema | utf8                       | utf8_general_ci        | NULL     |
| def          | gitea              | utf8mb4                    | utf8mb4_unicode_ci     | NULL     |

```

**Comment by lunny** [comment] 2022-10-18 15:32
Keep database as utf8mb4 and gitea.ini as utf8mb4 both.

**Comment by lunny** [comment] 2022-10-18 15:56
If your database tables are utf8, you need to convert them to utf8mb4. Gitea also provide a command `./gitea convert` to help to do that. You should also set app.ini CHARSET entry as utf8mb4. You should change both.

**Comment by gd197** [comment] 2022-10-19 06:29
my issue is :
database is utf8mb4 but CHARSET in app.ini is utf8 I fear we corrupted the metadata entry for the mentioned package.

**Comment by lunny** [comment] 2022-10-19 06:49
> my issue is : database is utf8mb4 but CHARSET in app.ini is utf8 I fear we corrupted the metadata entry for the mentioned package.

Then you can just change app.ini CHARSET to utf8mb4 and restart Gitea

**Comment by gd197** [comment] 2022-10-19 07:17
ok done, but we have still the issue for the mentioned package.
API is working fine for publishing/downloading packages but the GUI is crashing.
My understanding is that we have corrupted the metadata entry for this package (which was containing emojis).
As far as I can see, there is no API for deleting a package, meaning that we should do it manually in database.

**Comment by KN4CK3R** [comment] 2022-10-20 20:56
You could manually navigate to `/<owner>/-/packages/<type>/<name>/<version>/settings` to delete the package.

> As far as I can see, there is no API for deleting a package, meaning that we should do it manually in database.

There is an API call for that: https://gitea.com/api/swagger#/package/deletePackage

**Comment by lunny** [comment] 2024-03-25 15:12
I think this could be closed as it's caused by mixed configuration.

**Closed as completed by lunny** 2024-03-25 15:12 UTC
Labels: type/bug, topic/packages
