### ISSUE TITLE
Inconsistent button size on the team web page

### ISSUE THREAD

**Issue by nanguanlin6** [go-gitea/gitea#27745] opened 2023-10-23 05:38 UTC
### Description

There are two bugs. 
Left side: the first button is selected by a class because he is the direct child of attached.header, while the second button is wrapped by a form class.
Right side: the class of join is wrong. It should be `tiny` instead of `small`.

### Screenshots

![two_button](https://github.com/go-gitea/gitea/assets/70063547/e5fe4ccb-ca06-4b65-838b-a54ea16367e5)

### Gitea Version

latest codebase

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

none

**Comment by Virtual4087** [comment] 2023-10-23 05:44
I'd like to work on this issue if you can instruct me how to reproduce it.

**Comment by lng2020** [comment] 2023-10-23 05:49
It's on the web page. You don't need to reproduce it...
The first one probably required some familiarity with the CSS style in Gitea. If you directly change the class style, It may result in some side effects.

**Comment by silverwind** [comment] 2023-10-23 14:39
https://github.com/go-gitea/gitea/pull/27632 sounds related but it's not because neither button are dropdowns in those screenshots.

**Comment by wxiaoguang** [comment] 2023-10-23 14:51
> #27632 sounds related but it's not because neither button are dropdowns in those screenshots.

Nope, not related.

The problem is the button styles were polluted by `.ui.right>.button`, but another button is in `<form>`

**Comment by wxiaoguang** [comment] 2024-01-18 07:06
Fixed by:  Fix button size in "attached header right" #28770

**Closed as completed by wxiaoguang** 2024-01-18 07:06 UTC
Labels: type/bug, topic/ui
