### ISSUE TITLE
Using release binary on armv7 fails with segmentation fault

### ISSUE THREAD

**Issue by jlelse** [go-gitea/gitea#6700] opened 2019-04-21 10:36 UTC
I tried upgrading my Gitea Dockerfile for armv7 (based on Alpine) which uses the binary from the release page from 1.7.6 to 1.8.0, but starting Gitea failed.

I was able to reproduce it in an empty alpine container on the armv7 machine by downloading the 1.7.6 binary and executing it - that works without problems, but downloading and executing the 1.8.0 binary fails with a "segmentation fault".

What can be the problem?

Edit: I just tried it in an ubuntu container too, same problem, so it seems like there's something wrong with the binary.

**Comment by jlelse** [comment] 2019-04-21 10:52
My current workaround is to use the arm-6 binary.

**Comment by vmario89** [comment] 2019-04-21 12:15
Hi, i got the same problem. I am running Gitea on Xubuntu 18 (odroid platform armv7). The newest 1.8.0 armv7 fails to start with segmentation fault and without any additional comment / stacktrace. I tried with different go versions, but no difference (1.12.1, 1.12.4). It already occured on beta releases 1.8; reverting back to 1.7.5 works fine. 

Now i solved the problem like @jlelse did, to use armv6 - works!. But i guess its not the best solution. 

regards, Mario

**Comment by lunny** [comment] 2019-04-21 12:49
Yes, we ever have an issue to report that before v1.8.0 release. It maybe related with our cross-platform compile.

**Comment by jlelse** [comment] 2019-04-21 13:01
I'm sorry I didn't report this before, but I didn't try any beta release to wait for the final one.

**Comment by focmb** [comment] 2019-04-22 12:27
Same here on a raspberry with gitea 1.8.0 arm v7

**Comment by Akcaxup** [comment] 2019-04-23 09:07
On RaspberryPi Gitea 1.8.0 failed start without any messages in logs. Gitea 1.7.6 works greate

**Comment by sorin-p** [comment] 2019-04-24 13:51
Hi guys.

Can this be fixed by just rebuilding the code from "v1.8.0" branch with the latest version of go compiler (1.12.4) on a Linux x86 machine (with GOOS, and GOARCH set for linux/arm), or does it need some changes in the source code as well?
Thanks.

**Comment by zeripath** [comment] 2019-04-24 15:30
For those new to this issue armv6 works.

The issue is apparently something to do with our building environment. The segfault happens extremely early and appears to be when we assign the data segment value main.Version on line 28 however this may simply be first running line of the go program - so I'm not sure whether that's just poor information.

I guess an option might be to try to run the Gitea program from within an unreadable directory - if that panics from within Macaron (which is known about) rather than segfaults - then we know it's something to do with main.Version. In which case the problem would likely be the linker and its override of main.Version - either we aren't telling the linker that this is an armv7 binary and its detection is wrong or its making an incorrect assumption about where to put the override - if not then it could still be something to do with that but it's less suspicious.

Other putative causes such as glibc version, kernel version have been suggested but I'm not certain about this as people seem to be able to cross-compile without hitting this bug.

**Comment by zeripath** [comment] 2019-04-24 19:11
@sorin-p I believe just building it should work.

**Comment by Josue-T** [comment] 2019-05-08 17:02
I have the same issue with the version 1.8.0 and 1.8.1

**Comment by sorin-p** [comment] 2019-05-08 18:42
Hi guys.
I can confirm, build 1.8.1 fails with "Bus error" while using armv7 binary, and using armv6 binary works fine.

**Comment by rbouikila** [comment] 2019-05-13 13:36
I have the same issue with the version 1.8.0 and 1.8.1 on armbian.

**Comment by Wurstnase** [comment] 2019-06-22 08:39
I successfully build the 1.8.3 for arm-7 and run it currently on my Synology NAS.
Until SHA 8eba27c79 I was able to build. The change with the vfsgen I've got some errors.

However. If someone need the 1.8.3 binary for arm-7, I will upload it. Appropriated link will follow.

**Comment by Wurstnase** [comment] 2019-06-22 08:46
Here it is:
https://github.com/Wurstnase/gitea/releases/tag/v1.8.3_arm-7

**Comment by junpet** [comment] 2019-06-22 11:31
@Wurstnase Thanks, working on my RPI3B+.

**Comment by lunny** [comment] 2019-06-23 01:31
Maybe we should add an integration test for arm build on every pull request.

**Comment by focmb** [comment] 2019-06-23 16:51
The arm v7 version from Wurstnase doesn't work here on my RPi 3 with nginx as a reverse proxy:
Connection refused) while connecting to upstream

The arm v6 version from the original repo works flawless

**Comment by mrsdizzie** [comment] 2019-06-23 17:06
I think this issue can be closed since we don't build an arm7 specific release anymore (and I think these comments are starting to become confusing/misleading). People should be using the arm6 build as arm is backwards compatible and it works fine on arm7.

Anybody can always build their own if they want, since our issue was that a statically linked build segfaults on arm7 and we only offer statically linked builds -- but most people building their own probably aren't doing that. Also there is no real reason to imo, I don't think anything in our stack is particularly optimized for the few features added by arm7 and go itself doesn't even do a build for arm7 just arm6.

**Comment by zeripath** [comment] 2019-06-23 18:04
I think @mrsdizzie is correct. The advice is to use arm6 unless someone can debug why the arm7 static compiles fail.

Therefore I will close this bug.

**Closed as completed by zeripath** 2019-06-23 18:04 UTC
Labels: topic/build, issue/regression

**Comment by Wurstnase** [comment] 2019-06-24 04:13
> People should be using the arm6 build as arm is backwards compatible and it works fine on arm7.

I only start to try to build the arm7, because I was not able to install/run the arm6 build on my Synology NAS. But I will try it soon (tm) again.

> Anybody can always build their own if they want, since our issue was that a statically linked build segfaults on arm7 and we only offer statically linked builds

I made a ``` TAGS="bindata" make generate release-linux```. Isn't it a statically build? I only replaced the target in the Makefile.

**Comment by zeripath** [comment] 2019-06-24 06:26
@wurstnase that's actually a non static build.

Take at the release target in the makefile, you would need to add a few more tags and LDFLAGS

**Comment by Wurstnase** [comment] 2019-06-24 07:02
@zeripath thx for clarification.

**Comment by bazsodombiandras** [comment] 2019-10-06 13:15
The ARM v6 version of Gitea 1.9.3. is NOT working on ODROID XU4. The Gitea service keeps restarting. If I switch back to the v1.7.5 binary, everything is fine. And why arent't there ARM v7 binaries build anymore? Will this compatibility problem be solved properly or has ARM v7 been given up on completely?

**Comment by coreoas** [comment] 2019-10-10 01:53
I am also getting a "Segmentation Fault" with arm-6 build on an ARMv7 CPU (raspberry Pi 3 with raspbian)

**Comment by kgraefe** [comment] 2019-10-10 06:51
As written before, ARMv7 is abandoned until someone is willing to invest the time to debug the ARMv7 build. Also your issue seems unrelated.

**Comment by atomi** [comment] 2019-10-10 23:57
FWIW, mine builds just fine using 1.13.1 on armv7l (rpi3).

**Comment by lunny** [comment] 2019-10-11 00:20
@kgraefe If you can build armv7 yourself, It should be OK. Only official armv7 binary is abandoned.

**Comment by MichaIng** [comment] 2019-12-09 13:16
Hmm, for some reason the ARMv6 binary now fails with segmentation fault on ARMv7 RPi models: https://github.com/MichaIng/DietPi/issues/3248
I'm currently running some tests which older version still works.
