### ISSUE TITLE
When i create PR with many changes i see freeze gitea, because she return full compare

### ISSUE THREAD

**Issue by visteras** [go-gitea/gitea#16652] opened 2021-08-08 16:59 UTC
- Gitea version (or commit ref): 1.14.5
- Git version: 2.30.2
- Operating system: docker

- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite

Just subj. I can disable full compare for "create PR" ?
P.S.: 453 changed files :123758 add and 7694 remove
P.P.S. Why i can see changes for create PR? I known my changes, changes need for reviewer(after create PR), not for creator...

**Comment by visteras** [comment] 2021-08-17 06:35
Alternatively, we can create exclusion templates for files (* .xml or vendor / *) so that we don't see this when creating a PR.

**Comment by lafriks** [comment] 2021-08-17 07:18
This will be fixed by #16250

**Comment by lunny** [comment] 2024-12-05 23:09
Duplicate of #31600

**Closed as not planned by lunny** 2024-12-05 23:09 UTC
Labels: performance/speed
