### ISSUE TITLE
Segmentation Violation when Creating User

### ISSUE THREAD

**Issue by julmb** [go-gitea/gitea#26899] opened 2023-09-04 15:16 UTC
### Description

I am trying to create a user via the command-line:
```
sudo docker exec --user git gitea_main_1 gitea admin user create --username test
```

I get the following result:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x50ff9a]

goroutine 1 [running]:
fmt.Fprintf({0x0, 0x0}, {0x32882e7, 0x12}, {0xc002726780, 0x1, 0x1})
	/usr/local/go/src/fmt/print.go:225 +0x7a
code.gitea.io/gitea/cmd.RunMainApp(0xc00280e8c0, {0xc0000521e0?, 0x4?, 0xc002726978?})
	/go/src/code.gitea.io/gitea/cmd/main.go:23 +0xc7
main.main()
	/go/src/code.gitea.io/gitea/main.go:153 +0xc2b
```

### Gitea Version

1.20.3

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Debian 5.10.191-1

### How are you running Gitea?

I am using Gitea 1.20.3 from Docker Hub: https://hub.docker.com/layers/gitea/gitea/1.20.3/images/sha256-eda9ebe211772fd2a47c02a7f828eb5c957f5812043a7ff03e4e2780a850554b

### Database

SQLite

**Comment by wxiaoguang** [comment] 2023-09-04 16:08
Duplicate of #26615


It should have been fixed by "Set errwriter for urfave/cli v1 #26616"

You can use the nightly build.

**Closed as completed by wxiaoguang** 2023-09-04 16:08 UTC
Labels: type/bug

**Comment by julmb** [comment] 2023-09-04 20:40
Ah, I looked around for a few minutes but did not see #26615, sorry for the duplicate.

**Comment by wxiaoguang** [comment] 2023-09-05 02:32
Never mind. Indeed it's a bug, sorry for the inconvenience.
