### ISSUE TITLE
ssh:// prefix missing in 1.21.1

### ISSUE THREAD

**Issue by ohschmidty** [go-gitea/gitea#28416] opened 2023-12-11 07:36 UTC
### Description

I recently upgraded from 1.19 to 1.21.1 and discovered that ssh:// prefix is missing from the clone address section in the web UI. I do not see a setting in app.ini where i would be able to specify or add the prefix, only the ability to change the SSH_DOMAIN.

### Screenshots

<img width="741" alt="image" src="https://github.com/go-gitea/gitea/assets/41527702/87ed1a37-83c5-4b81-8606-cec14f220cf0">

### Gitea Version

1.21.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

Firefox 120

**Comment by lunny** [comment] 2023-12-11 08:58
I think it's by design.

**Comment by wxiaoguang** [comment] 2023-12-11 12:31
->  Improve SSH clone URL generation behavior #28421 

As a workaround, you can set `[repository].USE_COMPAT_SSH_URI = true` in your app.ini to use the full SSH clone URL.

**Comment by wxiaoguang** [comment] 2023-12-11 17:01
After more thoughts, I would like to keep the old behavior of the SSH clone URL generation in  #28421

Could you show your app.ini? Then we could know how `git@domain:port:user/repo.git` happened.

**Comment by daveschmidt86** [comment] 2023-12-11 19:53
I am good setting the USE_COMPAT_SSH_URL to true, I just didn't know it was an option. My app.ini is the standard one with just the URL and SSH_DOMAIN  values modified ( and soon to also include the USE_COMPAT_SSH_URL)).

Thank you all for your help and attention, I will close this one.

**Closed as completed** 2023-12-11 19:54 UTC
Labels: issue/needs-feedback
