### ISSUE TITLE
New pull request from last pushed branch 404 error

### ISSUE THREAD

**Issue by stuzer05** [go-gitea/gitea#25830] opened 2023-07-11 13:18 UTC
### Description

We use issue reference as branch name
![image](https://github.com/go-gitea/gitea/assets/23124682/4f8da1bf-40f6-4442-bf39-a261bd7289fa)

and when I pushed my branch, gitea suggested to create new pr, however "#" in the branch name breaks this feature 
![image](https://github.com/go-gitea/gitea/assets/23124682/e3bc020c-1cb8-4801-87fe-dd79de9bcd02)
![image](https://github.com/go-gitea/gitea/assets/23124682/22c40e88-ae61-4815-b70a-757d50535b57)

Also, pushed branches from one repository are shown in another one for some reason

### Gitea Version

trunk

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker

### Database

None

**Comment by puni9869** [comment] 2023-07-11 19:19
This is related to html encoding of `#` in the url. I can replicate it in my local.

**Comment by puni9869** [comment] 2023-07-12 07:14
I need some feedback on above Pr.

**Comment by stuzer05** [comment] 2023-07-12 08:36
> I need some feedback on above Pr.

Works with the branch name, however these messages are shown for the wrong repo 
![image](https://github.com/go-gitea/gitea/assets/23124682/dea6e611-e0f5-473e-a64a-c2d7a4797634)

**Comment by puni9869** [comment] 2023-07-12 08:43
> > I need some feedback on above Pr.
> 
> Works with the branch name, however these messages are shown for the wrong repo ![image](https://user-images.githubusercontent.com/23124682/252908623-dea6e611-e0f5-473e-a64a-c2d7a4797634.png)

I am little bit confused.
Q 1. Do you have `repo1` as a repository in your gitea account.
or
Q 2. Do you have `repo1` as a branchname in the `repo2` repository [the current repository.]

PS: Please share the screenshot of branches list of `repo2` repository.  I think these are two different Issues.
Let reproduce one by one.

**Comment by stuzer05** [comment] 2023-07-12 08:52
I have 2 repos and issue branch in each of them, created from master
![image](https://github.com/go-gitea/gitea/assets/23124682/3bb686e5-562d-4436-9a42-9418fa34a86a)
![image](https://github.com/go-gitea/gitea/assets/23124682/17618e50-e221-468c-b113-d5004ea2cc64)

**Comment by puni9869** [comment] 2023-07-12 09:28
> 
> Works with the branch name, however these messages are shown for the wrong repo ![image](https://user-images.githubusercontent.com/23124682/252908623-dea6e611-e0f5-473e-a64a-c2d7a4797634.png)

Technically branches should be from same repo only.
I have less knowledge on this feature. Is it intentional to show all branches from all repositories.

PS: I have confirmed, github shows only branches which are to be`New Pull Request`  only from that repository only.

**Comment by stuzer05** [comment] 2023-07-12 09:39
> I have less knowledge on this feature. Is it intentional to show all branches from all repositories.

This must be a bug, because in the code of those messages there're 2 sql queries WITH repository check. But it works incorrectly

**Comment by stuzer05** [comment] 2023-07-13 05:47
> Fix: #25812

You didn't include fix for branch names with "#" here

**Comment by puni9869** [comment] 2023-07-13 06:51
Its in WIP, I have raise the concern..

**Comment by stuzer05** [comment] 2023-07-13 11:07
Branch selector also doenst work 
![image](https://github.com/go-gitea/gitea/assets/23124682/4f744e1a-fded-4256-93e8-72a329922b2a)
![image](https://github.com/go-gitea/gitea/assets/23124682/93937b97-c57b-4306-bf73-2e8c574c76c3)

But when you replace "#" with "%23" in url, everything is okay. Branch name should be url encoded in all "a" tags

**Comment by yp05327** [comment] 2023-07-14 00:50
> Branch selector also doenst work ![image](https://user-images.githubusercontent.com/23124682/253255825-4f744e1a-fded-4256-93e8-72a329922b2a.png) ![image](https://user-images.githubusercontent.com/23124682/253255898-93937b97-c57b-4306-bf73-2e8c574c76c3.png)
> 
> But when you replace "#" with "%23" in url, everything is okay. Branch name should be url encoded in all "a" tags

Will be fixed in #25875

**Comment by lunny** [comment] 2023-07-27 03:14
Close per #25875 merged.

**Comment by stuzer05** [comment] 2023-08-10 16:55
@lunny please, reopen. Error is still not fixed on latest dev build.

I have a branch named `test/test#123`
![image](https://github.com/go-gitea/gitea/assets/23124682/fc4aa04e-5340-4dc1-8969-dfc44220d3a2)

1. Branch name insede the message is still escaped, but shouldn't
2. In "New Pull Request" button "#" is escaped as "%2523", which is incorrenct. Correct escaping is "%23" as in branch name inside the message (showed by an arrow)

I tested if button would lead to url with correct `%23` escaping everything would work

**Comment by puni9869** [comment] 2023-08-26 13:03
This is due to double encoding. Its a known issue. 
cc @yp05327

**Comment by wxiaoguang** [comment] 2023-08-26 13:39
The newly reported bug is not related to #25875

-> Fix template bugs in recently_pushed_new_branches.tmpl #26744

**Closed as completed** 2023-08-27 00:16 UTC
Labels: type/bug, issue/needs-feedback
