### ISSUE TITLE
gitea-1.13.2-linux-mipsle: Illegal instruction

### ISSUE THREAD

**Issue by zhaojh329** [go-gitea/gitea#14857] opened 2021-03-03 01:37 UTC
Downloaed from https://github.com/go-gitea/gitea/releases/download/v1.13.2/gitea-1.13.2-linux-mipsle

**Comment by techknowlogick** [comment] 2021-03-03 02:50
closing as dupe of https://github.com/go-gitea/gitea/issues/14857

**Closed as completed by techknowlogick** 2021-03-03 02:50 UTC
Labels: issue/duplicate

**Comment by delvh** [comment] 2021-03-03 07:49
Wait a second…
Did you just close #14857 with the reason being that it is a duplicate of #14857?

**Comment by jolheiser** [comment] 2021-03-03 14:57
He may have meant #14034, as he commented on it shortly after this one. 🙂
