### ISSUE TITLE
Gitea breaks on Mariadb 10.1.35

### ISSUE THREAD

**Issue by CountMurphy** [go-gitea/gitea#4704] opened 2018-08-14 16:32 UTC
- Gitea version (or commit ref): 15.0
- Git version:2.18.0
- Operating system: Arch Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

Error 1071: Specified key was too long; max key length is 767 bytes

## Description
Looks like this Gogs bug (https://github.com/gogs/gogs/issues/4894) migrated over. gitea now expects mariadb 10.2 for this upgrade. Arch still runs 10.1.35. Gitea will crash trying to upgrade the database.
...

**Comment by SagePtr** [comment] 2018-08-14 17:01
Just another duplicate of #2979

**Comment by CountMurphy** [comment] 2018-08-14 17:09
didn't see that one. thanks

**Closed as completed** 2018-08-14 17:09 UTC
Labels: issue/duplicate
