### ISSUE TITLE
[Feature] Project tasks

### ISSUE THREAD

**Issue by belliash** [go-gitea/gitea#11982] opened 2020-06-19 16:26 UTC
Could it be possible to add 'Tasks' subpage per repository (something like Jira or GitHub Projects), so that every project could have its own board with a list of tasks? I think there should be several columns, best configurable per project.

**Comment by jolheiser** [comment] 2020-06-19 17:00
Duplicate of https://github.com/go-gitea/gitea/issues/3476

Will be implemented in https://github.com/go-gitea/gitea/pull/8346

**Closed as completed by jolheiser** 2020-06-19 17:00 UTC
Labels: issue/duplicate
