### ISSUE TITLE
Duplicated issue will be created if issue creation button clicked multiple times

### ISSUE THREAD

**Issue by NateScarlet** [go-gitea/gitea#6859] opened 2019-05-06 08:03 UTC
- Git version: 1.9.0+dev-207-gdab38c375 
- Operating system: Windows7 / Chrome 74
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL): https://try.gitea.io/NateScarlet/test/issues
  - [ ] No
  - [ ] Not relevant

## Description

Current version has no loading indicator and submit button is not disabled after first submit,
therefore user may accidently send multiple isssue creation request for same issue

## Screenshots

![image](https://user-images.githubusercontent.com/21083014/57212951-e6c8f880-7017-11e9-8c1e-9a2f9f368dc4.png)

**Comment by wxiaoguang** [comment] 2021-12-08 07:37
Duplicate of

* https://github.com/go-gitea/gitea/issues/17111 (with more details)

**Closed as completed by wxiaoguang** 2021-12-08 07:37 UTC
Labels: topic/ui, issue/confirmed
