### ISSUE TITLE
[1.21.0] New SQL warnings

### ISSUE THREAD

**Issue by tuxmaster5000** [go-gitea/gitea#28064] opened 2023-11-15 05:30 UTC
### Description

On startup new SQL warnings are shown after migration:
```
Nov 15 06:25:25 gitea[302897]: 2023/11/15 06:25:25 cmd/web.go:194:serveInstalled() [W] Table oauth2_application Column confidential_client db default is true, struct default is TRUE
Nov 15 06:25:25 gitea[302897]: 2023/11/15 06:25:25 cmd/web.go:194:serveInstalled() [W] Table system_setting Column version db default is , struct default is 1
Nov 15 06:25:25 gitea[302897]: 2023/11/15 06:25:25 cmd/web.go:194:serveInstalled() [W] Table user Column max_repo_creation db default is '-1', struct default is -1
Nov 15 06:25:27 gitea[302897]: 2023/11/15 06:25:27 cmd/web.go:194:serveInstalled() [W] Table label Column archived_unix db default is , struct default is NULL
```

### Gitea Version

1.21.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Updated from github.

### Database

PostgreSQL

**Comment by successgo** [comment] 2023-11-15 10:08
Your gitea version might be 1.21 other than 1.121.0

**Comment by tuxmaster5000** [comment] 2023-11-15 10:15
@successgo Yes, the header was correct. Only an typo in the body.

**Comment by somera** [comment] 2023-11-15 11:36
I see this
```
2023/11/14 17:23:13 cmd/web.go:194:serveInstalled() [W] Table oauth2_application Column confidential_client db default is true, struct default is TRUE
2023/11/14 17:23:13 cmd/web.go:194:serveInstalled() [W] Table session has column created_unix but struct has not related field
2023/11/14 17:23:14 cmd/web.go:194:serveInstalled() [W] Table system_setting Column version db default is , struct default is 1
2023/11/14 17:23:14 cmd/web.go:194:serveInstalled() [W] Table email_address Column lower_email db nullable is true, struct nullable is false
2023/11/14 17:23:14 cmd/web.go:194:serveInstalled() [W] Table user Column max_repo_creation db default is '-1', struct default is -1
2023/11/14 17:23:16 cmd/web.go:194:serveInstalled() [W] Table project column board_type db type is INTEGER, struct type is BIGINT
2023/11/14 17:23:16 cmd/web.go:194:serveInstalled() [W] Table project column card_type db type is INTEGER, struct type is BIGINT
2023/11/14 17:23:16 cmd/web.go:194:serveInstalled() [W] Table project Column card_type db default is 0, struct default is
2023/11/14 17:23:16 cmd/web.go:194:serveInstalled() [W] Table project Column card_type db nullable is false, struct nullable is true
2023/11/14 17:23:16 cmd/web.go:194:serveInstalled() [W] Table project column type db type is INTEGER, struct type is BIGINT
2023/11/14 17:23:16 cmd/web.go:194:serveInstalled() [W] Table label Column archived_unix db default is , struct default is NULL
2023/11/14 17:23:16 cmd/web.go:194:serveInstalled() [W] Table hook_task has column repo_id but struct has not related field
```
in 1.21.0 with PostgreSQL.

**Comment by 0x6d61726b** [comment] 2024-01-06 11:42
Duplicate of #22275?

**Closed as completed** 2024-01-07 03:05 UTC
Labels: type/bug, issue/duplicate
