### ISSUE TITLE
Error 500 when loading empty repository

### ISSUE THREAD

**Issue by grisu48** [go-gitea/gitea#18460] opened 2022-01-30 11:14 UTC
### Gitea Version

1.16.0+rc1

### Git Version

2.30.2

### Operating System

openSUSE Leap 15.3

### How are you running Gitea?

I'm running `gitea:latest` as a podman container

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/grisu48/fe729f43fea4735235ea772733ee5d53

### Description

When creating a new empty repository, gitea results in a 500 error and I see the following in the log

    2022/01/30 11:07:32 Started GET /phoenix/labenvmon for 10.88.0.1:54964
    2022/01/30 11:07:32 ...ers/web/repo/view.go:860:renderCode() [E] GitRepo.IsEmpty: check empty: exit status 128 - fatal: your current branch 'main' does not have any commits yet
	
    2022/01/30 11:07:32 Completed GET /phoenix/labenvmon 500 Internal Server Error in 62.831049ms

### Screenshots

![Screenshot 2022-01-30 at 12-13-41 labenvmon](https://user-images.githubusercontent.com/1527829/151697233-d74af498-0db5-4ab9-97d7-e5e546d63cc6.png)

**Comment by Gusted** [comment] 2022-01-30 11:32
Sounds like a duplicate of #18413

**Comment by zeripath** [comment] 2022-01-30 11:58
Yup already fixed and will be in rc2

**Closed as completed** 2022-01-30 11:58 UTC
Labels: issue/duplicate

**Comment by grisu48** [comment] 2022-01-31 07:36
Perfect, thank you for fixing this :+1:
