### ISSUE TITLE
Gitea Act Runner ubuntu image is missing ANDROID SDK for GitHub workflows

### ISSUE THREAD

**Issue by TristanWasTaken** [go-gitea/gitea#29635] opened 2024-03-06 17:32 UTC
### Description

I've been busy/lazy since my last issue (#28847). I discovered the issue on 2024-01-16 (yyyy-mm-dd).

when mirroring the gh repo https://github.com/mihonapp/mihon and enabling actions that run on every new commit, the job fails on gitea even though it succeeds on github
error: `SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable'.`

tldr; turns out [github's ubuntu image has the Android SDK preinstalled](https://github.com/nektos/act/issues/1172#issuecomment-1699598124), while Gitea's image doesn't have it
gitea would (probably) need `uses: android-actions/setup-android@v2` to be added in the workflow config files for it to work without it preinstalled.

relevant section in workflow files:
- [mihon/.github/workflows/build_push.yml#L27](https://github.com/mihonapp/mihon/blob/0d449a9b1d4fbfd81c7d2bfb849c68d6656f6939/.github/workflows/build_push.yml#L27)
- [mihon-previews/.github/workflows/build_app.yml#L43](https://github.com/mihonapp/mihon-preview/blob/0b2aa8b83163826baa8efa154fa45aeca9760116/.github/workflows/build_app.yml#L43)

If I should try to repro it on the demo site, please tell me.

### Gitea Version

1.21.3

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Docker

### How are you running Gitea?

gitea: docker `gitea/gitea:1.21.3`
runner: docker `gitea/act_runner:nightly` (2024-01-16/yyyy-mm-dd)

### Database

None

**Comment by lunny** [comment] 2024-03-07 10:44
I think this is by design that the default images of Gitea Actions will be very smaller than Github's

**Comment by TristanWasTaken** [comment] 2024-03-07 14:43
> I think this is by design that the default images of Gitea Actions will be very smaller than Github's

@lunny if the goal of Gitea's action images is to be smaller, then it should be documented on the [comparison page](https://docs.gitea.com/usage/actions/comparison) and changed on other pages like [Design of Gitea Actions](https://docs.gitea.com/usage/actions/design) which states "You can mirror actions repositories from GitHub to your Gitea instance, **and use them as normal**."
It does, in fact, not work as normal.

**Comment by lunny** [comment] 2024-06-15 14:05
Now we have official runner images https://gitea.com/gitea/runner-images and an example for android https://gitea.com/action-examples/Android . I think we can close this now.

**Closed as completed by lunny** 2024-06-15 14:05 UTC
Labels: type/docs, topic/gitea-actions
