### ISSUE TITLE
After upgrading to 1.13.0, can no longer login

### ISSUE THREAD

**Issue by sseneca** [go-gitea/gitea#13832] opened 2020-12-03 22:14 UTC
- Gitea version (or commit ref): 1.13.0
- Git version: 2.29.2
- Operating system: Parabola GNU/Linux
- I'm using Gitea via the [Helm chart](https://gitea.com/gitea/helm-chart), on my server running [k3s](https://k3s.io). [This is the deploy file](https://git.ssene.ca/sseneca/k8s-server/src/branch/master/gitea/release.yaml).
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No (n/a)
- Log gist:
```
[Macaron] 2020-12-03 22:12:20: Started POST /user/login for 10.42.0.1
2020/12/03 22:12:20 ...m.io/xorm/core/db.go:286:afterProcess() [I] [SQL] SELECT "id", "type", "name", "is_actived", "is_sync_enabled", "cfg", "created_unix", "updated_unix" FROM "login_source" WHERE (is_actived = $1 and type = $2) [true 6] - 795.229µs
2020/12/03 22:12:20 ...m.io/xorm/core/db.go:286:afterProcess() [I] [SQL] SELECT "id", "type", "name", "is_actived", "is_sync_enabled", "cfg", "created_unix", "updated_unix" FROM "login_source" WHERE (is_actived = $1 and type = $2) [true 7] - 579.519µs
2020/12/03 22:12:20 ...m.io/xorm/core/db.go:286:afterProcess() [I] [SQL] SELECT "id", "lower_name", "name", "full_name", "email", "keep_email_private", "email_notifications_preference", "passwd", "passwd_hash_algo", "must_change_password", "login_type", "login_source", "login_name", "type", "location", "website", "rands", "salt", "language", "description", "created_unix", "updated_unix", "last_login_unix", "last_repo_visibility", "max_repo_creation", "is_active", "is_admin", "is_restricted", "allow_git_hook", "allow_import_local", "allow_create_organization", "prohibit_login", "avatar", "avatar_email", "use_custom_avatar", "num_followers", "num_following", "num_stars", "num_repos", "num_teams", "num_members", "visibility", "repo_admin_change_team_access", "diff_view_style", "theme", "keep_activity_private" FROM "user" WHERE "lower_name"=$1 LIMIT 1 [sseneca] - 860.604µs
[Macaron] 2020-12-03 22:12:20: Completed POST /user/login 200 OK in 29.759793ms
2020/12/03 22:12:20 routers/user/auth.go:177:SignInPost() [I] Failed authentication attempt for sseneca from 10.42.0.1
```

## Description

After updating to v1.13.0, I can no longer login to to my account on my two-account Gitea instance. The account is the only admin account and also has 2FA enabled. The other account logs in fine, is not an admin, and does not have 2FA enabled.

Whilst it didn't appear in the above logs, other times when I've tried I've also seen this line:

```
Unable to negotiate with 10.42.0.1 port 62090: no matching key exchange method found. Their offer: diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1 [preauth]
```

Not sure if it's relevant though because like I said it didn't appear when I tried in the above logs.

Also note that I've read [this](https://discourse.gitea.io/t/2516) thread but after checking the account in the database `is_active` is `t`. Forum post [here](https://discourse.gitea.io/t//2719).

**Comment by birkb** [comment] 2020-12-05 10:12
Same for me. It only affects the local admin user. The LDAP users are working fine.

**Comment by kisaragi-hiu** [comment] 2020-12-07 10:40
Does it help if you upgrade the Gitea Helm Chart to the latest version, 2.1.0? (at https://git.ssene.ca/sseneca/k8s-server/src/branch/master/gitea/release.yaml#L23)

I don't actually know Kubernetes, but I can see that there seems to be a version mismatch.

**Comment by sseneca** [comment] 2020-12-07 11:31
Just tried it but unfortunately version 2.0.7+ of the Chart [is broken on Kubernetes 1.18](https://gitea.com/gitea/helm-chart/issues/77), which I'm stuck on for now. I'll follow that issue and once it's resolved try to upgrade the Chart version again.

**Comment by birkb** [comment] 2020-12-07 11:56
I use `https://dl.gitea.io/gitea/1.13.0/gitea-1.13.0-linux-amd64` in my custom Dockerfile with Postgres `12.5` running in another container. Before the upgrade the login with the local admin user was working fine.

**Comment by antoine2tt** [comment] 2020-12-07 18:48
Same here for me
I'm using docker, last version of Gitea, and i'm running it with SQLite.

**Comment by onedr0p** [comment] 2020-12-07 18:58
I am having the same issue! I just upgraded to 2.1.0 of the helm chart. Wish I saw this issue beforehand :(

**Comment by luhahn** [comment] 2020-12-07 20:37
Hi there i will have a look at this issue tomorrow

**Comment by onedr0p** [comment] 2020-12-07 20:38
Thanks @luhahn you know where to reach me on Discord :D if you need any info. It looks like it might be more of an issue with Gitea 1.13.0 than the chart. But I dunno.

**Comment by luhahn** [comment] 2020-12-07 20:40
yeah, i dont know, the init container looks fine. But i can't spend any time today for looking at the chart

**Comment by techknowlogick** [comment] 2020-12-08 04:16
This appears related specifically to the helm chart, could you open an issue in the helm chart https://gitea.com/gitea/helm-chart so we can track it there?

**Comment by birkb** [comment] 2020-12-08 06:48
@techknowlogick The problem [also affects](https://github.com/go-gitea/gitea/issues/13832#issuecomment-739872134) the downloaded gitea binary. Should we track that in a separate case?

**Comment by luhahn** [comment] 2020-12-08 08:31
Hi all, please see https://gitea.com/gitea/helm-chart/issues/79 for more information on this issue.

**Comment by sseneca** [comment] 2020-12-08 08:35
I'm confused. Both @birkb and @antoine2tt are facing this same bug, and neither use the Helm chart. Why is this bug being tracked there?

**Comment by luhahn** [comment] 2020-12-08 08:38
Well I'm sure I need to adjust some stuff on the init container for the helm chart. So I also created an issue there.
At least the admin creation changed.

However since this also affects the downloaded binary we should not close this issue here. If I find something useful I will also post it here.

**Comment by luhahn** [comment] 2020-12-08 09:12
Well, I deleted the admin user via the gitea cli inside my container and created it again. Which seems to work even after reinstalling the Chart.
However it is now required to set the following even for admin accounts, if you don't want to change the password after creation:
```
--must-change-password=false
```

**Comment by sseneca** [comment] 2020-12-08 09:42
For both the users on my instance, `must_change_password` is already false:

```
gitea=> SELECT "must_change_password" FROM "user";
 must_change_password
----------------------
 f
 f
(2 rows)
```

even though one can login and the other can't.

**Comment by luhahn** [comment] 2020-12-08 09:45
Yes I know, that's now for newly created admins.

I did not find a way to recover the faulty admins. But I have a workaround, posted in the helm chart issue.

**Comment by birkb** [comment] 2020-12-08 10:13
I update the admin password from within the `entrypoint.sh` and it does not fix the problem.
```bash
${GITEA_BIN} ${GITEA_OPTS} admin change-password --username ${GITEA_ADMIN_USERNAME} --password ${GITEA_ADMIN_PASS} 
```
I will try the delete/create workaround.

**Comment by zeripath** [comment] 2020-12-08 10:37
First of all so I've taken so long to look at or notice this - but let's go through this systematically.

@sseneca 
> After updating to v1.13.0, I can no longer login to to my account on my two-account Gitea instance. The account is the only admin account and also has 2FA enabled. The other account logs in fine, is not an admin, and does not have 2FA enabled.

 I think the 2FA here is most likely the biggest hint as to what the issue is - and it would be good to know if you even get asked to provide a 2FA or if that doesn't occur. From your provided logs it looks like that doesn't happen - but it's helpful to know for definite.

@luhahn 
> I did not find a way to recover the faulty admins. But I have a workaround, posted in the [helm chart issue](https://gitea.com/gitea/helm-chart/issues/79).

It would be helpful to check what the difference is for these users in the user table as it might easily be something wrong with a default value.

In the next reply I'll walk through the provided log.

**Comment by sseneca** [comment] 2020-12-08 11:19
Yep, I don't get asked to provide the 2FA code. I get `Username or password is incorrect.` once I press `Sign In`.

**Comment by zeripath** [comment] 2020-12-08 11:20
OK, let's go through and find the ultimate place that calls and causes this log and think about what we can do to get some more information - or understanding.

```
[Macaron] 2020-12-03 22:12:20: Started POST /user/login for 10.42.0.1
```

Comes from:

https://github.com/go-gitea/gitea/blob/e39ed0b1d98b312c9986969f77acad404748e004/routers/routes/routes.go#L106

and matches:

https://github.com/go-gitea/gitea/blob/e39ed0b1d98b312c9986969f77acad404748e004/routers/routes/routes.go#L366

https://github.com/go-gitea/gitea/blob/e39ed0b1d98b312c9986969f77acad404748e004/routers/user/auth.go#L151-L232

Now let's check the SQL

```
2020/12/03 22:12:20 ...m.io/xorm/core/db.go:286:afterProcess() [I] [SQL] SELECT "id", "type", "name", "is_actived", "is_sync_enabled", "cfg", "created_unix", "updated_unix" FROM "login_source" WHERE (is_actived = $1 and type = $2) [true 6] - 795.229µs
2020/12/03 22:12:20 ...m.io/xorm/core/db.go:286:afterProcess() [I] [SQL] SELECT "id", "type", "name", "is_actived", "is_sync_enabled", "cfg", "created_unix", "updated_unix" FROM "login_source" WHERE (is_actived = $1 and type = $2) [true 7] - 579.519µs
```

are caused by:

https://github.com/go-gitea/gitea/blob/e39ed0b1d98b312c9986969f77acad404748e004/routers/user/auth.go#L155

So we get in to the meat of this function. Which is performed in:

https://github.com/go-gitea/gitea/blob/e39ed0b1d98b312c9986969f77acad404748e004/routers/user/auth.go#L173

https://github.com/go-gitea/gitea/blob/e39ed0b1d98b312c9986969f77acad404748e004/models/login_source.go#L734-L819

The next SQL emitted :

```
2020/12/03 22:12:20 ...m.io/xorm/core/db.go:286:afterProcess() [I] [SQL] SELECT "id", "lower_name", "name", "full_name", "email", "keep_email_private", "email_notifications_preference", "passwd", "passwd_hash_algo", "must_change_password", "login_type", "login_source", "login_name", "type", "location", "website", "rands", "salt", "language", "description", "created_unix", "updated_unix", "last_login_unix", "last_repo_visibility", "max_repo_creation", "is_active", "is_admin", "is_restricted", "allow_git_hook", "allow_import_local", "allow_create_organization", "prohibit_login", "avatar", "avatar_email", "use_custom_avatar", "num_followers", "num_following", "num_stars", "num_repos", "num_teams", "num_members", "visibility", "repo_admin_change_team_access", "diff_view_style", "theme", "keep_activity_private" FROM "user" WHERE "lower_name"=$1 LIMIT 1 [sseneca] - 860.604µs
```

is caused by:

https://github.com/go-gitea/gitea/blob/e39ed0b1d98b312c9986969f77acad404748e004/models/login_source.go#L758

**So what is the result of this query?** (You may need to change it slightly to match postgreSQL variant.) 

Then we get no logs but:

```
[Macaron] 2020-12-03 22:12:20: Completed POST /user/login 200 OK in 29.759793ms
2020/12/03 22:12:20 routers/user/auth.go:177:SignInPost() [I] Failed authentication attempt for sseneca from 10.42.0.1
```

The first of which is:

https://github.com/go-gitea/gitea/blob/e39ed0b1d98b312c9986969f77acad404748e004/routers/routes/routes.go#L112

and the counterpart of the first log. But the second bit comes from:

https://github.com/go-gitea/gitea/blob/e39ed0b1d98b312c9986969f77acad404748e004/routers/user/auth.go#L177'

Now that implies that we have received a `models.ErrUserNotExist{}`

### How do we get a `models.ErrUserNotExist`?

First of all. Let's assume that 

https://github.com/go-gitea/gitea/blob/e39ed0b1d98b312c9986969f77acad404748e004/models/login_source.go#L758

returned `hasUser := true` - You can check this and should have checked the result of the query that this is associated with already. **What is the result of that query?**

To obtain a `models.ErrUserNotExist` if `hasUser == true` we have two options:

https://github.com/go-gitea/gitea/blob/e39ed0b1d98b312c9986969f77acad404748e004/models/login_source.go#L764-L765

(this is the most likely path)

https://github.com/go-gitea/gitea/blob/e39ed0b1d98b312c9986969f77acad404748e004/models/login_source.go#L766

The most likely problem is that this fails and interestingly if we look at the line below it we get a hint as to what might really be the problem:

https://github.com/go-gitea/gitea/blob/e39ed0b1d98b312c9986969f77acad404748e004/models/login_source.go#L769

I recall on 1.13 we changed the default hashing algorithm to argon2. Is it possible that hashing algorithm is detected incorrectly for postgres? The presumption was that the default would have been stored in the database at the time of insertion and was previously `pbkdf2`.

I'm gonna stop here because I bet that that is the issue.

**Comment by sseneca** [comment] 2020-12-08 11:26
> I recall on 1.13 we changed the default hashing algorithm to `argon2`. Is it possible that hashing algorithm is detected incorrectly for postgres? The presumption was that the default would have been stored in the database at the time of insertion and was previously `pbkdf2`.

```
gitea=> SELECT "lower_name", "passwd_hash_algo" FROM "user";
 lower_name | passwd_hash_algo 
------------+------------------
 jonnobrow  | argon2
 sseneca    | pbkdf2
(2 rows)
```

`sseneca` is the user that cannot login, `jonnobrow` is the user that can. So that makes sense.

**Comment by zeripath** [comment] 2020-12-08 11:32
err...:

https://github.com/go-gitea/gitea/blob/e39ed0b1d98b312c9986969f77acad404748e004/models/user.go#L412-L416

**Comment by zeripath** [comment] 2020-12-08 11:48
OK the other routes should definitely cause more SQL to be emitted so those are ruled out. The issue is definitely at:

https://github.com/go-gitea/gitea/blob/e39ed0b1d98b312c9986969f77acad404748e004/models/login_source.go#L766

**Comment by zeripath** [comment] 2020-12-08 11:56
https://github.com/go-gitea/gitea/blob/e39ed0b1d98b312c9986969f77acad404748e004/models/user.go#L431-L434

just tests that the user's password is not empty - and although there are a few changes here I think it should make no difference.

https://github.com/go-gitea/gitea/blob/e39ed0b1d98b312c9986969f77acad404748e004/models/user.go#L418-L429

calls hashPassword to check the user's passwd:

https://github.com/go-gitea/gitea/blob/e39ed0b1d98b312c9986969f77acad404748e004/models/user.go#L392-L410

So the question is is `u.PasswdHashAlgo` being set correctly? I worry that it's being defaulted to argon2 all the time but I don't understand how or why that could happen. The other possibility is that the algo is incorrectly stored and the stored hash has been updated to argon2. One other possibility is that the salt has got renewed but I don't understand how that could happen.

I guess the only answer here is to add more debugging statements in to a locally built copy of gitea. I don't see how helm could be responsible for this - but neither do I understand how this could have become so broken.

**Comment by 6543** [comment] 2020-12-08 12:00
I'll reopen since it looks not solved to me

**Comment by antoine2tt** [comment] 2020-12-08 12:22
@zeripath i don't know if it can helps you, but i have the same issue (only 1 user, local admin, can not login after 1.13 upgrade, error 500), and i'm not running Gitea with Helm (i don't even know what Helm is) i'm just running Gitea with Docker (database = SQLite) 

i've been back to 1.12.4 and it's working again. 

If you need anything, i'll be glad to help you.

**Comment by sseneca** [comment] 2020-12-08 12:25
>  The other possibility is that the algo is incorrectly stored and the stored hash has been updated to argon2. One other possibility is that the salt has got renewed but I don't understand how that could happen.

Yeah, both of these accounts were created before I upgraded Gitea to `1.13`: I created `sseneca` on 2020-10-20, when I was [running Gitea 1.12.5](https://git.ssene.ca/sseneca/k8s-server/src/commit/83fec7504fda06a6d3fa8bfbb9867f38088fdf63/gitea/release.yaml#L30), and `jonnobrow` was created about a month later on 2020-11-13, when I was [running the same version](https://git.ssene.ca/sseneca/k8s-server/src/commit/614db48e1d2d7cf5fea2ff24772dac498606a46b/gitea/release.yaml#L30). So I doubt they were different before I upgraded Gitea to 1.13; it makes sense that something went wrong with the accounts in the upgrade to `1.13`.

Like others have said I really doubt this is anything to do with Helm.

**Comment by zeripath** [comment] 2020-12-08 12:58
I think we need one of you to build a gitea with a some added logging to the ValidatePassword function.

**Comment by zeripath** [comment] 2020-12-08 20:08
So I can't replicate this on my testing system. I wonder is this possibly a schema issue?

from 1.13 we're a lot more strict with the schema - is it possible that the user table is in a different schema?

**Comment by sseneca** [comment] 2020-12-11 10:33
I don't have time to debug things but the workaround posted by @luhahn worked for me. Now I can login again after changing my password with the other admin account. I checked the DB and the password hash algorithm has also been updated:

```
gitea=> SELECT "lower_name", "passwd_hash_algo" FROM "user";
 lower_name | passwd_hash_algo 
------------+------------------
 jonnobrow  | argon2
 sseneca    | argon2
(2 rows)
```

**Comment by zeripath** [comment] 2020-12-11 16:07
@sseneca did the passwd and/or salt change? Is it possible that the stored passwd hash is in the incorrect hash_algo?

**Comment by fblaese** [comment] 2020-12-12 11:42
I have a similar issue. Users that tried to reset their password using account recovery were unable to login using the new password. Setting the password from command line had the same effect.

Only when setting the password using the web interface, they could finally log in again. I checked the user table in the database and noticed, that passwd_hash_also was only updated when the password was set using the webui, so I have the feeling that the password is hashed using the new algorithm but the passwd_hash_algo is not updated in some cases.

I don't have the time to verify this, but might the issue be, that passwd_hash_algo is not updated in this function, which seems to be called to update the password on account recovery?
https://github.com/go-gitea/gitea/blob/f8e9a3df40e34945acb5c82ee9e4342b9d8f4aaf/models/user.go#L400-L403

**Comment by fblaese** [comment] 2020-12-12 12:04
Could the issue be, that passwd_hash_algo is not updated here when the password is changed?
https://github.com/go-gitea/gitea/blob/f8e9a3df40e34945acb5c82ee9e4342b9d8f4aaf/routers/user/setting/account.go#L71

**Comment by zeripath** [comment] 2020-12-12 18:24
> Could the issue be, that passwd_hash_algo is not updated here when the password is changed?
> https://github.com/go-gitea/gitea/blob/f8e9a3df40e34945acb5c82ee9e4342b9d8f4aaf/routers/user/setting/account.go#L71

That could very well be it.

**Closed as completed** 2020-12-12 18:59 UTC
