### ISSUE TITLE
REGISTER_MANUAL_CONFIRM  does't work

### ISSUE THREAD

**Issue by soxft** [go-gitea/gitea#18089] opened 2021-12-24 11:20 UTC
### Gitea Version

1.15.8 built with GNU Make 4.1, go1.16.12 : bindata, sqlite, sqlite_unlock_notify

### Git Version

2.25.1

### Operating System

Ubuntu 20.04

### How are you running Gitea?

From binary
Prod

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

REGISTER_MANUAL_CONFIRM  Does't Work

```conf
[service]
REGISTER_EMAIL_CONFIRM            = false
REGISTER_MANUAL_CONFIRM           = true
... MORE ...
```

**Comment by noerw** [comment] 2021-12-24 13:06
duplicate of #17263

**Closed as completed by noerw** 2021-12-24 13:06 UTC
