### ISSUE TITLE
bug: previous attachments cannot be loaded when editing the release

### ISSUE THREAD

**Issue by wohenbushuang** [go-gitea/gitea#14310] opened 2021-01-12 08:53 UTC
- Gitea version (or commit ref): 1.13.1
- Git version:
- Operating system: docker
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

When trying to edit the release, the attachements cannot be shown(the upload region is blank), so cannot be deleted. 
I have tried to save the modification, the attachements still remain, so only edit text description is okay just now.

**Comment by noerw** [comment] 2021-01-17 20:33
duplicate of #677

**Closed as completed by noerw** 2021-01-17 20:33 UTC
Labels: issue/duplicate
