### ISSUE TITLE
Creating Wiki Page Results in Error

### ISSUE THREAD

**Issue by russoj88** [go-gitea/gitea#11393] opened 2020-05-12 20:26 UTC
- Gitea version (or commit ref): 1.11.5
- Git version: 2.26.2
- Operating system: Arch Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
1. Create a new repo.
2. Go to the Wiki tab.
3. Click "Create the First Page"
4. Click "Save Page"
See error: 
`template: repo/wiki/view:48:14: executing "repo/wiki/view" at <(not $.DisableHTTP) (and (not $.DisableSSH) (or $.IsSigned $.ExposeAnonSSH))>: can't give argument to non-function not $.DisableHTTP`

**Comment by jolheiser** [comment] 2020-05-12 20:57
Duplicate of https://github.com/go-gitea/gitea/issues/10552

The problem comes from building Gitea 1.11.x (or presumably earlier versions as well) using Go 1.14 rather than 1.13 (or below)

This issue is fixed and will be included in Gitea 1.12+

**Closed as completed by jolheiser** 2020-05-12 20:57 UTC
Labels: issue/duplicate
