### ISSUE TITLE
Users become "Ghost" when restoring from dump

### ISSUE THREAD

**Issue by DuckDuckWhale** [go-gitea/gitea#14069] opened 2020-12-20 05:49 UTC
- Gitea version (or commit ref): 1.13.0
- Git version: 2.25.1
- Operating system: Ubuntu Server 20.04 LTS
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] N/A
- Log gist: N/A

## Description

Found this when testing a periodic backup. Seems that the culprit is that the last column (`keep_activity_private`) becomes `NULL` for some users in this `NOT NULL` column after upgrading to Gitea 1.13.0 from 1.12.5, which causes the exported `.sql` file to be rejected by postgresql and Gitea to display "Ghost" for those users.

**Comment by DuckDuckWhale** [comment] 2020-12-21 06:57
Migrations seems to be there in #11353... Did it not work?

**Comment by zeripath** [comment] 2020-12-21 19:13
Sorry did you restore the dump from 1.12.5 directly into 1.13? I think the issue is that dumps from 1.12.x never stored the version table. This should now be fixed on 1.13

**Comment by DuckDuckWhale** [comment] 2020-12-21 19:37
No. I dumped and restored after upgrading to 1.13.0 from 1.12.5.

**Comment by lafriks** [comment] 2020-12-22 07:28
As not all users was imported that's why Ghost is displayed. Does original table has those values null?

**Comment by DuckDuckWhale** [comment] 2020-12-22 10:02
Yeah. Not sure why that's the case since the migration should have taken care of it. Thought it might be a bug so reported it here.

**Comment by commel** [comment] 2021-01-11 19:50
I hit that bug as well. Migrated from 1.13.1 from MariaDB 10.0.38 with "gitea dump -c postgres" to insert into PostgreSQL 11.

`FEHLER:  NULL-Wert in Spalte »keep_activity_private« verletzt Not-Null-Constraint`

**Comment by vosdev** [comment] 2021-01-18 09:40
All my users are also broken after a restore. All user entries fail importing into postgres with the following error:

```
ERROR:  null value in column "keep_activity_private" violates not-null constraint
DETAIL:  Failing row contains (7, galaxy, galaxy, , , f, , , , f, 0, 0, , 1, , , lSMiE8D7ei, ulnAng3IHw, , , 1601903326, 1601904018, 0, f, -1, t, f, f, f, f, f, f, 1a18fd989ddbc0dbb8d2ddfdf6fa075e, , t, 0, 0, 0, 8, 1, 1, 0, t, , gitea, null).
```

Dumping and restoring from and to a Gitea 1.13.1 docker image with postgres 11.6

**Comment by 6543** [comment] 2021-01-18 17:31
I found a migration issue ...

**Comment by 6543** [comment] 2021-01-18 17:43
@DuckDuckWhale thanks for reporting, @vosdev did manually altering the user table schema fix it?

**Comment by commel** [comment] 2021-01-19 09:16
> @DuckDuckWhale thanks for reporting, @vosdev did manually altering the user table schema fix it?

It did for me. Also if the number of users if small, manually adjusting the SQL works as well. But great to see the fix incoming! :-)

**Comment by vosdev** [comment] 2021-01-20 09:00
> @DuckDuckWhale thanks for reporting, @vosdev did manually altering the user table schema fix it?

I did not try but it seems @commel has been succesful.

 I automate a daily restore of the latest backup zipfile to test if it actually works because I do not want to be surprised with errors when I actually need to restore from backup :-)

**Closed as completed** 2021-01-28 22:58 UTC
Labels: type/bug
