### ISSUE TITLE
After merging pull request incorrect commit count  displayed

### ISSUE THREAD

**Issue by m0xf** [go-gitea/gitea#3088] opened 2017-12-04 14:49 UTC
- Gitea version (or commit ref): 1.3.0
- Git version: 2.1
- Operating system: Windows 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes ( https://try.gitea.io/m0xf/commit-count/commits/branch/master )
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

After merging pull request incorrect commit count displayed. 

## Screenshots

![gitea_c](https://user-images.githubusercontent.com/1099490/33558463-f01fe9ce-d91a-11e7-89f4-820db85fa5e9.png)

**Comment by lunny** [comment] 2017-12-04 15:23
I confirmed this issue is only for master not in v1.3

**Comment by ethantkoenig** [comment] 2017-12-05 03:53
@m0xf The count is now correct; have you changed anything since opening this issue?
![image](https://user-images.githubusercontent.com/8990880/33589340-c6f944a2-d92c-11e7-9579-f2bf273353e5.png)

**Comment by lunny** [comment] 2017-12-05 05:56
Maybe related with commit count cache? @lafriks

**Comment by lafriks** [comment] 2017-12-05 07:21
I will check if caching could reason for this

**Comment by m0xf** [comment] 2017-12-05 14:43
@ethantkoenig No.

**Comment by lafriks** [comment] 2018-01-15 01:06
Should be fixed by #3368

**Comment by lafriks** [comment] 2018-01-20 13:14
Closing as fixed, reopen if #3368 did not fix your issue

**Closed as completed by lafriks** 2018-01-20 13:14 UTC
Labels: type/bug
