### ISSUE TITLE
Many lock file exists errors

### ISSUE THREAD

**Issue by harryzcy** [go-gitea/gitea#29673] opened 2024-03-08 14:40 UTC
### Description

I'm having many lock file exists error in System Notices. I know it's likely because sync requests are triggered too quickly (I have a Github app that triggers it on every Github webhook), and it doesn't cause anything. But is there way to reduce the errors? Like using a retry logic, using a queue, etc.

```
Failed to update mirror repository '/data/git/repositories/harryzcy/repo.git': fatal: Unable to create '/data/git/repositories/harryzcy/repo.git/./objects/info/commit-graphs/commit-graph-chain.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```

### Gitea Version

1.21.7

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

<img width="1015" alt="image" src="https://github.com/go-gitea/gitea/assets/37034805/757787af-09c7-455f-a10b-33babfb9d599">

### How are you running Gitea?

Kubernetes with distributed storage

### Database

PostgreSQL

**Comment by lunny** [comment] 2024-06-13 14:21
Duplicate of #22578

**Closed as not planned by lunny** 2024-06-13 14:21 UTC
Labels: type/bug
