### ISSUE TITLE
Support different/localized language/character/letter for organization/repository name

### ISSUE THREAD

**Issue by myoung1032** [go-gitea/gitea#13295] opened 2020-10-24 15:16 UTC
- Git version:LATEST
- Operating system:
WIN10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

The current repository_name only supports English letters and hyphens. How can I change it to support Chinese characters？

**Comment by lunny** [comment] 2020-10-24 15:29
I don't think it's necessary.

**Comment by myoung1032** [comment] 2020-10-24 15:41
This is for non-technical personnel. I'm not familiar with this structure, and I want to know how many places I need to modify?
thanks a lot!

**Comment by kevinlin18** [comment] 2020-10-24 16:31
Maybe full name/nickname for repo will help. Some non-technical members in our team can never figure out the repo name.

**Comment by usernamedd** [comment] 2020-12-01 15:38
In my opinion , it is absolutely necessary !

**Comment by lafriks** [comment] 2020-12-01 15:46
You can always add Description to repository

**Comment by wxiaoguang** [comment] 2023-05-18 00:50
This comment contains more details (a general explanation)

* https://github.com/go-gitea/gitea/issues/13943#issuecomment-939462599

**Comment by muttakigenc** [comment] 2024-01-02 07:12
It is arrogant to assume that the world is only in English.

**Comment by muttakigenc** [comment] 2024-01-02 07:14
The world is not just about English. Other languages should definitely be taken into consideration.

**Comment by techknowlogick** [comment] 2024-01-02 07:20
Closing as dupe of https://github.com/go-gitea/gitea/issues/13943#issuecomment-939462599 which we are limited by filesystem limitations. The git repos shouldn't be stored as reponame on disk, and should be shared due to possible issues with inodes, but as that is the case right now. There was a proposal PR to change this, but this should be tracked in the ticket that was related to (can't currently find it).

**Closed as completed by techknowlogick** 2024-01-02 07:20 UTC
Labels: reviewed/wontfix
