### ISSUE TITLE
Externalize bindata.go to an auto-generated file

### ISSUE THREAD

**Issue by thibaultmeyer** [go-gitea/gitea#77] opened 2016-11-05 08:02 UTC
I think `bindata.go` dont have to be committed on repository and must be auto-generated during the make process.

It become a mess when two (or more) Pull Requests update different files (eg : app.ini for the first commit and add new files for the second) because the `bindata.go` file cause merge error each time.

**Comment by strk** [comment] 2016-11-05 08:09
I generally agree on never keeping anything that's not source code into the repository.
What I've understood is that bindata.go is there to allow for "go get" to get you a compiled binary, so basically a workaround to a "go get" limitation. But I don't have further references about this limitation and other possible workarounds.

In all cases, I think it is acceptable to `go get ...; less README.md; make;`

**Comment by tboerger** [comment] 2016-11-05 08:13
I don't agree on that. There are no other ways to stay go gettable than adding bindata to the repo.

If there are other ways around we can talk about that.

**Comment by tboerger** [comment] 2016-11-05 08:14
BTW, go get will fail without the bindata because the imports can't be accomplished

**Comment by strk** [comment] 2016-11-05 08:17
@tboerger it will fail but will have downloaded all the sources, right ?

**Comment by tboerger** [comment] 2016-11-05 08:20
But if I go get something I expect to have it working without reading the readme to find out what else needs to be done

**Comment by strk** [comment] 2016-11-05 08:21
I'm not a long Go user enough to know what one would have to expect by "go get". I've read it's not a package manager, but I do see it being used as such

**Comment by strk** [comment] 2016-11-05 08:25
For the PR mess (conflicts and changelogs size), I shall note that @Unkwon used to only update bindata.go before releases, and not accepting those updates in the PRs themselves.

**Comment by tboerger** [comment] 2016-11-05 08:37
I would suggest an additional commit made by the CI system that updates the bindata.

**Comment by strk** [comment] 2016-11-05 08:45
If bindata.go has to stay, +1 for the CI system automation (only if it would change).
But I'd really prefer to give-up go-get'ability than keeping generated files in the repo.
How about making bindata.go usage optional, so to retain go-getability while still allowing bindata.go usage upon request ?

**Comment by strk** [comment] 2016-11-05 08:55
@tboerger is the optional bindata.go what you'd get with build tags ? (https://github.com/go-gitea/gitea/pull/74#issuecomment-258598101)

**Comment by strk** [comment] 2016-11-05 14:30
My take on the optional embedding of files is in this PR: https://github.com/go-gitea/gitea/pull/78
I've understood @tboerger is also working on making embedding optional in his #74, but I think that PR also adds `public` and `templates` into the bindata, so maybe it make sense to divide the work in two steps, for easier reviews ?

**Comment by strk** [comment] 2016-11-05 15:16
For reference, @tboerger PR about conditional bindata embedding is #30 (came out in gitter chat)

**Comment by strk** [comment] 2016-11-05 15:17
So, should this be closed as a duplicate of #30 ?

**Comment by tboerger** [comment] 2016-11-11 22:18
Duplicate of #30

**Closed as completed by tboerger** 2016-11-11 22:18 UTC
Labels: issue/duplicate
