### ISSUE TITLE
Inline review comment is broken

### ISSUE THREAD

**Issue by wxiaoguang** [go-gitea/gitea#18320] opened 2022-01-18 09:12 UTC
Demo: https://try.gitea.io/wxiaoguang/test/pulls/4/files

Click the `+` to do a comment:

![image](https://user-images.githubusercontent.com/2114189/149906454-a0ed534e-703e-4b0e-abd4-027d548911c9.png)

**Comment by zeripath** [comment] 2022-01-18 09:17
This was fixed in the bidi PR but I guess some of the changes that happened to that or changes that happened as it was merged broke things.

The comment box will be in the wrong column - should be a very simple fix.

**Comment by zeripath** [comment] 2022-01-18 09:24
yup I think it's an unrecognised conflict

The problem is here:

https://github.com/go-gitea/gitea/blob/089b4e6a4585a3d9d185abd9350e7c5d537cfa86/web_src/js/features/repo-issue.js#L503

This should be:

```html
            <td colspan="3" class="lines-num"></td>
```

**Closed as completed** 2022-01-18 10:28 UTC
Labels: type/bug, topic/ui, issue/regression
