### ISSUE TITLE
Cannot restore gitea-db.sql from mysql to postgresql

### ISSUE THREAD

**Issue by jtktam** [go-gitea/gitea#13875] opened 2020-12-06 13:22 UTC
- Gitea version (or commit ref): 1.14.0+dev-321-g8561f2669
- Git version: 
- Operating system: docker image from docker hub
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description

I am currently trying to migrate from mysql to postgresql as the backend database.  I did a dump of the current mysql database and everything looks fine.

When I try to run the backup sql file (gitea-db.sql) it is failing on insert into the user table

when I use psql (with the same login credentials and datbase name) and do a "select * from user" i get the built in user table.  I think this is why the inserts are failing

I tried to create the database table manually and set the search path to "public" only and it still picks up the built in user table.

what's the workaround?

thanks

**Comment by lafriks** [comment] 2020-12-07 21:43
Add double quotes around user table name, ex `"user"`

**Comment by jtktam** [comment] 2020-12-08 00:57
> Add double quotes around user table name, ex `"user"`

it's already quoted in the dump script

**Comment by 6543** [comment] 2020-12-08 02:02
@jtktam did you add the database argument?

`./gitea dump --database postgres`

**Comment by jtktam** [comment] 2020-12-08 02:06
yes

**Comment by 6543** [comment] 2020-12-08 02:22
can you test ```sed -i 's/user/`user`/g' gitea-db.sql``` ?

**Comment by balibebas** [comment] 2020-12-29 21:33
> When I try to run the backup sql file (gitea-db.sql) it is failing on insert into the user table

What command did you use?

**Comment by balibebas** [comment] 2020-12-29 21:35
> When I try to run the backup sql file (gitea-db.sql) it is failing on insert into the user table

What command did you use to try restoring that caused the failure? And what was the failure message?

**Comment by visteras** [comment] 2021-05-05 20:56
I also tried to move from mysql (mariadb) to postgres, but only the first user was added (but the dump has everything), and in the version table there is only an id column (and no version column), this is what I noticed.
I see this error after start(migration): https://github.com/go-gitea/gitea/blob/main/models/migrations/migrations.go#L385

**Comment by visteras** [comment] 2021-05-06 06:23
User cannot inserted because keep_activity_private in mysql(mariadb) is null, but real filed has status "not null".
And the release table has the correct number of rows, but the IDs are different, I don't know if this will lead to an error or not ...

**Comment by zeripath** [comment] 2021-05-10 08:39
I suspect this is related to the issues I've noted with cross-db dumps in gitea. Ultimately the problem is that the cross db dump does a direct translation of the db schemas without reference to objects attached to those schemas. For most fields this doesn't cause a problem but it does when a db uses things like `int` for `bool` - e.g. MySQL. https://gitea.com/xorm/xorm/pulls/1872 and all of its follow-ups should fix this and will be in xorm 1.0.8 which will very likely be used by Gitea 1.15. (We'll have to think about whether backporting it is the right thing to do but we'll need serious testing.)

In the meantime users who want/need previews of this fixed functionality should contact me either on discord or by email. I can provide builds of 1.14.x (and perhaps earlier) with the fixed xorm PRs 1.0.8.x pulled in to gitea so that you can get a fixed migrations scripts and we can work through any issues.

**Comment by lunny** [comment] 2021-06-01 15:15
Could you help to confirm that #15885 resolved the problem?

**Comment by Adito5393** [comment] 2021-06-11 13:18
I am planning to migrate my Gitea DB from MySQL to PostgreSQL, is this still a valid issue for **v1.14.2**?

If no one knows, I can try to migrate and see what errors/warnings I encounter.

**Closed as completed** 2021-06-11 21:51 UTC
Labels: type/question
