### ISSUE TITLE
Proposal: hide organizations for users are not part of

### ISSUE THREAD

**Issue by yusefmaali** [go-gitea/gitea#1474] opened 2017-04-09 01:29 UTC
In my typical scenario, will be extremely useful if a user is not allowed to see all the organizations through the explore page, but only those he is part of.

May be needed, for example, add a "private" flag to the organization, just like repos already have.

Thank you!

**Comment by DblK** [comment] 2017-05-18 15:00
Seems to be a duplicate of #714

**Comment by lunny** [comment] 2017-05-19 00:27
@DblK yes. Let's continue there. @usef

**Closed as completed by lunny** 2017-05-19 00:27 UTC
Labels: issue/duplicate
