### ISSUE TITLE
Sort tags by commit date

### ISSUE THREAD

**Issue by FrostKiwi** [go-gitea/gitea#30971] opened 2024-05-14 07:18 UTC
### Feature Description

As of right now (Gitea `1.21.5`), tags are shown in the order they were added.
Recently I went through and tagged all out releases, to add tags that were forgotten. As a result, the order of releases does not correspond to the shown order, see Screenshot below.

It would be great, if the tags were displayed in order of the commit date, that the tags are pointing to.

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/60887273/c48c23bc-db00-470f-83f3-829a2d44cd69)

**Comment by kemzeb** [comment] 2024-08-06 04:39
Hi @FrostKiwi, thanks for the feature request. I know it has been some time, but do you remember using the **web UI** to add your tags? Or, did you do a regular `git push --tags`?

**Comment by FrostKiwi** [comment] 2024-08-06 05:45
> Hi @FrostKiwi, thanks for the feature request. I know it has been some time, but do you remember using the **web UI** to add your tags? Or, did you do a regular `git push --tags`?

They were added by `git push --tags`

**Comment by kemzeb** [comment] 2024-08-07 01:32
Gotcha. Just to make sure, were you creating annotated tags?

I am able to reproduce this problem with annotated tags but not lightweight tags in v1.21.5 onwards.

**Comment by FrostKiwi** [comment] 2024-08-07 01:37
> Gotcha. Just to make sure, were you creating annotated tags?
> 
> I am able to reproduce this problem with annotated tags but not lightweight tags in v1.21.5 onwards.

Yes, that is correct. The tags were created via `git tag -a v0.1.19 98babb4a4895cd17ed087da334c1263c023ee0ac`
Currently on Gitea `v1.22.1` and it ignores the commit order, instead showing tag creation order, which is counterintuitive:
![image](https://github.com/user-attachments/assets/28351139-362a-48d8-8dea-f97db57fac04)

**Comment by FrostKiwi** [comment] 2024-08-07 01:42
> I am able to reproduce this problem with annotated tags but not lightweight tags.

Ohh! I just noticed, that I messed up. I compared all the commit dates and there is actually no issue! The tags were set wrong. So from my point of view, we can close the issue, but since you were able to reproduce a bug, I'll not close the issue yet.

**Comment by kemzeb** [comment] 2024-08-07 04:26
> Ohh! I just noticed, that I messed up. I compared all the commit dates and there is actually no issue! The tags were set wrong. So from my point of view, we can close the issue, but since you were able to reproduce a bug, I'll not close the issue yet.

Sorry I misspoke. After learning more about lightweight vs annotated tags and observing the following Gitea behavior:
- Creating a lightweight tag using the git CLI tags will use the commit creation time
- Creating annotated tags using the git CLI will use the time the tag was created

This appears to be expected behavior (and is behavior that GitHub seems to follow too after testing on a test repo). I'll close my PR since we appear to be doing things correctly and my current implementation will have a negative performance impact.

One problem I did discover was that when creating a lightweight tag using the Gitea Web UI (i.e. navigate to a single commit -> Operations -> Create tag), we would actually use the current time rather than the commit time. This is inconsistent with what we do when servicing a `git push --tags`, so I think I should create a bug report for that. I'll go ahead and close this since you are not facing any further problems

**Closed as completed by kemzeb** 2024-08-07 04:26 UTC
Labels: type/proposal
