### ISSUE TITLE
User language preference not honored

### ISSUE THREAD

**Issue by thibaultmeyer** [go-gitea/gitea#5768] opened 2019-01-19 11:14 UTC
- Gitea version (or commit ref): 1.7.0-rc3
- Git version: 2.9.5
- Operating system: Linux Centos 7
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

The user defined language is not honored when user logon the website. My browser locale is "french", when i clean all cookie and login again on Gitea, even if I have set "english" on account settings page, Gitea stay in "french"

## Screenshots

![image](https://user-images.githubusercontent.com/1005086/51425908-ff391280-1be2-11e9-82be-a9b96be2e7c5.png)

**Comment by zeripath** [comment] 2019-01-19 12:45
I think this sometimes can be due to caching. Have you tried a forced refresh? (Of the browser that is)

**Comment by adelowo** [comment] 2019-01-19 15:04
Duplicate of https://github.com/go-gitea/gitea/issues/4884

**Closed as completed** 2019-01-19 22:22 UTC
Labels: issue/duplicate
