### ISSUE TITLE
Do not emit ambiguous character warning on wiki pages

### ISSUE THREAD

**Issue by adigitoleo** [go-gitea/gitea#24421] opened 2023-04-29 10:57 UTC
### Description

The warning in question was discussed in https://github.com/go-gitea/gitea/issues/20999, and it was decided that it should not be presented on rendered pages.

The PR https://github.com/go-gitea/gitea/pull/22018 was merged to address this, however I still see the warning on wiki pages at codeberg. The PR modifies the repo template but perhaps a wiki template file also needs to be patched.

Codeberg is using a forked Gitea 1.19.2:
https://codeberg.org/forgejo/forgejo/src/branch/forgejo/RELEASE-NOTES.md#1-19-2-0

### Screenshots

![unicode_warning](https://user-images.githubusercontent.com/34595875/235298955-f73caf44-60fb-47d7-b1ae-1fde025320d9.png)

### Gitea Version

1.19.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

qutebrowser 2.5.4 (QtWebEngine 5.15.2)

**Comment by adigitoleo** [comment] 2023-04-29 12:05
Here is the demo test:

https://try.gitea.io/adigitoleo/test-wiki/wiki/Home

**Comment by wxiaoguang** [comment] 2023-04-29 13:55
Dup of #23149  (and many other similar reports)

**Comment by silverwind** [comment] 2023-04-30 18:35
Duplicate of https://github.com/go-gitea/gitea/issues/23149

**Closed as not planned by silverwind** 2023-04-30 18:35 UTC
Labels: type/bug, topic/ui, topic/wiki
