### ISSUE TITLE
Update the gitea docker tags to include a "stable" tag

### ISSUE THREAD

**Issue by markg85** [go-gitea/gitea#4881] opened 2018-09-06 16:11 UTC
Hi,

I'm running gitea on docker and thus far have had no issues. My use is rather limited though ;)
One think i noticed is that the available tags [1] is either the latest git commit or one specific version. Both aren't really ideal. I'd like to have a "stable" tag which would be the same as the last released version.

So, at this very moment gitea/gitea:stable should pull in 1.5.1

[1] https://hub.docker.com/r/gitea/gitea/tags/

**Comment by lafriks** [comment] 2018-09-07 00:27
I think `gitea/gitea:1` should contain latest sable version

**Comment by techknowlogick** [comment] 2018-09-07 00:28
The problem is if a release is created for 1.5.x, and some gets backported to 1.4.x and then a 1.4 release happens that would overwrite the "newer" release.

**Comment by markg85** [comment] 2018-09-07 09:10
@lafriks that would be an uncommon difficult to guess way.
As far as i know, no other projects do it that way. Take a look at nginx for instance [1]

@techknowlogick then you have more maintained versions i guess.
I'd say that "stable" should probably be the version that has long terms support (if gitea even has a release that covers that). A tag like "mainline" would be the latest git version. A tag like "newest" should be the newest (and highest) release.

Anyhow, this problem has been solved by a million other projects. Take your pick in how you want to solve it ;)

[1] https://hub.docker.com/r/library/nginx/tags/

**Comment by techknowlogick** [comment] 2019-02-04 01:14
Closing this as per @lafriks comment regarding `:1`

**Closed as completed by techknowlogick** 2019-02-04 01:14 UTC
Labels: type/proposal, topic/distribution

**Comment by kebertxela** [comment] 2019-05-25 17:48
Would it be possible to revisit the idea of a :stable tag?

This would allow other projects the ability to incorporate Gitea with less headache and more future proofing

**Comment by lafriks** [comment] 2019-05-25 22:05
You can already use `:1` that will be always latest stable version

**Comment by kebertxela** [comment] 2019-05-25 22:58
Oh, I assumed that the :1 would only apply for Gitea versions 1.x
