### ISSUE TITLE
Extending Gitea with Plugins

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#21302] opened 2022-09-30 10:03 UTC
### Feature Description

Using plugins system to extend Gitea can make its core functions more modular and smaller. For `Go` example, [Caddyserver](https://caddyserver.com/docs/extending-caddy).

As a result, people can extend CI, mail, packages and other Github like feature through Gitea plugins.

**Comment by delvh** [comment] 2022-09-30 10:17
duplicate of #20126

**Closed as completed by delvh** 2022-09-30 10:17 UTC
Labels: type/proposal, type/feature
