### ISSUE TITLE
Gitea with a Sub-Path: U2F Token Does Not Work With Chrome/Chromium, Does Work With Firefox

### ISSUE THREAD

**Issue by uli-heller** [go-gitea/gitea#14412] opened 2021-01-21 07:52 UTC
I've searched the issues for "fido chrome" and did not find a proper existing issue, so here is a new one...

- Gitea version (or commit ref): 1.13.1 and 1.14.0+dev-575-g1c230f69d 
- Git version: 2.25.1
- Operating system: ubuntu-20.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description

I've setup a gitea instance. It runs on ubuntu-20.04 behind an apache2 httpd reverse proxy.
My HW token (a solo key) works perfectly within firefox, but not within chrome or chromium.
Using the token with chrome on try.gitea.io works without an issue. Any idea?

## Screenshots

![image](https://user-images.githubusercontent.com/1677414/105320194-2ce83600-5bc6-11eb-8b45-97ed933a3433.png)

**Comment by zeripath** [comment] 2021-01-21 20:24
if this works on try - the suspicion has to fall upon the configuration of your server.

Now interestingly the error screen doesn't seem to report an error properly - there should be an errorcode interpretation here.

However the reload points to what the underlying issue.

There is a timeout error reported.

I suspect your server time is incorrect.

**Comment by uli-heller** [comment] 2021-01-22 07:10
@zeripath  : Thx for looking into this!

The server time is in sync with my local computer:

```
uli@ulicsl:~/git/datenschutz$ ssh gitea date; date
Fri 22 Jan 2021 07:58:52 AM CET
Fr 22. Jan 07:58:52 CET 2021
```

My local computer syncs via NTP and TOTP works for various other sites, so I guess the local time is fine.

On the other hand: It works for my gitea when using firefox. This shouldn't work when time sync is an issue, or should it?

I tried to reload by pressing the "Reload" button. The popup disappears and shows up again. No details show up unfortunately.

I checked the browser console:
- for firefox, only some warnings related to expired cookies show up
- for chrome, some errors related to logo.png show up - see below
- for chrome and try.gitea.io, no errors show up

I'll try to fix the logo error, maybe it helps

GET https://hetzner-de.daemons-point.com/gitea/gitea/img/logo.png 404 (Not Found)
u2f:1 Error while trying to use the following icon from the Manifest: https://hetzner-de.daemons-point.com/gitea/gitea/img/logo.png (Download error or resource isn't a valid image)

**Comment by uli-heller** [comment] 2021-01-22 07:14
* https://try.gitea.io/img/logo.png ... works
* https://hetzner-de.daemons-point.com/gitea/img/logo.png ... works for firefox
* https://hetzner-de.daemons-point.com/gitea/gitea/img/logo.png ... 404 for firefox

Unclear: Why does chrome try to load the "gitea/gitea" logo?

**Comment by uli-heller** [comment] 2021-01-22 07:35
Adding this

```
   RewriteRule "^/gitea/gitea" "/gitea" [R]
```

to the apache httpd reverse proxy makes the error disappear. U2F doesn't work.

**Comment by cortices** [comment] 2021-01-25 02:53
I'm getting the same results in Safari 14 (which has native U2F support) trying to add a U2F key as well.

**Comment by uli-heller** [comment] 2021-01-25 11:19
I changed my setup a little bit, now it works with chrome:
- remove the sub-path and restart gitea and apache2 httpd reverse proxy
- try to login using the token:
    - now the token blinks red -> push the button
    - now I'm getting the error page again
- remove the token (was added when sub-path was active)
- add the token again
- works OK with chrome

**Comment by uli-heller** [comment] 2021-01-25 11:23
@cortices : Are you using a sub-path, too?

**Comment by cortices** [comment] 2021-01-25 11:29
I am not using a subpath. I just tested and found it is working with both Chrome and Firefox, so the bug is Safari-specific. I will open a separate issue.

**Comment by cortices** [comment] 2021-01-25 11:54
By the way your issue here seems to be a duplicate of #10231 : https://github.com/go-gitea/gitea/issues/10231#issuecomment-584836417

**Comment by uli-heller** [comment] 2021-01-25 12:25
@cortices : Thx. I tried to set these properties:

```
[U2F]
APP_ID = https://hetzner-de.daemons.point.com
TRUSTED_FACETS = https://hetzner-de.daemons.point.com
```

and activated the sub-path again. Unfortunately, the hw token doesn't work. So maybe I'm facing a different issue?

**Comment by 6543** [comment] 2022-01-14 15:04
#17957

**Closed as completed by 6543** 2022-01-14 15:04 UTC
Labels: type/bug
