### ISSUE TITLE
Markdown styling issue with lists

### ISSUE THREAD

**Issue by luwol03** [go-gitea/gitea#12488] opened 2020-08-13 21:07 UTC
- Gitea version (or commit ref): 4315e313d12bbf0655710b6ab0aad121e0f7dba2
- Git version: 2.20.1
- Go version: 1.14.2
- Operating system: Debian 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes https://try.gitea.io/luwol03/test/src/branch/master/CHANGELOG.md
  - [ ] No
  - [ ] Not relevant
- Log gist:
  - Not relevant
## Description
![IMG_20200813_224833](https://user-images.githubusercontent.com/60048565/90185563-3370b700-ddb7-11ea-9f5d-3c555582efac.png)
The margin between the second and first level points is rendered smaller than between the first and second level points. This happened also on issues, releases, Pull request and wiki pages; Everywhere you can use markdown.

**Comment by m455** [comment] 2020-11-08 14:58
Hello, I am experiencing this issue too. The only difference is I'm using SQLite.

Having the nested points looking like they are part of their parent point would definitely be nicer, so I'm all for this fix :D

**Comment by zeripath** [comment] 2020-11-08 15:42
So up until very recently Github would render this exactly the same - I know because I have commented on another issue reporting the same problem.

This would be very simple to solve after looking at the less.

**Comment by nostachio** [comment] 2020-12-01 18:15
This seems to be expected behavior for markdown; checking a few other renderings outside of gitea, the behavior is the same:
![Screen Shot 2020-12-01 at 10 17 52 AM](https://user-images.githubusercontent.com/38520190/100775235-3c19e700-33c0-11eb-8b04-57ec0d060d30.png)
![Screen Shot 2020-12-01 at 10 29 01 AM](https://user-images.githubusercontent.com/38520190/100775252-420fc800-33c0-11eb-8204-8ddbeb3084e4.png)

Your example is rendering with the extra space because the blank line in between the heading and the list causes the list items to be wrapped in paragraph tags:
![Screen Shot 2020-12-01 at 10 50 53 AM](https://user-images.githubusercontent.com/38520190/100779260-5d310680-33c5-11eb-85d3-5db33b7f38a2.png)

The formatting solution is to remove the blank line between the heading and the list like so and the items are no longer wrapped in paragraph tags:
![Screen Shot 2020-12-01 at 11 09 11 AM](https://user-images.githubusercontent.com/38520190/100779523-be58da00-33c5-11eb-90fc-db6f71567f69.png)

I'd recommend closing this and tagging with reviewed/not-a-bug or similar.

**Comment by jolheiser** [comment] 2020-12-01 18:25
@nostachio Thanks for the comparisons!

I'm going to close this issue based on the above. If we do want to change how the grouping looks, I'd prefer a new proposal issue to track any CSS/Less changes needed. 🙂 

Here are some comparison links/images on try.gitea.io illustrating the proposed change from @nostachio.

[the original](https://try.gitea.io/luwol03/test/src/commit/4dd420cafafb9f0c9041d746b5f053455f0cb04f/CHANGELOG.md)
![changelog1](https://user-images.githubusercontent.com/42128690/100781001-1563ac80-33d0-11eb-893e-df4eeb8180ed.png)

[my fork](https://try.gitea.io/jolheiser/luwol-test/src/commit/524f6f567dee39b4d4fd7d9bfb8454f79aa3c0a4/CHANGELOG.md)
![changelog2](https://user-images.githubusercontent.com/42128690/100781005-15fc4300-33d0-11eb-89a7-558e305898d5.png)

**Closed as completed by jolheiser** 2020-12-01 18:25 UTC
Labels: topic/ui, issue/not-a-bug, good first issue
