### ISSUE TITLE
Rename organization cause git push fail

### ISSUE THREAD

**Issue by chinglinwen** [go-gitea/gitea#3432] opened 2018-01-30 03:28 UTC
- Gitea version (or commit ref):    Gitea Version: 1.3.2
- Git version:  git version 2.15.1.windows.2
- Operating system: windows7 amd64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)  https://try.gitea.io/chinglinorg1/test/_edit/master/README.md
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

$ git clone http://issue.qianbao-inc.com/SRE/issues.git
Cloning into 'issues'...
remote: Counting objects: 12, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 12 (delta 1), reused 12 (delta 1)
Unpacking objects: 100% (12/12), done.

git add . 
git commit -m "update readme"

$ git push
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 305 bytes | 305.00 KiB/s, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: 2018/01/30 10:25:01 [...io/gitea/cmd/hook.go:66 hookSetup()] [E] LFS server support needs at least Git v2.1.2
remote: 2018/01/30 10:25:01 [...io/gitea/cmd/hook.go:66 hookSetup()] [E] LFS server support needs at least Git v2.1.2
remote: 2018/01/30 10:25:01 [...io/gitea/cmd/hook.go:66 hookSetup()] [E] LFS server support needs at least Git v2.1.2
To http://issue.qianbao-inc.com/SRE/issues.git
   14621fb..0bbe2f3  master -> master

## Screenshots
![rename_org_cause_git_fail](https://user-images.githubusercontent.com/16344129/35545296-615c0338-05a9-11e8-8ae0-f7690a50d9a1.png)

Failed to update/create file 'README.md' with error: UpdateLocalCopyBranch [branch: master]: git fetch origin: exit status 128 - fatal: '/data/git/repositories/chinglinorg/test.git' does not appear to be a git repository fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists.

**Comment by lafriks** [comment] 2018-01-30 04:31
Duplicate of #3378 and has been fixed by #3399. Will be fixed in release 1.4.0

**Comment by lafriks** [comment] 2018-01-30 04:33
You can just delete local temporary copy of repository in `tmp/local-repo`

**Closed as completed by lafriks** 2018-01-30 04:33 UTC
Labels: issue/duplicate

**Comment by chinglinwen** [comment] 2018-01-30 07:25
Delete tmp/local-repo in gitea/data directory works. I tried search issue before, my keyword may not align.

Thank you !
