### ISSUE TITLE
GitHooks UI (Web IDE) is broken on update to Gitea 1.21.0

### ISSUE THREAD

**Issue by sgabenov** [go-gitea/gitea#28344] opened 2023-12-04 14:45 UTC
### Description

After migration from 1.20.0 -> 1.21.0 the web ide for displaying Git Hooks brakes. When i paste any text to web ide it actually saves it but do not display. All previousely configured git hooks do not display as well.

![gitea_1](https://github.com/go-gitea/gitea/assets/15741789/63a8861f-ac1c-4a1b-93ae-5f866d11c7be)
![gitea_2](https://github.com/go-gitea/gitea/assets/15741789/57a43297-9827-42c8-9891-41f0449cc585)

### Gitea Version

1.21.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker

### Database

PostgreSQL

**Comment by wxiaoguang** [comment] 2023-12-04 15:02
Maybe caused by  Fix EOL handling in web editor #27141  and reverted by " Revert "Fix EOL handling in web editor" #28101 "

Could you try the 1.21 nightly build?

**Comment by wxiaoguang** [comment] 2023-12-06 04:19
I think it should have been fixed by the "revert" PR. Feel free to reopen if there is still a problem.

**Closed as completed** 2023-12-06 04:21 UTC
Labels: issue/needs-feedback
