### ISSUE TITLE
[Feature] Better Multi Domain Support

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#11732] opened 2020-06-02 12:56 UTC
~~Use host from http request to set hostname if setting is ""~~
Use hostname of http request by default to generate http links

Config Rev:
https://github.com/go-gitea/gitea/blob/02a52d683b32e2670f746d898bd0041954390e7b/custom/conf/app.ini.sample#L235

Usefull for https://codeberg.org/Codeberg/Community/issues/180

**Comment by silverwind** [comment] 2020-06-02 13:43
IIRC the issue is that LFS over SSH requires a hostname but because SSH does not have the concept of a host header, the config can not be completely domain-less with LFS is enabled.

But I guess we could try making it work domain-less when LFS is not enabled but it will require many changes I assume.

**Comment by 6543** [comment] 2020-06-02 15:02
Or use hostnabe of http request by default to generate http links

**Comment by Codeberg-org** [comment] 2020-06-02 16:50
> IIRC the issue is that LFS over SSH requires a hostname but because SSH does not have the concept of a host header, the config can not be completely domain-less with LFS is enabled.
> 
> But I guess we could try making it work domain-less when LFS is not enabled but it will require many changes I assume.

Could potentially the hostname from the request struct be used?

**Comment by Codeberg-org** [comment] 2020-06-02 16:50
> Or use hostnabe of http request by default to generate http links

sorry, saw this too late. Yes.

**Comment by silverwind** [comment] 2020-06-02 17:34
One more issue would be the "Create a pull request" links that are printed when pushing to a non-default branch via SSH but I guess conditionals to skip the print could be added to those places if hostname can not be determined from the config.

**Comment by rany0** [comment] 2020-06-23 12:09
Wouldn't it be better to allow the admin to specify a fallback hostname and then rely on `Host` header if it was present?  

That way SSH would still print and we won't need to skip the print.

**Comment by silverwind** [comment] 2020-06-23 12:18
I think generally we want to use `Host` header (and request path) if present and echo it back and for cases where it's not available fall back to `ROOT_URL` if set, or skip/fail otherwise.

**Comment by wxiaoguang** [comment] 2023-07-22 13:48
->  Multi-domain support, ROOT_URL problem, use relative URLs in templates instead of absolute URLs #19345 

Most of the ROOT_URL problems should have been fixed by the recent ROOT_URL refactoring PRs.

There are still incorrect usages of the ROOT_URL(AppURL), which could be fixed one by one when they are found.

**Closed as completed** 2023-07-22 17:25 UTC
Labels: issue/needs-feedback
