### ISSUE TITLE
Can't migrate the github repo with ssh protocol

### ISSUE THREAD

**Issue by hansen6878** [go-gitea/gitea#19096] opened 2022-03-15 16:36 UTC
### Gitea Version

1.16.4

### Git Version

2.20.1

### Operating System

debian10(bluster)

### Database

SQLite

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

In my network environment,  it is very unstable to migrate github repo with https protocol(git clone https://github.com/ownxxx/repoxxx.git), so I have to use ssh protocol(git clone git@github.com:ownxxx/repoxxx.git) to migrate github repo.
when i use the migrate feature of gitea to mirror github repo, and type the ssh url(git@github.com:ownxxx/repoxxx.git), it will show the invalid URL message: "is not a valid URL."
does gitea really support migrate github repo with ssh protocol now? or it's my migrate method is wrong?

BTW: i have make and setup the pair of RSA ssh key for github, and can clone the repo successfully with raw command method on the terminal.

thanks a lot!

**Comment by techknowlogick** [comment] 2022-03-15 16:50
closing as dupe of https://github.com/go-gitea/gitea/issues/1635

**Closed as completed by techknowlogick** 2022-03-15 16:50 UTC
Labels: issue/duplicate
