### ISSUE TITLE
Long commit messages are not wrapped properly and break CSS

### ISSUE THREAD

**Issue by proton-ab** [go-gitea/gitea#10209] opened 2020-02-10 14:28 UTC
- Gitea version (or commit ref): 1.11.0
- Git version: -
- Operating system: -
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: -

## Description
Long commit messages are not wrapped properly anymore and cause `repo-files-table` table to grow with them.

## Screenshots
![firefox_2020-02-10_15-26-15](https://user-images.githubusercontent.com/25139420/74158207-f1a16100-4c19-11ea-9e6e-021f7052d4d5.png)

**Comment by zeripath** [comment] 2020-02-11 07:56
I think this is a duplicate but it's a good reminder that it still needs to be fixed

**Comment by silverwind** [comment] 2020-02-11 17:21
Dupe of https://github.com/go-gitea/gitea/issues/8900 but this issue has a more accurate description. I think server-side truncaton is needed here.

**Closed as completed** 2020-02-17 17:45 UTC
Labels: topic/ui
