### ISSUE TITLE
Incorrect nested webUI when submitting an empty inline review within a PR

### ISSUE THREAD

**Issue by eeyrjmr** [go-gitea/gitea#18151] opened 2022-01-01 18:03 UTC
### Gitea Version

1.15.8/1.16

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

When you start a review associated with a PR, if you select a line-number and "start review" the vast majority of the Gitea WebUI is reproduced causing layout issues. **The key point is "submitting an empty comment" (or trigger some other errors).**

https://try.gitea.io/eeyrjmr/test_issues/pulls/2/files

Steps to reproduce

1. Start a PR
2. view PR 
3. View PR files
4. click blue + on one of the  lines 
5. keep content empty, click green start review UI button
6. error message:  "Content cannot be empty."

![2022-01-01_18-01-1641060192](https://user-images.githubusercontent.com/4564448/147857190-fb2319e2-f262-416b-b472-b287044e55ae.png)

**Comment by Gusted** [comment] 2022-01-01 23:03
This of course shouldn't be happening, I know that this HTML(the review panel) is provided and rendered from a network request on-demand. So... do you have any extension, proxies, firewall that could cause interference.

**Comment by eeyrjmr** [comment] 2022-01-01 23:08
I do have some extensions so I'll retry with all disabled to see if it can be narrowed down

**Comment by eeyrjmr** [comment] 2022-01-02 13:05
so...
Chrome-98 and used incognito mode - issue exists
Chrome-98 and all extensions disabled - issue exists
Firefox-95 - issue exists

**Comment by eeyrjmr** [comment] 2022-01-02 13:30
Just tried it on my mobile on 4G, same thing

**Comment by wxiaoguang** [comment] 2022-01-02 13:35
What is the message here?


<img width="1131" alt="image" src="https://user-images.githubusercontent.com/2114189/147877496-72ca2e51-fa48-44ef-8305-e4ecbc150126.png">

**Comment by wxiaoguang** [comment] 2022-01-02 13:38
The error message is "Content cannot be empty."

The problem occurs when a user tries to submit a empty form, then backend&frontend can not handle it gracefully.

**Comment by Gusted** [comment] 2022-01-02 13:39
> The error message is "Content cannot be empty."
> 
> The problem occurs when a user tries to submit a empty form, then backend&frontend can not handle it gracefully.

Can reproduce now. Thanks @wxiaoguang 😄

**Comment by wxiaoguang** [comment] 2022-01-02 13:41
I updated the original comment also. It's important to report/describe a bug clearly. 😂

**Comment by eeyrjmr** [comment] 2022-01-02 14:07
> I updated the original comment also. It's important to report/describe a bug clearly. joy
At the time I didn't know this was the cause, adding "something" doesn't cause this. Also once the "review has started" you don't get this ui option anymore only comments

**Comment by wxiaoguang** [comment] 2022-01-02 14:55
That's fine and already helps Gitea a lot 👍  (ps: if the screenshot could be more clear, then the problem could be more obvious at first glance 😊)

The updating of the original comment is to make new readers can know how the bug appends and hopefully the bug can be fixed soon.

**Comment by Gusted** [comment] 2022-01-02 14:56
I guess the simplest fix is to disable the comments when their is no content? Because otherwise the patch will become quite lengthy in order for the JS to see redirects and then replace the whole DOM(Performance does ouch).

**Comment by wxiaoguang** [comment] 2022-01-02 15:00
There  was a PR  to make the edit area on  Wiki pages  can be `requried`. I am not sure whether it could help this problem:
* #17415

If the empty content is the only reason to trigger this bug,  it could be fixed by the `required` attribute.

Otherwise maybe we should re-design the AJAX requests.

**Closed as completed** 2022-01-02 22:31 UTC
Labels: type/bug, issue/confirmed
