### ISSUE TITLE
Strange red label span containing hexadecimal beside notification icon

### ISSUE THREAD

**Issue by gabrielctn** [go-gitea/gitea#13037] opened 2020-10-05 20:01 UTC
- Gitea version (or commit ref): 1.13.0+dev-617-g8ce10fb6e built with GNU Make 4.3, go1.15.2 : bindata, sqlite, sqlite_unlock_notify
- Git version: 2.26.2
- Operating system: Ubuntu 14.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
Once logged in, there is always a strange html span of class `span.ui.red.label` appearing next to the notification icon
...

## Screenshots

![image](https://user-images.githubusercontent.com/25644865/95125100-bdeceb80-0754-11eb-8e72-02797fc67f03.png)

**Comment by jolheiser** [comment] 2020-10-05 20:03
Duplicate of #12539 (and others)

This is caused by custom templates.

**Closed as completed by jolheiser** 2020-10-05 20:03 UTC
Labels: issue/duplicate
