### ISSUE TITLE
sqlite Migration: add approval whitelists to protected branches fails

### ISSUE THREAD

**Issue by jsimonetti** [go-gitea/gitea#5760] opened 2019-01-18 12:13 UTC
- Gitea version (or commit ref): docker 1.7.0-rc2 
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

2019/01/18 11:59:09 [I] Log Mode: File(Info)
2019/01/18 11:59:09 [I] XORM Log Mode: File(Info)
2019/01/18 11:59:09 [I] Cache Service Enabled
2019/01/18 11:59:09 [I] Session Service Enabled
2019/01/18 11:59:09 [I] Migration: add approval whitelists to protected branches
2019/01/18 11:59:09 [...itea/routers/init.go:61 GlobalInit()] [E] Failed to initialize ORM engine: migrate: do migrate: Unknown col "is_empty" in index is_bare of table repository, columns [id owner_id lower_name name description website default_branch num_watches num_stars num_forks num_issues num_closed_issues num_pulls num_closed_pulls num_milestones num_closed_milestones is_private is_empty is_mirror is_fork fork_id size is_fsck_enabled topics created_unix updated_unix]

## Description

The migration fails because the index was created using:
```CREATE INDEX `IDX_repository_is_bare` ON `repository` ("is_empty");```

The index should actually be:
```CREATE INDEX `IDX_repository_is_bare` ON `repository` (`is_empty`);```
(note the backticks instead of quotes)

Manually editting the database and doing:
```sqlite> DROP INDEX `IDX_repository_is_bare`;```
```sqlite> CREATE INDEX `IDX_repository_is_bare` ON `repository` (`is_empty`);```

now allows for the db migration to v74 to succeed.

**Comment by serverwentdown** [comment] 2019-01-18 14:10
Thanks! This affected me when I upgraded.

**Comment by theasp** [comment] 2019-01-18 15:58
Using the docker image that was pushed after that commit (image c98e58549906), I am still having this issue.

```
2019/01/18 15:57:04 [...itea/routers/init.go:61 GlobalInit()] [E] Failed to initialize ORM engine: sync database struct error: Unknown col "is_empty" in index is_bare of table repository, columns [id owner_id lower_name name description website default_branch num_watches num_stars num_forks num_issues num_closed_issues num_pulls num_closed_pulls num_milestones num_closed_milestones is_private is_empty is_mirror is_fork fork_id size created_unix updated_unix is_fsck_enabled topics]
```

**Comment by zeripath** [comment] 2019-01-18 21:55
If unfortunately you were hit by the migration bug and starting your gitea failed, please follow the below steps:

* Stop gitea if it's still running
* Change the value of the table `version`  from `79` to `78`
* Restart gitea

**Comment by zeripath** [comment] 2019-01-18 21:58
@theasp you may need to explicitly run `gitea migrate` too

**Comment by zeripath** [comment] 2019-01-18 21:58
This is a duplicate of #5759

**Closed as completed by zeripath** 2019-01-18 21:58 UTC
Labels: issue/duplicate
