### ISSUE TITLE
Use JS to convert timezones to local

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#15732] opened 2021-05-05 09:10 UTC
The timestamp output in the UI is currently incorrectly using a single time zone set on the server so it will not show the correct dates for the user's current timezone. Instead, we should use something like https://github.com/github/time-elements to render dates in the user's local timezone. This features does require JS to work, otherwise it will display the server-rendered fallback date.

**Comment by zeripath** [comment] 2021-05-05 22:01
Agreed. Either the user has to pass down their current timezone or it has to be rendered on the client. The issue is the language translation.(which we're currently not doing correctly anyway.)

**Comment by silverwind** [comment] 2021-05-05 22:12
Yes, we can output a rendering in the server timezone as the placeholder value and as soon as JS loads, that's going to be replaced by a value for the actual user time zone.

**Comment by yardenshoham** [comment] 2022-10-22 17:58
I believe this can be closed as the following PRs were merged:
* #21410
* #21440

**Closed as completed** 2022-10-22 18:03 UTC
Labels: type/proposal, topic/ui

**Comment by yardenshoham** [comment] 2022-11-04 13:24
time-elements now supports locales (github/relative-time-element#174) so my previous PRs could be replaced

**Comment by silverwind** [comment] 2022-11-07 20:05
`time-elements` would definitely be preferred as they can auto-update relative time.
