### ISSUE TITLE
Feature: Search on Wiki

### ISSUE THREAD

**Issue by rlogiacco** [go-gitea/gitea#16375] opened 2021-07-08 12:10 UTC
It would be very useful if we can have a search field for a full text search on wiki content, optionally reducing the search scope to either the organization or the repository.

**Comment by nauevg** [comment] 2021-07-10 04:43
main problem for me
#12302 #3670 #2434 here something more about searching
for the wiki search. it is one more git repo. we already have search for repos. maybe it is possible to add existing function for one more wiki git repo?

**Comment by noerw** [comment] 2021-07-10 09:10
closing as duplicate of 3670, please follow progress there

**Closed as completed by noerw** 2021-07-10 09:10 UTC
Labels: issue/duplicate
