### ISSUE TITLE
5000 commenting on a line with accented chars

### ISSUE THREAD

**Issue by rlogiacco** [go-gitea/gitea#10393] opened 2020-02-21 10:53 UTC
- Gitea version (or commit ref): *1.11.1*
- Git version: 
- Operating system: *linux*
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

Commenting on a pull request on a line containing accented characters produces a 500 error with the following log:

```
2020/02/21 10:48:46 .../repo/pull_review.go:48:CreateCodeComment() [E] CreateCodeComment: Error 1366: Incorrect string value: '\xE8 vali...' for column 'patch' at row 1
```

The line this comment was pointing at is
```
			throw new Exception("ATTENZIONE: La Sessione HTTP non è valida");
```

**Comment by lunny** [comment] 2020-02-21 11:26
Maybe you should use utf8mb4 charset on your app.ini

**Comment by guillep2k** [comment] 2020-02-21 13:24
This happens when the file itself is not using utf-8 (e.g. ISO-8859-1).
This is a duplicate of #7270.

**Closed as completed by guillep2k** 2020-02-21 13:24 UTC
Labels: issue/duplicate
