### ISSUE TITLE
SHA-256 object hashes cause fatal error on push

### ISSUE THREAD

**Issue by h3xx** [go-gitea/gitea#22309] opened 2023-01-02 04:00 UTC
### Description

Steps:

1. Run these commands to set up your repository:

```sh
git init --object-format=sha256
touch test
git add .
git commit -m 'Initial commit'
```

2. Push it to a gitea instance.

Results in fatal server-side error:

```
$ git push -vvv origin main
Pushing to codeberg.org:h3xx/test-sha256
fatal: protocol error: unexpected capabilities^{}
fatal: the remote end hung up unexpectedly
Gitea: Internal error
```

Note: that's literal `^{}` garbage characters.

Expected:
- A better error message. This one makes me feel like I broke your site.
- OR (and I realize it's a long shot) support for SHA-256 object hashes

git 2.39.0

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

2.39.0

### How are you running Gitea?

Codeberg.org

### Database

None

**Comment by lafriks** [comment] 2023-01-02 16:11
Gitea currently does not support sha256 hashes

**Comment by lafriks** [comment] 2023-01-02 16:16
Duplicate of #13794

**Closed as completed by lafriks** 2023-01-02 16:16 UTC
Labels: issue/duplicate
