### ISSUE TITLE
env vars don't work, k8s

### ISSUE THREAD

**Issue by andloh** [go-gitea/gitea#6684] opened 2019-04-19 20:54 UTC
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ x] Not relevant
- Log gist:

## Description

Right to the case: 

k8s config: 

```
env:
        - name: DISABLE_SSH
          value: "true"
```

Inside gitea container: 

```
bash-4.4# env | grep SSH
GITEA_APP_SERVICE_PORT_SSH=22
DISABLE_SSH=true
```

But the value is still "false" in the app.ini and same with the web interface, ofc.

I have tried these env vars too: 

```
- name: DISABLE_REGISTRATION
          value: "true"
- name: REQUIRE_SIGNIN_VIEW
          value: "true"
```

...and those actually work. 

I know I can use a configmap to resolve this issue, but env vars is useful too, somtimes :) 

env ref: https://docs.gitea.io/en-us/install-with-docker/

**Comment by adelowo** [comment] 2019-04-27 10:51
This is a duplicate of https://github.com/go-gitea/gitea/issues/350

**Closed as completed** 2019-04-28 05:31 UTC
Labels: issue/duplicate
