### ISSUE TITLE
[Feature] Environment variables should take precedence over the configuration file

### ISSUE THREAD

**Issue by dannyhpy** [go-gitea/gitea#10563] opened 2020-03-02 01:01 UTC
## Description
This would be **really useful** for Docker users.
Currently, when you to change a specific setting, you need to edit the configuration file.

It would be more convenient to have the ability to change a setting from the command line especially for testing purposes (or from the `docker-compose.yml` file for Docker users)

For instance, this would allows you to change the domain pretty easily if you have a Raspberry Pi and want to move it temporary to an another location without having to change the config file.
```sh
SSH_DOMAIN=176.173.39.149 gitea web
```

(I don't think this is similar to any issue out there, but there are a lot of issues so if there is already an issue mentioning this, I'm sorry about that)

**Comment by techknowlogick** [comment] 2020-03-02 01:03
Closing as dupe of #10123

**Closed as completed by techknowlogick** 2020-03-02 01:03 UTC
Labels: issue/duplicate

**Comment by zeripath** [comment] 2020-03-02 21:19
There is a contrib command environment-from-ini
