### ISSUE TITLE
Can't execute gitea.exe on Windows in cmd.exe

### ISSUE THREAD

**Issue by crackedmind** [go-gitea/gitea#22063] opened 2022-12-07 18:26 UTC
### Description
```
>gitea-1.18.0-rc1-windows-4.0-amd64.exe --help
2022/12/07 23:15:28 ...s/setting/setting.go:516:1() [F] Failed to get app path: exec: "gitea.exe": cannot run executable found relative to current directory
```
From powershell it starts normally.

And it' working as expected in cmd.exe for 1.17.3

```
>gitea-1.17.3-windows-4.0-amd64.exe --help
NAME:
   Gitea - A painless self-hosted Git service
```

### Gitea Version

1.18-rc1

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Windows 11

### How are you running Gitea?

Official gitea-1.18.0-rc1-windows-4.0-amd64.exe

### Database

None

**Comment by eeyrjmr** [comment] 2022-12-07 18:32
Duplicate of #21943 

NOTE: it might have been premature to close the other issue as it just captures a "workaround" not the change in behaviour (or regression...)

**Comment by KazzmanK** [comment] 2022-12-07 20:14
but it still runs as windows service as previously.

**Comment by zeripath** [comment] 2022-12-07 20:55
I wonder if this would fix this?

```patch
diff --git a/modules/setting/setting.go b/modules/setting/setting.go
index f0d7f0292..6d99ffa0f 100644
--- a/modules/setting/setting.go
+++ b/modules/setting/setting.go
@@ -6,6 +6,7 @@ package setting
 
 import (
 	"encoding/base64"
+	"errors"
 	"fmt"
 	"math"
 	"net"
@@ -465,6 +466,13 @@ func getAppPath() (string, error) {
 		appPath, err = exec.LookPath(os.Args[0])
 	}
 
+	if err != nil {
+		if !errors.Is(err, exec.ErrDot) {
+			return "", err
+		}
+		appPath, err = os.Getwd()
+		appPath = filepath.Join(appPath, os.Args[0])
+	}
 	if err != nil {
 		return "", err
 	}

```

**Comment by zeripath** [comment] 2022-12-07 20:59
The trouble is I can't test this because I don't run windows.

**Comment by eeyrjmr** [comment] 2022-12-07 21:19
> The trouble is I can't test this because I don't run windows.

If I can figure out how to cross compile in Gentoo , I can test

**Comment by zeripath** [comment] 2022-12-07 21:21
`make release-windows`

**Comment by zeripath** [comment] 2022-12-08 21:39
ok so it looks like my patch does work!

Right I'll try to clean it up a bit and push it up as a fix.

**Closed as completed** 2022-12-14 06:15 UTC
Labels: type/bug
