### ISSUE TITLE
Ability to review multiple lines.

### ISSUE THREAD

**Issue by Midou36O** [go-gitea/gitea#21150] opened 2022-09-12 20:21 UTC
### Feature Description

It would have been nice if gitea had the ability to review multiple lines.

### Screenshots

Currently on gitea:
![Gitea](https://user-images.githubusercontent.com/45198486/189750820-b8314058-70f5-466f-8c78-28c30a754a6e.gif)
What it could have been (like GitHub):
![GitHub](https://user-images.githubusercontent.com/45198486/189751043-48d0f9da-c3a9-48c1-b3c8-967b6caa7239.gif)

**Comment by mtareqhosain** [comment] 2023-02-02 10:52
_no progress so far. But this could be a useful feature like GitHub._

**Comment by delvh** [comment] 2023-02-02 11:28
That's definitely on the plan.
There's simply no activity yet because no one took the time to implement it.

---

I've already gathered some implementation thoughts on this as I think GitHub's approach has some major drawbacks:
At the moment, we only gather one number `+/-$line` for a review comment, where `+` means on new and `-` means on old diff, and `$line` is the line number.

My proposal is to limit multi-line comments to one side: Either you mark multiple lines on the old side, or multiple lines on the new side, but no mixture in between.
Reasoning: You **very rarely** want a multi-line message that has both old and new content (speaking from my experience as a "serial reviewer"), and it has a couple of benefits:
- it is (at least for the backend) far easier to implement: Simply store another signed number meant as a relative counter:
  - Case 1 - `|x| = 0`: It's a single-line message, so use the current algorithm including the corresponding settings.
  - Case 2 - `|x| = 1`: Show **only** the selected line without the additional context lines. Can be useful from time to time to clarify exactly which line you're talking about, and GitHub doesn't offer this functionality. Should be the same case as case 3, but is listed here for completeness. 
  - Case 3 - `|x| > 1`: Show the next/last `x` lines, depending on the sign of `x`. Only show exactly the requested lines, and nothing more or less.
  - it might even make sense to switch the behavior of case 1 with the one of case 2 if an edge case can be avoided that way 
- it is far less error-prone (see i.e. GitHubs problems with suggestions)
- the (backend) implementation is straightforward, hence much easier to maintain
- it is a much better user experience (I always have to hope that GitHub interprets my dragging correctly which it often just… doesn't)

**Comment by jpraet** [comment] 2023-03-05 17:04
Duplicate of #12640.

**Closed as completed** 2023-03-06 04:14 UTC
Labels: issue/duplicate
