### ISSUE TITLE
Markdown callouts/attention blocks do not follow GitHub's behaviour with backslashes

### ISSUE THREAD

**Issue by UtkarshKunwar** [go-gitea/gitea#31214] opened 2024-06-01 19:23 UTC
### Description

GitHub's markdown attention blocks discussed in #28316 and introduced in v1.22.0 with #21711 do not follow the same behaviour when the square brackets are escaped with backslashes.

I noted this issue when the `mdformat` tool corrected the syntax by escaping the square brackets. GitHub was dealing with this just fine but Gitea failed in this situation.

### Gitea Version

v1.22.0

### Can you reproduce the bug on the Gitea demo site?

Yes

## Behaviour on GitHub
```markdown
> [!NOTE]
> testing note without backslash
```
> [!NOTE]
> testing note without backslash

---

```markdown
> \[!NOTE\]
> testing note with backslash
```
> \[!NOTE\]
> testing note with backslash

## Behaviour on Gitea
![image](https://github.com/go-gitea/gitea/assets/14164924/de12bbef-6f30-40ac-a0a4-7de30e9ffd52)

### How are you running Gitea?

Used <https://demo.gitea.com> as well as self-hosted `deb` package instance.

### Database

None

**Comment by yp05327** [comment] 2024-06-03 04:31
maybe related to #29121 ?

**Comment by yardenshoham** [comment] 2024-06-03 04:46
cc @wxiaoguang as he last touched this code

**Comment by wxiaoguang** [comment] 2024-06-03 05:07
> cc @wxiaoguang as he last touched this code

IIRC I didn't change the syntax for parsing, just kept the logic from #29121 :

https://github.com/go-gitea/gitea/pull/29121/files#diff-d78a9d361b1fddc12218e4dd42f42d39d6be1fda184041e06bb6fb30f0d94c59R199-R213

The new code still checks: `// > Text("[") Text("!TYPE") Text("]")`.

----

I think the problem is related to the "unescaping" behavior.

GitHub does the unescaping before parsing, so `> \[!NOTE\]` becomes `> [!NOTE]` first before parsing the attentions.

Gitea doesn't do unescaping, so it only sees `> \[!NOTE\]`, and it is not recognized at the moment.

IIRC there are not only one issues for the different unescaping behaviors between GitHub and Gitea. For this case, I think it could be simply fixed by adding more checks for `\[` and `\]` in code, and add a proper test.

**Comment by yardenshoham** [comment] 2024-06-03 18:27
- https://github.com/go-gitea/gitea/pull/31231

**Closed as completed** 2024-06-04 15:35 UTC
Labels: type/bug
