### ISSUE TITLE
Avatar is not scaled correctly

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#20970] opened 2022-08-26 23:33 UTC
### Description

The problem appears in the comments on the code, as shown:

### Screenshots

![20220827-072304](https://user-images.githubusercontent.com/76462613/187002441-05cb61c9-f11e-471d-ad88-1f6f648b01be.gif)

### Gitea Version

1.18.0+dev-346-g94549bcd1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Browser Version

Edge/104

**Comment by noerw** [comment] 2022-09-15 15:03
duplicate of https://github.com/go-gitea/gitea/issues/20074

**Closed as completed** 2022-09-15 15:04 UTC
Labels: type/bug, issue/duplicate, topic/ui
