### ISSUE TITLE
Wiki: links to pages with spaces not working anymore

### ISSUE THREAD

**Issue by PaulBINK** [go-gitea/gitea#12517] opened 2020-08-18 04:50 UTC
- Gitea version (or commit ref): 1.12.2
- Git version: -
- Operating system: Ubuntu AMD64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

We use a Home page in the wiki to link to all other pages we have there. It worked fine for a long time across many different versions of Gitea. When we visited the page again yesterday we noticed all those links didn't work anymore. I ran a simple test today in the test environment, and I see it's related to spaces in the name of the page. An example can be found here: [https://try.gitea.io/the_paul/WikiTest/wiki/Home](https://try.gitea.io/the_paul/WikiTest/wiki/Home)

The moment you add a space, the link is not recognized as such anymore. Replacing spaces with %20 does work.

We hadn't used the wiki for a while, so we have no idea when it stopped working.

**Comment by jolheiser** [comment] 2020-08-18 04:59
Duplicate of https://github.com/go-gitea/gitea/issues/10223

This is considered a feature of our markdown library in that it follows a defined spec.
Enclosing the link in <> should resolve the issue.

**Closed as completed by jolheiser** 2020-08-18 04:59 UTC
Labels: issue/not-a-bug
