### ISSUE TITLE
API does not return object_format_name

### ISSUE THREAD

**Issue by NicolasChusseau** [go-gitea/gitea#31287] opened 2024-06-07 10:08 UTC
### Description

When I try to create a new pull request using the api "/repos/{owner}/{repo}/pulls", the pr is correctly created but in the response, the attribute 'object_format_name' should be "sha1" or "sha256" but I have an empty string. 

### Gitea Version

1.22.0

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

Expected according to the swagger 1.22.0
![image](https://github.com/go-gitea/gitea/assets/122353423/ca828dac-2ff4-450c-9aec-99a515263cf0)
Actual on postman
![image](https://github.com/go-gitea/gitea/assets/122353423/8d470733-25d5-4c90-af4d-622368edbb1f)

### How are you running Gitea?

I was using postman.

### Database

None

**Comment by lunny** [comment] 2024-06-07 10:48
Duplicate of #31117

**Closed as completed by lunny** 2024-06-07 10:48 UTC
Labels: type/bug
