### ISSUE TITLE
Flicker in some parts of the compare page

### ISSUE THREAD

**Issue by A-UNDERSCORE-D** [go-gitea/gitea#7722] opened 2019-08-02 22:16 UTC
- Gitea version (or commit ref): 1.9.0
- Git version: 2.17.1
- Operating system: Ubuntu 18.04 (host machine same)
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
The diff stats and some other sections of the compare screen flicker during scrolling. Could not reproduce on try.gitea.io as it would appear I cant compare things there. Example used is at [my instance](https://git.ferricyanide.solutions/A_D/goGoGameBot/compare/master...de-irc)

## Screenshots

![test](https://user-images.githubusercontent.com/21071450/62401500-bf84b780-b583-11e9-96d5-753792cce7cb.gif)

**Comment by Ryuno-Ki** [comment] 2022-06-05 19:36
The domain ferricyanide.solutions is expired. Since the OP indicates, it isn't reproducible on try.gitea.io I suggest to close this issue.

**Closed as completed** 2022-06-06 03:38 UTC
Labels: topic/ui, issue/confirmed
