### ISSUE TITLE
Failed to sync push mirror repo when repo is mirror repo

### ISSUE THREAD

**Issue by hiifong** [go-gitea/gitea#26059] opened 2023-07-22 14:53 UTC
### Description

Mirror repo from github to self-hosted gitea, and then add a push mirror for this repo. When the sync button is clicked, Error is displayed, and the mouse is placed on `Error` to display `git cat-file --batch-check --batch-all-object [/data/gitea/data/gitea-repositories/mirrors/linux.git]: context deadline exceeded - `

```
git cat-file --batch-check --batch-all-object [/data/gitea/data/gitea-repositories/mirrors/linux.git]: context deadline exceeded - 
```
![image](https://github.com/go-gitea/gitea/assets/89133723/9af698d7-5a08-40ee-99f0-2fc708a41403)
```
View Notice Details
Jul 22, 2023, 10:38 PM GMT+8
Failed to update mirror repository '/data/gitea/data/gitea-repositories/mirrors/linux.git': fatal: Unable to create '/data/gitea/data/gitea-repositories/mirrors/linux.git/./objects/info/commit-graphs/commit-graph-chain.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```
![image](https://github.com/go-gitea/gitea/assets/89133723/d64f64a2-bffa-4b15-9d6c-abf8f24f0563)

### Gitea Version

v1.20+

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

./gitea web

### Database

MySQL

**Comment by hiifong** [comment] 2023-07-22 15:00
Maybe the repo is too big

**Comment by cassiozareck** [comment] 2023-07-22 21:13
Im not a maintainer neither a experienced Gitea contributor. But I'm trying to figure out what it may be. I found 2 reasons
1. By some reason gitea is spawning two git instances at same time in the same repository, creating this lock file that is giving the error
2. The time was exceeded. Do it last more than 5 minutes? If so probably it exceeded the timeout. If you're self-hosting gitea by yourself maybe you can try to extend this timeout in the mirror field of the Git structure under modules\setting\git.go

Its not clear for me what exactly what happen when timeout is exceeded but I'll search more

**Comment by lunny** [comment] 2024-06-13 14:21
Duplicate of #22578

**Closed as not planned by lunny** 2024-06-13 14:21 UTC
Labels: type/bug
