### ISSUE TITLE
Plans for Gitea 1.21

### ISSUE THREAD

**Issue by delvh** [go-gitea/gitea#25123] opened 2023-06-07 22:13 UTC
Hi all,

Gitea `v1.20.0-rc0` has been released.
We have created the `release/v1.20` branch accompanied by the `v1.21.0-dev` tag and are now using `main` for `1.21` development.
As always, this issue is intended to show what you can expect from the next version.

## Schedule

Gitea `1.21` is currently set to enter feature freeze on <time datetime="2023-09-03 23:59+00:00">2023-09-03 23:59 UTC</time>, so in the beginning of september.
This deadline is at the moment only a rough estimate and might change in the future.

<details><summary><h2>Previous Plans</h2></summary>

- #23072
- #21598 
- #20022
- #18345
- #16429
- #14477
</details>

## :warning: Important

This summary is for things you **plan to implement yourself**, not things you want (from other people).
Wishes and other offtopic comments will be hidden.

**Comment by delvh** [comment] 2023-06-07 22:17
I'll start with my plans:
- [x] Reviewing  **a lot** of PRs ([as always](https://github.com/go-gitea/gitea/pulls?q=is%3Apr+reviewed-by%3Adelvh+milestone%3A1.20.0+))
- [ ] Merging the separate project templates together
- [ ] Display branches and tags a commit appears in (issue does not yet exist)

<details><summary>somewhere on the back of my TODO list</summary>

- [ ] #23203
- [ ] #20126
- [ ] #12640
</details>

**Comment by wfjake** [comment] 2023-06-08 01:01
I'm pretty new to the codebase but I'm going to try my hand at implementing:
- [ ] #5512 using the [russellhaering/gosaml2](https://github.com/russellhaering/gosaml2) library

**Comment by oetiker** [comment] 2023-06-09 07:59
@silverwind it was mentioned before, but switching to svelte, combined with tailwind might be a great way forward

**Comment by wolfogre** [comment] 2023-06-13 07:51
- [ ] #24662
  - [ ] #25174
- [ ] #24603
- [ ] #24543

<details>
<summary>Backlog</summary>

- Take over `https://github.com/go-gitea/gitea/pull/18165`

</details>

**Comment by HesterG** [comment] 2023-06-13 08:34
- Finish the dropdowns in action list https://github.com/go-gitea/gitea/issues/25042
- Fix more issues like https://github.com/go-gitea/gitea/issues/25096 (change the form actions to form fetch to avoid duplicate requests)
- https://github.com/go-gitea/gitea/issues/24593
- Fix more frontend inconsistency

**Comment by sillyguodong** [comment] 2023-06-13 09:13
- [ ] https://github.com/go-gitea/gitea/pull/24806
- [ ] https://github.com/go-gitea/gitea/pull/24724
- [ ] https://github.com/go-gitea/gitea/pull/25199
- [ ] Refactor https://github.com/go-gitea/gitea/pull/23522
- [ ] https://gitea.com/gitea/act_runner/issues/232

**Comment by lunny** [comment] 2023-06-20 12:27
I will work on
- [ ] #25206
- [ ] #25071
- [ ] #22743
- [ ] #20549

**Comment by delvh** [comment] 2023-06-20 17:24
Off-topic, but:
What exactly do you mean by `hard-reset to specific commit`? Commit Reverting, or really a `reset --force`?
Because I'm rather against a `reset --force` and more in favor of reverting.
Otherwise, there's too much error potential.
Anyway, I think all this discussion should be outsourced into a new issue. We shouldn't discuss these things here.

**Comment by denyskon** [comment] 2023-06-20 18:03
> Off-topic, but:
> What exactly do you mean by `hard-reset to specific commit`? Commit Reverting, or really a `reset --force`?
> Because I'm rather against a `reset --force` and more in favor of reverting.
> Otherwise, there's too much error potential.
> Anyway, I think all this discussion should be outsourced into a new issue. We shouldn't discuss these things here.

I'm talking about `git reset --hard SHA`, which just removes all commits after SHA.
Of course it's on the maintainers to decide about it. My use case is to remove the changes caused by multiple commits, so if the decision is made not to allow reset, I could also try to extend the existing revert mechanism to revert multiple commits.
But as you said, this should be moved out to a separate issue.

**Comment by prologic** [comment] 2023-06-24 00:14
> I'm pretty new to the codebase but I'm going to try my hand at implementing:
> 
> * [ ]  [Support SAML 2.0 as Login-Source (Service Provider) #5512](https://github.com/go-gitea/gitea/issues/5512) using the [russellhaering/gosaml2](https://github.com/russellhaering/gosaml2) library
>   
>   * [ ]  [Enable configuration of SAML authentication sources (#5512) #25132](https://github.com/go-gitea/gitea/pull/25132)
>   * [ ]  (future patch(s) adding actual logic behind SAML authentication)

Please let me know if this is inappropriate to comment/contribute...

Could we look at implementing Trusted Header / Proxy Auth first? That way some folks can very easily and cheaply implement SSO with things like Authelia

**Comment by techknowlogick** [comment] 2023-06-24 01:40
@prologic that is already possible. search for reverse_proxy_auth in the cheat sheet and that'll be a starting point that works.

**Comment by ivancxj** [comment] 2023-07-04 01:56
Enhance issues and project management
Make Gitea A one-stop collaboration platform for development，Full Lifecycle Support of Team Collaboration and Product Development，like https://www.tapd.cn

**Comment by editfund-founder** [comment] 2023-07-08 12:13
https://primer.style/css/

**Comment by puni9869** [comment] 2023-08-26 13:05
I am currently working on
* [ ] `WIP` Feature https://github.com/go-gitea/gitea/issues/25237
* [ ] Feature https://github.com/go-gitea/gitea/pull/26151
* [ ] https://github.com/go-gitea/gitea/pull/26212
* [ ] More pr review
* [ ] Fix mobile view ports.

**Comment by denyskon** [comment] 2023-09-22 14:31
Closing as 1.21rc0 released, replaced by #27194 :)

**Closed as completed by denyskon** 2023-09-22 14:31 UTC
Labels: type/summary
