### ISSUE TITLE
Wrong count of issues in milestones

### ISSUE THREAD

**Issue by mmarif4u** [go-gitea/gitea#8190] opened 2019-09-15 16:07 UTC
Gitea ver : 8b54b58 on gitea.com

Just noticed that milestone count and graph showing wrong open issues. This mostly happens when change ms of issues.

![ms](https://user-images.githubusercontent.com/1280585/64924323-9f8c1900-d7fc-11e9-8bfb-49fb44aa70ae.png)

cc @lunny

**Comment by mmarif4u** [comment] 2019-09-16 06:17
Sorry, i wrongly mentioned Gitea ver. It is happening on gitea.com which has 1.10-dev(8b54b58).

**Comment by 6543** [comment] 2019-09-17 14:45
Noticet it yesterday too!
-4 are open? I think it has somehow to do wich a count funktion

**Comment by mmarif4u** [comment] 2019-09-17 16:06
Just noticed, this happens on labels page also.

![label](https://user-images.githubusercontent.com/1280585/65059153-eb6ec780-d98e-11e9-8410-9b68ec284e1f.png)

**Comment by lunny** [comment] 2019-09-18 03:02
@mmarif4u label's wrong number should be another issue.

**Comment by 6543** [comment] 2019-09-30 18:50
it hapens again!
https://gitea.com/mmarif/GitNex/milestones

Gitea Version  1.10.0+dev-289-g8b54b58bc

**Comment by manuelmohr** [comment] 2019-10-03 14:02
Duplicate of #8069.

Thanks for fixing!

**Closed as completed** 2019-10-05 06:22 UTC
Labels: type/bug, issue/duplicate
