### ISSUE TITLE
[Feature Request] When creating PRs, reload diffs in background

### ISSUE THREAD

**Issue by nils91** [go-gitea/gitea#16159] opened 2021-06-15 08:51 UTC
## Description

When creating a new pull request using the UI, Gitea will reload the page every time when the selected branch(es) are changed through the dropdowns to display the diff (and relevant commits) between those 2 branches. That can take time, especially for large diffs. During that time, seemingly nothing happens. 
It would probably be better if Gitea would reload the diff in background and display a simple loading animation to the user until the diff is ready.

## Screenshots

![pr](https://user-images.githubusercontent.com/7298243/122022746-30739800-cdc7-11eb-974f-ff3819d78eef.gif)
On the screengrab it doesn´t look so bad, but for larger diffs that can take several minutes. The screengrab is from try.gitea.io ( [https://try.gitea.io/nils91/test](https://try.gitea.io/nils91/test) ).

**Comment by jpraet** [comment] 2021-06-15 16:57
Duplicate of #13949

**Closed as completed** 2021-06-15 19:42 UTC
Labels: type/proposal, performance/speed
