### ISSUE TITLE
Git for Windows 2.41.0 stuck on push with gitea 1.19.3

### ISSUE THREAD

**Issue by MaxWaldorf** [go-gitea/gitea#25067] opened 2023-06-04 09:01 UTC
### Description

With the latest git package, the push doesn't work anymore and stay stuck for ever at TOTAL xxxx.

Reverting to 2.40.1 solves the issue

### Gitea Version

1.19.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

official dockerfile 1.19.3

### Operating System

Linux

### How are you running Gitea?

Official Dockerfile 1.19.3

### Database

PostgreSQL

**Comment by lunny** [comment] 2023-06-04 09:04
Linux or Windows?

**Comment by MaxWaldorf** [comment] 2023-06-04 09:16
windows client
linux server

**Comment by eeyrjmr** [comment] 2023-06-04 10:41
This isn't related to git version

On my gentoo desktop
`
git -v
git version 2.41.0
`

My alpine headless: 
`
apk info gitea

gitea-1.19.3-r0 installed size:
138 MiB
`


So this could being git-for-win v2.41.0. I can book my work machine and upgrade git-for-win (it is  v2.39.x) and see if the issue exists as : win-git-2.41 -> linux-gitea-1.19

**Comment by MaxWaldorf** [comment] 2023-06-04 10:56
Bear in mind that I am using the container provided by gitea.

There might be a matching git issue between server and client...

**Comment by eeyrjmr** [comment] 2023-06-04 11:00
> Bear in mind that I am using the container provided by gitea.
> 
> There might be a matching git issue between server and client...

There shouldn't be. git is actually quite stable in terms of ABI with regards to data interchange 

my alpine headless (running gitea-1.19.3) is also using git-2.40.1-r0.     My gentoo desktop is using git-2.41 

There might be a "bug" in git-for-win-2.41 and I can independently check shortly

**Comment by eeyrjmr** [comment] 2023-06-12 09:52
Apologies for the delay...

Upgraded git-for-windows to 2.41.0 and cloning/pushing to to Gitea-1.19.3 

```

 git -v
git version 2.41.0.windows.1
```


Something else is going on here.

**Comment by wxiaoguang** [comment] 2023-07-09 11:34
I am pretty sure the "stuck" is caused by incorrect log messages during startup.

It should have been fixed in 1.20/1.21

Feel free to reopen if there is still a problem

**Comment by MaxWaldorf** [comment] 2023-07-13 22:05
Sorry but 2.41.0.2 did not help either...

Works well with github... not with gitea... Happy to help, but don't know how to debug right now.

**Comment by MaxWaldorf** [comment] 2024-01-10 14:44
No issues here anymore...

**Comment by lunny** [comment] 2024-01-10 16:09
> No issues here anymore...

How did you resolve the problem?

**Comment by MaxWaldorf** [comment] 2024-01-10 16:52
The lastest git exe on windows and 1.21.x work so far

**Closed as completed** 2024-01-10 17:14 UTC
Labels: type/bug
