### ISSUE TITLE
I hope to add multiple directories under the organization directory to group warehouses

### ISSUE THREAD

**Issue by meng-plus** [go-gitea/gitea#30695] opened 2024-04-25 02:33 UTC
### Feature Description

like it   https://jihulab.com/zhiyun-studio
This way, I can easily manage all the resources of the entire project
Software, hardware, drawings, manuals, etc. should be managed separately

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/37764731/df538fce-7904-4b1b-825e-d5d651d40db9)
![8f1f9d12493aea53583c2fd74511426c](https://github.com/go-gitea/gitea/assets/37764731/2065d843-9d61-4cde-a567-0fb676e1ec60)

**Comment by techknowlogick** [comment] 2024-04-25 03:18
closing as duplicate of https://github.com/go-gitea/gitea/issues/1872

**Closed as completed by techknowlogick** 2024-04-25 03:18 UTC
Labels: type/proposal
