### ISSUE TITLE
Deleting an org avatar breaks the image

### ISSUE THREAD

**Issue by tboerger** [go-gitea/gitea#2073] opened 2017-06-28 08:54 UTC
- Gitea version (or commit ref): 1.1.2
- Git version: n/a
- Operating system: docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL): https://try.gitea.io/foobar
  - [ ] No
  - [ ] Not relevant
- Log gist: n/a

## Description

I have uploaded a custom avatar for my organization, afterwards I have deleted it again and than the org avatar is broken. No page is loading any avatar anymore. I would expect that I get an auto-generated Gravatar image again.

## Screenshots

![bildschirmfoto 2017-06-28 um 10 46 35](https://user-images.githubusercontent.com/156964/27628641-fb7a10d6-5bef-11e7-9c68-236c447f75c3.png)

**Comment by lunny** [comment] 2017-06-28 08:57
This bug maybe reproduced on master?

**Comment by ethantkoenig** [comment] 2017-06-29 14:33
Also, after the avatar breaks, the `GET /orgs/:orgname` API endpoint for the organization gives a 500.

I'm guessing this is because `org.RelAvatarLink()` is returning an empty string, so there is an out-of-index error at https://github.com/go-gitea/gitea/blob/master/models/user.go#L361

**Comment by tboerger** [comment] 2017-06-29 14:40
@lunny try.gitea.io is based on master.

**Comment by lunny** [comment] 2017-06-29 14:52
So let's mark it as v1.2 and back port to v1.1.3

**Comment by ethantkoenig** [comment] 2017-07-02 18:17
@tboerger @lunny Fixed? (see https://try.gitea.io/foobar)

**Comment by lunny** [comment] 2017-07-03 00:52
@ethantkoenig @tboerger seems yes.

**Comment by lunny** [comment] 2017-07-11 01:26
@ethantkoenig please backport to v1.1

**Comment by lunny** [comment] 2017-07-11 01:27
closed by #2083

**Closed as completed by lunny** 2017-07-11 01:27 UTC
Labels: type/bug
