### ISSUE TITLE
Failed to initialize issue indexer: invalid argument -- will not install

### ISSUE THREAD

**Issue by brandonkal** [go-gitea/gitea#8566] opened 2019-10-17 22:04 UTC
- Gitea version (or commit ref): gitea/gitea:1.9.4-linux-amd64 (also an issue on gitea:latest)
- Git version: 2.17.1
- Operating system: Kubernetes
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

https://gist.github.com/brandonkal/299fa99968e5939633c825045a33cffe

## Description

This error occurs when the PV is on a specific mounted drive that is a folder shared with the Kubernetes host (Ubuntu 18.04 KVM with microk8s). The logged error is not descriptive enough to conclude it is a permissions issue. From the host, it is clear the files are created in the mounted location without issue.

**Comment by guillep2k** [comment] 2019-11-13 02:07
@brandonkal One user at Discord had the same problem. It turned out that Gitea was running in a virtual box shared folder; running Gitea on a non-shared folder solved his issue. Please check if anything similar might be happening to you.

**Comment by brandonkal** [comment] 2019-11-13 02:45
It's just vanilla micork8s on Ubuntu 18.04 with Racher's local path provisioner.

As stated, the bug here is that the error is not descriptive of whatever disk IO issue Gitea is having.

It was an NFS or SMB mounted volume backing the PV. I know vagrant/virtual box uses network shares for shared volumes. So it could be a similar Gitea bug.

**Comment by lunny** [comment] 2019-11-13 04:36
Please notice, indxer folder cannot be shared by multiple gitea instance.

**Comment by zeripath** [comment] 2019-11-13 07:11
So @brandonkal the invalid argument is the error that comes out of bleve - it doesn't appear to tell us anything more than that.

I agree it is opaque to the extreme but unless anyone can find a way of getting bleve to tell us what the problem is, that's what we're stuck with.

**Comment by brandonkal** [comment] 2020-01-12 20:32
See you next month bot. #notstale

**Comment by MattDahEpic** [comment] 2020-02-24 06:06
This also occurs when the work directory is on a 9p virtio mount.

**Comment by Kramins** [comment] 2020-12-16 02:31
I am also having this problem on microk8s and my data volume is on a 9p virtio mount as @MattDahEpic mentioned.

Are there any known workarounds  that would allow me to keep my data volume mounted over 9p?

**Comment by lunny** [comment] 2020-12-17 15:55
For most Gitea instances, `db` is enough.

**Comment by aaronjwood** [comment] 2021-01-02 01:38
I second this issue when using a 9p mount via kvm/qemu. Changing the indexer type to `db` fixes it. I don't have much context on Bleve indexer, does anyone know why it would break under a specific mount type? I've had Gitea working with NFS before, I figured things would have broken there first...

**Comment by aaronjwood** [comment] 2021-01-02 01:43
I'm guessing this has something to do with mmap being used and it not working across the boundary of a hypervisor...?

**Comment by aaronjwood** [comment] 2021-01-02 01:53
Yeah, you need to add `cache=mmap` mount option for this to work, unless you want to switch over to `db`. I had to do this to get Plex to work which is also using a 9p mount (and sqlite internally) so I decided to just apply `cache=mmap` to my setup.

**Comment by lunny** [comment] 2021-01-02 02:19
@aaronjwood Thanks for the clarify.

I will summary something here for the three issue indexer types, `bleve`, `db` and `elasticsearch`. BTW: For code indexer types, there are only `bleve` and `elasticsearch`.

- `bleve` is the default currently and it's only suitable for single Gitea instance and don't share the indexer data with other programs. A local filesystem is recommended.
- `db` is low efficient which use database's indexer feature. This is only for issue indexer.
- `elasticsearch` will use an elasticsearch  instance or cluster to do index and search.

**Comment by safag05** [comment] 2021-06-14 14:08
I am trying to change my repo indexer to elasticsearch however Gitea tries to restart over and over again. On the logs I see this: `Error: health check timeout: no Elasticsearch node available` Do I need to set up Elastic Search node separately from Gitea in order to use? Isn't just enabling `REPO_INDEXER_TYPE = elasticsearch` not sufficient?

**Comment by lunny** [comment] 2021-06-14 14:51
see https://docs.gitea.io/en-us/config-cheat-sheet/#indexer-indexer

**Comment by safag05** [comment] 2021-06-14 15:02
Thanks for sharing that @lunny I have been looking into that already but I am noob on this indexer. I have the following in my app.ini and it is failing
`REPO_INDEXER_ENABLED = true
REPO_INDEXER_TYPE = elasticsearch
REPO_INDEXER_PATH: indexers/repos.elasticsearch`

I see that there is a config for `REPO_INDEXER_CONN_STR` is that something that I need to configure as well? It has an example of `http://elastic:changeme@localhost:9200` but not sure where to get such URL from.

**Comment by lunny** [comment] 2021-06-15 09:09
When `REPO_INDEXER_TYPE = elasticsearch`, you should use `REPO_INDEXER_CONN_STR`

**Comment by safag05** [comment] 2021-06-15 12:10
Sorry just to clarify as I am noob with this. In order to use `REPO_INDEXER_CONN_STR` I would need elastic search up and running right? And will need to use it's URL to connect it to Gitea via `REPO_INDEXER_CONN_STR`?

**Comment by lunny** [comment] 2021-10-21 12:09
See https://docs.gitea.io/en-us/config-cheat-sheet/#indexer-indexer. I will close this issue currently because it's upstream related and there are some workrounds.

**Closed as completed by lunny** 2021-10-21 12:09 UTC
Labels: type/question, issue/confirmed
