### ISSUE TITLE
TeamCity Webhooks

### ISSUE THREAD

**Issue by firephreek** [go-gitea/gitea#18667] opened 2022-02-08 07:15 UTC
Gitea has webhooks for a variety of platforms including MSTeams, Discord, Slack, and others. Unfortunately, TeamCity is not amongst them.  I'd like to fix that.

Notes: 
- TeamCity has a single end point used for triggering VCS builds. 
- End point takes a POST request with no body
- An "Authorization: Bearer <token>" header is required.
    - Addressing this by adding a BearerToken property to HookTask. When the actual request is built, the property is checked and if it has a value, the header will be added.
 
- TeamCity REST API: https://www.jetbrains.com/help/teamcity/rest-api.html
- TeamCity REST API Reference: https://www.jetbrains.com/help/teamcity/rest-api-reference.html

**Comment by firephreek** [comment] 2022-02-09 02:45
Work for this feature is in PR #18668 
https://github.com/go-gitea/gitea/pull/18668

**Comment by techknowlogick** [comment] 2022-11-07 15:42
closing as dupe of https://github.com/go-gitea/gitea/issues/1089

**Closed as completed by techknowlogick** 2022-11-07 15:42 UTC
Labels: type/feature, topic/webhooks
