### ISSUE TITLE
Docker instance always using CPU

### ISSUE THREAD

**Issue by binarydad** [go-gitea/gitea#16611] opened 2021-08-03 13:08 UTC
- Gitea version (or commit ref): 1.14.5
- Operating system: Ubuntu 18 on latest Docker instance
- Not sure the DB, whatever was installed with Docker
- No logs seem out of place, besides standard HTTP requests

## Description
The instance works fine, and doesn't seem sluggish, but I've noticed there is ALWAYS CPU activity. The Ubuntu host shows the `gitea` instance at around 4-6%. The docker container stats show it's higher, of course. Still, it's constant. 

What is causing this constant CPU usage? Thanks.

Host process CPU:
![image](https://user-images.githubusercontent.com/1760607/128020806-300a4fe3-0fea-4e62-bae3-532f7e8de369.png)

Docker stats (Portainer):
![image](https://user-images.githubusercontent.com/1760607/128020578-a18f103b-3bb0-478f-ba88-a685e30d3ad6.png)

**Comment by zeripath** [comment] 2021-08-03 13:15
Please try 1.15.0-RC2.

**Comment by binarydad** [comment] 2021-08-03 13:18
> 
> 
> Please try 1.15.0-RC2.

Got it. I came across this (https://github.com/go-gitea/gitea/issues/15542) after posting, and noticed your comments about this change in 1.15. I'll just wait for the RTM. Thank you!

**Comment by zeripath** [comment] 2021-08-03 13:19
Why wait?

If no-one tests the RCs - they're not getting released.

**Comment by zeripath** [comment] 2021-08-03 13:27
Anyway I'll mark this as a duplicate of #15542

**Closed as completed by zeripath** 2021-08-03 13:27 UTC
Labels: issue/duplicate
