### ISSUE TITLE
Sync fork

### ISSUE THREAD

**Issue by hiifong** [go-gitea/gitea#23423] opened 2023-03-11 13:26 UTC
### Feature Description

like github sync fork

### Screenshots

![image](https://user-images.githubusercontent.com/89133723/224487294-0d2c89e6-10ae-45f3-acf5-076f7035c38b.png)

**Comment by manuelkamp** [comment] 2023-04-16 17:07
is there a manual way to sync a fork until this gets implemented?

**Comment by ykong1337** [comment] 2023-04-19 06:33
> is there a manual way to sync a fork until this gets implemented?

(github docs)[https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork#syncing-a-fork-branch-from-the-command-line]

**Comment by jonathanspw** [comment] 2023-12-14 18:27
+1

**Comment by wolftune** [comment] 2024-11-26 19:37
this is a duplicate of https://github.com/go-gitea/gitea/issues/20880

**Closed as not planned** 2024-11-26 20:14 UTC
Labels: issue/duplicate, type/proposal, type/feature
