### ISSUE TITLE
Pinned Issues

### ISSUE THREAD

**Issue by davidmayr** [go-gitea/gitea#12077] opened 2020-06-27 23:54 UTC
## Description

Everything should be explained in the Title.
I haven't found it in my Gitea instance so I will request it here.
It should be like the Pinned Issue "Discussion of Gitea roadmap" on this repository.

**Comment by a1012112796** [comment] 2020-06-28 16:47
Add example view on github:
![image](https://user-images.githubusercontent.com/25342410/85953257-a8239980-b9a1-11ea-8511-03187cc9db0b.png)

![image](https://user-images.githubusercontent.com/25342410/85953295-f9cc2400-b9a1-11ea-8e03-e5e2bf57fed7.png)


Maybe can use card module in semantic ui to do it, ref:
https://semantic-ui.com/views/card.html

**Comment by septatrix** [comment] 2021-02-13 14:22
Duplicate of #2175

**Comment by 6543** [comment] 2021-02-13 16:33
@septatrix thanks for finding it!

**Closed as completed by 6543** 2021-02-13 16:33 UTC
Labels: type/proposal
