### ISSUE TITLE
Gitea does not clean up old reverences on branch delete

### ISSUE THREAD

**Issue by Tchoupinax** [go-gitea/gitea#9201] opened 2019-11-28 20:55 UTC
- Gitea version (or commit ref): 1.10.0
- Git version: Docker image
- Operating system: Docker image
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No (On try.gitea.io, deleted branches are not kept)
  - [ ] Not relevant
- Log gist:

## Description

Hello,

Following a Discord discussion, i create this issue about deleted branches. Sometimes i meet issues when i delete my `develop` branch and repush an other branch also named `develop`.

My global issue : 
```
I explain my situation :
I work on master and develop, and sometimes i squash develop on master, delete develop and create it again from master.
I squashed and merged with gitea, deleted branch from UI.
In local, i created develop from master. And when i pushed it on gitea, i saw in branch overview that my develop branch kept the tag "merged #4"
```

When i want to show branches : 
```
template: repo/branch/list:22:106: executing "repo/branch/list" at <.Commit.ID.String>: nil pointer evaluating *git.Commit.ID
```
@6543 advises me to create this issue to collect data and scenario about this problem. I think there is a "global" issue when you delete and recreate same naming branch.

I can not reproduce the issue on try.gitea.io, deleted branches are not kept... It is because of the public instance or the 1.11 version ? 

Update will coming :)

**Comment by 6543** [comment] 2019-11-28 20:56
@Tchoupinax :+1:

**Comment by Tchoupinax** [comment] 2019-12-20 21:57
![image](https://user-images.githubusercontent.com/9136206/71295375-eb120e00-237b-11ea-9776-a00923f3c1e8.png)

Example 1 : i merged develop into master, i removed develop, i created develop in local and push it to gitea... but new develop branch has a reference to the PR that concerns the old branch.

**Comment by Tchoupinax** [comment] 2020-01-04 15:26
Hello,

I installed the milestone 1.10.2 that should fix this problem but it appears that nothing has changed for it (or i do not understand).

![image](https://user-images.githubusercontent.com/9136206/71767600-1107e880-2f0e-11ea-8e33-26598e2d3a9f.png)

Once again i will describe my issue :

I have two branches, master and develop. I push some code on my develop branch, create a pull request and merge it into master (with "squash and merge" option). Once it's done, i remove the develop branch with gitea (branch > trash icon). Branch is marked as deleted by me.

In local, i follow theses steps:
- Checkout master
- Pull
- Delete develop branch
- Create develop branch from master
- Push develop

And when i have done this, Gitea keeps a reference on the pull request that have been merged (as you can see on the screenshot).

Is it the expected behaviour by the patched milestone ?
Regards,

**Comment by 6543** [comment] 2020-01-04 18:32
@Tchoupinax can you reopen this issue?

**Comment by Tchoupinax** [comment] 2020-01-05 11:49
I can't. :/
Let's an Gitea member reopens this please :)

**Comment by 6543** [comment] 2020-01-05 12:09
@techknowlogick ⬆️ ?

**Comment by 6543** [comment] 2020-01-05 12:10
@techknowlogick ⬆️ ?

**Comment by zeripath** [comment] 2020-01-05 12:58
I've reopened but I still don't understand the problem - probably because I've not read the issue completely.

**Comment by 6543** [comment] 2020-01-05 13:16
@Tchoupinax if you do it this way:
1. merge Dev branch to master
2. Delete
3. creat new Dev branch localy
4. **add at leas 1 new commit**
5. push

is it still referenced?

**Comment by 6543** [comment] 2020-01-05 13:26
@zeripath I can confirm the bug:

if you merge a branch into master, delete the branch and add a new branch **with the same name** gitea think it is the same branch and on the **repo-branch-view** the old PR is reverenced

This happen because gitea determine the source branch of a PR by repo and branch **name**

To fix this the **repo-branch-view** only should show merged with reference if merged_commit_id or one of the merged_commit_id.parent (should only exist two) is equal with commitID of the current branch

**Comment by 6543** [comment] 2020-01-05 13:27
Dont know what the correct title of THIS issue should look like ...

**Comment by Tchoupinax** [comment] 2020-01-05 14:12
@6543 Thank you for reproducing and confirming the bug ;)

**Comment by zeripath** [comment] 2020-01-05 20:56
Ah I've been able to repeat this on the branches view.

I've fixed another issue - if the branch has moved on from the MergeCommitID we shouldn't offer to delete it either.

**Comment by zeripath** [comment] 2020-01-05 21:20
The problem here is that the MergeCommitID isn't the actual head - I need to use a different ID...

**Comment by zeripath** [comment] 2020-01-05 21:48
OK I've come up with a solution but it's very inefficient and it needs to be improved.

The branches page likely needs some pagination too.

**Comment by 6543** [comment] 2020-01-05 23:50
@lunny wrong milestone, schould we create 1.10.3?

**Comment by 6543** [comment] 2020-01-06 01:04
@lafriks can you move this to 1.10.3 pleace

**Closed as completed** 2020-01-07 17:06 UTC
Labels: type/bug
