### ISSUE TITLE
Incurrect ui in creating projects page

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#22901] opened 2023-02-14 04:28 UTC
### Description
`Create Project` is incurrect in some special size of the browser
![image](https://user-images.githubusercontent.com/18380374/218639314-2762b95a-c1d2-44fa-8e36-e943b67d5335.png)

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

build

### Database

None

**Comment by wxiaoguang** [comment] 2023-02-14 06:38
Do you mean the incorrect height? If yes, I guess it's related to #22883 and fixed by #22885

**Comment by wxiaoguang** [comment] 2023-02-14 06:56
Oh sorry, the problem isn't fixed. I will take a look at it.

**Closed as completed** 2023-02-14 13:04 UTC
Labels: type/bug
