### ISSUE TITLE
Synchronize push mirror on push

### ISSUE THREAD

**Issue by culmat** [go-gitea/gitea#18220] opened 2022-01-09 08:04 UTC
### Feature Description

Allow a [push mirror](https://docs.gitea.io/en-us/repo-mirror/#pushing-to-a-remote-repository) to synchronize on the _push event_ like a [web hook](https://docs.gitea.io/en-us/webhooks/). 
Make this the default behavior?

see also #18175
this would also provide a work around for  #13539,  as it would allow to trigger github actions on a mirror timely.

**Comment by zeripath** [comment] 2022-01-15 23:14
I think you're really asking for an API that would cause a push mirror to sync.

Now the issue here is who that API should be available and how often it can be called.

**Comment by kodermho** [comment] 2022-02-02 16:10
Seems similar to #16579

**Comment by guiohm** [comment] 2022-04-09 00:58
I'm coming from Bitbucket and I was using this plugin: https://github.com/ef-labs/stash-hook-mirror/wiki
It pushes without any delay and is very convenient.

**Comment by harryzcy** [comment] 2022-04-14 05:49
> I think you're really asking for an API that would cause a push mirror to sync.
> 
> Now the issue here is who that API should be available and how often it can be called.

I think this feature request means Gitea sync the repo with the "push mirror" every time new commits are pushed to Gitea, rather than syncing on scheduled intervals. So it's not a public API.

**Comment by jotoho** [comment] 2022-07-14 19:21
> I think this feature request means Gitea sync the repo with the "push mirror" every time new commits are pushed to Gitea, rather than syncing on scheduled intervals. So it's not a public API.

If this interpretation is correct, I suspect that this issue is a duplicate of my issue #16579.

**Comment by harryzcy** [comment] 2022-07-14 19:40
I believe this issue is resolved as #19411 has been merged

**Closed as completed** 2022-10-17 15:51 UTC
Labels: type/proposal, type/feature
