### ISSUE TITLE
Wrong image references in wiki

### ISSUE THREAD

**Issue by Lonerider2010** [go-gitea/gitea#11986] opened 2020-06-19 21:57 UTC
- Gitea version (or commit ref): 1.10.1
- Git version: 2.20.1
- Operating system: Raspbian GNU/Linux 10 (buster)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No                (see https://try.gitea.io/Lonerider2010/Test_Wiki/wiki)
  - [ ] Not relevant

## Description

When I mirrored the QMapShack github repository (https://github.com/Maproom/qmapshack), the wiki was also mirrored.
In contrast to the working wiki on github (and also working try gitea test wiki, see above), my local gitea repository 
does not show the included images. Whereas the image links in the .md files refer to the images directory, my local
mirror changes these links from "images/..." to "raw/images/...". As there is no raw directory, the images are not shown.

## Screenshots

Working image references:
![working-refs](https://user-images.githubusercontent.com/4317444/85181957-95191700-b287-11ea-96c6-0983c0041eb8.png)

Not working image references:
![not-working-refs](https://user-images.githubusercontent.com/4317444/85181986-ab26d780-b287-11ea-9618-2302f2e99178.png)

What is wrong with my local gitea server?

**Comment by mrsdizzie** [comment] 2020-06-19 22:20
This is fixed in 1.12 version which is why you can't reproduce on try. you'd need to update and it should display right after

**Closed as completed** 2020-06-19 22:47 UTC

**Comment by Lonerider2010** [comment] 2020-06-20 03:50
Thank you for this hint.
