### ISSUE TITLE
repo/header:53:150: executing "repo/header" at <EscapePound>: invalid value; expected string

### ISSUE THREAD

**Issue by Alir3z4** [go-gitea/gitea#7663] opened 2019-07-29 13:33 UTC
- Gitea version (or commit ref): 1.9.0+rc2-16-gd789170e3 built with GNU Make 4.1, go1.12.7 : bindata, sqlite, sqlite_unlock_notify
- Git version: 2.7.4
- Operating system:  Ubuntu 16.04 LTS
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

```
2019/07/29 13:27:33 .../xorm/session_get.go:99:nocacheGet() [I] [SQL] SELECT "id", "lower_name", "name", "full_name", "email", "keep_email_private", "passwd", "must_change_password", "login_type", "login_source", "login_name", "type", "location", "website", "rands", "salt", "language", "description", "created_unix", "updated_unix", "last_login_unix", "last_repo_visibility", "max_repo_creation", "is_active", "is_admin", "allow_git_hook", "allow_import_local", "allow_create_organization", "prohibit_login", "avatar", "avatar_email", "use_custom_avatar", "num_followers", "num_following", "num_stars", "num_repos", "num_teams", "num_members", "visibility", "diff_view_style", "theme" FROM "user" WHERE "id"=$1 LIMIT 1 []interface {}{1}
2019/07/29 13:27:33 .../xorm/session_raw.go:87:queryRow() [I] [SQL] SELECT count(*) FROM "notification" WHERE (user_id = $1) AND (status = $2) []interface {}{1, 0x1}
2019/07/29 13:27:33 .../xorm/session_get.go:99:nocacheGet() [I] [SQL] SELECT "id", "owner_id", "lower_name", "name", "description", "website", "default_branch", "num_watches", "num_stars", "num_forks", "num_issues", "num_closed_issues", "num_pulls", "num_closed_pulls", "num_milestones", "num_closed_milestones", "is_private", "is_empty", "is_archived", "is_mirror", "is_fork", "fork_id", "size", "is_fsck_enabled", "close_issues_via_commit_in_any_branch", "topics", "avatar", "created_unix", "updated_unix" FROM "repository" WHERE "owner_id"=$1 AND "lower_name"=$2 LIMIT 1 []interface {}{1, "django-cms"}
2019/07/29 13:27:33 .../xorm/session_get.go:99:nocacheGet() [I] [SQL] SELECT "id", "repo_id", "user_id", "mode" FROM "collaboration" WHERE "repo_id"=$1 AND "user_id"=$2 LIMIT 1 []interface {}{90, 1}
2019/07/29 13:27:33 ...xorm/session_find.go:199:noCacheFind() [I] [SQL] SELECT "id", "repo_id", "type", "config", "created_unix" FROM "repo_unit" WHERE (repo_id = $1) []interface {}{90}
2019/07/29 13:27:33 .../xorm/session_raw.go:87:queryRow() [I] [SQL] SELECT count(*) FROM "release" WHERE repo_id=$1 AND is_draft=$2 []interface {}{90, false}
2019/07/29 13:27:33 ...xorm/session_find.go:199:noCacheFind() [I] [SQL] SELECT * FROM "user" INNER JOIN "team_user" ON "team_user".org_id="user".id INNER JOIN "team" ON "team".id="team_user".team_id WHERE ("team_user".uid=$1) AND ("team".authorize=$2) ORDER BY "user"."name" ASC []interface {}{1, 4}
2019/07/29 13:27:33 .../xorm/session_get.go:99:nocacheGet() [I] [SQL] SELECT "id", "owner_id", "lower_name", "name", "description", "website", "default_branch", "num_watches", "num_stars", "num_forks", "num_issues", "num_closed_issues", "num_pulls", "num_closed_pulls", "num_milestones", "num_closed_milestones", "is_private", "is_empty", "is_archived", "is_mirror", "is_fork", "fork_id", "size", "is_fsck_enabled", "close_issues_via_commit_in_any_branch", "topics", "avatar", "created_unix", "updated_unix" FROM "repository" WHERE (owner_id=$1 AND fork_id=$2) LIMIT 1 []interface {}{2, 90}
2019/07/29 13:27:33 .../xorm/session_get.go:99:nocacheGet() [I] [SQL] SELECT "id", "user_id", "repo_id" FROM "watch" WHERE "user_id"=$1 AND "repo_id"=$2 LIMIT 1 []interface {}{1, 90}
2019/07/29 13:27:33 .../xorm/session_get.go:99:nocacheGet() [I] [SQL] SELECT "id", "uid", "repo_id" FROM "star" WHERE "uid"=$1 AND "repo_id"=$2 LIMIT 1 []interface {}{1, 90}
2019/07/29 13:27:33 ...ules/context/repo.go:638:func1() [E] RepoRef invalid repo: branch or tag not exist:
2019/07/29 13:27:35 .../xorm/session_get.go:99:nocacheGet() [I] [SQL] SELECT "id", "lower_name", "name", "full_name", "email", "keep_email_private", "passwd", "must_change_password", "login_type", "login_source", "login_name", "type", "location", "website", "rands", "salt", "language", "description", "created_unix", "updated_unix", "last_login_unix", "last_repo_visibility", "max_repo_creation", "is_active", "is_admin", "allow_git_hook", "allow_import_local", "allow_create_organization", "prohibit_login", "avatar", "avatar_email", "use_custom_avatar", "num_followers", "num_following", "num_stars", "num_repos", "num_teams", "num_members", "visibility", "diff_view_style", "theme" FROM "user" WHERE "id"=$1 LIMIT 1 []interface {}{1}
2019/07/29 13:27:35 .../xorm/session_raw.go:87:queryRow() [I] [SQL] SELECT count(*) FROM "notification" WHERE (user_id = $1) AND (status = $2) []interface {}{1, 0x1}
2019/07/29 13:27:44 .../xorm/session_get.go:99:nocacheGet() [I] [SQL] SELECT repository.* FROM "repository" INNER JOIN "user" ON "user".id = repository.owner_id WHERE (repository.lower_name = $1) AND ("user".lower_name = $2) LIMIT 1 []interface {}{"xxx", "xxxxx"}
2019/07/29 13:27:44 .../xorm/session_get.go:99:nocacheGet() [I] [SQL] SELECT "id", "owner_id", "name", "fingerprint", "content", "mode", "type", "login_source_id", "created_unix", "updated_unix" FROM "public_key" WHERE "id"=$1 LIMIT 1 []interface {}{6}
2019/07/29 13:27:44 .../xorm/session_get.go:99:nocacheGet() [I] [SQL] SELECT "id", "lower_name", "name", "full_name", "email", "keep_email_private", "passwd", "must_change_password", "login_type", "login_source", "login_name", "type", "location", "website", "rands", "salt", "language", "description", "created_unix", "updated_unix", "last_login_unix", "last_repo_visibility", "max_repo_creation", "is_active", "is_admin", "allow_git_hook", "allow_import_local", "allow_create_organization", "prohibit_login", "avatar", "avatar_email", "use_custom_avatar", "num_followers", "num_following", "num_stars", "num_repos", "num_teams", "num_members", "visibility", "diff_view_style", "theme" FROM "user" WHERE "id"=$1 LIMIT 1 []interface {}{10}
2019/07/29 13:27:44 .../xorm/session_raw.go:87:queryRow() [I] [SQL] SELECT count(*) FROM "public_key" WHERE "id"=$1 []interface {}{6}
2019/07/29 13:27:44 ...rm/session_update.go:375:Update() [I] [SQL] UPDATE "public_key" SET "updated_unix" = $1 WHERE "id"=$2 []interface {}{1564406864, 6}
2019/07/29 13:27:44 .../xorm/session_get.go:99:nocacheGet() [I] [SQL] SELECT "id", "key_id", "repo_id", "name", "fingerprint", "mode", "created_unix", "updated_unix" FROM "deploy_key" WHERE "key_id"=$1 AND "repo_id"=$2 LIMIT 1 []interface {}{6, 108}
```
## Description

Tried to open a commit list page of a repository and got

```
template: repo/header:53:150: executing "repo/header" at <EscapePound>: invalid value; expected string
```

You can visit the URL as see the issue https://gitfoo.com/Alir3z4/django-cms/commits/branch/master

Also there's no custom template for  repo/header file.
...

## Screenshots

![image](https://user-images.githubusercontent.com/591113/62052457-27529f80-b21e-11e9-853d-1c483b6eb105.png)

**Comment by lafriks** [comment] 2019-07-29 14:16
Are you using custom templates?

**Comment by techknowlogick** [comment] 2019-07-29 14:17
@lafriks "`Also there's no custom template for repo/header file.`"

**Comment by lafriks** [comment] 2019-07-29 14:18
@techknowlogick it is strongly not recommended but you can override any template file in Gitea

**Comment by techknowlogick** [comment] 2019-07-29 14:20
@lafriks oh yes, I know ;) I was just quoting what the user said about not using them.

**Comment by zeripath** [comment] 2019-07-29 14:21
There's something very odd about that repository. I've just migrated it to try and your "master" branch wasn't brought along.

How did you create this repository and the master branch?

Gitea's branches are supposed to be in refs/heads I suspect your master branch is not.

**Comment by Alir3z4** [comment] 2019-07-29 14:23
Thanks @techknowlogick for pointing that out, yes @lafriks I have not overridden such template.

@zeripath I have simply migrated that repo via migration interface, the original repo is located at https://github.com/Alir3z4/django-cms which has been migrated into https://gitfoo.com/Alir3z4/django-cms/

I have found another problem as well, which it's reported at https://github.com/go-gitea/gitea/issues/7664

**Comment by zeripath** [comment] 2019-07-29 16:29
This is very odd because there's no master branch in that upstream repository

**Comment by Alir3z4** [comment] 2019-07-29 16:49
git can be without `master` branch. AFAIK, `master` is just like any other branch, with the exception that it's created by default when creating a repo (`git init`)

This SO thread can clarify more https://stackoverflow.com/a/3623762/636136

**Comment by zeripath** [comment] 2019-07-29 16:56
yeah I'm aware - but somehow your repo seems to think there should be a master branch.

I guess the default branch never got updated when the repo was migrated. Now, I think on try this doesn't happen c.f. https://try.gitea.io/arandomer/django-cms - so we must have fixed this in 1.10 but it wasn't reverted back to 1.9.

**Comment by zeripath** [comment] 2019-07-29 18:00
OK so a quick fix is to go to the repository settings and reset the default branch. But I don't understand why/how this appears fixed on 1.10

**Comment by amiga23** [comment] 2019-09-11 12:43
Have the same issue.
1. Create a branch
2. Go to settings and set new branch as default branch
3. delete branch
4. try to open any folder of the repo in the gitea WebUI -> ERROR

**Comment by lunny** [comment] 2019-09-12 01:35
@amiga23 which version of your gitea? I cannot reproduce that on 1.10.0+dev-281

**Comment by rdissertori** [comment] 2020-06-23 04:29
Hi, I can reproduce that. I'm at the current master branch of gitea runnin on docker.
What I did:
Migrate a project from github as a mirror. Initially there was a 1 "master" branch, but someone deleted it and renamed it to 1 "public" branch.
Then I'm getting that exact issue because gitea won't switch to the new "public" branch.

**Comment by DeRuiterIndustrieleAutomatisering** [comment] 2020-07-16 18:50
The problem occurs when you migrate a repo from github that doesn't have a master branch and then try to view a file. Gitea tries to open the master branch. When you switch to a existing branch first everything working fine

**Comment by techknowlogick** [comment] 2020-07-16 19:00
I've re-opened this issue. Thanks for the report.

@rdissertori / @DeRuiterIndustrieleAutomatisering  are you able to replicate this on try.gitea.io?

**Comment by Izorkin** [comment] 2020-08-04 15:18
A similar error occurs when viewing the history in the wiki.
```
авг 04 18:13:08 web gitea[101658]: 2020/08/04 18:13:08 .../templates/helper.go:614:ActionContent2Commits() [E] json.Unmarshal:
авг 04 18:13:08 web gitea[101658]:         {"Len":2,"Commits":[{"Sha1":"fd97fb5abf1e7338f24af26199e21d24817003f4","Message":"first commit
авг 04 18:13:08 web gitea[101658]:         ","AuthorEmail":"name@doname.local","AuthorName":"Izorkin","CommitterEmail":"name@doname.local","CommitterName":"Izorkin","Timestamp":"2020-07-29T14:56:35+03:00"},{"Sha1":"d84275409645b8d84fb1d85d33739a9aa972cae2","Message":"first commit
авг 04 18:13:08 web gitea[101658]:         ","AuthorEmail":"name@doname.local","AuthorName":"Izorkin","CommitterEmail":"name@doname.local","CommitterName":"Izorkin","Timestamp":"2020-07-29T14:56:35+03:00"}],"CompareURL":"test/example-wiki/compare/d84275409645b8d84fb1d85d33739a9aa972cae2...fd97fb5                                                                                   abf1e7338f24af26199e21d24817003f4"}
авг 04 18:13:08 web gitea[101658]:         ERROR: invalid character '\n' in string literal
авг 04 18:13:08 web gitea[101658]: 2020/08/04 18:13:08 .../templates/helper.go:614:ActionContent2Commits() [E] json.Unmarshal:
авг 04 18:13:08 web gitea[101658]:         {"Len":91,"Commits":[{"Sha1":"d84275409645b8d84fb1d85d33739a9aa972cae2","Message":"first commit
авг 04 18:13:08 web gitea[101658]:         ","AuthorEmail":"name@doname.local","AuthorName":"Izorkin","CommitterEmail":"name@doname.local","CommitterName":"Izorkin","Timestamp":"2020-07-29T14:56:35+03:00"},{"Sha1":"4cc3d12696add1a325bd4e91ca49393212d3baaa","Message":"homesrv: update config
авг 04 18:13:08 web gitea[101658]:         ","AuthorEmail":"name@doname.local","AuthorName":"Izorkin","CommitterEmail":"name@doname.local","CommitterName":"Izorkin","Timestamp":"2020-07-29T14:49:01+03:00"},{"Sha1":"77570b2db922c4454888f634c37a409a8e67004b","Message":"homesrv: update config
авг 04 18:13:08 web gitea[101658]:         ","AuthorEmail":"name@doname.local","AuthorName":"Izorkin","CommitterEmail":"name@doname.local","CommitterName":"Izorkin","Timestamp":"2020-07-28T21:37:10+03:00"},{"Sha1":"b1226bca9139f1d6a5610bcb127956d4af290499","Message":"homesrv: update config
авг 04 18:13:08 web gitea[101658]:         ","AuthorEmail":"name@doname.local","AuthorName":"Izorkin","CommitterEmail":"name@doname.local","CommitterName":"Izorkin","Timestamp":"2020-07-23T14:00:10+03:00"},{"Sha1":"e0c10bbc086e7554587f38615e6d930abdb3d9ee","Message":"homesrv: update config
авг 04 18:13:08 web gitea[101658]:         ","AuthorEmail":"name@doname.local","AuthorName":"Izorkin","CommitterEmail":"name@doname.local","CommitterName":"Izorkin","Timestamp":"2020-07-22T20:15:21+03:00"}],"CompareURL":"test/example-wiki/compare/4cc3d12696add1a325bd4e91ca49393212d3baaa...d842754                                                                                   09645b8d84fb1d85d33739a9aa972cae2"}
авг 04 18:13:08 web gitea[101658]:         ERROR: invalid character '\n' in string literal
авг 04 18:13:08 web gitea[101658]: 2020/08/04 18:13:08 .../templates/helper.go:614:ActionContent2Commits() [E] json.Unmarshal:
авг 04 18:13:08 web gitea[101658]:         {"Len":10,"Commits":[{"Sha1":"4cc3d12696add1a325bd4e91ca49393212d3baaa","Message":"homesrv: update config
авг 04 18:13:08 web gitea[101658]:         ","AuthorEmail":"name@doname.local","AuthorName":"Izorkin","CommitterEmail":"name@doname.local","CommitterName":"Izorkin","Timestamp":"2020-07-29T14:49:01+03:00"},{"Sha1":"77570b2db922c4454888f634c37a409a8e67004b","Message":"homesrv: update config
авг 04 18:13:08 web gitea[101658]:         ","AuthorEmail":"name@doname.local","AuthorName":"Izorkin","CommitterEmail":"name@doname.local","CommitterName":"Izorkin","Timestamp":"2020-07-28T21:37:10+03:00"},{"Sha1":"b1226bca9139f1d6a5610bcb127956d4af290499","Message":"homesrv: update config
авг 04 18:13:08 web gitea[101658]:         ","AuthorEmail":"name@doname.local","AuthorName":"Izorkin","CommitterEmail":"name@doname.local","CommitterName":"Izorkin","Timestamp":"2020-07-23T14:00:10+03:00"},{"Sha1":"e0c10bbc086e7554587f38615e6d930abdb3d9ee","Message":"homesrv: update config
авг 04 18:13:08 web gitea[101658]:         ","AuthorEmail":"name@doname.local","AuthorName":"Izorkin","CommitterEmail":"name@doname.local","CommitterName":"Izorkin","Timestamp":"2020-07-22T20:15:21+03:00"},{"Sha1":"173cc1a68f70bc195dcdf8b2d50259d14c1aebd8","Message":"homesrv: update config
авг 04 18:13:08 web gitea[101658]:         ","AuthorEmail":"name@doname.local","AuthorName":"Izorkin","CommitterEmail":"name@doname.local","CommitterName":"Izorkin","Timestamp":"2020-06-23T12:21:45+03:00"}],"CompareURL":""}
авг 04 18:13:08 web gitea[101658]:         ERROR: invalid character '\n' in string literal
```

**Comment by fashberg** [comment] 2020-09-07 15:31
Using latest 1.12.4 you can simply reproduce this error:

- Create (empty) repositoy
- add a wiki-page
- open diff (/user/testrepo/wiki/commit/<id>)
- you'll get ```template: repo/header:95:151: executing "repo/header" at <EscapePound>: invalid value; expected string```
- if you add more changes to that wiki-page only the latest diff shows this error (top of "/user/testrepo/wiki/Home/_revision").


If you push something the the repo (not the wiki-repo, the repo itself) then everying is working.

gitea source file templates/repo/header.tmpl, Line 95

```<a class="{{if .PageIsViewCode}}active{{end}} item" href="{{.RepoLink}}{{if (ne .BranchName .Repository.DefaultBranch)}}/src/{{.BranchNameSubURL | EscapePound}}{{end}}">```

If i build and install from latest gitea-master (1.13) this issue seems to be solved.

**Comment by zeripath** [comment] 2020-10-17 21:44
Is this still present on 1.12.5?

**Comment by lunny** [comment] 2021-01-02 12:12
I will close this and please feel free reopen it if it occurs again.

**Closed as completed by lunny** 2021-01-02 12:12 UTC
Labels: type/bug, issue/needs-feedback
