### ISSUE TITLE
migrate from github fail when use the 'custom/conf/app.example.ini'

### ISSUE THREAD

**Issue by soyozhang** [go-gitea/gitea#20325] opened 2022-07-12 02:46 UTC
### Description

 I run gitea with docker ,and when I want to migrate project from git, It shows fail and needs me to configure the `migrations-ALLOWED_DOMAINS,BLOCKED_DOMAINS ,ALLOW_LOCALNETWORKS`

And when I want to find the introduction of the `app.ini`, I find it's the example:

```
;; Allowed domains for migrating, default is blank. Blank means everything will be allowed.
;; Multiple domains could be separated by commas.
;; Wildcard is supported: "github.com, *.github.com"
;ALLOWED_DOMAINS =
;;
;; Blocklist for migrating, default is blank. Multiple domains could be separated by commas.
;; When ALLOWED_DOMAINS is not blank, this option has a higher priority to deny domains.
;; Wildcard is supported.
;BLOCKED_DOMAINS =

```

but when I configure as blow, it's still fail.

```
ALLOWED_DOMAINS =
BLOCKED_DOMAINS =

```

and when I change it as:

```
ALLOWED_DOMAINS = *
BLOCKED_DOMAINS =

```

and now, it can migrate successful.

### Gitea Version

1.16.8

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

I run gitea with docker-compose, and the image is v1.16.8

### Database

PostgreSQL

**Comment by wxiaoguang** [comment] 2022-07-12 03:34
Oops, sorry for the bug. It will be fixed by #20327

**Comment by wxiaoguang** [comment] 2022-07-12 04:17
It's not a bug, see https://github.com/go-gitea/gitea/pull/20328

I think what you need is ALLOW_LOCALNETWORKS .

**Comment by wxiaoguang** [comment] 2022-07-14 02:40
https://github.com/go-gitea/gitea/pull/20328 has been merged.

If you still have questions, please provide more clues.

**Closed as completed by wxiaoguang** 2022-07-14 02:40 UTC
Labels: issue/needs-feedback
