### ISSUE TITLE
Profile README.md

### ISSUE THREAD

**Issue by KevinKrueger** [go-gitea/gitea#21760] opened 2022-11-10 08:59 UTC
### Feature Description

It would be nice to be able to prettify your profile with a README.md file like in GitHub.

Yes.... I know.... is not really a feature and maybe a bit unnecessary but would be cool :)

### Screenshots

![image](https://user-images.githubusercontent.com/25382167/201046391-bb1823f8-c7c7-4163-9316-8d0d1149ac61.png)

**Comment by jolheiser** [comment] 2022-11-10 13:17
Duplicate of #12233

**Closed as not planned by jolheiser** 2022-11-10 13:17 UTC
Labels: issue/duplicate, type/proposal, type/feature
