### ISSUE TITLE
UX: Add icon based on filetype

### ISSUE THREAD

**Issue by webysther** [go-gitea/gitea#25376] opened 2023-06-19 23:59 UTC
### Feature Description

Support for icon will be great, there a few chrome extensions to improve github/gitlab/gitea/gogs but have a set based on file type by default will be great.

### Screenshots

From 
![image](https://github.com/go-gitea/gitea/assets/750007/60e8e90f-861c-47e8-bec7-fb8cca93be84)

To
![image](https://github.com/go-gitea/gitea/assets/750007/ae1ab9a7-6e0c-40ac-bcbf-0484c18753d2)

https://github.com/homerchen19/github-file-icons
https://chrome.google.com/webstore/detail/file-icons-for-github-and/ficfmibkjjnpogdcfhfokmihanoldbfe

**Comment by eeyrjmr** [comment] 2023-06-20 00:34
duplicate of https://github.com/go-gitea/gitea/issues/11149 
There was a PR to implement this  https://github.com/go-gitea/gitea/pull/24147

**Comment by lunny** [comment] 2023-06-20 01:11
#24147 is perfect enough for this requirement but most of us don't think it should be the default setting. Maybe it's better as a theme.

**Closed as not planned** 2023-06-20 01:11 UTC
Labels: type/proposal, type/feature
