### ISSUE TITLE
Narrowly-scoped Authentication Tokens

### ISSUE THREAD

**Issue by chmac** [go-gitea/gitea#19079] opened 2022-03-14 14:26 UTC
### Feature Description

Similar to #18374 I'd like to see the same for access tokens. When I add a new access token, I'd like to be able to choose which repositories it is allowed to access, and preferably, whether the token should have read-only or read-write access to each repository.

I'd love to see the following options available for newly created access tokens:

- Token is valid for:
  - All repositories the user can access
  - Select specific repositories
- Token allows:
  - Pull only access
  - Pull and push access

If it makes the implementation easier, it would also be totally acceptable to have the tokens created on the repository itself instead of per user, similarly to Deploy Keys. So a user can create a personal access token for a specific repository.

There are places where I put tokens, unencrypted, because they need to push to a single repo on my gitea install. In that situation, I have to create new users to be able to limit the token to only be valid for a single repository. It would be great if there was an easier option.

Thanks for gitea, it really makes self hosting git painless and joyful. Y'all rock. 🧡 

### Screenshots

GitHub has a whole host of options, which I think would be overkill for gitea.

<img width="823" alt="image" src="https://user-images.githubusercontent.com/690997/158192093-48b7cc06-7d36-4908-b0dd-404d6e1e7a08.png">

**Comment by qwerty287** [comment] 2022-03-20 06:32
Duplicate of https://github.com/go-gitea/gitea/issues/4300?

**Closed as completed** 2022-03-20 07:30 UTC
Labels: issue/duplicate
