### ISSUE TITLE
please add a Ukrainian language

### ISSUE THREAD

**Issue by andruwa13** [go-gitea/gitea#3858] opened 2018-04-28 18:11 UTC
files are present in the project
![gitea options locale at master go-gitea gitea 2018-04-28 21-08-44](https://user-images.githubusercontent.com/5846351/39399552-67829906-4b28-11e8-929a-e7d47e7536bf.png)

but there is no language menu
![andruwa13 - - gitea git with a cup of tea 2018-04-28 21-10-24](https://user-images.githubusercontent.com/5846351/39399560-9f557f42-4b28-11e8-8382-c0eed519ccdb.png)

  
![andruwa13 - - gitea git with a cup of tea 2018-04-28 21-10-09](https://user-images.githubusercontent.com/5846351/39399563-a88e7546-4b28-11e8-8541-e3bb1c26afb0.png)

**Comment by lunny** [comment] 2018-04-29 04:30
The languages could be changed on the app.ini file.

**Comment by daviian** [comment] 2018-05-24 12:01
So this can be closed, right?

**Comment by andruwa13** [comment] 2018-05-24 12:05
@daviian no, the [site](https://try.gitea.io) does not have the opportunity to choose the Ukrainian language

**Comment by daviian** [comment] 2018-05-24 12:26
@andruwa13 ok, now I get it. You want `try.gitea.io` to enable Ukrainian.

**Comment by andruwa13** [comment] 2018-05-24 13:04
@daviian with a new installation, there is also no Ukrainian language by default

**Comment by daviian** [comment] 2018-05-24 13:05
@andruwa13 Like @lunny said you can adjust the list of languages in app.ini

**Comment by lunny** [comment] 2018-05-24 14:38
@bkcsoft I think this is not a bug, it's a new language of gitea.

**Comment by lunny** [comment] 2018-05-24 15:30
closed by #4036

**Closed as completed by lunny** 2018-05-24 15:30 UTC
Labels: type/proposal

**Comment by andruwa13** [comment] 2018-05-24 16:46
not work :(

**Comment by apricote** [comment] 2018-05-24 17:06
The PR only modified the `app.ini.sample`. The actual `app.ini` used in the `try.gitea.io` deployment would need to be updated too.

**Comment by andruwa13** [comment] 2018-05-24 17:10
new install Gitea, there is also no Ukrainian language :(
![installation - gitea git with a cup of tea 2018-05-24 20-08-39](https://user-images.githubusercontent.com/5846351/40500774-844fd510-5f8e-11e8-964f-843878a4cc51.png)

**Comment by apricote** [comment] 2018-05-24 17:28
You have to configure it in your custom `app.ini` to take effect. The file changed in the PR is **not** the default that your clean install will use, only a **sample** of what you could use.

The actual default is loaded in [`modules/setting/setting.go#L1090`](https://github.com/go-gitea/gitea/blob/master/modules/setting/setting.go#L1090):

```go
Langs = Cfg.Section("i18n").Key("LANGS").Strings(",")
if len(Langs) == 0 {
	Langs = defaultLangs
}
```

and `defaultLangs` is defined in [`modules/setting/defaults.go`](https://github.com/go-gitea/gitea/blob/master/modules/setting/defaults.go):

```go
var (
	defaultLangs     = strings.Split("en-US,zh-CN,zh-HK,zh-TW,de-DE,fr-FR,nl-NL,lv-LV,ru-RU,ja-JP,es-ES,pt-BR,pl-PL,bg-BG,it-IT,fi-FI,tr-TR,cs-CZ,sr-SP,sv-SE,ko-KR", ",")
	defaultLangNames = strings.Split("English,简体中文,繁體中文（香港）,繁體中文（台灣）,Deutsch,français,Nederlands,latviešu,русский,日本語,español,português do Brasil,polski,български,italiano,suomi,Türkçe,čeština,српски,svenska,한국어", ",")
)
```

So if you create another PR that modifies this file, ukrainian should appear in the menu by default.
