### ISSUE TITLE
Adding multiple labels in pull / issue detail page broken

### ISSUE THREAD

**Issue by noerw** [go-gitea/gitea#13923] opened 2020-12-09 23:31 UTC
- Gitea version (or commit ref):  1.14.0+dev-290-gb1cf7f4df (current gitea.com)
- Git version: ? (current gitea.com)
- Operating system: ? (current gitea.com)

- Database (use `[x]`):  (current gitea.com)
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL): 
  - [x] No, only on gitea.com https://gitea.com/gitea/tea/pulls/285
- Log gist:

## Description
1. Opening the label dropdown and selecting more than one label applies only one of the selected labels. Sometimes two, not consistent. So far never all selected labels.

2. Doing this several times adds the remaining labels, but in the action log / comments of the issue, only the first added label is displayed.

I didn't check in detail, but 2. makes me think this was introduced by #13304.
Another recent bug related to labels is #13688

## Screenshots
![grafik](https://user-images.githubusercontent.com/7880552/101701099-236f9800-3a76-11eb-8ccb-1a417def6856.png)

**Comment by lunny** [comment] 2020-12-10 00:36
May also related with #13619

**Comment by silverwind** [comment] 2020-12-10 08:32
Not sure if related but I noticed when adding a single label and trying to "Clear Labels", it does not work. Label is temporarily removed but get's re-added again from the server response.

**Comment by noerw** [comment] 2021-02-27 20:15
A new interesting sample on this, might be *another* labels bug..

- I created https://gitea.com/gitea/tea/pulls/327, and labeled it as `kind/bug`. The label is not shown in the PR comment log (as described in OP)
    ![grafik](https://user-images.githubusercontent.com/7880552/109398974-e067e700-7937-11eb-804a-23f380d9ee1a.png)
- Unlike the PR detail view, the PR list also shows the `kind/enhancement` label. Filtering by that label reveals the label ID 4694. 
    ![grafik](https://user-images.githubusercontent.com/7880552/109398949-b8788380-7937-11eb-8115-3c7917f03572.png)
- Other PRs intentionally labeled `kind/enhancement` have label ID 435 for that.

gitea.com currently runs 1.14.0+dev-754-g5d2b7ba63

**Comment by CirnoT** [comment] 2021-03-05 17:13
Unsure if this should be closed as it raises two separate issue. #14894 fixes display issue for event-timeline but this issue also tracks case where label is not added at all server-side.

**Comment by zeripath** [comment] 2021-03-05 17:45
OK - I think we need to retest and show that the issue is still happening on try/master

**Comment by lunny** [comment] 2021-03-06 03:46
I can see both https://gitea.com/gitea/tea/pulls/285 and https://gitea.com/gitea/tea/pulls/327 's problem resolved.

**Comment by lunny** [comment] 2021-03-06 04:20
OK. The problem left is here.

> * Unlike the PR detail view, the PR list also shows the `kind/enhancement` label. Filtering by that label reveals the label ID 4694.
>   ![grafik](https://user-images.githubusercontent.com/7880552/109398949-b8788380-7937-11eb-8115-3c7917f03572.png)
> * Other PRs intentionally labeled `kind/enhancement` have label ID 435 for that.
> 
> gitea.com currently runs 1.14.0+dev-754-g5d2b7ba63

**Comment by noerw** [comment] 2021-03-06 12:22
> OK. The problem left is here.
> 
> > * Unlike the PR detail view, the PR list also shows the `kind/enhancement` label. Filtering by that label reveals the label ID 4694.

For new issues this doesnt happen anymore, so I think this is because the bug previously persisted those extra labels to DB.
I guess a heuristic to clean the DB would be to remove rows `where labelID > 4000` (and maybe only for issues from last 12 days)

**Comment by CirnoT** [comment] 2021-03-07 04:34
The fix applied did nothing to change what label ID is saved to database, it only fixed squashing multiple actions into one timeline event.

The ID discrepancy will most likely be because of repo vs org label. I'm gonna guess both tea repo and gitea org have `kind/enhancement` label and some parts of code use one, while others the other (possibly `tea` tool explicitly tells Gitea to apply the other one)

**Comment by Toxik1983** [comment] 2021-04-16 07:44
I believe this bug has existed since before 1.13.0.

Not only does this happen when adding multiple labels at once, but also when removing them at the same time.
For example, if you swap labels by removing one and adding the other, this will only perform one of the two actions.
Most of the time, you need to refresh the page for this to become apparant.

Currently, in order to set or remove multiple labels reliably, you must blur the dialog in between each alteration.

**Comment by fnetX** [comment] 2021-06-04 23:31
Not sure if this is new information to anyone here (didn't look in all the mentioned PRs), but this is also tracked at Codeberg with some log output: https://codeberg.org/Codeberg/Community/issues/123#issuecomment-77816
(https://codeberg-test.org/fnx/general/issues/1#issuecomment-95)

**Comment by lunny** [comment] 2021-11-15 01:12
I think this has been resolved.

**Closed as completed** 2021-11-16 02:21 UTC
Labels: type/bug, topic/ui
