### ISSUE TITLE
Garbled styling on latest docker

### ISSUE THREAD

**Issue by bkraul** [go-gitea/gitea#9253] opened 2019-12-05 12:34 UTC
- Gitea version (or commit ref): 1.11.0+dev-371-gd9c67a8c9
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)L https://try.gitea.io
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
The last update seems to have introduced styling issues. A lot of the usual styling has been lost, and the collapsible menu button on the top left does not work. The gitea logo is huge, and the other sections seem to not have the right styling. The login screen looks rather bad as well.

### Main Screen
![image](https://user-images.githubusercontent.com/14616851/70235656-f5e86400-1728-11ea-8424-0656410843d9.png)

### Login Screen
![image](https://user-images.githubusercontent.com/14616851/70235695-0a2c6100-1729-11ea-8334-d1b3eb2aee9f.png)

**Comment by ashimokawa** [comment] 2019-12-05 13:24
Probably caused by d9c67a8c903fa9927bad28f5fcb816f89f8200eb

Tries to load this, which does not exist:
https://try.gitea.io/js/index.js

**Comment by lunny** [comment] 2019-12-05 15:29
This will be fixed by #9252

**Comment by techknowlogick** [comment] 2019-12-05 17:19
PR merged, docker image now being built. Closing this ticket now.

**Closed as completed by techknowlogick** 2019-12-05 17:19 UTC
Labels: type/bug
