### ISSUE TITLE
Unable to deliver webhook task[53215]: webhook does not exist [id: 134]

### ISSUE THREAD

**Issue by hiifong** [go-gitea/gitea#25744] opened 2023-07-07 07:56 UTC
### Description

```
2023/07/07 15:54:26 ...s/webhook/webhook.go:125:handler() [E] Unable to deliver webhook task[53215]: webhook does not exist [id: 134]
```

### Gitea Version

v1.20+

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

./gitea web

### Database

MySQL

**Comment by puni9869** [comment] 2023-07-08 11:25
I can pick this one.

Could you share the repro steps. It will be very use ful for me to understand .

**Comment by hiifong** [comment] 2023-07-08 13:06
> I can pick this one.
> 
> Could you share the repro steps. It will be very use ful for me to understand .

I'm very sorry, I didn't notice this bug before and now I don't know how to reproduce it, anyway he will throw it when I start the gitea instance.

**Comment by puni9869** [comment] 2023-07-08 15:09
I will try to repro it.
Wish me luck...

**Comment by puni9869** [comment] 2023-07-09 10:45
I tried couple of ways to repro it. But didn't get the cause.

**Comment by puni9869** [comment] 2023-07-09 10:57
I found it 
<img width="1402" alt="image" src="https://github.com/go-gitea/gitea/assets/80308335/cb2b65e6-f7ab-4b59-b02b-684598d51238">

**Comment by puni9869** [comment] 2023-07-09 11:01
But if you see the error 
`2023/07/09 16:26:12 ...s/webhook/webhook.go:114:handler() [E] GetHookTaskByID[16] failed: hook task does not exist [task: 16, hook: 0, uuid: ]
``
Its showing different  error. `hook task does not exist`

**Comment by hiifong** [comment] 2023-07-09 11:05
> But if you see the error 
> `2023/07/09 16:26:12 ...s/webhook/webhook.go:114:handler() [E] GetHookTaskByID[16] failed: hook task does not exist [task: 16, hook: 0, uuid: ]
> ``
> Its showing different  error. `hook task does not exist`

I guess you might get the same error as me when you restart your gitea instance with console

**Comment by puni9869** [comment] 2023-07-09 11:07
Are you testing it on your local system or on testing instance.
PS: in my local when I restart the project I don't see any error. I mean `make watch`

**Comment by hiifong** [comment] 2023-07-09 11:11
> Are you testing it on your local system or on testing instance. The error only persist when we delete any repo with a webhook
> PS: in my local when I restart the project I don't see any error. I mean `make watch`

prod

**Comment by puni9869** [comment] 2023-07-21 07:44
@hiifong  Shall we close this issue, Since I have tried multple time, multiple ways to repro it, still no luck. I have not seen the above issue again. Ofcourse we can reopen this if we encountered

**Comment by lunny** [comment] 2023-07-21 08:09
Maybe we should clean the tasks in queues before deleting database records when deleting a repository.

**Comment by wxiaoguang** [comment] 2023-07-21 08:25
> Maybe we should clean the tasks in queues before deleting database records when deleting a repository.

TBH, it's not the right way. Queue item couldn't/shouldn't be deleted ad-hoc.

It should simply ignore the non-existing webhooks.

**Comment by puni9869** [comment] 2023-07-21 08:26
Shall we log warn level instead of error level in the program.

**Comment by lunny** [comment] 2023-07-21 08:27
> Shall we log warn level instead of error level in the program.

Maybe yes.

**Closed as completed** 2023-07-28 17:46 UTC
Labels: type/bug

**Comment by hiifong** [comment] 2023-07-29 17:23
very strange,here is my gitea compiled from the latest commit @puni9869 
![image](https://github.com/go-gitea/gitea/assets/89133723/2b07ed57-bdc7-45a2-9f75-a5a04887a53e)

`2023/07/30 01:14:28 ...s/webhook/webhook.go:130:handler() [E] Unable to deliver webhook task[53215]: webhook does not exist [id: 134]`

Gitea version: `Gitea version 1.20.0+rc0-422-g11074258f built with GNU Make 4.2.1, go1.20.6 : bindata`

**Comment by puni9869** [comment] 2023-07-29 18:05
It works on my system,  could you share your system configs like  os and architecture, go version.

**Comment by puni9869** [comment] 2023-07-29 18:20
Just checked on my system,
`2023/07/29 23:49:13 ...s/webhook/webhook.go:116:handler() [W] GetHookTaskByID[41] warn: hook task does not exist [task: 41, hook: 0, uuid: ]`

<img width="1370" alt="image" src="https://github.com/go-gitea/gitea/assets/80308335/5034d870-6072-4d78-92bb-18f44ca7c6e5">
