### ISSUE TITLE
Add user to organization based on LDAP group membership

### ISSUE THREAD

**Issue by tobias--** [go-gitea/gitea#2121] opened 2017-07-07 11:18 UTC
- Gitea version (or commit ref): 1.1.2

## Description

It would be nice if users could be automatically added to an organization based on their LDAP group membership (e.g. using the "memberof" attribute).

**Comment by bkcsoft** [comment] 2017-07-07 20:27
Something I've wanted for a while. Also for OAuth and SMTP based on domain of email :)

**Comment by TwoTwenty** [comment] 2019-06-05 19:27
it would be nice to be able to add them to an organization based on the ldap source.. since gitea supports multiple ldap definitions.

**Comment by alexattws** [comment] 2019-11-30 14:40
We've implemented mapping LDAP groups to teams in (all) organizations (by group/team name) and published it here, if anyone is interested,
https://github.com/tws-inc/gitea-group-sync

**Comment by pbodnar** [comment] 2020-02-29 15:42
Duplicate of #1395? Lets vote for this feature there...

**Closed as completed** 2022-02-14 13:22 UTC
Labels: type/feature, issue/confirmed
