### ISSUE TITLE
Can't grant rights to clone local repositories

### ISSUE THREAD

**Issue by HaasJona** [go-gitea/gitea#4969] opened 2018-09-21 08:27 UTC
- Gitea version (or commit ref): 1.5.1
- Git version: 2.17.1
- Operating system: Fedora 28
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No (Don't have admin permissions there)
  - [ ] Not relevant
- Log gist:

```
2018/09/21 10:24:06 [I] [SQL] SELECT `id`, `lower_name`, `name`, `full_name`, `email`, `keep_email_private`, `passwd`, `login_type`, `login_source`, `login_name`, `type`, `location`, `website`, `rands`, `salt`, `language`, `created_unix`, `updated_unix`, `last_login_unix`, `last_repo_visibility`, `max_repo_creation`, `is_active`, `is_admin`, `allow_git_hook`, `allow_import_local`, `allow_create_organization`, `prohibit_login`, `avatar`, `avatar_email`, `use_custom_avatar`, `num_followers`, `num_following`, `num_stars`, `num_repos`, `description`, `num_teams`, `num_members`, `diff_view_style` FROM `user` WHERE `id`=? LIMIT 1 []interface {}{1}
2018/09/21 10:24:06 [I] [SQL] SELECT count(*) FROM `notification` WHERE (user_id = ?) AND (status = ?) []interface {}{1, 0x1}
2018/09/21 10:24:06 [I] [SQL] SELECT `id`, `lower_name`, `name`, `full_name`, `email`, `keep_email_private`, `passwd`, `login_type`, `login_source`, `login_name`, `type`, `location`, `website`, `rands`, `salt`, `language`, `created_unix`, `updated_unix`, `last_login_unix`, `last_repo_visibility`, `max_repo_creation`, `is_active`, `is_admin`, `allow_git_hook`, `allow_import_local`, `allow_create_organization`, `prohibit_login`, `avatar`, `avatar_email`, `use_custom_avatar`, `num_followers`, `num_following`, `num_stars`, `num_repos`, `description`, `num_teams`, `num_members`, `diff_view_style` FROM `user` WHERE `id`=? LIMIT 1 []interface {}{1}
2018/09/21 10:24:06 [I] [SQL] SELECT `id`, `type`, `name`, `is_actived`, `is_sync_enabled`, `cfg`, `created_unix`, `updated_unix` FROM `login_source`
2018/09/21 10:24:06 [I] [SQL] UPDATE `user` SET `lower_name` = ?, `name` = ?, `full_name` = ?, `email` = ?, `keep_email_private` = ?, `passwd` = ?, `login_type` = ?, `login_source` = ?, `login_name` = ?, `type` = ?, `location` = ?, `website` = ?, `rands` = ?, `salt` = ?, `language` = ?, `last_login_unix` = ?, `last_repo_visibility` = ?, `max_repo_creation` = ?, `is_active` = ?, `is_admin` = ?, `allow_git_hook` = ?, `allow_import_local` = ?, `allow_create_organization` = ?, `prohibit_login` = ?, `avatar` = ?, `avatar_email` = ?, `use_custom_avatar` = ?, `num_followers` = ?, `num_following` = ?, `num_stars` = ?, `num_repos` = ?, `description` = ?, `num_teams` = ?, `num_members` = ?, `diff_view_style` = ?, `updated_unix` = ? WHERE `id`=? []interface {}{"jonathan.###", "Jonathan.###", "", "jonathan.###@###.de", false, "###", 0, 0, "", 0, "", "", "###", "###", "en-US", 0, false, -1, true, true, true, true, true, false, "###", "jonathan.###@###.de", false, 0, 0, 0, 1, "", 0, 0, "", 1537518246, 1}
2018/09/21 10:24:06 [I] [SQL] SELECT `id`, `lower_name`, `name`, `full_name`, `email`, `keep_email_private`, `passwd`, `login_type`, `login_source`, `login_name`, `type`, `location`, `website`, `rands`, `salt`, `language`, `created_unix`, `updated_unix`, `last_login_unix`, `last_repo_visibility`, `max_repo_creation`, `is_active`, `is_admin`, `allow_git_hook`, `allow_import_local`, `allow_create_organization`, `prohibit_login`, `avatar`, `avatar_email`, `use_custom_avatar`, `num_followers`, `num_following`, `num_stars`, `num_repos`, `description`, `num_teams`, `num_members`, `diff_view_style` FROM `user` WHERE `id`=? LIMIT 1 []interface {}{1}
2018/09/21 10:24:06 [I] [SQL] SELECT count(*) FROM `notification` WHERE (user_id = ?) AND (status = ?) []interface {}{1, 0x1}
2018/09/21 10:24:06 [I] [SQL] SELECT `id`, `lower_name`, `name`, `full_name`, `email`, `keep_email_private`, `passwd`, `login_type`, `login_source`, `login_name`, `type`, `location`, `website`, `rands`, `salt`, `language`, `created_unix`, `updated_unix`, `last_login_unix`, `last_repo_visibility`, `max_repo_creation`, `is_active`, `is_admin`, `allow_git_hook`, `allow_import_local`, `allow_create_organization`, `prohibit_login`, `avatar`, `avatar_email`, `use_custom_avatar`, `num_followers`, `num_following`, `num_stars`, `num_repos`, `description`, `num_teams`, `num_members`, `diff_view_style` FROM `user` WHERE `id`=? LIMIT 1 []interface {}{1}
2018/09/21 10:24:06 [I] [SQL] SELECT `id`, `type`, `name`, `is_actived`, `is_sync_enabled`, `cfg`, `created_unix`, `updated_unix` FROM `login_source`
```

(censored a few potentially sensitive things with ###)

## Description

Checking "May Import Local Repositories" and clicking "Update user Account" causes the site to reload and it says "The user account has been updated" at the top, but the checkbox will reset to being unchecked and the user will still not be able to import local repositories.

## Screenshots
![bildschirmfoto von 2018-09-21 10-22-17](https://user-images.githubusercontent.com/4310707/45869243-3fe56400-bd88-11e8-93b8-786f993b46c4.png)

**Comment by lafriks** [comment] 2018-09-21 10:39
Duplicate of #2166

**Closed as completed by lafriks** 2018-09-21 10:39 UTC
Labels: type/question

**Comment by HaasJona** [comment] 2018-09-24 08:34
If you need to change the app.ini in order to enable local repositories, it should show an error message stating that instead of silently doing nothing. The current behaviour looks definitely like a bug.
