### ISSUE TITLE
Unable to login using e-mail (LDAP)

### ISSUE THREAD

**Issue by taziden** [go-gitea/gitea#18547] opened 2022-02-02 10:34 UTC
### Gitea Version

1.16.0

### How are you running Gitea?

Using gitea binary downloaded from dl.gitea.io.

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

When trying to log in using my e-mail, I get an error "Identifiant ou mot de passe invalide." (username or password invalid).
When using username, it works as expected.

**Comment by mscherer** [comment] 2022-02-02 12:30
I can't reproduce that on almost the same setup (downloaded gitea, same version, using postgresql, and in french).

**Comment by viceice** [comment] 2022-02-03 16:01
I've the same issue, see #18577 for details. We are suing the official helm chart and ldap as login source.
Login via username works fine.

**Comment by bluppfisk** [comment] 2022-02-14 14:41
same issue here with LDAP as login source

**Comment by lunny** [comment] 2022-02-14 16:12
@taziden I asume your account is also a LDAP account.

**Comment by lunny** [comment] 2022-02-14 16:13
@viceice @bluppfisk Could you confirm that the login source is active?

**Comment by viceice** [comment] 2022-02-14 16:18
I'm out of office, will try to validate next days.

**Comment by johanvdw** [comment] 2022-02-14 16:41
The error in the errorlog is:
` Failed to login 'xxx' via 'ldapsource': e-mail already in use [email: johan@xxx]`

**Comment by lunny** [comment] 2022-02-14 16:53
> The error in the errorlog is: ` Failed to login 'xxx' via 'ldapsource': e-mail already in use [email: johan@xxx]`
> 
> also affects 1.16.1 - this was working in 1.15.9

Could you help to check if there are more than 1 users have the same email address?

**Comment by lunny** [comment] 2022-02-16 09:09
@johanvdw Could you help to confirm #18769 resolved the problem.

**Comment by lunny** [comment] 2022-02-17 03:57
Ah, maybe I should merge #18769 and #18786 as one.

**Comment by MarTiXcz** [comment] 2022-02-17 08:33
We are also experiencing the issue with LDAP login. Neither username nor email is not working. Is there a Windows(x64-gogit) binary I can test if it's fixed?  Can we expect 16.2 version soon or should I downgrade to 15.x?

**Comment by lunny** [comment] 2022-02-17 08:36
> We are also experiencing the issue with LDAP login. Neither username nor email is not working. Is there a Windows(x64-gogit) binary I can test if it's fixed? Can we expect 16.2 version soon or should I downgrade to 15.x?

If both of the two PRs merged, you can download from https://dl.gitea.io/gitea/1.16 as a test.

**Comment by johanvdw** [comment] 2022-02-17 22:32
I have tested both your PR https://github.com/go-gitea/gitea/pull/18769 and https://github.com/go-gitea/gitea/pull/18786

They do not fix the issue.

If I enable debug logging I will get:
```
2022/02/17 23:29:05 ...odels/auth/source.go:300:GetSourceByID() [I] [SQL] SELECT "id", "type", "name", "is_active", "is_sync_enabled", "cfg", "created_unix", "updated_unix" FROM "login_source" WHERE "id"=$1 LIMIT 1 [1] - 1.154345ms
2022/02/17 23:29:05 ...dap/source_search.go:98:findUserDN() [D] Failed search using filter[(&(objectclass=posixAccount)(uid=johanvdw))]: <nil>
2022/02/17 23:29:05 ...s/context/context.go:198:HTML() [D] Template: user/auth/signin
2022/02/17 23:29:05 ...ers/web/auth/auth.go:200:SignInPost() [I] Failed authentication attempt for johanvdw from [::1]:36534: user does not exist [uid: 0, name: johanvdw, keyid: 0]
```

```
2022/02/17 23:31:19 ...odels/auth/source.go:300:GetSourceByID() [I] [SQL] SELECT "id", "type", "name", "is_active", "is_sync_enabled", "cfg", "created_unix", "updated_unix" FROM "login_source" WHERE "id"=$1 LIMIT 1 [1] - 2.477986ms
2022/02/17 23:31:19 ...dap/source_search.go:98:findUserDN() [D] Failed search using filter[(&(objectclass=posixAccount)(uid=johan@fluves.com))]: <nil>
2022/02/17 23:31:19 ...s/context/context.go:198:HTML() [D] Template: user/auth/signin
2022/02/17 23:31:19 ...ers/web/auth/auth.go:200:SignInPost() [I] Failed authentication attempt for johan@fluves.com from [::1]:36534: user does not exist [uid: 0, name: johan@xxx.com, keyid: 0]
```
both do not work because the loginname for ldap is different from the email or the username in this case.

With my PR https://github.com/go-gitea/gitea/pull/18789 applied, login is succesfull.

**Comment by lunny** [comment] 2022-02-18 05:35
OK. Look at the error log
```
2022/02/17 23:29:05 ...dap/source_search.go:98:findUserDN() [D] Failed search using filter[(&(objectclass=posixAccount)(uid=johanvdw))]: <nil>
```
It should search different field per requested login name. If it's an email, search `mail `, if it's not an email, just search `uid`.

**Closed as completed** 2022-02-18 09:33 UTC
Labels: type/bug, issue/regression

**Comment by lunny** [comment] 2022-02-18 09:44
#18800 is another PR should partially fix this.

**Comment by johanvdw** [comment] 2022-02-19 11:09
> OK. Look at the error log
> 
> ```
> 2022/02/17 23:29:05 ...dap/source_search.go:98:findUserDN() [D] Failed search using filter[(&(objectclass=posixAccount)(uid=johanvdw))]: <nil>
> ```
> 
> It should search different field per requested login name. If it's an email, search `mail `, if it's not an email, just search `uid`.

No, the issue was that the username passed in the loginbox ("johanvdw") was passed, rather than the loginName stored for the user. My PR fixed that. I don't think it is a syncing issue. This login worked before, no recent changes were done to it.

With my fix applied, logging in works again as before. I can use both email and gitea username to login.

As I understand it , #18800 is actually the same fix that was applied previously in my PR(https://github.com/go-gitea/gitea/pull/18789/files#diff-61ff4979f4806bfe43709f4004297c6366b2baeb9fdf73e5c201d7ecd6b4beef) , except not specific to ldap. If it is fixed at that level, we probably can undo that change.

**Comment by lunny** [comment] 2022-02-19 15:37
```
2022/02/17 23:31:19 ...dap/source_search.go:98:findUserDN() [D] Failed search using filter[(&(objectclass=posixAccount)(uid=johan@fluves.com))]: <nil>
```
I think I'm wrong. As above there is a situation that when a ldap user login with email but his account didn't sync to Gitea. Then Gitea will find user with email address.

**Comment by lunny** [comment] 2022-03-18 07:26
Please fire another issue.
