### ISSUE TITLE
System level global webhook

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#7523] opened 2019-07-19 01:32 UTC
I prefer to add system level global webhooks UI on admin panel. Administrators of gitea instance could add or remove system webhooks.

All system webhooks will not be displayed in repositories webhook settings ui but only displayed on admin panel. When an event is triggered, then all system webhooks, organization webhooks and repository webhooks will be requested.

A system webhook will help administrator to do statistics/backup/update depends systems and etc.

**Comment by Mikaela** [comment] 2019-08-16 19:24
I think this is a duplicate of https://github.com/go-gitea/gitea/issues/4456

**Comment by 0x5c** [comment] 2019-08-17 01:00
@Mikaela
#4456 calls for user webhooks, that are essentially notifications.
This, however, calls for admin webhooks, which would run for *all* repositories on the instance.

**Comment by Mikaela** [comment] 2019-08-17 18:21
Actually it says:

> Feature Request: support for personal webhooks and site-wide webhooks
> ...
>  It is also useful to have site-wide webhooks that react on all repos for those who want to do some "logging to slack" kinda stuff.

and I think *site-wide webhooks* and *system level global webhooks* are the same thing, but I don't mind either way and probably won't comment here further.

**Closed as completed** 2019-09-06 01:06 UTC
Labels: issue/duplicate
