### ISSUE TITLE
Disallow merging if PR has been rejected

### ISSUE THREAD

**Issue by FryDay** [go-gitea/gitea#4785] opened 2018-08-24 17:33 UTC
If you request changes on a PR, you are still able to merge it. Github disallows merging if a PR is rejected.

**Comment by lafriks** [comment] 2018-08-24 17:45
Was not there issue already about this?

**Comment by FryDay** [comment] 2018-08-24 18:17
Not that I was able to find.

**Comment by lunny** [comment] 2018-08-25 12:37
@FryDay  I think a PR is rejected by someone could still be merged on Github.

**Comment by FryDay** [comment] 2018-08-26 21:35
Only someone with admin privileges, and you need to click through warnings to do it.

**Comment by lunny** [comment] 2018-08-27 02:41
@FryDay yes, we could follow that.

**Comment by 3l73** [comment] 2019-04-15 16:53
AFAIK the reject information stored inside of a review, that is connected to a comment.

In order to disable a pull request, all comments of an issue have to be process, checking if the rejection is still valid. 
This solution become a problem depending on the amount of comments.

One possible solution could be changing the relation between comment and review to issue and review.
This solution could lead to
1. a better runtime (less entries inside a loop)
2. a listing who reject a pull request
    - this could be used to remove reject status by an administrator
3. possibility to create a rule that a review is required in order to merge

**Comment by 3l73** [comment] 2019-04-15 17:04
Based on the solution described in the previous comment, there is a way with less refactoring.

The issue is extended with the review, the review remain inside the comment.
The issue indexer process the comments and create the review inside the issue based on the information inside the comment.

Did not know how often the indexer is running and how long it will take ro process the data.

**Comment by 3l73** [comment] 2019-04-21 09:21
I will have a look inside this issue.

Other issues going in the same direction:

- #3588 
- #996

**Closed as completed** 2019-09-12 08:32 UTC
Labels: issue/duplicate
