### ISSUE TITLE
Dashboard: Organization repositories no longer show up on dashboard (even when the user belongs to them)

### ISSUE THREAD

**Issue by bkraul** [go-gitea/gitea#6195] opened 2019-02-26 20:57 UTC
- Gitea version (or commit ref): 7afe81f 
- Operating system: docker, gitea/gitea:latest
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes: https://try.gitea.io/org/Arrow/dashboard
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
It used to, that all repositories for the organization you belonged to would show up on the repositories list on the dashboard page. This is no longer the case, and only your own repositories and other users' forks to which you were given express access show up. I am the owner of one of the organizations, and there are upwards of 50 repos in the organization, and I can see none of them. I cannot even search for repositories using Explore/Repositories. I have to end up browsing the organization and then searching in there.

Has behavior changed by design? Is there a property I need to turn on in order to see all the repositories of the organization I own on my dashboard? My user is not an admin user, but it is a user flagged as the organization's owner.

**Comment by lunny** [comment] 2019-02-27 12:03
Could you search them on the dashboard?

**Comment by bkraul** [comment] 2019-02-27 12:21
No, that's the point. I used to. Now I cannot. The only way I can search them is by going to Explore -> Pick the organization, and search within the organization.

**Comment by bkraul** [comment] 2019-03-08 15:00
Any news on this?

**Comment by lunny** [comment] 2019-03-16 14:38
Cannot reproduce this and could you reproduce this on https://try.gitea.io or https://gitea.com?

**Comment by bkraul** [comment] 2019-03-17 12:08
I am not sure if I will be able to replicate there, as this behavior involves a user that once was system admin, and then it was demoted to user but still is an organizational owner, but I will see what I have to work with and get back with you.

**Comment by bkraul** [comment] 2019-03-21 00:49
I was able to reproduce it on https://try.gitea.io . The source of the issue seems to be the **Private** flag for the organization. When the organization is set to **Public** which is the default on creating an organization, all the repositories show for all the members:

![image](https://user-images.githubusercontent.com/14616851/54727910-87d32100-4b48-11e9-8eca-5f98d69ea4b6.png)

But If you flag the organization as **Private (Visible only to organization members)**, the dashboard no longer shows any organizational projects, only your own projects, forks or collaborative projects. This happens no matter if you switch the dashboard context to the specific organization.

![image](https://user-images.githubusercontent.com/14616851/54727975-eac4b800-4b48-11e9-94b1-0af27528dbee.png)

![image](https://user-images.githubusercontent.com/14616851/54728033-42632380-4b49-11e9-9fa6-a423a5078c22.png)

I mean, you can see all the events in the feed, but all of the sudden, the organizational projects are no longer there. And these are not just organization members, they are **Owners** of the organization. I hope this helps.

**Comment by bkraul** [comment] 2019-03-21 00:56
I can also verify that the projects do show up if the organization is set to **Limited (Visible to logged in users only**), but, the idea is that we do not even want information about the organization or its projects seen by logged in users that are not part of the organization. But members, definitely should be able to see all organizational projects in dashboard.

**Comment by zeripath** [comment] 2019-03-21 07:39
The problem is that the API route /api/v1/repos/search is incorrect and needs to be changed.

**Comment by bkraul** [comment] 2019-04-16 18:49
@lunny Is there currently a milestone or a target version release for this?

**Comment by lunny** [comment] 2019-04-19 02:20
@bkraul Nobody are working on this. but I think this should be fixed on v1.8.0 or v1.8.1

**Closed as completed** 2019-05-15 15:24 UTC
Labels: type/bug
