### ISSUE TITLE
Add "federated projects"

### ISSUE THREAD

**Issue by SoniEx2** [go-gitea/gitea#6493] opened 2019-04-02 17:00 UTC
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Hi! It would be extremely cool if gitea had decentralized projects. A project is a collection of repos/branches that share commits. Projects don't care who originally created them, and repos/branches are shown in update order. Additionally, a project could have a shared issue tracker (this may use ActivityPub), but that's outside the scope of this proposal.

Projects are created from a commit, and while this does contain authorship information, it's not attached to any specific repo. This is a very useful property.

Due to being that lightweight, a project federates as a simple commit. Additionally, the issues also federate. This means projects transcend social structures, which means a BDFL can't just say an arbitrary set of issues don't belong in the issue tracker.

This would be a HUGE win for decentralized development. Additionally, and especially for big projects with a lot of momentum, this would encourage new developers to participate, as they wouldn't feel like anything they attempt to contribute will go unseen/unused.

**Comment by techknowlogick** [comment] 2019-04-02 20:09
Federation is duplicate of #184.

For multiple proposals please open multiple tickets so they could be tracked independently of one another.

**Closed as completed by techknowlogick** 2019-04-02 20:09 UTC
Labels: issue/duplicate

**Comment by SoniEx2** [comment] 2019-04-02 20:11
It's not multiple proposals, it's one proposal with multiple factors. It can't be tracked independently because the proposal also takes the protocol into account and the protocol is useless without the proposal.

**Comment by SoniEx2** [comment] 2019-04-02 20:19
kinda ironic that a proposal somewhat focused on having issues be wide open gets closed.
