### ISSUE TITLE
OpenID redirect loop

### ISSUE THREAD

**Issue by otbutz** [go-gitea/gitea#26097] opened 2023-07-24 14:16 UTC
### Description

I'm using gitea as an OpenID provider for Jenkins. Everything works as long as the user is already logged into gitea. If there's no valid Jenkins/gitea session, the user is properly guided to the gitea login page. The problem starts after hitting the Login button:

![2023-07-24_16-01](https://github.com/go-gitea/gitea/assets/22315436/17a99310-dc51-4469-b58e-96d6234dc5cb)

The initial POST request to `/user/login` contains the username and password entered in the login form. The server answers with a HTTP 303 status code and the location `/login/oauth/authorize` with a few query parameters. The `redirect_uri` parameter of this request points to my Jenkins instance: https://jenkins.mydomain.com/securityRealm/finishLogin

The problem is that this ends up in a redirect loop as `/login/oauth/authorize` will also answer with HTTP 303 pointing to `/user/login`. Firefox ultimately errors out with a `NS_ERROR_REDIRECT_LOOP`.

The authentication itself works though. I can successfully open gitea or jenkins afterwards with a valid user session.

The configuration in Jenkins is pretty barebones:

![2023-07-24_16-13](https://github.com/go-gitea/gitea/assets/22315436/81245762-193f-4866-8bb6-7e16baae01f3)

### Gitea Version

1.20.1

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Binary started via systemd behind a caddy reverse proxy.

### Database

PostgreSQL

**Comment by otbutz** [comment] 2023-07-24 14:24
The chain of requests from jenkins to the initial gitea login page:

![2023-07-24_16-23](https://github.com/go-gitea/gitea/assets/22315436/12490fbd-f619-4f1c-837f-8908779bd7ef)

**Comment by otbutz** [comment] 2023-07-24 14:29
The strange thing is the cookie set by the first call to `login/oauth/authorize`:

```
redirect_to=%2Flogin%2Foauth%2Fauthorize%3Fclient_id%3DXXXXXXXXXXXXXXXXXXXXXX20%26redirect_uri%3Dhttps%3A%2F%2Fjenkins.mydomain.com%2FsecurityRealm%2FfinishLogin%26response_type%3Dcode%26scope%3Dopenid%2520profile%2520groups%2520email%26state%3Dxxxxxxxxxxxxxxxxxx%26nonce%3Dxxxxxxxxxxxxxxxxxxxxx; Path=/; HttpOnly; Secure; SameSite=Lax
```

A redirect to a redirect?

**Comment by evgnblkn** [comment] 2023-07-25 10:22
I have the same problem. PgAdmin works well with the Gitea oauth provider, but Portainer and my own application are constantly getting to the login page. This has been around since version 1.19. Perhaps this is related to #20908 and #24767.

**Comment by MrGussio** [comment] 2023-07-26 07:28
Same thing happened for a colleague of mine this morning. Interesting enough, for me personally it does work, but unlike my colleague I have 2FA enabled, so I first see that page, and then the redirect does work correctly.

**Comment by evgnblkn** [comment] 2023-07-26 17:11
> I have the same problem. PgAdmin works well with the Gitea oauth provider, but Portainer and my own application are constantly getting to the login page. This has been around since version 1.19. Perhaps this is related to #20908 and #24767.

We found the cause of the loop, the redirect_uri parameter was not specified in the URL-encoded format. It might help in other cases too.

**Comment by m42e** [comment] 2023-10-07 04:34
@evgnblkn how did you solve it then?

**Comment by jimafisk** [comment] 2024-02-16 03:15
We're having the same issue using Gitea as an OAuth provider for our static websites (using https://plenti.co/).

> Everything works as long as the user is already logged into gitea

If there is already an active login directly to Gitea, it works for us as well.

> If there's no valid Jenkins/gitea session, the user is properly guided to the gitea login page. The problem starts after hitting the Login button

Same, the login page just refreshes when clicking "Sign in" and it `303`s in the console.

> This has been around since version 1.19

We noticed something similar, it used to work in prior versions but somewhere around this version (we're not sure exactly when), we started having this issue.

**Comment by jimafisk** [comment] 2024-02-16 23:28
> We found the cause of the loop, the redirect_uri parameter was not specified in the URL-encoded format.

Using [encodeURIComponent()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) ended up working for us too.

**Broken:**
```js
const url = authProvider.authUrl + env.cms.redirectUrl;
window.open(url, "_self", "");
```

**Working:**
```js
const url = authProvider.authUrl + encodeURIComponent(env.cms.redirectUrl);
window.open(url, "_self", "");
```

**Comment by wxiaoguang** [comment] 2024-02-17 02:49
@jimafisk thank you very much for the hint!

@otbutz could you confirm that it is the same problem? The "redirect_uri" isn't URL-encoded in your screenshot either.

**Comment by otbutz** [comment] 2024-02-19 08:19
Just to confirm but the `redirect_uri` should be stored as e.g `https%3A%2F%2Fjenkins.example.com%2FsecurityRealm%2FfinishLogin` ?

At least the builtin applications don't follow that either:

https://github.com/go-gitea/gitea/blob/5e72526da4e915791f03af056890e16821bde052/models/auth/oauth2.go#L59-L73

**Comment by wxiaoguang** [comment] 2024-02-19 08:28
> At least the builtin applications don't follow that either:

That's a different problem. For `RedirectURIs` in code, they should be stored as their raw value. These values should be encoded/decoded when used.

----

For the redirecting problem, I haven't got enough time to get a reproducible setup. So, if there would be a prepared reproducible environment/setup (eg: by docker compose), I could spend time on debugging it.

**Comment by Zettat123** [comment] 2024-02-19 08:35
Maybe #28529 is the same issue?

**Comment by wxiaoguang** [comment] 2024-03-05 02:39
> For the redirecting problem, I haven't got enough time to get a reproducible setup. So, if there would be a prepared reproducible environment/setup (eg: by docker compose), I could spend time on debugging it.

If there could be a reproducible environment/setup, I think we might be able to fix it in 1.22, I will spend time on fixing it. Otherwise the bug will be moved to next milestone ........

**Comment by wxiaoguang** [comment] 2024-03-07 01:12
I think most "redirect loop" could be fixed by:

-> Use strict protocol check when redirect #29642 

It would be helpful if you could build your own binary to test the patch. Thank you very much.

**Comment by wxiaoguang** [comment] 2024-03-07 06:11
The 1.21 nightly (pre-1.21.8) is ready, it is a stable release and will become 1.21.8 soon. Please take a try, if the problem is still not resolved, please help to provide more details. Thank you!

Get 1.21 nightly:

* Docker: https://hub.docker.com/r/gitea/gitea/tags?page=1&name=nightly
* Binary: https://dl.gitea.com/gitea/1.21/

**Comment by otbutz** [comment] 2024-03-07 08:19
> I think most "redirect loop" problems could be fixed by:
> 
> -> Use strict protocol check when redirect https://github.com/go-gitea/gitea/pull/29642

Confirmed :+1: 

I just tested the nightly version in a private window by trying to log in to our Jenkins instance. Everything works as expected without any funzies.

**Closed as completed** 2024-03-07 08:35 UTC
Labels: type/bug, issue/needs-feedback
