### ISSUE TITLE
Repo listings include all repos of org for restricted user

### ISSUE THREAD

**Issue by noerw** [go-gitea/gitea#16281] opened 2021-06-28 09:03 UTC
- Gitea version (or commit ref): 1.14.3
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
## Description

Context:
Have a restricted user that is member in an organization team with access to a subset of repos of that organization.

This restricted user will see all repos of that organization listed when visiting `/explore/repos` or `/<org>`.
Visiting the repo page of a repo that is listed, but not part of the team's access, will give a 404.

So there is a mistake in the repo list query for the explore & org page..

**Comment by wolfogre** [comment] 2022-12-27 07:31
I can't reproduce it in the latest version(1.19.0+dev-234-g90237d8ab). Maybe it's an outdated issue?

**Comment by lunny** [comment] 2022-12-27 13:22
Let's close it for now and please feel free to reopen it.

**Closed as completed by lunny** 2022-12-27 13:22 UTC
Labels: type/bug, issue/needs-feedback
