### ISSUE TITLE
gitea webhook empty POST variable

### ISSUE THREAD

**Issue by 8ctopus** [go-gitea/gitea#7700] opened 2019-08-01 10:35 UTC
- Gitea version (or commit ref): 1.9.0 (https://github.com/go-gitea/gitea/releases/tag/v1.9.0)
- Git version: 2.16.5
- Operating system: Centos 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Upgrading from gitea 1.8.3 to 1.9.0 breaks gitea webhooks of type application/x-www-form-urlencoded: the POST variable is empty and therefore doesn't contain the payload.

sample hook on receiver side:
`<?php`
`file_put_contents('/var/tmp/gitea-debug.log', var_export($_POST, true));`
`exit();`

result in 1.9.0:
`array (
)`

result in 1.8.3:
`array (
  'payload' => '{
  "secret": "***********",
  "ref": "refs/heads/master",
  "before": "3bc52c056257af7ae79fe5399f59f5de506b877c",
  "after": "3bc52c056257af7ae79fe5399f59f5de506b877c",
  "compare_url": "",
  "commits": [
    ...
}',
)`

UPDATE: It looks like the same issue as this one [https://github.com/go-gitea/gitea/issues/7692](https://github.com/go-gitea/gitea/issues/7692)
## Screenshots

![2019-08-01_152635](https://user-images.githubusercontent.com/13252042/62286775-daff9d80-b471-11e9-808d-745893aa10ce.png)

**Comment by 8ctopus** [comment] 2019-10-01 12:46
Problem is still present in version 1.9.3...

**Comment by 8ctopus** [comment] 2019-10-02 10:33
looks like the payload is no longer passed correctly.

webhook deliver() function code in 1.8.3

```
func (t *HookTask) deliver() {
	...
	req := httplib.Post(t.URL).SetTimeout(timeout, timeout).
		Header("X-Gitea-Delivery", t.UUID).
		Header("X-Gitea-Event", string(t.EventType)).
		Header("X-Gogs-Delivery", t.UUID).
		Header("X-Gogs-Event", string(t.EventType)).
		HeaderWithSensitiveCase("X-GitHub-Delivery", t.UUID).
		HeaderWithSensitiveCase("X-GitHub-Event", string(t.EventType)).
		SetTLSClientConfig(&tls.Config{InsecureSkipVerify: setting.Webhook.SkipTLSVerify})

	switch t.ContentType {
		case ContentTypeJSON:
			req = req.Header("Content-Type", "application/json").Body(t.PayloadContent)
		case ContentTypeForm:
			req.Param("payload", t.PayloadContent)
	}
```

and code in HEAD revision on master

```
func (t *HookTask) deliver() error {
	t.IsDelivered = true

	var req *http.Request
	var err error

	switch t.HTTPMethod {
	case "":
		log.Info("HTTP Method for webhook %d empty, setting to POST as default", t.ID)
		fallthrough
	case http.MethodPost:
		switch t.ContentType {
		case ContentTypeJSON:
			req, err = http.NewRequest("POST", t.URL, strings.NewReader(t.PayloadContent))
			if err != nil {
				return err
			}

			req.Header.Set("Content-Type", "application/json")

		case ContentTypeForm:
			var forms = url.Values{
				"payload": []string{t.PayloadContent},
			}

			req, err = http.NewRequest("POST", t.URL, strings.NewReader(forms.Encode()))
			if err != nil {

				return err
			}
		}
```

**Comment by vszakats** [comment] 2019-10-20 10:57
As of v1.9.4, the issue is still there. It seems that the `Content-Type: application/x-www-form-urlencoded` header is missing from the `POST` request. May be related to changing the http client from `GiteaServer` to `Go-http-client/1.1`:
```
POST / HTTP/1.1
Host: localhost:9090
User-Agent: Go-http-client/1.1
Content-Length: 4224
X-GitHub-Delivery: ffffffff-0000-0000-0000-ffffffffffff
X-GitHub-Event: push
X-Gitea-Delivery: ffffffff-0000-0000-0000-ffffffffffff
X-Gitea-Event: push
X-Gitea-Signature: 
X-Gogs-Delivery: ffffffff-0000-0000-0000-ffffffffffff
X-Gogs-Event: push
X-Gogs-Signature: 
Accept-Encoding: gzip

payload=[...]
```

Compared to `application/json` mode, where `Content-Type` is there:
```
POST / HTTP/1.1
Host: localhost:9090
User-Agent: Go-http-client/1.1
Content-Length: 2916
Content-Type: application/json
X-GitHub-Delivery: ffffffff-0000-0000-0000-ffffffffffff
X-GitHub-Event: push
X-Gitea-Delivery: ffffffff-0000-0000-0000-ffffffffffff
X-Gitea-Event: push
X-Gitea-Signature: 
X-Gogs-Delivery: ffffffff-0000-0000-0000-ffffffffffff
X-Gogs-Event: push
X-Gogs-Signature: 
Accept-Encoding: gzip

{
  "secret": [...]
```

**Comment by vszakats** [comment] 2019-10-20 11:22
It looks like this is what happened. Issued a PR to fix it.

**Comment by adelowo** [comment] 2019-10-20 14:37
Can we close this issue?

**Closed as completed** 2019-10-20 17:18 UTC
Labels: type/bug, issue/confirmed
