### ISSUE TITLE
Markdown files cannot be edited

### ISSUE THREAD

**Issue by a96219** [go-gitea/gitea#15932] opened 2021-05-20 06:52 UTC
- Gitea version (or commit ref): docker 1.15.0+dev-327-gc636ef8f1
- Git version:
- Operating system: centos 7
- Database (use `[x]`):
  - PostgreSQL

- Can you reproduce the bug at https://try.gitea.io:
  - [try.gitea.io/FreeSaltedFish/test](https://try.gitea.io/FreeSaltedFish/test)

**Comment by FreeSaltedFish** [comment] 2021-05-20 06:53
![image](https://user-images.githubusercontent.com/38235993/118932866-1c30ac80-b97b-11eb-919e-5e8d25d14af4.png)

**Comment by FreeSaltedFish** [comment] 2021-05-20 06:54
Click Edit to stay stuck in this interface

**Comment by silverwind** [comment] 2021-05-20 08:01
Check the browser console for any errors.

**Comment by FreeSaltedFish** [comment] 2021-05-20 08:29
> 检查浏览器控制台是否有任何错误。



> Check the browser console for any errors.

I didn't see any errors
This project can reproduce the problem:(try.gitea.io/FreeSaltedFish/test)[https://try.gitea.io/FreeSaltedFish/test]

**Comment by silverwind** [comment] 2021-05-20 08:35
Works fine for me when I edit one of the files I can access. Might be a browser cache problem of you had visited, try clearing it or `CTRL-F5` a few times.

**Comment by FreeSaltedFish** [comment] 2021-05-20 08:45
> Works fine for me when I edit one of the files I can access. Might be a browser cache problem of you had visited before, try clearing it or `CTRL-F5` a few times.

This is not true for all files, but only for some.
Can you edit the md document in my link above?

**Comment by FreeSaltedFish** [comment] 2021-05-20 08:46
> Works fine for me when I edit one of the files I can access. Might be a browser cache problem of you had visited before, try clearing it or `CTRL-F5` a few times.

When I delete parts of the file, I can open the edit page again

**Comment by silverwind** [comment] 2021-05-20 10:37
I forked your repo and indeed that seems to be some issue with the `GET https://try.gitea.io/silverwind/testedit/_edit/master/test.md` request timing out, seems like a backend bug.

**Comment by FreeSaltedFish** [comment] 2021-05-20 12:16
> I forked your repo and indeed that seems to be some issue with the `GET https://try.gitea.io/silverwind/testedit/_edit/master/test.md` request hanging, seems like a backend bug.

I updated my repo:https://try.gitea.io/FreeSaltedFish/test  

Test1.md is only one line more than test2.md.
but Test1.md cannot be edited,Test2.md can be edited.

Test3.md is only one more '\n' than test2.md
but Test3.md cannot be edited,Test2.md can be edited.

Is it caused by some special sequence of bytes?

**Comment by noerw** [comment] 2021-05-21 12:26
This is a really weird one.
The bug seems not entirely stable, maybe a race condition
I suspect this is because we have `Transfer-Encoding: chunked` for HTTP, and somehow somewhere the chunk length is miscalculated, sending non-zero when the response is actually finished..?

edit: I bisected, 270aab429ef025df9a0b9bf9e3982729ae8df449 is the bad commit (from PR #15667)
@zeripath any ideas?

**Comment by FreeSaltedFish** [comment] 2021-05-28 08:03
Will this bug be fixed in the next version?

**Comment by noerw** [comment] 2021-05-29 11:41
The bug didn't exist in the last release, this only happens in the current development version. So yes, we try to not introduce new bugs in releases, but can't make any guarantees. Feel free to look into it yourself if you want to get it fixed asap.

@zeripath I studied your changes in your `cat-file --batch` PR for a while, but didn't find any obvious bug. Two potential error conditions come to mind;
1. somewhere we read the wrong amount of bytes, or return the wrong size
2. there is a racecondition for reading multiple files
  - I see on edit page, that there are two calls to `blob.DataAsync()`, one for the file itself, and one for `.editorconfig`. Could there be a racecondition?
  - (I don't understand where `CatFileBatch()` ensures results are returned in order)

For reference, here we call to read the file
https://github.com/go-gitea/gitea/blob/fb6c6895fa10328821d53c0f2d7cb7d6540a2689/routers/repo/editor.go#L104-L125

which is similar to the (working) codepath for viewing a file:
https://github.com/go-gitea/gitea/blob/fb6c6895fa10328821d53c0f2d7cb7d6540a2689/routers/repo/view.go#L497

**Comment by zeripath** [comment] 2021-05-29 13:15
There's not really any ordering as writes and reads shouldn't really be Asynchronous writes and reads. I guess I might have missed one?

I'd have to replicate and test. The trick might be to re-get the cat-file-batch triple before use.

**Comment by zeripath** [comment] 2021-05-29 18:31
Ah - I think there might actually be an issue here!

The Close!

**Comment by zeripath** [comment] 2021-05-29 18:43
hmm... still can't replicate this. 

```patch
From ee9f0a3970d5e5a91f236b25672fa24a79d7ac27 Mon Sep 17 00:00:00 2001
From: Andrew Thornton <art27@cantab.net>
Date: Sat, 29 May 2021 19:41:29 +0100
Subject: [PATCH] Close the dataRC reader sooner

Fix #15932

Signed-off-by: Andrew Thornton <art27@cantab.net>
---
 routers/repo/editor.go | 13 ++++++++++++-
 1 file changed, 12 insertions(+), 1 deletion(-)

diff --git a/routers/repo/editor.go b/routers/repo/editor.go
index 2cc5c1e7f..3b74373c2 100644
--- a/routers/repo/editor.go
+++ b/routers/repo/editor.go
@@ -106,7 +106,13 @@ func editFile(ctx *context.Context, isNewFile bool) {
 			ctx.NotFound("blob.Data", err)
 			return
 		}
-		defer dataRc.Close()
+		closed := false
+
+		defer func() {
+			if !closed {
+				dataRc.Close()
+			}
+		}()
 
 		ctx.Data["FileSize"] = blob.Size()
 		ctx.Data["FileName"] = blob.Name()
@@ -122,6 +128,11 @@ func editFile(ctx *context.Context, isNewFile bool) {
 		}
 
 		d, _ := ioutil.ReadAll(dataRc)
+		if err := dataRc.Close(); err != nil {
+			log.Error("Error whilst closing blob data: %v", err)
+		}
+		closed = true
+
 		buf = append(buf, d...)
 		if content, err := charset.ToUTF8WithErr(buf); err != nil {
 			log.Error("ToUTF8WithErr: %v", err)
-- 
2.31.1

```

Could you try applying the above patch to see if that solves your issue? (if copying&pasting you may need to add a blank line at the end)

**Comment by noerw** [comment] 2021-05-29 22:04
@zeripath yeah nice, that fixes it!

**Comment by zeripath** [comment] 2021-05-29 22:24
Strange that I can't replicate. There must be a race but I don't quite understand how.

**Closed as completed** 2021-05-30 16:38 UTC
Labels: type/bug
