### ISSUE TITLE
Gitea in docker container doesn't display my commits

### ISSUE THREAD

**Issue by xakaitetoia** [go-gitea/gitea#12927] opened 2020-09-23 16:38 UTC
- Gitea version (or commit ref): docker - gitea/gitea:latest
- Git version:
- Operating system: Ubuntu 20.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Hello team,
I am using the latest gitea version in docker (gitea/gitea:latest) and when creating a repo I follow the instructions from a machine and although I succeed on creating the initial README.MD file and pushing it successfully, I do not see any update in the dashboard with my commits. See screenshot. Still remains the same page with instructions. Pulling and pushing though works fine as if there were some data. It just doesn't display any contents on the specified repo

This doesn't happen if i download the gitea:1.12 version though.

## Screenshots
~/docker/gitea/test$ git push -u origin masterUsername for xxx
Password for 'x: 
Enumerating objects: 3, done.
Counting objects: 100% (3/3), done.
Writing objects: 100% (3/3), 207 bytes | 207.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0)
remote: . Processing 1 references
remote: Processed 1 references in total
To xxxxxx/test.git
 * [new branch]      master -> master
Branch 'master' set up to track remote branch 'master' from 'origin'.

![gitea](https://user-images.githubusercontent.com/24432587/94042090-073b5380-fdc3-11ea-849a-95dc210e9006.png)

**Comment by zeripath** [comment] 2020-09-25 18:03
This should only happen if the post-receive hook hasn't run.

Was this repository created on a different version of Gitea and resynchronize hooks not run?

**Comment by xakaitetoia** [comment] 2020-09-25 18:07
No I did it on a fresh host with native docker installer and just downloaded the latest gitea version. If I docker-compose down and delete all gitea images / created volumes again and specify 1.12 version in docker-compose.yml then it's working fine.

**Comment by zeripath** [comment] 2020-09-25 19:07
Well we will need some logs.

I can't replicate this issue.

**Comment by wxiaoguang** [comment] 2022-01-28 07:54
It's caused by the out-sync IsEmpty state. Has been fixed by:

* https://github.com/go-gitea/gitea/pull/18088

**Closed as completed** 2022-01-28 07:55 UTC
