### ISSUE TITLE
Cant create a pull-request if i used a Template

### ISSUE THREAD

**Issue by DjSni** [go-gitea/gitea#28953] opened 2024-01-27 09:36 UTC
### Description

As the title says, if a repo from a template, I cannot create pull requests. I always get an error 500 as you can see in the screenshot.

As can also be recreated here https://try.gitea.io/DjSni/Test/.

### Gitea Version

 1.22.0+dev-611-g01acd1eea

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/31524614/b86a5ded-20c7-4d48-aafe-8866e4265dbf)
![image](https://github.com/go-gitea/gitea/assets/31524614/9dce616a-fc45-4c32-b28e-55e767d1e049)

### Git Version

build in

### Operating System

Docker

### How are you running Gitea?

i used https://try.gitea.io/

### Database

MySQL/MariaDB

**Comment by yp05327** [comment] 2024-01-29 05:55
caused by #28469, forgot setting `ObjectFormatName` which should not be null when creating repos from templates.

**Comment by a1012112796** [comment] 2024-03-05 03:23
fixed by #28969 ? @yp05327 @lunny

**Comment by lunny** [comment] 2024-03-05 03:59
Yes, I can confirm this has been resolved.

**Closed as completed by lunny** 2024-03-05 03:59 UTC
Labels: type/bug, issue/needs-feedback, issue/confirmed, skip-changelog
