### ISSUE TITLE
Typing in comment box seems to have fundamental race condition, scrambles the order of letters on slow devices

### ISSUE THREAD

**Issue by ell1e** [go-gitea/gitea#21883] opened 2022-11-21 00:11 UTC
### Description

Typing in comment box seems to have fundamental race condition and seems to scramble the order of letters on slow devices in the comment box. Needless to say, this makes typing kind of a huge pain. I can reproduce this on my Allwinner PinePhone in Firefox with codeberg.org at least, I imagine it might also show with something like an old Raspberry 2 or 3 if you type fast enough.

(I assume it also reproduces on the demo site, I just don't have the login credentials for that one here rn since I'm traveling, that's also why I'm using the phone and ran into this)

### Gitea Version

1.17.3+104-g5904fd9

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Accessing it via Linux Wayland (not Android)

### How are you running Gitea?

Using Codeberg instance

**Comment by yardenshoham** [comment] 2022-11-22 12:03
Can you post a video showing the issue?

**Comment by yardenshoham** [comment] 2022-11-22 16:01
I'm not able to reproduce

**Comment by wxiaoguang** [comment] 2023-10-01 15:10
This problem should have been fixed by " Introduce GitHub markdown editor, keep EasyMDE as fallback #23876 ", now the editor uses native textarea, there shouldn't be any input problem.

**Closed as completed by wxiaoguang** 2023-10-01 15:10 UTC
Labels: type/bug
