### ISSUE TITLE
Support stemming / partial matches / unicode normalizing in issue search

### ISSUE THREAD

**Issue by xak2000** [go-gitea/gitea#3448] opened 2018-02-02 17:25 UTC
As [mentioned early](https://github.com/go-gitea/gitea/pull/530#discussion_r102756415) by @sha-red, the issue search should support:

- Short [n-grams](http://www.blevesearch.com/docs/Token-Filters/#n-gram:c38efc402d8771527a225c32b59be157) to allow partial matches (an issue tracker won't work without partial matching).
  _Not sure what is it._

- Strong [Unicode normalizing](http://www.blevesearch.com/docs/Token-Filters/#unicode-normalize:c38efc402d8771527a225c32b59be157) (because of diacritical letters).
  _Allows to find `fällen` by typing `fallen`._

- Multi-lingual [stemming](http://www.blevesearch.com/docs/Token-Filters/#stemmer:c38efc402d8771527a225c32b59be157).
  _Allows to find `fallen` by typing `fall`._

- Also it should be possible to search by multiple words even when they are not near each other in the text (not sure how this ablility is called in terms of [bleeve](http://www.blevesearch.com)).

  _For example, if some issue has `some english comment` text in the description, then it should be able to find this issue by typing `some comment` in the search box. For now such issue will not be found._

**Comment by techknowlogick** [comment] 2022-04-13 01:45
closing as dupe of https://github.com/go-gitea/gitea/issues/2967

**Closed as completed by techknowlogick** 2022-04-13 01:45 UTC
Labels: issue/duplicate
