### ISSUE TITLE
[Bug] User dashboard doesn't have forward-slashes unlike other pages, resulting in incorrectly generated "pagination" navigation links for subpath-enabled instances

### ISSUE THREAD

**Issue by OdinVex** [go-gitea/gitea#29533] opened 2024-03-02 04:35 UTC
### Description

After logging in (at the user dashboard), users are presented with their commit history and such...but the navigation at the bottom does not use correct links (subpath issue). **Everywhere else they appear to be correct**, but here is the actual HTML (cleaned up for sake of posting):

```
<div class="center page buttons">
  <div class="ui borderless pagination menu">
    <a class="disabled item navigation">
      <span class="navigation_label">First</span>
    </a>
    <a class="disabled item navigation">
      <span class="navigation_label">Previous</span>
    </a>
    <a class="active item gt-content-center">1</a>
    <a class="item gt-content-center" href="/SUBPATH?page=2&amp;date=">2</a>
    <a class=" item navigation" href="/SUBPATH?page=2&amp;date=">
      <span class="navigation_label">Next</span>
    </a>
    <a class=" item navigation" href="/SUBPATH?page=2&amp;date=">
      <span class="navigation_label">Last</span>
    </a>
  </div>
</div>
```

There is a missing forward-slash after `SUBPATH`. **All other links generated by Gitea appear to be correct (`/SUBPATH/`).**

I believe the issue is in [paginate.tmpl](https://github.com/go-gitea/gitea/blob/main/templates/base/paginate.tmpl), the way links are generated using `{{$.Link}}` instead of `{{$.Link}}/` or perhaps `{{AppSubUrl}}/`? I don't do Go. All of that paginating uses broken linkage.

I do use Forgejo, but the issue is present in Gitea as well.

### Gitea Version

1.21.3

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Docker behind a reverse-proxy with a subpath.

### Database

MySQL/MariaDB

**Comment by wxiaoguang** [comment] 2024-03-02 04:48
If I understand correctly, that's by design. In Gitea, the URLs are always considered to equal no matter they have trailing slash or not.

So maybe you could make your reverse proxy to serve `http://.../subpath` as `http://.../subpath/`?

**Comment by wxiaoguang** [comment] 2024-03-02 04:49
> Without the forward-slash users are told to login again (Gitea destroys the session maybe?).

I think the "login" (cookie) problem is related to the cookie path. The cookie is only set on "/subpath/" IIRC ......

**Comment by wxiaoguang** [comment] 2024-03-02 05:03
After looking into the problem:

1. The "Link" can't have trailing slash, because it is heavily used in code like this: `{{.Link}}/other-path`. It would cause double-slashes if there is a trailing slash:
    * `//other-path` : it is even worse, because browsers would use it as "http://other-path".
    * `/subpath//other-path`: not a good URL path ....
2. The cookie is only set on "/subpath" (for security), so only "/subpath/" accesses could use it?
3. The workaround could be: make reverse proxy always redirect all "/subpath?..." requests to "/subpath/?...."

To completely fix the problem, it needs more designs & improvements ..... not that easy by a simple fix.

**Comment by wxiaoguang** [comment] 2024-03-02 05:21
Oops .... I found the root problem now. That's my fatal (regression of #24107)

->  Fix incorrect cookie path for AppSubURL #29534

**Comment by wxiaoguang** [comment] 2024-03-02 17:03
More details in https://github.com/go-gitea/gitea/pull/29534#issuecomment-1974851486

If you focus on "fixing the trailing slash", I could remove the "fix" operation from that PR, and keep this issue open.

**Comment by wxiaoguang** [comment] 2024-03-02 17:10
> Edit: I took a peek around, I think maybe something in `templates/user/dashboard/feeds.tmpl` could address it? `{{template "base/paginate" .}}` That period, does that help to generate a link?

Nope. The `dot syntax` is a Golang template syntax, it means "pass all current data into the sub template"

**Comment by lunny** [comment] 2024-03-03 02:18
resolved by #29534

**Comment by wxiaoguang** [comment] 2024-03-03 03:59
> original fixer misunderstood this bug because another was found at the same time.

Well, TBH I do not think I misunderstand this issue (actually I won't call the "slash" problem is a "bug").

Maybe you misunderstand the problem. I will quote my explanations and summarize them again:

1. The fact is: it is a requirement that making Gitea work with both `https://host/SUBPATH` and `https://host/SUBPATH/`, the document has said so:
    * https://docs.gitea.com/administration/reverse-proxies#apache-httpd-with-a-sub-path
    * `# Note: no trailing slash after either /git or port`
2. Based on the fact, a URL `href="/SUBPATH?page=2...` should work, it doesn't need an extra slash.
3. Gitea never adds extra slash to a full path
    * so you only see: `https://host/SUBPATH` , `https://host/SUBPATH/user`, `https://host/SUBPATH/user/repo`
    * you won't see: `https://host/SUBPATH/` , `https://host/SUBPATH/user/`, `https://host/SUBPATH/user/repo/`
4. The root problem of your bug report is: "Without the forward-slash users are told to login again (Gitea destroys the session maybe?)."
    * I think it is caused by incorrect cookie path
    * After the fix (29534), I think it should have been resolved. Users won't get logout, nor they need to "manually edit the URL"


I don't see why you wouldn't follow the document and why you insist to add an extra trailing slash for some links, I don't see such a real use-case for end users either.

If you think the trailing slash is a must, please show some real bad cases for no-trailing-slash. Without a real bad case, I couldn't figure out what you mean.

**Comment by wxiaoguang** [comment] 2024-03-03 04:03
> Calling #29534 a fix is a hackjob following non-standard practice to _assume_ a file is a directory to circumvent fixing the issue.

As I explained before, Gitea requires to make "/SUBPATH" the same as "/SUBPATH/". Since it is a "proxy path", it is not  related to file or directory. There is no file nor directory in this case.

**Comment by wxiaoguang** [comment] 2024-03-03 04:10
>  https://docs.gitea.com/administration/reverse-proxies#apache-httpd-with-a-sub-path
> `# Note: no trailing slash after either /git or port`

The document was written there to help users configure their instances correctly. If some users don't follow, then that's another problem.

As I explained above, Gitea never adds extra slash to the full path. So if you think it is a problem, then not only "pagination"  is affected, a lot of hard-coded links are also affected, then it is not a simple problem, it is a new proposal to totally refactor the Gitea's link system.

Would you like to edit the title to clarify what you mean? For example: `Always add an extra slash when the AppSubURL is used without other sub paths` ("pagination" is just a tip of the iceberg)

**Comment by wxiaoguang** [comment] 2024-03-03 04:28
> Yes, Gitea DOES add forward-slashes, you can grep the code for it all over.

I guess I have explained many times ... `Gitea never adds extra slash to a full path`:

    * so you only see: `https://host/SUBPATH` , `https://host/SUBPATH/user`, `https://host/SUBPATH/user/repo`
    * you won't see: `https://host/SUBPATH/` , `https://host/SUBPATH/user/`, `https://host/SUBPATH/user/repo/`

There could be more cases that the SUBPATH misses the correct trailing slash .... for example, I just fixed some: #29535

Anyway, if you believe only the "dashboard" page needs to be fixed, it's fine to me. It could be fixed by this:

->  Add an trailing slash to dashboard links #29555 


You could apply this patch to your instance to see whether it satisfy your requirement, I will add some tests later.

**Comment by wxiaoguang** [comment] 2024-03-03 04:45
Oh one more thing, since we have a long discussion for this simple problem, I think maybe we could try to improve the communication in the future.

What I understand:

* Gitea requires to make "/SUBPATH" and "/SUBPATH/" work equivalently.
* "SUBPATH" is only a proxy path.
* So the trailing slash shouldn't be a hard requirement, so using "/SUBPATH" should be right in Gitea's deployment.

What you proposed if I understand correctly now:

* Some users need to deploy Gitea in a subpath where the subpath could point to an existing file, they don't follow the document.
* There are some mentioned RFC standards (could you share the link? I'd like to take a deep look).


Fortunately, eventually, we could understand each other better. 🙏 In the future if there would be some real cases for a proposal/bug report, I think I could catch you up more quickly. Thank you again for the constructive discussion.

**Comment by wxiaoguang** [comment] 2024-03-03 04:47
>  I also had to disable Notifications because of an Apache bug with reverse-proxies that prevents multiple threads (ends up blocking new threads because of concurrently held threads)

Do you mean this? #19265 I also participated in it .... 🤣

**Closed as completed** 2024-03-04 01:02 UTC
Labels: type/bug, issue/needs-feedback
