### ISSUE TITLE
Local time zone in timestamps

### ISSUE THREAD

**Issue by mozoh** [go-gitea/gitea#13925] opened 2020-12-10 03:06 UTC
- Gitea version (or commit ref): 1.14.0+dev-260-g7bc0c8cff
- Git version: ?
- Operating system: docker
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/explore/repos
  - [ ] No
- Log gist: n/a

## Description

Popup timestamps are always in UTC, but not browser timezone wherever I am.
There is a closed issue about this https://github.com/go-gitea/gitea/issues/6004, but seems like it is being reproduced again.

## Screenshots

![image](https://user-images.githubusercontent.com/42132525/101715894-dec41b00-3ace-11eb-9ce0-e4f3442b8a09.png)

**Comment by zeripath** [comment] 2020-12-11 08:15
Paging @silverwind - is it possible recent changes to js have broken this?

**Comment by silverwind** [comment] 2020-12-11 08:44
No, I've never touched those. I remember suggesting them to be converted in JS to browser timezone but I think @lunny persisted that they should render in the server timezone.

**Comment by Colin5887** [comment] 2020-12-11 21:48
I've tested 1.9.0, 1.10.0, 1.11.0 and 1.12.0. They all have the same issue. This is also reproducible in https://try.gitea.io

Here: I create a repo 4 seconds ago and it's marked to be an operation yesterday.
![image](https://user-images.githubusercontent.com/30656548/101957930-7ef87c00-3c56-11eb-8e06-528d33c7cafd.png)

BTW, I'm at AEDT.

**Comment by lunny** [comment] 2021-01-01 16:38
See https://docs.gitea.io/en-us/config-cheat-sheet/#time-time . You can change the default time zone.

**Comment by Colin5887** [comment] 2021-01-01 22:12
@lunny I promise I change that and it works......partially works.

It only changes the time when the mouse hovers on the commit and the time IS correct now.
However, the table of contributions is still incorrect. A commit made at 9:30 is still marked as yesterday's work.
It is reproducible on https://try.gitea.io as well.

**Comment by Colin5887** [comment] 2021-01-01 22:14
@lunny The problem is not the time in the text format but the table. 

I mean, the table:
![image](https://user-images.githubusercontent.com/30656548/103447101-da101280-4cda-11eb-8af9-b8fe78a9c665.png)

**Comment by lunny** [comment] 2021-01-02 02:09
@Colin5887 Your problem is not the same as this one. I think you can create a new issue so that we can track that.

**Comment by Colin5887** [comment] 2021-01-02 03:00
@lunny Thanks, a new issue is created here: https://github.com/go-gitea/gitea/issues/14215

**Comment by mozoh** [comment] 2021-01-02 03:20
Why the issue has been closed? Change timezone on server is not the real solution.

**Comment by lunny** [comment] 2021-01-02 03:22
@mozoh see my reply https://github.com/go-gitea/gitea/issues/13925#issuecomment-753341604

**Comment by mozoh** [comment] 2021-01-02 03:28
Your reply is about changing default, but not for local timezone. Every client can have its own timezone, different from the server. So, there will no solution for this as i understand.

**Comment by silverwind** [comment] 2021-01-03 14:12
Yes, we need some JS that runs during page load that converts timestamp to local. Should probably be inline so wrong timestamps never even render (can't put it in the main js bundle because that takes time to load).

**Comment by noerw** [comment] 2021-01-09 10:26
this similar to / the same as #6087

**Comment by lunny** [comment] 2021-01-11 14:02
#6087 is for heatmap, this one is the time on feeds .

**Comment by yardenshoham** [comment] 2023-04-29 17:06
Fixed by #23988

**Closed as completed by yardenshoham** 2023-04-29 17:06 UTC
Labels: type/proposal, topic/ui
