### ISSUE TITLE
translation display issues

### ISSUE THREAD

**Issue by csthenry** [go-gitea/gitea#27101] opened 2023-09-16 12:56 UTC
### Description

There is a problem with Mirror Configuration in the repository settings page as shown in the screenshot

### Gitea Version

1.20.4

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/32993468/1646bd5e-b1ef-4133-9789-f54e33797db0)

### How are you running Gitea?

docker

### Database

MySQL/MariaDB

**Comment by lng2020** [comment] 2023-09-17 14:17
Can u provide the procedure to reproduce? It works well for me.

**Comment by wxiaoguang** [comment] 2023-09-17 14:20
> Can u provide the procedure to reproduce? It works well for me.

`1.20.4` . I guess the problem is that the locale files in 1.20.4 are out-of-sync

**Comment by lng2020** [comment] 2023-09-17 14:44
> > Can u provide the procedure to reproduce? It works well for me.
> 
> `1.20.4` . I guess the problem is that the locale files in 1.20.4 are out-of-sync

Indeed. The current zh-CN lacks the translation of `settings.docs.pull_mirror_instructions`, so we just wait for the gitea bot to sync.

**Comment by wxiaoguang** [comment] 2023-09-17 15:03
> Indeed. The current zh-CN lacks the translation of `settings.docs.pull_mirror_instructions`, so we just wait for the gitea bot to sync.

There won't be any sync

**Comment by denyskon** [comment] 2023-10-19 20:44
Closing as will be solved with next release

**Closed as completed by denyskon** 2023-10-19 20:44 UTC
Labels: type/bug
