### ISSUE TITLE
Repository migration: repository description not synced

### ISSUE THREAD

**Issue by MPeti1** [go-gitea/gitea#17626] opened 2021-11-12 18:11 UTC
### Gitea Version

v1.15.5

### Git Version

2.30.2

### Operating System

Raspbian Buster

### How are you running Gitea?

I'm building Gitea myself for ARM32 with the official and unmodified rootless Dockerfile.
I then run the container with docker compose.

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

Reproduction of the behavior can be found here: https://try.gitea.io/MPeter/andOTP

The migration source repository has this description, at the top right of the page:
> Open source two-factor authentication for Android

The problem is that the resulting repo in Gitea has this as the description instead:
> No Description

### Screenshots

Repository with description on Github: 
![image](https://user-images.githubusercontent.com/9215491/141514358-f392745a-99ff-425d-bf46-0ee74c1d417b.png)

Migrated repository without description on Gitea:
![image](https://user-images.githubusercontent.com/9215491/141514455-84eb8e37-8f4f-443c-86d3-bae7e43073bc.png)

**Comment by lunny** [comment] 2021-11-15 09:59
Mirror will not copy the description I think.It just mirrors git data and will not invoke API.

**Comment by fredrikekre** [comment] 2021-11-16 12:37
> It just mirrors git data and will not invoke API.

Are you sure about that? The tags/topics are synced from GitHub and that is not part of the git data.

**Comment by lunny** [comment] 2021-11-16 13:01
Hm, looks like I'm wrong. But looks like there is no problem with the code https://github.com/go-gitea/gitea/blob/main/modules/migrations/github.go#L209

**Comment by 99rgosse** [comment] 2021-11-16 15:20
When you make a migration, you can specify the description 

![image](https://user-images.githubusercontent.com/61579380/142012365-637cc75a-b4e6-4603-be4c-298e1a59a6ea.png)

Seems that maybe we can check that if there is no description that would override the original repository description

**Comment by lunny** [comment] 2021-11-16 15:42
It has checked, if you input a description, then use your new input. Otherwise will get from external repository's via API.

**Comment by MPeti1** [comment] 2021-11-16 19:47
> It has checked, if you input a description, then use your new input. Otherwise will get from external repository's via API.

Sorry, I don't underatand. Is this current stable or dev release behavior?

**Comment by 99rgosse** [comment] 2021-11-17 07:58
I can confirm it is the behavior on current stable : 

the migrated repository does not import the description even if you do not put anything in the box when importing.
Tested on gitlab & github

**Comment by lunny** [comment] 2021-11-17 09:49
Ah, right it should be `if opts.Description == ""`

**Comment by 99rgosse** [comment] 2021-11-17 10:10
> Ah, right it should be `if opts.Description == ""`
I thought too, but, what is strange is that 
`	if opts.Description != "" {
		repo.Description = opts.Description
	}`
works perfectly, but not the other way around... I suspect there may be some formatting issue ?

**Comment by lunny** [comment] 2021-11-17 11:18
> > Ah, right it should be `if opts.Description == ""`
> > I thought too, but, what is strange is that
> > `	if opts.Description != "" { 		repo.Description = opts.Description 	}`
> > works perfectly, but not the other way around... I suspect there may be some formatting issue ?
> 
> Edit : Nope, the PlainGitDownloader does not have the "repo description" attribute. Checking to add this

They are different entry for git and github. And `topics` migrated.

**Comment by lunny** [comment] 2021-11-23 05:02
closed by #17727

**Closed as completed by lunny** 2021-11-23 05:02 UTC
Labels: type/bug
