### ISSUE TITLE
Long gitea-actions log stops output at ~3hours and job failure

### ISSUE THREAD

**Issue by RobertBerger** [go-gitea/gitea#32694] opened 2024-12-02 22:22 UTC
### Description

This[1], which calls this[2] keeps on running 

![gitea-1](https://github.com/user-attachments/assets/542c4d4a-5c4e-43db-987d-02b58a5b0144)

... but call-use-uninative-core-image-minimal-local-source-mirror stops around 3 hrs with logs and I can not see the error.

[1] https://github.com/RobertBerger/gitea-yocto-build/blob/master/.gitea/workflows/00.01-release.yml
[2] https://github.com/RobertBerger/gitea-yocto-build/blob/master/.gitea/workflows/03-use-uninative-core-image-minimal-local-source-mirror.yml

I already changed ENDLESS_TASK_TIMEOUT = 6h

and added timeout: 6h to my workflow.

gitea/gitea:1.22.4
gitea/act_runner:0.2.11

both are containers

### Gitea Version

gitea/gitea:1.22.4

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

https://drive.google.com/file/d/1-bJ2tCk3zqCteGW8dh_TuGUh2vqGoLZn/view?usp=sharing

### Git Version

whatever came with the docker container

### Operating System

Linux/docker container

### How are you running Gitea?

```
version: "3.8"

networks:
  gitea-latest:
    external: false

services:
  server-latest:
    image: gitea/gitea:1.22.4
    container_name: gitea-latest
    environment:
      - USER_UID=1001
      - USER_GID=1001
    restart: always
    networks:
      - gitea-latest
    volumes:
      - /appdata/gitea-latest/data:/data
      - /appdata/gitea-latest/git:/var/lib/gitea/git
      - /home/git/.ssh/:/data/git/.ssh
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8940:3000"
      - "2226:22"
  runner:
    image: gitea/act_runner:0.2.11
    restart: always
    depends_on:
      - server-latest
    volumes:
      - /appdata/act_runner/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - GITEA_INSTANCE_URL=http://192.168.42.182:8940
      - GITEA_RUNNER_NAME=runner-182
      - GITEA_RUNNER_LABELS=ubuntu-latest:docker://node:16-bullseye,ubuntu-22.04:docker://node:16-bullseye,yocto-build-walnascar:docker://reliableembeddedsystems/poky-container:2024-03-11-master-local-icecc-ub22-doc-spdx
      - GITEA_RUNNER_REGISTRATION_TOKEN=I4MFCivMcJH1dLobtSs1tn44LT8GU1rfxNXZSV9T
# langdale:
# GITEA_RUNNER_LABELS=ubuntu-latest:docker://node:16-bullseye,ubuntu-22.04:docker://node:16-bullseye,yocto-build-langdale:docker://reliableembeddedsystems/poky-container:2023-05-24-master-local-icecc-ub20-doc-action
```

### Database

None

**Comment by RobertBerger** [comment] 2024-12-02 22:23
Note: I did not try on the Gitea demo site

**Comment by Zettat123** [comment] 2024-12-03 07:25
Thank you for reporting this issue. 

I noticed that you added `timeout: 6h` to your workflow. But `timeout` is a configuration item of act_runner and should not be added to the workflow file. Also, Gitea does not support the timeout for jobs (see [this doc](https://docs.gitea.com/usage/actions/comparison#jobsjob_idtimeout-minutes)). So I think setting a timeout will not help with this issue. 

From the log, I found that the log ended at `Compress Artifacts after build` step without errors. I want to know when the log stops, is the task status "Running" or has it turned into "Failure"? If it has turned into "Failure", has it been running for longer than `ENDLESS_TASK_TIMEOUT`?

**Comment by RobertBerger** [comment] 2024-12-03 10:44
As you said, I also see no error. The `Compress Artifacts after build` step just takes the build artefacts and makes tarballs out of them. I tried splitting it into more tarballs, but this does not help either.

As you can see from the yellow (spinning) clock one might think it still runs after 10+ hours.

![gitea-1](https://github.com/user-attachments/assets/95a40b92-fbce-4586-9c67-2c785af0a09f)

The job failed:

![gitea-2](https://github.com/user-attachments/assets/a65211ec-5c62-4770-9a32-fc1fedbd4ce6)

ENDLESS_TASK_TIMEOUT = 6h

... but it fails pretty much exactly at 3h.

Is there any way to see if it read ENDLESS_TASK_TIMEOUT = 6h?

Here is also my app.ini

[app.ini.txt](https://github.com/user-attachments/files/17991498/app.ini.txt)

Where should I set the timeout of act_runner?

**Comment by RobertBerger** [comment] 2024-12-03 11:31
Maybe let me add. If I don't build the 3 things (`uninative, core-image-minimal, core-image-sato-sdk`) but only `uninative, core-image-sato-sdk` it works, since it takes significantly less time.

**Comment by RobertBerger** [comment] 2024-12-03 15:08
It looks like it does what it's supposed to do, but gets stuck after 3 hours somehow. Let me do further experiments.

**Comment by RobertBerger** [comment] 2024-12-03 18:26
The next build step stops at 3 hours with a failure, although there is no obvious failure visible.

**Comment by Zettat123** [comment] 2024-12-04 07:03
> Where should I set the timeout of act_runner?

You could configure your act_runner with a configuration file by following [this instruction](https://gitea.com/gitea/act_runner#configuration).

**Comment by Zettat123** [comment] 2024-12-04 07:44
> Maybe let me add. If I don't build the 3 things (`uninative, core-image-minimal, core-image-sato-sdk`) but only `uninative, core-image-sato-sdk` it works, since it takes significantly less time.

I see. Building `core-image-sato-sdk` took more than 2 hours, but eventually succeeded. How long does the `Compress Artifacts after build` step usually take?

And I also found the `ENDLESS_TASK_TIMEOUT` configuration seems to not work. Several tasks took significantly longer than `ENDLESS_TASK_TIMEOUT`. I'm going to take a look at this issue.

**Comment by Zettat123** [comment] 2024-12-04 09:13
One more thing I would like to know, are the logs downloaded from the UI or excerpted from act_runner's log file?

**Comment by RobertBerger** [comment] 2024-12-04 17:06
> One more thing I would like to know, are the logs downloaded from the UI or excerpted from act_runner's log file?

From the UI - download log.

**Comment by Zettat123** [comment] 2024-12-05 08:26
Could you get some logs from the act_runner? Maybe we can find some error messages from them.

**Comment by RobertBerger** [comment] 2024-12-05 11:37
This is my config.yaml

[config.yaml.txt](https://github.com/user-attachments/files/18022563/config.yaml.txt)

Do you want me to change the log level from `info` to something else?

**Comment by RobertBerger** [comment] 2024-12-05 11:43
At the moment I suspect https://github.com/appleboy/scp-action to explode in some mysterious way, but I don't see the exact problem anywhere:

```
⭐ Run Main Copy artifacts after build
2024-12-05T01:00:15.0665023Z Writing entry to tarball workflow/outputcmd.txt len:0
2024-12-05T01:00:15.0665185Z Writing entry to tarball workflow/statecmd.txt len:0
2024-12-05T01:00:15.0665314Z Writing entry to tarball workflow/pathcmd.txt len:0
2024-12-05T01:00:15.0665444Z Writing entry to tarball workflow/envs.txt len:0
2024-12-05T01:00:15.0665576Z Writing entry to tarball workflow/SUMMARY.md len:0
2024-12-05T01:00:15.0665687Z Extracting content to '/var/run/act'
2024-12-05T01:00:15.0746419Z type=remote-action actionDir=/***/.cache/act/570479a11c3755bfb3e972af32971613da4b795d6dc834cdecde074d733f5ef4 actionPath= workdir=/workspace/rber/gitea-yocto-build actionCacheDir=/***/.cache/act actionName=570479a11c3755bfb3e972af32971613da4b795d6dc834cdecde074d733f5ef4 containerActionDir=/var/run/act/actions/570479a11c3755bfb3e972af32971613da4b795d6dc834cdecde074d733f5ef4
2024-12-05T01:00:15.0799763Z image 'act-570479a11c3755bfb3e972af32971613da4b795d6dc834cdecde074d733f5ef4-dockeraction:latest' for architecture '' already exists
2024-12-05T01:00:15.0914779Z expression '${{ secrets.SCP_HOST }}' rewritten to 'format('{0}', secrets.SCP_HOST)'
2024-12-05T01:00:15.0915265Z evaluating expression 'format('{0}', secrets.SCP_HOST)'
2024-12-05T01:00:15.0915542Z expression 'format('{0}', secrets.SCP_HOST)' evaluated to '%!t(string=***)'
2024-12-05T01:00:15.0915714Z expression '${{ secrets.SCP_USERNAME }}' rewritten to 'format('{0}', secrets.SCP_USERNAME)'
2024-12-05T01:00:15.0915823Z evaluating expression 'format('{0}', secrets.SCP_USERNAME)'
2024-12-05T01:00:15.0915996Z expression 'format('{0}', secrets.SCP_USERNAME)' evaluated to '%!t(string=***)'
2024-12-05T01:00:15.0916143Z expression '${{ secrets.SCP_PASSWORD }}' rewritten to 'format('{0}', secrets.SCP_PASSWORD)'
2024-12-05T01:00:15.0916253Z evaluating expression 'format('{0}', secrets.SCP_PASSWORD)'
2024-12-05T01:00:15.0916433Z expression 'format('{0}', secrets.SCP_PASSWORD)' evaluated to '%!t(string=***)'
2024-12-05T01:00:15.0916612Z expression '${{ secrets.SCP_PORT }}' rewritten to 'format('{0}', secrets.SCP_PORT)'
2024-12-05T01:00:15.0916720Z evaluating expression 'format('{0}', secrets.SCP_PORT)'
2024-12-05T01:00:15.0916881Z expression 'format('{0}', secrets.SCP_PORT)' evaluated to '%!t(string=***)'
2024-12-05T01:00:15.0917055Z expression '${{env.WORK_DIR}}/artifacts/*' rewritten to 'format('{0}/artifacts/*', env.WORK_DIR)'
2024-12-05T01:00:15.0917160Z evaluating expression 'format('{0}/artifacts/*', env.WORK_DIR)'
2024-12-05T01:00:15.0917361Z expression 'format('{0}/artifacts/*', env.WORK_DIR)' evaluated to '%!t(string=/workspace/rber/gitea-yocto-build/workdir/artifacts/*)'
2024-12-05T01:00:15.1125772Z   🐳  docker pull image=act-570479a11c3755bfb3e972af32971613da4b795d6dc834cdecde074d733f5ef4-dockeraction:latest platform= username= forcePull=false
2024-12-05T01:00:15.1126173Z   🐳  docker pull act-570479a11c3755bfb3e972af32971613da4b795d6dc834cdecde074d733f5ef4-dockeraction:latest
2024-12-05T01:00:15.1136185Z Image exists? true
2024-12-05T01:00:15.1187527Z   🐳  docker create image=act-570479a11c3755bfb3e972af32971613da4b795d6dc834cdecde074d733f5ef4-dockeraction:latest platform= entrypoint=[] cmd=[] network="container:GITEA-ACTIONS-TASK-542_WORKFLOW-release-use-uninative-core-image-minimal-local-source-mirror_JOB-release-use-uninative-core-image-minimal-local-source-mirror-job"
2024-12-05T01:00:17.8088451Z Created container name=GITEA-ACTIONS-TASK-542-WORKFLOW-release-use-uninative-core-image-minimal-local-source-mirror-JOB-release-use-uninative-core-image-minimal-local-source-mirror-job_STEP-45 id=c75a3377db1ca029e5afb086b2bc406caa4e2741df90f36434fe9dccf7ae1b57 from image act-570479a11c3755bfb3e972af32971613da4b795d6dc834cdecde074d733f5ef4-dockeraction:latest (platform: )
2024-12-05T01:00:17.8089885Z ENV ==> [GITHUB_ENV=/var/run/act/workflow/envs.txt INPUT_PROXY_KEY_PATH= key= USE_HASH_SERVER=yes ACTIONS_RUNTIME_TOKEN=*** GITHUB_ACTION_REPOSITORY=appleboy/scp-action INPUT_COMMAND_TIMEOUT=60m INPUT_HOST=*** proxy_use_insecure_cipher=false PR_SERVER=***:18586 USE_SOURCE_MIRROR_LOCAL=yes GITHUB_SERVER_URL=http://***:8940 INPUT_USE_INSECURE_CIPHER=false INPUT_STRIP_COMPONENTS=0 GITHUB_ACTOR=rber INPUT_TARGET=/appdata/artifacts GITHUB_STATE=/var/run/act/workflow/statecmd.txt BITBAKE_TWO_ALLOW_ERROR=no USE_VAR_WWW=yes GITHUB_WORKFLOW=release-use-uninative-core-image-minimal-local-source-mirror GITHUB_RUN_NUMBER=54 GITHUB_ACTION_REF=v0.1.7 INPUT_KEY_PATH= proxy_password= tar_tmp_path= BITBAKE_ZERO_ALLOW_ERROR=no DONT_USE_UNINATIVE_TARBALL=no BUILD_UNINATIVE_TARBALL=no INPUT_TAR_DEREFERENCE=false INPUT_DEBUG=false NO_SSTATE_MIRRORS=yes NO_PREMIRRORS=yes ImageOS=yoctobuild-walnascar GITEA_OUTPUT=/var/run/act/workflow/outputcmd.txt INPUT_FINGERPRINT= INPUT_PROXY_HOST= proxy_key= WORKFLOW_DIR=gitea-yocto-build MANIFEST_REPO=rber/manifests -b master-action-walnascar GITHUB_ACTION_PATH= INPUT_PASSWORD=*** GITEA_ENV=/var/run/act/workflow/envs.txt fingerprint= USE_PREMIRRORS=no RUNNER_PERFLOG=/dev/null INPUT_TAR_TMP_PATH= proxy_key_path= strip_components=0 GITEA_SERVER=***:8940 source=/workspace/rber/gitea-yocto-build/workdir/artifacts/* HASH_SERVER=***:8688 WEB_SERVER=***:8941 INPUT_PROXY_FINGERPRINT= INPUT_TIMEOUT=30s tar_exec=tar INPUT_PROXY_USERNAME= THE_ALLOWED_NETWORKS=*** UNINATIVE_TARBALL_VERSION=4.6 TEMPLATE_COMMON=template-common-master GITHUB_HEAD_REF= GITEA_PATH=/var/run/act/workflow/pathcmd.txt ACTIONS_RUNTIME_URL=http://***:8940/api/actions_pipeline/ INPUT_RM=false GITHUB_REPOSITORY=rber/gitea-yocto-build GITHUB_API_URL=http://***:8940/api/v1 overwrite=false username=*** key_path= debug=false password=*** PREP_SOURCE_MIRROR=no GITHUB_RUN_ID=300 GITHUB_WORKSPACE=/workspace/rber/gitea-yocto-build GITHUB_PATH=/var/run/act/workflow/pathcmd.txt INPUT_PROXY_PASSWORD= THE_SOURCE_MIRROR_URL=http://***:8941/source_mirror_walnascar GITHUB_SHA=98c7fb9e7e516d6473b69c16a2c0f02532c3e9f3 GITHUB_RETENTION_DAYS= NO_SOURCE_MIRROR=yes USE_BB_NO_NETWORK=yes POPULATE_UNINATIVE_TARBALL=no CI=true INPUT_USERNAME=*** ACT=true GITHUB_REPOSITORY_OWNER=rber INPUT_PROXY_KEY= INPUT_TAR_EXEC=tar BITBAKE_ONE=core-image-minimal WORKFLOW_REPO=rber/gitea-yocto-build WORK_DIR=/workspace/rber/gitea-yocto-build/workdir GITHUB_EVENT_NAME=push USE_BB_ALLOWED_NETWORKS=no GITEA_ACTIONS_RUNNER_VERSION=v0.2.11 USE_PR_SERVER=yes GITEA_ACTIONS=true target=/appdata/artifacts BITBAKE_ZERO=empty GITHUB_ACTION=45 GITHUB_OUTPUT=/var/run/act/workflow/outputcmd.txt INPUT_PROXY_USE_INSECURE_CIPHER=false proxy_fingerprint= proxy_passphrase= ARTIFACTS_ON_SERVER=/appdata/artifacts/workspace/rber/gitea-yocto-build/workdir/artifacts GITHUB_JOB=release-use-uninative-core-image-minimal-local-source-mirror-job GITEA_STATE=/var/run/act/workflow/statecmd.txt INPUT_PROXY_TIMEOUT=30s proxy_username= BITBAKE_ONE_ALLOW_ERROR=no GITHUB_BASE_REF= INPUT_PROXY_PASSPHRASE= INPUT_SOURCE=/workspace/rber/gitea-yocto-build/workdir/artifacts/* host=*** passphrase= NOTE=use-uninative-core-image-minimal-local-source-mirror POPULATE_SSTATE_MIRROR=no USE_SOURCE_MIRROR=no GITEA_STEP_SUMMARY=/var/run/act/workflow/SUMMARY.md INPUT_PASSPHRASE= port=*** use_insecure_cipher=false BITBAKE_TWO=core-image-sato-sdk GITEA_GIT_MIRROR=***:8939 THE_UNINATIVE_URL=http://***:8941/releases/uninative/4.6/ GITHUB_REF=refs/heads/master GITHUB_REF_NAME=master INPUT_PORT=*** GITHUB_STEP_SUMMARY=/var/run/act/workflow/SUMMARY.md INPUT_KEY= proxy_port=*** proxy_host= YP_CONFIG=multi-v7-ml-debug-training-master ACTIONS_CACHE_URL=http://172.20.0.2:46819/ GITHUB_EVENT_PATH=/var/run/act/workflow/event.json GITHUB_GRAPHQL_URL= JOB_CONTAINER_NAME=GITEA-ACTIONS-TASK-542_WORKFLOW-release-use-uninative-core-image-minimal-local-source-mirror_JOB-release-use-uninative-core-image-minimal-local-source-mirror-job META_RESY=meta-resy-master ACTIONS_RESULTS_URL=http://***:8940 GITHUB_REF_TYPE=branch command_timeout=60m GITHUB_ACTIONS=true RUNNER_TRACKING_ID= INPUT_PROXY_PORT=*** INPUT_OVERWRITE=false rm=false USE_UNINATIVE_TARBALL=yes YP_VERSION=walnascar proxy_timeout=30s timeout=30s tar_dereference=false RUNNER_TOOL_CACHE=/opt/hostedtoolcache RUNNER_OS=Linux RUNNER_ARCH=X64 RUNNER_TEMP=/tmp]
2024-12-05T01:00:17.8094742Z   🐳  docker run image=act-570479a11c3755bfb3e972af32971613da4b795d6dc834cdecde074d733f5ef4-dockeraction:latest platform= entrypoint=[] cmd=[] network="container:GITEA-ACTIONS-TASK-542_WORKFLOW-release-use-uninative-core-image-minimal-local-source-mirror_JOB-release-use-uninative-core-image-minimal-local-source-mirror-job"
2024-12-05T01:00:17.8108665Z Starting container: c75a3377db1ca029e5afb086b2bc406caa4e2741df90f36434fe9dccf7ae1b57
2024-12-05T01:00:17.9978477Z Started container: c75a3377db1ca029e5afb086b2bc406caa4e2741df90f36434fe9dccf7ae1b57
2024-12-05T01:00:18.0350803Z drone-scp version: v1.6.14
2024-12-05T01:00:18.0351600Z tar all files into /tmp/pFlqCIJOzz.tar.gz
2024-12-05T01:00:18.0385365Z tar: removing leading '/' from member names

```

So I am tring with https://github.com/marketplace/actions/copy-via-ssh instead.

Let's see.

https://github.com/appleboy/scp-action tars my tarballs again, which is not needed and they are some tens of Gigs in size.

**Comment by RobertBerger** [comment] 2024-12-05 11:44
If you think it helps, I guess I could also give you remote access to my machine, or we can do a remote live session.

**Comment by Akshu-305** [comment] 2024-12-06 07:52
Even I'm facing the similar issue(pipeline stopped after 3hrs) after changing the ENDLESS_TASK_TIMEOUT under [actions] in app.ini of gitea  and changed runner.timeout in the configuration file of gitea act runner. Is there anything else I should change/do?

**Comment by RobertBerger** [comment] 2024-12-06 11:37
I am still stuck there. I suspected one of my steps to be the problem, but I am still investigating. At the moment I try to break everything down to something smaller than 3 hours, but that is not easy, since I build a complete Linux OS for an Embedded target from sources and if I want to build everything only from sources without any special tricks on 16 cores this takes time.

**Comment by RobertBerger** [comment] 2024-12-08 11:54
Looking again at the logs, I see this

``
ENV ==> [RUNNER_TOOL_CACHE=/opt/hostedtoolcache RUNNER_OS=Linux RUNNER_ARCH=X64 RUNNER_TEMP=/tmp LANG=C.UTF-8]
  🐳  docker run image=reliableembeddedsystems/poky-container:2024-03-11-master-local-icecc-ub***-doc-spdx platform= entrypoint=["/bin/sleep" "10800"] cmd=[] network="GITEA-ACTIONS-TASK-614_WORKFLOW-release-use-uninative-core-image-minimal-local-source-mirror_JOB-release-use-uninative-core-image-minimal-local-source-mirror-job-release-use-uninative-core-image-minimal-local-source-mirror-job-network"
``

`entrypoint=["/bin/sleep" "10800"]` would be 3 hours. I am not quite sure where this comes from, but this might be an issue.

**Comment by RobertBerger** [comment] 2024-12-10 18:05
... and looking at this[1] it makes me think, that it comes from the gitea act runner. Can someone confirm and maybe fix this?

[1] https://forum.gitea.com/t/oci-runtime-exec-failed-unable-to-start-container-process/8299/3

just search for sleep and you will find:

```
entrypoint=["/bin/sleep" "10800"]
```

**Comment by RobertBerger** [comment] 2024-12-10 21:54
Here is my current setup -- please review and comment.

`docker compose`/`portainer` setup:

```
version: "3.8"

networks:
  gitea-latest:
    external: false

services:
  server-latest:
    image: gitea/gitea:1.22.4
    container_name: gitea-latest
    environment:
      - USER_UID=1001
      - USER_GID=1001
    restart: always
    networks:
      - gitea-latest
    volumes:
      - /appdata/gitea-latest/data:/data
      - /appdata/gitea-latest/git:/var/lib/gitea/git
      - /home/git/.ssh/:/data/git/.ssh
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro      
    ports:
      - "8940:3000"
      - "2226:22"
  runner-latest:
    image: gitea/act_runner:0.2.11
    restart: always
    depends_on:
      - server-latest
    volumes:
      - /appdata/act_runner-latest/data:/data
      - /appdata/act_runner-latest/data/config.yaml:/data/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      - CONFIG_FILE ./config.yaml
      - GITEA_INSTANCE_URL=http://192.168.42.182:8940
      - GITEA_RUNNER_NAME=runner-latest-182
      - GITEA_RUNNER_LABELS=ubuntu-latest:docker://node:16-bullseye,ubuntu-22.04:docker://node:16-bullseye,yocto-build-walnascar:docker://reliableembeddedsystems/poky-container:2024-03-11-master-local-icecc-ub22-doc-spdx
      - GITEA_RUNNER_REGISTRATION_TOKEN=q9KaYYnadreasdklASdrif3Stb8TWWfrWKNjNsdb
# langdale:
# GITEA_RUNNER_LABELS=ubuntu-latest:docker://node:16-bullseye,ubuntu-22.04:docker://node:16-bullseye,yocto-build-langdale:docker://reliableembeddedsystems/poky-container:2023-05-24-master-local-icecc-ub20-doc-action
# walnascar ori:
# GITEA_RUNNER_LABELS=ubuntu-latest:docker://node:16-bullseye,ubuntu-22.04:docker://node:16-bullseye,yocto-build-walnascar:docker://reliableembeddedsystems/poky-container:2024-03-11-master-local-icecc-ub22-doc-spdx
# GITEA_RUNNER_LABELS=ubuntu-latest:docker://gitea/runner-images:ubuntu-latest,ubuntu-22.04:docker://gitea/runner-images:ubuntu-22.04,yocto-build-walnascar:docker://reliableembeddedsystems/poky-container:2024-03-11-master-local-icecc-ub22-doc-spdx
```

Are those the correct act runners?
```
ubuntu-latest:docker://node:16-bullseye,ubuntu-22.04:docker://node:16-bullseye
```

The other one is mine, which I need to build my stuff.

My app.ini contains

```
[actions]
ENABLED = true
;; Timeout to stop the tasks which have running status and continuous updates, but don't end for a long time
;; default is 3h
ENDLESS_TASK_TIMEOUT = 6h
```

config.yaml:

```
# Example configuration file, it's safe to copy this as the default config file without any modification.

# You don't have to copy this file to your instance,
# just run `./act_runner generate-config > config.yaml` to generate a config file.

log:
  # The level of logging, can be trace, debug, info, warn, error, fatal
  level: info

runner-latest-182:
  # Where to store the registration result.
  file: .runner
  # Execute how many tasks concurrently at the same time.
  capacity: 1
  # Extra environment variables to run jobs.
  envs:
  # A_TEST_ENV_NAME_1: a_test_env_value_1
  # A_TEST_ENV_NAME_2: a_test_env_value_2
  # Extra environment variables to run jobs from a file.
  # It will be ignored if it's empty or the file doesn't exist.
  env_file: .env
  # The timeout for a job to be finished.
  # Please note that the Gitea instance also has a timeout (3h by default) for the job.
  # So the job could be stopped by the Gitea instance if it's timeout is shorter than this.
  timeout: 6h
  # The timeout for the runner to wait for running jobs to finish when shutting down.
  # Any running jobs that haven't finished after this timeout will be cancelled.
  shutdown_timeout: 0s
  # Whether skip verifying the TLS certificate of the Gitea instance.
  insecure: false
  # The timeout for fetching the job from the Gitea instance.
  fetch_timeout: 50s
  # The interval for fetching the job from the Gitea instance.
  fetch_interval: 20s
  # The labels of a runner are used to determine which jobs the runner can run, and how to run them.
  # Like: "macos-arm64:host" or "ubuntu-latest:docker://gitea/runner-images:ubuntu-latest"
  # Find more images provided by Gitea at https://gitea.com/gitea/runner-images .
  # If it's empty when registering, it will ask for inputting labels.
  # If it's empty when execute `daemon`, will use labels in `.runner` file.
  labels:
  # - "ubuntu-latest:docker://gitea/runner-images:ubuntu-latest"
  # - "ubuntu-22.04:docker://gitea/runner-images:ubuntu-22.04"
  # - "yocto-build-walnascar:docker://reliableembeddedsystems/poky-container:2024-03-11-master-local-icecc-ub22-doc-spdx"
    - "ubuntu-latest:docker://node:16-bullseye"
    - "ubuntu-22.04:docker://node:16-bullseye"
    - "yocto-build-walnascar:docker://reliableembeddedsystems/poky-container:2024-03-11-master-local-icecc-ub22-doc-spdx"


cache:
  # Enable cache server to use actions/cache.
  enabled: true
  # The directory to store the cache data.
  # If it's empty, the cache data will be stored in $HOME/.cache/actcache.
  dir: ""
  # The host of the cache server.
  # It's not for the address to listen, but the address to connect from job containers.
  # So 0.0.0.0 is a bad choice, leave it empty to detect automatically.
  host: ""
  # The port of the cache server.
  # 0 means to use a random available port.
  port: 0
  # The external cache server URL. Valid only when enable is true.
  # If it's specified, act_runner will use this URL as the ACTIONS_CACHE_URL rather than start a server by itself.
  # The URL should generally end with "/".
  external_server: ""

container:
  # Specifies the network to which the container will connect.
  # Could be host, bridge or the name of a custom network.
  # If it's empty, act_runner will create a network automatically.
  network: ""
  # Whether to use privileged mode or not when launching task containers (privileged mode is required for Docker-in-Docker).
  privileged: false
  # And other options to be used when the container is started (eg, --add-host=my.gitea.url:host-gateway).
  options:
  # The parent directory of a job's working directory.
  # NOTE: There is no need to add the first '/' of the path as act_runner will add it automatically. 
  # If the path starts with '/', the '/' will be trimmed.
  # For example, if the parent directory is /path/to/my/dir, workdir_parent should be path/to/my/dir
  # If it's empty, /workspace will be used.
  workdir_parent:
  # Volumes (including bind mounts) can be mounted to containers. Glob syntax is supported, see https://github.com/gobwas/glob
  # You can specify multiple volumes. If the sequence is empty, no volumes can be mounted.
  # For example, if you only allow containers to mount the `data` volume and all the json files in `/src`, you should change the config to:
  # valid_volumes:
  #   - data
  #   - /src/*.json
  # If you want to allow any volume, please use the following configuration:
  # valid_volumes:
  #   - '**'
  valid_volumes: []
  # overrides the docker client host with the specified one.
  # If it's empty, act_runner will find an available docker host automatically.
  # If it's "-", act_runner will find an available docker host automatically, but the docker host won't be mounted to the job containers and service containers.
  # If it's not empty or "-", the specified docker host will be used. An error will be returned if it doesn't work.
  docker_host: ""
  # Pull docker image(s) even if already present
  force_pull: true
  # Rebuild docker image(s) even if already present
  force_rebuild: false

host:
  # The parent directory of a job's working directory.
  # If it's empty, $HOME/.cache/act/ will be used.
  workdir_parent:
```

On this webpage: https://docs.gitea.com/usage/actions/act-runner#configuration

I searched for `timeout`, but can not find this:

```
runner:
  # The timeout for a job to be finished.
  # Please note that the Gitea instance also has a timeout (3h by default) for the job.
  # So the job could be stopped by the Gitea instance if it's timeout is shorter than this.
  timeout: 3h
```

In my 'config.yaml' file, I have, as you can see above:

```
runner-latest-182:
  ...
  timeout: 6h
  ...
 
```

My top level job is this: https://github.com/RobertBerger/gitea-yocto-build/blob/master/.gitea/workflows/00.01-release.yml

It calls stuff from here:

https://github.com/RobertBerger/gitea-yocto-build/tree/master/.gitea/workflows

There I defined:

```
timeout-minutes: 1000
```

With this setup, I see in the logs:

```
🐳  docker create image=reliableembeddedsystems/poky-container:2024-03-11-master-local-icecc-ub***-doc-spdx platform= entrypoint=["/bin/sleep" "10799"] cmd=[] network="GITEA-ACTIONS-TASK-681_WORKFLOW-release_JOB-release-release-network"
Created container name=GITEA-ACTIONS-TASK-681_WORKFLOW-release_JOB-release id=16ac0a33318213e0f55b255e49386dd15c2a39130d5b37cd2066c14344a50b0a from image reliableembeddedsystems/poky-container:2024-03-[11](http://192.168.42.182:8940/rber/gitea-yocto-build/actions/runs/118#jobstep-0-11)-master-local-icecc-ub***-doc-spdx (platform: )
ENV ==> [RUNNER_TOOL_CACHE=/opt/hostedtoolcache RUNNER_OS=Linux RUNNER_ARCH=X64 RUNNER_TEMP=/tmp LANG=C.UTF-8]
  🐳  docker run image=reliableembeddedsystems/poky-container:2024-03-11-master-local-icecc-ub***-doc-spdx platform= entrypoint=["/bin/sleep" "10799"] cmd=[] network="GITEA-ACTIONS-TASK-681_WORKFLOW-release_JOB-release-release-network"
```
or instead of `sleep 10799` `sleep 10800`, which is 3h

Am I missing something?

**Comment by Zettat123** [comment] 2024-12-11 01:08
> I searched for `timeout`, but can not find this

You can find the `timeout` configuration in [config.example.yaml](https://gitea.com/gitea/act_runner/src/commit/8b72d1c7ae3a53059476ca600951e69efaf40913/internal/pkg/config/config.example.yaml#L22-L25)

> In my 'config.yaml' file, I have, as you can see above:
> 
> ```
> runner-latest-182:
>   ...
>   timeout: 6h
>   ...
> ```
> 

`runner-latest-182` is not a valid configuration key. Could you please change `runner-latest-182` to `runner` ?

**Comment by Zettat123** [comment] 2024-12-11 12:42
> @Zettat123 Even I used runner.timeout in my configuration still it doesn't work for me. Should I add anything else?

Thanks for your feedback. I think just specifying the `timeout` is enough, no need to add any additional configuration. I will do some tests to check if there are any bugs related to the `timeout` configuration.

**Comment by RobertBerger** [comment] 2024-12-11 13:35
> > I searched for `timeout`, but can not find this
> 
> You can find the `timeout` configuration in [config.example.yaml](https://gitea.com/gitea/act_runner/src/commit/8b72d1c7ae3a53059476ca600951e69efaf40913/internal/pkg/config/config.example.yaml#L22-L25)
> 
> > In my 'config.yaml' file, I have, as you can see above:
> > ```
> > runner-latest-182:
> >   ...
> >   timeout: 6h
> >   ...
> > ```
> 
> `runner-latest-182` is not a valid configuration key. Could you please change `runner-latest-182` to `runner` ?

Hi,

Good catch!

I did change this in my config.yaml, restarted everything, but I still get:

```
2024-12-11T12:21:59.8336299Z   🐳  docker create image=reliableembeddedsystems/poky-container:2024-03-11-master-local-icecc-ub***-doc-spdx platform= entrypoint=["/bin/sleep" "10800"] cmd=[] network="GITEA-ACTIONS-TASK-690_WORKFLOW-release-uninative-local-source-mirror_JOB-release-uninative-local-source-mirror-job-release-uninative-local-source-mirror-job-network"
2024-12-11T12:21:59.8960372Z Created container name=GITEA-ACTIONS-TASK-690_WORKFLOW-release-uninative-local-source-mirror_JOB-release-uninative-local-source-mirror-job id=e008a03754d4f40d84c0c7eb198ededa94ea796fafcbd43c63f078a0c28d7d37 from image reliableembeddedsystems/poky-container:2024-03-11-master-local-icecc-ub***-doc-spdx (platform: )
2024-12-11T12:21:59.8961174Z ENV ==> [RUNNER_TOOL_CACHE=/opt/hostedtoolcache RUNNER_OS=Linux RUNNER_ARCH=X64 RUNNER_TEMP=/tmp LANG=C.UTF-8]
2024-12-11T12:21:59.8961505Z   🐳  docker run image=reliableembeddedsystems/poky-container:2024-03-11-master-local-icecc-ub***-doc-spdx platform= entrypoint=["/bin/sleep" "10800"] cmd=[] network="GITEA-ACTIONS-TASK-690_WORKFLOW-release-uninative-local-source-mirror_JOB-release-uninative-local-source-mirror-job-release-uninative-local-source-mirror-job-network"
2024-12-11T12:21:59.8961937Z Starting container: e008a03754d4f40d84c0c7eb198ededa94ea796fafcbd43c63f078a0c28d7d37
2024-12-11T12:22:00.2400298Z Started container: e008a03754d4f40d84c0c7eb198ededa94ea796fafcbd43c63f078a0c28d7d37
2024-12-11T12:22:00.3931369Z   🐳  docker exec cmd=[chown -R 70:70 /workspace/rber/gitea-yocto-build] user=0 workdir=

```

`entrypoint=["/bin/sleep" "10800"]`

**Comment by Zettat123** [comment] 2024-12-13 02:27
This is weird. It works on my act_runner.

![image](https://github.com/user-attachments/assets/6afd087d-a1ea-49ec-8661-828d61e71e67)

**Comment by Zettat123** [comment] 2024-12-13 03:05
Ah, I think I know where the issue is.

The `CONFIG_FILE` env of act_runner in your `compose.yaml` is
```
    environment:
      - CONFIG_FILE ./config.yaml
```

It should be 
```
    environment:
      - CONFIG_FILE=./config.yaml
```

**Comment by RobertBerger** [comment] 2024-12-13 13:46
As far as I can see, this fixed it. Thanks a lot!

**Comment by Zettat123** [comment] 2024-12-16 04:03
I'll close this issue since it has been resolved. Please reopen it if you need more help.

**Closed as completed by Zettat123** 2024-12-16 04:03 UTC
Labels: issue/not-a-bug, topic/gitea-actions

**Comment by Akshu-305** [comment] 2024-12-16 13:01
in my act runner Deployment yaml I use 
env:
  - name: CONFIG_FILE
     value: ./config.yaml
     
What should I do?

**Comment by RobertBerger** [comment] 2024-12-16 19:00
@Akshu-305 

What does your `entrypoint=["/bin/sleep" "10800"]` return? Something like `10800`?

Maybe your config file is wrong or not picked up?
