### ISSUE TITLE
The website does not show any modification (Pushes, Commits etc...)

### ISSUE THREAD

**Issue by qjoly** [go-gitea/gitea#16464] opened 2021-07-16 14:02 UTC
- Gitea version (or commit ref): 1.15.0+dev-582-g3dcb3e907
- Git version: git version 2.20.1
- Operating system: Ubuntu 20 and Debian 10
- **Gitea Installed with Docker (Latest Image)**
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description
Hello,
When I create a GIT repo, I can push my files without any problem. But none of them show up on the website.

This occurs as soon as the Repo is created, and even if I can Clone, Pull, and Push without any problem: the web interface is unusable. I tried on differents repos

...

## Screenshots
https://i.imgur.com/sLwe1OT.png

**Comment by jolheiser** [comment] 2021-07-16 15:14
I believe this is a duplicate of #16428
Updating your docker image should fix the issue

**Closed as completed by jolheiser** 2021-07-16 15:14 UTC
Labels: issue/duplicate

**Comment by QJoly** [comment] 2021-07-16 15:34
Hi, i've updated my gitea, but i still have the issue :(

**Comment by QJoly** [comment] 2021-07-16 15:34
my version is now 1.15.0+rc1

**Comment by zeripath** [comment] 2021-07-16 15:36
Sigh... we'll need to release rc2 to make this happen

**Comment by jolheiser** [comment] 2021-07-16 15:36
The fix is past rc1, it will be available in rc2 or any commits at/after https://github.com/go-gitea/gitea/commit/7b31aae414fe8c4117ffd2d2c284d111e52f700e

**Comment by zeripath** [comment] 2021-07-16 15:40
An alternative option is to upgrade your docker to version 20

**Comment by QJoly** [comment] 2021-07-16 15:40
Crap, so i just have to wait

Thanks for your time ;)

**Comment by QJoly** [comment] 2021-07-16 15:57
> An alternative option is to upgrade your docker to version 20

Oh, that is simple, i'll try ! Thanks

**Comment by QJoly** [comment] 2021-07-16 16:49
> An alternative option is to upgrade your docker to version 20

It didn't solved the issue :(

**Comment by zeripath** [comment] 2021-07-16 17:08
Read this: https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0

**Comment by zeripath** [comment] 2021-07-22 17:32
@QJoly 1.15.0-rc2 has been tagged.

**Comment by QJoly** [comment] 2021-07-23 06:55
Thank you ! 

> @QJoly 1.15.0-rc2 has been tagged.
