### ISSUE TITLE
Personal access token limited for repository name

### ISSUE THREAD

**Issue by gusta70** [go-gitea/gitea#6170] opened 2019-02-23 21:40 UTC
Always preffered 2FA.
When 2FA is enabled, user must create PAT to access the repo.
But this PAT have permission to ALL repos.

New feature:
at create token, declare repo name, and this token can access only for this repo name.

**Comment by lafriks** [comment] 2019-02-23 21:46
How that would be different form deploy keys?

**Comment by gusta70** [comment] 2019-02-23 21:51
deploy keys is for ssh only?

**Comment by silverwind** [comment] 2019-02-24 07:00
Duplicate of https://github.com/go-gitea/gitea/issues/2051?

**Comment by gusta70** [comment] 2019-02-24 18:39
So, 1year and half porposal

**Closed as completed** 2019-02-24 21:58 UTC
Labels: issue/duplicate
