### ISSUE TITLE
[FR]: support for personal webhooks and site-wide webhooks

### ISSUE THREAD

**Issue by LER0ever** [go-gitea/gitea#4456] opened 2018-07-17 20:20 UTC
Feature Request: support for personal webhooks and site-wide webhooks

## Description
Since most users host Gitea as their personal git server and frontend, It would be great if a user can have a personal webhook that triggers on every repository that belongs to him/her, that is `username/*`. It is also useful to have site-wide webhooks that react on all repos for those who want to do some "logging to slack" kinda stuff.

- Gitea version (or commit ref): 7be5935
- Git version: 2.18.0
- Operating system: Manjaro Linux Latest
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

**Comment by techknowlogick** [comment] 2018-07-18 01:17
@LER0ever thank you for clarifying. I've reopened this ticket.

**Comment by luismanolo** [comment] 2018-10-04 06:43
I like this proposal too...

**Comment by 0x5c** [comment] 2019-02-19 23:11
Same as above, but I would add that having a trigger for mentions would be pretty nice

**Comment by Mikaela** [comment] 2019-08-16 19:24
I was going to open a duplicate of this.

## Feature request: user level webhooks

- Gitea version (or commit ref):  © Gitea Version: 1.10.0+dev-183-g867f46f78
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/user/settings/hooks - 404
  - [ ] No
  - [ ] Not relevant

## Description

Currently webhooks can only be set on individual repository and organisation level, while I wish I would be able to setup webhooks on user level applying to all of my repositories without having to visit their settings separately.

My usecase is a private IRC channel where I have feeds related to me and a IRC bot with support for Gitea. Currently I have to visit all repositories separately to configure webhooks (it's not a big problem as I don't have that many yet), but being able to configure them at one place would be easier.

I think noticing suspicious activity on my Gitea account could also be easier if I was informed about it all automatically.

Related: https://github.com/go-gitea/gitea/issues/7523 which requests system level global webhooks (later I guess that is a duplicate of this one)

**Comment by 0x5c** [comment] 2019-08-17 00:56
Would the best name for this be "notification webhooks"?

**Comment by lunny** [comment] 2019-08-17 01:48
Notification is one of this, another maybe a backup, mirror or any other purpose.

**Comment by insertjokehere** [comment] 2019-09-05 21:50
My use case for this would be a "repo created" webhook that I could use to automatically configure some things (create jobs on my CI etc)

**Comment by Mikaela** [comment] 2022-01-16 22:41
Another case for this would be Matrix webhooks being cumbersome to enable as they use the room ID

Matrix has room versions and to benefit from the features of the newer room versions a `/upgraderoom` is necessary. It then changes the room ID

And that means going through all webhooks and checking that they point to the new room instead of attempting to post into an old one

**Comment by delvh** [comment] 2023-04-29 14:24
I remember a PR for system webhooks being merged.
I think that means this issue is closed, right?

**Closed as completed by delvh** 2023-04-29 14:24 UTC
Labels: type/proposal, type/feature
