### ISSUE TITLE
Control panel

### ISSUE THREAD

**Issue by ppolunin** [go-gitea/gitea#29051] opened 2024-02-04 21:47 UTC
### Description

![image](https://github.com/go-gitea/gitea/assets/17013215/86547f0a-2ddf-4e1d-8f0b-41f7c11ddb43)

I extended gitea through the reverse proxy, the path is {SERVER_HOST}/git. There is no way to use a separate domain name yet. When I log in, I get to the control panel (as I understand it), which contains a list of repositories and a history at the same time. I can't switch between the pages of the story, the link I'm going to (the hint in the picture) doesn't work. With such a request, the browser does not want to send cookies.  If the link is change to {SERVER_HOST}/git/?page=4&date=, everything works.

### Gitea Version

1.21.4

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.43.0

### Operating System

Windows Server 2016

### How are you running Gitea?

IIS 10 Reverse Proxy is used. Gitea works as a service in the context of a private user.

### Database

MySQL/MariaDB

**Comment by KN4CK3R** [comment] 2024-02-05 09:27
Did you set the url with path in the `app.ini`?

**Comment by yp05327** [comment] 2024-03-22 00:12
duplicate of #29533?

**Comment by lunny** [comment] 2024-04-09 01:41
Duplicate of #29533

**Closed as completed by lunny** 2024-04-09 01:41 UTC
Labels: type/bug, issue/needs-feedback
