### ISSUE TITLE
Parsing error when using asciidoctor

### ISSUE THREAD

**Issue by proailurus** [go-gitea/gitea#8545] opened 2019-10-16 16:14 UTC
- Gitea version (or commit ref): 1.9.4
- Git version: 2.23.0
- Operating system: openSUSE Tumbleweed 20191012
- Database (use `[x]`):
- asciidoctor version: 2.0.10
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant (the test instance doesn't support AsciiDoc)
- Log gist: (couldn't find anything in logs pertaining to external renderers)

## Description

When using asciidoctor as external renderer for AsciiDoc files, a superfluous string appears in the output at the beginning of the file:
**lang="en">**

This seems to be part of asciidoctor's html output, for some reason gitea doesn't filter it out.
The rest of the AsciiDoc file is displayed correctly in gitea's web interface.

I'm using the default asciidoctor config described here:
https://docs.gitea.io/en-us/external-renderers/

## Screenshots

https://i.imgur.com/PBewpAz.png

**Comment by anthonyvdotbe** [comment] 2019-12-15 17:31
This is a valid issue & shouldn't be closed

**Comment by lunny** [comment] 2019-12-16 00:34
There is a new sectioon on https://docs.gitea.io/en-us/external-renderers/ about `sanitizer` maybe help you.

**Comment by anthonyvdotbe** [comment] 2019-12-22 12:17
AFAICT, the purpose of that is to avoid certain attributes from getting stripped by Gitea. To solve this issue, there should be a way to do the exact opposite: tell Gitea to strip certain attributes. I tried with the section below, but it doesn't help:
````
[markup.sanitizer]
ELEMENT = html
ALLOW_ATTR =
REGEXP =
````

**Comment by anthonyvdotbe** [comment] 2020-01-08 06:21
@lunny this can be closed: it's a duplicate of #8676, which is fixed in v1.11.0

**Closed as completed** 2020-01-08 09:13 UTC
