### ISSUE TITLE
Upgrading gogs on CentOS 6 to gitea 1.0.0

### ISSUE THREAD

**Issue by RichieB2B** [go-gitea/gitea#627] opened 2017-01-09 16:09 UTC
I just went through the process of upgrading gogs 0.9.97 to gitea 1.0.0. Since I used the RPM to install gogs I needed to modify several things to get things working.

I started following [this guide](https://docs.gitea.io/en-us/upgrade-from-gogs/), but soon realized all you need from there is:
```
cp -r gitea-v1.0.0/options /opt/gogs/options
```
Interestingly enough that guide does not tell you to [install the gitea binary](https://docs.gitea.io/en-us/install-from-binary/), which I installed as `/opt/gogs/gitea-1.0.0-linux-amd64`

The only real problem is that the gitea binary is linked against glibc 2.14:
```
$ ./gitea-1.0.0-linux-amd64 web
./gitea-1.0.0-linux-amd64: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./gitea)
```
The [solution](http://unix.stackexchange.com/questions/176489/how-to-update-glibc-to-2-14-in-centos-6-5) for this is to install glibc 2.14 in /opt.

To load the new libc I created a new script `/opt/gogs/gogs` (replaces the old gogs binary):
```
#!/bin/sh

LD_LIBRARY_PATH=/opt/glibc-2.14/lib /opt/gogs/gitea-1.0.0-linux-amd64 "$@"
```
I linked this file to /opt/gogs/gitea because gitea writes this path in ~/.ssh/authorized_keys
```
ln -s /opt/gogs/gogs /opt/gogs/gitea
```
After this gitea is a true drop-in replacement for gogs. Perhaps this above can be documented somewhere.

**Comment by tboerger** [comment] 2017-01-09 20:03
For 1.1.0 we will provide binaries without the glibc requirement. Beside that we still want to provide proper rpms for the major distros and this will also resolve this issue

**Comment by lunny** [comment] 2017-01-10 00:53
So we need a document update to close this issue?

**Comment by tboerger** [comment] 2017-01-10 07:26
@lunny at least we should add a note to the docs for now

**Comment by RichieB2B** [comment] 2017-01-12 09:39
I modified my solution slightly because after gitea rebuilds /home/gogs/.ssh/authorized_keys it puts /opt/gogs/gitea in there. So this needs to be a wrapper script as well.

**Comment by donguidou** [comment] 2017-01-12 15:51
The nightly builds still require glibc-2.14.

**Comment by tboerger** [comment] 2017-01-16 21:22
> The nightly builds still require glibc-2.14.

Of course, because the issue is not resolved yet.

**Comment by lunny** [comment] 2017-01-25 15:18
Is there any docs updated to close this?

**Closed as completed** 2017-02-09 05:43 UTC
Labels: type/docs

**Comment by tboerger** [comment] 2017-03-07 19:43
The upcoming release 1.1.0 won't depend on glibc anymore because of https://github.com/go-gitea/gitea/pull/985
