### ISSUE TITLE
All "select lists" are not working

### ISSUE THREAD

**Issue by Aragur** [go-gitea/gitea#10568] opened 2020-03-02 10:51 UTC
- Gitea version (or commit ref): 1.12.0+dev-412-g4160bd6ef
- Operating system: Debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Any select lists are not working after the latest update. (They are also not working on try.gitea.io)

## Screenshots

![Screenshot_20200302_115116](https://user-images.githubusercontent.com/11004008/75669921-22eed900-5c7c-11ea-91d2-6a3d2b076a36.png)

**Comment by alexanderadam** [comment] 2020-03-02 19:48
I guess this is a duplicate of #10565

and therefore I guess #10576 will fix this as well.

**Comment by silverwind** [comment] 2020-03-03 08:05
If this was built from source, try a clean build, e.g. `TAGS=bindata make clean-all build`.

**Comment by AragurDEV** [comment] 2020-03-03 08:09
@silverwind my installation is using the official docker image

**Comment by bkraul** [comment] 2020-03-03 14:23
Same here. This is kind of a breaking issue, as it interferes with the ability to create pull requests (can't select branch to PR from)....

**Comment by silverwind** [comment] 2020-03-03 18:32
All I currently know is that this is some kind of intermittent build issue. Try updating to a newer image again, chances are the issue is not present there.

https://hub.docker.com/r/gitea/gitea/tags

**Comment by bkraul** [comment] 2020-03-03 18:33
I actually reverted to one of my archived docker tags, until this is confirmed normalized. I know for sure c08c975d3 does not have this issue.

**Comment by silverwind** [comment] 2020-03-03 18:34
Chances are, it was introduced in https://github.com/go-gitea/gitea/commit/85e6a1267c634b0316b159874e6e4e18c267c7fb.

**Closed as completed** 2020-03-03 19:51 UTC
Labels: type/bug, topic/build
