### ISSUE TITLE
The top bar doesn't scale properly

### ISSUE THREAD

**Issue by Kreyren** [go-gitea/gitea#12877] opened 2020-09-16 22:57 UTC
- Gitea version (or commit ref): Codeberg/Gitea
- Git version: Unknown
- Operating system: Unknown
- Database: Unknown
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes
  - No
  - Not relevant
- Log gist: Not Relevant

Transfer from https://codeberg.org/Codeberg/Community/issues/258

## Description

See https://codeberg.org/Codeberg/Community/issues/258#issuecomment-80947

TLDR: The menu elements shoudn't be allowed to expand through the full width as long as the menu is there and the menu should be visible even when the website is not 1000px wide.

## Screenshots

![image](https://user-images.githubusercontent.com/11302521/93400720-ba1a2780-f880-11ea-8597-ba4107094e26.png)

**Comment by Kreyren** [comment] 2020-09-16 22:58
This seems to require a HTML change to define the borders to the elements to avoid overlapping.

**Comment by techknowlogick** [comment] 2020-09-16 23:19
Closing as this is handled for the default case, codeberg is using custom templates and would need to fix downstream as mentioned in their ticket.

**Closed as completed by techknowlogick** 2020-09-16 23:19 UTC
Labels: issue/duplicate

**Comment by Kreyren** [comment] 2020-09-16 23:23
Not codeberg issue

@techknowlogick This issue is present on upstream gitea as well when multiple menu items are created and the menu dissapears at around 1000px

**Comment by techknowlogick** [comment] 2020-09-16 23:34
Not an issue upstream as we don’t have that many menu bar items. As mentioned, it is a codeberg issue as they have customized their instance.

**Comment by Kreyren** [comment] 2020-09-17 00:04
That makes no sense to me as this seems as an UI issue with customization that Gitea supports so it makes no sense to submit the fix in codeberg as the same issue will be present on other gitea instances as well using codeberg-alike configuration..

**Comment by techknowlogick** [comment] 2020-09-17 00:09
In theory someone could also use customized templates to use bootstrap, that doesn’t mean we support it. If you, or codeberg would like to submit a PR we’d be happy to review, but as this is an issue I only due to a customization I am keeping this closed.

**Comment by zeripath** [comment] 2020-09-17 07:18
This is actually a duplicate of #12031 . The problem affects translations. 

We'd potentially need to use a flexbox but I suspect some JavaScript might actually be needed to make it properly render.

We'd like help in this regard if there is anyone who is able to do the grind of fixing the less/html.
