### ISSUE TITLE
task and checkbo

### ISSUE THREAD

**Issue by maieul** [go-gitea/gitea#11788] opened 2020-06-07 10:00 UTC
- Gitea version (or commit ref): 1.13.0+dev
- Git version: https://try.gitea.io
- Operating system: https://try.gitea.io
- Database (use `[x]`): https://try.gitea.io
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL) https://try.gitea.io/Maieul/test/issues/3
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Weshould be able to check the box in the task list without editing the text of the issue, but directly by clicking on it, as for gitlab/github.

## Screenshots
https://try.gitea.io/Maieul/test/issues/3

**Comment by techknowlogick** [comment] 2020-06-07 16:00
closing as dupe of #7097 ﻿

**Closed as completed by techknowlogick** 2020-06-07 16:00 UTC
Labels: issue/duplicate
