### ISSUE TITLE
404 when trying to stop the timer which has been started before binary upgrade

### ISSUE THREAD

**Issue by bagasme** [go-gitea/gitea#22878] opened 2023-02-12 08:24 UTC
### Description

I was curious about using timer/stopwatch feature of Gitea. I enabled the timer when the deployed binary version was about 7ae10cb7f1a520d46c2c92d60cf5181c3d7b6850.

Today I build Gitea from version e460b6ef4da02aa03e7eaa9baa23dbd62898fc44 and deployed it. When I tried to stop the timer,
Gitea returned 404 on `https://%(DOMAIN)s/times/stopwatch/toggle`, thus the timer cannot be stopped.

I guessed that commit 90cf07a2c8dc2917d0c02648f0a69e0229cfce21 touched the subsystem in question.

### Gitea Version

main (commit e460b6ef4da02aa03e7eaa9baa23dbd62898fc44)

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/bagasme/335d722c4f87f552176b352d2e466f84

### Screenshots

![Stopping timer 404](https://user-images.githubusercontent.com/40219486/218300450-f4d62ce8-aac1-4cdd-9641-0c9b96070cdb.png)

### Git Version

2.39.1

### Operating System

Ubuntu 22.04

### How are you running Gitea?

I built Gitea from source using Go 1.20, Node v18.13.0 (installed via nvm) on Debian 11.

The Gitea instance is hosted on a LXD container on my computer.

### Database

PostgreSQL

**Comment by wxiaoguang** [comment] 2023-02-12 16:04
The generated stopwatch URL is wrong, it loses current issue's prefix.

![image](https://user-images.githubusercontent.com/2114189/218322243-c4317e74-0954-437d-a285-479008effe04.png)

**Comment by wxiaoguang** [comment] 2023-02-12 16:10
I just played a while, I think it could be just a display bug? Maybe you do not have active stopwatch yet .....

Could you help to confirm how your problem happens, especially the screenshots? Is there an active stopwatch?

**Comment by bagasme** [comment] 2023-02-13 03:27
> Could you help to confirm how your problem happens, especially the screenshots? Is there an active stopwatch?

My Gitea instance have implicit `ENABLE_TIMETRACKING=true` (as the config item isn't specified in `app.ini`). When it is set to `false`, the timer is paused; but when I set it again to `true`, the timer resumes.

Anyway, how can I check if there is active stopwatches?

**Comment by wxiaoguang** [comment] 2023-02-13 03:31
Screenshots?

ps: the display bug of #22169 problem would be fixed by #22879 -- if 22169 is the cause.

**Comment by wxiaoguang** [comment] 2023-02-13 19:20
Please have a try to see whether 22879 resolve the "display bug" on your side (I guess).

**Comment by wxiaoguang** [comment] 2023-02-20 12:44
I would assume that the problem has been resolved?

**Comment by wxiaoguang** [comment] 2023-02-28 17:20
> I would assume that the problem has been resolved?

Hmm ... maybe there is no more problem. I guess the problem was the UI regression caused by https://github.com/go-gitea/gitea/pull/22169 , it should have been fixed by https://github.com/go-gitea/gitea/pull/22879

**Closed as completed** 2023-03-01 05:50 UTC
Labels: type/bug
