### ISSUE TITLE
I created a repository and I am able to push the code to repository without credentials??

### ISSUE THREAD

**Issue by srikanthdasari66** [go-gitea/gitea#4653] opened 2018-08-09 06:35 UTC
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

...

**Comment by lafriks** [comment] 2018-08-09 06:37
check your git credential cache, git has probably cached your credentials

**Comment by srikanthdasari66** [comment] 2018-08-09 07:04
but in every system I am able to push to master without any password?

**Comment by srikanthdasari66** [comment] 2018-08-09 07:05
and using any branch I am able to push without asking any passwords.

**Comment by atom0s** [comment] 2018-08-09 18:42
I'm not able to reproduce this at all on either try.gitea.io or my personal Gitea hostings. All tests yield the auth login prompt from both TortoiseGit as well as command line.

**Comment by techknowlogick** [comment] 2018-08-10 16:02
@srikanthdasari66 Please use our forums at https://discourse.gitea.io/ for this question. Information such as if you are using SSH or HTTP(S) would be helpful as well as the version of Gitea you are using.

If using SSH you may not be prompted for a password because your SSH key is already authenticated.

I am going to close this issue now.

**Closed as completed by techknowlogick** 2018-08-10 16:02 UTC
Labels: type/question
