### ISSUE TITLE
no pull request possible for fork of self owned repo

### ISSUE THREAD

**Issue by bluecatchbird** [go-gitea/gitea#2189] opened 2017-07-21 13:19 UTC
- Gitea version (or commit ref): dde0052
- Git version: not relevant
- Operating system: Linux/Debian 8.8
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (https://try.gitea.io/testUnicorn/cannotCreatePullRequestOfOwnForkBug_fork)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

it is not possible to create a pull request from a fork to a self owned repo

Repreduce:
1. create new repo
2. fork the new repo
3. go to fork on the web interface and click on "Pull Requests" and on then on "New Pull Request"

after this, you get redirected to the original repo and a pull request from the fork is not possible

**Comment by lafriks** [comment] 2017-07-21 14:15
It should not be possible to create fork for repository that is under your user already. I think this issue is duplicate of #2019

**Closed as completed** 2017-07-26 07:19 UTC
Labels: issue/duplicate
