### ISSUE TITLE
closed PRs can create a patch check task on every commit

### ISSUE THREAD

**Issue by earl-warren** [go-gitea/gitea#24490] opened 2023-05-02 17:55 UTC
### Description

This is an issue introduced by https://github.com/go-gitea/gitea/pull/23324

Steps to reproduce:

* Create a pull request to merge the default branch into another branch
* Close the pull request
* Every time a commit is pushed to the default branch a task will [verify the patch](https://github.com/go-gitea/gitea/blob/bf999e406994ab34420fb62e0de7948c8c2116c1/services/pull/pull.go#L260)

Although the above scenario is unlikely, it will never stop creating a workload. At scale the number of such cases keep growing, specially when importing projects from other forges. 

### Gitea Version

v1.19

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

https://codeberg.org

### Database

None

**Comment by wolfogre** [comment] 2023-05-04 04:31
Should be fixed by #24231

**Comment by denyskon** [comment] 2023-07-01 07:05
Cannot reproduce it anymore, should be fixed by #24231

**Closed as completed by denyskon** 2023-07-01 07:05 UTC
Labels: type/bug
