### ISSUE TITLE
When after login visit startpage( / ), loading long time

### ISSUE THREAD

**Issue by maxid** [go-gitea/gitea#31646] opened 2024-07-17 03:27 UTC
### Description

Is it because there are too many repositories?

### Gitea Version

1.21.4 ~1.22.1

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

2024/07/17 03:18:22 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13951566527469631649 2100230653303 0x695ad20} false}
..
2024/07/17 03:18:22 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13951566527469631649 2100230653303 0x695ad20} false}
2024/07/17 03:18:22 ...eb/routing/logger.go:102:func1() [I] router: completed GET / for 172.23.0.4:60722, 200 OK in `35793.8ms` @ web/home.go:32(web.Home)

### Screenshots

![image](https://github.com/user-attachments/assets/49978a3f-8fb6-4af1-b94a-562890fb10ab)
![image](https://github.com/user-attachments/assets/9ddb3cc2-625f-4a81-bd19-f44bf36ee24e)

### Git Version

2.40.1

### Operating System

centos 7

### How are you running Gitea?

docker gitea

### Database

SQLite

**Comment by lunny** [comment] 2024-08-18 03:29
Can you post slow logs?

**Comment by techknowlogick** [comment] 2024-08-19 16:59
How many repositories do you have? What cache type are you using?

**Comment by lunny** [comment] 2024-09-24 22:17
Duplicate of #31582. The loading time is unrelated to the repositories amount of right sidebar.

**Closed as completed by lunny** 2024-09-24 22:17 UTC
Labels: type/bug, performance/speed
