### ISSUE TITLE
Allowing to modify the branch on an issue

### ISSUE THREAD

**Issue by snowc0de** [go-gitea/gitea#8765] opened 2019-10-31 18:18 UTC
- Gitea version (or commit ref): 1.11.0+dev-110-gc4bc5abda
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/chopin42/Hello1/issues/1)
  - [ ] No
  - [x] Not relevant

## Description
If I create an issue without choosing a branch because I forgot, I cannot edit it again to add this branch the button stay grey, but I can edit the other settings as the text, the title, the milestone, the tag and the assignees.

Thanks for your concern of this issue

**Comment by guillep2k** [comment] 2019-10-31 18:54
Duplicate of #5476

**Closed as completed** 2019-11-01 00:31 UTC
Labels: issue/duplicate
