### ISSUE TITLE
Metadata inheritance from issue to pull request

### ISSUE THREAD

**Issue by tdido** [go-gitea/gitea#19529] opened 2022-04-27 09:59 UTC
### Feature Description

In GitLab, if when working on an issue you name your branch starting with the issue number (e.g. "123-doing-something"), when creating a merge request from that branch the request inherits the issue's metadata (labels, milestone, etc.), and gets the `Closes #123` comment to auto-close the issue added to it.

I find it extremely helpful for my workflow and I thought others may as well.

**Comment by lunny** [comment] 2024-08-29 20:04
Maybe duplicate of #20226

**Closed as not planned** 2024-10-25 10:11 UTC
Labels: type/proposal
