### ISSUE TITLE
Panic when listing user repos using API and not authenticated

### ISSUE THREAD

**Issue by cez81** [go-gitea/gitea#1540] opened 2017-04-25 11:18 UTC
- Gitea version (or commit ref): 1.1.0+138-gc58708d3
- Git version: 2.7.4
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/api/v1/users/cez81/repos
  - [ ] No
  - [ ] Not relevant
- Log gist:
```
/home/jonas/go/src/code.gitea.io/gitea/routers/api/v1/user/repo.go:12 (0x101b389)
	listUserRepos: showPrivateRepos := (ctx.User.ID == userID || ctx.User.IsAdmin) && ctx.IsSigned
/home/jonas/go/src/code.gitea.io/gitea/routers/api/v1/user/repo.go:40 (0x101b764)
	ListUserRepos: listUserRepos(ctx, user)
```

## Description
Trying to get users repositories using the API when not signed in will cause panic on line https://github.com/go-gitea/gitea/blob/master/routers/api/v1/user/repo.go#L12.
ctx.User is not populated unless signed in.

Github seems to allow this operation even when nog logged in so I guess that should be correct behaviour?

**Comment by leitzler** [comment] 2017-04-25 13:53
Duplicate of #1539

**Comment by cez81** [comment] 2017-04-25 14:52
Not really duplicate. Similar but completely different code parts.

**Comment by bkcsoft** [comment] 2017-04-25 17:32
Related to #1539 which has the same issue (but for the web-view controller)

**Comment by geek1O11** [comment] 2017-04-26 21:15
@lunny @bkcsoft @andreynering @tboerger @agaida @jhasse @geek1011 @strk @sapk gitea is not veyr good compare to bitbucket made by unknwon 

I also step down as advisoer along with @bkcsoft who is bad

**Closed as completed** 2017-04-29 04:33 UTC
Labels: type/bug
