### ISSUE TITLE
LFS find commits internal error

### ISSUE THREAD

**Issue by rwalravens** [go-gitea/gitea#15850] opened 2021-05-12 23:09 UTC
- Gitea version (or commit ref): 1.14.2
- Git version: 2.30.2
- Operating system: docker with local storage LFS
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No (**LFS not supported**)

## Description
The #15236 "no commits found" problem was fixed in 1.14.2.
Now, for certain use cases, the functionality results in an internal error, or the page keeps on loading.
I will give instructions to create a repo that triggers the problem, or just download [lfs-cases.zip](https://github.com/go-gitea/gitea/files/6469471/lfs-cases.zip)

Some notes:
- the cases work fine in 1.13.7
- the files can be committed/pushed in any order, or all together, it always triggers the problem
- the gitea repo does not require special configuration, the problem also appears on a freshly installed instance

**Case 1: 500 internal error**
```
#!/bin/sh
rm -rf lfs-500 && mkdir lfs-500 && cd lfs-500 && git init
git lfs track bigfile.txt
echo content >> bigfile.txt
mkdir folder
echo public class RandomClass {} >> folder/RandomClass.java
mkdir anotherfolder
echo public class RandomClassA {} >> anotherfolder/RandomClassA.java
git add . && git commit -m "add files"
git remote add origin <your-gitea-repo-url>
git push -u origin --all
```
Repo settings > LFS > "Find Commits" result in an internal error. In the logs:
```
routers/repo/lfs.go:401:LFSFileFind() [E] Failure in FindLFSFile: strconv.ParseInt: parsing "RandomClass {}": invalid syntax
routers/repo/lfs.go:402:LFSFileFind() [E] LFSFind: FindLFSFile.: strconv.ParseInt: parsing "RandomClass {}": invalid syntax
```

**Case 2: page keeps loading**
```
#!/bin/sh
rm -rf lfs-pending && mkdir lfs-pending && cd lfs-pending && git init
git lfs track bigfile.txt
echo content >> bigfile.txt
mkdir folder
echo content >> folder/bigfile.txt
echo simple >> folder/otherfile.txt
mkdir folder2 && cd folder2 && mkdir subfolder && cd ..
echo content >> folder2/bigfile.txt
echo fdq >> folder2/subfolder/normalfile.txt
git add . && git commit -m "add files"
git remote add origin <your-gitea-repo-url>
git push -u origin --all
```
Repo settings > LFS > "Find Commits" keeps loading and the logs show nothing

**Comment by KN4CK3R** [comment] 2021-05-13 10:55
I can't reproduce both cases with the current main branch.

Case 1:
![grafik](https://user-images.githubusercontent.com/1666336/118115832-c0e64380-b3e9-11eb-87b1-250cb2c69159.png)

Case 2:
![grafik](https://user-images.githubusercontent.com/1666336/118115784-af04a080-b3e9-11eb-8ba8-726d803f91ea.png)

**Comment by zeripath** [comment] 2021-05-13 11:21
The bug has probably been fixed in the common-cat-file PR. The 1.14 code will have to be checked again.

**Comment by rwalravens** [comment] 2021-05-13 12:24
> I can't reproduce both cases with the current main branch.

I can't confirm this (using image `gitea/gitea:latest`, which currently is `1.15.0+dev-288-g52f8dcda4`, published 2 hours ago)
I tried 2 setups:
- fresh installation 1.15, with newly pushed repos
- upgrade our working instance 1.13.7 -> 1.15, with repos already there

However something has changed, because the error message is different, and case 2 also returns the same kind of 500 internal server error now.
```
routers/repo/lfs.go:392:LFSFileFind() [E] Failure in FindLFSFile: object does not exist [id: ����\03003d�\01703d�������\02203d7�Y��119ce2668c0de7ac167d, rel_path: ]
routers/repo/lfs.go:393:LFSFileFind() [E] LFSFind: FindLFSFile.: object does not exist [id: ����\03003d�\01703d�������\02203d7�Y��119ce2668c0de7ac167d, rel_path: ]

routers/repo/lfs.go:392:LFSFileFind() [E] Failure in FindLFSFile: object does not exist [id: QI����!Ih>�4\�A��\0503d��cf15403d112c71327d26, rel_path: ]
routers/repo/lfs.go:393:LFSFileFind() [E] LFSFind: FindLFSFile.: object does not exist [id: QI����!Ih>�4\�A��\0503d��cf15403d112c71327d26, rel_path: ]
```

**Comment by KN4CK3R** [comment] 2021-05-13 12:30
With the docker image I get the same error. Compiled from source there is no error.

**Closed as completed** 2021-05-14 13:12 UTC
Labels: type/bug
