### ISSUE TITLE
Show markdown summary

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#15720] opened 2021-05-04 10:42 UTC
## Description
Each markdown file opened in the browser should have a neat quick access summary to improve the user experience.
Each headline should be clickable to provide a more efficient workflow.

GitHub recently launched this feature also.

## Screenshots
![GitHub example](https://image.prntscr.com/image/KYQOC5YAQue3VEBVPA95HQ.png)

**Comment by zeripath** [comment] 2021-05-04 11:57
this is a duplicate of the table of contents feature requests.

**Closed as completed by zeripath** 2021-05-04 11:57 UTC
Labels: issue/duplicate
