### ISSUE TITLE
Stats.DB Index Repo[425] hangs

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#26064] opened 2023-07-22 21:54 UTC
### Description

Just saw, that the job hangs.

![image](https://github.com/go-gitea/gitea/assets/8334250/07b720f8-45a5-4b07-983d-f5aa02ea43ec)
[gitea-diagnosis-20230722-235117.zip](https://github.com/go-gitea/gitea/files/12137286/gitea-diagnosis-20230722-235117.zip)

### Gitea Version

1.20.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

 2.25.1

### Operating System

Ubuntu 20.04.6

### How are you running Gitea?

Precompiled gitea-1.20.1-linux-amd64

### Database

PostgreSQL

**Comment by somera** [comment] 2023-07-22 22:06
After I updated to 1.20.0 I saw high CPU usage on my system comparing to 1.19.x. Caus you changes how the queues works.

In 1.19.x my configuration was

```
[queue.mirror]
LENGTH = 30000
WORKERS = 1
```

Now I changet it to

```
[queue]
MAX_WORKERS = 4

[queue.mirror]
LENGTH = 30000
WORKERS = 1
MAX_WORKERS = 1

[queue.repo_stats_update]
WORKERS = 1
MAX_WORKERS = 1
```

Cause MAX_WPRKERS is 10 as default. And in this case my system runs on 100%.

When you change parameters, this should be shown after the Gitea restart. For exampe on the firts Gitea start in the browser.

**Comment by somera** [comment] 2023-07-22 22:18
I restarted my gitea to "fix" this.

**Comment by techknowlogick** [comment] 2023-07-23 00:06
Thanks for the report @somera, could you confirm that repo with ID 425 in your DB is https://github.com/google/material-design-icons ? I'm cloning it now to poke at it in my instance.

**Comment by wxiaoguang** [comment] 2023-07-23 03:04
Just a guess, maybe it's related to this problem (I have left some comments in the "code/indexer.go")


![image](https://github.com/go-gitea/gitea/assets/2114189/be9acb02-54ab-49c9-b9d9-256588c7f647)

**Comment by somera** [comment] 2023-07-23 10:54
> Thanks for the report @somera, could you confirm that repo with ID 425 in your DB is https://github.com/google/material-design-icons ? I'm cloning it now to poke at it in my instance.

Yes, this repo is in my DB.

**Comment by somera** [comment] 2023-07-31 16:19
1.20.2: hangs for 2 hours now.

![image](https://github.com/go-gitea/gitea/assets/8334250/560e76e8-5346-4450-9b09-56c3a421ac1e)

**Comment by wxiaoguang** [comment] 2023-07-31 16:23
Still the same problem as above: stats.(*DBIndexer).Index  -> GetLanguageStats -> git.ReadBatchLine ....

I have tried writing some different tests but I still can't reproduce it on my side, no idea yet .....

**Comment by somera** [comment] 2023-07-31 16:25
I think this happens, when the mirror and stats tasks run at the same time. But i'm not sure, that this is the reason.

**Comment by somera** [comment] 2023-07-31 16:29
And I found
```
2023/07/31 16:10:59 ...it/repo_attribute.go:306:func2() [E] Unable to open checker for 6745d95590b1a5593888b6c402401fc3db75fbdb. Error: failed to run attr-check. Error: context deadline exceeded
Stderr:
        /source/modules/git/repo_attribute.go:306 (0xd8e2e1)
        /usr/local/go/src/runtime/asm_amd64.s:1598 (0x475380)
                goexit: BYTE    $0x90   // NOP
```

**Comment by somera** [comment] 2023-07-31 16:32
And I see, this is the same repo id -> 425.

**Comment by somera** [comment] 2023-08-03 19:07
I removed the mirror.

The issue can be closed or you fix this: https://github.com/go-gitea/gitea/issues/26064#issuecomment-1646682126

**Comment by wxiaoguang** [comment] 2023-08-04 03:15
I think it is a really serious bug, so it could be kept open until it gets resolved ......

**Comment by wxiaoguang** [comment] 2023-08-04 03:42
As a workaround:

```
;; repo indexer units, the items to index, could be `sources`, `forks`, `mirrors`, `templates` or any combination of them separated by a comma.
;; If empty then it defaults to `sources` only, as if you'd like to disable fully please see REPO_INDEXER_ENABLED.
;REPO_INDEXER_REPO_TYPES = sources,forks,mirrors,templates
```

I think it could help you to avoid indexing such large repo

**Comment by wxiaoguang** [comment] 2023-08-04 06:09
After more trails, I figured out the problem. It looks like a Golang's framework's bug.


```go
func TestCommand(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	cmd := exec.CommandContext(ctx, "cat")
	rStdin, wStdin := io.Pipe()
	rStdout, wStdout := io.Pipe() // nio.Pipe(buffer.New(32 * 1024))
	cmd.Stdin = rStdin
	cmd.Stdout = wStdout
	written := 0
	read := 0
	stopWriting := atomic.Bool{}
	go func() {
		for !stopWriting.Load() {
			line := strings.Repeat("a", 5+rand.Intn(100)) + "\n"
			for i := 0; i < len(line); i++ {
				_, _ = wStdin.Write([]byte{line[i]})
			}
			written++
			time.Sleep(50 * time.Microsecond)
		}
	}()
	go func() {
		bio := bufio.NewReader(rStdout)
		for {
			_, _ = bio.ReadString('\n')
			read++
		}
	}()

	go func() {
		time.Sleep(1000 * time.Millisecond)
		t.Logf("now written: %d, read: %d, stop writing", written, read)
		stopWriting.Store(true) // with this line, if the "writing" is stopped ahead, the cmd.Run()/Wait() gets stuck forever
		t.Logf("cancel context (kill process) ...")
		cancel()
	}()

	err := cmd.Run()
	assert.Error(t, err)
	t.Logf("done. written: %d, read: %d", written, read)
}
```

**Comment by wxiaoguang** [comment] 2023-08-04 09:10
And one more thing, after #26325 gets merged, you might see your mirror tasks consume more CPU

Before: the mirror's tasks like "language stats" fails after 10minute timeout

After: the tasks won't fail by timeout, it will try to run as long as possible to finish the "language stats" task, for the "material-design-icons" repo which has more than 580k files, it will run for a pretty long time with CPU=100%. The good news is that the "languages stats" will be right then.

**Closed as completed** 2023-08-04 12:50 UTC
Labels: type/bug, issue/critical
