### ISSUE TITLE
Gitea Pages

### ISSUE THREAD

**Issue by mgite** [go-gitea/gitea#28907] opened 2024-01-23 16:50 UTC
### Feature Description

Recently i created Gitea action to automatically build repo for static pages. I needed same functionality as Github Pages and could not find it in Gitea. Thought after so many years of development Gitea would have it, but was surprised when i found out it still does not have such a simple functionality.

Please provide Github Pages alternative functionality in Gitea.

**Comment by jolheiser** [comment] 2024-01-23 18:00
Ignoring the valuation that it is "simple", we do currently note two viable alternatives that can be used with Gitea.
https://codeberg.org/Codeberg/pages-server
https://github.com/42wim/caddy-gitea

Also a duplicate of https://github.com/go-gitea/gitea/issues/302 and https://github.com/go-gitea/gitea/issues/23521 which have some additional commentary.

**Closed as not planned by jolheiser** 2024-01-23 18:00 UTC
Labels: type/proposal
