### ISSUE TITLE
SSH signed commits with unknown email address appear as key not found regardless of SSH key being verified

### ISSUE THREAD

**Issue by Mikaela** [go-gitea/gitea#18238] opened 2022-01-11 15:57 UTC
### Gitea Version

1.16.0+dev-828-g0857c197a

### Git Version

unknown, try.gitea.io

### Operating System

try.gitea.io

### How are you running Gitea?

I am using try.gitea.io

### Can you reproduce the bug on the Gitea demo site?

Yes

### Log Gist

I don't have one

### Description

When SSH key is added to Gitea and verified, I expected all commits that are signed by that key to appear as verified. However without adding the email address that signed the commits, the commits page stays gray and reports that the key is not found in the database. This was resolved by adding the email address making the commits to my account after which everything turned to green.

I noticed this by mirrorring https://try.gitea.io/Mikaela/ssh-allowed_signers as a test, I had changed my commit email address since last using try.gitea.io due to name change.

### Screenshots

I didn't think of taking them and I imagine the prompt "previous commits remain unchanged" means that I cannot reproduce this issue as simply as removing  the email address.

**Comment by zeripath** [comment] 2022-01-11 17:04
This is not a bug and is by design.

If you allow non-activated email addresses to verify you allow anyone to spoof anyone.

Just because a user owns a key does not mean that that user is who they say are.

**Comment by Mikaela** [comment] 2022-01-12 09:17
Doesn't user verifying a key mean that commits made by that key are made by that user?

Is this also the case with PGP signed commits?

Should I close this or is the bug that it says key not found instead of unverified email address?

**Comment by zeripath** [comment] 2022-01-12 13:32
This should be the same thing with the GPG/PGP case too.

The page should state for which email addresses the key is verifying - I guess we need to be clearer about what the error is however, it depends on the trust model being used.

It's all about how we want to express the trust and verification model. In order to trust or verify a commit we need to do a few things.

Let's talk about Github's "trust" model as this is the one you're most likely to be aware of. Please note that there is no real trust here - it's simply commit verification:

* The committer that made the commit owns the key that signed the commit. 

What does this require:
 
1. The commit is signed
2. That signature matches a key that matches a user
3. That key asserts it matches the email of the committer 
4. That user has proved that they have that email of the committer

Gitea allows a slightly different version of 3 as we allow verification if the user can prove that they have the private key for the public key even if the key itself does not assert that it publicly matches the email of the committer. They can prove this by signing a random token and if they can do that that key can verify any of their email addresses. However, in either case Gitea can only verify commits came from a particular user if we can prove that that user has that email otherwise I could create a key-pair for you, upload it as one of my keys, say I own your email address and start creating verified commits as if I were you. There'd be a split in your identity and the only way to solve it in the end would be to email you.  

For SSH keys there is no inbuilt identity within the key - so in that case the only way of proving that the user really is the committer is by checking that the user has activated the email address. Unfortunately I wasn't involved in the SSH signing PR and so I'm not completely aware if we actually verify that the key is owned by the user who is claiming that it is theirs. I would hope that there was some test of the user asserting ownership of the private key component similar to the token test above.

Note that none of the verification above suggests that you should trust my commits,  all it says is that I wrote them.

Gitea has another trust model, one is where it allow trusted users who don't match the committer to sign commits. In this model collaborators and gitea itself are allowed to (re)sign commits to say that they trust the contents of the commit. This allows authors, committers and signers to be three separate people - but in order to trust a commit signed by a third party you have to trust that third party. This model is not github compatible. The idea here is that some alternative authority can audit and sign an entire commit history saying this is correct. This has the benefit that a committer and author can always remain unchanged as the trust is separate from that of the commit. However, it is not Github compatible and if you need to change who is trusted you will need to re-sign the commits changing their SHA-1s. This is currently the default model for Gitea but as it's complex I think we should change to commit verification as per Github.

Gitea also has another trust model, commit verification is enforced but non-collaborators commits are marked as non-trusted. 

There are a couple of other models that I think we should support - one would be where a public keyring of valid trusted committers can be provided per repository, one where you as a user can express your trust of certain users, and we should consider providing functionality for attestations of validity of commits outside of the signed commit itself, and re-signing of commits too.

**Closed as completed** 2022-01-15 18:35 UTC
Labels: issue/not-a-bug
