### ISSUE TITLE
Error 500 when migrating a repository if the name already exists

### ISSUE THREAD

**Issue by tforgione** [go-gitea/gitea#4225] opened 2018-06-11 18:19 UTC
- Gitea version (or commit ref): I'm on master, but I can reproduce the error on [try.gitea.io](https://try.gitea.io)
- Git version: 2.11.0
- Operating system: Raspbian
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes
  - [ ] No
  - [ ] Not relevant
- Log:
  ```
  2018/06/11 18:09:20 [...routers/repo/repo.go:146 handleCreateError()] [E] MigratePost: repository already exists [uname: tforgione, name: model-converter-python]
    ```

## Description
Basically, trying to migrate a repository on a repository whose name already exists gives error 500.

## Screenshots
![capture du 2018-06-11 20 11 22](https://user-images.githubusercontent.com/3015402/41249455-7a96031c-6db4-11e8-951e-f910fe242e58.png)
![capture du 2018-06-11 20 11 25](https://user-images.githubusercontent.com/3015402/41249461-7d193a5a-6db4-11e8-8339-3e2eb86ef21e.png)

I hope this helps.

**Comment by techknowlogick** [comment] 2018-06-11 18:28
@tforgione Thanks for the bug report. I'm closing this as it is a dupe of #4140

**Closed as completed by techknowlogick** 2018-06-11 18:28 UTC
Labels: issue/duplicate

**Comment by tforgione** [comment] 2018-06-11 18:29
Ah, sorry, should've looked better...
