### ISSUE TITLE
Feature Request: Enable TOC in README

### ISSUE THREAD

**Issue by MFYDev** [go-gitea/gitea#10523] opened 2020-02-28 04:59 UTC
- Gitea version (or commit ref): 1.11.1
- Git version: latest
- Operating system: Ubuntu 18.04
- Database (use `[x]`): 
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Description
Hi there,

Recently when I try to demonstrate my project in detail, I found that the README.md could be so long that it could ruin the user experience. Hence I am wondering that if you can enable `[TOC]` in the markdown file so that we can write it as long as we want.

If you can do that it will be so much appreciated.

**Comment by FanyangMengDev** [comment] 2020-02-28 05:55
Duplicate of #7182 , hoping it would be added

**Comment by guillep2k** [comment] 2020-02-28 06:26
Closing as duplicate of #822

**Closed as completed by guillep2k** 2020-02-28 06:26 UTC
Labels: issue/duplicate
