### ISSUE TITLE
Mirror synchronization should not trigger actions

### ISSUE THREAD

**Issue by mrexodia** [go-gitea/gitea#32412] opened 2024-11-03 13:40 UTC
### Description

There is a major footgun where a user might accidentally execute untrusted actions from a mirrored repository. This issue was introduced by https://github.com/go-gitea/gitea/pull/27482

Reproduction steps:
- Enable gitea actions on your instance
- Set up a runner globally
- Set up a mirrored repository (example https://github.com/mrexodia/runner-funner), no actions executed here
- Push a new commit to the mirrored repository
- Wait for synchronization to trigger

This will execute the actions in the mirrored repository. I noticed this when mirroring a repository from codeberg

## Other providers

I checked and Gitlab has a specific checkbox to [enable pipelines on mirrored repositories](https://docs.gitlab.com/17.5/ee/user/project/repository/mirror/pull.html#trigger-pipelines-for-mirror-updates) (disabled per default):

![image](https://github.com/user-attachments/assets/042abc4b-b80a-4b69-b28d-97949b766b90)

GitHub does not execute the actions on initial import, it has no mirroring feature so there is no comparison.

### Gitea Version

1.22.3

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Default setup with systemd and a caddy reverse proxy, nothing special.

### Database

None

**Comment by yp05327** [comment] 2024-11-04 23:43
#32010 or #30350

**Comment by lunny** [comment] 2024-11-05 06:18
Duplicate of #30350

**Closed as not planned by lunny** 2024-11-05 06:18 UTC
Labels: type/bug, topic/gitea-actions
