### ISSUE TITLE
Calling your repo 'src' breaks rendering of relative paths in markdown

### ISSUE THREAD

**Issue by orre** [go-gitea/gitea#26792] opened 2023-08-29 09:38 UTC
### Description

Reproducer Repo: https://try.gitea.io/Orjan/src

As shown, the rendering of _README.md_ is broken - images are not showing up at all and the links themselves are also broken.

Compare this with https://try.gitea.io/aybe/markdown-branch where everything is rendered correctly.

The only difference of the repos I see is their names. Mine is called **_src_**, and this seems to trigger the problem.

Of course I could name my repo differently, but that dosn't address the real issue.

### Gitea Version

1.21.0+dev-651-g60ca3d04a

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

I'm using latest version on https://try.gitea.io.

### Database

None

**Comment by CaiCandong** [comment] 2023-08-29 13:16
Duplicate of #26548

**Closed as completed** 2023-08-29 19:23 UTC
Labels: type/bug, issue/duplicate
