### ISSUE TITLE
[Update] gitea to the latest gitea version: 1.9.0+rc2, which makes it impossible to push

### ISSUE THREAD

**Issue by zhanghenxiao** [go-gitea/gitea#7594] opened 2019-07-24 08:49 UTC
![image](https://user-images.githubusercontent.com/24770824/61779262-f4ca3080-ae32-11e9-8c27-c7d49a914e67.png)

**Comment by zeripath** [comment] 2019-07-24 09:18
There is no code in 1.9 that can create that message. That's from the 1.8 branch.

You're not running 1.9.

**Comment by zeripath** [comment] 2019-07-24 09:22
If you're definitely running 1.9 as the http server. Presumably you have both the 1.8 and 1.9 binaries installed and you've changed the path to gitea for 1.9. In which case you will need to run the admin task to update/recreate the authorized_keys file.

**Comment by jwegner** [comment] 2019-07-27 15:02
@zeripath
I experienced similar problems, push, fetch didn't work. Your advice to regenerate keys worked for me. I had to regenerate the hooks too, after that everything worked as expected. Thank you :)

**Comment by zeripath** [comment] 2019-07-27 15:51
No problems. I'll close this as invalid - as it's not a bug with Gitea but your install.

**Closed as completed by zeripath** 2019-07-27 15:51 UTC
Labels: issue/not-a-bug
