### ISSUE TITLE
Automatic OIDC login

### ISSUE THREAD

**Issue by DaLynX** [go-gitea/gitea#13795] opened 2020-12-02 17:46 UTC
- Gitea version (or commit ref): 1.12.4
- Git version: 2.28.0
- Operating system: FreeBSD
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description

Hello,

I have setup a gitea instance on my server and successfully added my OIDC provider. However, I would like to make so that users are automatically redirected to the OIDC provider if not authenticated, without having to click the "OpenID Connect" button.

I did not find any setting to do so or any mention in the documentation. Is it possible? If not, could it be considered for implementation?

**Comment by ailox** [comment] 2021-02-21 11:07
I support this issue, but it seems to me this is a duplicate of both https://github.com/go-gitea/gitea/issues/7633 and https://github.com/go-gitea/gitea/issues/6352 , so maybe it can be closed?

**Comment by lunny** [comment] 2021-02-21 16:55
Closed as duplicated mentioned above.

**Closed as completed by lunny** 2021-02-21 16:55 UTC
Labels: type/proposal
