### ISSUE TITLE
Weird css fonts on Firefox after upgrading to V1.13.0 

### ISSUE THREAD

**Issue by waterdrop01** [go-gitea/gitea#13821] opened 2020-12-03 17:08 UTC
- Gitea version (or commit ref): v1.13.0
- Database (use `[x]`):
  - [x ] MariaDB

## Description
After upgrading to 1.13.0, as you can see on the screenshot below, the numbers look odd, and there are space between words.
## Screenshot
![Screenshot from 2020-12-03 17-59-35](https://user-images.githubusercontent.com/47316824/101062821-63c0a900-3592-11eb-896d-9aa45391715d.png)

I tried clearing the cache on Firefox without help. It works perfectly on Chrome.
Thanks for your help!

**Comment by silverwind** [comment] 2020-12-03 18:00
What does the devtools font inspector show on those numbers? (Ctrl-Shift-C, Click Number, Switch to Fonts tab on the right side panel).

**Comment by techknowlogick** [comment] 2020-12-03 18:13
Closing as dupe of https://github.com/go-gitea/gitea/issues/13784

**Closed as completed by techknowlogick** 2020-12-03 18:13 UTC
Labels: issue/duplicate
