### ISSUE TITLE
Link to user profile in issue list is missing server URL

### ISSUE THREAD

**Issue by steko** [go-gitea/gitea#16713] opened 2021-08-17 14:42 UTC
- Gitea version (or commit ref): 1.16.0+dev-116-g274aeb3a9 
- Git version: n/a
- Operating system: n/a
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/issues (for logged in users with at least one issue) AND https://try.gitea.io/steko/webhook-test/issues/1 
  - [ ] No

## Description
In the issue list, the name of the user who created the issue has a link to the user profile (under the issue title: issue#123 opened 12 hours ago by user). However, the href points to https://<username> instead of https://<instance.tld>/<username>. This happens both on the user dashboard and the repository issue list. Both are caused by these lines in the `issuelist.tmpl` file:

https://github.com/go-gitea/gitea/blob/274aeb3a9e13da47a925eabe0e43ed0b1424d02a/templates/shared/issuelist.tmpl#L57-L63

In the issue page, the same behavior is seen next to the open/closed label.

This seems caused by these lines in `view_title.tmpl`:

https://github.com/go-gitea/gitea/blob/ab77a24f18ae45248bd6c71778fe3bfacacf864f/templates/repo/issue/view_title.tmpl#L92-L98

## Screenshots
See in the bottom left the URL preview pointing to https://steko instead of https://try.gitea.io/steko
![Schermata da 2021-08-17 16-16-37](https://user-images.githubusercontent.com/40545/129743364-589c21a8-26d6-4b1b-a760-96208d2344ac.png)

This is the issue page:
![immagine](https://user-images.githubusercontent.com/40545/129744024-714776d3-3910-49f5-a517-f7139df7e10f.png)

**Comment by noerw** [comment] 2021-08-23 09:15
I can't reproduce this, also on the try link you provided, probably already fixed?

**Comment by steko** [comment] 2021-08-23 10:59
I just checked again on try.gitea.it and I still see the same issue as described, so I wouldn't say it's been fixed.

**Comment by noerw** [comment] 2021-08-23 11:16
the link that gets rendered does not contain a domain section, and as such works correctly for me
![image](https://user-images.githubusercontent.com/7880552/130438535-345ff114-d768-4cab-9908-48a6633ff480.png)
maybe a browser extension meddles with your links? 🤔

**Comment by steko** [comment] 2021-08-23 12:33
Oh no I found the culprit. It's specific to Italian language, the href value is `//steko` because there's an extra "/" in the translation string. Can I submit a PR directly or do I need to go through Crowdin?

https://github.com/go-gitea/gitea/blob/94f529af02e74f5d13fefda48d3ef9db4559f71f/options/locale/locale_it-IT.ini#L1060

**Comment by steko** [comment] 2021-08-23 12:52
I submitted a proposal for correcting the translation on Crowdin.

**Comment by noerw** [comment] 2021-08-23 13:03
Great, I'll close this then

**Closed as completed by noerw** 2021-08-23 13:03 UTC
Labels: issue/needs-feedback

**Comment by zeripath** [comment] 2021-08-23 19:47
agh we better backport a fix to 1.15
