### ISSUE TITLE
Kanban Feature Request: Allow to change the order of issues on boards

### ISSUE THREAD

**Issue by neszt** [go-gitea/gitea#15551] opened 2021-04-20 09:09 UTC
- Gitea version (or commit ref): 1.14.0 built with GNU Make 4.3, go1.16.3 : bindata, timetzdata, sqlite, sqlite_unlock_notify
- Git version: 2.30.2
- Operating system: Linux, k8s
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite

## Description

Allow sort the issues on boards.

Now the frontend allow sorting (mouse drag and drop) but the sorted state is not saved, after reloading the page, the order is lost.

Anyway, I think this is a misleading operation, the interface suggests that you can change the order of the issues.

**Comment by delvh** [comment] 2021-04-20 13:05
Duplicate of #11161.
But agreed, it is time project cards save their order.

**Closed as completed** 2021-04-20 15:18 UTC
Labels: issue/duplicate
