### ISSUE TITLE
Assigning a PR causes server to hang

### ISSUE THREAD

**Issue by pixelspark** [go-gitea/gitea#8746] opened 2019-10-30 10:18 UTC
- Gitea version (or commit ref): v1.9.4 (using Docker image `gitea/gitea:1.9.4`)
- Git version: 2.22.0 (the one included in ` gitea/gitea:1.9.4` Docker image)
- Operating system: Linux, in Docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist: https://gist.github.com/pixelspark/ea9fbe6b6feb0759eaa9f9985b5fb50d

## Description

First of all, great work on this project!

Assigning a pull request on our Gitea instance, which runs using SQLite, causes the Gitea server to hang and stop responding to new requests, until the gitea process is killed (kill -9 is required even!). The logs do not appear to say anything useful. Please let me know what additional information would be of interest in order to find this problem.

This appears to be highly similar to #5639, except that one was supposedly fixed. We have experienced this problem before on earlier versions of Gitea as well. Note that we are also running SQLite.

The interesting thing is that this happens consistently in the repositories we use daily, but does not appear to happen in a freshly created repository. See the attached screen captures.

## Screenshots

![assign-issue-2](https://user-images.githubusercontent.com/181337/67849375-c9787100-fb06-11e9-8b98-a2171fdca3b5.gif)
![assign-issue](https://user-images.githubusercontent.com/181337/67849377-ca110780-fb06-11e9-8974-394bda11512f.gif)

**Comment by guillep2k** [comment] 2019-10-30 12:01
Sounds like a deadlock in the database to me. Please note that SQLite allows only one query/connection at a time, and two simultaneous operations can compete for the same resource locking each other. Most operations run sequentially, but some attempt to execute in parallel, and those might be the ones giving you trouble.
We use SQLite for our unit and integration tests because it requires minimum setup, but it's definitely not an appropriate database for a site where more than one user may be connected at any given time (or even webhooks, background operations, etc). I'd suggest you migrate to another supported database.

**Comment by pixelspark** [comment] 2019-10-30 14:29
>  it's definitely not an appropriate database for a site where more than one user may be connected at any given time

I am aware and I performed I migration today to MySQL (this is not so straightforward - creating a schema by installed from scratch, then moving over the data using DBeaver appears to work fine).

Note that the bug is indeed gone now (exact same version of Gitea, same environment, same database, only now in MySQL).

**Comment by zeripath** [comment] 2019-10-31 07:47
Damn another deadlock must have sneaked in. I spent a very long time checking for these earlier this year - (I bet it is in the notification system. It really needs to be moved out of thread already.)

@guillep2k although the probably will "disappear" with MySQL etc. It's not resolved - we're just relying on deadlock resolution in those databases which means that one of those queries is likely to be killed leading to a Heisenbug.

Sqlite deadlocking is really helpful for us as developers because we actually see which action causes the deadlock.

We have to take them seriously when we see them even if other DBs aren't obviously affected.

**Comment by guillep2k** [comment] 2019-10-31 12:16
@zeripath sqlite deadlocks are a little different in that the whole database is locked by each connection, while other databases can lock individual tables or rows. I don't think an SQLite deadlock is the same as other databases in terms of design or diagnostics. 😉

**Comment by lunny** [comment] 2019-11-03 09:34
Cannot reproduce this on my macbook.

**Comment by zeripath** [comment] 2019-11-03 20:40
@lunny it won't happen in a fresh repository - If I had to bet you need to be assigning to a person who is watching the repository.

Do we really need to keep `notifyWatchers` within the same goroutine and session?

**Comment by zeripath** [comment] 2019-11-03 20:50
@pixelspark OK looking at your (quite brief) logs the deadlock appears to be happening in /ORGNAME/REPONAME/issues/assignee

Do you have any more logs at all? The Xorm logs (suitably censored) would likely show the causative query which could let us work out where the deadlock is.

**Comment by lunny** [comment] 2019-11-04 04:44
@zeripath That's what I'm refactoring with `notifyWatchers`. Yes, I think we should keep them on the same goroutine and session.

**Comment by lunny** [comment] 2019-11-04 05:01
@zeripath That's what I'm refactoring with `notifyWatchers`. Yes, I think we should keep them on the same goroutine and session.

**Comment by pixelspark** [comment] 2019-11-04 11:21
> @pixelspark OK looking at your (quite brief) logs the deadlock appears to be happening in /ORGNAME/REPONAME/issues/assignee
> 
> Do you have any more logs at all? The Xorm logs (suitably censored) would likely show the causative query which could let us work out where the deadlock is.

Will have to look into the log archive as I migrated the instance to MySQL shortly after. I suspect that this issue occurs for repositories that have webhooks (we had those on the affected repositories for signaling Drone builds).

**Comment by pixelspark** [comment] 2019-11-04 11:27
XORM log (all entries containing "10:08", the time around when this happened): https://gist.github.com/pixelspark/865f287161d5c59a3e9451d7de6f0d56

**Closed as completed** 2022-04-12 23:22 UTC
Labels: issue/confirmed
