### ISSUE TITLE
Cron tasks can not find git repos time to time

### ISSUE THREAD

**Issue by rozhuk-im** [go-gitea/gitea#13175] opened 2020-10-16 12:31 UTC
- Gitea version (or commit ref): 1.12.4
- Git version: 2.28.0
- Operating system: FreeBSD 12.2 amd64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
In notices from past 3 days we got:
```
Failed to health check repository (ZZZ/RRRR): chdir /var/db/gitea/repositories/zzz/rrrr.git: no such file or directory
Failed to health check repository (ZZZ/RRRR): exit status 4 - error in commit...
Failed to health check repository (ZZZ/RRRR): chdir /var/db/gitea/repositories/zzz/rrrr.git: no such file or directory
Failed to health check repository (ZZZ/RRRR): exit status 4 - error in commit...
Failed to health check repository (ZZZ/RRRR): exit status 128 - fatal: not a git repository (or any of the parent directories): .git\n
```
ZZZ/RRRR - has wrong commits and ```exit status 4``` mean that fsck run ok.
/var/db/gitea - symlink (```ln -s```) to some location, never changed.
On other mine installation I have same config, except no symlink and have no issues with cron+repos.

This bug + https://github.com/go-gitea/gitea/issues/13174 = gitea removes all my repos every 72 hours.

Possible this is FreeBSD specific, but it is very annoying to lost all repos record.
Before 1.12.4 we got only fsck errors.

**Comment by zeripath** [comment] 2020-10-16 17:26
A git fsck warning message does not delete repositories. It's just that a warning message.

`chdir /var/db/gitea/repositories/zzz/rrrr.git: no such file or directory` is coming from your git installation. If you can't chdir to a directory that means imo that there is something drastically wrong with your filesystem, kernel or most likely hardware. We're just using plain old git fsck here - there's nothing that is involved with gitea specifically.

**Comment by rozhuk-im** [comment] 2020-10-16 17:58
This installation works 1,5 year, only show this errors/warnings in gitea log.
There is no other issues on that system, kernel, OS, filesystem, hardware - is ok.

Possible that some times some error happen inside ```com.IsDir(repo.RepoPath())``` and it is wrongly interpreted: "not ok" = "no dir", but possible here some EBUSY/EAGAIN or other error code, not ENOENT.

Well, I see code and looks like it interpret any error as "no dir": https://github.com/go-gitea/gitea/blob/66a9ef90362db1280808ff74e40c2e670f992fcb/modules/git/utils.go#L46


```exit status 128 - fatal: not a git repository (or any of the parent directories): .git``` - this is very strange, why ```.git```!?

**Comment by zeripath** [comment] 2020-10-16 18:20
The errors fstatat can return are:

https://www.freebsd.org/cgi/man.cgi?query=fstatat&sektion=2#ERRORS

**Comment by rozhuk-im** [comment] 2020-10-16 18:41
In any case ```isDir()``` does not allow to handle errors.

**Comment by zeripath** [comment] 2020-10-17 08:49
Would you like to make a PR to fix?

**Comment by rozhuk-im** [comment] 2020-10-17 09:41
Sorry, I do not spoke on GO and this is to complex change to start :)

**Comment by zeripath** [comment] 2020-11-28 05:01
I'm just gonna reopen this issue because the associated pr just means that we'll see the underlying cause for this issue rather than actually solve it. 

@rozhuk-im now we have merged this PR would you be able to replicate the original problem and tell us what is really happening?

If you can no longer reproduce please close this again.

**Comment by zeripath** [comment] 2021-06-21 20:32
This has been awaiting further feedback since November and therefore I'm going to close this.

Should this happen again - please reopen or open another issue.

**Closed as completed by zeripath** 2021-06-21 20:32 UTC
Labels: issue/needs-feedback
