### ISSUE TITLE
Add meilisearch support for code indexer

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#29434] opened 2024-02-26 21:27 UTC
enhancement to  #20665

by adding **meilisearch** to  [`REPO_INDEXER_TYPE`](https://docs.gitea.com/administration/config-cheat-sheet?_highlight=REPO_INDEXER_TYPE#indexer-indexer)

**Comment by lunny** [comment] 2024-02-27 06:13
duplicate of #25976

**Closed as completed** 2024-02-27 06:14 UTC
Labels: issue/duplicate
