### ISSUE TITLE
Expand commit file list height issue

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#23845] opened 2023-03-31 09:47 UTC
### Description

When showing the list of files of commits, the option to expand/collapse the file list is not visually working properly.

When expanding the list, the area showing the list is too small in height.
It should cover the entire height of the page, but it only shows one or two lines with a vertical scrollbar.
This makes showing the list useless as you do not have a clear overview of the files. You need to use the scrollbar which is terrible.

### Screenshots

![ExpandedList](https://user-images.githubusercontent.com/15105219/229086101-221badf6-3c05-4517-89d8-5657d9526791.png)
![CollapsedList](https://user-images.githubusercontent.com/15105219/229086107-97e13103-1b1a-4496-a8aa-83ccf1e4c6f1.png)

### Gitea Version

1.19.0+3-g782c376c8 built with GNU Make 4.1, go1.20.2 : bindata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Server=Linux ARM64, client=Windows 10

### Browser Version

Firefox & Chrome

**Comment by DaveRabelink** [comment] 2023-03-31 09:52
Here a screenshot when using the scrollbar. It clearly shows that the file list area is just a few lines in height.

![Scrolling](https://user-images.githubusercontent.com/15105219/229087897-0ce05a7d-f09f-4610-9ca4-bdee0280eb52.png)

**Comment by wxiaoguang** [comment] 2023-03-31 09:52
It has been fixed on latest nightly build.

Download the binary from https://dl.gitea.com/gitea/1.19/

**Comment by DaveRabelink** [comment] 2023-03-31 10:04
Yes, using latest build:
1.19.0+37-g8b3dd7de5 built with GNU Make 4.1, go1.20.2 : bindata, sqlite, sqlite_unlock_notify

The issue is indeed solved, see screenshot below:

![FixedHeight](https://user-images.githubusercontent.com/15105219/229090627-f6c25265-f8d3-4f1b-8fa5-72d06adb17e9.png)

**Closed as completed** 2023-03-31 10:05 UTC
Labels: type/bug, topic/ui
