### ISSUE TITLE
Custom event > releases payload does not contain secret

### ISSUE THREAD

**Issue by AuspeXeu** [go-gitea/gitea#5173] opened 2018-10-25 03:07 UTC
- Gitea version (or commit ref): 1.5.2
- Git version: 2.9.3
- Operating system: CentOS
- Database:
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Not relevant
## Description
When setting up a gitea webhook, one can provide a secret that is supposed to be included in the delivered POST `application/json` payload. This works fine for "Push Events", however when choosing "Custom Events..." and selecting "Releases", this secret is not included in the payload anymore.

**Comment by AuspeXeu** [comment] 2018-11-12 07:36
I just tested the latest version `1.6.0-rc2` and it seems like this issue is still not resolved. Now, if I trigger a test delivery for a custom event of the type release, no request is queued whatsoever.

Edit: I tried this on the demo instance with the following settings.

![screen shot 2018-11-12 at 16 04 02](https://user-images.githubusercontent.com/2115696/48355566-9f7b3400-e694-11e8-9e63-fd9e5cdd4092.png)

As you can see here, no requests are received http://requestbin.net/r/1oa26911?inspect

**Comment by HoffmannP** [comment] 2018-11-14 15:46
Could you explain "trigger a test delivery"? I tried to retrace your steps but couldn't find the same error

**Comment by AuspeXeu** [comment] 2018-11-14 16:25
I simply press the "Test Delivery" button :)

**Comment by HoffmannP** [comment] 2018-11-14 17:12
Okey, but it looks to me as if the TestDelivery is always executing a push event. If your webhook only acts on releases it will not be triggered. https://github.com/go-gitea/gitea/blob/4c1f1f96465e809161f7d634a07eb60b4511db35/routers/repo/webhook.go#L677

Perhaps the button should be renamed to "Test push event"

**Comment by AuspeXeu** [comment] 2018-11-14 17:21
My intuition was that the button tests whatever hook is specified at the top?!
Anyways, I had to put a new request bin, here the link to inspect it http://requestbin.net/r/wy4b3rwy?inspect

I pushed a tag (release) to the repository under https://try.gitea.io/test1337/Hooktest and it did not trigger a request to the request bin. So something seems to be broken, no?

Edit: Okay, I just figure out what the problem is. I am actually not sure whether it's a problem or by design. But there is definitely some confusion. If I create a tag and push it, the tag appears under `releases` in the repository, however the custom event hook is not triggered. BUT, if I create a release via the webinterface, the hook is triggered.

So here is some inconstancy. Either a normal tag should not be a release or it is considered a release and it should trigger the hook.

**Comment by lafriks** [comment] 2018-11-16 16:09
@AuspeXeu tag without release in release list page is displayed differently

**Comment by lafriks** [comment] 2018-11-16 16:11
release will be triggered when you create release (either by UI or API) either on new tag or existing. Pushing tag from git command will not create release, this is by design so

**Comment by AuspeXeu** [comment] 2018-11-16 16:46
Okay, I guess it's all working correctly then in that case.

**Comment by HoffmannP** [comment] 2018-11-18 19:41
Closeable?

**Comment by AuspeXeu** [comment] 2018-11-18 19:45
I guess so :) - thanks for your efforts!
Edit: Actually ... I think the test delivery is still a bug, no? It should test whatever you set up instead of a push event?

**Comment by lafriks** [comment] 2018-11-22 20:56
Test delivery will always issue push event

**Comment by AuspeXeu** [comment] 2018-11-22 21:29
Why? :D

**Comment by lafriks** [comment] 2018-11-23 20:18
Because it is just for testing if target can be reached not to test actual functionaliity

**Comment by AuspeXeu** [comment] 2018-11-23 20:58
Well, but exactly this is not happening. If you set the hook to custom event as I showed above, and then press "test delivery" nothing happens. It claims that a fake event has been generated but no request ever reaches the specified endpoint.

Edit: these are the settings
![image](https://user-images.githubusercontent.com/2115696/48960234-1bb22900-ef6b-11e8-8752-5b57fc277107.png)

And no request reaches https://requestbin.fullcontact.com/1h3kkfs1?inspect

**Comment by lafriks** [comment] 2018-11-23 21:33
Ok, now I understand the problem. It is tested if event type is enabled before sending. This would require option to choose what kind of event to send then and implement each event type webhook content generation. I don't think that is worth time needed to develop this the gains.

**Comment by AuspeXeu** [comment] 2018-11-23 21:47
Well, if we could at least have a delivery test that would be great :) One option could be, as you said, to always send a push event type. That way one could at least verify that the endpoint is reachable, no?

**Comment by lafriks** [comment] 2018-11-23 22:00
If you enable push events and then try test delivery than it will work and do request. Later you can disable it again

**Comment by AuspeXeu** [comment] 2018-11-23 22:29
Basically my point is, if someone is new to gitea and sets up a custom event webhook, they will wonder why the test delivery does not work unless the read this particular issue with our comments.

**Comment by lafriks** [comment] 2018-11-24 11:12
We could probably add warning if push event is not enabled

**Comment by 6543** [comment] 2020-04-23 13:53
Whats the state of this issue?

**Comment by techknowlogick** [comment] 2020-04-23 13:56
Secret inside the payload has been deprecated, and the hmac header of webhook should now be used. Closing this issue.

**Closed as completed by techknowlogick** 2020-04-23 13:56 UTC
