### ISSUE TITLE
Edit Authentication Source broken

### ISSUE THREAD

**Issue by anbraten** [go-gitea/gitea#18432] opened 2022-01-27 13:28 UTC
### Gitea Version

v1.16.0-rc1

### How are you running Gitea?

using docker-compose

### Can you reproduce the bug on the Gitea demo site?

No

### Description

Seems like there is an error in the edit screen for editing authentication sources.

### Screenshots

![Screenshot from 2022-01-27 14-26-01](https://user-images.githubusercontent.com/6918444/151368105-38bc6289-ed2d-469e-abb6-143c2523e096.png)

**Comment by lafriks** [comment] 2022-01-27 13:29
Duplicate of #18388

**Closed as completed by lafriks** 2022-01-27 13:29 UTC
