### ISSUE TITLE
suddenly cannot (web)login but repos work

### ISSUE THREAD

**Issue by persianphilosopher** [go-gitea/gitea#1046] opened 2017-02-24 17:53 UTC
Hi there,

I am having a strange problem all of a sudden. I can no longer login through the web interface (it says it's the wrong password and I had sadly disabled reset/create user options).

On three servers, my repos work with the same login/password. 

Not sure where to start. Any direction would be appreciated.

**Comment by lunny** [comment] 2017-02-26 06:27
cannot reproduce this.

**Comment by ivilata** [comment] 2018-02-19 23:18
I experienced something similar when upgrading from Gogs to Gitea.  When examining the SQLite db with ``sqlite3 gogs.db .dump`` it turned out to only show table schemas but no data at all.

With services stopped, I recovered the ``gogs-db.sql`` from a backup created with ``gogs dump`` by running ``sqlite3 new-gogs.db < gogs-db.sql`` and replaced the db file. After that it worked like a charm.

Please backup your db before attempting this!

**Comment by lafriks** [comment] 2018-02-19 23:33
Closing issue as no additional info was provided

**Closed as completed by lafriks** 2018-02-19 23:33 UTC
Labels: type/question
