### ISSUE TITLE
Discord webhook uses wrong urls on issue updates

### ISSUE THREAD

**Issue by radonthetyrant** [go-gitea/gitea#4758] opened 2018-08-21 16:35 UTC
- Gitea version (or commit ref): 1.5.0 (try.gitea.io is on 05dcfcf)
- Git version: 2.7.4
- Operating system: Ubuntu 16.04.5 LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When a discord webhook is setup with the setting "All events" and an issue is created/edited/closed, the link that gets sent to the discord channel points to a json api url, instead of the actual issue url.

## Screenshots

![image](https://user-images.githubusercontent.com/4189978/44415332-7acd5f80-a570-11e8-8510-c45ba11d7252.png)

![image](https://user-images.githubusercontent.com/4189978/44415358-8882e500-a570-11e8-842d-df07e5f7eb5b.png)

![image](https://user-images.githubusercontent.com/4189978/44415377-93d61080-a570-11e8-88c6-fd54806fc29b.png)

![image](https://user-images.githubusercontent.com/4189978/44415391-9cc6e200-a570-11e8-9a9a-12eb1895f050.png)

![image](https://user-images.githubusercontent.com/4189978/44415455-c08a2800-a570-11e8-8de4-d4207955b953.png)

**Comment by adelowo** [comment] 2018-08-21 17:48
Duplicate of #4656

**Closed as completed** 2018-08-21 17:48 UTC
Labels: issue/duplicate
