### ISSUE TITLE
Allow selecting protected branches by pattern

### ISSUE THREAD

**Issue by jsil3601** [go-gitea/gitea#14461] opened 2021-01-25 19:51 UTC
This is a suggestion for improvement. 
My knowledge of gitea code or go Lang is insufficient to pr this. 

Currently, to add a branch to 'branch protection' , we need to create the branch, goto repo settings, and then select it individually from drop down, and set its security setting (allowed push teams, voters etc). 
This means every time we have a  new release branch, we need to go through this process, which is repetitive and prone to human error. 

It will be very helpful if we could add a pattern, (such as release*, similar to how we select branches by pattern in the 'webhooks' page) thus allowing to select the protection settings by pattern and not one by one. As new branches are added in the future if they match the pattern they will also be protected. 

Is this feature interesting to the gitea community /devs? 

Thanks

**Comment by lunny** [comment] 2021-01-26 01:56
Hm, I think there is already an issue to report this.

**Comment by jsil3601** [comment] 2021-01-26 05:02
I didn't find such an issue... Is this something that's planned for implementation?

**Comment by lunny** [comment] 2021-01-26 07:21
I think this is a duplicate of #2529 . There is no plan for that.

**Comment by jsil3601** [comment] 2021-01-30 10:34
Yes you are right it's a duplicate. Can this be looked at for a future release?

**Closed as completed** 2021-01-30 15:40 UTC
Labels: issue/duplicate
