### ISSUE TITLE
Repository of private Organisation not shown in List "Repositories" in "/dashboard"

### ISSUE THREAD

**Issue by lucas-gaitzsch** [go-gitea/gitea#6893] opened 2019-05-09 14:09 UTC
- Gitea version (or commit ref): 1.8.1
- Git version: -
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes ( https://try.gitea.io/org/private-test_org/dashboard )
  - [ ] No
  - [ ] Not relevant

## Description

A Repository of private Organisation is not shown in the List of "Repositories" in the Dashboard (.../dashboard).

The Repository belongs the private Organisation (1st Screenshot). But the Repository is not visible in the Dashboard of the User (Owner of the Organisation) and its as well not shown in the Dashboard of the Organisation itself.

If the Oranisation is public, the Repository was shown in the Dashboard.

## Screenshots

<img width="1280" alt="gitea1" src="https://user-images.githubusercontent.com/6965260/57459271-335c4000-7273-11e9-825f-e964817edcef.png">
<img width="1277" alt="gitea2" src="https://user-images.githubusercontent.com/6965260/57459272-335c4000-7273-11e9-8ab1-d69fb065be55.png">
<img width="1278" alt="gitea3" src="https://user-images.githubusercontent.com/6965260/57459273-335c4000-7273-11e9-9e12-2d7db5846621.png">

**Comment by techknowlogick** [comment] 2019-05-09 14:11
Closing as dupe of #6195

**Closed as completed by techknowlogick** 2019-05-09 14:11 UTC
Labels: issue/duplicate
