### ISSUE TITLE
When upgrading to gitea 1.22.1, must_change_password is set to true

### ISSUE THREAD

**Issue by agateaux** [go-gitea/gitea#31758] opened 2024-08-01 21:37 UTC
### Description

I was using Gitea for Kubernetes 1.21.11.

After having upgraded to 1.22.1, I noticed my admin couldn't login anymore.
When I tried to login manually, it asked me to change the password.

After having looked in the database, the user table column 'must_change_password', which was unset before the upgrade, has been set to true during the upgrade database migration.

It should be kept to empty or false to avoid any big issues.

### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

In Kubernetes

### Database

PostgreSQL

**Comment by lunny** [comment] 2024-08-01 21:45
After taking a tour of all migrations of 1.22, it seems no migration will set must_change_password.

**Comment by agateaux** [comment] 2024-08-01 22:00
But this is something I observe each time I try an upgrade.

I noticed, in your changelog: https://github.com/go-gitea/gitea/pull/27626
And https://github.com/go-gitea/gitea/pull/30472

Could they have an impact on the database?

**Comment by lunny** [comment] 2024-08-01 22:12
Both PR haven't introduced migrations. They are just for commandline.

**Comment by agateaux** [comment] 2024-08-01 22:14
And when the new gitea is starting, could there be an init, not a migration, running a command line, and activating this boolean?

**Comment by lunny** [comment] 2024-08-01 22:44
> And when the new gitea is starting, could there be an init, not a migration, running a command line, and activating this boolean?

I don't think so.

**Comment by techknowlogick** [comment] 2024-08-02 01:16
> I don't think so.

@lunny, I'm assuming @agateaux is using the helm-chart as they mentioned they are using k8s, and the helm-chart, as they thought, does use an init script which calls the command line. So this could be the case.

cc-ing helm-chart managers @justusbunsi @pat-s to keep you in the loop, in case you think this is best discussed in the helm-chart repo.

**Comment by justusbunsi** [comment] 2024-08-02 05:51
@techknowlogick thanks for the ping.
@agateaux Please upgrade to Helm Chart version https://gitea.com/gitea/helm-chart/releases/tag/v10.3.0 or later. This issue has been fixed.

**Comment by agateaux** [comment] 2024-08-02 17:44
Thanks a lot for your help.

We are not using the Helm chart, but a gitea operator.

I ported the same fix on the upgrade script, and now it works without changing the database column.

**Comment by lunny** [comment] 2024-08-02 18:17
Since Gitea cannot do anything about this issue. I think this could be closed.

**Comment by agateaux** [comment] 2024-08-02 18:20
Maybe a clearer documentation about this breaking change? Like when you use init scripts, it could break your users journey?

**Comment by lunny** [comment] 2024-08-02 19:12
> Maybe a clearer documentation about this breaking change? Like when you use init scripts, it could break your users journey?

As I know Gitea just provides a command line tool. No official init scripts for Gitea itself.
Old helm chart's init script used this command line tool. But the new version will not do that? Maybe you mean add a breaking change label for the helm-chart? If that, this could be finished in https://gitea.com/gitea/helm-chart but not here because it's unrelated.

**Comment by justusbunsi** [comment] 2024-08-02 19:21
> > Maybe a clearer documentation about this breaking change? Like when you use init scripts, it could break your users journey?
> 
> As I know Gitea just provides a command line tool. No official init scripts for Gitea itself.
> Old helm chart's init script used this command line tool. But the new version will not do that? Maybe you mean add a breaking change label for the helm-chart? If that, this could be finished in https://gitea.com/gitea/helm-chart but not here because it's unrelated.

@lunny, https://github.com/go-gitea/gitea/pull/27626 should've been marked as breaking change for that very command line tool. Our Helm Chart still rely on it in the init scripts. Since the introduced flag did not exist before, there was no way to configure it earlier. With the introduction the default behavior without passing the flag changed. I am not sure if this was intended or not. It _was_ breaking. 🙂

Have we ever marked a PR breaking after a release and adjust the release notes? If not, this might be the "clearer docs" the user asked for.

**Comment by agateaux** [comment] 2024-08-02 19:42
That's exactly what I propose, thanks a lot.

In your documentation (https://blog.gitea.com/release-of-1.22.0/), this line is part of enhancements: 
`Add must-change-password command line parameter (#27626)`, but behind, default which 'false' is now 'true'.

**Comment by techknowlogick** [comment] 2024-08-03 05:32
This is good feedback to have, thank you :) Is the operator published anywhere?
I've marked the related PR as breaking, and the blog post could be updated (I've made an issue in the blog tracker so this doesn't get lost). As that issue has been created over there, I will close this issue.

**Closed as completed by techknowlogick** 2024-08-03 05:32 UTC
Labels: issue/not-a-bug

**Comment by agateaux** [comment] 2024-08-05 14:19
Yes, FYI, our operator is based on this one https://github.com/integr8ly/gitea-operator, now unmaintained.
We forked it and have simplified it a lot.
Our version is not published.
