### ISSUE TITLE
Wrong `project_board_id` for newly created issue

### ISSUE THREAD

**Issue by bilogic** [go-gitea/gitea#30701] opened 2024-04-25 09:50 UTC
### Description

![image](https://github.com/go-gitea/gitea/assets/946010/85077227-2499-4f83-b6c3-b1d75d7366da)

If I create an issue and add it to a project, its `project_board_id` is 0, but it should not be.

Instead, `project_board_id` should either be the value of the default board or board with lowest `sorting`

### Gitea Version

1.21.11+9-g0e20ccfe32

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker

### Database

None

**Comment by wxiaoguang** [comment] 2024-04-25 11:25
It seems a release blocker

**Comment by lunny** [comment] 2024-04-25 13:07
That table column name should be renamed `project_column_id`, https://github.com/go-gitea/gitea/pull/30170 is the first step to correct the names.

**Comment by lunny** [comment] 2024-04-26 14:10
This should be caused by #29874 and will be fixed by 30696

**Comment by bilogic** [comment] 2024-04-26 14:46
Will it be in the nightly release?

**Comment by lunny** [comment] 2024-04-28 04:33
> Will it be in the nightly release?

Yes, once it merged and I expect it can be backported to v1.22

**Comment by bilogic** [comment] 2024-04-28 04:38
I'm on 1.22.0-rc1 now, let me know what to do to test it. Thank you.

**Comment by KazzmanK** [comment] 2024-05-07 14:05
It is still created with 0 instead of default board ID. 
Why it is not Okay ? 

If i move issue to other column (board) and take it back,  0-> actual board id.

May be, having issue without actual appointments to be shown on _currently_ default board is normal ?

**Comment by lunny** [comment] 2024-05-07 14:11
Because v1.22, all project_issue should have a column id. 0 will not be displayed on the project board view UI. #30696 will fix this and will be backport to v1.22

**Comment by bilogic** [comment] 2024-05-07 17:24
> It is still created with 0 instead of default board ID. Why it is not Okay ?

I have not come across any project that uses 0 as a database ID, it typically starts from 1 and null if it does not have an ID

**Closed as completed** 2024-05-08 13:44 UTC
Labels: type/bug, topic/projects
