### ISSUE TITLE
Migrating repo with LFS causes 500 error

### ISSUE THREAD

**Issue by Shuenhoy** [go-gitea/gitea#31137] opened 2024-05-28 13:57 UTC
### Description

https://gitea.com/Shuenhoy/vtk-m is migrated from https://gitlab.kitware.com/vtk/vtk-m. 
Accessing the `data` folder will trigger 500 error.

Whether selecting `migrate LFS files` is the same.
In the demo site, https://demo.gitea.com/Shuenhoy/vtk-m will not trigger 500 error, but it doesn't treat the files as LFS files at all. 

### Gitea Version

1.22.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/2196156/ea374c37-f06b-41bf-9016-26bfa81bbc3b)

(On my instance, there is an extra message)
```
An error occurred:

getFileReader, LFS Meta object does not exist
```

### How are you running Gitea?

Docker

### Database

None

**Comment by wolfogre** [comment] 2024-07-12 07:39
It was caused by the fact that the original remote has missing LFS objects. I found it but maybe not the only one: oid `137439af2a14dfaab461b07e643fb45dc8e898690f21ca9514cc794dc4afd50a` with size 30144. GitLab returned `Object does not exist on the server or you don't have permissions to access it`.

And you can find it in commit [fecea93da490d460709001ce18c389154c36633c](https://gitlab.kitware.com/vtk/vtk-m/-/commit/fecea93da490d460709001ce18c389154c36633c), the preview is broken.

<img width="1245" alt="image" src="https://github.com/user-attachments/assets/d989af6c-5c5e-418b-bc51-72651ed44830">


But what makes it worse is that Gitea doesn't skip the missing objects, it just stops migrating LFS immediately but treats the migration as successful, so you could see most LFS objects are broken. It will be fixed by #31623.

**Closed as completed** 2024-07-31 10:29 UTC
Labels: type/bug, topic/lfs
