### ISSUE TITLE
API: no support to attach files to an issue

### ISSUE THREAD

**Issue by fhuberts** [go-gitea/gitea#16027] opened 2021-05-30 09:50 UTC
- Gitea version (or commit ref): 1.14.2+29-g3a79f1190 (self-packaged, private server)
- Git version: 2.31.1
- Operating system: Fedora 34 x64, running from systemd
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io: not relevant
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist: not relevant

## Description
The API does not allow me to attach files to an issue (the UI does allow me to do that)

This prevents me from automatically converting my Trac based issue system to Gitea.
It requires manual intervention for every attachment.

**Comment by noerw** [comment] 2021-05-30 14:03
duplicate of #3690; #14601 will implement the missing API routes.
also related, but a different story: #14705

**Closed as completed by noerw** 2021-05-30 14:03 UTC
Labels: issue/duplicate
