### ISSUE TITLE
//feature request\\ learn gitlab ui and functions

### ISSUE THREAD

**Issue by sysdl132** [go-gitea/gitea#11299] opened 2020-05-05 05:17 UTC
Nothing

**Comment by TsakiDev** [comment] 2020-05-05 21:26
I mean what's the point Gitea imitates Github UI which is satisfying to many users that know it. Why would it have to change? And, why is Gitlab UI better that Gitea or Github?! It's simply different, but, which one is better, is subjective for each individual.

I don't disagree with the CI/CD idea but it's a really big feature, like building another platform on top. Plus it will inevitably make Gitea heavier, when running builds. Also what about ARM? ARM won't be able to have CI capabilities. Also, if I hosted a CI platform I would want it to be in a separate container at least.

**Comment by Adrien-Luxey** [comment] 2020-05-06 10:36
I disagree with "update project gui"! I love Gitea's simplicity. It's eye-candy in its own way :)

I do like showing projects on the front-page though. It's always nice to have some UI feedback, thanks for posting.

**Comment by sapk** [comment] 2020-05-06 11:20
The default front page is already a setting (LANDING_PAGE). If you want to display repositories you can use that option to display the explore page.

**Comment by techknowlogick** [comment] 2020-05-06 16:50
Closing as a dupe of #5937

A couple of notes about above: We do have oauth login capabilities with many other platforms including the ones you've listed above. Also in terms of CI, we integrate with many different CI providers already, and if you are looking for one like Gitlab CI, then Drone offers a similar experience and can translate existing gitlabci yaml files (perhaps others do too, but I'm listing drone here as it is the CI that I am most familiar with).

For future suggestions I recommend being more detailed instead of just "Update project GUI" and providing a screenshot of gitlab, concrete & actionable steps are preferred as then everyone is on same page with what completion of ticket is.

**Closed as completed by techknowlogick** 2020-05-06 16:50 UTC
Labels: issue/duplicate
