### ISSUE TITLE
Two Factor not working after Account is linked with a Oauth2 login

### ISSUE THREAD

**Issue by pree** [go-gitea/gitea#3970] opened 2018-05-15 19:57 UTC
- Gitea version (or commit ref): 1.1.0+1201-g0b718e0d
- Git version: 
- Operating system: Debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
I had two factor authentication enabled on my account. Added a Oauth2 provider and linked my Oauth2 account with my gitea user. After the account was linked the two factor authentication does not work anymore. Even if I log in with Username/Password.
...

## Screenshots

![image](https://user-images.githubusercontent.com/9799276/40080353-f5f4bd08-588a-11e8-934d-58d11b0b1374.png)

**Comment by daviian** [comment] 2018-05-15 20:43
@pree It's hard to diagnose the issue without further information. Can you please provide the log entries from that moment?

**Comment by pree** [comment] 2018-05-24 15:07
Hello daviian.
I will take a look at my logs later today to see if anything is reported there.

If you wan't to reproduce this, you could do this with the following steps:
* Create User
* Enable 2FA
* Add an OAuth2 (OIC) Connection
* Log into git via OAuth2
* Merge the Accounts

After the merge the login isn't possible with this user.

**Comment by techknowlogick** [comment] 2018-06-28 00:29
Closed as dupe of #1509. Please re-open if you think it is different.

**Closed as completed by techknowlogick** 2018-06-28 00:29 UTC
Labels: type/bug, issue/duplicate
