### ISSUE TITLE
Unauthenticated request to company's projects board shows 404 instead of login page

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#25720] opened 2023-07-06 06:14 UTC
### Description

For private instances of Gitea, ie. where https://GITEA/explore/repos redirects to the login page rather than allowing users to display any content anonymously, I expect all unauthenticated requests to be redirected to the login page.

This for example works fine for following URLs:
![image](https://github.com/go-gitea/gitea/assets/2737900/96ae9731-302f-4d7f-a73b-9ac56c7f9a30)
1. https://GITEA/MyCompany
2. https://GITEA/org/MyCompany/members
3. https://GITEA/org/MyCompany/teams

But when try to access the projects URL https://GITEA/MyCompany/-/projects I'll see a 404 error page.

I am aware that that page reads "The page you are trying to reach either does not exist or you are not authorized to view it." and that you could argue that it is correct, but given that the other URLs behave differently, this behaviour is inconsistent and should thus be considered a bug.

BTW, this problem cannot be reproduced via https://try.gitea.io/ since it allows anonymous access.

### Gitea Version

1.19.3

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

downloaded version

### Database

None

**Comment by sh7dm** [comment] 2023-07-06 08:47
It might be an expected behavior to prevent probing for names present. If it redirected access to private repository, it'd be possible to determine if a private repository does exist or not.

**Comment by lafriks** [comment] 2023-07-20 22:46
Yes this looks like a bug, for private instances all pages should redirect to login

**Comment by LukeOwlclaw** [comment] 2023-07-27 06:35
Fixed with version 1.20.0

**Closed as completed by LukeOwlclaw** 2023-07-27 06:35 UTC
Labels: type/bug
