### ISSUE TITLE
Issue history details

### ISSUE THREAD

**Issue by gayprogrammer** [go-gitea/gitea#1894] opened 2017-06-06 22:29 UTC
- Gitea version (or commit ref): 1.1.1+2-g2854c8a
- Git version: 2.12.2
- Operating system: Windows Server 2012
- Database (use `[x]`):
  - [x] MSSQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Not relevant
- Log gist: Not relevant

I would like if details could be less obtrusive in the issues interface. This would be very similar to the way GitHub displays adding issues in one line, instead of one line for every label. 

This:
```
User added the kind/build kind/testing status/wip labels 2 weeks ago
```
Instead of this:
```
User added the kind/build label 2 weeks ago
User added the kind/testing label 2 weeks ago
User added the status/wip label 2 weeks ago
```

**Comment by lunny** [comment] 2017-06-07 01:23
I remember there is already an issue to describe it.

**Comment by andreynering** [comment] 2017-06-07 17:44
Closing as duplicate of https://github.com/go-gitea/gitea/issues/834

**Closed as completed by andreynering** 2017-06-07 17:44 UTC
Labels: issue/duplicate
