### ISSUE TITLE
When pushing, pre-commit hook fails when using LETS_ENCRYPT

### ISSUE THREAD

**Issue by jryan128** [go-gitea/gitea#5610] opened 2018-12-30 16:32 UTC
- Gitea version (or commit ref): 1.6.2
- Git version: 2.11.0
- Operating system: Debian 9.6 (stretch)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:
https://gist.github.com/jryan128/83b1678715c51ae7ec8fe0bcb7322728
- Config gist:
https://gist.github.com/jryan128/732ae49844b03a9ddb46dbb7749e8ce8
## Description
Push to repo is failing with lets_encrypt enabled.

1. Setup new gitea 1.6.2 instance following instructions
2. Add lets_encrypt to config
3. Create new repo
4. Try to push to repo
5. Push preRecieveHook fails with error
`retrieve protected branches information failed: Get https://localhost:443/api/internal/branch/1/master: remote error: tls: internal error`

If you set `LOCAL_ROOT_URL` to the domain name like so, `https://git.example.com:443/` it fixes the issue.

I imagine there should be some better default behavior here. Like if SSL enabled to use the real domain name instead?

Thanks!

**Comment by techknowlogick** [comment] 2018-12-30 19:37
Closing as dupe of #5540

Thank you for reporting the issue :)

**Closed as completed by techknowlogick** 2018-12-30 19:37 UTC
Labels: issue/duplicate
