### ISSUE TITLE
No clone options in private repo

### ISSUE THREAD

**Issue by rugk** [go-gitea/gitea#1955] opened 2017-06-12 19:55 UTC
In a private repo, only I as the creator, can see the clone URL/ZIP download/etc. Another user, who has read access, cannot see these buttons, but can still clone the repo and download the ZIP, etc.

Is this intentionally?

**Comment by lunny** [comment] 2017-06-13 02:39
any screenshot?

**Comment by rugk** [comment] 2017-06-13 18:44
Sure, basically here you can see the missing elements:
![noicons](https://user-images.githubusercontent.com/11966684/27098792-15f7804c-5079-11e7-89d8-6cca29e1de64.jpg)

When accessing the same repo with the creator account, the buttons are shown.

**Comment by ethantkoenig** [comment] 2017-06-14 13:06
I can't reproduce, neither locally nor at https://try.gitea.io

![image](https://user-images.githubusercontent.com/8990880/27133603-bbcbc5d4-50e0-11e7-9631-1ed225ddb09e.png)

What version of gitea are you running?

**Comment by rugk** [comment] 2017-06-14 14:04
An older one. Could you invite me to the repo at try.gittea?

**Comment by ethantkoenig** [comment] 2017-06-14 14:09
@rugk Do you have an account? There doesn't seem to be a user with username "rugk" on https://try.gitea.io

**Comment by rugk** [comment] 2017-06-14 15:34
Okay, I'll create one.

**Comment by rugk** [comment] 2017-06-14 20:31
done. I'll upgrade my Gitea version soon and try to reproduce this issue.

**Comment by lunny** [comment] 2017-09-22 06:37
@rugk could you reproduce it again?

**Comment by rugk** [comment] 2017-09-22 11:54
I am currently having bigger issues (https://github.com/go-gitea/gitea/issues/2308), but I am working on it.

**Comment by ethantkoenig** [comment] 2017-12-10 02:40
I still cannot reproduce, it's probably safe to close this bug.

**Comment by lunny** [comment] 2017-12-10 03:19
@rugk  Please feel free to reopen it.

**Closed as completed by lunny** 2017-12-10 03:19 UTC
Labels: type/bug
