### ISSUE TITLE
Problema migrating from gogs to gitea

### ISSUE THREAD

**Issue by kleper** [go-gitea/gitea#4457] opened 2018-07-17 21:05 UTC
- Gitea version (or commit ref): 1.4.3
- Git version: 2.18.0
- Operating system: Linux Debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X ] No
  - [ ] Not relevant
- Log gist:

## Description
I recently decided to migrate from GOGS to GITEA. Following the documentation I managed to look at the gogs database to my new server with gitea using version 1 of gitea for migration. Migrate all files as specified by the configuration but I have the following problem:
In the repositories I had in GOGS I can not push, when I try the following error:
emote: *** Project description file has not been set
remote: error: hook declined to update refs / heads / master
To https://code.tupale.co/kleper/milfskleper.git
 ! [remote rejected] master -> master (hook declined)
error: fail push to some refereces to 'https: // ....

In the log I have these types of messages:
= git-upload-pack 401 Unauthorized in 1.566429ms

In the log: log / hooks / pre-receive.log, I have these messages:
GetProtectedBranchBy: http://10.10.10.3:3000/api/internal/branch/30/master

As I saw in other issues update the reference to the hooks using the web interface, also organize several configurations related to the URL and the LOCAL HOST, but I still have this problem.

If I create a new repository I do not have any problems and I can do push and everything works fine.

**Comment by lafriks** [comment] 2018-07-17 21:07
Duplicate of #1794

**Closed as completed** 2018-07-17 21:46 UTC
Labels: issue/duplicate
