### ISSUE TITLE
error

### ISSUE THREAD

**Issue by qxa792** [go-gitea/gitea#29883] opened 2024-03-18 10:27 UTC
### Description

![image](https://github.com/go-gitea/gitea/assets/53459088/6c4e96a9-e310-43d3-bdd7-7748fcfa046d)

### Gitea Version

1.21.8

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker

### Database

None

**Comment by wxiaoguang** [comment] 2024-03-18 10:40
Sorry for the inconvenience.

* Known Issues
    * Browsing "packages" pages might cause 500 error, it could be fixed by updating to pre-1.21.9:
        * Docker image: use `gitea/gitea:1.21-nightly` and `gitea/gitea:1.21-nightly-rootless`
        * Binary: download from https://dl.gitea.com/gitea/1.21/

**Comment by silverwind** [comment] 2024-03-18 13:13
Duplicate of https://github.com/go-gitea/gitea/issues/29773. Use nightly or wait for release.

**Closed as not planned by silverwind** 2024-03-18 13:13 UTC
Labels: type/bug, issue/needs-feedback

**Comment by qxa792** [comment] 2024-03-19 01:27
thanks
