### ISSUE TITLE
Gitea Web frontend broken since ~2 weeks

### ISSUE THREAD

**Issue by gsantner** [go-gitea/gitea#9362] opened 2019-12-15 11:29 UTC
- Gitea version (or commit ref): ba1acf5b5
- Git version: 2.17.1
- Operating system: U18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
Since about beginning of december the web frontend of Gitea seems to be completely broken.
I can login but  nearly cannnot click  anything and most stuff doesn't render.
Additionally from browser log I see that some css/js files are served as html which sould be also relevant.

I'm using the builds from <https://dl.gitea.io/gitea/master/gitea-master-linux-amd64> since long time and had never such problems.. I have a older version of gitea locally (2019-11-28) where everything works still works as it should,  so it's no webserver issue. But seems like all newer builds are broken due some recent changes.

See screenshots:

## Screenshots
![Screenshot_20191215-121715](https://user-images.githubusercontent.com/6735650/70861997-091be080-1f2e-11ea-8945-9daa368b63c5.png)
![Screenshot_20191215-121734](https://user-images.githubusercontent.com/6735650/70861998-0b7e3a80-1f2e-11ea-822b-cb7dd367095d.png)
![Screenshot_20191215-121812](https://user-images.githubusercontent.com/6735650/70861999-0d47fe00-1f2e-11ea-83e9-832a7d97818b.png)

**Comment by silverwind** [comment] 2019-12-15 12:18
Duplicate of https://github.com/go-gitea/gitea/issues/9324

**Closed as completed** 2019-12-15 15:52 UTC
Labels: issue/duplicate
