### ISSUE TITLE
The WYSIWYG editor and preview do not work in Wiki

### ISSUE THREAD

**Issue by SlavekB** [go-gitea/gitea#14196] opened 2020-12-30 15:50 UTC
- Gitea version (or commit ref): 1.13.1
- Git version: 2.20.1
- Operating system: Debian 10.x (Buster)
- Installed: downloaded official binary
  
- Started: as systemd service
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes – wiki of any project
  - [ ] No

## Description

When creating a new wiki page and opening an existing wiki page for editing, the WYSIWYG editor toolbar is not displayed there. At the same time, the preview does nothing at all.

This seems similar to issue #12971 except that the WYSIWYG editor is not displayed at all, so there is no need to switch to textarea – it doesn't work from the beginning.

**Comment by zeripath** [comment] 2020-12-30 16:09
I just tried this on try.gitea.io with Google Chrome | 87.0.4280.88 (Official Build) (64-bit) on ubuntu focal and it worked perfectly.

**Comment by zeripath** [comment] 2020-12-30 16:10
what browser are you using? if you look at the development console do you get errors etc?

**Comment by SlavekB** [comment] 2020-12-30 16:26
+ Palemoon 28.17
+ Firefox 68.9 (ESR)
+ Chromium 57

In Firefox, I watched the browser console, but there were no new messages.

**Comment by SlavekB** [comment] 2020-12-30 16:32
Another test performed – another browser where it doesn't work:
+ Firefox 78.6 (ESR)

**Comment by zeripath** [comment] 2020-12-30 17:19
It is working on firefox 84 here

**Comment by zeripath** [comment] 2020-12-30 17:20
Is it possible you have cached assets?

**Comment by SlavekB** [comment] 2020-12-30 17:26
If you mean in the browser, then I do not normally use Firefox or Chromium on my machine == these have not been running for a long time. The same goes for Firefox 78.6 on a Windows test machine. Furthermore, I only rarely go to `try.gitea.io`, so it doesn't seem possible that I have any old content cached there either.

**Comment by zeripath** [comment] 2020-12-30 17:33
have you logged in? are you certain that there no console errors? Without having a clear way to reproduce or some errors to work with we're a bit stuck.

**Comment by zeripath** [comment] 2020-12-30 17:35
Have you tried CTRL-F5? To forciblyreload in case you have an oldcached ServiceWorker

**Comment by SlavekB** [comment] 2020-12-30 18:07
Another attempt – another machine where I never accessed any Gitea instance, this time Firefox 84. I assume that using a newer Firefox could be a change in that try.gitea.io works:
![snimek82](https://user-images.githubusercontent.com/9537053/103372250-c8a7ea00-4ad1-11eb-961c-c6b52c68a157.png)

But Gitea 1.13.1 still has the same problem:
![snimek83](https://user-images.githubusercontent.com/9537053/103372273-dbbaba00-4ad1-11eb-9393-833d86d3cabb.png)

You can see an open Firefox console window in the screenshot. There is no new record at all.

**Comment by micheleCTDE** [comment] 2020-12-31 06:48
Same issue on my machine. Firefox ESR 78.6 on Debian testing.

**Comment by vanous** [comment] 2021-01-02 19:50
Same issue here, both Firefox 84.0 (64-bit) and Chromium Version 87.0.4280.88 (Developer Build) built on Debian bullseye/sid, running on Debian bullseye/sid (64-bit), happening on [Codeberg](https://codeberg.org/).

**Comment by mibuthu** [comment] 2021-01-04 07:55
I have the same problem: Gitea 1.13.1 installed via Docker, tried with multiple browsers (e.g. Firefox 84, Brave 1.18, Opera 73).

**Comment by gytisrepecka** [comment] 2021-01-04 08:30
Did you try to clear Firefox cache?

After upgrading Gitea to version 1.13.1 I had visual editor and preview gone. Perhaps some static files were cached from previous version as clearing browser cache brought editor and preview back.

**Comment by SlavekB** [comment] 2021-01-04 08:47
As I wrote above: I used browsers that I have not used for a long time => they did not have a chance to have such data in the cache, none worked. I used latest Firefox on another virtual machine, where there had never been access to any Gitea instance before => had no chance to have such data in the cache, it worked on try.gitea.io (i.e. 1.14.0-devel), but it didn't work on our 1.13.1.

**Comment by BLumia** [comment] 2021-01-05 09:36
I also have this issue on my selfhosted gitea `1.13.1` instance, either switch back to `1.13.0` or the try.gitea.io instance (with version `1.14.0+dev-506-g126c9331d`) doesn't have this issue. Use `1.13.1` with a clean installed firefox also wont fix this issue.

I found there was a commit between `1.13.0` and `1.13.1` that most likely related to this issue, which will try not use simpleMDE editor on mobile devices for 1.13 (4f296f7436e35af0b72c03e01b6cca46266052c8). simply revert that commit seems fixes this issue (at least on my machine).

Let me know if you need any other information.

**Comment by lunny** [comment] 2021-01-05 09:45
I can confirm this is a bug and should be fixed on v1.13.2

**Comment by miklobit** [comment] 2021-01-09 00:22
> I have the same problem: Gitea 1.13.1 installed via Docker, tried with multiple browsers (e.g. Firefox 84, Brave 1.18, Opera 73).
> I also cannot see any error in the browser console.

Same with me. installed with docker image gitea/gitea:1.13.1

**Comment by ojn** [comment] 2021-01-20 23:59
Same, on Gitea 1.13.1 using Firefox 84.0.2 and Chromium 87.0

**Comment by trepmag** [comment] 2021-01-25 13:57
Do someone have a quick turn around for 1.13.1 docker until 1.13.2?

**Comment by lunny** [comment] 2021-01-25 15:25
I think we can just remove the preview tab because there is already a preview button on the toobar.

**Comment by jpraet** [comment] 2021-01-28 22:13
I think the issue is here: https://github.com/go-gitea/gitea/blob/release/v1.13/web_src/js/index.js#L1362

should be `isMobile()`

**Closed as completed** 2021-01-29 14:37 UTC
Labels: type/bug, outdated/theme/markdown
