### ISSUE TITLE
500 error on generating CSV diffs

### ISSUE THREAD

**Issue by melmus** [go-gitea/gitea#16921] opened 2021-09-02 14:51 UTC
- Gitea version (or commit ref):  v1.15.0
- Git version: 2.30.2
- Operating system: Ubuntu 18.04.4 LTS
   Gitea running in docker
  
  
  
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

When i create PR in repository, i have 500 error. If i created another branch, and created PR in master branch, everything is fine, but if i see file changed, i have 500 error. This  problem i see on one repository.

```
2021/09/02 12:09:00 ...s/context/context.go:195:HTML() [E] Render failed: template: repo/diff/csv_diff:15:21: executing "repo/diff/csv_diff" at <$cell.Type>: nil pointer evaluating *gitdiff.TableDiffCell.Type

```

**Comment by zeripath** [comment] 2021-09-02 18:47
It would be helpful if you could upload an example CSV to try.gitea.io.

I think:

```patch
diff --git a/templates/repo/diff/csv_diff.tmpl b/templates/repo/diff/csv_diff.tmpl
index b86e9d2a7..b037e29b8 100644
--- a/templates/repo/diff/csv_diff.tmpl
+++ b/templates/repo/diff/csv_diff.tmpl
@@ -12,7 +12,9 @@
 						{{if and (eq $i 0) (eq $j 0)}}
 							<th class="line-num">{{.RowIdx}}</th>
 							{{range $j, $cell := $row.Cells}}
-								{{if eq $cell.Type 2}}
+								{{if not $cell}}
+									<th></th>
+								{{else if eq $cell.Type 2}}
 									<th class="modified"><span class="removed-code">{{.LeftCell}}</span> <span class="added-code">{{.RightCell}}</span></th>
 								{{else if eq $cell.Type 3}}
 									<th class="added"><span class="added-code">{{.LeftCell}}</span></th>
@@ -25,7 +27,9 @@
 						{{else}}
 							<td class="line-num">{{if .RowIdx}}{{.RowIdx}}{{end}}</td>
 							{{range $j, $cell := $row.Cells}}
-								{{if eq $cell.Type 2}}
+								{{if if not $cell}}
+									<td></td>
+								{{else eq $cell.Type 2}}
 									<td class="modified"><span class="removed-code">{{.LeftCell}}</span> <span class="added-code">{{.RightCell}}</span></td>
 								{{else if eq $cell.Type 3}}
 									<td class="added"><span class="added-code">{{.LeftCell}}</span></td>
```

Would stop the panic but I'm not sure if there is a deeper bug here.

**Comment by zeripath** [comment] 2021-09-04 17:13
Duplicate of #16837

**Closed as completed by zeripath** 2021-09-04 17:13 UTC
Labels: type/bug, issue/duplicate
