### ISSUE TITLE
Gitea 1.6.0 Crash

### ISSUE THREAD

**Issue by gsiz007** [go-gitea/gitea#5406] opened 2018-11-26 11:32 UTC
- Gitea version (or commit ref): 1.6.0.
- Git version: 2.19.1
- Operating system: CentOS 7, x86_64
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
After upgrade from Gitea 1.6.0rc2 to Gitea 1.6.0 program crash. Binary are directly from Github and as a config file you can use https://github.com/go-gitea/gitea/blob/master/custom/conf/app.ini.sample

Gitea 1.6.0rc2
[gitea@git ~]$ /var/lib/gitea/gitea.old web --config /etc/gitea/gitea.ini
2018/11/26 06:41:16 [T] AppPath: /var/lib/gitea/gitea.old
2018/11/26 06:41:16 [T] AppWorkPath: /var/lib/gitea
2018/11/26 06:41:16 [T] Custom path: /var/lib/gitea/custom
2018/11/26 06:41:16 [T] Log path: /var/lib/gitea/log
2018/11/26 06:41:17 Serving 127.0.0.1:3000 with pid 3103

Gitea 1.6.0

[gitea@git ~]$ /var/lib/gitea/gitea web --config /etc/gitea/gitea.ini
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x7f09a4]

goroutine 1 [running]:
code.gitea.io/gitea/vendor/gopkg.in/ini%2ev1.(*Key).transformValue(0xc000561740, 0xc00052fec1, 0x28, 0xc0004dae08, 0x4aa8a9)
        /go/src/code.gitea.io/gitea/vendor/gopkg.in/ini.v1/key.go:123 +0xa4
code.gitea.io/gitea/vendor/gopkg.in/ini%2ev1.(*Key).String(0xc000561740, 0xc000555a20, 0x15)
        /go/src/code.gitea.io/gitea/vendor/gopkg.in/ini.v1/key.go:130 +0x3d
code.gitea.io/gitea/vendor/gopkg.in/ini%2ev1.(*Key).MustString(0xc000561740, 0xc000555a20, 0x15, 0x1, 0xc000555a20)
        /go/src/code.gitea.io/gitea/vendor/gopkg.in/ini.v1/key.go:202 +0x2f
code.gitea.io/gitea/modules/setting.NewContext()
        /go/src/code.gitea.io/gitea/modules/setting/setting.go:1194 +0x489f
code.gitea.io/gitea/routers.GlobalInit()
        /go/src/code.gitea.io/gitea/routers/init.go:47 +0x4a
code.gitea.io/gitea/cmd.runWeb(0xc0002fea00, 0x0, 0x0)
        /go/src/code.gitea.io/gitea/cmd/web.go:112 +0xaa
code.gitea.io/gitea/vendor/github.com/urfave/cli.HandleAction(0x13d6ee0, 0x15dc398, 0xc0002fea00, 0xc00007b100, 0x0)
        /go/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/app.go:471 +0xad
code.gitea.io/gitea/vendor/github.com/urfave/cli.Command.Run(0x1567c87, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x158deed, 0x16, 0x0, ...)
        /go/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/command.go:191 +0x96d
code.gitea.io/gitea/vendor/github.com/urfave/cli.(*App).Run(0xc000288ea0, 0xc0000300c0, 0x4, 0x4, 0x0, 0x0)
        /go/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/app.go:241 +0x5a2
main.main()
        /go/src/code.gitea.io/gitea/main.go:53 +0x3d1

**Comment by lafriks** [comment] 2018-11-26 15:13
This is upstream problem. Duplicate of #4692

**Closed as completed** 2018-12-02 16:14 UTC
Labels: issue/duplicate
