### ISSUE TITLE
Can't add user to a specific repo or team

### ISSUE THREAD

**Issue by thibaultmeyer** [go-gitea/gitea#361] opened 2016-12-07 10:05 UTC
When we try to assign user to a specific project or a team, we get the error `user does not exist.`.

![image](https://cloud.githubusercontent.com/assets/1005086/20963237/e9e676fc-bc6c-11e6-8314-b54c25e98e5a.png)

**Comment by Bwko** [comment] 2016-12-07 11:02
This is caused by commit 55bd3edb90285fe5983229defcaec7b49f94b980
It is caused by:

```
 -	UserName  string `json:"username"`
 +	UserName  string `json:"login"`
```

**Comment by lunny** [comment] 2016-12-07 15:19
This have been resolved by #362

**Closed as completed by lunny** 2016-12-07 15:19 UTC
Labels: type/bug
