### ISSUE TITLE
Commit message description not hidden in commit reference links

### ISSUE THREAD

**Issue by raucao** [go-gitea/gitea#5867] opened 2019-01-27 08:32 UTC
- Gitea version (or commit ref): 1.7.0

## Description

When referencing an issue from a commit, the commit message that is rendered in the issue should only show the title (first line) by default, same as in other places, like e.g. the PR commit list.

### Issue view

Description is added directly after title, and unformatted:

![screenshot from 2019-01-27 16-29-32](https://user-images.githubusercontent.com/842/51798651-f2ef2e00-2250-11e9-9c5f-13fd1a893c3f.png)

### PR commit index

The correct rendering:

![screenshot from 2019-01-27 16-30-01](https://user-images.githubusercontent.com/842/51798661-1023fc80-2251-11e9-936b-bcf1b437e19d.png)

**Comment by petercolberg** [comment] 2019-02-01 20:54
Since `Comment` conveniently includes the commit hash in the `CommitSHA` field, what do you think of reusing `RenderCommitMessage` and optionally `RenderCommitBody` similar to the following? https://github.com/go-gitea/gitea/blob/756eafaaf68b3cadb3f33f37554a6aa2d83921ef/templates/repo/commits_table.tmpl#L66-L73 (The `Content` field would contain the empty string instead of the current prerendered message.)

**Comment by lunny** [comment] 2019-02-06 06:39
@petercolberg could you send a PR to fix that?

**Comment by adelowo** [comment] 2019-02-07 23:04
Duplicate of https://github.com/go-gitea/gitea/issues/3626

**Closed as completed** 2019-02-08 11:13 UTC
Labels: issue/duplicate, type/enhancement, topic/ui
