### ISSUE TITLE
[feature request] Git only token

### ISSUE THREAD

**Issue by tuxmaster5000** [go-gitea/gitea#15052] opened 2021-03-19 18:41 UTC
On bitbucket I can set an token, which are only valid for read/write to the repo, but no admin rights for it.
But on gitea I can only set an token which have the full rights of my account.

**Comment by techknowlogick** [comment] 2021-03-19 21:25
closing as dupe of https://github.com/go-gitea/gitea/issues/4300

**Closed as completed by techknowlogick** 2021-03-19 21:25 UTC
Labels: issue/duplicate
