### ISSUE TITLE
ORM issue upgrading from 1.13.7 to 1.14.3 on error 500 repo

### ISSUE THREAD

**Issue by Jack64** [go-gitea/gitea#16267] opened 2021-06-27 10:51 UTC
- Gitea version (or commit ref): 1.14.0
- Git version: 2.30.2
- Operating system: linux (docker)
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist: https://pastebin.com/ZPdByCge

## Description

When trying to upgrade from 1.13.7 to 1.14.0, I get an ORM initialization error as shown in the logs above. It is unclear which repository is causing this, please help.
EDIT: added log line below to help others facing this problem find this issue
```bash
ORM engine initialization attempt #3/10 failed. Error: migrate: do migrate: GetTagCommit: exit status 128 - fatal: not a git repository (or any parent up to mount point /)
```

**Comment by zeripath** [comment] 2021-06-27 13:02
Please try 1.14.3 - it will at least give you more information even if it continues to fail.

In general once a point release is release just use the latest point release - never use the lower point releases unless absolutely necessary.

**Comment by zeripath** [comment] 2021-06-27 13:08
I just don't understand why you would ever not just use the latest point release? How can we improve our documentation so people don't do this?

I'm serious here - we fix a large number of bugs in between point releases - sometimes with migrations - sometimes bugs that would cause data loss. If you use the lowest point release instead of jumping to the latest point release you're exposing yourself to already fixed bugs and wasting our time responding to bug reports that are duplicates.

**Comment by Jack64** [comment] 2021-06-27 13:17
@zeripath I wasn't actually planning on staying at 1.14.0. I moved from 1.13.1 to 1.13.7 prior to upgrading to 1.14.0, assuming this would improve my chances of a successful minor release upgrade. If I understand correctly, you are recommending that if someone is at 1.X.<latest-patch> they should upgrade directly to 1.Y.<latest-patch> ?

In any case, this produces the same result, curiously on a mirror of gitea itself:
```
2021/06/27 13:15:33 ...s/migrations/v156.go:89:fixPublisherIDforTagReleases() [I] [SQL] SELECT "id", "owner_id", "owner_name", "name" FROM "repository" WHERE "id"=$1 LIMIT 1 [151] - 1.221616ms
2021/06/27 13:15:33 ...s/migrations/v156.go:125:fixPublisherIDforTagReleases() [E] Error whilst getting commit for Tag: v0.11rc in [151]mirrors/gitea. Error: exit status 128 - fatal: not a git repository (or any parent up to mount point /)
        Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

2021/06/27 13:15:33 ...ations/migrations.go:397:Migrate() [I] [SQL] ROLLBACK [] - 605.608µs
2021/06/27 13:15:33 routers/init.go:81:initDBEngine() [E] ORM engine initialization attempt #8/10 failed. Error: migrate: do migrate: GetTagCommit: exit status 128 - fatal: not a git repository (or any parent up to mount point /)
        Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

**Comment by Jack64** [comment] 2021-06-27 13:19
Do you have any suggestions for a next step? I can always remove the mirror while on 1.13.7 and try again, but what if this happens on a repo I can't remove?

**Comment by zeripath** [comment] 2021-06-27 13:32
Yes always go from latest point release to latest point release.

Anyway this is a duplicate issue. The error message on 1.14.3 is different if you read the logs:

```
...s/migrations/v156.go:125:fixPublisherIDforTagReleases() [E] Error whilst getting commit for Tag: v0.11rc in [151]mirrors/gitea. Error: exit status 128 - fatal: not a git repository (or any parent up to mount point /)
        Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

The migration can't find the repository in the place it is looking for. That is likely because your `[repository]` `ROOT` is incorrect - likely you left it unset in your app.ini but unfortunately we had to change this default location because of snap.

The breaking notes for 1.14 state:

```
 The default location for repository data ([repository] ROOT) will now be in a subdirectory of the APP_DATA_PATH path. (#13991)
```

Likely all you have to do is set `[repository]` `ROOT` correctly or move them to the new location.
See: #16217 and #16210

**Comment by Jack64** [comment] 2021-06-27 13:46
OK in the future I'll remember to upgrade minor versions from latest point release to latest point release.

I have the [repository] ROOT set in the app.ini but it fails regardless. I have no other keys set under [repository] and I don't have [server] APP_DATA_PATH defined.

I'm using "/data/git/gitea-repositories" as [repository]ROOT, from what I gathered from the other issues I need to move it to something like "/data/gitea/git/gitea-repositories" and also set [server]APP_DATA_PATH = /data/gitea so that [repository]ROOT becomes a subdirectory of APP_DATA_PATH. Is this correct?

**Comment by zeripath** [comment] 2021-06-27 13:48
What command are you running? Are you running that command in the same environment as you would normally run Gitea and with the same arguments?

**Comment by Jack64** [comment] 2021-06-27 13:53
Yes, nothing has changed in that regard. I'm simply running the Docker container pointing to the app.ini I'm mounting in there.

The thing is, I have a terraform module that I use to run gitea which allows automatic periodic backups and restores from a minio / S3 bucket so since I was moving it from one Kubernetes cluster to another, it ran in migration mode and had to pull all the data from the S3 to put it in the correct folder (i.e. [repository]ROOT). This has worked flawlessly since (IIRC) 1.11 . If [repository]ROOT now must be a subdir of APP_DATA_PATH (which I have not set), I have to change the backup/restore scripts to adjust to this change.

**Comment by zeripath** [comment] 2021-06-27 13:56
it doesn't have to be - you can set it anywhere.

If you're absolutely certain that you have `[repository]` `ROOT` set and that you're reading in the config correctly - then the problem is going to be that the repository this migration is looking for simply doesn't exist.

So ... are you sure that `$ROOT/mirrors/gitea.git` is a bare git repository ?

**Comment by zeripath** [comment] 2021-06-27 14:00
> I have the `[repository]` `ROOT` set in the `app.ini` but it fails regardless. I have no other keys set under `[repository]` and I don't have `[server]` `APP_DATA_PATH` defined.
>
> I'm using `"/data/git/gitea-repositories"` as `[repository]` `ROOT`, from what I gathered from the other issues I need to move it to something like `"/data/gitea/git/gitea-repositories"` and also set `[server]` `APP_DATA_PATH = /data/gitea` so that `[repository]` `ROOT` becomes a subdirectory of `APP_DATA_PATH`. Is this correct?

No. So long as you have set the ROOT to an absolute path the APP_DATA_PATH is irrelevant regarding this.

**Comment by Jack64** [comment] 2021-06-27 14:01
Good hint. It shows in the repo search but then it throws a 500 error when I try to access it (on 1.13.7).
![image](https://user-images.githubusercontent.com/11641285/123547291-15eed680-d758-11eb-8397-f1c086147845.png)

I don't see any error logs anywhere to explain this 500 error.

**Comment by zeripath** [comment] 2021-06-27 14:03
Likely it's not there and you just need to remove it from the db. Probably there was a migration failure at some point. 1.14.x won't do that. 

you might be able to get to `http://gitea/mirors/gitea/settings` and delete the repository that way if you don't know how to remove it directly from the db.

**Comment by Jack64** [comment] 2021-06-27 14:06
Yes that's likely. Unfortunately /settings throws an error as well. I guess all that's left is removing it from the DB directly, do you by any chance have the SQL command at hand ? I see that I have other repos in this situation so I'll have to do it more than once ..

**Comment by zeripath** [comment] 2021-06-27 14:20
`DELETE FROM repository WHERE owner_name = 'mirrors' AND name = 'gitea'`

**Comment by zeripath** [comment] 2021-06-27 14:22
normally we'd just have the migrations delete these sort of things but as the ROOT location can be wrong it's not really the right thing to do in this case.

**Comment by zeripath** [comment] 2021-06-27 14:23
An alternate option is to just do a `git init --bare owner/repo.git` in your `$ROOT` as that should allow stop the 500.

**Comment by Jack64** [comment] 2021-06-27 14:27
> normally we'd just have the migrations delete these sort of things but as the ROOT location can be wrong it's not really the right thing to do in this case.

Yes I realized that might be why it's not "auto-fixed". Would be nice to have somewhere in the UI (administration section maybe?) where we could do this without having to jump into the SQL.

The DELETE command worked flawlessly, thank you very much. I'll re-run the migration now and delete any other repos in this situation.

**Comment by Jack64** [comment] 2021-06-27 14:32
Boom - 1.14.3 running :+1: thanks again for your invaluable help @zeripath , this sort of incredibly fast and helpful support puts some commercial solutions to shame!! :pray: :pray:

**Comment by zeripath** [comment] 2021-06-27 14:35
> Yes I realized that might be why it's not "auto-fixed". Would be nice to have somewhere in the UI (administration section maybe?) where we could do this without having to jump into the SQL, though. But perhaps it's not that common an issue to make this a priority.

Trouble is to get to any fixed UI would require you to pass the migration step first... 

The other issue is that the loss of a repo should cause a 500 - it is an internal server error. I'm not sure I really want these to be tolerated. Something has gone drastically wrong if the git repo has disappeared - but yeah it's not great that then you're stuck in a broken db situation even if the rest of the situation is resolvable.

**Comment by zeripath** [comment] 2021-06-27 14:41
I'll close this and think a bit more about the 500 issue.

**Closed as completed by zeripath** 2021-06-27 14:41 UTC
Labels: issue/duplicate, type/question

**Comment by Jack64** [comment] 2021-06-27 14:42
> Trouble is to get to any fixed UI would require you to pass the migration step first...

The common solution for this is simply rolling-back to the last working version (in my case 1.13.7). After that, I would be able to go to the Administration panel and see that there is an "errored repo". If I had a list of such repos there, I could manually decide which ones could be safely deleted (pressing a button that ran this DELETE SQL command on the back-end) or leave it alone in order to restore the data, depending on which case it were.

At least that's how I imagined this would work. By putting this on the Administration tab and not on the repo settings it'd bypass the 500 error.

> The other issue is that the loss of a repo should cause a 500 - it is an internal server error. I'm not sure I really want these to be tolerated. Something has gone drastically wrong if the git repo has disappeared - but yeah it's not great that then you're stuck in a broken db situation even if the rest of the situation is resolvable.

Fully agree here that there shouldn't be an "auto-fix", because it may use the "wrong fix" by deleting or keeping it. The point of that UI would be to point out to the admin that there are repos in this situation (fortunately for me it was only this mirror + my own fork of it) and allow them to fix it. I'm not sure if this is common enough to warrant the new UI, but if this happened by a rogue rm -rf or ransomware or something, it'd be invisible if it's not a regularly used repo (which was the case).

**Comment by Jack64** [comment] 2021-06-27 14:47
updated the title, might help anyone with this exact problem find this issue.
