### ISSUE TITLE
Switch font to Noto

### ISSUE THREAD

**Issue by xf-** [go-gitea/gitea#6937] opened 2019-05-13 21:23 UTC
Switch from Lato to Noto font.

Noto is one of the biggest fonts available and subsets should contain a lot languages (582).
Also Noto provides Noto Sans Mono (and Noto Mono)

Sponsored/maintained by Google to run applications around the world.
https://www.google.com/get/noto/

I opened a issue because i have no idea if it is worth the effort and will get merged.

**Comment by silverwind** [comment] 2019-05-14 15:45
I'm generally 👍 to this if we can cover all our supported languages with it. Better to have one unified font style across languages.

Looks like we just need to extract the woff/woff2 from these webfonts, weight 400, right?

https://fonts.google.com/specimen/Noto+Sans/
https://fonts.google.com/specimen/Noto+Sans+JP/
https://fonts.google.com/specimen/Noto+Sans+KR/
https://fonts.google.com/specimen/Noto+Sans+TC/
https://fonts.google.com/specimen/Noto+Sans+SC/

Maybe there is some tooling available to automatically build the font CSS for Noto for all languages.

**Comment by lafriks** [comment] 2019-05-14 16:39
I would also be ok with this font

**Comment by mrsdizzie** [comment] 2019-05-14 17:41
For reference these tools were helpful in showing some differences between the fonts (for certain ASCII characters anyway). 

 http://www.identifont.com/differences?first=Lato&second=Noto+Sans&q=Go
 https://tiff.herokuapp.com

**Comment by xf-** [comment] 2019-05-14 19:05
**Status**
I tested a lot yesterday and replaced the font (branch on the fork...), but providing JP KR TC and SC maybe not so easy. The fonts are really large otf 4.3 MB and woff2 3.4 MB. All other languges are included in other file like latin, Cyrillic ...
It is possible, but 2 files (Regular,(?Semi)Bold) at 6.8 MB.

**Monospaced**
Monospaced is not that interesting. Works for code, but no italic and most developers prefer standard system font for code.

**Current problem with Lato**
Lato is included in index and lato-v14 is included semantic ui as font-face.

**My favorite solution so far**
- Use Noto
- Not include remote sources for JP KR TC and SC, but define local in font-face (will be used if installed)
- Get rid of all :lang definitions and use fallback over all important fonts - System font will be used at the end
- Maybe cleanup the icon font chaos (tools like icomoon or fontastic can easily create own iconfont. No duplicates anymore). Some tools support a config file an can be generated with nodejs (extened if needed)

**Comment by silverwind** [comment] 2019-05-14 19:20
> The fonts are really large otf 4.3 MB and woff2 3.4 MB

But wouldn't browsers be smart enough to only download the font if they encounter a glyph from it (using CSS `unicode-range`)?

> Monospaced is not that interesting

Agree, I also prefer a system font stack for monospace.

>  Lato is included in index and lato-v14 is included semantic ui as font-face.

I'd have no issues using `!important` to overrule that.

> Maybe cleanup the icon font chaos

Ideally, icons should be inline SVG, icon fonts are just a dirty hack from the past for browsers without SVG support (all browsers since IE9 do).

**Comment by xf-** [comment] 2019-05-14 20:31
@silverwind yes the browser is smart enough, but 1 font file has 3.4 MB for JP SC... Like a really large Icon font. My "All Noto" download had > 1 GB font files. That means you incease download for JP or SC TH by nearly 7 MB without italic and trigger a complete repaint.

> I'd have no issues using !important to overrule that.
I would replace it in semantic ui css (first file loaded) and initially a Google Font import is in git history. Was already modified. Also use preload in header.

> Ideally, icons should be inline SVG, icon fonts are just a dirty hack from the past for browsers without SVG support (all browsers since IE9 do).
I personally like icon fonts. Better to control (position inline) compared to background-image svg, easy to change color and apply. Inline in CSS or webpage? Supixel, hinting.. options are really good in fonts. for small icons. Logos are SVGs.

**Comment by silverwind** [comment] 2019-05-14 20:59
> 1 font file has 3.4 MB for JP SC

Ugh, yes that seems quite big. Probably not a great idea to include it. Maybe @zeripath has a opinion.

> Inline in CSS or webpage

Inline in HTML of course, anything else is a hack. Some tooling will be needed so that our template code can emit SVGs and I fear some major hacks to semantic-ui might be necessary to make it works, so probably not that great of an option unless we ditch semantic.

**Comment by xf-** [comment] 2019-05-14 22:03
@silverwind you are on discord?
I prefer inline aswell for logos/larger icons, but small icons (to add some visual) are really nice with font. You can add icon in docu inline and no c&p the svg. Even with "use" imports from one svg.

**Comment by silverwind** [comment] 2019-05-14 22:56
Not on discord (yet), I'm afraid. Keep the icon fonts for now. We can probably switch to SVG icons later when we have a CSS framework that supports them (bulma does).

**Comment by zeripath** [comment] 2019-05-15 08:02
Although I like Noto, I thought if we were going to remove Lato we were going to move to a native stack? Noto might make sense as a fall through though - if that's possible without browsers downloading the fonts unnecessarily.

**Comment by xf-** [comment] 2019-05-15 10:54
@zeripath like github? i like the idea, but maybe some "bug" reports about alignment of icons.

@silverwind i never seen Bulma before and i looked into repo and syntax without braces in sass is really strange & uses hsl (+ hex + rgba) colors. Also in the hand of a single Maintainer (no Team or Organization). I normally use Bootstrap and import needed modules like Grid, maybe cards, responsive images. I prefer it, because a lot of external stuff uses the same classes or provide a bootstrap version. Of course you need to  adjust some variables.
Looks like on Bulma you should to import all modules. Bootstrap

**Comment by silverwind** [comment] 2019-05-15 15:46
Actually, I think I'd prefer a completely native stack too, especially given that we can not properly cover the asian fonts without a big load performance regression.

@xf- not sure I follow but I was refering to https://bulma.io and it was brought up in https://github.com/go-gitea/gitea/issues/5937 as a replacement for the aging semantic-ui. Bootstrap 4 might also be a a valid option for a replacement framework, actually.

**Comment by lafriks** [comment] 2019-05-15 16:13
Idea behind Bulma is to use flex for layouts that make it a lot more cleaner than bootsrtap

**Comment by silverwind** [comment] 2019-05-15 17:35
Yeah, Bulma is built around Flexbox while it's [optional](https://getbootstrap.com/docs/4.0/utilities/flex/) in Bootstrap. Not saying that Flexbox is a cure-all, but it's a step in the right direction.

**Comment by xf-** [comment] 2019-05-15 19:06
@silverwind @lafriks flexbox it isn't optional in bootstrap 4 (was in alpha (because of some issues with decimals and miscalculation in browsers - was changed/fixed), d-* selectors for changing the display value - your link was to 4.0 uptodate is 4.3) and bootstrap is lighter in my eyes and tested like nothing else.

Only grid example is in repo of bootstrap:
https://github.com/twbs/bootstrap/blob/master/scss/bootstrap-grid.scss

 You only include needed components and you can set your own variables or for example to avoid the button overhead. Include the mixin and call the mixin with wanted colors. 10% darker and other stuff are calculated by mixin.

**Comment by silverwind** [comment] 2019-05-15 19:50
I see. Well it certainly is an option. We will have to add quite a bit of custom CSS to whatever framework we choose. If Bootstrap allows to import single components, that'd probably be a great start to gradually move over. Would start by converting LESS to SCSS first and take it from there.

**Comment by xf-** [comment] 2019-05-15 20:50
Converter exists, but scss has more functions and i think shouldn't be used. Easier to generate a old css include it as well and delete part by part. set a good linter in place like and replace the lines. A lot of stuff can be done with cards/ menus provided and some adjusted variables.
This would allow for multiple merges and less problems while switching/replacing and other commits touching templates and classes.
Options like bold, uppercase should be set via class. Custom CSS should be reduced and maybe different kind of mobile menu

**Comment by xf-** [comment] 2019-05-18 11:53
About the size
**Bootstrap** master min (complete) - last commit "v5 dist"
https://github.com/twbs/bootstrap/blob/master/dist/css/bootstrap.min.css
![Screenshot_20190518_135014](https://user-images.githubusercontent.com/1295633/57969132-e6afed80-7973-11e9-9d56-308b1463db3c.png)

v4.3.1 release
![image](https://user-images.githubusercontent.com/1295633/57969157-31316a00-7974-11e9-8c51-4e536daaa203.png)


**Bulma** (min - complete)
![image](https://user-images.githubusercontent.com/1295633/57969144-0e9f5100-7974-11e9-8eac-0d204ca80e94.png)

**Comment by lafriks** [comment] 2019-05-21 15:10
About lighter I meant resulting layout html

**Comment by lunny** [comment] 2020-01-28 13:47
Since we have used roboto font, I think we could close this one.

**Closed as completed** 2020-01-28 14:47 UTC
Labels: type/proposal
