### ISSUE TITLE
Migration form 1.13.7 to 1.14.0 fails

### ISSUE THREAD

**Issue by jakubgs** [go-gitea/gitea#16217] opened 2021-06-21 09:27 UTC
- Gitea version (or commit ref): [`1.14.0`](https://hub.docker.com/layers/gitea/gitea/1.14.0/images/sha256-a491dc1f1e69bb850842aff9f2e1df733e4c919438f0e46fa840da0180c74ce4?context=explore)
- Operating system: Ubuntu 20.04.2
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist: https://gist.github.com/jakubgs/bb3bcb825c5f17d8b1b90353086feb55

## Description
I'm trying to upgrade from `1.13.7` to  `1.14.0` using the [official Docker images](https://hub.docker.com/r/gitea/gitea) and I'm getting this error (full log above in the gist):
```
...ations/migrations.go:394:Migrate() [I] Migration[156]: fix publisher ID for tag releases
routers/init.go:81:initDBEngine() [E] ORM engine initialization attempt #1/10 failed. Error: migrate: do migrate: no such file or directory
```
I have no idea what I'm supposed to do with that.

**Comment by zeripath** [comment] 2021-06-21 09:55
This is a duplicate of #16210 

This is likely due to your app.ini not having `[repository]` `ROOT` set - thus you're hitting the published breaking change in 1.14.0:

https://blog.gitea.io/2021/04/gitea-1.14.0-is-released/#breaking-changes-or-potentially-breaking :

❗ The default location for repository data ([repository] ROOT) will now be in a subdirectory of the APP_DATA_PATH path. (#13991)

Set `[repository]` `ROOT` to the required place in your app.ini.

**Closed as completed by zeripath** 2021-06-21 09:55 UTC
Labels: issue/duplicate

**Comment by jakubgs** [comment] 2021-06-21 11:37
But I do have a value for that setting, and it is an absolute path:
```yaml
[repository]
ROOT = /data/git/repositories

[repository.local]
LOCAL_COPY_PATH = /data/gitea/tmp/local-repo

[repository.upload]
TEMP_PATH = /data/gitea/uploads

[server]
APP_DATA_PATH    = /data/gitea
```
So why is it not working?

**Comment by zeripath** [comment] 2021-06-21 11:46
Oh I've just seen you're using 1.14.0 - use 1.14.3

**Comment by zeripath** [comment] 2021-06-21 11:46
(and if that fails give us the full logs too.)

**Comment by jakubgs** [comment] 2021-06-21 11:49
I have tried with `1.14.3` and the same thing happens:
https://gist.github.com/jakubgs/752203b20581700c288fa856bc7d48a6

**Comment by zeripath** [comment] 2021-06-21 11:52
This is therefore an exact duplicate of #16210.

Let's move over there.
