### ISSUE TITLE
comment button is not active during review mode

### ISSUE THREAD

**Issue by lakostin** [go-gitea/gitea#17218] opened 2021-10-04 10:48 UTC
### Gitea Version

1.15.0

### Git Version

2.30.2

### Operating System

docker Alpine Linux v3.13

### How are you running Gitea?

docker

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

During review "Comment" button is not being pushed.

2021/10/01 17:20:05 ...s/context/context.go:195:HTML() [E] Render failed: template: repo/diff/conversation:1:16: executing "repo/diff/conversation" at <index .comments 0>: error calling index: reflect: slice ind
ex out of range

### Screenshots

https://user-images.githubusercontent.com/29179059/135637954-25da3ccf-3894-4743-86e4-a6033459ed38.MOV

**Comment by axifive** [comment] 2021-10-04 17:03
Can you prepare a test repository with this bug at try.gitea.io or gitea.com?

**Comment by 99rgosse** [comment] 2022-05-18 08:37
Okay I got this one too,
It seems that someone of my team, yesterday, prepared comments on a PR, but did not click on "Review => Request changes".

Then today the comments are gone. And clicking to recreate them generates :
`2022/05/18 08:33:40 Started POST /thisrepo/pulls/3616/files/reviews/comments for 172.18.0.6:41826`
`2022/05/18 08:33:40 ...s/context/context.go:214:HTML() [E] Render failed: template: repo/diff/conversation:1:16: executing "repo/diff/conversation" at <index .comments 0>: error calling index: reflect: slice index out of range`
`2022/05/18 08:33:40 Completed POST /thisrepo/pulls/3616/files/reviews/comments 500 Internal Server Error in 385.030984ms`

But, clicking on other line sections works fine.
I will try to get this.

**Comment by vilunov** [comment] 2023-09-21 15:12
Reproduced this one on 1.20.3 after leaving a reply comment on an open PR. After page refresh, the comment is visible on "conversations" page, but not on "files changed" page.

PR in question: https://git.vilunov.me/lavina/lavina/pulls/12
I will keep it unmerged for a week so that you can take a look

**Comment by lunny** [comment] 2024-03-25 14:17
Looks like it's the same as #28347 and was fixed by #28351

**Closed as completed by lunny** 2024-03-25 14:17 UTC
Labels: type/bug
