### ISSUE TITLE
Uplink NPM Feature Similar to Verdaccio

### ISSUE THREAD

**Issue by fahrulseptiana** [go-gitea/gitea#26667] opened 2023-08-22 17:54 UTC
### Feature Description

I have been an avid user of Gitea for managing my NPM packages, and I truly appreciate the simplicity and effectiveness of your platform. One feature that I find particularly useful in the realm of NPM package management is the Uplink feature that is offered by Verdaccio. The Uplink feature allows users to proxy external NPM registries, enabling efficient caching and improved access to external dependencies. This not only enhances package retrieval speed but also ensures more reliable package availability.

Given the benefits of the Uplink feature in Verdaccio, I wanted to suggest that Gitea consider implementing a similar Uplink feature within your platform.

Reference: [https://verdaccio.org/docs/uplinks/](https://verdaccio.org/docs/uplinks/)

**Comment by KN4CK3R** [comment] 2023-08-27 18:30
Duplicate of #21223

**Closed as completed by KN4CK3R** 2023-08-27 18:30 UTC
Labels: issue/duplicate, type/proposal, topic/packages
