### ISSUE TITLE
Stuck creating new local storage 

### ISSUE THREAD

**Issue by profectcru** [go-gitea/gitea#21661] opened 2022-11-02 14:36 UTC
### Description

I copied a gitea instance from one kubernetes environment to another and I can't seem to start the copy - the original instance is still running fine however.

All the data is an exact copy, environment is kept as close to the original as possible.

/data is mounted from an NFS share in both cases, permissions are fine. The folder is created successfully, but startup never advances past the last entry in the storage module init function: https://github.com/go-gitea/gitea/blob/v1.16.9/modules/storage/storage.go#L131
On version 1.13.11 it got stuck on the LFS storage, while its now moved on to Repo Archives on v1.16.9.

### Gitea Version

1.13.11-1.16.9

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/profectcru/92b6682a9c3b10e530f7f344bbd8ba4f

### Operating System

Ubuntu 20.04.4

### How are you running Gitea?

Kubernetes 1.22.4
Docker 20.10.11

### Database

PostgreSQL

**Comment by wxiaoguang** [comment] 2022-11-03 01:53
The duplicate logs: maybe the logger setting in your `app.ini` is wrong.

About "startup never advances past the last entry": I didn't see the problem in your provided logs. The last log "Creating new Local Storage" is just a log, it doesn't mean that anything is blocked.

**Comment by profectcru** [comment] 2022-11-03 07:49
Hi, the duplicate logs are definitely from having 2 loggers setup, i just added the traceconsole example on top of the regular console logs, hoping that would work.

Still, gitea web never comes up after this last line is printed - even after a week of waiting and working on something else.
Maybe the next step in initialization takes a long time - longer than the allowed startup time of the pod? What would be next in initialization?

**Comment by wxiaoguang** [comment] 2022-11-03 07:52
1.16 is out of dated.

Could you try the latest 1.17.x? If Gitea startup blocks,  you can try (5) in https://docs.gitea.io/en-us/seek-help/  , to see what happens inside.

**Comment by profectcru** [comment] 2022-11-03 08:03
I've been going 1.13 -> 1.14 -> ... -> 1.17 now but still stuck at the last local storage initialisation step (now packages instead of repo-archive).

My app.ini has:
`
 [log]
 MODE = console,traceconsole
 
 [log.traceconsole] ; traceconsole here is just a name
 MODE = console ; this is the output that the traceconsole writes to
 LEVEL = trace
`
which is where the double lines are coming from - trace logging should be enabled but im still not seeing any helpful log lines. :/

I will try step 5 of the seek help article next.

**Comment by wxiaoguang** [comment] 2022-11-03 11:09
I think it blocks here

cmd.runWeb -> GlobalInitInstalled -> ... -> nosql.(*Manager).GetLevelDB

Either, the LevelDB is opened by another process, or, the LevelDB is corrupted.

I think you can try to delete all LevelDB files to retry.

```

1 @ 0x443c56 0x40f50c 0x40ef38 0xe04725 0x16c89e5 0x16c874b 0x16c92ee 0x16c3dae 0x16cf41d 0x1b8baa8 0x1b8ba19 0x21b581b 0x2299051 0x1becb28 0x1bed912 0x1bea187 0x22d5979 0x443892 0x474681
# labels: {"graceful-lifecycle":"with-hammer"}
#       0xe04724        code.gitea.io/gitea/modules/nosql.(*Manager).GetLevelDB+0x144           /go/src/code.gitea.io/gitea/modules/nosql/manager_leveldb.go:71
#       0x16c89e4       code.gitea.io/gitea/modules/queue.NewLevelQueueByteFIFO+0x44            /go/src/code.gitea.io/gitea/modules/queue/queue_disk.go:71
#       0x16c874a       code.gitea.io/gitea/modules/queue.NewLevelQueue+0x18a                   /go/src/code.gitea.io/gitea/modules/queue/queue_disk.go:44
#       0x16c92ed       code.gitea.io/gitea/modules/queue.NewPersistableChannelQueue+0x46d      /go/src/code.gitea.io/gitea/modules/queue/queue_disk_channel.go:101
#       0x16c3dad       code.gitea.io/gitea/modules/queue.NewQueue+0x8d                         /go/src/code.gitea.io/gitea/modules/queue/queue.go:201
#       0x16cf41c       code.gitea.io/gitea/modules/queue.CreateQueue+0x25c                     /go/src/code.gitea.io/gitea/modules/queue/setting.go:51
#       0x1b8baa7       code.gitea.io/gitea/modules/notification/ui.NewNotifier+0xa7            /go/src/code.gitea.io/gitea/modules/notification/ui/ui.go:38
#       0x1b8ba18       code.gitea.io/gitea/modules/notification.NewContext+0x18                /go/src/code.gitea.io/gitea/modules/notification/notification.go:33
#       0x21b581a       code.gitea.io/gitea/routers.GlobalInitInstalled+0x4ba                   /go/src/code.gitea.io/gitea/routers/init.go:122
#       0x2299050       code.gitea.io/gitea/cmd.runWeb+0x810                                    /go/src/code.gitea.io/gitea/cmd/web.go:160
#       0x1becb27       github.com/urfave/cli.HandleAction+0xa7                                 /go/pkg/mod/github.com/urfave/cli@v1.22.9/app.go:524
#       0x1bed911       github.com/urfave/cli.Command.Run+0x651                                 /go/pkg/mod/github.com/urfave/cli@v1.22.9/command.go:173
#       0x1bea186       github.com/urfave/cli.(*App).Run+0x8a6                                  /go/pkg/mod/github.com/urfave/cli@v1.22.9/app.go:277
#       0x22d5978       main.main+0xcf8                                                         /go/src/code.gitea.io/gitea/main.go:116
#       0x443891        runtime.main+0x211                                                      /usr/local/go/src/runtime/proc.go:250
```

**Comment by wxiaoguang** [comment] 2022-11-03 11:13
And according to the LevelDB stacktrace, more guess: 

Either, the LevelDB is opened by another process, or the file system doesn't support file lock well.

Anyway, the problem is highly likely related to the LevelDB module in your environment.

```

1 @ 0x4c2885 0x4bfe98 0xa10d8b 0xa10c25 0xa0b4b2 0xa32939 0xe066a5 0xe04852 0x474681
# labels: {"pid":"63637667-3", "ppid":"", "process-description":"Service: NoSQL", "process-type":"system"}
#       0x4c2884        syscall.Syscall+0x4                                                     /usr/local/go/src/syscall/asm_linux_amd64.s:20
#       0x4bfe97        syscall.Flock+0x37                                                      /usr/local/go/src/syscall/zsyscall_linux_amd64.go:413
#       0xa10d8a        github.com/syndtr/goleveldb/leveldb/storage.setFileLock+0x8a            /go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/storage/file_storage_unix.go:59
#       0xa10c24        github.com/syndtr/goleveldb/leveldb/storage.newFileLock+0xc4            /go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/storage/file_storage_unix.go:41
#       0xa0b4b1        github.com/syndtr/goleveldb/leveldb/storage.OpenFile+0x1d1              /go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/storage/file_storage.go:107
#       0xa32938        github.com/syndtr/goleveldb/leveldb.OpenFile+0x38                       /go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:215
#       0xe066a4        code.gitea.io/gitea/modules/nosql.(*Manager).getLevelDB+0x1c84          /go/src/code.gitea.io/gitea/modules/nosql/manager_leveldb.go:192
#       0xe04851        code.gitea.io/gitea/modules/nosql.(*Manager).GetLevelDB.func1+0xb1      /go/src/code.gitea.io/gitea/modules/nosql/manager_leveldb.go:69
```

**Comment by profectcru** [comment] 2022-11-03 14:01
File Locking may well be the cause then, since the volume is a mounted NFS share. I couldn't find any files hinting at leveldb, where should I be looking for those?

**Comment by wxiaoguang** [comment] 2022-11-04 01:24
TBH, I have no idea. Maybe you can search "leveldb" in https://github.com/go-gitea/gitea/blob/main/custom/conf/app.example.ini, and you can use redis instead.

**Comment by profectcru** [comment] 2022-11-08 08:35
I originally installed using the helm chart, the version i was using is obviously outdated by now but it's using memcached for caching - wouldn't this replace leveldb or redis? There's no mention of leveldb in my app.ini.

**Comment by lunny** [comment] 2023-03-29 06:49
Is the problem still there. And I want to mention, if Gitea is running, the leveldb folder should not be copied successfully.

**Comment by wxiaoguang** [comment] 2023-04-26 17:17
No more feedback, I think we can close this issue. Feel free to reopen if there are new clues.

**Closed as completed by wxiaoguang** 2023-04-26 17:17 UTC
Labels: issue/needs-feedback
