### ISSUE TITLE
URLs in markdown are rendered with Javascript

### ISSUE THREAD

**Issue by kolaente** [go-gitea/gitea#3364] opened 2018-01-13 10:56 UTC
- Gitea version (or commit ref): a8325dd
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/ZeroNet/ZeroNet

## Description

URLs in Markdown documents are parsed with Javascript. Is there a reason for this? I don't think its a good approach. And the markdown library we're using does support that, so there's no real need to make it more complicated. (Quick example: https://gist.github.com/kolaente/2d8ad9e2ebc0562698ec052dc575e5d9)

**Comment by thehowl** [comment] 2018-01-13 11:12
Known and being resolved by #3354. (The way to solve the issue is more complicated than a simple "flick a switch in blackfriday", but I'm working on it)

**Comment by kolaente** [comment] 2018-01-13 11:15
Oh very cool! There is another issue open for this which I've just found: #652

**Closed as completed** 2018-02-27 07:09 UTC
Labels: type/bug
