### ISSUE TITLE
 SourceHut will blacklist the Go module mirror

### ISSUE THREAD

**Issue by simmstein** [go-gitea/gitea#22389] opened 2023-01-10 07:57 UTC
### Description

SourceHut will disable git access for the [Go Module Mirror](https://proxy.golang.org/) on February 24th, 2023.
https://sourcehut.org/blog/2023-01-09-gomodulemirror/

GItea uses `git.sr.ht/~mariusor/go-xsd-duration`.

### Gitea Version

Not revelant.

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Not revelant.

### Database

None

**Comment by yardenshoham** [comment] 2023-01-10 08:03
We don't use proxy.golang.org, we use goproxy.io so this shouldn't be an issue. @jolheiser please confirm

**Comment by zeripath** [comment] 2023-01-10 09:45
```
$ go mod why git.sr.ht/~mariusor/go-xsd-duration
# git.sr.ht/~mariusor/go-xsd-duration
code.gitea.io/gitea/routers/api/v1/activitypub
github.com/go-ap/activitypub
git.sr.ht/~mariusor/go-xsd-duration
```

**Comment by zeripath** [comment] 2023-01-10 09:47
So whilst I think our CI should continue to work - the issue is likely that anyone else building from source will be negatively affected.

**Comment by yardenshoham** [comment] 2023-01-10 09:57
We could add it to the `Makefile`

**Comment by zeripath** [comment] 2023-01-10 10:23
I guess as long as we don't override any personal setting that a user has set this would probably be fine.

**Comment by jolheiser** [comment] 2023-01-10 11:39
There is still some ongoing discussion between the Go team and Drew, so hopefully this can be resolved before action is needed yet.

As mentioned, CI should continue to work, and past that there's a chance users won't be affected if the transitive dep doesn't change, as the module proxy should still serve the last updated version regardless.

**Comment by silverwind** [comment] 2023-01-13 13:42
> We could add it to the Makefile

I'd rather we vendor/incorporate the affected module than to mess with `GOPROXY`. The official proxy has certain undocumented behaviours that other proxies might not have, for example fixing the broken `hugo` releases.

**Comment by Goorzhel** [comment] 2023-02-25 21:22
> [Update 2023-01-31](https://sourcehut.org/blog/2023-01-09-gomodulemirror/): Russ Cox of the Go team reached out to us to address this problem. After some discussion, an acceptable plan was worked out. [...] Consequently, we have cancelled our plans to disable Go traffic to git.sr.ht. No action is required by users to continue receiving service. Thanks Russ!

**Comment by jolheiser** [comment] 2023-02-25 21:23
Thanks for the update! I'll close this for now, then.

**Closed as completed by jolheiser** 2023-02-25 21:23 UTC
