### ISSUE TITLE
Gitea 1.21.4 adds 'user-content-' in markdown file

### ISSUE THREAD

**Issue by makar112233** [go-gitea/gitea#29196] opened 2024-02-16 14:42 UTC
### Description

Hi.
I can't navigate through .md file in my repo, because all links in headers are converting from `readme.md#_toc152597800` to `readme.md#user-content-_toc152597800` and it breaks navigation through file.
I read, that it was fixed in https://github.com/go-gitea/gitea/pull/11903 but I can reproduce it in my local instance and in public Gitea instance: https://try.gitea.io/wenofib626/user-content/src/branch/main/readme.md

### Gitea Version

1.21.4

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

2.43.0

### Operating System

linux

### How are you running Gitea?

Self-hosted, systemd

### Database

PostgreSQL

**Comment by wxiaoguang** [comment] 2024-02-16 15:36
Regression of  Make user-content-* consistent with github #26388 @CaiCandong

**Comment by silverwind** [comment] 2024-02-16 15:45
Keep in mind `user-content-` prefix is also a security precaution, because we can't allow user content to override `id`s on the page. The mechanism should be completely transparent to the user, e.g. hash navigation should work with and without the prefix.

**Comment by silverwind** [comment] 2024-02-16 15:52
@makar112233 what is the exact issue? Does hash navigation not work for you? Keep note it does require having JavaScript enabled to work.

**Comment by wxiaoguang** [comment] 2024-02-16 15:53
> but I can reproduce it in my local instance and in public Gitea instance: https://try.gitea.io/wenofib626/user-content/src/branch/main/readme.md

@silverwind according to the report, and the demo on try.gitea.io, it doesn't work (neither for me).

**Comment by silverwind** [comment] 2024-02-16 15:55
Ah yes, I can see the issue on try. Maybe something wrong in https://github.com/go-gitea/gitea/blob/main/web_src/js/markup/anchors.js or does the backend set ids that are incompatible with the JS?

**Comment by makar112233** [comment] 2024-02-16 21:41
It works fine on Bitbucket server and it didn’t add “user-content” words into link.

**Comment by DanielMatiasCarvalho** [comment] 2024-02-19 21:56
Hello.
@makar112233 I have been trying to replicate exactly this problem in my repository but I can only achieve partial success, since when I use `readme.md#_toc152597800`, I can't make it so it goes to the respective header. 

Could you show the source file you created, so I can understand the problem exactly and try to solve it?

**Comment by silverwind** [comment] 2024-02-19 22:51
Actually no, I still don't understand what the issue is supposed to be. HTML here is

<img width="534" alt="image" src="https://github.com/go-gitea/gitea/assets/115237/ea060e4c-fea9-4532-a4b3-342996e9a60c">

The `<a>` is inserted by the JS and is the "link" icon when hovering the heading. When clicking it, the page scrolls to the heading and this persists when hitting F5 as well because of the JS in `initMarkupAnchors`.

This behaviour is the same as GitHub, which has HTML like this:

<img width="592" alt="image" src="https://github.com/go-gitea/gitea/assets/115237/5b53d620-a9d6-4c11-901b-1f19c067c62a">

So the only reason why those links do not work is that your browser's JS is disabled or broken and I'm pretty sure it wouldn't work on GitHub either.

**Comment by DanielMatiasCarvalho** [comment] 2024-02-19 23:05
Hello.

Could this issue be assigned to me? I would like to give a try at solving this.

**Comment by silverwind** [comment] 2024-02-19 23:26
Ah I see now that the problem is about the manual TOC links

```md
[Review](#_toc152597800)
[Staging](#_toc152597802)
[Development](#_toc152597803)
[Testing](#_toc152597828)
[Unit-tests](#_toc152597829)
```

Renders as 

```md
<p dir="auto"><a href="#user-content-_toc152597800" rel="nofollow">Review</a></p>
<p dir="auto"><a href="#user-content-_toc152597802" rel="nofollow">Staging</a></p>
<p dir="auto"><a href="#user-content-_toc152597803" rel="nofollow">Development</a></p>
<p dir="auto"><a href="#user-content-_toc152597828" rel="nofollow">Testing</a></p>
<p dir="auto"><a href="#user-content-_toc152597829" rel="nofollow">Unit-tests</a></p>
```

So we need to strip the prefix of user-generated links in JS.

**Comment by silverwind** [comment] 2024-02-19 23:27
@DanielMatiasCarvalho give it a try. If we don't hear back, I will fix it in a couple of days.

**Comment by makar112233** [comment] 2024-02-20 05:55
Thank you in advance, guys.

**Comment by DanielMatiasCarvalho** [comment] 2024-02-23 21:50
@makar112233 I believe I have solved the problem. Just waiting to see if my PR is accepted!😁

**Comment by makar112233** [comment] 2024-02-26 07:00
@DanielMatiasCarvalho super! Waiting for release)

**Closed as completed** 2024-03-08 09:53 UTC
Labels: type/bug
