### ISSUE TITLE
Gitea shows wrong code on lines with comments on Conversation tab

### ISSUE THREAD

**Issue by lakostin** [go-gitea/gitea#14268] opened 2021-01-06 10:49 UTC
- Gitea version (or commit ref):
1.14.0+dev-514-gd2ee1221c
- Git version:
2.26.2
- Operating system:
docker Alpine Linux v3.12
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description
I added comment to line. On Conversation tab gitea shows comment with other code, line numbers are correct though.
...

## Screenshots
Conversation tab:
![Screenshot from 2021-01-06 13-39-01](https://user-images.githubusercontent.com/29179059/103759423-c17a6200-5024-11eb-93f9-bb15239b5d35.png)
Files changed tab:
![Screenshot from 2021-01-06 13-38-39](https://user-images.githubusercontent.com/29179059/103759429-c5a67f80-5024-11eb-9356-c8ab4033380c.png)

**Comment by jpraet** [comment] 2021-01-06 17:34
Probably a duplicate of #13683 (which is already fixed.. but it doesn't fix the location for existing comments).

Do you know what version you were on 6 days ago when you made the comment?
Could you delete the comment and add it again to see if the problem persists?

**Comment by lakostin** [comment] 2021-01-12 11:45
Updated gitea, deleted comment and added a new one - the problem is gone. Thank you.

**Closed as completed** 2021-01-14 02:41 UTC
Labels: issue/needs-feedback
