### ISSUE TITLE
[Feature] Allow autodeleting branches after their PRs have been merged

### ISSUE THREAD

**Issue by delvh** [go-gitea/gitea#14892] opened 2021-03-05 11:02 UTC
- Gitea version (or commit ref): 1.14.0+dev-800-g752545023

## Description
Most often, after a PR from branch **a** to branch **b** has been merged, **a** is not needed anymore.
It would be nice (and time/ energy saving) if you could activate in the repo settings whether branches of merged PRs should be autodeleted (as humans tend to forget to delete the branch after it has been merged, leading to unused branches in the project).

Later on, even the distinction between merged and closed PRs could be made by using another setting whether branches of closed PRs should also be autodeleted (even though that will be used rarely).

**Comment by lunny** [comment] 2021-03-05 11:17
So this could be a personal setting.

**Comment by delvh** [comment] 2021-03-05 11:26
No, not really:
What is the behavior when person **a** commits and is basically the author of the PR, and he does not activate autodeleting branches, while person **b** merges the PR and has autodeletion active?
Will the branch get closed or not? Should Person B be responsible then for the deletion of the branch? 

While it might be a little bit more work on the user side to check the box for each repository, it definitely leads to way less confusion and a clearer appearance of what is happening behind the scenes.

**Comment by tomaswarynyca** [comment] 2021-03-05 12:46
I agree with @delvh it has to be a repository option.

**Comment by lunny** [comment] 2021-03-05 15:47
For the original repository or fork repositories? I assume not for original repositories, because original repositories' setting should not delete fork repositories' branches there is a permission problem here.

**Comment by jolheiser** [comment] 2021-03-05 15:54
One of the (only) things Azure does that I like is, when closing a PR, it gives me a checkbox for whether to remove the branch.

The checkbox could perhaps be defaulted to some user/repo setting, but then the checkbox can be changed ad-hoc.

Obviously this would need to adhere to branch protection and other permissions

**Comment by delvh** [comment] 2021-03-05 16:38
@lunny Can't forked repositories change the repo settings? I would have thought so…

**Comment by jpraet** [comment] 2021-03-05 18:46
see also #13568

**Comment by techknowlogick** [comment] 2021-03-06 01:37
closing as dupe of #13568

**Closed as completed by techknowlogick** 2021-03-06 01:37 UTC
Labels: issue/duplicate
