### ISSUE TITLE
Release menu

### ISSUE THREAD

**Issue by marknovem** [go-gitea/gitea#8171] opened 2019-09-13 08:48 UTC
big 500 error code displayed when accessing "Release" menu. Below are the sample logs on the server during the operation:

```
 []interface {}{1, 3}
2019/09/13 16:48:18 .../xorm/session_get.go:99:nocacheGet() [I] [SQL] SELECT "id", "uid", "repo_id" FROM "star" WHERE "uid"=$1 AND "repo_id"=$2 LIMIT 1 []interface {}{1, 3}
2019/09/13 16:48:18 ...xorm/session_find.go:199:noCacheFind() [I] [SQL] SELECT "id", "repo_id", "publisher_id", "tag_name", "lower_tag_name", "target", "title", "sha1", "num_commits", "note", "is_draft", "is_prerelease", "is_tag", "created_unix" FROM "release" WHERE repo_id=$1 ORDER BY "created_unix" DESC, "id" DESC LIMIT 10 []interface {}{3}
2019/09/13 16:48:18 .../xorm/session_raw.go:87:queryRow() [I] [SQL] SELECT count(*) FROM "release" WHERE repo_id=$1 []interface {}{3}
2019/09/13 16:48:18 ...xorm/session_find.go:199:noCacheFind() [I] [SQL] SELECT "id", "uuid", "issue_id", "release_id", "uploader_id", "comment_id", "name", "download_count", "size", "created_unix" FROM "attachment" WHERE "release_id" IN ($1) ORDER BY "release_id" ASC []interface {}{1}
2019/09/13 16:48:18 .../xorm/session_get.go:99:nocacheGet() [I] [SQL] SELECT "id", "lower_name", "name", "full_name", "email", "keep_email_private", "passwd", "must_change_password", "login_type", "login_source", "login_name", "type", "location", "website", "rands", "salt", "language", "description", "created_unix", "updated_unix", "last_login_unix", "last_repo_visibility", "max_repo_creation", "is_active", "is_admin", "allow_git_hook", "allow_import_local", "allow_create_organization", "prohibit_login", "avatar", "avatar_email", "use_custom_avatar", "num_followers", "num_following", "num_stars", "num_repos", "num_teams", "num_members", "visibility", "diff_view_style", "theme" FROM "user" WHERE "id"=$1 LIMIT 1 []interface {}{0}
2019/09/13 16:48:18 ...ters/repo/release.go:115:Releases() [E] calReleaseNumCommitsBehind: GetBranchCommit: object not found
```

Is there anything i missed to configured or missed to perform? please help me solve this problem. Thanks.

**Comment by lunny** [comment] 2019-09-13 12:55
Have you force push to remove some commits?

**Comment by marknovem** [comment] 2019-09-14 04:31
Nope.. i just perform 3 successive commits and push respectively and then create 1 tag. After that i notice that the "Releases" menu has a suffix value of "1" (e.g. 'Releases 1' ) so when i click it, the 500 error was displayed.

**Comment by JakobR** [comment] 2019-09-27 13:09
I'm having the same issue, with the same error message in the logs (`calReleaseNumCommitsBehind: GetBranchCommit: object not found`).

Versions:
- gitea 1.9.3 built with go1.13
- git 2.23.0

I have not force-pushed either, but I have pushed the commits and tag separately, if that makes any difference (i.e., something like `git commit; git push; git tag v1-xyz; git push --tags`).

**Comment by lunny** [comment] 2019-09-30 02:28
@JakobR did your tag name has a space on middle?

**Comment by JakobR** [comment] 2019-09-30 06:49
No, it was just lowercase letters with a hyphen (`-`) in the middle.

**Comment by JakobR** [comment] 2019-11-01 11:10
The release menu now works for me after upgrading to gitea 1.9.5.

**Comment by zeripath** [comment] 2019-11-01 21:07
Cool I think I'll close this issue as fixed. @marknovem please reopen if the issue is not fixed.

**Closed as completed by zeripath** 2019-11-01 21:07 UTC
Labels: issue/needs-feedback
