### ISSUE TITLE
OAuth Provider - getting "unauthorized" when trying to enable repo in drone

### ISSUE THREAD

**Issue by oliver006** [go-gitea/gitea#6703] opened 2019-04-22 01:52 UTC
- Gitea version (or commit ref):
1.8.0

- Git version:
git version 2.17.1
- Operating system:
Ubuntu 18.04

- Database (use `[x]`):
  - [x] PostgreSQL

## Description
As per https://github.com/drone/drone/pull/2622#issuecomment-485299376

Gitea 1.8.0 and docker image `drone/drone@sha256:7acfbba60ac6c35537b099ce612aac0af3cdbfa2e48d0ee96730cd4c904b89fa` (the one right after merging the Gitea OAuth PR https://github.com/drone/drone/pull/2622)

I use Gitea to log into drone. Logging in works as expected and I can perform all sorts of actions in drone like changing settings, restarting builds, etc but after about an hour, when the the oauth token expires, I can not take actions to like enabling a Gitea repo for builds, getting this error:

<img width="967" alt="image" src="https://user-images.githubusercontent.com/1222339/56478421-4f8f6d00-647d-11e9-835e-2673ccf65826.png">

Let me know what other information would be helpful to solve this issue.

**Comment by jonasfranz** [comment] 2019-04-22 06:55
As an hotfix, you can increase the access token lifetime like stated in the config cheat sheet.

**Comment by jonasfranz** [comment] 2019-04-22 06:57
@oliver006 Do you have the logs with http requests?

**Comment by oliver006** [comment] 2019-04-22 13:06
Thanks @jonasfranz - I'll increase the token lifetime as a workaround.

Here are the logs.

Gitea:
```
[Macaron] 2019-04-22 13:02:07: Started GET /metrics for 192.168.0.11
[Macaron] 2019-04-22 13:02:07: Completed GET /metrics 200 OK in 67.797419ms
[Macaron] 2019-04-22 13:02:10: Started GET /api/v1/repos/oliver/test for 195.201.18.0
[Macaron] 2019-04-22 13:02:10: Completed GET /api/v1/repos/oliver/test 200 OK in 13.401037ms
[Macaron] 2019-04-22 13:02:10: Started GET /api/v1/repos/oliver/test for 195.201.18.0
[Macaron] 2019-04-22 13:02:10: Started GET /api/v1/repos/oliver/test for 195.201.18.0
[Macaron] 2019-04-22 13:02:10: Completed GET /api/v1/repos/oliver/test 200 OK in 15.937571ms
[Macaron] 2019-04-22 13:02:10: Completed GET /api/v1/repos/oliver/test 200 OK in 14.866289ms
[Macaron] 2019-04-22 13:02:10: Started GET / for 195.201.18.0
[Macaron] 2019-04-22 13:02:10: Completed GET / 200 OK in 87.525221ms
[Macaron] 2019-04-22 13:02:12: Started GET /api/v1/repos/oliver/test/hooks for 195.201.18.0
[Macaron] 2019-04-22 13:02:12: Completed GET /api/v1/repos/oliver/test/hooks 401 Unauthorized in 8.088936ms
```
\
\
drone:

```

DEBU[0471] api: sync repository permissions              admin=false name=test namespace=oliver read=true request-id=1KDtjQ51qptHwQecMwvFZzgd0H8 user.admin=true user.login=oliver write=false
DEBU[0471] api: sync repository permissions              admin=false name=test namespace=oliver read=true request-id=1KDtjOtw9xBkdDtAZWmKxJh0Dwa user.admin=true user.login=oliver write=false
DEBU[0471] api: sync repository permissions              admin=false name=test namespace=oliver read=true request-id=1KDtjSPT4Ouga0ZszSc7BaqoaP1 user.admin=true user.login=oliver write=false
DEBU[0471] api: repository permissions synchrnoized      admin=false name=test namespace=oliver read=true request-id=1KDtjQ51qptHwQecMwvFZzgd0H8 user.admin=true user.login=oliver write=false
DEBU[0471] api: root access granted                      name=test namespace=oliver request-id=1KDtjQ51qptHwQecMwvFZzgd0H8 user.admin=true user.login=oliver
DEBU[0471]                                               fields.time="2019-04-22T13:02:10Z" latency=233.214124ms method=GET remote="192.168.0.1:37300" request=/api/repos/oliver/test request-id=1KDtjQ51qptHwQecMwvFZzgd0H8
DEBU[0471] api: repository permissions synchrnoized      admin=false name=test namespace=oliver read=true request-id=1KDtjOtw9xBkdDtAZWmKxJh0Dwa user.admin=true user.login=oliver write=false
DEBU[0471] api: root access granted                      name=test namespace=oliver request-id=1KDtjOtw9xBkdDtAZWmKxJh0Dwa user.admin=true user.login=oliver
DEBU[0471] api: root access granted                      name=test namespace=oliver request-id=1KDtjOtw9xBkdDtAZWmKxJh0Dwa user.admin=true user.login=oliver
DEBU[0471] api: repository permissions synchrnoized      admin=false name=test namespace=oliver read=true request-id=1KDtjSPT4Ouga0ZszSc7BaqoaP1 user.admin=true user.login=oliver write=false
DEBU[0471] api: root access granted                      name=test namespace=oliver request-id=1KDtjSPT4Ouga0ZszSc7BaqoaP1 user.admin=true user.login=oliver
DEBU[0471] api: root access granted                      name=test namespace=oliver request-id=1KDtjSPT4Ouga0ZszSc7BaqoaP1 user.admin=true user.login=oliver
DEBU[0471]                                               fields.time="2019-04-22T13:02:10Z" latency=258.906866ms method=GET remote="192.168.0.1:37306" request=/api/repos/oliver/test/secrets request-id=1KDtjOtw9xBkdDtAZWmKxJh0Dwa
DEBU[0471]                                               fields.time="2019-04-22T13:02:10Z" latency=253.489957ms method=GET remote="192.168.0.1:37310" request=/api/repos/oliver/test/cron request-id=1KDtjSPT4Ouga0ZszSc7BaqoaP1
DEBU[0472]                                               fields.time="2019-04-22T13:02:11Z" latency="58.706µs" method=GET remote="192.168.0.1:37338" request=/ request-id=1KDtjWSbINsejmJOFxRJSZjJCaU
DEBU[0472] api: root access granted                      name=test namespace=oliver request-id=1KDtjcsWdA3DcHIz0dHlhJn5lDX user.admin=true user.login=oliver
DEBU[0472] api: root access granted                      name=test namespace=oliver request-id=1KDtjcsWdA3DcHIz0dHlhJn5lDX user.admin=true user.login=oliver
DEBU[0473] api: cannot create or update hook             error=Unauthorized name=test namespace=oliver request-id=1KDtjcsWdA3DcHIz0dHlhJn5lDX user.admin=true user.login=oliver
DEBU[0473]                                               fields.time="2019-04-22T13:02:12Z" latency=128.866188ms method=POST remote="192.168.0.1:37342" request=/api/repos/oliver/test request-id=1KDtjcsWdA3DcHIz0dHlhJn5lDX

```

**Comment by oliver006** [comment] 2019-04-22 13:07
(To reproduce the issue more easily I set the token lifetime to 100s so it'll expire sooner)

**Comment by jonasfranz** [comment] 2019-04-22 18:12
Hmm, it seams that drone does not send a request to refresh the access token. Do you have other logs containing HTTP requests? Otherwise I would like to ask @bradrydzewski if drone support refresh tokens?

**Comment by bradrydzewski** [comment] 2019-04-22 18:16
Yes, Drone supports refresh tokens for Bitbucket

It looks like the Gitea implementation needs to be updated to configure a refresh provider, similar to what we do for Bitbucket. See https://github.com/drone/drone/blob/master/cmd/drone-server/inject_login.go#L166

**Comment by jonasfranz** [comment] 2019-04-22 21:44
Closing this issue since it's not caused by gitea.

**Closed as completed by jonasfranz** 2019-04-22 21:44 UTC
Labels: type/bug, reviewed/wontfix

**Comment by oliver006** [comment] 2019-04-22 23:50
Thanks for the quick investigation everyone!

**Comment by lunny** [comment] 2019-04-23 01:03
so someone could send a PR to drone to fix that as what @bradrydzewski said.

**Comment by techknowlogick** [comment] 2019-04-23 01:04
@lunny see: https://github.com/drone/drone/pull/2684
