### ISSUE TITLE
Adding headers field to webhook

### ISSUE THREAD

**Issue by gregfr** [go-gitea/gitea#21573] opened 2022-10-24 07:21 UTC
### Feature Description

Webhook is a nice feature, but many API servers expect specific headers, such as API key, to be set.

It would be nice to add the possibility to configure headers for webhook requests.

**Comment by techknowlogick** [comment] 2022-10-24 07:23
closing as dupe of https://github.com/go-gitea/gitea/issues/1089

**Closed as completed by techknowlogick** 2022-10-24 07:23 UTC
Labels: type/proposal, type/feature
