### ISSUE TITLE
Unable to select and copy checklist items

### ISSUE THREAD

**Issue by DuckDuckWhale** [go-gitea/gitea#12842] opened 2020-09-14 22:11 UTC
- Gitea version (or commit ref): 1.12.4 built with GNU Make 4.1, go1.14.8 : bindata, sqlite, sqlite_unlock_notify
- Git version: 2.25.1
- Operating system: Ubuntu 20.04
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes <https://try.gitea.io/flyscan/Testing-Todo-Markdown>
  - [ ] No
  - [ ] Not relevant
- Log gist: N/A

## Description

Unable to select and copy the text on the rendered markdown when using checklist.
The mouse turns to the pointer icon and left clicking and dragging has no effect.
Left clicking and dragging from non-checklist area, moving across the checklist, and releasing at the bottom selects
everything but the checklist, and copying shows that the checklist is indeed unselected.

This issue can be similarly reproduced on issue comments.

## Screenshots

![selection](https://user-images.githubusercontent.com/28813824/93143145-343d8700-f69c-11ea-9fcf-ee927b938387.png)

**Comment by a1012112796** [comment] 2020-09-18 01:48
test gh
- [ ] test

**Comment by a1012112796** [comment] 2020-09-18 01:50
Maybe it's an upstream-related issue

**Comment by DuckDuckWhale** [comment] 2020-09-18 04:24
Seems that after saving an edit containing the checklist, the items become selectable once again but also checkable (which doesn't save).

**Comment by zeripath** [comment] 2020-10-01 19:15
This is a duplicate of #7097

**Comment by DuckDuckWhale** [comment] 2020-10-01 22:53
Doesn't seem to be a duplicate to me, the referenced issue is requesting a checkbox feature but this one is about the expectation of being able to click and drag a mouse to select text and copy text getting broken when using checklists. Can it be reopened? @zeripath

**Comment by DuckDuckWhale** [comment] 2020-12-21 01:30
Can't reproduce now on <https://try.gitea.io/flyscan/Testing-Todo-Markdown> somehow but still reproducible on 1.13.0 in issue comments.

**Comment by noerw** [comment] 2021-05-13 23:10
Selection is working on 1.15.0+dev-291 in both readme and issue comments

**Closed as completed by noerw** 2021-05-13 23:10 UTC
