### ISSUE TITLE
Push error

### ISSUE THREAD

**Issue by SemikolonDEV** [go-gitea/gitea#2270] opened 2017-08-06 14:11 UTC
- Gitea version (or commit ref):  1.1.2
- Git version: 2.7.4
- Operating system: amd64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

I would pushed to my Repo at the Gitea Server and became this error:

`Counting objects: 4, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 374 bytes | 0 bytes/s, done.
Total 4 (delta 2), reused 0 (delta 0)
remote: ./hooks/pre-receive.d/gitea: line 2: /opt/gitea/gitea-1.1.2-linux-arm-7: No such file or directory
To https://git.tysox.de/Semikolon/PasswordTyper.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.tysox.de/Semikolon/PasswordTyper.git'`

**Comment by lafriks** [comment] 2017-08-06 18:04
If you have changed gitea binary name or location you need to call rewrite hooks from admin dashboard page

**Comment by andy0130tw** [comment] 2017-08-07 21:05
Having exactly the same issue above, when installing the latest docker image backed with SQLite as database, the push never succeeds.

Steps to reproduce:
1. Create a repository via the web interface
2. Clone it through HTTPS
3. Make a commit
4. Push and fail with error message "error: failed to push some refs to ..."

The log file `/data/log/hooks/pre-receive` is as follows:

```
2017/08/07 19:49:18 [T] GetProtectedBranchBy: http://localhost:10080/api/internal/branch/1/master
2017/08/07 19:49:18 [...io/gitea/cmd/hook.go:126 runHookPreReceive()] [F] retrieve protected branches information failed
```

Strangely, adding files via the web interface does not trigger the error.

**Comment by lafriks** [comment] 2017-08-07 21:25
@andy0130tw can you check if your app.ini has secret token value set?

**Comment by andy0130tw** [comment] 2017-08-08 06:44
The file seems to be populated upon the install completes. Below is the `[security]` section on my server, where `[...]` is omitted for brevity.

```
[security]
INTERNAL_TOKEN = eyJhb [...] 5a_kk
INSTALL_LOCK   = true
SECRET_KEY     = HL [...] zb
```

**Comment by exap** [comment] 2017-08-28 19:06
I had this issue too.

I temporarily fixed it by setting this in `app.ini`:

    LOCAL_ROOT_URL  = http://localhost:3000/

**Comment by RickZeeland** [comment] 2017-11-30 08:36
Although the answer by lafriks is probably the correct one:

> to call rewrite hooks from admin dashboard

I solved the problem by renaming the Gitea exe to the old name after an update from 1.2.0-RC1 to 1.2.0 on Windows 10.

**Comment by canyugs** [comment] 2017-12-14 08:41
`remote: ./hooks/pre-receive.d/gitea: line 2: /app/gitea/gitea: No such file or directory`

Same issue, but solved by the answer from lafriks

In admin dashboard you should see something like this and Run it 

> Resync pre-receive, update and post-receive hooks of all repositories.

**Comment by lafriks** [comment] 2017-12-14 09:31
Closing this issue as answered

**Closed as completed by lafriks** 2017-12-14 09:31 UTC
Labels: type/question

**Comment by luusl** [comment] 2018-02-12 10:23
I had the same error with the default setting for `LOCAL_ROOT_URL = %(PROTOCOL)s://%(HTTP_ADDR)s:%(HTTP_PORT)s/`, using a unix socket.
```
2018/02/12 10:26:45 [T] GetProtectedBranchBy: unix:///var/run/gitea/gitea.sock:3000/api/internal/branch/1/master
2018/02/12 10:26:45 [...io/gitea/cmd/hook.go:115 runHookPreReceive()] [F] retrieve protected branches information failed
```
After changing this to `LOCAL_ROOT_URL = http://localhost:3000/` it worked.

**Comment by randyesq** [comment] 2019-05-21 16:55
Changing `LOCAL_ROOT_URL = http://localhost:3000/` did not work for me.

**Comment by jtilles** [comment] 2020-08-14 00:28
I had this issue when I started to customize my instance.

I needed to copy `LFS_JWT_SECRET   = {}` from my previous app.ini into my new one.  Restarted the server, and now it works!
