### ISSUE TITLE
Sign git tags & commits

### ISSUE THREAD

**Issue by rugk** [go-gitea/gitea#658] opened 2017-01-12 16:04 UTC
You should consider signing git commits & releases.

* [onionshare#221 (comment)](https://is.gd/7vU4oK)
* It is also displayed on GitHub: https://github.com/blog/2144-gpg-signature-verification
* Here is GitHub's help for this: https://help.github.com/articles/generating-a-gpg-key/
* And here is how you can properly sign releases: https://wiki.debian.org/Creating%20signed%20GitHub%20releases

At least tags should be signed, so one can verify the release versions at least.

**Comment by Bwko** [comment] 2017-01-12 16:55
Duplicate of #425

**Comment by rugk** [comment] 2017-01-12 16:55
[previous post by @Bwko was removed]
No, I want *you* to sign your own commits/tags. The integration into gitea/gog is another issue.

**Comment by Bwko** [comment] 2017-01-12 16:59
I agree, it's a good idea to sign all the commits

**Comment by tboerger** [comment] 2017-01-12 18:54
I'm signing all my commits already, never tried to sign a tag. For the releases I'm not sure how to handle that because it's entirely managed within the ci server

**Comment by rugk** [comment] 2017-01-12 19:17
> never tried to sign a tag

It's [also easy](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work#Signing-Tags).

> For the releases I'm not sure how to handle that because it's entirely managed within the ci server

So they are automatically generated? In this case you should be able to download the version and sign it afterwards.
In this case you would however have to ensure that the things you sign are valid (check the signed commits e.g.).

**Comment by tboerger** [comment] 2017-01-12 19:51
Yes, they are automatically generated and uploaded. Our pipeline is automated, just commits and tags are manually done :)

**Comment by rugk** [comment] 2017-01-13 08:42
When tags are manually done you can easily sign them. That's all I request.
Of course signing the binary files would also be nice, but that's another thing.

**Comment by tboerger** [comment] 2017-01-13 09:25
So everybody should integrate his GPG key into git and sign the commits. I have added this snippet to my `.gitconfig` now, so from now on every tag I publish will be signed by me:

```
[alias]
  tag = tag -s
```

For everybody who is interested, I'm using https://github.com/tboerger/homeshick-base/blob/master/home/.gitconfig as my `~/.gitconfig` and additionally to that I put this into `~/.gitconfig.local`

```
[commit]
  gpgSign = true
```

**Comment by lunny** [comment] 2017-05-04 11:55
since https://github.com/go-gitea/gitea/issues/425 has been resolved. This issue should be resolved also or it's easy to fix now?

**Comment by tboerger** [comment] 2017-05-04 13:07
The releases done by me are based on signed tags already.

**Comment by tboerger** [comment] 2017-05-04 13:08
> since #425 has been resolved. This issue should be resolved also or it's easy to fix now?

That's a totally different story. He just requested to sign our Gitea tags and binaries.

**Comment by lunny** [comment] 2017-05-04 13:26
Ohoh, So this is a build thing not a feature?

**Comment by bkcsoft** [comment] 2017-05-04 17:39
Yeah, and I'm signing my tags. Maybe close when we have a `HOWTO_RELEASE.md` ? 😄

**Comment by agaida** [comment] 2017-11-29 11:52
an annotated or signed tag would be helpful for the upcoming release - git describe  start to look a little bit strange as the latest annotated or signed tag was v1.1.0 -  v1.1.0-783-g183da4c2

**Comment by tboerger** [comment] 2017-11-29 15:27
All tags should be signed and annotated since 1.1.3, otherwise somebody made a mistake :)

**Comment by tboerger** [comment] 2017-11-29 15:28
<img width="982" alt="bildschirmfoto 2017-11-29 um 16 28 04" src="https://user-images.githubusercontent.com/156964/33382931-5211a7fa-d522-11e7-99fa-2e662a9c7167.png">

**Comment by lafriks** [comment] 2017-11-29 15:49
I think we can close the issue as we are already doing it

**Closed as completed by lafriks** 2017-11-29 15:49 UTC
Labels: type/proposal, topic/build

**Comment by agaida** [comment] 2017-11-29 17:04
thats fine - but the last tag related to master was v1.1.0 by some webhippie - and if one follow the current development it looks like that:
> % git describe       
> v1.1.0-815-g033ad9a7

maybe this could be changed, 1.1.0 + 815 commits is nice and precise - ok, speed in Ansgström/Week is also precise.

**Comment by lafriks** [comment] 2017-11-29 17:06
We do not tag on master branch but on release/* branches

**Comment by agaida** [comment] 2017-11-29 17:14
you have - the last tag on master is v1.1.0 - but anyways ...

**Comment by lafriks** [comment] 2017-11-29 17:40
Yes, I mean latest versions

**Comment by agaida** [comment] 2017-11-29 23:54
It's not a problem, it only looks strange
