### ISSUE TITLE
Logged out while editing

### ISSUE THREAD

**Issue by rixx** [go-gitea/gitea#11797] opened 2020-06-07 20:27 UTC
If you edit an issue and keep it open in a tab for some time, your session may end. But if you click "save", there is no indication of an error at all, despite your changes not being saved! Only upon reloading the page you will be redirected to the login screen, with all your changes being irrecoverably lost. Especially with larger edits, this is quite frustrating.

I understand that mitigating this completely is complex (eg maintaining an edit log/drafts in the browser's localStorage would be a way), but the least gitea could do would be a show of an error message instead of pretending that changes have been saved correctly.

- Gitea version (or commit ref): 1.11.4

**Comment by rixx** [comment] 2020-08-06 22:38
bump

**Comment by zeripath** [comment] 2020-10-12 06:12
Does this really still happen with the notification event stream?

**Comment by wxiaoguang** [comment] 2021-12-08 07:22
Duplicate of 
* #17850  here we have more discussions
* #17282

**Closed as completed by wxiaoguang** 2021-12-08 07:22 UTC
Labels: type/bug, issue/needs-feedback
