### ISSUE TITLE
You are running Vue in development mode

### ISSUE THREAD

**Issue by tskamath** [go-gitea/gitea#1864] opened 2017-06-03 15:52 UTC
- Gitea version (or commit ref): 2ec5dc1 built with: bindata, sqlite
- Git version: ?? 
- Operating system: Synology Docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [√] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [√ ] Yes (provide example URL) http://tsktech.dyndns.biz:10080/
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
backend.js:1 [vue-devtools] Ready. Detected Vue v2.1.10

for vue.js website: "Turn on Production Mode

During development, Vue provides a lot of warnings to help you with common errors and pitfalls. However, these warning strings become useless in production and bloat your app’s payload size. In addition, some of these warning checks have small runtime costs that can be avoided in production mode."

is this normal that gitea cannot use vue.js in production mode..?
...
## Screenshots
<img width="1419" alt="screen shot 2017-06-03 at 9 16 24 pm" src="https://cloud.githubusercontent.com/assets/3492767/26754969/fe39b224-48a1-11e7-8b15-f0a7ad51d07d.png">

Regards
Srikanth Kamath

**Comment by sapk** [comment] 2017-06-03 16:12
duplicate of #1736

**Comment by andreynering** [comment] 2017-06-03 17:08
Closed as duplicate

**Closed as completed by andreynering** 2017-06-03 17:08 UTC
Labels: issue/duplicate
