### ISSUE TITLE
JavaScript error when editing md file with Palemoon 32.5.1

### ISSUE THREAD

**Issue by veita** [go-gitea/gitea#28458] opened 2023-12-13 18:34 UTC
### Description

When editing a md file with Palemoon 32.5.1 the following error occurs:
```
JavaScript error: Error: (https://host.example.org/assets/js/index.js?v=1.21.2 @ 17:583).
Open browser console to see more details.
```

### Gitea Version

1.21.2

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

```
JavaScript error: Error: (https://host.example.org/assets/js/index.js?v=1.21.2 @ 17:583).
Open browser console to see more details.
```

### Git Version

git version 2.39.2

### Operating System

Debian GNU/Linux 12 (bookworm) Release:	12

### How are you running Gitea?

As a Systemd service.

### Database

PostgreSQL

**Comment by wxiaoguang** [comment] 2023-12-14 04:19
Quote: **Open browser console to see more details.**

**Comment by wxiaoguang** [comment] 2023-12-14 04:38
It seems that the error comes from MonacoEditor.

Gitea has been using Monaco Editor for long time. In old releases, Gitea didn't report some kinds of JS errors to UI. In 1.21, many JS errors can be reported on the UI.


The root problem is that MonacoEditor can't run perfectly in PaleMoon, MonacoEditor code triggers JS errors.


So, the possible reasons are:

1. The error has been there for long time, but Gitea < 1.21 didn't show it. Gitea 1.21 exposes it, so you see it.
2. There was no error before Gitea 1.21 (old MonacoEditor), while the upgraded MonacoEditor in Gitea 1.21 triggers the new error.

You can try MonacoEditor here: https://microsoft.github.io/monaco-editor/

So maybe you need to make PaleMoon support MonacoEditor.

**Comment by silverwind** [comment] 2023-12-14 12:26
At some point we have to think about whether it's worth it trying to support PaleMoon. It lags at least 3-4 years behind other browsers in terms of features.

If this is a upstream bug, of course file it to Monaco and/or VSCode repos.

**Comment by silverwind** [comment] 2024-06-11 11:30
Duplicate of https://github.com/go-gitea/gitea/issues/31252, using that issue because it has the actual error.

**Closed as not planned by silverwind** 2024-06-11 11:30 UTC
Labels: issue/not-a-bug
