### ISSUE TITLE
Visit /vendor/plugins/vue-calendar-heatmap/vue-calendar-heatmap.css panic

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#7183] opened 2019-06-12 01:54 UTC
When visit this file, it returned sucessfully. But it also will panic on logs. How macaron stop execution when hit a static file?
```
2019/06/12 09:49:16 Started GET /vendor/plugins/vue-calendar-heatmap/vue-calendar-heatmap.css for [::1]
2019/06/12 09:49:16 routers/repo/http.go:96:HTTP() [E] GetUserByName: user does not exist [uid: 0, name: vendor, keyid: 0]
	/Users/***/gopath/src/code.gitea.io/gitea/routers/repo/http.go:96 (0x1ef1a22)
		HTTP: ctx.NotFoundOrServerError("GetUserByName", models.IsErrUserNotExist, err)
	/Users/lunny/goroot/src/reflect/value.go:447 (0x1089410)
		Value.call: call(frametype, fn, args, uint32(frametype.size), uint32(retOffset))
	/Users/lunny/goroot/src/reflect/value.go:308 (0x1088e93)
		Value.Call: return v.call("Call", in)
	/Users/***/gopath/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:177 (0x156e486)
		(*injector).callInvoke: return reflect.ValueOf(f).Call(in), nil
	/Users/***/gopath/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:137 (0x156dd7b)
		(*injector).Invoke: return inj.callInvoke(f, t, t.NumIn())
```

**Comment by lunny** [comment] 2019-09-12 01:45
Panic is gone on , but it still try to get the repository by name. That means macaron will try another routes after match the static routes.

```
Started GET /vendor/plugins/vue-calendar-heatmap/vue-calendar-heatmap.css for [::1]
2019/09/12 09:43:12 ...les/public/public.go:135:handle() [I] [Macaron] [Static] Serving /vendor/plugins/vue-calendar-heatmap/vue-calendar-heatmap.css
2019/09/12 09:43:12 routers/repo/http.go:97:HTTP() [E] GetUserByName: user does not exist [uid: 0, name: vendor, keyid: 0]
2019/09/12 09:43:13 ...ers/routes/routes.go:105:func1() [I] Completed GET /vendor/plugins/vue-calendar-heatmap/vue-calendar-heatmap.css 304 Not Modified in 73.651786ms
```

**Comment by guillep2k** [comment] 2019-09-19 03:40
Can't reproduce in my server. Gitea Version: 1.10.0+dev-311-g8eaacbfdb 
```
[Macaron] 2019-09-19 00:38:13: Started GET /vendor/plugins/vue-calendar-heatmap/vue-calendar-heatmap.css for 172.30.254.2
[Macaron] [Static] Serving /vendor/plugins/vue-calendar-heatmap/vue-calendar-heatmap.css
[Macaron] 2019-09-19 00:38:13: Completed GET /vendor/plugins/vue-calendar-heatmap/vue-calendar-heatmap.css 304 Not Modified in 135.005M-BM-5s
```

**Comment by lafriks** [comment] 2019-09-24 21:25
I also can not sent to be able to reproduce this, closing as fixed, please reopen if you can reproduce this in latest dev version

**Closed as completed by lafriks** 2019-09-24 21:25 UTC
Labels: type/bug, issue/confirmed
