### ISSUE TITLE
Avatar caching doesn't work on Firefox

### ISSUE THREAD

**Issue by seadra** [go-gitea/gitea#16964] opened 2021-09-05 19:09 UTC
- Gitea version (or commit ref): 1.15.2
- Git version: 2.20.1
- Operating system: Debian
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes
  - [ ] No
- Log gist:

## Description

Avatar images aren't cached with Firefox, a new copy is always fetched on load.

On Chromium, it shows that avatar images are cached (in memory).

## Screenshots

On Firefox, after a refresh:

**Comment by wxiaoguang** [comment] 2021-09-06 03:09
What you saw in Firefox network log:

1. Firefox tried to get avatar from `try.gitea.io`
2. `try.gitea.io` response `302` to redirect to `gravatar.com` (a common avatar service)
3. Firefox request `gravatar.com` with local cache information
4. `gravatar.com` response `304` (Not Modified) to tell Firefox use local cache.

It seems there is no problem. If you believe you found a bug, just provide the expected behavior you thought it should be.

**Comment by lunny** [comment] 2021-09-06 03:14
Have you opened the option of firefox to `disable all cache`?

**Comment by seadra** [comment] 2021-09-06 05:20
Admittedly, I haven't carefully checked try.gitea.io, but this is a real issue on my private server. It's a Raspberry Pi and loading images take ~20 seconds on Firefox, so very noticeable without even checking any logs. No such issue on Chromium, images are loaded instantly.

`disable all cache` isn't enabled. Images other than avatar images are loaded from cache (like logo.svg). Images are cached on Github etc.

On Firefox, after a refresh:

![image](https://user-images.githubusercontent.com/9574367/132164450-577fb5f1-66fc-4ec2-831c-189e251fb3f7.png)

Same page, on Chromium, after a refresh:

![image](https://user-images.githubusercontent.com/9574367/132164366-296f3e9b-867c-4647-9328-7aed33897d8c.png)

**Comment by silverwind** [comment] 2021-09-06 07:20
The 302 from gitea is uncachable in such a case, we might be able to make it cachable by using 307 or 301.

<img width="1171" alt="image" src="https://user-images.githubusercontent.com/115237/132176211-9b235f87-928c-461a-8e2b-7854e224a5ee.png">

**Comment by wxiaoguang** [comment] 2021-09-06 07:33
`307` is very similar to `302` (except how to handle GET/POST methods), they all have cache control: https://stackoverflow.com/questions/12212839/how-long-is-a-302-redirect-saved-in-browser : It shouldn't be cached at all unless there's also a Cache-Control or Expires header returned by the web server. According to RFC 2616, section 10.3.3 302 Found.

And I do not think `301` is a correct way: https://stackoverflow.com/questions/9130422/how-long-do-browsers-cache-http-301s . The redirection may change: https://github.com/go-gitea/gitea/blob/main/routers/web/user/avatar.go#L76

From the screenshots that the author provided, I do not think there is a serious problem.

**Comment by silverwind** [comment] 2021-09-06 07:35
I meant 308, basically any "permanent" redirect should be cachable. Edited my comment above.

I think browser should honor caching headers fine on such redirects, so they should eventually invalidate.

**Comment by wxiaoguang** [comment] 2021-09-06 07:38
What's the difference between 301/308 and 302/307 if they both have cache control?

**Comment by silverwind** [comment] 2021-09-06 07:54
There's probably no difference, browsers should cache all status codes as long as cache-control headers are in place. We do not set any so the current 302 with no cache-control headers is uncachable. It might have been if it were a 301/308. I think we just need to set cache headers on redirect responses like we already do on self-hosted avatars.

**Comment by wxiaoguang** [comment] 2021-09-06 07:57
From the above information and my test (on try.gitea.io and my private server), I do not think this is a gitea problem.

And the author just deleted a comment containing screenshots of his private server, you can refer that (maybe some wrong configuration on the private server?)

**Comment by wxiaoguang** [comment] 2021-09-06 08:11
> There's probably no difference, browsers should cache all status codes as long as cache-control headers are in place. We do not set any so the current 302 with no cache-control headers is uncachable. It might have been if it were a 301/308. I think we just need to set cache headers on redirect responses like we already do on self-hosted avatars.

ps: if we add a cache control header in avatar's response to reduce browser requests and reduce gitea server/database load, it would be helpful in other ways. LOL.

**Comment by silverwind** [comment] 2021-09-06 08:17
Yes, I think it's good practice to always set cache-control on resourced. We can use time-based cache for avatar requests, e.g.

https://github.com/go-gitea/gitea/blob/0767fe0d806a36b5d23bc2714c740be93a6b18dc/modules/httpcache/httpcache.go#L34

**Comment by silverwind** [comment] 2021-09-06 16:44
Caching of Avatar requests certainly works in Firefox. What does not work is the caching of the redirected request in case the Avatar is hosted externally. I did add cache headers to those redirects in https://github.com/go-gitea/gitea/pull/16973 but Firefox just seems to ignore them. I think this is the best we can do, unless someone has another idea.

**Comment by 6543** [comment] 2021-09-06 21:06
#16973 got merged :rocket:

**Comment by silverwind** [comment] 2021-09-06 21:47
Can't figure out why Firefox would not cache those redirects, maybe it has something to do with their privacy protection, I'm not sure. Couldn't find anything on Bugzilla either.

It might be possible to directly render gravatar links without going through a redirect, but I think that method may not be possible for other federated avatar sources.

**Comment by wxiaoguang** [comment] 2021-09-07 04:58
If the cache doesn't work, maybe it is caused by `RUN_MODE` != 'prod'

https://github.com/go-gitea/gitea/blob/ab77a24f18ae45248bd6c71778fe3bfacacf864f/modules/httpcache/httpcache.go#L21

```
	if !setting.IsProd() {
		return "no-store"
	}
```

**Comment by silverwind** [comment] 2021-09-07 08:18
No, I am running `RUN_MODE = prod` in my development setup to to specifically allow cache testing.

**Comment by wxiaoguang** [comment] 2021-09-07 08:27
(I mean the original problem described in this issue)

**Comment by silverwind** [comment] 2021-09-07 08:36
Yeah I think we can close this. OP has deleted any helpful information and is probably not going to respond any more.

**Closed as completed by silverwind** 2021-09-07 08:36 UTC
