### ISSUE TITLE
Multidomain support

### ISSUE THREAD

**Issue by eleksir** [go-gitea/gitea#8697] opened 2019-10-26 14:21 UTC
UseCase:

I have 1 server with gitea, 2 isolated private domains (in different local nets) and one public domain. I'd like to expose gitea to all three domains correctly with correct links in web ui.

As a frontend server nginx is used.

With versions up to current master (Oct 26 2019) i cannot do it without nginx [sub module](https://nginx.org/en/docs/http/ngx_http_sub_module.html) but replacing strings in http response is dangerous thing as you know.

I'd like to see some simple setting in app.ini where i can put full list of domains to expose gitea to. Or if it is possible not to explicitly set domain name, to be able to expose gitea to any domain request comes to.

**Comment by silverwind** [comment] 2019-10-31 16:07
Ideally, we would get rid of domain name configuration entirely. All links exposed in the UI could be made relative paths and in case a full URL is needed, it can be obtained the `Host` header in the backend or `location.hostname` in JS.

Maybe have a config option for root directory in case someone wants to run gitea under a subdirectory (thought, such cases can and usually should be solved via URL rewrite in nginx).

**Comment by zeripath** [comment] 2019-11-01 00:10
So we definitely can't get rid of domain entirely as Git lfs requires a domain. It has to give back the full URLs over SSH and http.

URL rewriting can be a little bit temperamental I think there can be problems with JS Ajax requests but I guess those just have to be changed to use something that could be rewritten.

**Comment by eleksir** [comment] 2019-11-23 16:40
Well, i do not use git LFS, and in this case multi-domain should not be an issue. 

At least there can be choice: either you live with git-lfs and without multidomain or whithout git-lfs and with multidomain.

I think this choice is fair - not every user/admin of gitea requre git-lfs.
So, can we implement this choice as feature?

**Comment by silverwind** [comment] 2019-11-26 18:19
> Git lfs requires a domain. It has to give back the full URLs over SSH and http.

Would be no issue for HTTP, but SSH seems to have no concept of a `Host` header, a shame really.

**Comment by teotikalki** [comment] 2019-12-14 14:15
Possible duplicate of this: https://github.com/go-gitea/gitea/issues/6397

I found both of these threads while googling this issue today. I'm actually the original poster of the one I linked above in which I described the progress that I had had when I played with it last and the answer I got.

I would love it if there was progress on this... I just noticed that the internal URL wasn't the one I was connecting from (via my nginx reverse proxy). My alternative would be to rather needlessly set up multiple Gitea VMs which is orders of magnitude heavier than the ROOT_URL syntax working and having a few extra text characters in config plus whatever lines of code make it work.

**Comment by zeripath** [comment] 2019-12-15 00:35
So I think there's a way of doing this using values that are put in the request context but it's not ideal.

The idea would be to give different root URLs to different originating listeners or IPs. We would probably have to sort out the clear context handler and we would have expose the context throughout the request - but it could work although fiddly. 

It would be a lot of work to even check if this is feasible though.

**Comment by teotikalki** [comment] 2020-01-01 00:05
I have no knowledge of coding Go, but I've got a VM server, multiple domains that I can play with, and experience with Nginx reverse proxy. I'd be happy to set up a dedicated Gitea instance for testing.

**Closed as completed** 2022-04-13 01:52 UTC
Labels: type/proposal

**Comment by wxiaoguang** [comment] 2022-04-13 03:01
Related to
* https://github.com/go-gitea/gitea/issues/19345

**Comment by wxiaoguang** [comment] 2023-03-04 04:09
After https://github.com/go-gitea/gitea/issues/19345 , the "Multidomain support" is about 50%-70%.

* A correct main domain (ROOT_URL) is still necessary, because Gitea sends mails/notifications with no knowledge of "current domain"
* There are still incorrect usages of AppURL(ROOT_URL) in code, which should be cleaned one by one in the future.

**Comment by silverwind** [comment] 2023-03-04 13:54
Also

- The messages that are output during SSH git push require a "main domain" as well because the SSH protocol does not communicate which `Host` was used to connect.

**Comment by lunny** [comment] 2023-03-04 14:34
> Also
> 
>     * The messages that are output during SSH git push require a "main domain" as well because the SSH protocol does not communicate which `Host` was used to connect.

Yes, especially there are some TCP reverse proxies for SSH.
