### ISSUE TITLE
commits history page style error

### ISSUE THREAD

**Issue by ExplodingDragon** [go-gitea/gitea#25693] opened 2023-07-05 03:51 UTC
### Screenshots

![图片](https://github.com/go-gitea/gitea/assets/33776693/88c3090c-e22d-496a-abb7-c472ce9d03be)

### Gitea Version

3dbcbf7a1b

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

linux

### Browser Version

firefox last stable

**Comment by silverwind** [comment] 2023-07-05 06:37
Example https://try.gitea.io/silverwind/symlink-test/commits/branch/master.

Seems like a recent regression

**Comment by stuzer05** [comment] 2023-07-05 08:30
Can confirm this issue
![image](https://github.com/go-gitea/gitea/assets/23124682/3ea84222-5df1-4f14-90a0-2fdc73a0ecbd)

**Comment by wxiaoguang** [comment] 2023-07-05 13:22
Because the "fixed" class was removed by  https://github.com/go-gitea/gitea/pull/25634

Addeding the "fixed" back then the UI is right again.

![image](https://github.com/go-gitea/gitea/assets/2114189/1550c278-ff23-485a-8b09-ce74df9feb85)

**Comment by silverwind** [comment] 2023-07-05 15:36
@denyskon are you able to raise fix PR, and once merged, incorporate the change into https://github.com/go-gitea/gitea/pull/25689?

**Comment by denyskon** [comment] 2023-07-05 15:38
I will do it, give me an hour or so, not at home currently 🚉

**Closed as completed** 2023-07-06 21:07 UTC
Labels: type/bug, topic/ui, issue/regression, issue/confirmed
