### ISSUE TITLE
Error 500 when opening Repos, Issues, etc. after Upgrade to 1.15.3 on Docker

### ISSUE THREAD

**Issue by Snck3rs** [go-gitea/gitea#17190] opened 2021-09-30 08:14 UTC
### Gitea Version

1.15.3

### Git Version

2.30.2

### Operating System

Official Docker Image on Synology NAS

### How are you running Gitea?

Upgrade from 1.15.x (i'm not sure if 1.15.1 or 1.15.2). Running Gitea under Docker and updated it by pulling the latest image from docker hub - like the ones before.

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

After Upgrading Gitea i can't open repositories, issues and pull-requests any more. There's just an error 500.

In the Logs i found this:

2021/09/30 09:58:56 ...ers/web/user/home.go:438:buildIssueOverview() [E] userRepoIDs: ctxUser.GetAccessRepoIDs: skipObjectDecoder: expect object or null, error found in #0 byte of ...|&\003d{\003d}\003d|..., bigger context ...|&\003d{\003d}\003d|...

2021/09/30 09:58:56 Completed GET /issues 500 Internal Server Error in 13.969572ms

I'm using the official Docker Image, so i wonder if anybody else has this issue?

**Comment by techknowlogick** [comment] 2021-10-08 02:24
closing as dupe of https://github.com/go-gitea/gitea/issues/16961 there is directions on what to do there.

**Closed as completed by techknowlogick** 2021-10-08 02:24 UTC
