### ISSUE TITLE
Update from 1.14.1 to 1.15.0-rc "This pull request is broken due to missing fork information." after updating PR

### ISSUE THREAD

**Issue by JHenneberg** [go-gitea/gitea#16484] opened 2021-07-19 14:00 UTC
I am running gitea within a docker.

1. 1.14.1 create PR
2. update gitea to 1.15.0 
3. update branch which is already an PR
4. "This pull request is broken due to missing fork information."

Also branches with PRs created post gitea update have the same issue.

There were already similar problems (#11105, #11196) and I followed the suggested solution if possible but without success.

- Gitea version (or commit ref): 1.15.0-rc1
- Git version: 2.32.0
- Operating system: Debian 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No

**Comment by 6543** [comment] 2021-07-21 05:59
@JHenneberg we need logs gitea print out to specify the issue

**Comment by JHenneberg** [comment] 2021-07-21 07:19
Is there any easy way to sanitize the logs automatically?

**Comment by 6543** [comment] 2021-07-21 11:45
There is no ` ...[E]…` entry so gitea did not log an issue

**Comment by 6543** [comment] 2021-07-21 11:46
Does pushing an empty commit fix it?

**Comment by JHenneberg** [comment] 2021-07-21 12:11
> There is no ` ...[E]…` entry so gitea did not log an issue

I realised this two.

> Does pushing an empty commit fix it?

I did `git commit --allow-empty -m "Empty commit"`
Did not fix the problem

**Comment by zeripath** [comment] 2021-07-21 19:06
Is this docker?

**Comment by JHenneberg** [comment] 2021-07-22 07:07
> Is this docker?

Yes it it.

**Comment by zeripath** [comment] 2021-07-22 07:50
I bet this is an alpine 3.14 seccomp related issue.

**Comment by zeripath** [comment] 2021-07-22 08:03
See https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0

**Comment by zeripath** [comment] 2021-07-22 08:06
We're hopefully about to release RC2 where we've reverted back to 3.13 because of these issues.

As alpine 3.14 percolates through the docker ecosystem users are going to be forced to update their docker installations to take account of its requirements, however, it's not our intention to force our users to do that right now.

**Comment by sigma-schn** [comment] 2021-07-22 16:52
Updated installation to 1.15.0-rc2 (it's the same as @JHenneberg ones) and it worked again, thanks!

BTW: "latest" on Docker Hub points to 1.15.0-rc2, should be 1.14.5 ?

**Comment by zeripath** [comment] 2021-07-22 17:21
That is a long story you can search our issues db for things relating to that and look at #16421 

However, this problem is fixed therefore I'm closing and marking as a duplicate of #16428

**Closed as completed by zeripath** 2021-07-22 17:21 UTC
Labels: type/bug, issue/duplicate, issue/needs-feedback
