### ISSUE TITLE
[LDAP] Can't map LDAP groups to Gitea Orgs/Teams

### ISSUE THREAD

**Issue by drequivalent** [go-gitea/gitea#21159] opened 2022-09-13 17:13 UTC
### Description

Trying to join Gitea into FreeIPA's LDAP.

Users work fine, but then I need to map the LDAP user groups to Gitea teams in order to manage access in a more centralized way.

The settings are as follows:
![Снимок экрана от 2022-09-13 18-45-01](https://user-images.githubusercontent.com/1463277/189964003-4bf5b197-deb2-4a84-b1f2-1de3c73f116f.png)

```
Group Search Base DN: cn=groups,cn=accounts,dc=autogramma,dc=lan
Group Attribute Containing List Of Users: member
User Attribute Listed In Group: uid
Map LDAP groups to Organization teams: {"cn=developers,cn=groups,cn=accounts,dc=autogramma,dc=lan":{"Autogramma":["Developers"]},"cn=engineers,cn=groups,cn=accounts,dc=autogramma,dc=lan":{"Autogramma":["Engineers"]}}
```

Organization is present:
![Снимок экрана от 2022-09-13 20-10-21](https://user-images.githubusercontent.com/1463277/189964400-27b04709-2dc4-4418-aea5-5c26ea1527a2.png)

Teams as well:
![Снимок экрана от 2022-09-13 20-10-49](https://user-images.githubusercontent.com/1463277/189964525-58633a42-07c3-42ca-acb2-29c72b80c85f.png)

Updating external user information, though, is not joining anyone to any Teams.

What am I doing wrong?

### Gitea Version

1.17.2

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Gitea binary build

### Database

PostgreSQL

**Comment by kdumontnu** [comment] 2022-09-13 18:10
Is this a duplicate of https://github.com/go-gitea/gitea/issues/19555?

**Comment by drequivalent** [comment] 2022-09-13 18:23
If it's not supported, why is it present?

> Is this a duplicate of #19555?
> 
> In short, I don’t think this feature is supported.

No. The issue you referenced is about OIDC.

I'm talking about LDAP.

**Comment by drequivalent** [comment] 2022-09-13 20:19
The log doesn't mention `LDAP group sync:` in any way.

(I would publish it, but it contains personal data)

**Comment by drequivalent** [comment] 2022-09-13 20:33
Here's the abridged version:
```
сен 13 23:13:53 gitea gitea[12272]: 2022/09/13 23:13:53 [6320e481] router: started   POST /admin for 192.168.94.11:52480
сен 13 23:13:53 gitea gitea[12272]: 2022/09/13 23:13:53 ...ices/auth/session.go:47:SessionUser() [T] [6320e481] Session Authorization: Found user[2]
сен 13 23:13:53 gitea gitea[12272]: 2022/09/13 23:13:53 ...ices/auth/session.go:63:SessionUser() [T] [6320e481] Session Authorization: Logged in user 2:andrey.scherbakov
сен 13 23:13:53 gitea gitea[12272]: 2022/09/13 23:13:53 ...rvices/cron/tasks.go:141:GetTask() [I] [6320e481] Getting sync_external_users in &{{0 0} sync_external_users 0xc0037e63c0 0x1f9f600 finished  andrey.scherbakov 12}
сен 13 23:13:53 gitea gitea[12272]: 2022/09/13 23:13:53 ...ervices/auth/sync.go:17:SyncExternalUsers() [T] [6320e481-2] Doing: SyncExternalUsers
сен 13 23:13:53 gitea gitea[12272]: 2022/09/13 23:13:53 [6320e481] router: completed POST /admin for 192.168.94.11:52480, 303 See Other in 3.4ms @ admin/admin.go:141(admin.DashboardPost)
сен 13 23:13:53 gitea gitea[12272]: 2022/09/13 23:13:53 .../ldap/source_sync.go:24:Sync() [T] [6320e481-2] Doing: SyncExternalUsers[Autogramma]
сен 13 23:13:53 gitea gitea[12272]: 2022/09/13 23:13:53 ...dap/source_search.go:115:dial() [T] [6320e481-2] Dialing LDAP with security protocol (Unencrypted) without verifying: false
сен 13 23:13:53 gitea gitea[12272]: 2022/09/13 23:13:53 ...dap/source_search.go:490:SearchEntries() [T] [6320e481-2] Bound as BindDN uid=gitea,cn=users,cn=accounts,dc=autogramma,dc=lan
сен 13 23:13:53 gitea gitea[12272]: 2022/09/13 23:13:53 ...dap/source_search.go:508:SearchEntries() [T] [6320e481-2] Fetching attributes 'uid', 'givenName', 'sn', 'mail', 'ipaSshPubKey', '' with filter (&(memberOf=cn=git,cn=groups,cn=accounts,dc=autogramma,dc=lan)(objectClass=posixAccount)(uid=*)) and base cn=users,cn=accounts,dc=autogramma,dc=lan
сен 13 23:13:53 gitea gitea[12272]: 2022/09/13 23:13:53 ...dap/source_search.go:156:checkAdmin() [T] [6320e481-2] Checking admin with filter (memberOf=cn=admins,cn=groups,cn=accounts,dc=autogramma,dc=lan) and base uid=<USERNAME TRUNCATED>,cn=users,cn=accounts,dc=autogramma,dc=lan
сен 13 23:13:53 gitea gitea[12272]: 2022/09/13 23:13:53 ...dap/source_search.go:167:checkAdmin() [T] [6320e481-2] LDAP Admin Search found no matching entries.
сен 13 23:13:53 gitea gitea[12272]: 2022/09/13 23:13:53 ...dap/source_search.go:156:checkAdmin() [T] [6320e481-2] Checking admin with filter (memberOf=cn=admins,cn=groups,cn=accounts,dc=autogramma,dc=lan) and base uid=<USERNAME TRUNCATED>,cn=users,cn=accounts,dc=autogramma,dc=lan
--+more lines like this, one or two for each user--
сен 13 23:13:53 gitea gitea[12272]: 2022/09/13 23:13:53 [6320e481-3] router: started   GET /admin for 192.168.94.11:52482
сен 13 23:13:53 gitea gitea[12272]: 2022/09/13 23:13:53 ...s/context/context.go:219:HTML() [D] [6320e481-3] Template: admin/dashboard
сен 13 23:13:53 gitea gitea[12272]: 2022/09/13 23:13:53 [6320e481-3] router: completed GET /admin for 192.168.94.11:52482, 200 OK in 3.7ms @ admin/admin.go:126(admin.Dashboard)
сен 13 23:13:53 gitea gitea[12272]: 2022/09/13 23:13:53 ...s/asymkey/ssh_key.go:394:SynchronizePublicKeys() [T] [6320e481-2] synchronizePublicKeys[Autogramma]: Handling Public SSH Key synchronization for user alexander.volnov
сен 13 23:13:53 gitea gitea[12272]: 2022/09/13 23:13:53 ...s/asymkey/ssh_key.go:421:SynchronizePublicKeys() [T] [6320e481-2] synchronizePublicKeys[Autogramma]: Public Keys are already in sync for <USERNAME TRUNCATED> (Source:0/DB:0)
--+more lines like this, one for each user--
```

**Comment by 6543** [comment] 2022-09-13 22:35
@drequivalent `1.17.12` does not exist do you mean `1.17.2` ?

**Comment by drequivalent** [comment] 2022-09-13 22:39
> @drequivalent `1.17.12` does not exist do you mean `1.17.2` ?

Yes, of course. Sorry for typo.

**Comment by drequivalent** [comment] 2022-09-20 13:10
Please, help! I'm stuck!

**Comment by drequivalent** [comment] 2022-09-20 22:07
I have put `dn` into `User Attribute Listed In Group` instead of `uid`, as suggested by @svenseeberg in private correspondence.

This seems to have worked, and now I have the teams populated.

I think, this needs a better explanation in documentation.

Thanks, @svenseeberg, I really appreciate your help!

**Comment by dawivid** [comment] 2023-04-05 06:14
sorry, I am running v1.19 and authenticating against Active Directory server 2016

**Comment by svenseeberg** [comment] 2023-04-05 08:59
Can you look into your log files on your AD server and see if there are any problems with the queries? And can you provide examples of your group and user objects?

**Comment by dawivid** [comment] 2023-04-05 10:13
THanks for getting back to me Sven. The Event viewer shows no errors, only mentions that I am working currently over LDAP and it woiuld like to move to LDAPS.  When you say examples, what would you like to see? OUtput from ldapsearch, or Attribute editor or........?

**Comment by dawivid** [comment] 2023-04-05 10:57
In the meantime I will give you this output:

**Comment by dawivid** [comment] 2023-04-05 12:04
So, looking through this with chatGPT, it is telling me the problem is at the start of the search string [(&()...   

This empty bracket is the issue and I can't work out how to get it populated.

**Comment by dawivid** [comment] 2023-04-05 12:44
> > This empty bracket is the issue and I can't work out how to get it populated.
> 
> Looks like you're running into #23615

Indeed! However, when I populate the 'Verify Group Memebership in LDAP' it stops searching all together.


my version is 1.19.0 built with GNU Make 4.3, go1.20.2  . I will update the other issue though

**Closed as completed** 2023-09-05 17:18 UTC
Labels: type/docs
