### ISSUE TITLE
templates 给暴露出来可好?, 系统提醒邮件不能修改内容了. 

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#575] opened 2017-01-03 20:34 UTC
sorry, I not see English. 

 
1. Please speak English, this is the language everybody of us can speak and write.
2. Please ask questions or config/deploy problems on our Gitter channel: https://gitter.im/go-gitea/gitea
3. Please take a moment to search that an issue doesn't already exist.
4. Please give all relevant information below for bug reports, incomplete details will be handled as an invalid report.

**You MUST delete the content above including this line before posting, otherwise your issue will be invalid.**

- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

...

**Comment by lunny** [comment] 2017-01-04 01:08
Hi, first of all, Please write English so that your issue could be read by others.
About your problem, you could put your `templates` on `custom/` then it will replace the default templates.

**Comment by bkcsoft** [comment] 2017-01-06 00:38
@lunny Maybe we can open a issues-only repo for questions in chinese? and link chinese README to that :)

**Comment by bkcsoft** [comment] 2017-01-06 01:04
@lunny duplicate of #529 ?

**Comment by lunny** [comment] 2017-01-06 01:38
I think yes. So I close this one. Please go to #529 to continue.

**Closed as completed by lunny** 2017-01-06 01:38 UTC
Labels: issue/duplicate
