### ISSUE TITLE
issues with embedded images

### ISSUE THREAD

**Issue by l-jonas** [go-gitea/gitea#10506] opened 2020-02-27 15:49 UTC
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (<https://try.gitea.io/jonas-l/rechnen-android>)

## Description

It looks like two images without something in between are processed wrongly. In the linked case, a browser http basic auth dialog is shown. When scrolling down, then there is a row with one image and to the right of it, there is just the alternative text. The first image path is correctly <https://try.gitea.io/jonas-l/rechnen-android/media/branch/master/art/old-1.png>, the second one is <https://try.gitea.io/jonas-l/art/old-2.png> in the rendered version which does not work. In the source code, both are just relative urls:

```
![old config screen](./art/old-1.png)
![old training screen](./art/old-2.png)
```

...

## Screenshots

GitHub always rejected my screenshot uploads ...

**Comment by jolheiser** [comment] 2020-02-27 15:57
Duplicate of #10484

**Closed as completed by jolheiser** 2020-02-27 15:57 UTC
Labels: issue/duplicate
