### ISSUE TITLE
Linux 2.6.32-042stab127.2 - Starting gitea results in FATAL: kernel too old

### ISSUE THREAD

**Issue by maikgreubel** [go-gitea/gitea#6616] opened 2019-04-14 17:03 UTC
- Gitea version (1.7.5 or newer):
- Git version: 2.3.6
- Operating system: CentOS release 6.10 (Final)
- Database (use `[x]`):
  - [x] PostgreSQL 9.4.20
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Starting gitea version newer than 1.7.4 provides an error message "FATAL kernel too old" message. 

Version 1.7.4 starts and runs fine on my system (it's a virtual system, so kernel update is not possible):

```
$ file gitea
gitea: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, not stripped
```
Whereas 1.7.5 or newer does not start:

```
$ file gitea
gitea: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, for GNU/Linux 3.2.0, not stripped
```
 
## Screenshots

n/a

Current workarround is to rollback to 1.7.4, but because of security updates this is not a solution.

Do you plan to provide only binaries compatible with kernel 3.2 or newer?

**Comment by techknowlogick** [comment] 2019-04-14 19:06
Closing as duplicate of #4131 please continue discussion there.

**Closed as completed by techknowlogick** 2019-04-14 19:06 UTC
Labels: issue/duplicate
