### ISSUE TITLE
Unablte to use svg files als repo/organisation icon.

### ISSUE THREAD

**Issue by tuxmaster5000** [go-gitea/gitea#14990] opened 2021-03-14 08:02 UTC
- Gitea version (or commit ref):  1.13.4
- Git version:    2.18.4
- Operating system: CentOS7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ X] Yes (provide example URL)
  - [ ] No

When I try to use an svg file, only the error message:
`UploadAvatar: DecodeConfig: image: unknown format`
will shown.

**Comment by altinnadmin** [comment] 2021-08-02 10:40
Seems like a duplicate of #8707 ?

**Comment by tuxmaster5000** [comment] 2021-08-02 11:18
It looks  some think it, but another error code on an different function.
For me it looks like an general svg problem on gitea.

**Closed as completed** 2021-11-12 15:13 UTC
Labels: issue/duplicate, type/enhancement
