### ISSUE TITLE
Team Members Assignment on Issues

### ISSUE THREAD

**Issue by AaronS8** [go-gitea/gitea#18555] opened 2022-02-02 14:58 UTC
### Feature Description

I think it would be great if Gitea Enables Team members assigned on issues even if they have readonly permmission on issues,
I thought that was a bug but as @Gusted suggested on #18483 , I think it would be a good enhancement on gitea's team permssion area

**Comment by AaronS8** [comment] 2022-02-03 05:22
![ReadOnly](https://user-images.githubusercontent.com/98172519/152286012-fcd24773-d514-491e-8b26-61a645af53c9.jpg)
![readonly1](https://user-images.githubusercontent.com/98172519/152286016-95216b8e-a521-4ca8-b970-c2182d7a2a07.jpg)

**Comment by AaronS8** [comment] 2022-02-03 05:39
I think the team members should be listed even if they have a readonly access on issue, but they should be able to be assigned on issues since they have access on code.

**Comment by AaronS8** [comment] 2022-02-03 05:40
It would be great after the team is given a readonly permission on all areas but write permmission on the code unit, they should be list on assign users filter list.

**Comment by zeripath** [comment] 2022-02-03 09:17
> I think the team members should be listed even if they have a readonly access on issue, but they should be able to be assigned on issues since they have access on code.

I guess the problem is that we really need the assigned user to be able to close the issue/PR or merge the PR otherwise they're not really in control of that issue and someone else will need to do that for them.

---

If that could be resolved, or is perhaps not relevant then I actually think any collaborator or team member with issue/pull request read access should be assignable for an issue/pull request respectively. Either that or we create another pair of permissions assignable to Issues, assignable to pull requests.

**Comment by AaronS8** [comment] 2022-02-03 09:50
I think collabrorator should be abel to close and open issues, the readonly permission 
1. should limit them from editing comments other than theirs and making changes on the left side of the menu like Assigning, labeling
2. should limit them from editing on the projects created by other users.

**Comment by AaronS8** [comment] 2022-02-03 10:56
@zeripath found a bug on v1.17 and opened it on #18572, I think it's related to this in some ways

**Comment by lunny** [comment] 2022-03-01 04:33
Should be resolved by #18680

**Closed as completed by lunny** 2022-03-01 04:33 UTC
Labels: type/proposal
