### ISSUE TITLE
Wrong link to PR in user/org level project causes 404

### ISSUE THREAD

**Issue by nblock** [go-gitea/gitea#26272] opened 2023-08-01 13:39 UTC
### Description

The project view of user/org based projects also displays a link to PRs. The link to this PR does not include the path to the individual repository but consists only of the path `/pulls/$ID`. Clicking on this link causes a 404.

The link should point to: <https://gitea.example.com/org/repo/pulls/123> but it points to <https://gitea.example.com/pulls/123>.

### Gitea Version

1.20.2

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/131119/8a9d78d2-2751-42e1-96be-c145b59d1a21)

### Git Version

git version 2.39.2

### Operating System

Debian 12

### How are you running Gitea?

Official release supervised by systemd.

### Database

PostgreSQL

**Comment by delvh** [comment] 2023-08-01 13:41
Duplicate of #23318

**Closed as not planned by delvh** 2023-08-01 13:41 UTC
Labels: type/bug
