### ISSUE TITLE
Switch to Weblate for translations

### ISSUE THREAD

**Issue by balporig** [go-gitea/gitea#20309] opened 2022-07-10 17:59 UTC
### Feature Description

Weblate is free and opensource localization tool. The hosted version https://hosted.weblate.org/ is free for libre projects. It can also be selfhosted and it will make sense when gitea repo is moved to https://gitea.com/ from github

**Comment by delvh** [comment] 2022-07-10 18:09
(Partial) Duplicate of #17081

**Comment by throwawayaccountfor** [comment] 2022-12-24 10:45
+1

Surprised that Gitea used Crowdin!

**Comment by lafriks** [comment] 2023-01-31 23:06
Weblate imho is missing multiple features that we need:
* More granular permission system (allow to set proofreaders for each language that can approve translations)
* Translations should not be pushed back to git if proofreader has not approved them (WeblateOrg/weblate#3745)

Taking into account this I don't see how we could currently move gitea translation process to Weblate even through I like it and otherwise is great product.

I will close this issue currently but we can definitely revisit this issue once issues mentioned above have been implemented in Weblate

**Closed as not planned** 2023-01-31 23:08 UTC
Labels: type/proposal, type/upstream
