### ISSUE TITLE
Suggest adding a backup mode

### ISSUE THREAD

**Issue by kenyon-wong** [go-gitea/gitea#19084] opened 2022-03-14 17:00 UTC
### Feature Description

I would like to see a backup mode added to gitea.
That is, when syncing code from upstream repositories in mirror mode, it would filter operations like `git push force` to ensure that the source code of the local mirror is preserved when the author of the upstream repository deletes the repository due to political persecution or other reasons. I've come across other people with this need, so I hope you developers will consider my suggestion, and I'd appreciate it if you could.

Thank you for your help!

**Comment by techknowlogick** [comment] 2022-03-14 17:04
closing as dupe of https://github.com/go-gitea/gitea/issues/14076

**Closed as completed by techknowlogick** 2022-03-14 17:04 UTC
Labels: issue/duplicate
