### ISSUE TITLE
Don't include protected branches in recently pushed branches

### ISSUE THREAD

**Issue by jpraet** [go-gitea/gitea#31566] opened 2024-07-05 11:01 UTC
### Feature Description

Currently the recently pushed branches panel also shows protected release branches to which you have made a commit (e.g. merged a backport). It would be better if such branches were excluded.

### Screenshots

![image](https://github.com/go-gitea/gitea/assets/2212615/28c8930a-8e87-4089-b7bc-82b64791a6fe)

**Comment by wolfogre** [comment] 2024-08-01 02:56
👍  Yeah, I think it's a good idea. I have also been annoyed by such notices from release branches.

**Comment by lafriks** [comment] 2024-08-01 07:18
Duplicate of #28447

**Closed as completed** 2024-08-01 07:21 UTC
Labels: type/proposal
