### ISSUE TITLE
Can't copy attachment link when accessing gitea not over HTTPS

### ISSUE THREAD

**Issue by OddMorning** [go-gitea/gitea#26202] opened 2023-07-28 12:28 UTC
### Description

It's impossible to copy attachment link when accessing gitea over local network:

```
JavaScript error: Uncaught TypeError: Cannot read properties of undefined (reading 'writeText') (http://192.168.9.56:3000/assets/js/index.js?v=1.20.1 @ 54:4159).
```

It tries to copy text using `navigator.clipboard.writeText(x)` but `navigator.clipboard` is available only when url is either HTTPS or localhost.
There are workarounds for "insecure sources" such as `document.execCommand('copy')`.
Or probably checking `window.isSecureContext` (which is `true` for both HTTPS and localhost) and showing a proper error message would be also fine.

### Gitea Version

1.20.1

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![mstsc – 28 07 2023; 15 18 34](https://github.com/go-gitea/gitea/assets/12204657/fe1b7be7-5d51-4b71-84b4-530b80144e65)

### How are you running Gitea?

Running file `gitea-1.20.1-windows-4.0-amd64.exe`

### Database

None

**Comment by wxiaoguang** [comment] 2023-07-28 13:48
IIRC it has been fixed by "Re-allow clipboard copy on non-https sites #17118"

It might be a regression of "Use clippie module to copy to clipboard #23801" @silverwind

**Comment by silverwind** [comment] 2023-07-29 14:16
Sounds like a bug in https://github.com/silverwind/clippie, I will check.

**Comment by silverwind** [comment] 2023-07-29 14:47
Actually it was not a bug in clippie in this case, but a bare use of `navigator.clipboard.writeText`, which I've fixed. So the fix in clippie is just a fast-path to the fallback now, but I ponder whether to revert it.

**Closed as completed** 2023-07-29 22:56 UTC
Labels: type/bug
