### ISSUE TITLE
Add OpenID/OAuth2 Role Mappings

### ISSUE THREAD

**Issue by ispringle** [go-gitea/gitea#12493] opened 2020-08-15 13:43 UTC
## Description

I have my Gitea instance setup with OIDC and it works well. However at the moment anyone with an account in the realm Gitea accesses also has access to Gitea, regardless of their groups/roles/permissions. It's not a "break" for me as I don't mind providing Gitea access to all users, however I would like to be able to control it and especially control admin access or even organizational access from within my OIDC provider (keycloak in this case). 

A lot of clients that use OpenID/Oauth2 allow to create roles and role mappings so you can assign a user a role in the identity manager and they automatically receive that role in the client application. 

I am assuming that this would be a new feature request, as I haven't found this feature in Gitea, the docs, my web searching, or the code I've looked through thus far.

**Comment by Morriz** [comment] 2021-04-19 17:31
I believe this is a dupe of https://github.com/go-gitea/gitea/issues/10016

**Comment by lunny** [comment] 2021-04-19 23:51
Closed as duplicated.

**Closed as completed by lunny** 2021-04-19 23:51 UTC
Labels: issue/duplicate
