### ISSUE TITLE
Error 500 when closing already closed issue from pull request

### ISSUE THREAD

**Issue by giteaUser** [go-gitea/gitea#9695] opened 2020-01-10 17:46 UTC
- Gitea version (or commit ref): v1.11.0-rc1
- Git version: not relevant
- Operating system: not relevant
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Making a pull request referencing an issue with keyword "closes" on an already closed issue will return error page 500 when the pull request is merged.
...

**Comment by guillep2k** [comment] 2020-01-10 19:21
@giteaUser I'm unable to reproduce. Could you check you server logs in order to get the actual error message?

**Comment by guillep2k** [comment] 2020-01-10 19:34
> 
> 
> @giteaUser I'm unable to reproduce. Could you check you server logs in order to get the actual error message?~

Never mind. I could reproduce it. It happens when the issue will be closed by the PR and one of its commits.

**Comment by giteaUser** [comment] 2020-01-10 20:41
> Never mind. I could reproduce it. It happens when the issue will be closed by the PR and one of its commits.

Do you mean if the merge commit message also has the 'closes" reference? If so, the default merge commit was not touched: "Merge branch 'branchName' of test/test into master"

Here's the relevant trace log:

`
2020/01/10 11:32:40 routers/repo/pull.go:698:MergePullRequest() [E] Merge: Issue [1] 0 was already closed
2020/01/10 11:32:40 ...ervices/pull/pull.go:172:AddTestPullRequestTask() [T] AddTestPullRequestTask [head_repo_id: 1, head_branch: master]: finding pull requests
2020/01/10 11:32:40 ...s/context/context.go:138:HTML() [D] Template: status/500
2020/01/10 11:32:40 ...ervices/pull/pull.go:202:func1() [T] AddTestPullRequestTask [base_repo_id: 1, base_branch: master]: finding pull requests
2020/01/10 11:32:40 ...rvices/pull/check.go:146:manuallyMerged() [E] PullRequest[3].setMerged : Issue.changeStatus: Pull request [6] 0 was already closed
2020/01/10 11:32:40 ...rvices/pull/patch.go:123:TestPatch() [D] PullRequest[3]: Patch is empty - ignoring
`
it seems to be fine now with #9696, thanks a lot

**Closed as completed** 2020-01-11 01:20 UTC
Labels: type/bug, skip-changelog
