### ISSUE TITLE
Cant add Dependency to Ticket older than 9 Tickets 

### ISSUE THREAD

**Issue by peterscheu** [go-gitea/gitea#12093] opened 2020-06-30 08:00 UTC
- Gitea version (or commit ref): 1.12.1
- Operating system: Ubuntu Server
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
  - [x] Not relevant
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

In the Web Interface Ticket view it is impossible add a Dependeing Ticket to a Ticket older than 9 Tickets ago:
So you cant make Ticket 100 Depend on Ticket 80 because the selection only goes back to 90 

## Screenshots
![image](https://user-images.githubusercontent.com/32014756/86099675-1bb7ca80-bab8-11ea-9b3e-9111aada038e.png)
![image](https://user-images.githubusercontent.com/32014756/86099366-af3ccb80-bab7-11ea-86a9-691f5cb42c21.png)
![image](https://user-images.githubusercontent.com/32014756/86099413-bc59ba80-bab7-11ea-8da1-a4f125c637ee.png)

**Comment by 6543** [comment] 2020-09-20 21:31
@peterscheu the drop-down is also a search box (you can search issues by title)

**Comment by 6543** [comment] 2020-09-20 21:32
@peterscheu did this solve your problem?

**Comment by zeripath** [comment] 2021-06-21 20:30
OK this has been awaiting feed-back since September 2020 - therefore I'm going to close it. 

Please reopen if the problem is still evident.

**Closed as completed by zeripath** 2021-06-21 20:30 UTC
Labels: issue/needs-feedback
