### ISSUE TITLE
error to show wiki page

### ISSUE THREAD

**Issue by hisune** [go-gitea/gitea#11396] opened 2020-05-13 02:41 UTC
- Gitea version (or commit ref): 1.11.5
- Git version: 1.131.14.2
- Operating system: centos 6.9
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
The page shown as below:

template: repo/wiki/view:48:14: executing "repo/wiki/view" at <(not $.DisableHTTP) (and (not $.DisableSSH) (or $.IsSigned $.ExposeAnonSSH))>: can't give argument to non-function not $.DisableHTTP

**Comment by jolheiser** [comment] 2020-05-13 02:52
Duplicate of #10552

The problem comes from building Gitea 1.11.x (or presumably earlier versions as well) using Go 1.14 rather than 1.13 (or below)

This issue is fixed and will be included in Gitea 1.12+

**Closed as completed by jolheiser** 2020-05-13 02:52 UTC
Labels: issue/duplicate
