### ISSUE TITLE
smart mirroring git

### ISSUE THREAD

**Issue by Hemanthdev** [go-gitea/gitea#10329] opened 2020-02-18 06:26 UTC
How to enable the  smart mirroring on server to server for repositories?

Please find the image given below 
![image2016-2-2-12-55-43](https://user-images.githubusercontent.com/10198348/74709623-a4d70f00-5245-11ea-9e6c-16fee8c9764d.png)

**Comment by lunny** [comment] 2020-02-18 07:14
The image is great!!!

**Comment by Hemanthdev** [comment] 2020-02-18 07:18
> The image is great!!!

Do you have any solution for in gitea

**Comment by lunny** [comment] 2020-02-18 07:57
Isn't enough to mirror a repository from bitbucket to gitea instance?

**Comment by Hemanthdev** [comment] 2020-02-18 08:19
I don't want to mirror for bitbucket,


gitea to gitra mirroring

**Comment by a1012112796** [comment] 2020-02-18 08:20
Hello,here are my advice:
Although there are git platforms like github and gitea, please do not forget the nature of git distributed architecture.
Therefore, git server  should not be limited to only one common repository, but can be as many as you like. As long as using Webhooks or simple timing synchronization ensures that each common repository basically keeps the same content, it is ok.
the ISSUE systems systems  can exist independently of gitea because gitea supports external work order systems. and I think it is not necesssory to be a part of git server, you even can just do it by email list or other chat way.
thanks.

extern config in gitea：
![jtd](https://user-images.githubusercontent.com/25342410/74716890-5b4ceb00-526a-11ea-9820-5917bda0bbd2.jpg)

**Comment by lafriks** [comment] 2020-02-18 09:02
It's meant like to trigger mirroring on push?

**Comment by Hemanthdev** [comment] 2020-02-18 14:52
Yes

**Comment by alexanderadam** [comment] 2020-02-25 09:34
This looks like a duplicate of #3480 for me.
@Hemanthdev would one of the solutions in that issue solve your problem (i.e. [this](https://github.com/go-gitea/gitea/issues/3480#issuecomment-437298285) or [this](https://github.com/go-gitea/gitea/issues/3480#issuecomment-536990459))?

**Comment by Hemanthdev** [comment] 2020-02-26 06:52
thank you

**Closed as completed** 2020-02-26 06:52 UTC
Labels: type/proposal
