### ISSUE TITLE
Missing editor functions when creating Markdown file on all versions after 1.11.8

### ISSUE THREAD

**Issue by mcuix** [go-gitea/gitea#12166] opened 2020-07-06 17:40 UTC
- Gitea version (or commit ref):
- Git version: git version 2.17.1
- Operating system: Ubuntu 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When creating a  markdown file in version 1.12.1, the editor functions are missing. This affects all versions after 1.11.8

## Screenshots
**Its working in version 1.11.8**
![image](https://user-images.githubusercontent.com/20878779/86622560-5e017000-bfc0-11ea-9a03-c3d1a8c7157e.png)

**Missing in versions after 1.11.8**
![image](https://user-images.githubusercontent.com/20878779/86622080-93f22480-bfbf-11ea-8248-933bb56d64df.png)

**Comment by techknowlogick** [comment] 2020-07-06 17:48
Closing as dupe of #12064

**Closed as completed by techknowlogick** 2020-07-06 17:48 UTC
Labels: issue/duplicate
