### ISSUE TITLE
Synology DS211J Kernel too old on v1.10.0-rc1

### ISSUE THREAD

**Issue by Francky46** [go-gitea/gitea#8595] opened 2019-10-19 18:18 UTC
- Gitea version : gitea-1.10.0-rc1-linux-arm-5 / gitea-1.9.4-linux-arm-5
- Kernel version : 2.6.32.12
- CPU : Marvell Kirkwood 88F6281 (ARMv5 ?)
- OS : Linux DiskStation 2.6.32.12 #24922 Tue Apr 23 17:32:06 CST 2019 armv5tel GNU/Linux synology_88f6281_211j

## Description
After launching a wget to get the x version of gitea on my DS211J NAS, I did a chmod + x on the binary.
So I tried to launch the application in web mode (normal mode also) :

> ./gitea-1.10.0-rc1-linux-arm-5 web

but in return I have only these two lines:

> FATAL: kernel too old
> Aborted (core dumped)

As mentioned, I guess my kernel is so old ... but is there a stable release of gitea that can turn on my version of the kernel?

Thank you in advance !

**Comment by zeripath** [comment] 2019-10-20 22:20
The problem is golang requires a much newer kernel - "Linux/ARMv5 requires much newer kernels, at least v3.1 (for __kuser_cmpxchg64)." See https://github.com/golang/go/wiki/MinimumRequirements

This appears to be longstanding. 

Is there really no way of rebuilding the kernel? There may also be a Synology arm port of go.

You could try cross compiling a non static build and seeing if that works?

**Comment by Francky46** [comment] 2019-10-21 06:49
I found a solution a little more viable, and also economical in the long run.
I have a raspberry pi 3B +, which currently serves nothing.
I could use it to host Gitea, and mount the NAS in a folder. It's better than asking too much task to this little DS211J.

I found a tutorial here: https://gist.github.com/afragen/e34e4b902a71a5550e04cb1ba7e0d711 (thanks Afragen)

**Comment by zeripath** [comment] 2019-10-21 06:51
Excellent. Ok I'll close this issue.

**Closed as completed by zeripath** 2019-10-21 06:51 UTC
Labels: type/question
