### ISSUE TITLE
[BUG] "clear labels" - labels still activated

### ISSUE THREAD

**Issue by turbopixel** [go-gitea/gitea#12410] opened 2020-08-03 09:29 UTC
- Gitea version (or commit ref): 1.12.2
- Git version: -
- Operating system: Linux Ubuntu 18
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes, on a new created repository: https://gitea.com/turbopixel/test/issues/new
  - [ ] No
  - [ ] Not relevant
- Log gist: -

## Description
Selected labels still activated on the label popup.

Environment: _Windows 10 with Firefox 78.0.2_

## Screenshots

**1. I choose a few labels.**
![grafik](https://user-images.githubusercontent.com/15839724/89167354-9d00f200-d57b-11ea-8c33-a568ba9350b2.png)

![grafik](https://user-images.githubusercontent.com/15839724/89167378-a5592d00-d57b-11ea-98d9-9ac31a2cfb6a.png)

**2. Click on "clear labels"**
![grafik](https://user-images.githubusercontent.com/15839724/89167406-ae49fe80-d57b-11ea-85bf-bfff9ae96a5b.png)

allright:

![grafik](https://user-images.githubusercontent.com/15839724/89167447-b9049380-d57b-11ea-92fe-e2db694f39e2.png)

**3. Open the "Add label" popup:**

In the popup, the labels are still activated, although none are selected anymore.

![grafik](https://user-images.githubusercontent.com/15839724/89167481-c15cce80-d57b-11ea-9c54-fed77b93bfb0.png)

**Comment by turbopixel** [comment] 2020-10-04 10:03
is still valid

**Comment by KN4CK3R** [comment] 2021-06-21 11:35
Should be fixed. I can't reproduce it anymore.

**Closed as completed** 2021-06-23 22:50 UTC
Labels: type/bug, issue/needs-feedback
