### ISSUE TITLE
Error upgrading to latest gitea docker image

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#13459] opened 2020-11-07 17:40 UTC
- Gitea version (or commit ref):
- Git version:
- Operating system:
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ X] No
- Log gist:

```
2020/11/07 18:43:35 routers/init.go:72:initDBEngine() [I] Beginning ORM engine initialization.
        /go/src/code.gitea.io/gitea/routers/init.go:72 (0x2052ae1)
2020/11/07 18:43:35 routers/init.go:79:initDBEngine() [I] ORM engine initialization attempt #1/10...
        /go/src/code.gitea.io/gitea/routers/init.go:79 (0x2052bc6)
        /go/src/code.gitea.io/gitea/routers/init.go:177 (0x2053cb1)
        /go/src/code.gitea.io/gitea/cmd/web.go:162 (0x22aa928)
        /go/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/app.go:524 (0x16cf7bc)
        /go/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/command.go:173 (0x16d058d)
        /go/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/app.go:277 (0x16cd747)
        /go/src/code.gitea.io/gitea/main.go:111 (0x22e8e29)
        /usr/local/go/src/runtime/proc.go:204 (0x441b48)
        /usr/local/go/src/runtime/asm_amd64.s:1374 (0x477dc0)


2020/11/07 18:43:35 ...rm/session_schema.go:25:Ping() [I] PING DATABASE postgres
        /go/src/code.gitea.io/gitea/vendor/xorm.io/xorm/session_schema.go:25 (0xd7af11)
        /go/src/code.gitea.io/gitea/vendor/xorm.io/xorm/engine.go:302 (0xd45f48)
        /go/src/code.gitea.io/gitea/models/models.go:214 (0x1563b0d)
        /go/src/code.gitea.io/gitea/routers/init.go:80 (0x2052cbb)
        /go/src/code.gitea.io/gitea/routers/init.go:177 (0x2053cb1)
        /go/src/code.gitea.io/gitea/cmd/web.go:162 (0x22aa928)
        /go/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/app.go:524 (0x16cf7bc)
        /go/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/command.go:173 (0x16d058d)
        /go/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/app.go:277 (0x16cd747)
        /go/src/code.gitea.io/gitea/main.go:111 (0x22e8e29)
        /usr/local/go/src/runtime/proc.go:204 (0x441b48)
        /usr/local/go/src/runtime/asm_amd64.s:1374 (0x477dc0)


Downgrading database version from '159' to '158' is not supported and may result in loss of data integrity.
If you really know what you're doing, execute `UPDATE version SET version=158 WHERE id=1;`
2020/11/07 18:43:35 ...ations/migrations.go:334:Migrate() [F] Downgrading database version from '159' to '158' is not supported and may result in loss of data integrity.
        If you really know what you're doing, execute `UPDATE version SET version=158 WHERE id=1;`
Received signal 15; terminating.
```

## Description

After upgrading yesterday to latest tag of docker image, when trying to start the image it restarts contanstly. The log from the container itself is:

```
2020/11/06 19:05:10 ...dules/setting/log.go:343:newLogService() [I] Gitea Log Mode: File(File:info)
2020/11/06 19:05:10 ...les/setting/cache.go:70:newCacheService() [I] Cache Service Enabled
2020/11/06 19:05:10 ...les/setting/cache.go:81:newCacheService() [I] Last Commit Cache Service Enabled
2020/11/06 19:05:10 ...s/setting/session.go:63:newSessionService() [I] Session Service Enabled
2020/11/06 19:05:10 ...s/storage/storage.go:151:initAttachments() [I] Initialising Attachment storage with type:
2020/11/06 19:05:10 ...les/storage/local.go:44:NewLocalStorage() [I] Creating new Local Storage at /data/gitea/attachments
2020/11/06 19:05:10 ...s/storage/storage.go:145:initAvatars() [I] Initialising Avatar storage with type:
2020/11/06 19:05:10 ...les/storage/local.go:44:NewLocalStorage() [I] Creating new Local Storage at /data/gitea/avatars
2020/11/06 19:05:10 ...s/storage/storage.go:163:initRepoAvatars() [I] Initialising Repository Avatar storage with type:
2020/11/06 19:05:10 ...les/storage/local.go:44:NewLocalStorage() [I] Creating new Local Storage at /data/gitea/repo-avatars
2020/11/06 19:05:10 ...s/storage/storage.go:157:initLFS() [I] Initialising LFS storage with type:
2020/11/06 19:05:10 ...les/storage/local.go:44:NewLocalStorage() [I] Creating new Local Storage at /data/git/lfs
2020/11/06 19:05:11 routers/init.go:72:initDBEngine() [I] Beginning ORM engine initialization.
2020/11/06 19:05:11 routers/init.go:79:initDBEngine() [I] ORM engine initialization attempt #1/10...
2020/11/06 19:05:11 ...rm/session_schema.go:25:Ping() [I] PING DATABASE postgres
2020/11/06 19:05:11 ...m.io/xorm/core/db.go:286:afterProcess() [I] [SQL] SELECT tablename FROM pg_tables WHERE schemaname = $1 AND tablename = $2 [public version] - 3.678746ms
2020/11/06 19:05:11 ...m.io/xorm/core/db.go:286:afterProcess() [I] [SQL] SELECT column_name FROM INFORMATION_SCHEMA.COLUMNS WHERE table_schema = $1 AND table_name = $2 AND column_name = $3 [public version id] - 10.979709ms
2020/11/06 19:05:11 ...m.io/xorm/core/db.go:286:afterProcess() [I] [SQL] SELECT column_name FROM INFORMATION_SCHEMA.COLUMNS WHERE table_schema = $1 AND table_name = $2 AND column_name = $3 [public version version] - 5.090024ms
2020/11/06 19:05:11 ...m.io/xorm/core/db.go:286:afterProcess() [I] [SQL] SELECT "id", "version" FROM "version" WHERE "id"=$1 LIMIT 1 [1] - 1.33289ms
2020/11/06 19:05:11 ...ations/migrations.go:334:Migrate() [F] Downgrading database version from '159' to '158' is not supported and may result in loss of data integrity.
        If you really know what you're doing, execute `UPDATE version SET version=158 WHERE id=1;`
```

And it restart and go again.

**Comment by jolheiser** [comment] 2020-11-07 17:43
Duplicate of #13451

**Closed as completed by jolheiser** 2020-11-07 17:43 UTC
Labels: issue/duplicate
