### ISSUE TITLE
[Feature Request] Single user server for personal git server.

### ISSUE THREAD

**Issue by CRKatri** [go-gitea/gitea#16143] opened 2021-06-13 16:45 UTC
- Gitea version (or commit ref): 1.14.2
- Git version: 1:2.20.1-2+deb10u3
- Operating system: Debian 10, release binary run with systemd
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
  
I currently use cgit and gitolite for my personal git server, however I would like to use Gitea because of is built in issue tracker, but I don’t need multiple namespaces. It would be very useful for me if it was possible to run Gitea without users being able to create , and instead let admin accounts create repos globally, like https://gitea.com/tea.git instead of https://gitea.com/gitea/tea.git. And having the main page be the profile for an admin account so https://gitea.com/ would show the same thing as https://gitea.com/gitea/. Because a personal git server doesn’t need repos split by user because there is only one user. I understand this could require a large amount of changes, and may not be possible, but that is perfectly fine, this is only a suggestion after all.

**Comment by techknowlogick** [comment] 2021-06-13 18:15
closing as dupe of https://github.com/go-gitea/gitea/issues/11028

**Closed as completed by techknowlogick** 2021-06-13 18:15 UTC
Labels: issue/duplicate
