### ISSUE TITLE
Gitea as Package Registry Reverse Proxy

### ISSUE THREAD

**Issue by uvulpos** [go-gitea/gitea#23619] opened 2023-03-21 18:21 UTC
### Feature Description

As a team with plenty of fetches from external servers like dockerhub, composer or pip, especially now with the CI/CD pipelines, I would suggest adding an optional proxy for these package registries.

The huge advantage of this would be, that the build + delivery speed inside a company would improve, but also less international internet traffic would occur, if certain servers are e.x. only in one country given. 

A busy CI/CD pipeline could also try to prevent an external registry call and map it to itself to fetch the cached resource. But this should be a check and not checked by default imo 🤔  

I could imagine that a server administrator could either whitelist a couple of packages to do this, but also by giving it a limited amount of disk space, and he caches everything himself from registry xyz.

The urls could look like this:
```
http://my-domain/package-cache/<registryname>/<organization>/<package>

http://my-domain/package-cache/dockerhub/gitea/gitea

http://my-domain/package-cache/composer/phpmailer/phpmailer

http://my-domain/package-cache/ghcr/linuxserver/wikijs
```

What do you think? Could that be a feature for 1.20 or 1.21? 🤔

**Comment by KN4CK3R** [comment] 2023-03-21 18:52
Duplicate of #21223

**Closed as completed by KN4CK3R** 2023-03-21 18:52 UTC
Labels: issue/duplicate, type/proposal, type/feature, topic/packages
