### ISSUE TITLE
Could change issures's hyperlink based on local IP?

### ISSUE THREAD

**Issue by snow2zhou** [go-gitea/gitea#15965] opened 2021-05-24 03:55 UTC
- Gitea version (or commit ref):
- Git version: 1.14.2
- Operating system: Cent OS 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite

## Description
There are questions about links:
In the Issures menu: The hyperlink of issures is based on domain name IP (from App.conf),Could It changed by local IP（or url IP）?
Like 192.168.../.../issures/6 ?

## Screenshots
photos:
![图片](https://user-images.githubusercontent.com/44360310/119294536-450cb680-bc87-11eb-93e7-405e6fd7ab13.png)

![图片](https://user-images.githubusercontent.com/44360310/119294502-2c040580-bc87-11eb-99c2-0aace022d86c.png)

![图片](https://user-images.githubusercontent.com/44360310/119295063-7639b680-bc88-11eb-932d-d0b7fcad1002.png)

**Comment by noerw** [comment] 2021-05-24 12:25
Gitea currently does not have multi-domain support, closing as duplicate of #8697

**Closed as completed by noerw** 2021-05-24 12:25 UTC
Labels: issue/duplicate

**Comment by snow2zhou** [comment] 2021-05-25 03:39
In Gitea version 1.14.2 , the issures items's hypelink's  domain is different whith url 's  domain.
But in Gitea version 1.12 ,the issures items's hypelink's  domain is same whith url 's  domain.
So can keep the issures items's hypelink's  domain  same with url's  domain ?
As you see, the issures items's author's hypelink's domain is same with url's domain.

![图片](https://user-images.githubusercontent.com/44360310/119435904-b3b44780-bd4d-11eb-9d6f-ceadfe36807f.png)
