### ISSUE TITLE
Pull request search shows merged PRs in Open tab

### ISSUE THREAD

**Issue by otbutz** [go-gitea/gitea#30684] opened 2024-04-24 11:37 UTC
### Description

Searching for a PR lists merged pull requests in the tab `Open`. The count is correct though.

Reproducer:

https://try.gitea.io/otbutz99/test/pulls?state=open&q=Add

### Gitea Version

1.21.11

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![2024-04-24_13-31](https://github.com/go-gitea/gitea/assets/22315436/560acb94-cc7e-433c-b5d5-ab026d89d698)

### How are you running Gitea?

Github binary started via systemd behind a caddy reverse proxy.

### Database

PostgreSQL

**Comment by Zettat123** [comment] 2024-04-25 10:18
The results are correct when searching with no keywords. So I think the bug might be related to the issue indexer.
Can you try to rebuild issue indexer and check the results? 

<img src="https://github.com/go-gitea/gitea/assets/15528715/fd0b987b-4ba5-4863-aa3f-fbeacdd69670" width="300px" />

(It is in Site Administration > Monitoring > Cron Tasks)

**Comment by otbutz** [comment] 2024-04-25 11:06
> Can you try to rebuild issue indexer then check the search results?

Same result.

> So I think the bug might be related to the issue indexer.

I can reproduce it locally and on try.gitea.io.

**Comment by wolfogre** [comment] 2024-04-26 06:40
I have "Rebuild issue indexer" on try.gitea.io, the index has been fixed now.

This is not to say that bugs do not exist, but to help maintainers determine the cause of the problem.

This is a screenshot before I rebuilt the index.

<img width="674" alt="xnip_240426_140938" src="/attachments/2668bab2-8961-4547-8298-0134e664cde9">

**Comment by otbutz** [comment] 2024-04-26 07:19
@wolfogre thanks!  I tried to reproduce it again locally and things are now working as expected. Perhaps I was a bit impatient and refreshed before the task was actually finished. Either way, I can confirm that the cause is the outdated index.

**Closed as completed** 2024-05-08 14:45 UTC
Labels: type/bug, issue/confirmed
