### ISSUE TITLE
Character code recognition error

### ISSUE THREAD

**Issue by FalconWu2017** [go-gitea/gitea#9760] opened 2020-01-14 08:10 UTC
- Gitea version (or commit ref):1.10.2
- Git version:
- Operating system: Windows
- Database (use `[x]`): MySQL
At the beginning, I added some database script files to a Repository,These files are in Unicode encoding format,But gitea can't recognize these files and display them as binary files.    
![image](https://user-images.githubusercontent.com/34147999/72324753-99dd0c00-36e6-11ea-978a-801ce1d56299.png)     
I then regenerated these script files using ANSI encoding and push them as  a new commit,binary again.  
and then change something,push a new commit,it is OK, I can see the changes.   
![image](https://user-images.githubusercontent.com/34147999/72325344-df4e0900-36e7-11ea-9be1-6cfb47f7e962.png)  
And then I did some other tests.I found that the required file must be submitted in ANSI code and that the file must also be ANSI code in the previous submission。Unicode is not.

**Comment by bagasme** [comment] 2020-01-14 09:10
@FalconWu2017 Did you push your scripts or via `Upload file`?

**Comment by FalconWu2017** [comment] 2020-01-14 09:13
@bagasme Yes,I did.How can I see the commit in gitea without push anything?

**Comment by bagasme** [comment] 2020-01-14 09:22
@FalconWu2017 You have committed your change in your local repo on your workstation, but have not been pushed.

To view changes against your remote (in your case Gitea), after `git fetch origin`, invoke `git diff origin`.

**Comment by bagasme** [comment] 2020-01-15 07:18
Have you also checked file encoding of your script by `file -i`?

**Comment by FalconWu2017** [comment] 2020-01-15 07:25
How to do it? I don't understand what you said.

**Comment by bagasme** [comment] 2020-01-15 07:27
@FalconWu2017 Are your scripts encoded with UTF-8 or UTF-16 (any variations)?

**Comment by FalconWu2017** [comment] 2020-01-15 07:33
No,they aren't. I can only generate scripts in unicode or ANSI(GB2312(Simplified) ).There is not any way to generate in UTF-8.

**Comment by bagasme** [comment] 2020-01-15 08:03
@FalconWu2017 So did you mean UTF-16 encoding on your files?

**Comment by FalconWu2017** [comment] 2020-01-15 08:05
No, it's actually GB2312。

**Comment by FalconWu2017** [comment] 2020-01-15 08:12
e...I think you are right. Unicode is UTF-16.  @bagasme 
![image](https://user-images.githubusercontent.com/34147999/72416505-c0b44480-37b1-11ea-9505-f3adf4494017.png)

**Comment by lunny** [comment] 2020-01-15 10:58
I think the problem is UTF16 text files are recognized as binary files. When click `view file`, it works.

**Comment by lunny** [comment] 2020-01-15 11:33
ref: https://stackoverflow.com/questions/777949/can-i-make-git-recognize-a-utf-16-file-as-text

**Comment by yp05327** [comment] 2024-04-09 04:37
Tested in the latest version, it seems that this issue has been fixed.
see: https://gitea.com/yp05327/test/src/branch/main/aaa.txt
![image](https://github.com/go-gitea/gitea/assets/18380374/202fea7f-b5b6-4515-8aed-867033fa0ecd)

**Comment by yp05327** [comment] 2024-04-09 04:40
in this page, it works
https://gitea.com/yp05327/test/src/branch/main/aaa.txt
![image](https://github.com/go-gitea/gitea/assets/18380374/6c615747-bfb7-45ef-8bfb-ced3137f2ea8)

but in commit page, it doesn't work.
https://gitea.com/yp05327/test/commit/8b38cb8b34a713a66934cc4086e2839c4d5d99c1
![image](https://github.com/go-gitea/gitea/assets/18380374/2422a59d-0293-4bec-a7a9-ab1d2cd4f1ff)

**Comment by yp05327** [comment] 2024-04-09 05:01
In GH:
https://github.com/yp05327/test2/blob/main/aaa.txt
![image](https://github.com/go-gitea/gitea/assets/18380374/957fbbf5-b611-46d4-90a5-72a6089021bc)

https://github.com/yp05327/test2/commit/e5b0370c109be49036ff47c9354668471aa94100
![image](https://github.com/go-gitea/gitea/assets/18380374/c58667c0-9122-4d96-b409-11f8704301eb)

**Comment by lunny** [comment] 2024-04-09 06:27
Closed as it's at least better than GH now.

**Closed as completed by lunny** 2024-04-09 06:27 UTC
Labels: type/bug, status/blocked
