### ISSUE TITLE
Add support for LibreJS

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#7572] opened 2019-07-23 01:25 UTC
- Gitea version (or commit ref): 1.10.0+dev-67-ge0d6d2f97
- Git version: n/a
- Operating system: Deepin Manjaro
- Can you reproduce the bug at https://gitea.com:
  - [x] Yes (https://gitea.com/gitea/gitea_mirror)
  - [ ] No
  - [ ] Not relevant

## Description

I'm a user of IceCat Browser because I care about my privacy and security online. By default IceCat installs and runs LibreJS to avoid [The JavaScript Trap](https://www.gnu.org/philosophy/javascript-trap.html). When LibreJS is activated Gitea continues to function with a degraded experience which is great, but there's also this message which says Gitea works better with JS enabled and that can be remedied along with the JS trap if support for LibreJS were added.

https://www.gnu.org/software/librejs/

## Screenshots

![DeepinScreenshot_dde-desktop_20190723084515](https://user-images.githubusercontent.com/51995133/61675636-b9910a00-ad2b-11e9-9cef-6e925c294929.png)

**Comment by techknowlogick** [comment] 2019-07-23 01:41
Duplicate of #1524

**Closed as completed by techknowlogick** 2019-07-23 01:41 UTC
Labels: issue/duplicate
