### ISSUE TITLE
PR options disappears once unchecked. Can not enable Pull Requests again.

### ISSUE THREAD

**Issue by tna76874** [go-gitea/gitea#13359] opened 2020-10-30 14:39 UTC
- Gitea version (or commit ref):
- Git version: Gitea Version: 1.14.0+dev-106-g5b2096dd5
- Operating system: docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (--> just create repo and disable PR in options)
  - [ ] No
- Log gist:

## Description

1. Enter repository options
2. uncheck "Activate Pull requests"
3. Whole PR option area with all PR-related options are disappearing
4. **How to enable PR for repository again?**

## Screenshots

![missing_PR_options](https://user-images.githubusercontent.com/47271687/97718252-05e9fe80-1ac6-11eb-8de4-6ae4558f3dbc.jpg)

**Comment by jolheiser** [comment] 2020-10-30 14:45
I think this may be caused by #12808

Instead of checking if PRs _can_ be enabled, it now checks if PRs _are_ enabled. (assuming variables are named semantically)

https://github.com/go-gitea/gitea/blob/643a0a691a53a1c13a52edf0a09e8013394b07fe/templates/repo/settings/options.tmpl#L287

**Comment by zeripath** [comment] 2020-10-30 14:47
yup - this should be fixed in the same way as projects bit just above it.

https://github.com/go-gitea/gitea/blob/643a0a691a53a1c13a52edf0a09e8013394b07fe/templates/repo/settings/options.tmpl#L274-L281

**Comment by zeripath** [comment] 2020-10-30 14:49
I suspect that simply changing line 287 to:

```
{{if not .IsMirror}}
```
might actually be enough?

**Comment by zeripath** [comment] 2020-10-30 14:50
I'll add this change to #13360

**Closed as completed** 2020-10-30 16:27 UTC
