### ISSUE TITLE
Broken diff highlighting

### ISSUE THREAD

**Issue by superfaktura** [go-gitea/gitea#14641] opened 2021-02-11 09:21 UTC
- Gitea version (or commit ref): 1.13.2
- Git version: 2.26.2
- Operating system: Docker image
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL (Maria)
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/superfaktura/test/commit/fe8481fe92cc357bf158e387ec11a811dc1d9d21?style=split)
  - [ ] No
- Log gist:

## Description

Comment message with diacritics contains broken HTML formatting: `Event vytvorenia úhrady> an class="nx">nákladu.`
The comment changed from "Event vytvorenia nakladu." to "Event vytvorenia úhrady nákladu.".

**Comment by zeripath** [comment] 2021-02-11 18:39
This is a duplicate of #14231

**Closed as completed by zeripath** 2021-02-11 18:39 UTC
Labels: issue/duplicate
