### ISSUE TITLE
Message new Branch(es) are ready to be merged

### ISSUE THREAD

**Issue by uvulpos** [go-gitea/gitea#23743] opened 2023-03-27 09:32 UTC
### Feature Description

As a developer, I want the ability to create pull requests fast. Therefore, I create a branch and switch then to the UI to click the button create a pull request. To improve my workflow, I would appreciate it if there was a banner to quickly create Pull Requests, like there is on GitHub. 

**Notes:**
- these messages should only appear for really newly created Branches, e.x. 1 hour
- It is available on the main page of the code repository
- Example: ![Example Image](https://i.ytimg.com/vi/rgbCcBNZcdQ/maxresdefault.jpg)

**Comment by yardenshoham** [comment] 2023-03-27 10:23
Many people use git UIs without looking the command line output when pushing so I support this

**Comment by wxiaoguang** [comment] 2023-03-27 10:24
> Do you know Gitea will return a link to the git client, so you can just click the link to enter the process to create a pull request?

I never used that

**Comment by uvulpos** [comment] 2023-03-27 10:47
I have to agree with @yardenshoham, I got used to the VSC Git Integration since I was kinda forced by my team to use a similar workflow and I don't have any console output for that. Thats why I need a button to do this for me 🙂

**Comment by lunny** [comment] 2023-03-27 10:51
I'm not against this feature but just mentioned we have another one I used it frequently. I just sent a PR to improve the documentation. #23744

**Comment by delvh** [comment] 2023-03-27 11:45
Additionally, the problem with the existing feature is that it is **only triggered on the first commit**.
Oftentimes, you want to have multiple commits before creating a PR.

**Comment by jpraet** [comment] 2023-03-27 17:39
Duplicate of #13196. There is a draft PR #14003

**Comment by uvulpos** [comment] 2023-03-28 13:20
Oh, but at least we can make it alive again :)

**Comment by lunny** [comment] 2023-03-29 03:12
Let's keep this one since there more discuss here. And I copied the content from that issue for @kolaente 
> As a user, I would like to see a prompt on the home page or repository page to create a new PR if I recently pushed to a new branch for which no PR exists yet so that I save clicking on the "new PR" button on the repo page.

This could be done purely through the db without any git calls since we already have all the data in the action table.

I think we can always assume the user has the rights to create a PR if they have the right to push to a new branch in that repo, so no need to check that.
We would just need another check if the repo pushed to is a fork to check with the head repo if a PR exists there and not in the fork repo.

**Comment by kolaente** [comment] 2023-04-01 18:23
I've rebased and fixed a bunch of things in my PR https://github.com/go-gitea/gitea/pull/14003 - would appreciate a couple of eyeballs.

**Closed as completed** 2023-07-08 03:19 UTC
Labels: type/proposal, type/feature
