### ISSUE TITLE
Image diff has 0 width/height images

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#15920] opened 2021-05-18 20:15 UTC
Seems like image diff is currently broken, all images have inline styles with `width: 0; height: 0`. I think the JS calculations go wrong somewhere. Also, I think default view mode should be image diff. 

Example: https://try.gitea.io/silverwind/updates/commit/3d80fab2f8ee1d7bca1b7cff4f242461424866f8

cc: @KN4CK3R

**Comment by KN4CK3R** [comment] 2021-05-19 09:51
That's caused by the "file view toggle" from #14661 and already fixed in #14867. As 1.14.2 still works I would wait until the PR with the fix gets merged.

**Closed as completed** 2021-06-05 12:32 UTC
Labels: type/bug
