### ISSUE TITLE
Enable Multiline Comments for Code Reviews

### ISSUE THREAD

**Issue by uvulpos** [go-gitea/gitea#24681] opened 2023-05-12 09:39 UTC
### Feature Description

As a software developer and reviewer, I want to be able to select multiple lines of code before I can comment on them, so in the communication tab there is more context, like there is on GitHub.

### Screenshots

Feature on GitHub
<img width="600" alt="Screenshot 2023-05-12 at 11 38 37" src="https://github.com/go-gitea/gitea/assets/53957681/56a781f2-14d3-4ec6-b5bd-25ae1e6906a0">

**Comment by silverwind** [comment] 2023-05-12 09:42
I'd say this is closely related to code suggestions during review, so let's close it as a duplicate of  https://github.com/go-gitea/gitea/issues/14765

**Closed as not planned by silverwind** 2023-05-12 09:42 UTC
Labels: type/proposal, type/feature

**Comment by delvh** [comment] 2023-05-12 12:24
Actually, it's a duplicate of #12640 which is its own issue for a reason as it basically blocks #14765.
But yeah, the issue still exists nonetheless already.

**Comment by silverwind** [comment] 2023-05-12 12:39
Ah yes indeed. I guess those two features will be implemented together anyways.

**Comment by silverwind** [comment] 2023-05-12 12:53
Right, first the multiline comments, then extend with suggestions etc.
