### ISSUE TITLE
[Bug] Notifications remains after repository deletion

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#4416] opened 2018-07-10 20:56 UTC
- Gitea version (or commit ref): 3e445cc
- Git version: not relevant
- Operating system: not relevant
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

**Comment by cezar97** [comment] 2018-07-10 21:39
Duplicate of #3105?

**Comment by cezar97** [comment] 2018-07-26 14:19
@lunny if you could update the title in issue #3105 including all the repository notifications and not only of issues deleted, this can be closed as duplicate as they are nearly the same. Or you want them separated?

**Closed as completed** 2018-08-01 08:22 UTC
Labels: issue/duplicate
