### ISSUE TITLE
Last commit status in pull request lists are not shown

### ISSUE THREAD

**Issue by dschmidt** [go-gitea/gitea#8160] opened 2019-09-12 07:52 UTC
- Gitea version (or commit ref): v1.9.3 from Docker Image
- Git version: 
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

I updated from 1.8.1 to 1.9.3 because I wanted better status reporting for CI. The report underneath the PR itself works fine, but I see no trace of the feature  "Show last commit status in pull request lists" from PR #6465, which to my understanding should be included in 1.9.3, right?

I'm sorry to open a new issue, but commenting isn't possible anymore after the pull request was closed.

## Screenshots
Nothing to see really, the little dots are simply not there:
![Screenshot_list](https://user-images.githubusercontent.com/448487/64764509-81938f80-d542-11e9-8229-708fb53e3860.png)

Although the single PR view shows the status just fine:
![Screenshot_pr](https://user-images.githubusercontent.com/448487/64764591-a7b92f80-d542-11e9-986b-753dcc66b873.png)

**Comment by lunny** [comment] 2019-09-12 07:59
The CI status on PR list is not implemented yet I think. We need a PR to resolve that. I think it could be on v1.10.

**Comment by dschmidt** [comment] 2019-09-13 09:29
> I'm using Jenkins aswell, and it works for me in Gitea Version: 1.10.0+dev-232-gf1c414882.

Okay, that's good to know - I found setting up Jenkins quite wonky and was afraid it might be related to the plugin because it's not being maintained so well :)

> I may found the bug. When the base repository is the same as the head repository, then it works. If it's from a forked repository, it will not work.

Maybe several issues here? As you can see in my screenshot I'm also not using forks...

**Comment by dschmidt** [comment] 2019-09-13 09:35
> What version more specifically are you running?

As I said I'm using the 1.9.3 docker image, I assume it's built from the v1.9.3 tag.

**Comment by yzzyx** [comment] 2019-09-27 07:49
I finally got some time to look at this, but I didn't manange to reproduce it when building from HEAD, so I'll backtrack to 1.9.3, and check with the same steps there.

Have you managed to see any patterns in which PR's or commits that are missing the build status?

**Comment by dschmidt** [comment] 2019-09-27 07:54
Well, I'm afraid the pattern is "always". I have never seen those little dots in my installation so far, and I've been working with it since I posted this issue...

**Comment by MarkusAmshove** [comment] 2019-09-27 08:43
@dschmidt how many PRs are open in your repositories? Do they show up if you have a full page of PRs in the list?
We have the problem that they're off by some offset (showing on the wrong PR) and the some not having any dot. The pattern is also "always" I'm afraid  :-)

**Comment by dschmidt** [comment] 2019-09-27 09:12
Usually only one or two, I could possibly try with more... probably not this week anymore though.

**Comment by yzzyx** [comment] 2019-09-29 16:54
I found the cause of this, and the reason why I couldn't reproduce it in my tests - we were checking against the ID of the issue instead of the ID of the PR. These coincide as long as no issues exists. After the first issue is created, they will not match anymore.

I've also fixed the headRepo/baseRepo mismatch that lunny mentioned above.

**Comment by MarkusAmshove** [comment] 2019-09-29 18:06
> 
> 
> I found the cause of this, and the reason why I couldn't reproduce it in my tests - we were checking against the ID of the issue instead of the ID of the PR. These coincide as long as no issues exists. After the first issue is created, they will not match anymore.
> 
> I've also fixed the headRepo/baseRepo mismatch that lunny mentioned above.

Is this for the "not shown" issue or "off by some" issue? Because we don't use Gitea issues, just PRs ;-)

**Comment by yzzyx** [comment] 2019-09-29 18:14
@MarkusAmshove hopefully it will fix both cases.

**Comment by lunny** [comment] 2019-09-30 01:08
closed by #8316

**Closed as completed by lunny** 2019-09-30 01:08 UTC
Labels: type/bug
