### ISSUE TITLE
After Upgrade To 1.11 RC Gitea Stops After 1 Minute

### ISSUE THREAD

**Issue by jaqra** [go-gitea/gitea#9648] opened 2020-01-08 08:05 UTC
This is why stops:

```
2020/01/08 11:02:52 ...eue/queue_wrapped.go:69:setInternal() [W] [Attempt: 740] Failed to create queue: level for task cfg: {H:/gitea/data/H:/gitea/data/queues/task 1000 20 1 6 1s 5m0s 5 task-level} error: CreateFile H:/gitea/data/H:/gitea/data/queues/task: Dosya adı, dizin adı veya birim etiketi sözdizimi hatalı.
2020/01/08 11:02:52 ...eue/queue_wrapped.go:69:setInternal() [W] [Attempt: 10] Failed to create queue: level for  cfg: [123 34 65 100 100 114 101 115 115 101 115 34 58 34 34 44 34 66 97 116 99 104 76 101 110 103 116 104 34 58 50 48 44 34 66 108 111 99 107 84 105 109 101 111 117 116 34 58 49 48 48 48 48 48 48 48 48 48 44 34 66 111 111 115 116 84 105 109 101 111 117 116 34 58 51 48 48 48 48 48 48 48 48 48 48 48 44 34 66 111 111 115 116 87 111 114 107 101 114 115 34 58 53 44 34 68 66 73 110 100 101 120 34 58 48 44 34 68 97 116 97 68 105 114 34 58 34 72 58 47 103 105 116 101 97 47 100 97 116 97 47 72 58 47 103 105 116 101 97 47 100 97 116 97 47 113 117 101 117 101 115 47 105 115 115 117 101 95 105 110 100 101 120 101 114 34 44 34 77 97 120 87 111 114 107 101 114 115 34 58 49 48 44 34 78 97 109 101 34 58 34 105 115 115 117 101 95 105 110 100 101 120 101 114 34 44 34 78 101 116 119 111 114 107 34 58 34 34 44 34 80 97 115 115 119 111 114 100 34 58 34 34 44 34 81 117 101 117 101 76 101 110 103 116 104 34 58 50 48 44 34 81 117 101 117 101 78 97 109 101 34 58 34 105 115 115 117 101 95 105 110 100 101 120 101 114 95 113 117 101 117 101 34 44 34 87 111 114 107 101 114 115 34 58 49 125] error: CreateFile H:/gitea/data/H:/gitea/data/queues/issue_indexer: Dosya adı, dizin adı veya birim etiketi sözdizimi hatalı.
2020/01/08 11:02:52 ...eue/queue_wrapped.go:162:Run() [F] Unable to set the internal queue for -wrapper Error: Unable to create queue level for  with cfg [123 34 65 100 100 114 101 115 115 101 115 34 58 34 34 44 34 66 97 116 99 104 76 101 110 103 116 104 34 58 50 48 44 34 66 108 111 99 107 84 105 109 101 111 117 116 34 58 49 48 48 48 48 48 48 48 48 48 44 34 66 111 111 115 116 84 105 109 101 111 117 116 34 58 51 48 48 48 48 48 48 48 48 48 48 48 44 34 66 111 111 115 116 87 111 114 107 101 114 115 34 58 53 44 34 68 66 73 110 100 101 120 34 58 48 44 34 68 97 116 97 68 105 114 34 58 34 72 58 47 103 105 116 101 97 47 100 97 116 97 47 72 58 47 103 105 116 101 97 47 100 97 116 97 47 113 117 101 117 101 115 47 105 115 115 117 101 95 105 110 100 101 120 101 114 34 44 34 77 97 120 87 111 114 107 101 114 115 34 58 49 48 44 34 78 97 109 101 34 58 34 105 115 115 117 101 95 105 110 100 101 120 101 114 34 44 34 78 101 116 119 111 114 107 34 58 34 34 44 34 80 97 115 115 119 111 114 100 34 58 34 34 44 34 81 117 101 117 101 76 101 110 103 116 104 34 58 50 48 44 34 81 117 101 117 101 78 97 109 101 34 58 34 105 115 115 117 101 95 105 110 100 101 120 101 114 95 113 117 101 117 101 34 44 34 87 111 114 107 101 114 115 34 58 49 125] by max attempts: error: CreateFile H:/gitea/data/H:/gitea/data/queues/issue_indexer: Dosya adı, dizin adı veya birim etiketi sözdizimi hatalı.

```

**Comment by jaqra** [comment] 2020-01-08 08:22
When i set config as below it solved:

```ini
[queue.task]
DATADIR = queues/task/
```

**Comment by 6543** [comment] 2020-01-08 10:20
think this is caused by @zeripath 's  #9363 ?

**Comment by jaqra** [comment] 2020-01-08 10:22
Windows Server 2008 R2 Foundation
Working as Windows Service

Upgraded from: Gitea Version: 1.11.0+dev-494-gf88715e29

**Comment by jaqra** [comment] 2020-01-08 10:34
When also set this config solved problem

```ini
[queue.issue_indexer]
DATADIR = queues/issue_indexer/
```

The problem is that path combining wrong and result is `H:/gitea/data/H:/gitea/data/queues/issue_indexer`

**Comment by zeripath** [comment] 2020-01-08 12:15
Damn this is my fault need to use filepath.IsAbs not path.IsAbs

**Comment by 6543** [comment] 2020-01-08 12:38
the patch looks simple: https://github.com/go-gitea/gitea/pull/9651

In the first place it is a go-standad-lib issue

**Comment by sapk** [comment] 2020-01-08 14:31
Reopening it in the wait for a confirmation that it really fix the issue.

**Comment by zeripath** [comment] 2020-01-09 17:28
@jaqra would you be able to test the latest head? If only so we can close this as fixed.

**Comment by jaqra** [comment] 2020-01-09 18:13
@zeripath that is ok. its working without any queue configuration as expected 👍

**Closed as completed** 2020-01-09 18:14 UTC
Labels: type/bug, skip-changelog
