### ISSUE TITLE
workflow names instead of workflow file name

### ISSUE THREAD

**Issue by Sharaf5** [go-gitea/gitea#31458] opened 2024-06-21 23:40 UTC
### Description

Workflow names are part of wirkflow files that should replace file name
this behavior is missing in UI and workflows names are only listed by files

### Screenshots

![Screenshot_20240622_023627](https://github.com/go-gitea/gitea/assets/36330265/15bd2f3a-c0e6-4982-a62a-a33d2e43dee1)

![Screenshot_20240622_023826](https://github.com/go-gitea/gitea/assets/36330265/53668cd8-c2af-4e9d-9083-c5a972342f67)

### Gitea Version

1.22

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

dockerized

### Browser Version

Google Chrome: 126.0.6478.114 (Official Build)

**Comment by yp05327** [comment] 2024-06-24 01:07
IIRC, we already have a issue about this.

**Comment by silverwind** [comment] 2024-06-25 00:21
Duplicate of https://github.com/go-gitea/gitea/issues/25912.

**Closed as completed by silverwind** 2024-06-25 00:21 UTC
Labels: type/bug, topic/ui
