### ISSUE TITLE
Auto-merge empty notification in activity feed

### ISSUE THREAD

**Issue by henrygoodman** [go-gitea/gitea#28301] opened 2023-11-30 00:59 UTC
### Description

After  an auto-merge occurs, the notification on the activity feed appears however there is no descriptive text.

### Gitea Version

1.22.0+dev-326-gf65977df3

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

<img width="576" alt="image" src="https://github.com/go-gitea/gitea/assets/79623665/f0527adc-1c5a-4372-88b0-4e82a926a081">

### How are you running Gitea?

Run as systemd service

### Database

SQLite

**Comment by lunny** [comment] 2024-05-07 09:25
I cannot reproduce that on 1.22.0+rc1-78-g7d14dfcab7. Do you have custom templates?

**Comment by henrygoodman** [comment] 2024-05-07 10:21
Thanks for testing @lunny 
We are not using any custom template.

I have also not seen this bug again since the initial report, I would be happy to close this purely based on lack of reproducibility.

**Comment by lunny** [comment] 2024-05-07 14:09
Okay. Let's close it and feel free to reopen it when it occupies again.

**Closed as completed by lunny** 2024-05-07 14:09 UTC
Labels: type/bug
