### ISSUE TITLE
Weird comment field rendering on commenting source code

### ISSUE THREAD

**Issue by confusedsushi** [go-gitea/gitea#18391] opened 2022-01-24 19:21 UTC
### Gitea Version

1.16.0-rc1

### How are you running Gitea?

Pre-built Windows binary.

### Database

SQLite

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

In a pull request, when looking at a changed file in split view, adding a comment to a line of code renders the comment field weird.

**Comment by lafriks** [comment] 2022-01-24 19:41
can you add screenshot?

**Comment by confusedsushi** [comment] 2022-01-24 20:16
![image](https://user-images.githubusercontent.com/6968196/150857893-3e06e242-329b-4411-91fd-86b92c3df79e.png)

**Comment by mappu** [comment] 2022-01-25 01:20
Probable duplicate of #18320 ?

**Comment by lunny** [comment] 2022-01-25 02:09
Please clear the browser cache and try again.

**Comment by confusedsushi** [comment] 2022-01-25 10:23
> Please clear the browser cache and try again.

Already done. Did not solve the problem.

**Comment by confusedsushi** [comment] 2022-01-25 10:25
> Probable duplicate of #18320 ?

Not a duplicate. But kind of the same problem. In #18320 a similar issue was solved for the unified view. Here the problem is about the split view.

Here it seems an ``colspan="3"`` is missing from that one table cell, too.

**Comment by zeripath** [comment] 2022-01-25 10:58
yup - almost certainly. 

Fancy putting up the PR to fix?

**Closed as completed** 2022-01-25 12:18 UTC
Labels: type/bug, topic/ui
