### ISSUE TITLE
Cannot compare/create pr to the root repo from a fork

### ISSUE THREAD

**Issue by jkampich1411** [go-gitea/gitea#20233] opened 2022-07-04 19:56 UTC
### Description

I can compare branches in the fork, but as soon as I try to compare to the root repo, I get a HTTP500 error.
Even with the log level set to "debug" and the run mode set to "dev", the only log output i get is:

`.../web/repo/compare.go:538:ParseCompareInfo() [E] GetCompareInfo: exit status 128 - fatal: failed to read object 6103d84784ccd1968f25855bc74d70f4ffbb4621: Invalid argument`

### Gitea Version

1.16.8

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

git version 2.25.1

### Operating System

Linux xxxx 5.4.0-121-generic Ubuntu

### How are you running Gitea?

Self hosted on Ubuntu Server using systemd and the package downloaded from your Website

### Database

MySQL

**Comment by lunny** [comment] 2024-03-02 10:00
I cannot reproduce on the main branch now. So let's close it.

**Closed as completed by lunny** 2024-03-02 10:00 UTC
Labels: type/bug
