### ISSUE TITLE
Gitea/swag (nginx/fail2ban) not allowing pulls sometimes when using docker compose  

### ISSUE THREAD

**Issue by jessielw** [go-gitea/gitea#28448] opened 2023-12-12 21:16 UTC
### Description

Since `v1.21` I can no longer pull from my package repository. It just hangs there and in the logs it shows the below information. I have no issues pulling from a normal repository or pushing to either of them.

I changed nothing on my configuration other than updating gitea.

### Gitea Version

Current nightly build

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/jlw4049/80563ff5c54f578001cb32a0a6568421

### Git Version

nightly

### Operating System

Docker/UnRaid

### How are you running Gitea?

In docker on UnRaid

### Database

MySQL/MariaDB

**Comment by KN4CK3R** [comment] 2023-12-13 18:40
The client just hangs? There are 6 successfull requests to `/v2` and `/v2/token`. I don't see the responsibility of Gitea at the moment.

**Comment by jlw4049** [comment] 2023-12-13 19:32
That's what has me confused. I haven't changed anything at all. 
I just cleared my docker login.json once, re-logged into gitea was able to do 1 successful pull. Tried again and I'm getting errors on the client. 

```
Error response from daemon: Get "https://jessielw.com/v2/": dial tcp IP:443: connect: connection refused
root@bhds01-ubuntu-4gb:~/services/example# sudo docker compose -f docker-compose-prod.yml up
[+] Running 6/6
 ✘ celery_irc Error                                                                     0.1s
 ✘ create_databases Error                                                               0.1s
 ✘ start_log_rotator Error                                                              0.1s
 ✘ celery_worker Error                                                                  0.1s
 ✘ celery_beat Error                                                                    0.1s
Error response from daemon: Get "https://jessielw.com/v2/": dial tcp IP:443: connect: connection refused
root@bhds01-ubuntu-4gb:~/services/example# sudo micro docker-compose-prod.yml
root@bhds01-ubuntu-4gb:~/services/example# docker pull jessielw.com/jlw_4049/example:latest
Error response from daemon: Get "https://jessielw.com/v2/": dial tcp IP:443: connect: connection refused
root@bhds01-ubuntu-4gb:~/services/example# sudo docker pull jessielw.com/jlw_4049/example
:latest
Error response from daemon: Get "https://jessielw.com/v2/": dial tcp IP:443: connect: connection refused
```

I've tested this against 2 clients, but my config didn't change. It's been the same through out. 

I'm hosting my gitea from a server through nginx. I'm using a `subfolder` with a setup like so. Perhaps it's the cause, but I'm not sure why it would break all of a sudden after working for about 4 months since initial setup. 

```
## Version 2023/02/05
# make sure that your gitea container is named gitea
# make sure that gitea is set to work with the base url /gitea/
# The following parameters in /data/gitea/conf/app.ini should be edited to match your setup
# [server]
# SSH_DOMAIN       = example.com:2222
# ROOT_URL         = https://example.com/gitea/
# DOMAIN           = example.com

location /gitea {
    return 301 $scheme://$host/gitea/;
}

location ^~ /gitea/ {
    client_max_body_size 10G;
    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;
    set $upstream_app gitea;
    set $upstream_port 3000;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    rewrite /gitea(.*) $1 break;
}

# This forwards docker traffic to gitea
location /v2/ {
    client_max_body_size 10G;
    proxy_pass http://gitea:3000/v2/;
}
```

**Comment by KN4CK3R** [comment] 2023-12-13 19:37
> On the host, which doesn't come up EVERYTIME via gitea logs, I sometimes get this when trying to pull

That's ok because the `/v2` request is just a "is there a container registry" test which expects a 401 response.

Do you see follow up requests on nginx?

**Comment by jlw4049** [comment] 2023-12-13 20:51
So to reproduce the bug. I can just a normal docker site/jlw_4049/package:latest over and over again, works 100% of the time. However, when I try to run it in a `docker compose up` command, it will fail like the above errors I showed you after hanging. 

Once this happens I can no longer pull it with `docker pull` for quite some time. 

I will then get errors like this on the client `Error response from daemon: Get "https://jessielw.com/v2/": dial tcp IP:443: connect: connection refused`

Now on the nginx side of things when it fails, it does not appear to be in the `nginx` `access.log`. It appears that it never reaches it. 

I appreciate the responses so far!

**Comment by KN4CK3R** [comment] 2023-12-15 09:29
Great that you found the reason. The 6 requests are from the Docker client, Gitea just answers.

**Comment by jlw4049** [comment] 2023-12-15 18:10
Thanks, I'll adjust this title in case someone else comes across the same issues and close this. Thanks for the responses!

**Closed as completed by jlw4049** 2023-12-15 18:10 UTC
Labels: issue/needs-feedback, topic/packages
