### ISSUE TITLE
Using deploy key with write access, commits not counted

### ISSUE THREAD

**Issue by Exagone313** [go-gitea/gitea#5058] opened 2018-10-09 21:30 UTC
- Gitea version (or commit ref): 1.5.2
- Git version: 2.19.1
- Operating system: Arch Linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io: don't want to register :/
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist: irrelevant, nothing special?

## Steps to reproduce

* Set up a new SSH key as deploy key with write access to a repo (try with both an empty and non empty repo)
* Make one (or more) commit and push

## Expected result

* Nothing abnormal, it counts all the commits

## Actual result

* Commit count is off by one (or more)
* Files may **not** be shown (!) if there is no commit made by a real user, it'll show the initial *Quick Guide*

## Screenshots

![screen shot 2018-10-09 at 21 19 57-fullpage](https://user-images.githubusercontent.com/11819703/46699390-2c9c1a80-cc09-11e8-8845-cf4ad255c195.png)

**Comment by techknowlogick** [comment] 2018-10-09 21:31
Closing as duplicate of #4424

**Closed as completed by techknowlogick** 2018-10-09 21:31 UTC
Labels: issue/duplicate

**Comment by Exagone313** [comment] 2018-10-09 21:40
Ok, sorry, I didn't find this issue although I searched, but too many open issues.

**Comment by techknowlogick** [comment] 2018-10-09 21:51
@Exagone313 that's ok, the important thing is at least you searched.

**Comment by zeripath** [comment] 2019-02-04 21:46
This should be fixed by #5935 and its backport to v1.7 #5944

**Comment by Exagone313** [comment] 2019-02-04 22:37
I just had a quick look at the PR and I don't think it's going to fix actual repos. But maybe it just requires a new push or a new commit.

**Comment by zeripath** [comment] 2019-02-04 22:50
Those commits should prevent any further problems. In terms of fixing these repos - try pushing another commit and see if that solves it - if not I wonder if we should make an admin task that does an extreme cleanup.
