### ISSUE TITLE
Can't mirror projects from GH with topics >25 characters on Postgres

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#14125] opened 2020-12-23 12:43 UTC
- Gitea version (or commit ref): 1.13.0
- Git version:
- Operating system: Ubuntu
  
  
  
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

Problem mirroring some projects:

https://github.com/Computer-Kurzweil/computer_kurzweil.git
Migrate repository from https://github.com/Computer-Kurzweil/computer_kurzweil.git failed: pq: Wert zu lang für Typ character varying(25)

https://github.com/Computer-Kurzweil/diffusion-limited-aggregation.git
Migrate repository from https://github.com/Computer-Kurzweil/diffusion-limited-aggregation.git failed: pq: Wert zu lang für Typ character varying(25)

https://github.com/Computer-Kurzweil/mandelbrot.git
Migrate repository from https://github.com/Computer-Kurzweil/mandelbrot.git failed: pq: Wert zu lang für Typ character varying(25)

**Comment by zeripath** [comment] 2020-12-23 19:23
The problem is that these repositories all have topics >25 characters long.

**Comment by somera** [comment] 2020-12-23 19:42
> The problem is that these repositories all have topics >25 characters long.

Can I change the column size? Or should I wait for the fix?

**Comment by zeripath** [comment] 2020-12-23 19:56
I think changing the size in the db would work.

**Comment by michaelx** [comment] 2020-12-25 07:53
Duplicate of #14108.

**Closed as completed** 2020-12-25 12:50 UTC
Labels: issue/duplicate
