### ISSUE TITLE
Any events on webhook send twice

### ISSUE THREAD

**Issue by matrozov** [go-gitea/gitea#9183] opened 2019-11-27 11:20 UTC
- Gitea version (or commit ref): 1.11.0+dev-331-g055f6d229
- Git version: not needed
- Operating system: Docker container from gitea/gitea
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

I deployed gitea in my kubernetes from the docker image of gitea/gitea. I linked the webhook to the created repository and noticed that all events are fired twice (push, create / delete branch and tags, etc.). The pull-request event was triggered as many as 4 times per action, but there is a separate issue for this #9181. In the images below, I pushed a new brunch and received two push and brunch creation events each. Webhook has been configured in both "All Events" and "Push events" mode. In both cases, push events arrived twice, and in "All events" mode all events came twice.

## Screenshots

![1](https://user-images.githubusercontent.com/4449593/69719115-e19cd980-1120-11ea-8ca3-e1a9549ff258.PNG)
![2](https://user-images.githubusercontent.com/4449593/69719117-e3669d00-1120-11ea-956e-8bde54f608dc.PNG)
![3](https://user-images.githubusercontent.com/4449593/69719122-e497ca00-1120-11ea-9bf6-cb5ec17c8e1c.PNG)
![4](https://user-images.githubusercontent.com/4449593/69719124-e6618d80-1120-11ea-8ebe-ae167eaed19d.PNG)
![5](https://user-images.githubusercontent.com/4449593/69719129-e82b5100-1120-11ea-990b-0cc791d2ef05.PNG)

**Comment by lunny** [comment] 2019-11-27 15:22
Have you add webhooks on both repository webhook setting and orgnization webhook setting?

**Comment by matrozov** [comment] 2019-11-27 15:35
In the beginning, I used only the settings in the repository. Then, for the test, webhook was also added to the global settings, but this did not affect the double sending in any way. Duplicate notifications were from the start. Subsequent experiments with deleting, adding webhook, repositories and other types of events did not change the situation.

**Comment by lunny** [comment] 2019-11-28 01:26
I cannot reproduce this on my local instance. Could you reproduce this on try.gitea.io ?

**Comment by matrozov** [comment] 2019-11-28 07:53
Not. I tried, but on try.gitea.io I received only neighboring bugs # 9184, # 9181 and # 9180. I will try to deploy gitea on a separate host again today. Perhaps something is tied to the initial settings.

**Comment by matrozov** [comment] 2019-11-28 09:41
I received confirmation that the duplication of webhook depends on the installation configuration. I deployed on the local machine about 10 times and got different results depending on whether I redefined the parameters through ENV. In my product version in kubernetes, where I initially received an error, I also deployed with parameters predefined via ENV.

I attach my docker-compose.yaml file, as well as the resulting app.ini. At the installation stage, I only specify ssh_domain and administrator settings. As far as I could understand, if you do not pass EMV when deploying, then gitea does not duplicate webhook. I did not have enough time to figure out more specifically which parameter in the deployment leads to such an error. I hope you can repeat my experiment.

[test3.zip](https://github.com/go-gitea/gitea/files/3900932/test3.zip)

**Comment by stklcode** [comment] 2019-12-15 11:36
I experience the same issue. Every webhook (types "Slack" and "Gitea" in use, all added at repository level) is triggered twice when pushing from Git client (SSH or HTTPS). As far as I can tell, it happens on any repository.
Same JSON body (except for the timestamp +/- 1 second), same event-header, different delivery-header.

I'm running two separate instances. Both same version and about the same configuration, updated regularily since 1.1 or 1.2. Sadly I cannot remember when it started.

**Working instance:**
Version: 1.10.1
Platform: Linux, amd64 (Debian Buster, Kernel 4.19)
Deployment: Docker Stack (official Image `gitea/gitea:1.10`, only USER_UID, USER_GID env)
DB: MySQL (MariaDB 10.3)
Configuration: <details><summary>app.ini</summary>
<pre>APP_NAME = git @ otherdomain.example.com
RUN_USER = git
RUN_MODE = prod

[database]
DB_TYPE  = mysql
HOST     = /var/run/mysqld/mysqld.sock
NAME     = gitea
USER     = gitea
PASSWD   = ***
SSL_MODE = disable
PATH     = data/gitea.db

[repository]
ROOT = /opt/gitea/repo

[server]
SSH_DOMAIN       = otherdomain.example.com
PROTOCOL         = http
HTTP_ADDR        = 127.0.0.1
HTTP_PORT        = 3000
ROOT_URL         = https://otherdomain.example.com/git/
DISABLE_SSH      = false
DISABLE_HTTP_GIT = true
SSH_PORT         = 2222
SSH_LISTEN_PORT  = 2222
START_SSH_SERVER = true
OFFLINE_MODE     = true
LANDING_PAGE     = explore

[mailer]
ENABLED = false

[service]
REGISTER_EMAIL_CONFIRM = false
ENABLE_NOTIFY_MAIL     = true
DISABLE_REGISTRATION   = false
ENABLE_CAPTCHA         = false
REQUIRE_SIGNIN_VIEW    = false

[picture]
DISABLE_GRAVATAR        = true
ENABLE_FEDERATED_AVATAR = false

[session]
PROVIDER      = file
COOKIE_SECURE = true
COOKIE_NAME   = git_session

[log]
MODE      = file
LEVEL     = Info
ROOT_PATH = /opt/gitea/log

[security]
INSTALL_LOCK   = true
SECRET_KEY     = ***
INTERNAL_TOKEN = ***

[other]
SHOW_FOOTER_BRANDING           = false
SHOW_FOOTER_VERSION            = false
SHOW_FOOTER_TEMPLATE_LOAD_TIME = false</pre>
</details>

**Faulty instance:**
Version: 1.10.1
Platform: Linux, amd64  (Debian Stretch, Kernel 3.16)
DB: MySQL (MariaDB 10.1)
Deployment: Direct setup (Downloaded from https://dl.gitea.io)
Configuration: <details><summary>app.ini</summary>
<pre>APP_NAME = git @ mydomain.example.com
RUN_USER = git
RUN_MODE = prod

[database]
DB_TYPE  = mysql
HOST     = /var/run/mysqld/mysqld.sock
NAME     = gitea
USER     = gitea
PASSWD   = ***
SSL_MODE = disable
PATH     = data/gitea.db

[repository]
ROOT = /opt/gitea/repo

[server]
SSH_DOMAIN             = git.mydomain.example.com
PROTOCOL               = unix
HTTP_ADDR              = /opt/gitea/gitea.sock
HTTP_PORT              = 3000
UNIX_SOCKET_PERMISSION = 666
ROOT_URL               = https://git.mydomain.example.com/
DISABLE_SSH            = false
DISABLE_HTTP_GIT       = true
SSH_PORT               = 2222
SSH_LISTEN_PORT        = 2222
START_SSH_SERVER       = true
OFFLINE_MODE           = true
LANDING_PAGE           = explore

[mailer]
ENABLED = true
HOST    = mail.example.com:587
FROM    = "Git" <git@example.com>
USER    = git@example.com
PASSWD  = ***

[service]
REGISTER_EMAIL_CONFIRM = false
ENABLE_NOTIFY_MAIL     = true
DISABLE_REGISTRATION   = true
ENABLE_CAPTCHA         = false
REQUIRE_SIGNIN_VIEW    = false

[picture]
DISABLE_GRAVATAR        = true
ENABLE_FEDERATED_AVATAR = false

[session]
PROVIDER      = file
COOKIE_SECURE = true
COOKIE_NAME   = git_session

[log]
MODE      = file
LEVEL     = Info
ROOT_PATH = /opt/gitea/log

[security]
INSTALL_LOCK       = true
SECRET_KEY         = ***
INTERNAL_TOKEN     = ***
IMPORT_LOCAL_PATHS = false

[other]
SHOW_FOOTER_BRANDING           = false
SHOW_FOOTER_VERSION            = false
SHOW_FOOTER_TEMPLATE_LOAD_TIME = false

[oauth2]
JWT_SECRET = ***
</pre></details>

**Comment by stklcode** [comment] 2019-12-17 19:09
I've done some additional testing on the first of the above instances.

Two repositories (real world, no test dummies), both 1 Slack webhook and 1 Gitea webhook. Same configuration, same owner, same commit (dummy file on new temp-branch).

One repository (the slightly older one) behaves correcly, the other triggers twice. Both logs (Trace level) attached:
https://gist.github.com/stklcode/0e09e79033173413d55b9f800916a7e3

I cannot debug in that instance, as it is live and prod, but I had a look into the code.
`DeliverHooks()` iterates over undelivered tasks twice. For some reason the hooks appear in both selects, i.e. they are either places placed twice in the DB before or not marked as delivered.
_deliver.go_ in master: https://github.com/go-gitea/gitea/blob/2b0e4e0cb8b3e7fcc9b4493294567a060a27d299/modules/webhook/deliver.go#L152

_webhooks.go_ in v1.10: https://github.com/go-gitea/gitea/blob/f0f48e0fff7711401c95082c461309f1dcec4c61/models/webhook.go#L930

**Comment by lunny** [comment] 2019-12-18 02:41
I take a look at two implementation on master and v1.10. It's the same.

**Comment by stklcode** [comment] 2020-01-03 13:41
I've updated from 1.10.1 to 1.10.2 today. No change.

However by chance I've found the origin of the bug, because I have migrated my Gitea to a different directory structure and had to re-synchronize all hook scripts.

Apparently there are 2 identical hook files for pre- and post-receive phase, one named _gitea_ (the correct one) and one named like the phase.
```
<repo>/hooks/
 |- pre-receive.d/
 |-- gitea
 |-- pre-receive
 |- post-receive.d/
 |-- gitea
 |-- post-receive
```
(not for _update_)

Last modification of the "wrong" scripts is somewhere back in 2017, the _gitea_ scripts are modified today (I've triggered the "synchronize ... hooks for all repositories" task).

So the hook is really triggered twice externally.

**Comment by lunny** [comment] 2020-01-03 14:26
`pre-receive.d/gitea` is managed by gitea internal. `pre-receive.d/pre-receive` could be changed on gitea UI if you have enough permission.

**Comment by stklcode** [comment] 2020-01-03 21:10
I know. Content was exactly the same for all affected repos and I‘m pretty sure I never configured this and none of the collaborators knew the binary/config paths... 🤔

**Comment by lunny** [comment] 2020-01-04 02:06
If the content in `pre-receive.d/pre-receive` is the same as which in `pre-receive.d/gitea`.

**Comment by theAkito** [comment] 2020-02-02 00:32
> However by chance I've found the origin of the bug, because I have migrated my Gitea to a different directory structure and had to re-synchronize all hook scripts.

Same here and same issue.
This bug is 100% confirmed.

My Drone is going crazy and begging for mercy...

**Comment by zeripath** [comment] 2020-02-02 04:34
Then you need to remove these unnecessary duplicated hooks.

Do you have any idea how they ended up being there? When did you start using Gitea?

**Comment by theAkito** [comment] 2020-02-02 15:02
@zeripath 

> Then you need to remove these unnecessary duplicated hooks.

How do I do that automatically? I certainly can't do it manually as this would take hours. What file's content do I have to compare to which other file's one? Is the naming and pathing consistent? Is maybe another method more useful?

In my situation I had to do something like [this](https://discourse.gitea.io/t/reset-pre-receive-hooks/1865), urgently, which could've caused additional issues, but I can at least push now and the double hooks are a smaller problem than the one described in this thread.
(Problem started after Gitea migration with overhaul of the directory structure, as described by @stklcode.)

> When did you start using Gitea?

I think it was shortly after 1.0, don't remember really.

**Comment by zeripath** [comment] 2020-02-02 23:15
Ok, so it's a longstanding migration issue from that point in time. Sorry about that - ok here's how you remove those double hooks:

```bash
cd gitea-repositories
for i in */*.git/hooks; do
     if test -e "$i/pre-receive.d/pre-receive"; then
        diff "$i/pre-receive.d/pre-receive" "$i/pre-receive.d/gitea" > /dev/null && rm "$i/pre-receive.d/pre-receive"
    fi
done
```
And similarly for update and post-receive.

(Or something like that. Please be aware I'm writing bash on my phone in bed - stick echos in front of those rms before you run it.)

**Comment by theAkito** [comment] 2020-02-02 23:38
@zeripath 

Thanks for your help. From what I understand, this issue needs a general fix i.e. pull request, anyway?

**Comment by zeripath** [comment] 2020-02-03 08:11
I don't think this needs a PR - there's no current bug and the situation cannot occur in new repositories or on new installs. This is a migration issue from early Gitea.

We just need to delete the duplicate hooks. Unless we can see that the problem comes back...

(Likely some migration script failed for you a number of years ago, which one I don't know.)

**Comment by theAkito** [comment] 2020-02-03 13:06
> (Likely some migration script failed for you a number of years ago, which one I don't know.)

I never really "migrated" in the classic sense, except recently, when the sleeping error woke up.
When I checked the contents of the hooks, I saw some old directories I deprecated over a year ago. Since then I had _Resynchronize pre-receive, update and post-receive hooks of all repositories._ run a couple of times. Apparently, it doesn't seem to have helped, at least with the remains of an older version of the installation.

So are all Gitea native hooks now saved as `/pre-receive.d/gitea`? Then this issue should not occur on newer installations, as you said, though maybe there should be an additional step in the [FAQ/Troubleshooting section](https://docs.gitea.io/en-us/faq/) that explains this situation and its one-time fix to users of an older version that are maybe unaware of the issue.

**Comment by zeripath** [comment] 2020-02-03 23:04
You're correct that they're all saved as pre-receive.d/gitea etc.

The code is here:

https://github.com/go-gitea/gitea/blob/d92781bf941972761177ac9e07441f8893758fd3/modules/repository/hooks.go#L26-L70

Prior to that it was here: 

https://github.com/go-gitea/gitea/blob/27c6b8fc07eab2dd579b94cd92136738ace61706/models/repo.go#L919-L963

With the name being gitea since at #1006 when the directories were created. So I don't know where you picked up the pre-receive etc copies as they shouldn't have been put there by Gitea.

**Comment by theAkito** [comment] 2020-02-03 23:28
> So I don't know where you picked up the pre-receive etc copies as they shouldn't have been put there by Gitea.

🤷‍♀

**Comment by zeripath** [comment] 2020-02-04 22:53
Possibly there was some broken migration script?! Anyway have you managed to get rid of the things?

**Comment by theAkito** [comment] 2020-02-24 10:09
@zeripath 

 I ran https://github.com/go-gitea/gitea/issues/6636#issuecomment-590133526 and your https://github.com/go-gitea/gitea/issues/9183#issuecomment-581188712 but it did not change anything, as the scripts don't seem to find anything. I need to investigate that, as I assume, the solution should be pretty much like what was provided here.

**Closed as completed** 2020-02-26 23:05 UTC
Labels: type/question
