### ISSUE TITLE
Open Issue Counter becomes offset

### ISSUE THREAD

**Issue by alexander-zierhut** [go-gitea/gitea#11823] opened 2020-06-09 16:10 UTC
- Gitea version (or commit ref): 1.11.6 (I also had that in older versions)
- Git version: /
- Operating system: Ubuntu 18.04
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes: https://try.gitea.io/Alexzz/issue-confirm/issues
  - [ ] No
  - [ ] Not relevant
- Log gist: /

## Description
When closing issues using a commit message, for example `Changed some stuff Closes #1 Closes #2`, the open issue count does not change to portrait the new changes. This fixes itself when closing another issue manually using the webinterface. 

## Screenshots
| try.gitea.io  | Private installation  |  
|---|---|
| ![image](https://user-images.githubusercontent.com/26348781/84170886-71312680-aa7a-11ea-9426-aa7cf5c2c3c9.png) | ![image](https://user-images.githubusercontent.com/26348781/84170941-81490600-aa7a-11ea-8ef5-18f2d75a3602.png) |

**Comment by ALZlper** [comment] 2020-07-26 11:49
This still exists in the newest version I have updated to.

**Comment by iamdoubz** [comment] 2020-09-17 17:26
I have this issue in 1.12.4. But, if I close the issue with a pull request in the web interface, the number is not correct until I `restart the server` then the number is correct.

**Comment by warnat** [comment] 2020-09-17 19:20
There is a cron (?) job running every 24 hours, to correct that value. The function is called CheckRepoStats. 
In the Administration->Monitoring, there is a button for that: "Check all repository statistics".
I must admit, that I cannot find the root cause for the problem.

**Comment by Alexander-Zierhut** [comment] 2020-09-17 19:55
`There is a cron (?) job running every 24 hours, to correct that value` I was going to mention that as the server does not have to be restarted to fix this problem. It gets fixed after sometime.

**Comment by Alexander-Zierhut** [comment] 2020-09-18 10:10
` I cannot find the root cause for the problem.` @warnat Have you thought about a caching issue?

**Comment by warnat** [comment] 2020-09-18 18:31
there is someone working on.
see #10536

**Comment by zeripath** [comment] 2020-09-19 13:10
Duplicate of #10536

**Closed as completed by zeripath** 2020-09-19 13:10 UTC
Labels: issue/duplicate
