### ISSUE TITLE
Issue has only opened and closed status, what about testing status?

### ISSUE THREAD

**Issue by ivanvlaho** [go-gitea/gitea#20271] opened 2022-07-06 18:51 UTC
### Feature Description

Hi,

It would be very helpful if we could define more statuses for issue. Right now issue can be only in opened and closed status. 

Jira has many statuses for tickets and every status is connected to specific Kanban board. 

Currently if I put issue in closed status it is not automatically moved to Done board at Kanban project. 
Is this posible with some plugin?

**Comment by delvh** [comment] 2022-07-06 19:07
Related to and duplicate of both #14893 and #14359

**Closed as completed by delvh** 2022-07-06 19:07 UTC
Labels: type/proposal, type/feature
