### ISSUE TITLE
creating migration repo is synchronous?

### ISSUE THREAD

**Issue by tycho** [go-gitea/gitea#3800] opened 2018-04-15 15:09 UTC
- Gitea version (or commit ref): 1.4.0
- Git version: 2.17.0
- Operating system: 4.16.2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

Creating a migration repo marked as a mirror seems to be a synchronous action. The page has a loading spinner until the mirroring clone completes.

This should really be an async action done by the gitea daemon in the background.

**Comment by lafriks** [comment] 2018-04-19 11:47
Duplicate of #3770

**Closed as completed** 2018-04-19 11:47 UTC
Labels: issue/duplicate
