### ISSUE TITLE
 WARNING! Although there is a key with this ID in the database it does not verify this commit! This commit is SUSPICIOUS.

### ISSUE THREAD

**Issue by prologic** [go-gitea/gitea#16413] opened 2021-07-13 00:30 UTC
Hi 👋

Wondering if we can revisit a problem I've run into, which I'm quite sure is something I'm doing wrong!

Previous issues that are similar (_but different_): #2401 and #10420

In my case `$ git log -v -p --show-signature` shows a correct signature:

```#!sh
$ git log -v -p --show-signature
commit 02e2aebc49d793fa2100a3504cf8b991d4e384ac (HEAD -> master, origin/master)
gpg: Signature made Tue Jul 13 08:34:57 2021 AEST
gpg:                using RSA key C1F16643ADFF61B4A39EA3FEAC4C014F1440EBD6
gpg: Good signature from "James Mills (Public) <prologic@shortcircuit.net.au>" [ultimate]
Author: James Mills <prologic@shortcircuit.net.au>
Date:   Tue Jul 13 08:34:56 2021 +1000

    Remove Github workflows
```

And my Gitea server instance is running in UTC:

```#!sh
$ docker ps | grep gitea
f498ca1c4cc9   gitea/gitea:1.14.4                           "/usr/bin/entrypoint…"   2 days ago     Up 2 days     22/tcp, 3000/tcp         gitea_server.1.8ltljg9k4ah4phybh7qg7sbe5
$ docker exec -i -t f498ca1c4cc9 date
Tue Jul 13 00:27:38 UTC 2021
```

I'm running Gita 1.14.4 with a SQLite database (_although that probably means nothing here_).

I can see that basically we're falling thorugh this section of code:

https://github.com/go-gitea/gitea/blob/e0296b6a6de6450c474fdf7fe62635a05beb49ab/models/gpg_key.go#L609-L615

Though I don't yet fully understand what we're doing here (yet), been a while since I've worked with GPG using Go.

Any hints would be appreicated!

See: https://git.mills.io/prologic/tube/commit/02e2aebc49d793fa2100a3504cf8b991d4e384ac

<img width="1392" alt="Screen Shot 2021-07-13 at 10 29 32" src="https://user-images.githubusercontent.com/1290234/125371940-3dcf7280-e3c5-11eb-9954-d12bdf74ddfe.png">

**Comment by techknowlogick** [comment] 2021-07-13 00:41
closing as dupe of https://github.com/go-gitea/gitea/issues/16344

**Closed as completed by techknowlogick** 2021-07-13 00:41 UTC
Labels: issue/duplicate
