### ISSUE TITLE
Squash Merge will generate duplicate commit messages

### ISSUE THREAD

**Issue by ffbh123456** [go-gitea/gitea#13817] opened 2020-12-03 14:00 UTC
Please see the picture below. Squash Merge will generate two identical commit messages. I think it’s enough to have one of this message. When I use square merge on github, only one commit message will be generated.

![image](https://user-images.githubusercontent.com/20750357/101026936-75b24400-35b2-11eb-91c0-3a52571ce1d7.png)
![image](https://user-images.githubusercontent.com/20750357/101027069-9c707a80-35b2-11eb-82d3-4fafb003e2a9.png)

**Comment by ZhouJiaZhi** [comment] 2020-12-05 09:42
@lafriks 
Hi,Will you fix this problem soon? I hope that the function of square merge is the same as GitHub, with the title as the commit message, and other information should not be automatically generated

**Comment by techknowlogick** [comment] 2020-12-05 17:48
@ZhouJiaZhi we are volunteers and don't get paid for our work on Gitea so we can't guarantee a timeline

**Comment by jpraet** [comment] 2020-12-08 21:37
This is a duplicate of #12365. There's an open PR #13071 which would use the PR title and description as proposed commit message for a squash merge, instead of an aggregation of the individual commit messages. I think that's a good idea.

**Closed as completed** 2021-01-09 04:15 UTC
Labels: type/enhancement
