### ISSUE TITLE
Is is possible to count commit times rather than push times in user heatmap?

### ISSUE THREAD

**Issue by nbdavied** [go-gitea/gitea#11861] opened 2020-06-12 02:08 UTC

**Comment by lafriks** [comment] 2020-06-12 09:02
User heatmap calculates user activity in gitea not in git repositories. This also includes comments/reviews etc from Gitea database. I don't think it would be possible to count commits

**Comment by silverwind** [comment] 2020-06-12 11:52
Duplicate of https://github.com/go-gitea/gitea/issues/8178. Issue it heatmap counts the pusher, not the author of a commit.

**Closed as completed** 2020-06-19 20:19 UTC
