### ISSUE TITLE
Autolinking doesn't work in repo view/commits view but works inside a commit

### ISSUE THREAD

**Issue by adjurk** [go-gitea/gitea#7323] opened 2019-06-28 14:19 UTC
- Gitea version (or commit ref): 1.8.2+
- Git version: `git version 2.11.0`
- Operating system: Debian 9.6
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL): 
      - Works here: https://try.gitea.io/usertest123/Testrepo12345/commit/9f32a1874aa6f0cf923917ca7543a47d5091d2ab
      - Does not work here: https://try.gitea.io/usertest123/Testrepo12345
  - [ ] No
  - [ ] Not relevant
- Log gist: N/A

## Description
Enabling external issue tracker with numeric number format does not link to the issue (where it did in previous versions, such as 1.7.2)
...

## Screenshots
How it looks in a repo:
![How it looks in a repo](https://i.imgur.com/cndTM8T.png)
How it looks in a commit list:
![How it looks in a commit list](https://i.imgur.com/hQGJdSi.png)
Works properly inside a specific commit:
![Works properly inside a specific commit](https://i.imgur.com/tzbXfR8.png)

**Comment by mrsdizzie** [comment] 2019-06-28 15:30
This is duplicate of #7121 (which also has discussion of why that was changed).

**Closed as completed** 2019-06-28 15:32 UTC
Labels: issue/duplicate
