### ISSUE TITLE
Act runner doesn't trigger the event

### ISSUE THREAD

**Issue by kamzata** [go-gitea/gitea#25093] opened 2023-06-06 01:01 UTC
### Description

I'm using [Dokku](https://dokku.com/) and I'm trying to set up a CI/CD with Gitea. I implemented the Gitea actions [following this article](https://blog.gitea.io/2023/03/hacking-on-gitea-actions/) with [act_runner version v0.1.8](https://dl.gitea.com/act_runner/) and I tried to use the [github-actions for Dokku](https://github.com/dokku/github-action). Therefore I created [a simple workflow](https://github.com/dokku/github-action/blob/master/example-workflows/simple.yml) and it worked great. Then I created a [review-app workflow as in this example](https://github.com/dokku/github-action/blob/master/example-workflows/review-app.yml) which create and deploy an app on every `pull request` and here I find a issue: the app is correctly created on the pull request but it doesn't be destroyed when the pull request is closed or merged.

The act_runner logs says:

```
[deploy-on-pr/destroy_review_app] [DEBUG] evaluating expression 'github.event_name == 'pull_request' && github.event.action == 'closed''
[deploy-on-pr/destroy_review_app] [DEBUG] expression 'github.event_name == 'pull_request' && github.event.action == 'closed'' evaluated to 'false'
[deploy-on-pr/destroy_review_app] [DEBUG] Skipping job 'destroy_review_app' due to 'github.event_name == 'pull_request' && github.event.action == 'closed''
```

and when I'm closing the pull request nothing happen and even the act_runner logs don't add anything.

I talked with a [dokku/github-action](https://github.com/dokku/github-action) maintainer and he says it works using Github.

### Gitea Version

Gitea version 1.19.3 built with GNU Make 4.1, go1.20.4 : bindata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

git version 2.34.1

### How are you running Gitea?

act_runner version v0.1.8

### Database

None

**Comment by lunny** [comment] 2023-06-06 02:04
The default `on:pull_request` only trigger `open`, `reopen`, `sync` and I think it's the same as what Github does.

**Comment by Zettat123** [comment] 2023-06-06 02:06
Duplicate with [act_runner #229](https://gitea.com/gitea/act_runner/issues/229)

**Comment by Zettat123** [comment] 2023-06-07 08:41
Hi @kamzata , I can't reproduce this issue. The `opened` and `closed` types work fine in my tests.

Some questions:
1. Where is the workflow file? In the base branch or the head branch?
2. Have you tried creating a new pull request and closing it after updating the workflow file?

**Comment by kamzata** [comment] 2023-06-07 17:03
> Hi @kamzata , I can't reproduce this issue. The `opened` and `closed` types work fine in my tests.
> 
> Some questions:
> 
> 1. Where is the workflow file? In the base branch or the head branch?
> 2. Have you tried creating a new pull request and closing it after updating the workflow file?

Yes, I have. Please, [check the recording](https://youtu.be/Xsn5VmfpJ5s).

**Comment by Zettat123** [comment] 2023-06-08 03:05
Ah, yes. Thanks for the video recording, I reproduced the issue. This is a bug from the Gitea side and I'll send a PR to fix it.

**Comment by kamzata** [comment] 2023-06-08 14:18
> Ah, yes. Thanks for the video recording, I reproduced the issue. This is a bug from the Gitea side and I'll send a PR to fix it.

Thank you. Do you know when the fix will available in the next Gitea package in Debian repository?

**Closed as completed** 2023-06-11 01:06 UTC
Labels: type/bug, topic/gitea-actions
