### ISSUE TITLE
Issue render failed.

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#1523] opened 2017-04-20 09:44 UTC
visit https://try.gitea.io/trygitea123/BigRed/issues/1

**Comment by strk** [comment] 2017-04-20 10:30
Anything in the server logs ?

**Comment by cez81** [comment] 2017-04-25 21:48
Looks ok when signed in. Same as #1539?

**Comment by lunny** [comment] 2017-04-26 00:41
@cez81 seems a duplicted issue.

**Comment by geek1O11** [comment] 2017-04-26 21:08
Bad idea

**Comment by bkcsoft** [comment] 2017-04-26 21:29
Closing as duplicate of #1539

**Closed as completed by bkcsoft** 2017-04-26 21:29 UTC
Labels: type/bug
