### ISSUE TITLE
Code Editor Line number over 9999 not displayed correctly

### ISSUE THREAD

**Issue by jonde99** [go-gitea/gitea#31642] opened 2024-07-16 09:44 UTC
### Description

![image](https://github.com/user-attachments/assets/afee8d2f-5eac-4fd0-90d2-784c64545e2e)

Any file over 10000 lines displays the line numbers beyond 9999 incorrectly in the online editor. 

### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

Review mode: 
![image](https://github.com/user-attachments/assets/b700cb58-43d2-4558-bf3a-ee209e9b9bed)

Edit Mode: 
![image](https://github.com/user-attachments/assets/5422b69f-dff8-4fd1-beba-de9a5dacc4a7)

### Git Version

1.22.1

### Operating System

Redhat

### How are you running Gitea?

docker. 

### Database

MySQL/MariaDB

**Comment by yp05327** [comment] 2024-08-13 01:18
It seems that this is caused by the font?
<img width="952" alt="image" src="https://github.com/user-attachments/assets/66f770d0-a7e2-4a90-8157-928492878a59">

**Comment by yp05327** [comment] 2024-08-13 01:29
If you remove `Consolas` in `--fonts-monospace` it will be correct.
![image](https://github.com/user-attachments/assets/f69b0d4c-cbd1-421c-a8de-e0c3acb4b21b)
![image](https://github.com/user-attachments/assets/32e51c58-20e7-44d6-9c30-700d91fe0c17)

**Comment by jonde99** [comment] 2024-08-13 08:15
> If you remove `Consolas` in `--fonts-monospace` it will be correct. ![image](https://private-user-images.githubusercontent.com/18380374/357247380-f69b0d4c-cbd1-421c-a8de-e0c3acb4b21b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MzcyMDAsIm5iZiI6MTcyMzUzNjkwMCwicGF0aCI6Ii8xODM4MDM3NC8zNTcyNDczODAtZjY5YjBkNGMtY2JkMS00MjFjLWE4ZGUtZTBjM2FjYjRiMjFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDA4MTUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4MGQ2MTcxMTQwZGY1OGVmNzEzYWI4YjI4NzgwOGI3NzdjYzkyMTYyMDdhN2Y3YTkxYmQ2Y2JmZmZjNGI5NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hfyXnXA0M20EURwgJ6bp_mbWPQ2568OGCjhhezVHTD0) ![image](https://private-user-images.githubusercontent.com/18380374/357247490-32e51c58-20e7-44d6-9c30-700d91fe0c17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MzcyMDAsIm5iZiI6MTcyMzUzNjkwMCwicGF0aCI6Ii8xODM4MDM3NC8zNTcyNDc0OTAtMzJlNTFjNTgtMjBlNy00NGQ2LTljMzAtNzAwZDkxZmUwYzE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDA4MTUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhZTc5YTczZWRiMjM3MTY4OTI2M2Q4MDViZmY5OGY5YzY2MDYwMDJmMzFmNjdhZGRhMzMwZTUzMGU5MDU2NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RA5gRMcDylE4C0cI4CHNo1CVu3IrxzIqaZeTahscw6U)

Thanks. I will ask our admin to remove this line.

**Comment by jonde99** [comment] 2024-08-13 08:39
I played with this option, and it doesn't really fix it, it just delays the problem until there are 6 digits in the line number. 
The correct solution would be to allow the column to expand, but I cannot figure out where that is done.

**Comment by yp05327** [comment] 2024-08-13 08:51
I didn’t try 6 digits…. Maybe we need to check it first in https://microsoft.github.io/monaco-editor/playground.html?source=v0.50.0#example-creating-the-editor-hello-world

**Comment by palto42** [comment] 2024-08-15 07:37
@yp05327 
> In online demo, it works well. 

Are you sure you tried the editor view an not just the text preview?
I also tried the demo server and can confirm that I face the same issue as on my local Gitea instance.
https://demo.gitea.com/palto42/big_text/_edit/main/dummy_text_file.txt

![image](https://github.com/user-attachments/assets/3a29cd41-9e85-4b90-a3ae-223c74ba277f)

**Comment by lunny** [comment] 2024-08-15 16:21
I can confirm the problem.

![图片](https://github.com/user-attachments/assets/387f4173-b7b3-44ab-a3ef-ad2c06363428)

**Comment by yp05327** [comment] 2024-08-18 23:47
> @yp05327
> 
> > In online demo, it works well.
> 
> Are you sure you tried the editor view an not just the text preview? I also tried the demo server and can confirm that I face the same issue as on my local Gitea instance. https://demo.gitea.com/palto42/big_text/_edit/main/dummy_text_file.txt

I mean it works well in monaco editor playground, but not Gitea.

**Comment by charles7668** [comment] 2024-10-17 07:33
It seems the issue has been fixed by #31940.

**Comment by yp05327** [comment] 2024-10-17 07:56
I tested it in the latest version, it is fixed!

**Closed as completed** 2024-10-17 08:00 UTC
Labels: type/bug, topic/ui, issue/confirmed
