### ISSUE TITLE
Labels API does not work

### ISSUE THREAD

**Issue by rayitopy** [go-gitea/gitea#6047] opened 2019-02-12 14:26 UTC
- Gitea version (or commit ref): Go1.11.5
- Database (use `[x]`):
  - [] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description
The labels endpoints are not working as expected
` GET /repos/{owner}/{repo}/issues/{index}/labels`
Always return an epmty array
`POST, PUT, DELETE /repos/{owner}/{repo}/issues/{index}/labels`
Always returns a 401 status code, but I correctly setted the credentials

**Comment by Larivact** [comment] 2019-02-13 06:13
Link to reproduce: https://try.gitea.io/api/v1/repos/ttttttttttttttt/ttttttttttttttt/issues/1/labels

**Comment by adelowo** [comment] 2019-02-13 07:59
Yes, there is actually a bug with fetching labels of an issue. I have sent PR https://github.com/go-gitea/gitea/pull/6053 for that

I cannot replicate the 401 as it goes through on my end here. 
Can I see how you are authorizing the request?

**Comment by rayitopy** [comment] 2019-02-13 09:38
I was using basic authorization header in the swagger UI, with token authentication seems to work.
Maybe I'm misspelling the password or something. :man_shrugging:

**Comment by adelowo** [comment] 2019-02-13 16:03
@rayitopy I will guess it's your password that is wrong:). Since #6053 has been merged, is there any more thing to do on this issue?

**Comment by techknowlogick** [comment] 2019-02-13 16:37
closing as resolved. please re-open if needed.

**Closed as completed by techknowlogick** 2019-02-13 16:37 UTC
Labels: type/bug
