### ISSUE TITLE
CI Integration

### ISSUE THREAD

**Issue by hughesjs** [go-gitea/gitea#1889] opened 2017-06-06 12:49 UTC
I know this would be very difficult to implement and is by no means a small request, but might it be possible to integrate Continuous Integration within Gitea itself such that any unit tests in a project get run every time something is comitted?

**Comment by strk** [comment] 2017-06-06 13:21
James this is already working with drone (github.com/drone/drone)
The only part missing is automatically reporting build status near
the commits view and the PR view. But Drone can run on every commit
in all branches and pull requests

**Comment by lafriks** [comment] 2017-06-06 17:39
@strk it does show status in commits view but not in PR view currently

**Comment by strk** [comment] 2017-08-25 21:47
it could be useful to setup a fake service to showcase on try.gitea.io - ideas about doing that ?

**Comment by lunny** [comment] 2017-08-26 01:30
Maybe we can run a test drone service and all try.gitea.io project could visit it.

**Comment by strk** [comment] 2017-08-27 19:57
That would be great !

**Comment by bkcsoft** [comment] 2017-08-27 20:50
Duplicate of https://github.com/go-gitea/gitea/issues/996

**Closed as completed by bkcsoft** 2017-08-27 20:50 UTC
Labels: issue/duplicate
