### ISSUE TITLE
Comment history is loading slowly + has an offByOne error

### ISSUE THREAD

**Issue by delvh** [go-gitea/gitea#17676] opened 2021-11-17 00:16 UTC
### Gitea Version

1.16.0+dev-519-g3be156f66

### Operating System

Linux

### Browser Version

Firefox 94.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

Gitea now supports the comment history.
However, loading the history seems to be **way too slow**:

For normal comments, the history will automatically be loaded once the page is reloaded.
Fine so far. Still with a hefty delay (~3 seconds, so you definitely notice when the history suddenly appears), but it loads.

The issue bodies (the description of the issue) are way worse:
According to my tests on try.gitea.io, there seems to be an index error for those, as they only load once a second edit has been made. Once the second edit has been made, it behaves like a normal comment.

So, two things should be done:
1. the offByOne error should be fixed.
2. the history should be loaded faster, at best to the point that it is unnoticeable that it has been loaded afterwards.

### Screenshots

![image](https://user-images.githubusercontent.com/51889757/142085420-58df89c7-3bbd-4a57-820c-4e1195095331.png)
This is an issue description where one edit has been made and the page has been force-reloaded. As you see, the history is not getting displayed.

**Comment by jpraet** [comment] 2021-11-20 14:59
I think the offByOne happens when editing old issues/comments (created before there was support for edit history).

**Comment by wxiaoguang** [comment] 2021-11-20 15:22
> I think the offByOne happens when editing old issues/comments (created before there was support for edit history).

👍 Yep, the history menu won't be shown if there is only one history revision (that's by design). 

For old comments, there was no history revision before, so the first editing would save the first history revision, and the menu would only be shown for the second editing.

**Comment by wxiaoguang** [comment] 2021-11-20 15:30
And I haven't noticed any performance problem on my Gitea instance. The menu is always shown within 1 second.

If you believe there is a performance problem, please make sure your network is fast enough and help to find which function/sql causes the laggy.

**Comment by jpraet** [comment] 2021-11-20 15:45
To support edit history for existing comments: maybe the issue_content_history can be initialized with the initial (is_first_created) content when editing a comment that does not have such an entry yet?

**Comment by wxiaoguang** [comment] 2021-11-20 15:51
> To support edit history for existing comments: maybe the issue_content_history can be initialized with the initial (is_first_created) content when editing a comment that does not have such an entry yet?

Agree, it would work.

**Comment by jpraet** [comment] 2021-11-21 09:59
Or the issue_content_history could only be populated with the previous value when actually making an edit?
Because with the current implementation all issue contents and comments are unnecessarily saved twice in the database.

**Comment by wxiaoguang** [comment] 2021-11-21 10:15
> Or the issue_content_history could only be populated with the previous value when actually making an edit? Because with the current implementation all issue contents and comments are unnecessarily saved twice in the database.

I have thought about it, but it would make the algorithm more complex (eg: list/diff), usually I prefer a simple and clear solution. And issue contents are much smaller than git repositories, saving the contents won't cost too much in modern days.

**Comment by wxiaoguang** [comment] 2021-11-22 12:21
I think this issue can be closed by #17746

The "performance" problem may not be related. If there is really a performance problem, we need more details (and a separate issue)

**Closed as completed by wxiaoguang** 2021-11-22 12:21 UTC
Labels: type/bug, issue/needs-feedback, performance/speed, topic/ui-interaction
