### ISSUE TITLE
GET /api/v1/orgs returns no organisations

### ISSUE THREAD

**Issue by markusschaefer** [go-gitea/gitea#16785] opened 2021-08-23 12:33 UTC
- Gitea version 1.15.0
- Operating system: docker image gitea/gitea:1.15.0
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No

## Description
The api call "/api/v1/orgs" returns an empty result although there are many organisations and the user is owner of these organisations.

**Comment by noerw** [comment] 2021-08-23 16:55
Can't reproduce this. I think you need to be more specific about
- the exact request you made
- app.ini config: different settings affect visibility with/without authentication (eg `REQUIRE_SIGNIN_VIEW`)
- permission model of the orgs: are those private/restricted?
- permissions of the user owning the access token (are they admin?) also w.r.t. the orgs: are they member, did they create the org, was the org transferred?

**Comment by markusschaefer** [comment] 2021-08-25 06:14
Request is: GET /api/v1/orgs?token=XXX
app.ini REQUIRE_SIGNIN_VIEW is not set
visibility: "limited"
The User is gitea admin and owner of the orgs. The user created the orgs,

The request worked with gitea 1.14.6

With the request: GET /api/v1/orgs/myOrgName?token=XXX I can access every single org.

**Comment by 6543** [comment] 2021-08-29 17:22
If I had to guess, the **Actor** is not passed as searchOption

**Comment by 6543** [comment] 2021-08-29 19:07
my guess was right - I alos found a similar bug on a second api :D

**Closed as completed** 2021-08-30 18:00 UTC
Labels: type/bug
