### ISSUE TITLE
Internal Server Error on rendering diff page with updated LFS files

### ISSUE THREAD

**Issue by eddoursul** [go-gitea/gitea#17021] opened 2021-09-11 17:42 UTC
- Gitea version (or commit ref): 1.15.2
- Git version: 2.30.2
- Operating system: Debian 11 x64, using https://packaging.gitlab.io/gitea
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No, LFS is not enabled
- Log gist:
daemon.log:
https://gist.github.com/eddoursul/d366219877fc38faf5c0b02b7f7479b6

## Description
Gitea fails to render a diff page with updated LFS files, showing the `Internal Server Error` message instead.

To reproduce:
- Clone this repository https://github.com/eddoursul/gitea-lfsdiff-bugreport
- Push it to a Gitea instance with enabled LFS.
- Open the last commit /commit/a94fd5bc1e4abf49c7e393990387f865a60daf4c

**Comment by axifive** [comment] 2021-09-11 19:08
Maybe connected with #16837

**Comment by zeripath** [comment] 2021-09-12 10:45
This is a duplicate of #17007 and is already fixed by #17008 and its backport #17009

**Closed as completed by zeripath** 2021-09-12 10:45 UTC
Labels: type/bug, issue/duplicate
