### ISSUE TITLE
Closing a ticket shows it is closed by the opener not the doer 

### ISSUE THREAD

**Issue by eeyrjmr** [go-gitea/gitea#17942] opened 2021-12-10 00:01 UTC
### Gitea Version

1.16.0+dev-670-gc7e23401a

### Git Version

2.34

### Operating System

Windows 

### How are you running Gitea?

Windows service 

### Database

MySQL

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

When an issue is closed, it correctly shows who closed the issue when you review the issue BUT the when you view the issue list it shows the issue has been closed by the person that opened the issue 

https://try.gitea.io/eeyrjmr/test_issues/issues

### Screenshots

![Annotation 2021-12-10 000042](https://user-images.githubusercontent.com/4564448/145494521-a0930cc2-553e-4ea4-8d1e-28bac498bf30.png)

![Annotation 2021-12-10 000117](https://user-images.githubusercontent.com/4564448/145494551-956702f8-c39d-4527-9822-fc07f6eaaa1f.png)

**Comment by KN4CK3R** [comment] 2021-12-12 10:43
I don't think that's a bug, it's just wrong wording. It should show the user which created the issue not the one who closed it.

Github uses the phrases
`#xxx opened <time> by <user>`
`#xxx by <user> was closed <time>`

Gitea uses
`#xxx opened <time> by <user>`
`#xxx closed <time> by <user>`
which misleads the user as closer.

**Comment by eeyrjmr** [comment] 2021-12-12 12:32
The reason I opened it was it was a colleague was confused that I had opened a bunch of issues and they had closed but the wording implied I closed it.

Subtle reword or show who closed would suffice :)

**Comment by zeripath** [comment] 2021-12-13 22:05
This is a duplicate of another report. I guess it's time to just update the locale files and stop this once and for all.

**Comment by KN4CK3R** [comment] 2021-12-13 22:06
Just doing that right now.

**Closed as completed** 2021-12-14 01:45 UTC
Labels: type/bug, issue/critical
