### ISSUE TITLE
[ Feature ] workflow visual representation

### ISSUE THREAD

**Issue by Sharaf5** [go-gitea/gitea#31088] opened 2024-05-26 20:17 UTC
### Feature Description

Add support for visual representation of workflow

### Screenshots

Flow rendering of workflow

![Screenshot_20240526_231430](https://github.com/go-gitea/gitea/assets/36330265/dd9a7496-1330-4ab8-8091-d435da73b3e2)

**Comment by lunny** [comment] 2024-05-27 01:00
Duplicate of #26037

**Closed as not planned by lunny** 2024-05-27 01:00 UTC
Labels: type/proposal
