### ISSUE TITLE
Release attachments are shown with incorrect URL on release pages

### ISSUE THREAD

**Issue by congoblue** [go-gitea/gitea#14324] opened 2021-01-13 09:03 UTC
- Gitea version (or commit ref): 1.13.0
- Git version: 2.29.2
- Operating system: Windows 10 Professional using pre built download
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X ] Yes https://try.gitea.io/congoblue/FileAttachTest/releases
  - [ ] No
- Log gist:

## Description
When a file is manually attached to a release, on the release page Gitea uses a URL with a guid number to link to the file. This means you cannot right-click - save-as because the file saves with a numeric name and no extension rather than its correct filename as displayed on the release page.

http://giteaurl/attachments/69d80049-7826-4e98-9328-b87f43ff6d63

The attached file should be linked with a github-style URL like this to enable downloading and url sharing
http://giteaurl/organization/repo/releases/download/releasetag/filename.xxx

If you enter this style of URL manually in the browser, then Gitea does serve the correct file, so it appears the only problem is the URL being used on the page, the functionality being used to serve the file is all working.

## Screenshots
![image](https://user-images.githubusercontent.com/24965690/104429517-9a201980-557d-11eb-8fc8-461767043982.png)

**Comment by Daxigua443** [comment] 2021-01-14 02:14
![Uploading Lark20210113-165514.png…]()

**Comment by congoblue** [comment] 2021-01-14 08:14
Slight update to the comments above - if I put a test download link on a separate webpage in the correct form
http://giteaurl/organization/repo/releases/download/releasetag/filename.xxx

Gitea does serve the correct file but still with the guid-style numeric name, so right clicking and doing save-as still does not work - I assume the numeric filename must be set in the content-disposition of the response. So it is not just as simple as putting the correct link on the Releases page.

**Comment by noerw** [comment] 2021-01-17 20:41
duplicate of #10919

**Closed as completed by noerw** 2021-01-17 20:41 UTC
