### ISSUE TITLE
REQUIRE_SIGNIN_VIEW no longer working

### ISSUE THREAD

**Issue by mircolino** [go-gitea/gitea#4409] opened 2018-07-09 21:52 UTC
```
[service]
REQUIRE_SIGNIN_VIEW = true
```
In version 1.4.3 the above would redirect to the login page.
In version 1.5 this no longer works and the home page is always displayed. 

Gitea version: c784ac5 (1.5)
Git version: 2.18
Operating System: Windows 10
Database: SQLite

**Comment by spantaleev** [comment] 2018-07-10 12:44
Not only that, but repositories (those that haven't been marked as "private") also seem to be accessible by non-logged-in users.

**Comment by johanhugg** [comment] 2018-07-11 12:57
Can you give an example of urls that don't work as expected? I can't seem to reproduce this..

**Comment by mircolino** [comment] 2018-07-11 14:33
I attached our (redacted) app.ini. You can replicate the problem with a fresh 1.5 installation.
We use a real CA signed certificate, not sure if that makes any difference.

[app.zip](https://github.com/go-gitea/gitea/files/2184896/app.zip)

**Comment by mircolino** [comment] 2018-07-11 14:38
I attached our (redacted) app.ini. You can replicate the problem with a fresh 1.5 installation.
We use a real CA signed certificate, not sure if that makes any difference.

[app.zip](https://github.com/go-gitea/gitea/files/2184922/app.zip)

**Comment by johanhugg** [comment] 2018-07-12 07:43
Just fired up an instance using the commit hash specified in your original comment, created a repository called test under the user master, so the url was: http://localhost:3000/master/test. I enabled REQUIRE_SIGNIN_VIEW, logged out and tried to access the URL, I got redirected to the login screen. I also tried to clone the repository using HTTP, and it required a username and password which I entered nothing and got access denied. Clicking explore on the top bar also redirected me to the login screen.

**Comment by spantaleev** [comment] 2018-07-12 10:17
I've observed the problem with the `gitea/gitea:1.5` Docker image, if that helps.

**Comment by daviian** [comment] 2018-07-12 14:13
AFAIK the home screen is shown on purpose despite setting REQUIRE_SIGNIN_VIEW (https://github.com/go-gitea/gitea/pull/4040)

But nonetheless every other link should redirect to the login page.

**Comment by mircolino** [comment] 2018-07-12 14:16
Yes, accessing the [http://localhost:3000/master/test](http://localhost:3000/master/test) repo directly works.
Try accessing  the [http://localhost:3000](http://localhost:3000) home page. If all the repos are private (like in our case) it's nice to be redirected to the login page and then to the user's dashboard.

**Comment by johanhugg** [comment] 2018-07-12 14:22
Ok, then this is not a bug, and instead changed behaviour of the configuration value. Some people use the home page for showing information about the service, but still wanting people to have to sign up if they want to explore the service's repos and organizations.

**Comment by lafriks** [comment] 2018-07-12 14:33
Default behavior should not have changed

**Comment by d3473r** [comment] 2018-07-25 12:45
With the `gitea/gitea:1.5` Docker Image in Rancher neither `DISABLE_REGISTRATION` nor `REQUIRE_SIGNIN_VIEW` seems to be working.

The variables are set in the Container:
```
ubuntu@machine:~$ docker exec 00e102859dbd bash -c 'echo "$DISABLE_REGISTRATION"'
true
ubuntu@machine:~$ docker exec 00e102859dbd bash -c 'echo "$REQUIRE_SIGNIN_VIEW"'
true
```

The registration is open
![2018-07-25 14_42_35-registrieren - critalog-gitea](https://user-images.githubusercontent.com/10356892/43201572-2a49194e-9019-11e8-8eaa-3c896ec95469.png)

And i can browse public repos
![2018-07-25 14_42_50-erkunden - critalog-gitea](https://user-images.githubusercontent.com/10356892/43201573-2a63c44c-9019-11e8-9528-3ca1a235c0b4.png)

**Comment by lafriks** [comment] 2018-07-25 13:07
Check app.ini if these values are set there

**Comment by d3473r** [comment] 2018-07-25 13:11
Theay are not set there
```
[service]
DISABLE_REGISTRATION              = false
REQUIRE_SIGNIN_VIEW               = false
```

**Comment by lafriks** [comment] 2018-07-25 13:13
Did you set them when creating that instance initially or only later? app.ini values will be set only when creating and that file does not exists yet

**Comment by d3473r** [comment] 2018-07-25 13:14
I did set them later.
For persistence i have mounted a ec2 volume: gitea-storage:/data

**Comment by lafriks** [comment] 2018-07-25 13:16
That is why it is not working. Just update app.ini file manually and restart container

**Comment by lunny** [comment] 2018-11-23 07:13
The default behaviour has been changed by https://github.com/go-gitea/gitea/pull/4040, but that's not a bug.

**Closed as completed by lunny** 2018-11-23 07:13 UTC
Labels: type/question
