### ISSUE TITLE
[UI] Add namespace to global click event , index.js

### ISSUE THREAD

**Issue by derekhu** [go-gitea/gitea#15687] opened 2021-05-01 07:31 UTC
https://github.com/go-gitea/gitea/blob/5811e162ae7257ea85a910266dc3cb94a9e6472c/web_src/js/index.js#L688

```js
  $(document).on('click', (event) => {
    const urlTarget = $(':target');
    if (urlTarget.length === 0) return;

    const urlTargetId = urlTarget.attr('id');
    if (!urlTargetId) return;
    if (!/^(issue|pull)(comment)?-\d+$/.test(urlTargetId)) return;

    const $target = $(event.target);

    if ($target.closest(`#${urlTargetId}`).length === 0) {
      const scrollPosition = $(window).scrollTop();
      window.location.hash = '';
      $(window).scrollTop(scrollPosition);
      window.history.pushState(null, null, ' ');
    }
  });
```

This block of code performaces different UI experience with Gitlab issue comment.   

When I got focus on certain comment,  it gets highlight and hash changed ok.  
And when click blank place in the page, the hash changes to empty.

However, I want to keep the same experience as Gitlab done: keep the #hash .
I can .off() the global document click event, if the code provides events namespace, and I only have to add custom code in foot.tmpl instead of replace and modify the whole index.js.

eg: index.js
```js
 $(document).on('click.syncemptyhash' , ... )  // or any namespace you like
...
```

eg：custom，foot.tmpl
```html
<script>
   $(document).off('click.syncemptyhash')
</script>
```

**Comment by zeripath** [comment] 2021-05-11 06:06
Pop up a PR if you can.

I haven't completely understood what the problem is from your issue report. It would be good if you could give us some clear steps to reproduce the issue using try.gitea.io telling us what you expected instead.

Is it something like:

1. Go to https://try.gitea.io/owner/repo/issue/6#comment-id
2. Click anywhere
3. Note that the hash disappears from the URL bar
4. I expected the hash to stay

**Comment by derekhu** [comment] 2021-05-11 06:16
> Pop up a PR if you can.
> 
> I haven't completely understood what the problem is from your issue report. It would be good if you could give us some clear steps to reproduce the issue using try.gitea.io telling us what you expected instead.
> 
> Is it something like:
> 
> 1. Go to https://try.gitea.io/owner/repo/issue/6#comment-id
> 2. Click anywhere
> 3. Note that the hash disappears from the URL bar
> 4. I expected the hash to stay

yeah, exact

**Comment by wxiaoguang** [comment] 2021-11-19 17:48
I think the behavior can be fixed by a `capture` event listener.

https://stackoverflow.com/questions/12462721/does-stoppropgation-stop-the-event-from-propagating-in-the-capture-phase

Then we do not need to add event namespaces one by one.

I will close this issue and PR, feel free to feedback.

**Closed as completed by wxiaoguang** 2021-11-19 17:48 UTC
