### ISSUE TITLE
New issue: generate issue index failed: get resource index failed

### ISSUE THREAD

**Issue by kingzcheung** [go-gitea/gitea#16941] opened 2021-09-03 10:30 UTC
- Gitea version (or commit ref): 1.15.1
- Git version: 
- Operating system: linux amd64
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description

generate issue index failed: get resource index failed

#### LOG

```
2021/09/03 18:24:50 ...vices/issue/issue.go:16:NewIssue() [I] [SQL] BEGIN TRANSACTION [] - 83.008µs
2021/09/03 18:24:50 models/index.go:92:getNextResourceIndex() [I] [SQL] SELECT max_index FROM issue_index WHERE group_id = ? [358] - 293.367µs
2021/09/03 18:24:50 models/index.go:66:GetNextResourceIndex() [I] [SQL] INSERT INTO issue_index (group_id, max_index) VALUES (?,1) ON DUPLICATE KEY UPDATE max_index = max_index+1 [358] - 327.976µs
2021/09/03 18:24:50 models/index.go:102:getNextResourceIndex() [I] [SQL] SELECT max_index FROM issue_index WHERE group_id = ? AND max_index=? [358 5] - 332.99µs
2021/09/03 18:24:50 models/issue.go:1012:NewIssue() [I] [SQL] ROLLBACK [] - 705.562µs
2021/09/03 18:24:50 ...rs/web/repo/issue.go:980:NewIssuePost() [E] NewIssue: generate issue index failed: get resource index failed
```

## Screenshots

![screenshot-20210903-182545](https://user-images.githubusercontent.com/12839855/131991558-8efbb17e-f0a0-496f-beba-4387a806aa81.png)

**Comment by wxiaoguang** [comment] 2021-09-03 10:36
Just a guess, very likely this one: https://github.com/go-gitea/gitea/pull/16938

**Comment by zeripath** [comment] 2021-09-03 10:36
This is a duplicate of #16936

Run `gitea docker recreate-table issue_index` and it will go away.

We'll get 1.15.2 out v. soon.

**Closed as completed** 2021-09-03 10:36 UTC
Labels: issue/duplicate
