### ISSUE TITLE
Can we explore the source code like github does?

### ISSUE THREAD

**Issue by yusiwen** [go-gitea/gitea#30095] opened 2024-03-26 05:45 UTC
### Feature Description

Just like this:
![image](https://github.com/go-gitea/gitea/assets/3704932/475b75a2-79de-4b3a-ae83-fc980815dbb4)

Thanks

**Comment by lunny** [comment] 2024-03-26 05:54
Duplicate of #29328

**Closed as completed by lunny** 2024-03-26 05:54 UTC
Labels: type/proposal
