### ISSUE TITLE
Accentued chars in tags (under project description)

### ISSUE THREAD

**Issue by blankoworld** [go-gitea/gitea#4859] opened 2018-09-03 20:04 UTC
Gitea version 
- Gitea version (or commit ref): 1.5.0 built with: bindata, sqlite, tidb, pam
- Git version: 2.18.0
- Operating system: ArchLinux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL): https://try.gitea.io/bl4n/test (attempt to add tags with accentued chars without any result).
  - [ ] No
  - [ ] Not relevant

## Description

  * Use an existing project, or create a new one
  * Push some files (if new one to access to project description)
  * Click on "manage tags" (in French « Gérer les sujets »)
  * Add "vidéo" as tag, then click on "finish" button (in French « Terminé »)
  * The web interface ask to use a tag that start with a number or a char, etc.

## Screenshots

![2018-09-03-1536004939_screenshot_1680x1050](https://user-images.githubusercontent.com/147417/45000426-0f9a7900-afc5-11e8-8cc3-9fb3fe5b3739.jpg)

**Comment by lafriks** [comment] 2018-09-12 06:49
It is intended behavior to allow only English characters and I don't think topics should allow non-ascii characters. (GitHub also does not allow that)

**Comment by blankoworld** [comment] 2018-09-12 10:58
Ok, I understand.
So I suggest to add a better explanation. Because I do what's defined in the message: only chars and number.
And this message does not ask that space are forbidden (if they are).

Could we change the message?

**Comment by lafriks** [comment] 2018-09-12 20:09
Sure any recommendations what that message should look like?

**Comment by blankoworld** [comment] 2018-09-12 20:51
In fact neither spaces nor special chars are allowed.

So I suggest something like: 

```
Topics must start with a letter or number, can include dashes ('-') and can be up to 35 characters long. Spaces and special chars are not allowed.
```

or to have less chars:

```
Topics must start with a letter or number, can include dashes ('-') and can be up to 35 characters long. Dismiss spaces and special chars.
```

In french, it would be respectively:

```
Les noms de sujets doivent commencer par une lettre ou un nombre, peuvent contenir des tirets ('-') et peuvent comporter jusqu'à 35 caractères. Les espaces et les caractères spéciaux ne sont pas autorisés.
```

or:

```
Les noms de sujets doivent commencer par une lettre ou un nombre, peuvent contenir des tirets ('-') et peuvent comporter jusqu'à 35 caractères. Évitez les espaces et les caractères spéciaux.
```

You can adapt the sentence because I'm french native. Not english one ^_^

**Comment by blankoworld** [comment] 2019-01-09 15:41
Tell me where to change messages and I can suggest a pull request, can't it?

**Comment by apricote** [comment] 2019-01-09 16:17
The english message is defined here: https://github.com/go-gitea/gitea/blob/master/options/locale/locale_en-US.ini#L1255

You can adjust this line and create a PR.

The french translation is managed through Crowdin, you need to suggest the change there.

**Comment by techknowlogick** [comment] 2019-01-09 17:51
Thanks for responding @apricote. @blankoworld see above for where translations are made.

Closing this ticket now

**Closed as completed by techknowlogick** 2019-01-09 17:51 UTC
Labels: type/enhancement
