### ISSUE TITLE
SimpleMDE not usable on android mobile chrome browser

### ISSUE THREAD

**Issue by lafriks** [go-gitea/gitea#9658] opened 2020-01-08 20:34 UTC
~~It would keep adding all text duplicate after first space and on next again duplicate everything, not possible to delete text either~~

Review text area is too wide and does not fit in mobile screen

**Comment by zeripath** [comment] 2020-01-08 21:43
Yup I've noticed this too.

**Comment by bobemoe** [comment] 2020-01-18 10:50
Deleting text may be working since https://github.com/go-gitea/gitea/pull/9545 ?

**Comment by lafriks** [comment] 2020-01-21 17:46
Seems to be working now on try gitea. Of course review text is unusably large so that first par of simplemde text box is not visible and also no buttons are visible

**Comment by guillep2k** [comment] 2020-01-22 04:50
Label kind/ui ?

**Comment by wenzel-k** [comment] 2020-04-12 17:42
The initial description (which is striked through) is actually still an issue.

Space will repeadadly insert previous text.

I could just reproduce on try.gitea ([https://try.gitea.io/jzaeske/test/issues/3](https://try.gitea.io/jzaeske/test/issues/3) )

Would be nice if you could fix it 🙂

**Comment by danger89** [comment] 2020-09-25 23:50
Can we atleast introduce the markdown editor for markdown files.. for **desktop** PC's??

**Comment by delvh** [comment] 2023-04-03 10:56
Closed by #23876.

**Closed as completed by delvh** 2023-04-03 10:56 UTC
Labels: type/bug, topic/ui, issue/confirmed, topic/mobile, outdated/theme/markdown
