### ISSUE TITLE
Emojis are converted to question-marks in repository description

### ISSUE THREAD

**Issue by jonasfranz** [go-gitea/gitea#2711] opened 2017-10-15 21:31 UTC
- Gitea version (or commit ref): f3833b7
- Operating system: GNU/Linux
- Database (use `[x]`):
  - [x] MySQL
- Can you reproduce the bug at https://try.gitea.io:
  - [x] No
- Log gist: Not relevant

## Description

It result into the following: "????App for iOS" if you want to add emojis to your repository description like "📱App for iOS".

Emojis in the description could be useful like seen at the ownCloud Github Project (https://github.com/owncloud).

This might be caused by the used MySQL database.

**Comment by lunny** [comment] 2017-12-05 14:35
So maybe mysql database should be `utf8mb4`?

**Comment by kolaente** [comment] 2018-03-24 09:50
I had a similar issue, but in my case the description was completly deleted when I added an emoji to the repo description (`v1.4-rc-2`). Seems to work fine on master with sqlite though.

**Comment by lunny** [comment] 2018-12-09 08:44
~This should be fixed by https://github.com/go-gitea/gitea/pull/5168, please feel free to reopen it.~

**Comment by lunny** [comment] 2018-12-09 08:47
If you input `:smile:` that right for repo description, but if you paste from your clipboard, that will fail.

**Comment by immanuelfodor** [comment] 2018-12-31 16:59
I can confirm this on v1.6.2, any emoji copypasted from e.g. https://emojipedia.org becomes `????`. Only the manually typed `:emojicode:` works fine. This issue is also present at eg. org descriptions, copypasted emojis become question marks. Screenshot from an issue comment:

![screenshot_20181231_175649](https://user-images.githubusercontent.com/21174107/50564488-87837080-0d25-11e9-8801-65f7cba2608b.png)

**Comment by lunny** [comment] 2019-01-03 09:15
So should we parse the copypasted emojis to :emojicode: before save it?

**Comment by immanuelfodor** [comment] 2019-01-03 09:18
Great idea, it should work without `utf8mb4` then (simple `utf8` databases/tables).

**Comment by immanuelfodor** [comment] 2019-03-04 12:31
Any new info on somebody planning to implement the suggested conversion that could solve the original issue? :)

**Comment by helmut72** [comment] 2019-03-10 10:37
Or just add MySQL utf8mb4 support.

**Closed as completed** 2019-05-24 04:32 UTC
Labels: type/enhancement, topic/ui, issue/confirmed

**Comment by immanuelfodor** [comment] 2019-05-24 04:40
Wow, thank you, @lunny ! Will there be a migration guide for us until the next release how to upgrade an existing database? Or this depends on the community if someone publishes such? I think I did such for a Nextcloud install once following these steps: https://docs.nextcloud.com/server/16/admin_manual/configuration_database/mysql_4byte_support.html Should these steps work in theory for Gitea as well? (With replacing the DB name, of course)

**Comment by lunny** [comment] 2019-05-24 05:27
@immanuelfodor convert a utf8 database to utf8mb4 database is possbile. And I found an article about how to convert utf8 to utf8mb4, see https://mathiasbynens.be/notes/mysql-utf8mb4

**Comment by immanuelfodor** [comment] 2019-07-31 16:56
The new PRs #7144 #6992 took care of the conversion with the new `gitea convert` command successfully but I still get four question marks in comments when commenting with an emoji. All my tables are Barracuda, utf8mb4, row format dynamic, etc etc. Gitea was newly built, restarted, new login session.

```bash
gitea -v
# Gitea version 1.9.0 built with GNU Make 4.1, go1.12.7 : bindata
mysql -V
# mysql  Ver 15.1 Distrib 10.1.40-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
cat /etc/os-release | grep -i pretty_name
PRETTY_NAME="Ubuntu 18.04.2 LTS"
```

**Comment by immanuelfodor** [comment] 2019-07-31 17:16
I'm not sure if this is a DB issue because the CLI shows ???? as if it was saved to the DB this way.

```sql
MariaDB [gitea]> select id, name, content from issue where id=2;
+----+-----------------+---------------------+
| id | name            | content             |
+----+-----------------+---------------------+
|  2 | Testing utf8mb4 | :grinning: 

???? |
+----+-----------------+---------------------+
1 row in set (0.00 sec)

MariaDB [information_schema]> select column_name, character_set_name, collation_name from columns where table_schema = "gitea" and table_name = "issue" and character_set_name is not null;
+-------------+--------------------+--------------------+
| column_name | character_set_name | collation_name     |
+-------------+--------------------+--------------------+
| name        | utf8mb4            | utf8mb4_general_ci |
| content     | utf8mb4            | utf8mb4_general_ci |
| ref         | utf8mb4            | utf8mb4_general_ci |
+-------------+--------------------+--------------------+
3 rows in set (0.00 sec)

select table_name, table_collation, engine, row_format, create_options from tables where table_schema = "gitea" and table_name = "issue";
+------------+--------------------+--------+------------+--------------------+
| table_name | table_collation    | engine | row_format | create_options     |
+------------+--------------------+--------+------------+--------------------+
| issue      | utf8mb4_general_ci | InnoDB | Dynamic    | row_format=DYNAMIC |
+------------+--------------------+--------+------------+--------------------+
1 row in set (0.00 sec)

MariaDB [information_schema]> select * from innodb_sys_tables where name = "gitea/issue";
+----------+-------------+------+--------+-------+-------------+------------+---------------+
| TABLE_ID | NAME        | FLAG | N_COLS | SPACE | FILE_FORMAT | ROW_FORMAT | ZIP_PAGE_SIZE |
+----------+-------------+------+--------+-------+-------------+------------+---------------+
|     1005 | gitea/issue |   33 |     20 |   991 | Barracuda   | Dynamic    |             0 |
+----------+-------------+------+--------+-------+-------------+------------+---------------+
1 row in set (0.00 sec)

MariaDB [information_schema]> show variables like 'innodb_file_%';
+--------------------------+-----------+
| Variable_name            | Value     |
+--------------------------+-----------+
| innodb_file_format       | Barracuda |
| innodb_file_format_check | ON        |
| innodb_file_format_max   | Barracuda |
| innodb_file_per_table    | ON        |
+--------------------------+-----------+
4 rows in set (0.00 sec)

MariaDB [information_schema]> show variables like 'innodb_large_%';
+---------------------+-------+
| Variable_name       | Value |
+---------------------+-------+
| innodb_large_prefix | ON    |
+---------------------+-------+
1 row in set (0.00 sec)
```

**Comment by lunny** [comment] 2019-08-01 00:09
@immanuelfodor could you paste the content here so that I can test it locally.

**Comment by immanuelfodor** [comment] 2019-08-01 03:14
Just two grinning faces, first line is with `:grinning:`, second is the same face copied from emojipedia (copy button): https://emojipedia.org/grinning-face/
Funny thing is that in the meantime, I received an email from Gitea, and it contains the emoji fine on the second line. Maybe the email is sent before the multibyte character is converted? 
Another idea is the DB connection, in PHP, you would need to run `SET NAMES utf8mb4` before anything else, I don't know if it is true for Go as well or if you do it in Gitea: https://stackoverflow.com/questions/16893035/using-utf8mb4-with-php-and-mysql

**Comment by lunny** [comment] 2019-08-01 05:10
@immanuelfodor You should change `charset` in app.ini to `utf8mb4`. Go to https://docs.gitea.io/en-us/config-cheat-sheet/ and search CHARSET . I think your problem maybe because you haven't set that.

**Comment by immanuelfodor** [comment] 2019-08-01 05:20
Aaand YES! I looked through my app.ini before, but I did not have the charset option there, it must be newer than my file. Added it, restarted Gitea, new comment, and it works! Thank you very much.
