### ISSUE TITLE
Invite Links

### ISSUE THREAD

**Issue by f0x52** [go-gitea/gitea#7095] opened 2019-05-31 14:56 UTC
It would be nice if Gitea had support for invite links, like Mastodon does.
As an instance admin, you can choose who can generate them (admins, moderators, users).
When someone generates an invite link, they can then choose the amount of people that can use it, and after what time it expires.

**Comment by poVoq** [comment] 2022-02-16 21:28
This would be really nice for semi-public instances.

**Comment by ForestJohnson** [comment] 2022-03-10 00:39
Hello, I forked my friend's project to implement this in a very simplistic way on my own gitea instance without modifying the gitea code.  It's an app which reverse proxies the GET and POST for the `/user/sign_up` endpoint to enforce a single shared invite token.

You may check it out here: https://git.sequentialread.com/forest/gitea-registration-proxy

**Comment by poVoq** [comment] 2022-03-10 18:21
@ForestJohnson the link to your repository is dead.

**Comment by ForestJohnson** [comment] 2022-03-10 21:51
@poVoq  sorry about that. My server crashes and goes down sometimes. It should be up now.  I'll post a couple mirrors later today

**Comment by techknowlogick** [comment] 2022-04-13 01:54
closing as dupe of https://github.com/go-gitea/gitea/issues/5353

**Closed as completed by techknowlogick** 2022-04-13 01:54 UTC
Labels: issue/duplicate
