### ISSUE TITLE
Markdown relative links / not working properly

### ISSUE THREAD

**Issue by mg-cloud** [go-gitea/gitea#27646] opened 2023-10-16 13:41 UTC
### Description

I stumble upon a rendering issue with markdown relative links. I didn't find any specification for this so I'm referring to [GitHub documentation](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#relative-links) which states "Links starting with / will be relative to the repository root."
However in Gitea, the are relative to gitea root url.
For example:
```
[Link to ../test.md] (../test.md) -> Working (links to https://try.gitea.io/myrepo/src/branch/master/test.md)
[Link to /test.md] (/test.md) -> Not working (links to https://try.gitea.io/test.md)
```

I reproduce the issue on try.gitea.io, see https://try.gitea.io/mgalloux/test-markdown
In the README, you have a basic relative link (../test.md) which works as expected, but the syntax (/test.md) links to the ROOT_URL/test.md and returns a 404.

### Gitea Version

1.20.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![bug_gitea](https://github.com/go-gitea/gitea/assets/116154749/e74186b5-c608-48be-bc4c-43ea548b2d3e)

### How are you running Gitea?

Discovered the issue on my docker instance with Gitea 1.20.0 but was able to reproduce it on try.gitea.io 1.22.0+dev-188-g1be49fddae

### Database

None

**Comment by mg-castel** [comment] 2023-10-16 13:47
Closing as duplicate of https://github.com/go-gitea/gitea/issues/18592

**Closed as not planned by mg-castel** 2023-10-16 13:47 UTC
Labels: type/bug
