### ISSUE TITLE
Create modular API plug-in framework

### ISSUE THREAD

**Issue by liquidaty** [go-gitea/gitea#16195] opened 2021-06-18 14:39 UTC
Thank you for this fantastic project.

We are exploring using it and customizing for our purposes. The documentation at https://docs.gitea.io/en-us/hacking-on-gitea/ is immensely useful.

We would love to have a modularized way to customize API endpoints and UI features. The module would contain everything related to that endpoint / customization, including specification, code, localization, documentation etc, would ideally exist in its own directory located anywhere on the build system, and would be automatically included with the addition of a build tag, env var or similar mechanism that did not need to modify any tracked assets. This modularized approach would seem to be useful both for streamlining the development of new APIs or UI elements, regardless of whether they will be added to the library code base.

We would happily pay a bounty, especially if this feature could be rolled out quickly.

Thoughts?

**Comment by techknowlogick** [comment] 2021-06-19 02:45
Closing as dupe of https://github.com/go-gitea/gitea/issues/2222

**Closed as completed by techknowlogick** 2021-06-19 02:45 UTC
Labels: issue/duplicate
