### ISSUE TITLE
Bad URL detection in Description field

### ISSUE THREAD

**Issue by AloisMahdal** [go-gitea/gitea#4143] opened 2018-06-05 19:48 UTC
- Gitea version (or commit ref): fa3ceb6 (try.gitea.io)
- Git version: (not relevant)
- Operating system: (unknown)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes - https://try.gitea.io/netvor/slop-copr-build
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

If I include URL inside parentheses in Description of a git repo, gitea web UI will linkify it, but the closing bracket will be detected as  art of the URL, resulting in HTTP-404 errors.

## Screenshots

http://file.vornet.cz/tmp/rbrack.png

**Comment by techknowlogick** [comment] 2018-07-21 20:14
I don't know if this is an issue that needs to be resolved, because there is already a URL field for URLs to go into.

**Comment by davidak** [comment] 2018-07-21 23:34
@techknowlogick if this usage is not intended, maybe don't detect URLs in this text at all?

**Comment by AloisMahdal** [comment] 2018-07-25 09:40
It could still make sense to include another URL in this field.

**Comment by lunny** [comment] 2018-09-07 02:57
I like @davidak 's idea.

**Comment by davidak** [comment] 2019-02-25 09:26
I can still reproduce it on 28fcbf3: https://try.gitea.io/davidak/test4

**Comment by mrsdizzie** [comment] 2019-03-27 03:46
This is fixed as of 71b734b (link in previous comment now works as expected)

**Closed as completed** 2019-03-27 04:09 UTC
Labels: type/bug, issue/confirmed
