### ISSUE TITLE
Issue with creating or editing text in issues in mobile view

### ISSUE THREAD

**Issue by MelBourbon** [go-gitea/gitea#12146] opened 2020-07-05 08:49 UTC
- Gitea version (or commit ref): 1.12.1 - 1.13.0
- Operating system: Ubuntu 18.04 LTS
- Database (use `[x]`): Docker 

## Description
I have issues with adding or editing text to description or comments of issues (see attached gif). Text is autocompleted repetitively.

![ezgif-1-3232105a9c5b](https://user-images.githubusercontent.com/30600002/86528970-1807b780-bead-11ea-9cdf-50a1506445f8.gif)

**Comment by djonmayer** [comment] 2020-07-07 07:36
I have the same problem with mobile view. Testet in Firefox and Chrome on Android 8 / 9.

**Comment by sploders101** [comment] 2020-08-27 17:48
Not sure how many testimonials are necessary, but I can confirm the same issue on Chrome for Android. It seems like it is potentially an issue with the rich text editing function of the box, that automatically applies markdown syntax as you type. If this is too big of an issue, even a simple textarea would resolve the issue in the short-term, since it isn't usable as-is.

Thanks!

**Comment by ColinShorts** [comment] 2020-09-09 12:30
Switching to desktop view (android10/11 + chrome) seems to work around the issue, but that's not ideal on tiny screens.

**Comment by zeripath** [comment] 2020-09-09 13:21
There's a workaround: Press the last icon on the toolbar the black 🗅 folded over note. That will switch off the editor.

**Comment by luwol03** [comment] 2020-11-14 19:09
but the error is not fixed yet?

**Comment by corneliusroemer** [comment] 2020-12-15 12:07
This problem has now been known for at least 5mo - could you please switch off the editor by default on mobile browsers until this is fixed. It's provides a terrible first impression for anyone encountering Gitea on mobile for the first time.

**Comment by 6543** [comment] 2020-12-16 16:44
@MelBourbon can you confirm,  #13333  solved this?

try.gitea.com run with latest version to test agains :)

**Comment by corneliusroemer** [comment] 2020-12-16 16:47
@6543  try.gitea.com doesn't work for me, do I need to have some sort of permission or anything else to access it?

**Comment by jolheiser** [comment] 2020-12-16 16:48
It should be [try.gitea.io](https://try.gitea.io/)

**Comment by sploders101** [comment] 2020-12-16 16:50
try.gitea.io works for me now. Thank you!

**Comment by corneliusroemer** [comment] 2020-12-16 16:54
Yes, it works on mobile now - though autocorrect does not work on the body.

Body text is never automatically corrected by auto correct, in contrast to normal text fields. Presumably a remaining issue with EasyMDE on mobile.

**Comment by 6543** [comment] 2020-12-16 17:06
ok so this specific issue is "solved".

next step would be #10729

I'll close this for now :)

**Closed as completed by 6543** 2020-12-16 17:06 UTC
Labels: type/bug, topic/ui
