### ISSUE TITLE
Webhook sent twice when using Add File on Gitea repo

### ISSUE THREAD

**Issue by maxifom** [go-gitea/gitea#7543] opened 2019-07-20 10:42 UTC
- Gitea version (or commit ref): 1.9.0+rc2-2-g91e24a3a1
- Git version: not needed
- Operating system: Docker container on system 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linu
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL): https://try.gitea.io/qwkemklqkelqw/test
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
```
[Macaron] 2019-07-20 10:29:28: Started GET /username/repo/_new/master/sdf123 for MYIP
[Macaron] 2019-07-20 10:29:28: Completed GET /username/repo/_new/master/sdf123 200 OK in 11.289231ms

[Macaron] 2019-07-20 10:29:28: Started POST /username/repo/_new/master/ for MYIP

[Macaron] 2019-07-20 10:29:29: Started GET /api/internal/hook/pre-receive/username/repo?old=xxxxxxxxxxxxxxxxxxxxxxxx&new=xxxxxxxxxxxxxxxxxxxxxxxx&ref=refs%2Fheads%2Fmaster&userID=1&gitObjectDirectory=%2Fdata%2Fgit%2Frepositories%2Fusername%2Frepo.git%2F.%2Fobjects%2Fincoming-gpBOgg&gitAlternativeObjectDirectories=%2Fdata%2Fgit%2Frepositories%2Fusername%2Frepo.git%2F.%2Fobjects&prID=0 for 127.0.0.1

[Macaron] 2019-07-20 10:29:29: Completed GET /api/internal/hook/pre-receive/username/repo?old=xxxxxxxxxxxxxxxxxxxxxxxx&new=xxxxxxxxxxxxxxxxxxxxxxxx&ref=refs%2Fheads%2Fmaster&userID=1&gitObjectDirectory=%2Fdata%2Fgit%2Frepositories%2Fusername%2Frepo.git%2F.%2Fobjects%2Fincoming-gpBOgg&gitAlternativeObjectDirectories=%2Fdata%2Fgit%2Frepositories%2Fusername%2Frepo.git%2F.%2Fobjects&prID=0 200 OK in 1.858148ms

[Macaron] 2019-07-20 10:29:29: Started GET /api/internal/hook/post-receive/username/repo?old=xxxxxxxxxxxxxxxxxxxxxxxx&new=xxxxxxxxxxxxxxxxxxxxxxxx&ref=refs%2Fheads%2Fmaster&userID=1&username=username for 127.0.0.1

[Macaron] 2019-07-20 10:29:29: Completed GET /api/internal/hook/post-receive/username/repo?old=xxxxxxxxxxxxxxxxxxxxxxxx&new=xxxxxxxxxxxxxxxxxxxxxxxx&ref=refs%2Fheads%2Fmaster&userID=1&username=username 200 OK in 34.672842ms
```
## Screenshots

![Screenshot from 2019-07-20 15-39-28](https://user-images.githubusercontent.com/20924207/61577706-959faf80-ab04-11e9-8131-8d51f96720d9.png)

**Comment by lunny** [comment] 2019-07-21 14:58
This should be fixed by #7511

**Comment by lafriks** [comment] 2019-07-21 20:47
Please reopen if not fixed by #7511

**Closed as completed by lafriks** 2019-07-21 20:47 UTC

**Comment by matrozov** [comment] 2019-11-26 23:53
Please reopen. Reproduced on the version 1.11.0

**Comment by lunny** [comment] 2019-11-27 01:18
@matrozov Please submit a new issue and give some detail. Since webhooks have been changed a lot on v1.11, I think that maybe another reason.
