### ISSUE TITLE
Private Repo not available after update

### ISSUE THREAD

**Issue by mrbesen** [go-gitea/gitea#4426] opened 2018-07-11 17:43 UTC
- Gitea version (or commit ref): c784ac5
- Operating system: Ubuntu Server 16.04.04 LTS
- Git version: 2.7.4
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
```
2018/07/11 19:30:06 [I] Log Mode: File(Info)
2018/07/11 19:30:06 [I] XORM Log Mode: File(Info)
2018/07/11 19:30:06 [I] Cache Service Enabled
2018/07/11 19:30:06 [I] Session Service Enabled
2018/07/11 19:30:07 [I] Git Version: 2.7.4
2018/07/11 19:30:07 [I] SQLite3 Supported
2018/07/11 19:30:07 [I] Run Mode: Production
2018/07/11 19:30:07 [I] SSH server started on :2222. Cipher list ([aes128-ctr aes192-ctr aes256-ctr aes128-gcm@openssh.com arcfour256 arcfour128]), key exchange algorithms ([diffie-hellman-group1-sha1 diffie-hellman-group14-sha1 ecdh-sha2-nistp256 ecdh-sha2-nistp384 ecdh-sha2-nistp521 curve25519-sha256@libssh.org]), MACs ([hmac-sha2-256-etm@openssh.com hmac-sha2-256 hmac-sha1 hmac-sha1-96])
2018/07/11 19:30:07 [I] Listen: http://127.0.0.1:3000
2018/07/11 19:32:12 [...routers/repo/view.go:299 Home()] [E] Home: Du hast keine Berechtigung, um auf irgendeinen Bereich dieses Repositories zuzugreifen.
2018/07/11 19:35:51 [...routers/repo/view.go:299 Home()] [E] Home: Du hast keine Berechtigung, um auf irgendeinen Bereich dieses Repositories zuzugreifen.
```
## Description
I recently Updated gitea from 1.0.2 to 1.5 now i noticed, that all of my private repositories are not available (404-Error). But they show up on the list of my repositories and they show up in the administrative view but i get the same error. I tried to re-login, because i thought it might be a problem with the session, but it does not help.
I have a organisation with a private repo, which just works fine,

## Screenshots
Admin view:
![grafik](https://user-images.githubusercontent.com/8640309/42589545-98623628-8541-11e8-987d-aa9aed859f78.png)
Siede view:
![grafik](https://user-images.githubusercontent.com/8640309/42589586-c845b7ca-8541-11e8-90d0-2d17d3e06347.png)

**Comment by lafriks** [comment] 2018-07-11 22:12
Duplicate of #1794
See comment https://github.com/go-gitea/gitea/issues/1794#issuecomment-348717495 on how to fix this

**Closed as completed** 2018-07-11 22:16 UTC
Labels: issue/duplicate
