### ISSUE TITLE
Update repository last updated time when syncing mirror

### ISSUE THREAD

**Issue by pgaskin** [go-gitea/gitea#2054] opened 2017-06-24 23:17 UTC
- Gitea version (or commit ref): 1.1.0

The repository last updated time should be updated when a mirror is synced with new commits.

**Comment by cez81** [comment] 2017-06-25 11:40
Duplicate of https://github.com/go-gitea/gitea/issues/1329. I have added a GetLatestCommitTime (https://github.com/go-gitea/git/pull/45) put haven't got round to fix this yet.

**Closed as completed** 2017-06-25 14:53 UTC
Labels: issue/duplicate
