### ISSUE TITLE
Github migration fails with error 500 when issue comment is too long

### ISSUE THREAD

**Issue by ashimokawa** [go-gitea/gitea#7905] opened 2019-08-18 10:03 UTC
- Gitea version (or commit ref): g2d0b90c96
- Git version: 2.20.1
- Operating system: Debian 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Trying to migrate https://github.com/Freeyourgadget/Gadgetbridge to codeberg-test.org running gitea master yields error 500 with the following in log:

`
2019/08/18 11:50:58 routers/repo/repo.go:320:MigratePost() [E] MigratePost: Error 1406: Data too long for column 'content' at row 1
`

**Comment by typeless** [comment] 2019-08-22 11:37
According to https://dev.mysql.com/doc/refman/5.7/en/string-type-overview.html
The maximum length of [the TEXT type](https://github.com/go-gitea/gitea/blob/master/////models/issue_comment.go#L126) is 64KiB.
If the problem is indeed due to a very long text, we can probably use LONGTEXT for MySQL.
I am not sure if an ORM can fine-tune this for different DBMS.

**Comment by lunny** [comment] 2019-08-22 16:08
Comment content have ~64KB size. Isn't it enough for almost all the situation?

**Comment by ashimokawa** [comment] 2019-08-23 05:35
@lunny 
Yes, 64KB ought to be enough for everyone.
Anyway, I got that error above and that should not happen.
I will investigate which post exactly triggers the problem.
In any case 500 should be prevented by cutting off the text at a valid utf-8 boundary.

**Comment by guillep2k** [comment] 2019-08-23 05:56
I agree. The 64K limit sounds reasonable. But whatever the limit, we should check the available size before inserting. A post-migration list of warnings explaining what compromises had to be made during migration would be ideal, so the admin will be aware of the problems and can take corrective/compensatory actions.

**Comment by typeless** [comment] 2019-08-23 06:01
Besides a warning in the log, We can maybe reserve a little space to insert a line like `----- cut here, comment length exceeding 64KB -----\n`  when the text is too long.

**Comment by ashimokawa** [comment] 2019-09-24 08:49
OK, I think found out why this does not fail hard on try.gitea.io but on my test instance.
sql mode is strict on my server, so exceeding column size fails hard, but is just truncated when sql mode is more relaxed (I assume this is the case on try.gitea.io)

Nevertheless, comment size is bigger on github, so we should somehow handle this.

I added a quick hack to slice the string in go, and it worked. But doing this properly on a Rune boundary is the way to I assume.

**Comment by lunny** [comment] 2019-09-27 07:35
We need a PR to check comment size before insert it to database.

**Comment by ashimokawa** [comment] 2019-09-28 09:37
@lunny 
This is what I did locally, but I think someone with more proficiency in go should do the PR which checks the Rune boundary. Just cutting bytes is not nice.

**Comment by wxiaoguang** [comment] 2022-01-28 07:52
The issue comment problem has been fixed in 1.16

* https://github.com/go-gitea/gitea/pull/16765

**Closed as completed by wxiaoguang** 2022-01-28 07:52 UTC
Labels: type/bug, issue/confirmed
