### ISSUE TITLE
Cancel mirror process not possible

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#15108] opened 2021-03-22 17:08 UTC
- Gitea version (or commit ref): 1.13.4
- Git version:
- Operating system: Ubuntu 20.04.2
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

I have a long running mirror process which can't be canceled.

![image](https://user-images.githubusercontent.com/8334250/112029418-8541a280-8b39-11eb-85db-1aed486ef75f.png)

![image](https://user-images.githubusercontent.com/8334250/112029450-8d014700-8b39-11eb-97eb-1166d3a16e63.png)

Try this ~20 times

**Comment by lunny** [comment] 2021-03-23 01:41
Should be resolved by #12917

**Comment by techknowlogick** [comment] 2021-03-23 02:12
Closing as dupe of https://github.com/go-gitea/gitea/issues/12845

**Closed as completed by techknowlogick** 2021-03-23 02:12 UTC
Labels: issue/duplicate
