### ISSUE TITLE
Do not show Add file button if user has no rights to add files to repo

### ISSUE THREAD

**Issue by lafriks** [go-gitea/gitea#21179] opened 2022-09-15 21:00 UTC
### Description

Currently button with empty submenu is shown

### Gitea Version

1.17.2

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Not relevant

**Comment by wolfogre** [comment] 2022-09-27 03:54
I believe it has been fixed by #20718, and backport #20719 has been merged too.

I can't reproduce the error on v1.17.2, maybe this is a false positive?

**Comment by lunny** [comment] 2022-12-12 12:55
I can confirm this has been fixed in branch v1.17.

**Closed as completed by lunny** 2022-12-12 12:55 UTC
Labels: type/bug, topic/ui, issue/needs-feedback
