### ISSUE TITLE
Extraneous '>' introduced in diff

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#14506] opened 2021-01-28 12:01 UTC
Correct diff: https://try.gitea.io/silverwind/symlink-test/commit/d0c0659f1313d935e2934ae74a6d47c2c234d665

<img width="187" alt="image" src="https://user-images.githubusercontent.com/115237/106135856-c2f10300-6168-11eb-98fe-c4d6dcfb5ff4.png">

Incorrect diff: https://try.gitea.io/silverwind/symlink-test/commit/3debed8064253858d45cacc554d1b5ddca36051a

<img width="199" alt="image" src="https://user-images.githubusercontent.com/115237/106135876-cb493e00-6168-11eb-8a58-4e9c6590baec.png">

The `>` is not part of the actual diff and is being introduced by our diff code. The only difference in the examples above is the file extension of the updated file.

cc: @mrsdizzie

**Comment by zeripath** [comment] 2021-01-28 19:09
I think this is a duplicate of #14231

I think :

https://github.com/go-gitea/gitea/issues/14231#issuecomment-757361996

points towards a solution

**Closed as completed by zeripath** 2021-01-28 19:09 UTC
Labels: type/bug, issue/duplicate
