### ISSUE TITLE
Link this package to a repository issue

### ISSUE THREAD

**Issue by arkadiuszmakarenko** [go-gitea/gitea#23118] opened 2023-02-24 12:33 UTC
### Description

On Packages Settings page under Link this package to a repository dropdown listing repositories which can be linked do not display all repositories in organization. It appears that only last 30 of them are listed?
It doesn't allow me to link package to all needed repositories. 

### Gitea Version

1.18.4

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

2.39.1

### Operating System

windows

### How are you running Gitea?

It is deployed as a service with IIS reverse proxy.
GoGit build.

### Database

SQLite

**Comment by KN4CK3R** [comment] 2023-02-24 23:56
Duplicate of #22749

**Closed as completed by KN4CK3R** 2023-02-24 23:56 UTC
Labels: type/bug, issue/duplicate, topic/packages
