### ISSUE TITLE
"Commit Graph" report 500 error

### ISSUE THREAD

**Issue by feb-cloud** [go-gitea/gitea#15784] opened 2021-05-08 07:08 UTC
On the premise, I upgraded by directly replacing the ".exe" file. After upgrading, I found that clicking "Commit Graph" to report 500 errors, which was not clear. Is this a BUG, maybe it is my operation problem?I don't know if anyone has had this problem.
PS: My English language ability is very poor. The content of this question was translated by the software machine. I'm not sure whether the description of my question is clear or not.

**Comment by zeripath** [comment] 2021-05-08 07:35
Hi. Unfortunately this bug report is not very useful as it does not provide enough information to identify or reproduce the issue or even the version of Gitea that is affected. We have an issue template for a reason.

We need at least:

* What version of Gitea?
* Are you able to reproduce on try.gitea.io?
* What are the logs? Please read https://docs.gitea.io/en-us/logging-configuration/#debugging-problems

My suspicion is that this a duplicate report of a bug that is already fixed and that will be in 1.14.2 (coming very soon) but without the above basic information - I'm afraid this is a totally inadequate report.

You may find it easier to ask for help on one of the specific language channels on discord.

**Comment by Tao-Ya** [comment] 2021-05-08 09:03
Hi, thank you very much for your prompt reply. I just checked the version number, which is "1.14.0". I forgot the previous version.However, thank you very much for your reply. I will wait for the release of version 1.14.2 and try it, because it does not have much impact on my use.

**Comment by 6543** [comment] 2021-05-09 11:09
@PyBillowJiang v1.14.2 got released

**Closed as completed** 2021-05-10 00:51 UTC
Labels: issue/needs-feedback
