### ISSUE TITLE
Creating dependency for pull requests via API

### ISSUE THREAD

**Issue by suchAdemon** [go-gitea/gitea#17794] opened 2021-11-24 09:57 UTC
Would it be possible to get an API call which allows you to create dependencies between pull requests?

- Example 1: Two pull request are open, user curls API call with something like that:
`curl -X POST https://giteaserver/api/v1/repos/{owner}/{repo}/pulls/{index}  -H "accept: application/json" -H "Content-Type: application/json" -d "{ 'dependency': '<index_of_pull_request_to_depend_on>' }"`

- Example 2: One pull requests already exists and a second one gets opened by user with API call like that:
`curl -X POST https://giteaserver/api/v1/repos/{owner}/{repo}/pulls -H "accept: application/json" -H "Content-Type: application/json" -d "{<... already defined data for ceating pullrequest ...> , 'dependency': '<index_of_pull_request_to_depend_on>' }"`

This would help in automating pull request which are depending on other pull request a lot.

**Comment by qwerty287** [comment] 2021-11-27 18:19
Duplicate of https://github.com/go-gitea/gitea/issues/15393?

**Closed as completed** 2021-11-28 07:05 UTC
Labels: issue/duplicate
