### ISSUE TITLE
The markdown text in the dashboard entries of comments of pull requests is not rendered

### ISSUE THREAD

**Issue by shaoran** [go-gitea/gitea#11245] opened 2020-04-29 11:07 UTC
- Gitea version (or commit ref): 1.11.4
- Git version: 2.20.1
- Operating system: Debian 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes https://try.gitea.io/
  - [ ] No
  - [ ] Not relevant

## Description

When you open Gitea the dashboard is displayed which shows a brief history of
the contributions like who committed what and where, comments of pull requests,
etc.

The comments of pull requests however are not properly rendered using Markdown,
the raw text is displayed instead, see attached screenshot. The pull request
page itself does it correctly, so the problem is in the dashboard page.

## Screenshots

![][1]

[1]: https://user-images.githubusercontent.com/113313/80589033-b98c0c00-8a19-11ea-99b0-b6bc95cfb7dd.png

**Comment by zeripath** [comment] 2020-04-30 11:45
it's not that that it's not all rendered - it's simply that it is not rendered as markdown at all.

The reasoning is simple - how do you prevent the comment notification from completely messing up the appearance of the notifications list?

**Comment by guillep2k** [comment] 2020-05-02 06:13
Closing as it works as intended.

**Closed as completed by guillep2k** 2020-05-02 06:13 UTC
Labels: issue/not-a-bug

**Comment by shaoran** [comment] 2020-05-02 11:06
> The reasoning is simple - how do you prevent the comment notification from completely messing up the appearance of the notifications list?

don't you have the same issue on the *Conversation* tab of the pull requests? Why is that different?

**Comment by guillep2k** [comment] 2020-05-03 15:00
@shaoran because it's only a fragment, not the whole comment. And Markdown can contain tables, lists, images, and all sort of things. The intention is to provide some brief context without cluttering the view.

Example of Markdown I wouldn't want rendered in my dashboard:

# Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

## Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

- Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
- Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
