### ISSUE TITLE
Getting access denied on repository ownership transfer

### ISSUE THREAD

**Issue by hiteshnayak305** [go-gitea/gitea#8620] opened 2019-10-21 21:32 UTC
- Gitea version (or commit ref): master
- Git version: Git Version: 2.23.0
- Operating system: windows 10 19002 build
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist: https://gist.github.com/hiteshnayak305/f1ab8c6128bdf23ff064b2efa842ca1d

## Description
i am not able to transfer repositories ownership. getting access denied permission.
On windows platform installed on D:\

`hites` is admin user in pc.
gitea config includes `RUN_USER = hites`
...

**Comment by jolheiser** [comment] 2019-10-21 21:39
Duplicate of #7947

**Comment by zeripath** [comment] 2019-10-22 09:50
Presuming that Gitea definitely has permission to make these changes and that this isn't simply a permissions issue, I'm going to close this as a duplicate.

**Closed as completed by zeripath** 2019-10-22 09:50 UTC
Labels: issue/duplicate
