### ISSUE TITLE
File picker broken

### ISSUE THREAD

**Issue by gempir** [go-gitea/gitea#23593] opened 2023-03-20 13:48 UTC
### Description

The file picker in a PR has a tiny height and is effectively useless. Tested on 1.19.0 was not broken on 1.19.0-rc1

Example test PR
https://try.gitea.io/gempir/gempbot/pulls/1/files

### Gitea Version

1.19.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![image](https://user-images.githubusercontent.com/9765622/226359042-3e0de1ef-bfa6-4a81-b0e1-9315993f7bf2.png)

![image](https://user-images.githubusercontent.com/9765622/226359471-26f118ca-0417-4d91-baa5-235b5c0070fb.png)

### How are you running Gitea?

systemd

### Database

None

**Comment by gempir** [comment] 2023-03-20 14:09
I did add screenshots, maybe they were not clear enough? 

I don't really see how a PR with a scrollbar in the File Picker is an edge case to me that's a regular occurence, as we noticed this regression like 2 hours after upgrading.

**Comment by silverwind** [comment] 2023-03-20 14:11
"Edge case" is probably not the best term, but I mean the bug does not show in all cases.

**Comment by wxiaoguang** [comment] 2023-03-20 14:15
> I did add screenshots, maybe they were not clear enough?

Sorry for bothering, at first I just thought that "expanding" doesn't work well with some height, so I confirmed again that it seems only related to the height & scrolling ..... (correct me if I am wrong)

**Comment by wxiaoguang** [comment] 2023-03-20 14:38
I guess it's still somewhat related to the LESS->CSS (the change itself is good and right, but maybe some old bugs are triggered?)

According to my test, before: 202803fc69d21763a06d8d0f5a4c46509c18f6f1 , the tree-list just works (I can't reproduce the height bug), after 202803fc69d21763a06d8d0f5a4c46509c18f6f1 , I can 100% reproduce it .... strange.

I just don't understand what causes the problem ..... I will spend some time on it to see if we can find the root problem, to avoid other potential bugs.

**Comment by silverwind** [comment] 2023-03-20 15:21
Yes, it is a regression from #23554 and  #23553 will fix it.

**Comment by wxiaoguang** [comment] 2023-03-23 04:02
The fix for 1.19 (#23616) has been merged.

You can get 1.19 latest from https://dl.gitea.com/gitea/1.19/ , or docker gitea:1.19-dev

These contain the fix.

**Closed as completed** 2023-03-23 05:10 UTC
Labels: type/bug

**Comment by gempir** [comment] 2023-03-23 09:45
Will there be no 1.19.1 release ?

**Comment by wxiaoguang** [comment] 2023-03-23 09:47
There will be. Using  1.19-dev is the most convenient way to get bug fixes quickly before 1.19.1 gets released.

All fixed in 1.19-dev will be included in 1.19.1


After 1.19.1 gets release, then 1.19-dev is for next 1.19.2
