### ISSUE TITLE
ORM engine initialization Error: migrate: Row size too large

### ISSUE THREAD

**Issue by Whisprin** [go-gitea/gitea#9347] opened 2019-12-13 10:26 UTC
- Gitea version (or commit ref): 1.10.0
- Git version: 2.24.1
- Operating system: Linux (Arch)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
https://gist.github.com/Whisprin/69ec124abec9fb94fbe713e32f5a652a

## Description

After upgrading from Gitea v1.9.5 to 1.10.0 I'm getting a database migration error:
`ORM engine initialization attempt #8/10 failed. Error: migrate: do migrate: Error 1118: Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs`

**Comment by zeripath** [comment] 2019-12-15 00:55
What version of MySQL are you running?

**Comment by Whisprin** [comment] 2019-12-15 09:34
@zeripath 
```
% mariadb --version
mariadb  Ver 15.1 Distrib 10.4.11-MariaDB, for Linux (x86_64) using readline 5.1
```

**Comment by Whisprin** [comment] 2019-12-15 10:35
@zeripath Why did you close this issue? I only described a manual workaround, the issue persists 

This should be part of the database migration / maintenance script of gitea. Apparently gitea requires a certain row format which is not explicitly specified during table creation.

**Comment by zeripath** [comment] 2019-12-15 22:00
As far as I could see the issue is specific to old versions of MariaDB. I'm but certain there's really any way we can go about detecting this.

**Comment by Whisprin** [comment] 2019-12-16 12:23
The issue is independent of the MariaDB version in a sense that upgrading the database doesn't help. Specific MariaDB default configurations are required and tables which existed before need to be converted manually.
From my point of view gitea requires certain db features which are not explicitly specified or documented.

* MariaDB specific documentation can be added in the docs
    * that's something I could work on
* Prior to running migrations gitea can check the INFORMATION_SCHEMA table and print a meaningful warning
    * may be something I can contribute
* An automatic migration can convert all gitea tables. There's no harm in converting tables, that are already in the correct format

**Comment by jacksgt** [comment] 2020-02-20 13:17
I just had the same issue upgrading from Gitea 1.10.2 to 1.11.1 with MariaDB version 10.3.22

This should really be part of the automatic upgrade process.

**Comment by sapk** [comment] 2020-02-20 14:50
This should be added to the docs and maybe the check could be in doctor command first and if stable move to the web startup process.

**Comment by guillep2k** [comment] 2020-02-20 17:20
We could also add a function (step independent) to the migration function that attempts to create row with a deliberately big length, then delete it. If that fails, we could abort the process, warn the user and point them to the docs.

**Comment by leetNightshade** [comment] 2020-03-04 06:48
I upgraded from 1.6 to 1.11 and am having this issue. I tried running the manual fix as suggested above, but I'm still seeing the same error. 

`2020/03/04 06:45:24 ...ations/migrations.go:330:Migrate() [I] Migration[77]: add theme to users
 2020/03/04 06:45:24 ...orm/dialect_mysql.go:431:GetTables() [I] [SQL] SELECT `TABLE_NAME`, `ENGINE`, `TABLE_ROWS`, `AUTO_INCREMENT`, `TABLE_COMMENT` from `INFORMATION_SCHEMA`.`TABLES` WHERE `TABLE_SCHEMA`=?     AND (`ENGINE`='MyISAM' OR `ENGINE` = 'InnoDB' OR `ENGINE` = 'TokuDB') [gitea]
 2020/03/04 06:45:24 ...orm/dialect_mysql.go:320:GetColumns() [I] [SQL] SELECT `COLUMN_NAME`, `IS_NULLABLE`, `COLUMN_DEFAULT`, `COLUMN_TYPE`, `COLUMN_KEY`, `EXTRA`,`COLUMN_COMMENT` FROM `INFORMATION_SCHEMA`.     `COLUMNS` WHERE `TABLE_SCHEMA` = ? AND `TABLE_NAME` = ? [gitea user]
 2020/03/04 06:45:24 ...orm/dialect_mysql.go:460:GetIndexes() [I] [SQL] SELECT `INDEX_NAME`, `NON_UNIQUE`, `COLUMN_NAME` FROM `INFORMATION_SCHEMA`.`STATISTICS` WHERE `TABLE_SCHEMA` = ? AND `TABLE_NAME` = ?       [gitea user]
 2020/03/04 06:45:24 .../xorm/session_raw.go:196:exec() [I] [SQL] ALTER TABLE `user` ADD `theme` VARCHAR(30) DEFAULT '' NOT NULL ; - took: 3.750008ms
 2020/03/04 06:45:24 routers/init.go:72:initDBEngine() [E] ORM engine initialization attempt #1/10 failed. Error: migrate: do migrate: Error 1118: Row size too large. The maximum row size for the used table      type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs`

**Comment by guillep2k** [comment] 2020-03-04 07:36
@leetNightshade Can I suggest looking at [these answers](https://stackoverflow.com/a/51255047/225979) from SO?

**Comment by leetNightshade** [comment] 2020-03-11 21:00
> 
> 
> @leetNightshade Can I suggest looking at [these answers](https://stackoverflow.com/a/51255047/225979) from SO?

"Variable 'innodb_file_format' is a read only variable." Those answers aren't helpful to someone who doesn't know what they're doing. Gitea created this problem, why aren't you guys solving it?

**Comment by 6543** [comment] 2020-03-11 23:07
@leetNightshade what version of MySql do you run?

**Comment by guillep2k** [comment] 2020-03-11 23:11
@leetNightshade I'm sorry you didn't find that link useful. Unfortunately that's a limitation of MySQL/MariaDB. AFAICT the problem you are facing [is very common](https://mariadb.com/kb/en/troubleshooting-row-size-too-large-errors-with-innodb/) for databases created with old versions of those products. "Modern" versions of MySQL/MariaDB don't have this problem. What you need to do is to upgrade your engine and look for a way of converting your tables to a newer format.

I'd suggest you perform a backup and upgrade to the latest database engine version possible (e.g. MariaDB 10.4.12). You can then export your database with `mysqldump`, modify the backup [as instructed here](https://stackoverflow.com/a/60172908/225979), and import it back (you'll need to update the script and change `DB=""` for `DB="gitea"` or whatever is the name of your database).

**Comment by leetNightshade** [comment] 2020-03-12 00:38
I'm running: mariadb  Ver 15.1 Distrib 10.4.12-MariaDB, for Linux (x86_64) using readline 5.1

**Comment by 6543** [comment] 2020-03-12 00:43
@leetNightshade just try what guillep2k suggested and the try it again - would be nice if you can tell us the result

**Comment by guillep2k** [comment] 2020-03-12 04:47
> 
> 
> I'm running: mariadb Ver 15.1 Distrib 10.4.12-MariaDB, for Linux (x86_64) using readline 5.1

Nice! 😄. The original poster had one, but I didn't know what you had.

So, you need to stop Gitea (make sure no gitea processes keep running, even if it seems to have stopped), and export/transform/re-import the database (assuming your database name is `gitea`):

```
mysqldump -u root -p gitea > original.sql
sed 's:ROW_FORMAT=COMPACT:ROW_FORMAT=DYNAMIC:g' original.sql > modified.sql
mysql -u root -p gitea < modified.sql
```

You will be prompted for the root user's password two times. The `original.sql` script remains as a normal backup in case of trouble. Save a copy of `original.sql` for safekeeping purposes.

**Comment by leetNightshade** [comment] 2020-03-25 18:28
*That* did the trick, thank you @guillep2k !!

**Comment by zeripath** [comment] 2020-03-25 23:03
So we can finally close this issue - which is a fault with MySQL not Gitea - I guess we should put this little script in the FAQ.

**Comment by Whisprin** [comment] 2020-03-26 10:05
It's not a fault with MySQL, it works as intended. It's a fault of how Gitea is using MySQL and a missing migration. If you need ROW_FORMAT=DYNAMIC specify it explicitly during table creation or at least please mention it in the documentation that dynamic is the expected row format. @zeripath @lunny

**Comment by lafriks** [comment] 2020-03-26 10:45
I added PR to set that for new installations and new tables. Existing tables won't be fixed and @guillep2k script should be used instead.

**Comment by Whisprin** [comment] 2020-03-26 11:33
Awesome @lafriks 
Do you think it would be possible to add the migration or just a message to prompt the user to the doctor command as @sapk suggested earlier?

**Comment by lafriks** [comment] 2020-03-26 12:08
Migration is not really possible to implement as it requires dumping database and reimport. It would be enough to add that to FAQ as @zeripath suggested imho

**Comment by Whisprin** [comment] 2020-03-26 12:15
Using ALTER_TABLE the row format can be changed with MySQL built in commands without dumping and reimporting. See comment: https://github.com/go-gitea/gitea/issues/9347#issuecomment-565792626

**Closed as completed** 2020-03-27 08:44 UTC
Labels: type/docs, issue/confirmed

**Comment by devurandom** [comment] 2020-05-24 17:47
> ```
> # take a backup of the database
> 
> MariaDB> USE INFORMATION_SCHEMA;
> 
> # change row format
> # this creates a list of SQL commands, run each manually
> MariaDB> SELECT CONCAT("ALTER TABLE `", TABLE_SCHEMA,"`.`", TABLE_NAME, "` ROW_FORMAT=DYNAMIC;") AS MySQLCMD FROM TABLES WHERE TABLE_SCHEMA = "gitea";
> 
> # change collation, character set
> # this creates a list of SQL commands, run each manually
> MariaDB> SELECT CONCAT("ALTER TABLE `", TABLE_SCHEMA,"`.`", TABLE_NAME, "` CONVERT TO CHARACTER SET utf8mb4;") AS MySQLCMD FROM TABLES WHERE TABLE_SCHEMA = "gitea";
> ```

Thanks, @Whisprin, that worked and made my Gitea server usable again!

**Comment by zeripath** [comment] 2020-05-25 06:42
Or you could have just used `gitea convert`

https://docs.gitea.io/en-us/command-line/#convert

**Comment by mlthlschr** [comment] 2020-07-31 20:33
did not work for me, neither using `gitea convert`, nor using the proposal of @Whisprin. Using
