### ISSUE TITLE
Time of action in the commit table is incorrect.

### ISSUE THREAD

**Issue by Colin5887** [go-gitea/gitea#14215] opened 2021-01-02 02:59 UTC
- Gitea version (or commit ref): from 1.10 to 1.13
- Git version: ?
- Operating system: Raspberry pi
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description
Looks like the table of contributions uses the UTC+0 time instead of the timezone of the server or the timezone of users.

Here, an activity is made 4 minutes ago but it's logged as yesterday's work
![image](https://user-images.githubusercontent.com/30656548/103449859-5bc76680-4d02-11eb-993b-df623513cb25.png)

I tried to set the timezone as mentioned in https://docs.gitea.io/en-us/config-cheat-sheet/ and I'm 100% sure it does not work. The `Time` setting in the config only changes the time displayed when the mouse hovers on the commit, not on the table.

I live in UTC+10 and all of my commissions before 10:00 are marked to the day before.
...

**Comment by noerw** [comment] 2021-03-24 22:33
this is a duplicate of https://github.com/go-gitea/gitea/issues/6087, closing

**Closed as completed by noerw** 2021-03-24 22:33 UTC
Labels: type/bug, issue/duplicate
