### ISSUE TITLE
Gitea 1.1.0 docker image throws panic errors on startup 

### ISSUE THREAD

**Issue by TheRaz** [go-gitea/gitea#1391] opened 2017-03-27 12:59 UTC
- Gitea version (or commit ref): 1.1.0
- Git version: 2.8.3
- Operating system: Debian 8
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: https://gist.github.com/TheRaz/f0527ea6f69f84c38db34c056fb3e483

## Description

When the gitea docker 1.1.0 image is started it starts throwing go panic errors, the errors does not occur on 1.1 or 1.0 image, log goes into infinite loop and gitea wont start.

The image has been working for around 10 days after update before the errors started.

**Comment by sapk** [comment] 2017-04-30 14:08
Hi, since there were some update on the docker image done.
Is this bug still existing ?

**Comment by ptman** [comment] 2017-05-04 07:16
I don't have a problem with the docker image, so something is still missing before anyone can reproduce it.

**Comment by TheRaz** [comment] 2017-05-04 07:58
Sorry for the late answer, I'm no longer with the same employer so i can't reproduce this error again. The panic occurred as soon as the docker image loaded but that's all the info i still have access to.
My guess is that it was caused by some problem with the saved data as it only occurred after 10 days of running the image.

**Comment by DblK** [comment] 2017-05-22 14:58
Can we close this issue?

**Closed as completed** 2017-05-22 15:14 UTC
Labels: type/bug
