### ISSUE TITLE
Can not choose branch after create PR again

### ISSUE THREAD

**Issue by melmus** [go-gitea/gitea#13849] opened 2020-12-04 16:46 UTC
- Gitea version (or commit ref):
1.14.0+dev-225-g5bd05331c
1.14.0+dev-315-gbb50ab286
- Git version:
2.26.2
- Operating system:
Ubuntu 18.04.5 LTS
Gitea running in docker
  
  
  
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description
Hi! Early i created issue https://github.com/go-gitea/gitea/issues/12879 and now i see problem again.

**Comment by jolheiser** [comment] 2020-12-04 16:51
What version of Gitea are you using? 

I am able to change the branch on try.

**Comment by melmus** [comment] 2020-12-04 16:56
@jolheiser  i'm sorry, update issue

**Comment by melmus** [comment] 2020-12-25 08:33
@jolheiser 

> "I am able to change the branch on try."


What are you version? I update gitea, my version: 

> 1.14.0+dev-454-g19ae6439b

But i can't change branch after create PR, may be problem in database

**Comment by melmus** [comment] 2020-12-25 08:44
I fond some problem: https://github.com/go-gitea/gitea/issues/13684

**Comment by zeripath** [comment] 2020-12-28 21:01
OK when you say you can't change the branch - what do you mean exactly?

* Can you not find the option?
* If you attempt to change it it fails?
* Are there any logs on Gitea produced?
* Are there any javascript console logs?

**Comment by lakostin** [comment] 2021-01-12 15:37
Looks like it's a duplicate of #13684

**Comment by lunny** [comment] 2021-01-14 02:44
Let's continue on #13684

**Closed as completed by lunny** 2021-01-14 02:44 UTC
Labels: issue/duplicate, issue/needs-feedback
