### ISSUE TITLE
U2F Block In app.ini Causes A Segfault

### ISSUE THREAD

**Issue by TheDarkula** [go-gitea/gitea#5394] opened 2018-11-23 23:24 UTC
- Gitea version (or commit ref): 1.6.0-rc2
- Git version: 2.18.0
- Operating system: Arch Linux
- Database (use `[x]`):
  - [x] PostgreSQL
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
```
gitea_1_aab4d095f851 | gitea.default(SV): Starting service as user=git, group=git
gitea_1_aab4d095f851 | gitea.default(O): panic: runtime error: invalid memory address or nil pointer dereference
gitea_1_aab4d095f851 | gitea.default(O): [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x7f3cd4]
gitea_1_aab4d095f851 | gitea.default(O): 
gitea_1_aab4d095f851 | gitea.default(O): goroutine 1 [running]:
gitea_1_aab4d095f851 | gitea.default(O): code.gitea.io/gitea/vendor/gopkg.in/ini%2ev1.(*Key).transformValue(0xc000577b60, 0xc0000bf681, 0x28, 0xc0004eee08, 0x4a9909)
gitea_1_aab4d095f851 | gitea.default(O): 	/hab/cache/src/src/code.gitea.io/gitea/vendor/gopkg.in/ini.v1/key.go:123 +0xa4
gitea_1_aab4d095f851 | gitea.default(O): code.gitea.io/gitea/vendor/gopkg.in/ini%2ev1.(*Key).String(0xc000577b60, 0xc000574fa0, 0x15)
gitea_1_aab4d095f851 | gitea.default(O): 	/hab/cache/src/src/code.gitea.io/gitea/vendor/gopkg.in/ini.v1/key.go:130 +0x3d
gitea_1_aab4d095f851 | gitea.default(O): code.gitea.io/gitea/vendor/gopkg.in/ini%2ev1.(*Key).MustString(0xc000577b60, 0xc000574fa0, 0x15, 0x1, 0xc000574fa0)
gitea_1_aab4d095f851 | gitea.default(O): 	/hab/cache/src/src/code.gitea.io/gitea/vendor/gopkg.in/ini.v1/key.go:202 +0x2f
gitea_1_aab4d095f851 | gitea.default(O): code.gitea.io/gitea/modules/setting.NewContext()
gitea_1_aab4d095f851 | gitea.default(O): 	/hab/cache/src/src/code.gitea.io/gitea/modules/setting/setting.go:1194 +0x489f
gitea_1_aab4d095f851 | gitea.default(O): code.gitea.io/gitea/routers.GlobalInit()
gitea_1_aab4d095f851 | gitea.default(O): 	/hab/cache/src/src/code.gitea.io/gitea/routers/init.go:47 +0x4a
gitea_1_aab4d095f851 | gitea.default(O): code.gitea.io/gitea/cmd.runWeb(0xc000114640, 0x0, 0x0)
gitea_1_aab4d095f851 | gitea.default(O): 	/hab/cache/src/src/code.gitea.io/gitea/cmd/web.go:112 +0xaa
gitea_1_aab4d095f851 | gitea.default(O): code.gitea.io/gitea/vendor/github.com/urfave/cli.HandleAction(0x1273460, 0x14769c8, 0xc000114640, 0xc000163700, 0x0)
gitea_1_aab4d095f851 | gitea.default(O): 	/hab/cache/src/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/app.go:471 +0xad
gitea_1_aab4d095f851 | gitea.default(O): code.gitea.io/gitea/vendor/github.com/urfave/cli.Command.Run(0x1402587, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1428727, 0x16, 0x0, ...)
gitea_1_aab4d095f851 | gitea.default(O): 	/hab/cache/src/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/command.go:191 +0x96d
gitea_1_aab4d095f851 | gitea.default(O): code.gitea.io/gitea/vendor/github.com/urfave/cli.(*App).Run(0xc0000ca9c0, 0xc0000ae040, 0x4, 0x4, 0x0, 0x0)
gitea_1_aab4d095f851 | gitea.default(O): 	/hab/cache/src/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/app.go:241 +0x5a2
gitea_1_aab4d095f851 | gitea.default(O): main.main()
gitea_1_aab4d095f851 | gitea.default(O): 	/hab/cache/src/src/code.gitea.io/gitea/main.go:53 +0x3d1
gitea_1_aab4d095f851 | hab-launch(SV): Child for service 'gitea.default' with PID 122 exited with code exit code: 2
```

## Description
In `app.ini`, when using the default configuration block:
```
[U2F]
; Two Factor authentication with security keys
; https://developers.yubico.com/U2F/App_ID.html
APP_ID = %(PROTOCOL)s://%(DOMAIN)s:%(HTTP_PORT)s/
; Comma seperated list of truisted facets
TRUSTED_FACETS = %(PROTOCOL)s://%(DOMAIN)s:%(HTTP_PORT)s/
```
gitea segfaults with the above log output.

**Comment by lafriks** [comment] 2018-11-24 11:10
I think there is already issue for this

**Comment by lafriks** [comment] 2018-11-24 11:11
Duplicate of #4692

**Closed as completed by lafriks** 2018-11-24 11:11 UTC
Labels: issue/duplicate

**Comment by TheDarkula** [comment] 2018-11-24 14:49
Ah, didn't catch that one.
