### ISSUE TITLE
Firefox broken in 1.14.2

### ISSUE THREAD

**Issue by sjdrc** [go-gitea/gitea#15930] opened 2021-05-20 05:06 UTC
- Gitea version (or commit ref): 1.14.2
- Git version:
- Operating system: Ubuntu 18.04
  
  
  
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
- Log gist:

## Description

We were previously on 1.13.5 and everything was working as expected.

After updating (through docker) to 1.14.2, a lot of functionality is not working in firefox. Fonts and text spacing is all broken, and we are unable to delete releases (the confirm dialog doesn't show uo) or create new PRs in firefox.

I cant roll back to 1.13.5 due to database version incompatibility.

**Comment by lunny** [comment] 2021-05-20 06:22
I cannot reproduce this on master e5723d655

**Comment by silverwind** [comment] 2021-05-20 10:55
We had this issue before, it's related to emoji fonts and only shows on Ubuntu. I think https://github.com/go-gitea/gitea/pull/15855 is slated for 1.12.3 which might fix it, please try that patch.

**Comment by silverwind** [comment] 2021-05-21 19:08
Pretty positive this was fixed by https://github.com/go-gitea/gitea/pull/15855 and its backport. We had the same issue the last time in https://github.com/go-gitea/gitea/pull/13834 which moved `sans-serif` before the emoji fonts.

**Closed as completed by silverwind** 2021-05-21 19:08 UTC
Labels: issue/needs-feedback

**Comment by sjdrc** [comment] 2021-05-31 03:47
So when will the fix for this go live?

**Comment by silverwind** [comment] 2021-05-31 07:52
With 1.14.3, whenever it is ready.

**Comment by sjdrc** [comment] 2021-05-31 08:46
Cool, thanks.

In the meantime, installing `fonts-noto` has solved the problem for me.
