### ISSUE TITLE
Update failed if the `website` field is carried, when requesting `/user/settings` interface.

### ISSUE THREAD

**Issue by yixiubest** [go-gitea/gitea#30518] opened 2024-04-16 07:41 UTC
### Description

The request is:

`curl -X 'PATCH' \
  'https://172.16.161.221:8080/api/v1/user/settings' \
  -H 'accept: application/json' \
  -H 'authorization: Basic cm9vdDp6ZHd3QDIwMjQ=' \
  -H 'Content-Type: application/json' \
  -d '{
  "description": "",
  "location": "",
  "language": "zh-CN",
  "theme": "auto",
  "full_name": "root",
  "diff_view_style": "",
  "hide_email": true,
  "hide_activity": false,
  "website": "gitea.com"
}'`

The result is:

![image](https://github.com/go-gitea/gitea/assets/38375081/699f1a26-3902-487c-a65e-fae25ac937ce)

Is the parameter value wrong or  Is it a bug?

### Gitea Version

1.21.7

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

docker

### Database

None

**Comment by lunny** [comment] 2024-04-16 09:41
Website should be `https://gitea.com`.

**Comment by Gitttttttt** [comment] 2024-04-17 01:22
@lunny I hava tryied, but got the same error:
![image](https://github.com/go-gitea/gitea/assets/38375081/3f60ee83-4d09-4149-8d4d-eb664f8c9c37)

**Comment by lunny** [comment] 2024-04-17 07:49
I cannot reproduce this and I create a test PR in #30539. Maybe you can upgrade to 1.21.11 and try again?

**Comment by Gitttttttt** [comment] 2024-04-24 02:00
@lunny I upgraded to 1.21.11 and tried again, but it's still the same error.
The version:
![image](https://github.com/go-gitea/gitea/assets/38375081/3a56951c-712c-4741-b957-8f515bd8fefc)

The request:
![image](https://github.com/go-gitea/gitea/assets/38375081/28a2ca32-001b-43b7-9f02-bba3e17d9eb3)

The response:
![image](https://github.com/go-gitea/gitea/assets/38375081/3e5cdda4-acd4-41da-9d42-d48efea68d85)

**Comment by lunny** [comment] 2024-04-24 02:16
Please input `token <your_token>` in `AuthorizationHeaderToken (apiKey)` of the `Authorized` and try again.

**Comment by Gitttttttt** [comment] 2024-04-24 02:33
@lunny Like this? Seems to be the same result:

![image](https://github.com/go-gitea/gitea/assets/38375081/0ec7eb07-68fc-4795-b3dd-3f87ebb1d932)

**Comment by lunny** [comment] 2024-04-24 02:41
Can you get the information about this request/response from Gitea's log?

**Comment by Gitttttttt** [comment] 2024-04-24 03:02
@lunny The log only like this:
![image](https://github.com/go-gitea/gitea/assets/38375081/0ca22fc4-eb9d-4107-a2b5-6449ea2ad5a3)

`2024/04/24 11:01:08 ...eb/routing/logger.go:102:func1() [I] router: completed PATCH /api/v1/user/settings for 172.16.60.73:54290, 422 Unprocessable Entity in 32.4ms @ v1/api.go:689(v1.Routes.func1.7.1.bind[...])`

**Comment by wxiaoguang** [comment] 2024-04-24 04:45
It is a bug of `go-chi/binding`.

Main branch doesn't have such bug because its dependency has been upgrade.

On 1.21 branch, run `go get gitea.com/go-chi/binding` then build a new binary, then there won't be such bug.

**Comment by lunny** [comment] 2024-05-13 05:34
Fixed by #30742

**Closed as completed by lunny** 2024-05-13 05:34 UTC
Labels: type/bug, issue/confirmed, type/upstream
