### ISSUE TITLE
Expose metrics on metrics port

### ISSUE THREAD

**Issue by JosefWN** [go-gitea/gitea#14277] opened 2021-01-07 11:11 UTC
It would be nice if the metrics endpoint was exposed on the default Prometheus metrics port (9090), or on a configurable metrics port. Since I have an ingress mapping to the http port of Gitea, they get exposed externally unless I explicitly prevent it in the ingress.

**Comment by lunny** [comment] 2021-01-07 13:30
I think it's easy to configure the endpoint than server. There are already serval ports on Gitea. It seems this is unnecessary.

**Comment by lafriks** [comment] 2021-01-07 22:03
Metrics should be exposed on `/metrics` endpoint as that is most common imho

**Comment by JosefWN** [comment] 2021-01-07 22:41
> Metrics should be exposed on /metrics endpoint as that is most common imho

I agree, but just like `pprof` commonly uses port 6060, the `/metrics` endpoint for Prometheus is most commonly exposed on port 9090 (I think because that's the port Prometheus itself is using), or sometimes on other ports in the 9xxx range, but not on `HTTP_PORT` for applications that are exposed to the internet.

This clearly separates endpoints intended from internal use, from external endpoints. It gets a bit messy to manage in the ingress in k8s for example, especially if your ingress helm template supports multiple ingress controllers.

**Comment by techknowlogick** [comment] 2021-01-08 00:41
>  applications that are exposed to the internet.

For that reason we have the ability to protect `/metrics` by using token auth.

> It gets a bit messy to manage in the ingress in k8s

To simplify things for your k8s setup, would make the Gitea codebase more messy. Personally I use a black-hole service for the public ingress for that specific route, and then have prom pull for a service that it has access internal to the cluster.

I'm going to close this, however if another maintainer feels strongly they are free to re-open to continue discussion.

**Closed as completed by techknowlogick** 2021-01-08 00:41 UTC

**Comment by zeripath** [comment] 2021-01-10 09:18
So... I think there is a wider issue here - we do need to consider having at least the option of having internal things listening on a different port.

Similarly there are repeated "issues" whereby a server administrator wants gitea to recognise internal and external IPs differently essentially having different root URLs.

You're right though - the issue is one of configuration: how can we have a concise, clear and non ambiguous, backwards compatible configuration that allows for this?

Any issue/feature request that does not provide such a proposed configuration is simply unhelpful. The configuration is the problem - the implementation would not actually be that difficult, if only a little tiresome.
