### ISSUE TITLE
Unexpected connection loss when cloning via https with slow bandwidth

### ISSUE THREAD

**Issue by ashimokawa** [go-gitea/gitea#16055] opened 2021-06-02 17:21 UTC
- Gitea version (or commit ref): lastest 1.14 and latest main
- Git version: 2.29
- Operating system: Debian 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL)
  - [ ] No

## Description

When cloning a repository with slow bandwidth over https, gitea seems to timeout.
We noticed that because F-Droid fails to checkout repositories from codeberg.org, there is also a issue on Codeberg here: https://codeberg.org/Codeberg/Community/issues/461.

This seems to affect try.gitea.io also. Timeouts seem to happen after a few minutes, but not always after the same time. We tried to increase git.timeout values on our test instance also, also accessed port 3000 directly without reverse proxy, without any effect.
```
$ sudo wondershaper enp0s31f6 4000 4000 # somehow values do not really matter, anything between 500-4000 had the same effect
$ time git clone https://try.gitea.io/ashi/Gadgetbridge
Klone nach 'Gadgetbridge' ...
remote: Enumerating objects: 92096, done.
remote: Counting objects: 100% (92096/92096), done.
remote: Compressing objects: 100% (22562/22562), done.
error: 5767 Bytes des Bodys werden noch erwartet | 12.00 KiB/s
fetch-pack: unexpected disconnect while reading sideband packet
fatal: zu frühes Dateiende
fatal: fetch-pack: ungültige index-pack Ausgabe

real    1m31,925s
user    0m0,005s
sys     0m0,025s

```

**Comment by fnetX** [comment] 2021-06-02 21:25
Because the description is not clear on this: We reproduced with serving assets from Gitea public folder, too. https://codeberg.org/Codeberg/Community/issues/460 is most likely related, too.

**Comment by zeripath** [comment] 2021-06-02 21:33
We really need to see some logs from the gitea side of things.

**Comment by fnetX** [comment] 2021-06-02 22:22
Oh sure, sorry, we only shared them in our internal infrastructure groups ... :see_no_evil: 

~~~
root@codeberg:~# grep -E '2021/06/02 06.*RPC\(upload-pack\)' /data/git/log/gitea.log
2021/06/02 06:07:40 routers/repo/http.go:556:serviceRPC() [E] Fail to serve RPC(upload-pack) in /data/git/gitea-repositories/kollo/x11-basic.git: signal: broken pipe - 
2021/06/02 06:09:53 routers/repo/http.go:556:serviceRPC() [E] Fail to serve RPC(upload-pack) in /data/git/gitea-repositories/kollo/x11-basic.git: signal: broken pipe - 
2021/06/02 06:10:05 routers/repo/http.go:556:serviceRPC() [E] Fail to serve RPC(upload-pack) in /data/git/gitea-repositories/gitnex/gitnex.git: signal: broken pipe - 
2021/06/02 06:10:35 routers/repo/http.go:556:serviceRPC() [E] Fail to serve RPC(upload-pack) in /data/git/gitea-repositories/gitnex/gitnex.git: signal: broken pipe - 
2021/06/02 06:12:09 routers/repo/http.go:556:serviceRPC() [E] Fail to serve RPC(upload-pack) in /data/git/gitea-repositories/hjacobs/kube-resource-report.git: exit status 128 - fatal: the remote end hung up unexpectedly
2021/06/02 06:17:27 routers/repo/http.go:556:serviceRPC() [E] Fail to serve RPC(upload-pack) in /data/git/gitea-repositories/nexttracks/android.git: signal: broken pipe - 
2021/06/02 06:18:53 routers/repo/http.go:556:serviceRPC() [E] Fail to serve RPC(upload-pack) in /data/git/gitea-repositories/nexttracks/android.git: signal: broken pipe - 
2021/06/02 06:21:01 routers/repo/http.go:556:serviceRPC() [E] Fail to serve RPC(upload-pack) in /data/git/gitea-repositories/freeyourgadget/gadgetbridge.git: signal: broken pipe - 
2021/06/02 06:22:46 routers/repo/http.go:556:serviceRPC() [E] Fail to serve RPC(upload-pack) in /data/git/gitea-repositories/freeyourgadget/gadgetbridge.git: signal: broken pipe - 
2021/06/02 06:33:16 routers/repo/http.go:556:serviceRPC() [E] Fail to serve RPC(upload-pack) in /data/git/gitea-repositories/oppenlab/ariane.git: signal: broken pipe - 
2021/06/02 06:39:18 routers/repo/http.go:556:serviceRPC() [E] Fail to serve RPC(upload-pack) in /data/git/gitea-repositories/corona-contact-tracing-germany/cwa-android.git: signal: broken pipe - 
2021/06/02 06:42:56 routers/repo/http.go:556:serviceRPC() [E] Fail to serve RPC(upload-pack) in /data/git/gitea-repositories/stoptheccp/ccp-database-leak.git: signal: broken pipe - 
root@codeberg:~# 
~~~

This was the final thing we grepped because of the reports related to FDroid repos. We saw more broken pipes, but expected them to being unrelated, we noticed later that also normal file transfers fail. I'll check the logs again with this information.

**Comment by fnetX** [comment] 2021-06-02 22:44
Hmm, the canceling file downloads don't seem to appear in the logs, will play with the loglevels once more.

But basically, we're seeing this broken pipe issue, on slow throughput or when halting the download (I'm using ctrl+z and fg from time to time when reproducing locally when I don't want to throttle my full machine)

We were already looking for some timeout, but found none left to configure.
Using haproxy for connections to other backends (e.g. file serving from nginx) works fine. Direct access to Gitea via the local port results in the same issue.

Oh and I just noticed the error log from OP is translated, the English version would look like
~~~
error: 7158 bytes of body are still expected29 MiB | 487.00 KiB/s
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: index-pack failed
~~~

**Comment by zeripath** [comment] 2021-06-02 23:25
Ok your logs imply to me that the response writer is being closed independently of the upload pack. 

So ... If we're sure it's not coming from a proxy it must be being closed further down within gitea.

Now, we know that long running connections are allowed because the event stream doesn't have this problem. So there's maybe something that the event stream is setting on the response that is preventing this early close?

I guess it would be helpful to know if you're running with the inbuilt gzip handler or other config?

**Comment by zeripath** [comment] 2021-06-02 23:29
In particular we set:

 https://github.com/go-gitea/gitea/blob/c1ff59c1cd51da6fcc47d31ca84932e9bccced92/routers/events/events.go#L29

Which we don't set in http.

So a good guess might be to set that after this line here:

https://github.com/go-gitea/gitea/blob/c1ff59c1cd51da6fcc47d31ca84932e9bccced92/routers/repo/http.go#L439

**Comment by fnetX** [comment] 2021-06-02 23:31
We didn't change the GZIP config. In case you have questions about the codeberg config and don't want to wait for a reply, you can usually look at https://codeberg.org/Codeberg/build-deploy-gitea/src/branch/master/etc/gitea/conf/app.ini - in case this is easier for you.

Please keep in mind that normal file transfer seemed to show this very same issue (e.g. downloading a big file from gitea/public). Maybe a similiarity between repo and other connections (public serving + most likely file attachments) gives you a hint?

**Comment by zeripath** [comment] 2021-06-02 23:56
I think it's all similar as I don't think we set the keep alive header on those either so it's worth checking if the above suggestion solves things.

If it does then we can add in the keep alive command elsewhere or everywhere. 

If it doesn't then at least we know it's not that.

**Comment by ashimokawa** [comment] 2021-06-03 07:24
@zeripath 
added the keepalive header as suggested. Didn't help.

Since this affects try.gitea.io also we should not distract ourselves by digging into codeberg specific configs.

**Comment by 6543** [comment] 2021-06-04 16:00
just an idear of mine: could it be an regression of the **macaron -> chi migration** ?

**Comment by zeripath** [comment] 2021-06-04 16:54
@6543 that's my suspicion too and why I was asking specifically about things like HTTP keep alive etc.

**Comment by fnetX** [comment] 2021-06-04 18:01
@6543 I already started searching for the regression commit, but as I told youon Matrix I won't find time looking into more details until tonight, but I wanted to share some first results early, maybe you can already make use of them:

Good news - Release 1.14.2 seems not to be affected, so the bug wasn't delivered to end users (but Codeberg, shame on us for living on the edge). The release branch is. So maybe you have an idea what changed in between?

Also from the log:
~~~
2021/06/04 19:53:34 ...les/public/public.go:165:handle() [I] [Static] Serving /many-zeroes
2021/06/04 19:53:39 Completed GET /many-zeroes 200 OK in 5.01920503s
~~~
Before this timeout was shown AFTER the transfer stopped (e.g. `Completed GET /many-zeroes 200 OK in 11m56.011945691s`). As you can see, this returned early (after five seconds apparently) while the actual transfer timed out after 51 seconds with
~~~
2021-06-04 19:54:25 (50.1 KB/s) - Connection closed at byte 2621440. Giving up.
~~~

The file is 100MB of size.

**Comment by fnetX** [comment] 2021-06-04 18:16
Well, nevermind, I just finished the bisect, have a look at this commit: 41422f0df06be53d9ae8e16e385f03b81bd47f51

    Add timeout to writing to responses (#15831) (#15872)
    
    Backport #15831
    
    In #15826 it has become apparent that there are a few occasions when a response can
    hang during writing, and because there is no timeout go will happily just block
    interminably. This PR adds a fixed 5 second timeout to all writes to a connection.
    
    Fix #15826
    
    Signed-off-by: Andrew Thornton <art27@cantab.net>

Sounds obvious ...

**Comment by fnetX** [comment] 2021-06-04 18:21
The idea behind this makes sense, but I assume that there is some kind of network buffer, so the deadline isn't extended on slow connections, because the buffer isn't cleared on time?

That'd explain our observation, that it's not a fixed timeout - cloning huge repos on a fast connection worked just fine (probably because the buffer is refilled every <5s)? No clue about how this is handled deeper in the code or framework, I was just looking at this specific commit right now.

@zeripath

**Comment by zeripath** [comment] 2021-06-04 18:45
Aha!

**Comment by zeripath** [comment] 2021-06-04 18:47
So I think we still need this timeout - otherwise go will happily hold on to the connections when the connection is blocked.

I guess we just need to increase the length of this timeout.

**Comment by zeripath** [comment] 2021-06-04 18:50
So through compiling you can trial a few different values as I state in the PR:

LDFLAGS="-X \"code.gitea.io/gitea/modules/graceful.PerWriteWriteTimeout=30s\""

one other option is whether we should just tie the ResponseWriter to the request context?

**Comment by fnetX** [comment] 2021-06-04 18:55
Yes, we're doing exactly this right now.

I think, with this we mainly shift the curve, kinda like a threshold how slow a connection can become ... not sure if there is a better solution like knowing exactly if it's still alive or something ...

I also don't quite know the impact of the main issue. Would it be an option to set it really high, like a few minutes, so that only really stale connections are cleaned? Personally, I know that it's sometimes convenient when a network transfer continues, even when the connection was disrupted for a short time.

**Comment by fnetX** [comment] 2021-06-04 18:58
So I think there is some kind of function: the larger the blob to transfer and the slower the connection, the easier this will be hit. Remember I was running into this with 50KB/s transfer on a 100MB file after 5 seconds. I'd imagine that when you increase this to 60 seconds, but my transfer wouldn't have been finished, this would result in the same issue, but later (will try). With higher bandwidth but larger data, this should stay proportional.

**Comment by zeripath** [comment] 2021-06-04 20:01
OK, let's do a heuristic adjustment.

Couple of ideas:

1. Simplest: Store the last deadline that we set 
  * Minimum deadline is Now()+ 5s
  * If previous deadline has not passed use it instead of now + 5s 
  * PROBLEMS: This could be lead to very very long timeouts - but I guess that is reasonable. 
  * There's also no depenedence on the size of slice being written or how much written just on how many times written
2. Take account of what's about to be written plus the last timeout
  * Minimum basic timeout is 5s 
  * Timeout: is 2.5s + 0.25s * len(towrite)/1024 + previous deadline if this is longer
3. Take account of the amount written:
   * Minimum basic timeout is 5s
   * Timeout: is 0.25s * len(towrite + written)/1024 + previous deadline

**Comment by zeripath** [comment] 2021-06-04 20:16
```go
From 5387504d0e3ac1558668867b9a7c0df1ff78df52 Mon Sep 17 00:00:00 2001
From: Andrew Thornton <art27@cantab.net>
Date: Fri, 4 Jun 2021 21:15:25 +0100
Subject: [PATCH] Set self-adjusting deadline for connection writing

Fix #16055

Signed-off-by: Andrew Thornton <art27@cantab.net>

diff --git a/modules/graceful/server.go b/modules/graceful/server.go
index 26195c632..07f51de3e 100644
--- a/modules/graceful/server.go
+++ b/modules/graceful/server.go
@@ -31,6 +31,9 @@ var (
 // PerWriteWriteTimeout timeout for writes
 const PerWriteWriteTimeout = 5 * time.Second
 
+// PerWriteWriteTimeoutKbRate is a timeout taking account of how much there is to be written
+const PerWriteWriteTimeoutKbRate = 2 * time.Second
+
 func init() {
 	DefaultMaxHeaderBytes = 0 // use http.DefaultMaxHeaderBytes - which currently is 1 << 20 (1MB)
 }
@@ -249,13 +252,19 @@ func (wl *wrappedListener) File() (*os.File, error) {
 
 type wrappedConn struct {
 	net.Conn
-	server *Server
-	closed *int32
+	server   *Server
+	closed   *int32
+	deadline time.Time
 }
 
 func (w wrappedConn) Write(p []byte) (n int, err error) {
 	if PerWriteWriteTimeout > 0 {
-		_ = w.Conn.SetWriteDeadline(time.Now().Add(PerWriteWriteTimeout))
+		minDeadline := time.Now().Add(PerWriteWriteTimeout)
+		nextDeadline := w.deadline.Add(PerWriteWriteTimeout/2 + time.Duration(len(p)/1024)*PerWriteWriteTimeoutKbRate)
+		if minDeadline.After(nextDeadline) {
+			nextDeadline = minDeadline
+		}
+		_ = w.Conn.SetWriteDeadline(nextDeadline)
 	}
 	return w.Conn.Write(p)
 }
-- 
2.31.1

```

Is basically option 2 there.

**Comment by zeripath** [comment] 2021-06-04 21:35
Ugh the patch above is broken but I can't fix it on my phone - the pr should apply on to 1.14 cleanly

**Comment by fnetX** [comment] 2021-06-04 21:40
Yeah, I noticed this already. We are going for patching the timeout for the moment and wait for a proper fix then, don't hurry. We weren't able to use the build flag to override the setting.

**Closed as completed** 2021-06-10 21:25 UTC
Labels: type/bug
