### ISSUE TITLE
API interface support for renaming branch names

### ISSUE THREAD

**Issue by inbjo** [go-gitea/gitea#32324] opened 2024-10-23 04:23 UTC
### Feature Description

Hi all, I need to manipulate multiple repositories via API interface, e.g. create branch, delete branch. But I didn't find an interface to change the branch name. It is possible to rename a branch on the repository page. I hope the api interface will add support for this. Thanks to the development team.

**Comment by kemzeb** [comment] 2024-11-06 08:23
This is a duplicate of #22526

**Closed as not planned by kemzeb** 2024-11-06 08:23 UTC
Labels: issue/duplicate, type/proposal, topic/api
