### ISSUE TITLE
[Bug Report] Commits Bug

### ISSUE THREAD

**Issue by AaronS8** [go-gitea/gitea#18685] opened 2022-02-09 11:21 UTC
### Gitea Version

1.17

### Git Version

2.33

### Operating System

Windows 10

### How are you running Gitea?

Installed form gitea download packages for windows

### Database

MSSQL

### Can you reproduce the bug on the Gitea demo site?

Yes

###  Bug
1. Commits are shown as on the deleted orginal branches instead of on the current branch
2.  commits are duplicated sometimes

###  try.gitea.io
https://try.gitea.io/arons8/ComTest/commits/branch/master

### First Screenshot List of commits on master branch

![Git Commit list](https://user-images.githubusercontent.com/98172519/153186329-7a2d5ea4-9591-4456-8545-85b0e773c53e.jpg)
### a commit on the master branch showing as on pull/1/head when it should show on master

![Gitea Commit 6](https://user-images.githubusercontent.com/98172519/153186541-57598ff0-d1bc-423d-9f19-16d2b2a55839.jpg)
![Gitea commit 5](https://user-images.githubusercontent.com/98172519/153186692-77f3d5a0-b4b0-4d7b-879e-61562eee427d.jpg)

### GitHub Screenshots
![Screenshot 2022-02-09 124606](https://user-images.githubusercontent.com/98172519/153187533-94469530-56aa-4ccf-8163-048d56541124.jpg)

![Git Hub Commit 3](https://user-images.githubusercontent.com/98172519/153188966-73d12430-e55b-4432-b74b-c03475ca5075.jpg)

**Comment by lunny** [comment] 2022-02-09 15:53
Are they the same repository? Could you also paste the github's link?

**Comment by zeripath** [comment] 2022-02-09 19:26
I just don't understand what the issue is you're reporting. Can you please explain clearly what is happening.

Your screenshots do not tell me what the problem is nor can I determine it from the linked try.gitea.io repository.

**Comment by AaronS8** [comment] 2022-02-10 08:51
@lunny they aren't the same repository, but they are similar here's the link https://github.com/AaronS8/GitTes.

**Comment by AaronS8** [comment] 2022-02-10 09:10
@zeripath sorry for uplodding not clear screenshots, but here is my explanation

### On the Gitea Screenshots

1. first screen shot shows the list of commits on master branch
2. on the second screenshot is a commit on master branch were it's merged from pull request and delete that branch after merge, it's showing as it's on pull/1/head instead of **master**
3.  I think's this feature is added for convince of collabrators but I just want to make sure the last commit on the master brach is actualy an empty commit( meaning there is no change or whats over) but it's shows as there're commits(Changes made) **This's not only on Gitea, but on almost all Git Softwares and GitHub** the only ones I found that show it as an empty are "Git GUI" and Microsoft Visual Studio.

**Comment by zeripath** [comment] 2022-02-10 09:46
So this isn't a bug. This is a feature request.

You want to see all the branches that contain this commit not just the nearest branch.

**Comment by AaronS8** [comment] 2022-02-10 10:46
No!!!, it's not a feature request , shouldn't the pull request merge be shown as it on **master** branch not on **pull/1/head** as I've opened the commit on master.

### This is on Gitea
![gitea03](https://user-images.githubusercontent.com/98172519/153390170-4994d28e-4a9b-43b6-a647-00c6776ed9fc.jpg)

### This on Github
![github02](https://user-images.githubusercontent.com/98172519/153390429-ca6fc771-f232-49e3-93f9-ad300dbcefd8.jpg)

> 3. I think's this feature is added for convince of collabrators but I just want to make sure the last commit on the master brach is actualy an empty commit( meaning there is no change or whats over) but it's shows as there're commits(Changes made) **This's not only on Gitea, but on almost all Git Softwares and GitHub** the only ones I found that show it as an empty are "Git GUI" and Microsoft Visual Studio.

**Comment by LecrisUT** [comment] 2022-02-18 14:07
If you look at the [commit graph](https://try.gitea.io/arons8/ComTest/graph), you can see why the commits are marked as a different branch. You would see a similar view in gitkraken if you could access those internal branches. If you do not want it like this, do either a rebase merge or squash merge. Gitea needs to keep internal record of the branch for this situation or the squash version for the PR view.

Having it like this makes much more sense because you can track the branches from which each commit split and merged back. But if you do not care about that, and just want to clean up the graph view to a singular line, I would rather suggest the feature of deleting some or all of the internal branches. Personally I would be against that because it has the potential to create too many problems, and you can do that via rebase and force push as well I think.

**Closed as completed** 2022-03-01 15:06 UTC
Labels: issue/needs-feedback
