### ISSUE TITLE
adopting linux repo from existing local mirror repo causes 500

### ISSUE THREAD

**Issue by muhamad** [go-gitea/gitea#29043] opened 2024-02-04 06:27 UTC
### Description

I'm using `git version 2.43.0.windows.1`  and `gitea 1.21.5`

I do have a local bare mirror linux kernel repo from https://github.com/torvalds/linux and I get the following error

![error](https://github.com/go-gitea/gitea/assets/16896516/25a6699b-d300-43dc-915a-8e9b6da02c94)

even when I try to clone it directly from GitHub using GitHub migration I still get the same error.

### Gitea Version

1.21.5

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

2.43.0

### Operating System

Windows 10 22H2

### How are you running Gitea?

As a windows service using SQLite as my backend.

### Database

SQLite

**Comment by lunny** [comment] 2024-02-04 13:05
2.6.11 doesn't exist on github https://github.com/torvalds/linux/tags?after=v2.6.12-rc3

**Comment by wxiaoguang** [comment] 2024-02-04 13:21
Also see this:  unable to PushUpdateAddTag to Repo: unable to get tag Commit: object does not exist #28843 

And maybe this: slice bounds out of range in function: /modules/git.newSignatureFromCommitline #28840

**Comment by lunny** [comment] 2024-02-04 13:24
duplicate of #28843

**Closed as completed by lunny** 2024-02-04 13:24 UTC
Labels: type/bug

**Comment by muhamad** [comment] 2024-02-04 17:51
@lunny I understand that tag 2.6.11 doesn't exist, Shouldn't gitea ignore such error and continue on migration?

**Comment by lunny** [comment] 2024-02-05 04:34
> @lunny I understand that tag 2.6.11 doesn't exist, Shouldn't gitea ignore such error and continue on migration?

I think we can do that in a PR. Let's follow #28843
