### ISSUE TITLE
Imposible to add gogs webhook

### ISSUE THREAD

**Issue by zorn-v** [go-gitea/gitea#11458] opened 2020-05-17 13:44 UTC
- Gitea version (or commit ref): 1.11.5
- Git version: 2.24.3
- Operating system: gitea/gitea:1 docker image
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

When try to add new gogs webhook there is a error "ContentType can not be empty"

## Screenshots

![изображение](https://user-images.githubusercontent.com/12619075/82148782-39c6c400-9898-11ea-844f-6f845a7918f8.png)

**Comment by zorn-v** [comment] 2020-05-17 14:17
There is no selection for content type in gogs hook creation
![изображение](https://user-images.githubusercontent.com/12619075/82150875-e0ad5f00-989c-11ea-969b-b6fcb2406c43.png)
but seems gitea hook is compatible so I use them

**Comment by mrsdizzie** [comment] 2020-05-17 16:04
This was fixed but not backported to 1.11 for some reason:

https://github.com/go-gitea/gitea/issues/9504
https://github.com/go-gitea/gitea/pull/10456

**Comment by zeripath** [comment] 2020-05-17 16:47
Thanks @mrsdizzie I've sent a backport!

**Comment by lafriks** [comment] 2020-05-17 16:52
Duplicate of #9504

**Closed as completed by lafriks** 2020-05-17 16:52 UTC
Labels: issue/duplicate
