### ISSUE TITLE
Setting DEFAULT_THEME = gitea does not use light "gitea" theme

### ISSUE THREAD

**Issue by binarydad** [go-gitea/gitea#18631] opened 2022-02-06 05:50 UTC
### Gitea Version

1.16.0

### How are you running Gitea?

Docker

### Can you reproduce the bug on the Gitea demo site?

No

### Description

I have the following set in the app.ini file for the container, but when restarting (and even recreating) the container, the default theme for someone who is NOT logged in is still dark. 

```
DEFAULT_THEME = gitea
```

### Screenshots

![image](https://user-images.githubusercontent.com/1760607/152669318-b7d9de16-c9ca-42b1-8240-7c855fcee8dc.png)

**Comment by lunny** [comment] 2022-02-06 07:31
```ini
[ui]
DEFAULT_THEME = gitea
THEMES = auto,gitea,arc-green
```

**Comment by ki9us** [comment] 2023-04-02 22:24
Not sure if I'm having the same problem as op, but for me, when I start or restart the docker container with `-v ./data:/data`, it overwrites my `DEFAULT_THEME` setting to `arc-green`, but oddly doesn't overwrite my modified `THEMES` setting.

**Comment by denyskon** [comment] 2023-07-01 05:52
As lunny wrote in https://github.com/go-gitea/gitea/issues/18631#issuecomment-1030769440 , the setting needs to be set in `[ui]` and also the light theme needs to be enabled on your instance. I tried it with 1.19 and 1.20-rc on two different instances and can't reproduce your problem.

I'm closing this for now, feel free to reopen if you still have the issue and can give some more information.

**Closed as completed** 2023-07-01 05:53 UTC
Labels: type/bug
