### ISSUE TITLE
Transfer Repository from user to organization fails

### ISSUE THREAD

**Issue by realslacker** [go-gitea/gitea#8565] opened 2019-10-17 19:35 UTC
- Gitea version (or commit ref): 1.9.3 and 1.9.4
- Git version: 2.21.0.windows.1
- Operating system: Windows Server 2012 R2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:
    https://gist.github.com/realslacker/c0340d93d313dc25b0ef4898dcdc05d6

## Description

Transferring a repo from a user to an organization fails with error 500 on latest Gitea running on Windows.

The suspect log entry appears to be:

    2019/10/17 14:24:29 ...ters/repo/setting.go:378:SettingsPost() [E] TransferOwnership: rename repository directory: rename D:\gitea\repositories\user\repo.git D:\gitea\repositories\infrastructure-team\repo.git: Access is denied.

The Gitea service is running as LocalSystem, and SYSTEM has full rights to the D:\gitea folder and all sub-folders. I'm able to psexec -i -s cmd.exe and move folders inside the repositories folder so permissions do not seem to be an issue.

**Comment by guillep2k** [comment] 2019-10-17 19:36
Duplicate of #7947

**Closed as completed** 2019-10-18 06:39 UTC
Labels: issue/duplicate
