### ISSUE TITLE
MySQL: Internal server error 500 when request changes in a code review with non ascii characters in comment

### ISSUE THREAD

**Issue by ratuka** [go-gitea/gitea#7043] opened 2019-05-25 18:12 UTC
- Gitea version (or commit ref): 1.8.1
- Git version: not relevant
- Operating system: not relevant
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

2019/05/25 18:02:15 [.../repo/pull_review.go:170 SubmitReview()] [E] UpdateReview: Error 1366: Incorrect string value: '\xC5\x9 1l v\xC3...' for column 'content' at row 1
2019/05/25 18:02:15 [D] Template: status/500

**Comment by zeripath** [comment] 2019-05-25 18:20
this is likely to be yet another mysql utf8 table format issue. You need to change your tables to utf8mb4.

**Comment by ratuka** [comment] 2019-05-25 18:50
Could it be a solution but why does it work in a lot of other places?

**Comment by lafriks** [comment] 2019-05-25 22:08
Duplicate of #6236

**Closed as completed** 2019-05-25 22:08 UTC
Labels: issue/duplicate

**Comment by lafriks** [comment] 2019-05-25 22:09
Please reopen if this different issue
