### ISSUE TITLE
User can add more commits to PR after gaining approval

### ISSUE THREAD

**Issue by browcio** [go-gitea/gitea#8439] opened 2019-10-09 12:15 UTC
- Gitea version (or commit ref): 1.9.4
- Git version:    2.17.1
- Operating system: ubuntu 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (https://try.gitea.io/ppiwowa2/testrepo/pulls/1)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
We observe that user can add more commits to existing approved PR. After that PR remains approved and can be merged despite new commits not being reviewed.

Steps to reproduce:
1. fork repo
2. commit to fork
3. create PR
4. get your PR approved
5. add more commits to fork
6. merge

This way only first commit was reviewed but all commits can be merged. I suspect that gitea should at least inform that some commits were not reviewed.

**Comment by davidsvantesson** [comment] 2019-10-09 17:36
I think this should be the standard behaviour, but a new setting could be added. In Github this is called "Dismiss stale pull request approvals when new commits are pushed."

**Comment by jolheiser** [comment] 2019-10-09 17:41
Similar, possible duplicate of #5997

**Comment by lafriks** [comment] 2019-10-09 18:52
Yes, duplicate of #5997

**Closed as completed by lafriks** 2019-10-09 18:52 UTC
Labels: issue/duplicate
