### ISSUE TITLE
PR section is extremly slow and buggy after update to 1.14.0 on windows server

### ISSUE THREAD

**Issue by tautf** [go-gitea/gitea#15423] opened 2021-04-12 09:21 UTC
- Gitea version (or commit ref): 1.14.0
- Operating system: Windows Server 2019 Std.
  
- Using the lates amd64 binary package, with the installation instructions as a service from gitea.io
  
  
- Database (use `[x]`):
  - [x] PostgreSQL

## Description

First: Gitea.log does not show anything useful, its just spammed with sql statements

Running on Gitea 1.14.0 with the amd64 binary, the PR-section came extremly slow and it seems to be buggy.
- When you are watching a pr:
  - It takes about 3-4 times longer to open it:
  - Viewing commits and changed files also takes 3-4 times longer
  - The preview of you comment doenst work, it will always show `Loading...`
  - You cant upload any images to a pr as comment
  - On a pr, you cant logout, its running forever and your still logged in

Only Errors i could find are the following:
![Bildschirmfoto 2021-04-12 um 11 14 13](https://user-images.githubusercontent.com/18403881/114371346-af0e4800-9b80-11eb-973e-6baa64f1e194.png)

## Screenshots
Screenshot of the comment section as it alway looks after updating to 1.14.0
![Bildschirmfoto 2021-04-12 um 11 14 28](https://user-images.githubusercontent.com/18403881/114371389-ba617380-9b80-11eb-9445-bd3b48254e69.png)

**Comment by turbopixel** [comment] 2021-04-12 10:03
Same problem here (after upgrade to 1.14.0)


**My problems:**
* Cannot merge pull request, because loading dropzone failed (See below)
* Preview ist broken

---
![grafik](https://user-images.githubusercontent.com/15839724/114377276-c18b8000-9b86-11eb-9097-77d3d2b74499.png)
---

Browser console:
```
Uncaught ChunkLoadError: Loading chunk dropzone failed.
(missing: http://192.168.1.5:3000/js/dropzone.js)
    j jsonp chunk loading:30
    e ensure chunk:6
    e ensure chunk:5
    e tribute.js:37
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    Babel 2
    node_modules index.js:1
    node_modules index.js:1
    ac tribute.js:51
    rc tribute.js:36
    e index.js:3863
    u runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    Babel 2
    node_modules index.js:1
    node_modules index.js:1
    jQuery 2
```

**Comment by saitho** [comment] 2021-04-12 10:40
Can confirm that as well. This causes the "Reply" and "Resolve conversation" buttons on the PR conversation overview to not work.

I found out that opening the JS file directly in the browser and then reloading the page that had the errors works for that reload. :shrug:

**Comment by 6543** [comment] 2021-04-12 11:19
clean browser cache?

**Comment by TautFlorian** [comment] 2021-04-12 12:53
@6543 This helps for me with the broken comment section thanks.
But still its unusably slow.

For viewing `Changed files` which are about 80 files with 4000 adds and 2000 deletions it took 181785ms.
I would say before 1.14.0 it would probably not take longer than 30000ms.

**Comment by techknowlogick** [comment] 2021-04-12 13:33
Closing as dupe of https://github.com/go-gitea/gitea/issues/15401

**Closed as completed by techknowlogick** 2021-04-12 13:33 UTC
Labels: issue/duplicate
