### ISSUE TITLE
500 Internal Server Error due to weird specific corruption error

### ISSUE THREAD

**Issue by theAkito** [go-gitea/gitea#7991] opened 2019-08-26 22:53 UTC
- Gitea version (or commit ref): any
- Git version: any
- Operating system: any
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
```
handleCreateError() [E] CreatePost: newRepoAction: notify watchers '1/71': insert new actioner: pq: could not read block 12288 in file "base/16385/16944": read only 0 of 8192 bytes
```

## Description

Happens on `git push`, creating repository and anything that tries to write anything onto the disk. Yes, it seems like a file-system error, but how do I fix this error in Gitea? How can I tell Gitea to ignore this file and go on with their life? `git push` throws this error, every time **but the push works**. Problem now is, that the error does not let me create a new repository. All existing repositories work fine. I just want to get rid of this error.

**Comment by Akito13** [comment] 2019-08-26 23:04
> 
> 
> This error is happening in your database. The functions that throw that error don't interact with the file system directly. Besides, "pq:" stands for PostgreSQL. 😉

Good to know. Can it be caused by a recent update to PostgreSQL?

**Comment by Akito13** [comment] 2019-08-26 23:50
Fixed by running:
```
$ sudo -u yourdbuser psql
=> \c yourdbname
=> reindex database "yourdbname";
```

**Closed as completed by Akito13** 2019-08-26 23:50 UTC
