### ISSUE TITLE
Cannot paste into comment fields using mouse

### ISSUE THREAD

**Issue by IzzySoft** [go-gitea/gitea#11216] opened 2020-04-25 22:40 UTC
- Gitea version (or commit ref): 1.11.4 (but applies to other versions as well, e.g. on Codeberg.org)
- Git version: n/a
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
When I try to paste into a comment (e.g. issue) using mouse middle button, nothing happens. This is true for my self-hosted instance as well as for Codeberg.org – however, funnily it seems to work on try.gitea.io (which runs a development version). As I often use both clipboards separately, not being able to mouse-paste is really hindering to me.

I'm not sure if the functionality being available at try.gitea.io means it will be available with a future release – or if that's some "internal modification" not being released. I couldn't find a corresponding configuration option either. But neither do I see a reason to disable that by default – that's quite unusual, and not the case with other products like GitLab or Github.

## Screenshots
Cannot screenshot what's not there :wink:

**Comment by guillep2k** [comment] 2020-04-28 03:39
try.gitea.io is running our development version for 1.12. It's a "future release" indeed. We hope to bring up a release candidate very soon. Keep checking [blog.gitea.io](http://blog.gitea.io/)! 😁 

BTW, you can get our latest nightly release from [https://dl.gitea.io/gitea/](https://dl.gitea.io/gitea/). Make sure you don't get confused by the alphabetical order of the directory.

Closing as fixed (in 1.12) 😉

**Comment by IzzySoft** [comment] 2020-04-28 05:44
Good to know, thanks! And yes, I regularly check with `releases/` here :wink:

**Comment by IzzySoft** [comment] 2020-07-03 09:33
With 1.12 rolled out on Codeberg.org, I still cannot copy/paste using the mouse. Must that be explicitly enabled – or was it just not included with the release?

**Comment by IzzySoft** [comment] 2020-07-20 22:47
It's still unfixed. I've tracked it down to JavaScript: With JS disabled, I can paste fine. As soon as JS is enabled, it no longer works. The culprit is most likely SimpleMde (see [this issue there](https://github.com/sparksuite/simplemde-markdown-editor/issues/583)). Nextcloud Notes seems to [have the same problem](https://github.com/nextcloud/notes/issues/244). There might be even more references. The issue at SimpleMde unfortunately is open already since 2017 and didn't get much attention.

@guillep2k mind to reopen? I guess it worked with try.gitea.io because I didn't enable JS for the site. I just tried again now with JS enabled, and indeed it does not work there either. Disabling JS is not a good option either as then not even preview would work…

**Comment by IzzySoft** [comment] 2020-09-19 10:14
Dear bot, thanks for asking but the issue still persists. Please ask one of the devs for advice :rofl:

**Comment by nidico** [comment] 2022-04-18 18:18
I'm having this issue as well in Firefox (99) on Debian Linux as well as on Firefox (99) on Linux Mint. On Chromium it works fine. It doesn't matter whether wayland is used or not.

To summarize:

- This is caused by EasyMDE (a fork of SimpleMDE which is used in Gitea since #13333) - the corresponding EasyMDE issue can be found there: Ionaru/easy-markdown-editor#321
- EasyMDE can't do anything about it, since it's inherited from codemirror/CodeMirror#931. However this is supposed to be fixed with a workaround since codemirror/CodeMirror#5751.
- The issue was tracked in [this Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1482875), but states it was fixed.

This needs some more investigation...

**Comment by lunny** [comment] 2023-04-03 14:47
Should be fixed by #23876

**Comment by silverwind** [comment] 2023-04-03 20:40
Definitely fixed with https://github.com/go-gitea/gitea/pull/23876, let's close.

**Closed as completed by silverwind** 2023-04-03 20:40 UTC
Labels: type/enhancement, issue/confirmed, outdated/theme/markdown

**Comment by IzzySoft** [comment] 2023-04-03 22:04
OK, OK – I take your word on that, thanks :smile:
