### ISSUE TITLE
Migration stuck for some repos

### ISSUE THREAD

**Issue by Codeberg-org** [go-gitea/gitea#8812] opened 2019-11-03 15:04 UTC
- Gitea version (or commit ref): 1.11.0+dev-155-gdce22efbe
- Git version: whatever runs on try.gitea.io
- Operating system: whatever runs on try.gitea.io
- Database (use `[x]`): whatever runs on try.gitea.io
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL) : https://try.gitea.io/pcsv/Pix-Art-Messenger
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Trying to migrate https://github.com/kriztan/Pix-Art-Messenger with issues, wiki, pull requests and releases to Gitea, the migration is stuck, and the repo inaccessible.

No `Settings` tab either, so it is impossible to cancel the migration or delete the broken repo.

## Screenshots
![Bildschirmfoto vom 2019-11-03 15-04-29](https://user-images.githubusercontent.com/48032531/68087180-73cbfd80-fe53-11e9-9729-1586bcd085cb.png)

**Comment by ashimokawa** [comment] 2019-11-04 06:03
@lunny 
This is clearly a kind/bug.

The migration fails silently and the animation is running forever.
Not even the first issue (which is a PR with deleted branches) is migrated properly.

**Comment by lunny** [comment] 2019-11-04 12:50
I think we can add a `cancel` button here.

**Comment by ashimokawa** [comment] 2019-11-04 21:08
@lunny 
Sure, but that does not fix the underlying problem. The migrations fails somehow, always, reproducible with the repo mentioned above https://github.com/kriztan/Pix-Art-Messenger

**Comment by 6543** [comment] 2019-11-04 22:36
it works on gitea.com ( 1.11.0+dev-110-gc4bc5abda)
and 1.9.5 (with a timeout message but it works)

but not on (1.11.0+dev-163-g86a44f6b4 ) try.gitea.io

**Comment by 6543** [comment] 2019-11-04 22:37
maby some space limitations based on user? or something like that?

**Comment by 6543** [comment] 2019-11-04 22:38
@lunny what happen wen a user run out of granted space when he has a migration job?

**Comment by lunny** [comment] 2019-11-05 06:15
@6543 The repository should be deleted if any error found on the migrating. And a notice will be displayed on admin panel notices.

**Comment by lunny** [comment] 2019-11-05 06:17
As an enhancements for the migration process, I will send another PRs to split the process as serval parts.

**Comment by ashimokawa** [comment] 2019-11-05 06:26
@6543 
No it does *not* work when migration with issues and pr, please read the original issue description:

> with issues, wiki, pull requests and releases to Gitea, the migration is stuck, and the repo inaccessible.

**Comment by lafriks** [comment] 2019-11-05 07:37
Imho problem is that if Gitea is restarted while migration is running it will be left unfinished

**Comment by ashimokawa** [comment] 2019-11-05 10:00
@lafriks 
@lunny 

No, it happens always on any instance, not only when restarting. 

We did not restart try.gitea.io (we can't) and it happens on our test instance also. You can reproduce it easily by migrating https://github.com/kriztan/Pix-Art-Messenger

**Comment by lunny** [comment] 2019-11-05 10:16
@ashimokawa I will try that repository.

**Comment by mrsdizzie** [comment] 2019-11-05 16:48
I started to debug this a bit and ran out of time but if it is helpful for you @lunny what is happening is that at some point inserting a batch of releases from this repo is throwing the error:

```
UNIQUE constraint failed: release.repo_id, release.tag_name
```
And then it goes into rollback but never comes out. It seems to get here:

https://github.com/go-gitea/gitea/blob/45f219239e420f707a2452b99b27a68f45d5d4ca/vendor/xorm.io/xorm/session_delete.go#L211

And then the it hits this code and seems to never really do anything after that:

 https://github.com/go-gitea/gitea/blob/45f219239e420f707a2452b99b27a68f45d5d4ca/vendor/xorm.io/xorm/session_raw.go#L177-L179

That runs some code in the specific driver for the database, but I'm able to reproduce on sqlite3 and assume try.gitea.io and codeberg are using something else so I wonder if it just isn't returning an error where it should at some point. Not familiar with xorm at all though :-/

I tried with lafriks patch too but seems unrelated in this case (though helpful in general)

**Comment by ashimokawa** [comment] 2019-11-05 16:57
@mrsdizzie 
Yep, codeberg.org runs mariadb and not sqlite.

I assume you tried the repo I mentioned with full migration?

The only thing a saw in logs is that a rollback failed (timout? stuck?), I really do not remember because I was also in a hurry.

**Comment by lunny** [comment] 2019-11-06 07:25
@mrsdizzie Thanks for your work!
So 
```
UNIQUE constraint failed: release.repo_id, release.tag_name
```
means there are duplicated releases on that repository??? I will take a look at that code.

**Comment by ashimokawa** [comment] 2019-11-06 15:29
I can confirm that migrating the repository without releases works.

**Comment by techknowlogick** [comment] 2019-12-02 22:05
It seems unusual that there would be a duplicate release, as I'm not sure that git allows same tag to be used twice. Regardless of that assumption, I am able to replicate same error as above, but able to have successful migration when release is unchecked (I tested on sqlite as that's what I am using on my dev instance, but will try with postgres later, as that's whats on my prod instance).

**Comment by mrsdizzie** [comment] 2019-12-02 22:19
It could be a bug in the migrating that perhaps tries to insert the same release twice as well. 

The 100% certain bug is that the rollback isn't finishing but I didn't know enough about xorm etc to really figure out why that is happening here.

**Comment by lunny** [comment] 2019-12-11 06:11
#9319 shoud fix another bug but not this one. But @ashimokawa , you can still try it.

**Comment by mrsdizzie** [comment] 2019-12-11 06:51
The specific example from this issue should be fixd, see:

 https://try.gitea.io/mrsdizzie/Pix-Art-Messenger

But the original issue exposed a lower level bug in rollback that is still present (though not triggered anymore through this issue) and should probably stay open until that is fixed.

Plus there are the other aspects like not being able to cancel a migration that is stuck for any reason which should be possible

**Comment by lunny** [comment] 2019-12-11 07:03
@mrsdizzie it could be deleted from admin panel currently. :)

**Comment by ashimokawa** [comment] 2019-12-12 09:25
@lunny 
I can confirm that the specific case I opened this issue for is fixed. So normally I would close this one.

**Comment by ashimokawa** [comment] 2019-12-12 09:38
@lunny @mrsdizzie 

Stuck repos can be deleted by the user by just manually navigating to his settings, even in that stuck state.

https://try.gitea.io/mrsdizzie/Pix-Art-Messenger/settings 

Don't know if that is good or not.

**Comment by lunny** [comment] 2019-12-12 11:15
@ashimokawa :)

**Comment by mrsdizzie** [comment] 2019-12-12 16:13
There is no link to that settings page if it is stuck migrating (though visiting the URL directly works). So it is good but could be better.

I think the general bug still exists that it shouldn't be possible for it to get stuck at all (it should work or fail), but now this example will not trigger it so perhaps harder to reproduce. @lunny maybe if you have time to look at the xorm code from above, if not then I'm not sure : ) Glad that this example helped fix the bug causing it anyway so thanks!

**Comment by saurasambit** [comment] 2020-02-09 10:59
I faced the issue while migrating https://github.com/jitsi/jitsi-meet. 
See https://try.gitea.io/dashadsh/jitsi-meet for the reproduced problem.

**Comment by dkebler** [comment] 2020-03-16 23:12
Just had this happen to me after migrating many repos to my backup site.  How does not get rid of this aborted migration?  Not via the webui as there is no access to "settings" since the migration was not completed.  I restarted my instance and web server but it must be in the db itself.  How can on repair the `git.db`?   

Of Note.  I see that I had 7000+ pages of system notices all one date all about not being able to access the main git from which the migrations come.  This backup install has been acting funny too.  Slow page loads, popup notices above loosing data if moving to another page which I wasn't.  I'm guessing this is a corrupted data base maybe from loading up on all those system notifications.  7000 pages is excessive no :-).   Luckily I have daily backups and a backup from when I upgraded in Jan.  Will try those if I can solve this otherwise.

**Comment by dkebler** [comment] 2020-03-16 23:56
I was able to delete all the notifications via the UI and under site administration /admin/repos I was able to delete the offending migration.
I then attempted to make anew the migration and it was the same issue :-(  

I have been using 1.1  now going to try upgrading to 1.96.

**Comment by dkebler** [comment] 2020-03-17 01:02
I upgraded both installs to 1.9.6.  I deleted and recreated the offending repo on the main gitea install and pushed it again from local.  Then tried again to make a migration on my backup gitea from main gitea install and YEA that worked.

So only 2 issues for me now.

1.  that my git.db on my backup install is still 47mb.  Apparently sqlite has no way to compact after deleting all those pages of notifications? https://www.recoveryandmanagement.com/repair-sqlite-database-manually/

2.  Why did gitea create 7000 pages worth of notifications/logs.  Was that 'bug' fixed going from 1.1 to 1.9.6?

**Comment by lunny** [comment] 2020-03-17 01:07
That admin notices could be deleted after your problem resolved.

**Comment by guillep2k** [comment] 2020-03-17 01:12
@dkebler Sincerely, 1.1 was so long ago... so many things have changed since then: refactors, rewriting, updating libraries... I'd even suggest you upgrade to 1.11.3 while you're at it; a lot of good features and bugfixes were added since 1.9.6 already.

**Comment by qdzhaov** [comment] 2020-04-14 15:49
I found the bug like this.
- Gitea version (or commit ref):1.11.4
- Git version:2.17.1
- Operating system:linux
- Database : SQLite
When I  Migration a Repositories from gogs(,need a user name a password ,but I don't give,so
the task is in dead loop.(This bug is also in gogs.)

**Comment by guillep2k** [comment] 2020-04-15 17:48
@qdzhaov What version of Gogs are you migrating from? (I take it's not an upgrade but a site-to-site migration)

**Comment by theAkito** [comment] 2020-07-05 13:29
I've upgraded from 6af13dbac to 15d3aa7b95e37cc2e9a06208089169cbe04383b5, because I had this issue on the former version. Now the issue is gone and mirroring works.

**Comment by 1byte2bytes** [comment] 2020-09-14 22:27
I encounter the issue of migration getting stuck while trying to mirror https://github.com/apache/spamassassin to my Gitea instance, using Gitea 1.14.8 on Debian 10. Restarting the Gitea server did not fix the importing for me.

**Comment by jolheiser** [comment] 2020-09-14 22:31
> using Gitea 1.14.8 on Debian 10

Currently Gitea is version `1.12.4` heading towards `1.13`.

**Comment by 6543** [comment] 2020-09-14 23:01
@1byte2bytes found a bug related to DefaultBranch != "master" - it could have hit you ...

**Comment by 6543** [comment] 2020-09-14 23:08
(#12843)

**Comment by 6543** [comment] 2020-09-15 00:35
ok since **Pix-Art-Messenger** can be migrated (tested) I think it's time to close **this** issue

@1byte2bytes if gitea v1.12.5 has ben released and it still does not work, feel free to create an issue :)
and for cancel suggestions: (#12845)

**Closed as completed** 2020-09-15 00:36 UTC
Labels: type/bug, issue/confirmed
