### ISSUE TITLE
Can not choose branch after create PR

### ISSUE THREAD

**Issue by melmus** [go-gitea/gitea#12879] opened 2020-09-17 09:29 UTC
- Gitea version (or commit ref):
1.13.0+dev-600-g4f8dad37f

- Git version host system:
2.17.1

- Git version in docker gitea_server_1:
2.26.2

- Operating system:
Ubuntu 18.04.3 LTS

- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

After created Pull request, I can not choose another branch to merge changes.

## Screenshots
![Снимок экрана 2020-09-17 в 12 07 10](https://user-images.githubusercontent.com/15018126/93452320-f3827f80-f8e0-11ea-8c0c-3f32acf1f38a.png)
![Снимок экрана 2020-09-17 в 12 07 32](https://user-images.githubusercontent.com/15018126/93452325-f4b3ac80-f8e0-11ea-874e-3fc5d04564c9.png)

**Comment by bagasme** [comment] 2020-09-17 11:18
@melmus I can't reproduce the issue on current master (a9decf0dacb56e57024ef7c5a0ade7fdcc56407e)

**Comment by bagasme** [comment] 2020-09-17 11:53
@melmus bisecting between current master and your reported commit (g4f8dad37f), the commit 47289344e2ede03b7a74208aad3b92c8bca979c3 may solve this issue. can you please try?

**Comment by melmus** [comment] 2020-09-17 14:20
@bagasme, ok, I will try to learn this issue

**Comment by melmus** [comment] 2020-09-17 21:25
@bagasme, you right, problem solved

**Comment by 6543** [comment] 2020-09-18 11:48
☝️ close this issue now

**Comment by 6543** [comment] 2020-09-18 11:49
@melmus still thanks for testing & reporting errors :)

**Closed as completed by 6543** 2020-09-18 11:48 UTC
