### ISSUE TITLE
Revert to textarea dont work on wiki pages

### ISSUE THREAD

**Issue by davidglezz** [go-gitea/gitea#12971] opened 2020-09-29 08:54 UTC
- Gitea version (or commit ref):  1.12.4
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
When trying to change the editor to the textarea on a wiki page, the editor disappears and the ui stops working

## Screenshots
![gitea_wiki2](https://user-images.githubusercontent.com/194784/94535614-10547680-0242-11eb-923e-a0ba3de1c062.gif)

**Comment by InExtremaRes** [comment] 2020-10-15 22:42
I can confirm this and is in fact reproducible at https://try.gitea.io.

When the button "Revert to simple textarea" is pressed the `textarea` loses the inline style `display: none` but there is still a `#edit_area: {display: none}` that keeps it hide.

**Comment by zeripath** [comment] 2020-10-18 19:34
Looks like this trick won't work on the wiki.

**Comment by noerw** [comment] 2021-02-19 18:27
duplicate of #14453

**Closed as completed by noerw** 2021-02-19 18:27 UTC
Labels: type/bug, topic/ui
