### ISSUE TITLE
Commenting and closing an issue at the same time button

### ISSUE THREAD

**Issue by aha999** [go-gitea/gitea#10468] opened 2020-02-26 01:52 UTC
www.codeberg.org uses Gitea so i thought i can comment here on the issue.
When you want to make a comment and close the issue with that, there's only "close" next to the comment button. I think it would be better if the option was renamed to "comment & close" so we know it's going to post a comment and then close the issue (if there is text in the comment field already). Or maybe have three options.
With only Close option some can get confused if it's going to comment and then close, or just close.

![DCDZw94595](https://user-images.githubusercontent.com/50620416/75304130-def67100-5842-11ea-9eea-a19f7e0aa076.png)

Github method:
![A7Q67sS68H](https://user-images.githubusercontent.com/50620416/75351082-d1bf9d80-58a7-11ea-81ef-6dd3d928383f.gif)

**Comment by JVimes** [comment] 2023-02-24 18:34
@guillep2k #14407 says this feature exists. This might be "bug fix" instead of proposal?

**Comment by wxiaoguang** [comment] 2023-02-25 03:33
Not a bug fix, but the missing code for new editor.

Will be fixed by #23135

**Comment by guillep2k** [comment] 2023-02-25 15:13
> @guillep2k #14407 says this feature exists. This might be "bug fix" instead of proposal?

Ha! Is time going backwards?

**Comment by wxiaoguang** [comment] 2023-02-25 15:24
The "existing" feature for rich editor is a hacky patch, it doesn't work well with real rich editors, so it gets broken later.

EasyMDE/CodeMirror need to handle the `onChange` event.

**Closed as completed** 2023-02-27 23:13 UTC
Labels: type/proposal, topic/ui
