### ISSUE TITLE
'Assigned to you' issues should scope also in organisations

### ISSUE THREAD

**Issue by rikvdh** [go-gitea/gitea#706] opened 2017-01-20 09:06 UTC
- Gitea version (or commit ref): 1.0.0+116-g69b86378 (try.gitea.io @20-1-2017)
- Git version: n/a
- Operating system: n/a
- Database (use `[x]`): n/a
- Can you reproduce the bug at https://try.gitea.io:
  - [X] Yes (provide example URL) -- Login required
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

If I look at the "Assigned to you" list of issues this only scopes in issues in my repositories. But I expect it to scope also the users organisation.

When I have an issue in my organisation assigned to me, the issue is not visible on the Assigned to me overview. When having multiple organisations this becomes fast very cluttered.

**Comment by rikvdh** [comment] 2017-01-29 18:52
See https://github.com/gogits/gogs/pull/3560

**Comment by jeppech** [comment] 2017-01-31 13:21
Duplicate of #503

**Closed as completed** 2017-01-31 14:52 UTC
Labels: issue/duplicate
