### ISSUE TITLE
Markdown preview rendered for outdated markdown on android

### ISSUE THREAD

**Issue by joschahenningsen** [go-gitea/gitea#19784] opened 2022-05-22 20:26 UTC
### Description

When editing markdown (issue and pull request comments), clicking the preview button on mobile devices when the text input still has focus doesn't render the latest markdown but markdown that misses the latest input instead.

<small>tested on Chrome for Android 11</small>

### Gitea Version

1.17.0+dev-610-gfa5dec966

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

https://user-images.githubusercontent.com/44805696/169714463-6d957466-d90c-469a-a1fc-26298dda76be.mp4

### How are you running Gitea?

Tested this locally and on https://try.gitea.io

### Database

SQLite

**Comment by yp05327** [comment] 2023-02-24 08:55
You inputted the characters without confirming them, so they were just Preview Characters in the inputbox.
Then you switched to `Preview`, of course, the characters in the inpubox weren't changed at that moment.
Then you switched to `Write`, maybe a feature of your IME? IME automatically 'confirmed' the changes.
Then you switched to `Preview`, of course, the characters in the inputbox were changed.

Github uses `textarea` which has no problem, but gitea uses CodeMirror here. Maybe you need to fix this in CodeMirror.

**Comment by wxiaoguang** [comment] 2023-02-24 09:13
Gitea 1.18 and newer are using the CodeMirror with contenteditable mode, which brings different editing experience.

* #19776

Please try if the problem gets better in new releases.

**Comment by yp05327** [comment] 2023-02-24 09:42
I tested with Japanese Google IME in 1.18.5 (I only have this which may cause the same problem I think), and it was same.
But Github has no problem.

**Comment by wxiaoguang** [comment] 2023-02-24 09:45
Yup, the problem is `contenteditable`, sometimes it doesn't work well, and that's the reason why there were discussions about dropping EasyMDE&CodeMirror ....

**Comment by lunny** [comment] 2023-04-03 14:44
Should be fixed by #23876 ?

**Comment by yp05327** [comment] 2023-04-06 03:53
Tested in 1.20.0-361, Preview displayed the characters, but the inputbox is empty.

**Comment by wxiaoguang** [comment] 2023-04-06 04:00
> Tested in 1.20.0-361, Preview displayed the characters, but the inputbox was empty.

Can you elaborate, or provide some screenshots?

**Comment by joschahenningsen** [comment] 2023-04-06 04:55
> Should be fixed by #23876 ?

Yup, seems to be working now 👍

**Closed as completed** 2023-04-06 04:55 UTC
Labels: type/bug

**Comment by yp05327** [comment] 2023-04-06 09:57
> > Tested in 1.20.0-361, Preview displayed the characters, but the inputbox was empty.
> 
> Can you elaborate, or provide some screenshots?

I can’t upload videos to github on my phone.

Preview is worked.
![CF10BBA0-7C16-412E-8D1C-E7541D6D06A9](https://user-images.githubusercontent.com/18380374/230342013-c48fad0e-f356-4cb1-910a-25b647bc68a8.png)
But the input box is empty.
![5C520939-4273-48B0-9540-DFF416BBF8D7](https://user-images.githubusercontent.com/18380374/230342045-9a240ce5-208e-4c8c-9ed8-679ce705b482.png)

Github have the same performance, so maybe it is all right.

**Comment by wxiaoguang** [comment] 2023-04-06 13:45
> I can’t upload videos to github on my phone.
> Preview is worked.
> But the input box is empty.
> Github have the same behavior, so maybe it is all right.


What's the steps? Do you mean that:

1. Open the New Issue page
2. Input something into the textarea
3. Click the Preview
4. Preview shows
5. Click Write
6. The textarea loses its content and becomes empty?

**Comment by yp05327** [comment] 2023-04-06 14:04
![image](https://user-images.githubusercontent.com/18380374/230398979-82ba70fc-ac7f-443c-89cb-e74465855468.png)
I know the reason now LOL

Here is the video:

https://user-images.githubusercontent.com/18380374/230401807-606b59b0-7081-4dab-99dc-88ef79274042.mp4

**Comment by wxiaoguang** [comment] 2023-04-06 14:11
I guess because you didn't confirm the input in your input method.

The "temp" text is highlighted to show that they are not really in the textarea.

I guess you need to click the "確定"  on the virtual keyboard
