### ISSUE TITLE
Labels/Tags for repositories

### ISSUE THREAD

**Issue by michael-brade** [go-gitea/gitea#5171] opened 2018-10-25 00:37 UTC
Feature Request:

I would like to be able to assign labels or tags to repositories, just like you can assign labels to issues. Right now the only way to group repositories is by organization and per user. And the poor man's way is to prefix the repository name with a group name. It would be much nicer to be able to tag/label the repositories and then be able to filter them by label.

**Comment by techknowlogick** [comment] 2018-10-25 00:39
Closing as duplicate of #3711

See: https://blog.gitea.io/2018/08/gitea-1.5.0-is-released/ for a GIF of how to use topics.

**Closed as completed by techknowlogick** 2018-10-25 00:39 UTC
Labels: issue/duplicate

**Comment by michael-brade** [comment] 2018-10-25 00:42
Oh gee, I just found exactly that! Sorry for this issue and thanks for being faster than me :smile:

**Comment by michael-brade** [comment] 2018-10-25 00:45
Hmm, a nitpick: I am using 1.6.0-rc.1, but in that version the topics are always converted to lower case, so API becomes "api". Is that intentional or a bug? The GIF in your link doesn't do that.

**Comment by techknowlogick** [comment] 2018-10-25 00:49
I believe it is intentional. There was a PR (that was merged after the one I linked above) that does some validation, to reduce duplication of tags, and cleaning up of things. @axifive would be able to give you more specific information.

**Comment by lunny** [comment] 2018-10-25 02:07
That maybe a bug. We should keep the original name of topic.

**Comment by michael-brade** [comment] 2018-10-29 14:53
So... should I open a new issue? Or rename and reopen this one?
