### ISSUE TITLE
Internal Server Error accessing my profile on try.gitea.io

### ISSUE THREAD

**Issue by strk** [go-gitea/gitea#20002] opened 2022-06-17 18:02 UTC
### Description

If I go to https://try.gitea.io/strk, logging in via github OAuth, I get a 500

### Gitea Version

Gitea Version: 1.17.0+dev-736-g719eb4a87

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Only on try.gitea.io

**Comment by zeripath** [comment] 2022-06-17 21:06
Looking at the logs it appears that this is related to GetActiveStopwatch #20008 

```
router.log:2022/06/17 17:59:08 [62acc0ec] router: completed GET /strk for 172.18.0.3:38034, 500 Internal Server Error in 3.2ms @ repo/issue_stopwatch.go:81(repo.GetActiveStopwatch)
```

**Comment by strk** [comment] 2022-06-17 22:38
Still happens as of 1.17.0+dev-738-gea9997a9d

**Comment by strk** [comment] 2022-06-17 22:39
![Screenshot_20220618-003103](https://user-images.githubusercontent.com/289678/174409392-1d2aace9-51a7-4515-bc9c-bb511461f342.png)

**Comment by zeripath** [comment] 2022-06-17 22:45
The fixing commit is:

v1.17.0-dev-741-gae446b13f

**Comment by lafriks** [comment] 2022-06-18 07:29
I also have 500 error when authorizing but could be different, probably related to 2FA

**Comment by zeripath** [comment] 2022-06-18 07:49
I'd need to know when you tried to do this so we could check the logs.

**Comment by lunny** [comment] 2023-03-08 11:56
Closed as I cannot reproduce it in the try site now. Fell free to reopen it if it occurs again.

**Closed as completed by lunny** 2023-03-08 11:56 UTC
Labels: type/bug
