### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by SheepDomination** [go-gitea/gitea#6974] opened 2019-05-17 12:26 UTC
Hi, I'm following the instructions on [this](https://docs.gitea.io/en-us/install-from-binary/) page to install gitea and I've got gitea downloaded but when running the command `chmod +x gitea` from what I understand the permissions of this file should change; although nothing is happening ?

**Comment by lunny** [comment] 2019-05-17 15:49
Could you give more detail?

**Comment by SheepDomination** [comment] 2019-05-17 19:10
The installation instructions state to change the permissions for the directory, but I'm unable to even go into the directory named as it is labeled `gitea*` ?

**Comment by multinerd** [comment] 2019-05-17 20:37
@SheepDomination
`wget -O gitea https://dl.gitea.io/gitea/1.7.0/gitea-1.7.0-linux-amd64` downloads the file into the current directory

`chmod +x gitea` will make **the file you downloaded** into an executable

This obviously goes without saying but im gonna say it anyways, make sure you're downloading the right executable.

**Comment by SheepDomination** [comment] 2019-05-17 20:40
> 
> 
> @SheepDomination
> `wget -O gitea https://dl.gitea.io/gitea/1.7.0/gitea-1.7.0-linux-amd64` downloads the file into the current directory
> 
> `chmod +x gitea` will make **the file you downloaded** into an executable
> 
> This obviously goes without saying but im gonna say it anyways, make sure you're downloading the right executable.

I understand but I can't do anything with the file which I downloaded as I mentioned ?

**Comment by techknowlogick** [comment] 2019-05-17 21:17
What happens when you try to run it, any output? By default gitea binary is downloaded attached to the user who downloaded it, and as such if you are unable to assign any permissions to it, then likely some other issue is incorrect with your machine. Are you able to run `sudo chmod +x gitea`?

**Comment by SheepDomination** [comment] 2019-05-17 21:22
> 
> 
> What happens when you try to run it, any output? By default gitea binary is downloaded attached to the user who downloaded it, and as such if you are unable to assign any permissions to it, then likely some other issue is incorrect with your machine. Are you able to run `sudo chmod +x gitea`?

After using that command this is the result; `sudo: effective uid is not 0, is sudo installed setuid root?`

**Comment by multinerd** [comment] 2019-05-17 21:24
Try the following: https://stackoverflow.com/a/41848643

The problem is that you probably changed permissions to the directory `/usr/bin`.

To resolve that :

1) First be sure that **root** is owner of this directory `/usr/bin` : 

    chown root:root /usr/bin

2) and change permission for this directory :  

    chmod u+s /usr/bin/sudo

**Comment by SheepDomination** [comment] 2019-05-17 23:51
@multinerd I believe the problem is that the file was downloaded in the wrong path, instead of `/public_html`. How do I move a file labeled `gitea*` to another directory ?

**Comment by techknowlogick** [comment] 2019-05-21 01:57
`wget` downloads the file to whichever directory you are currently in, so you should download it to the directory you want. However the error you had with the command you had above suggests a larger problem with your install. As such I am going to close this.

For future issues you may open, please ensure you use the template provided as it provides us with valuable information that could help us help you faster. Here is what the template looks like:
```
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:
```

**Closed as completed by techknowlogick** 2019-05-21 01:57 UTC
Labels: type/question

**Comment by SheepDomination** [comment] 2019-07-20 15:10
What is the bare minimum required to install gitea ?  I'm using CentOS6 and I can't get it installed.

**Comment by techknowlogick** [comment] 2019-07-20 15:39
Git 1.8 installed, and if you use the pre-compiled binaries then you'll need Linux Kernel 3.16

Please don't comment in tickets that have been closed as your comments could be lost. You can use [discord](https://discord.gg/gitea), or the [forum](https://discourse.gitea.io/) for questions.
