### ISSUE TITLE
Broken links on dash page after renaming an organisation.

### ISSUE THREAD

**Issue by dalito** [go-gitea/gitea#1630] opened 2017-04-27 17:51 UTC
- Gitea version (or commit ref): release 1.10
- Git version: 1.8.4
- Operating system: Windows Server 2003
- Database (use `[x]`):
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)

After renaming an organization the dash page contains links that still point to the old organization. All urls to the renamed repository should be either updated or removed upon renaming an organization. 

I haven't tried yet if renaming a repository also produces broken links.

**Comment by ethantkoenig** [comment] 2017-07-23 16:48
@dalito I'm not able to reproduce. Can you confirm the issue is still present in latest version of gitea, and if so give more detailed intstructions on how to reproduce? Thanks.

**Comment by dalito** [comment] 2017-07-26 10:03
I can still reproduce this in Gitea Version 1.1.2:

Steps: 

1. Create Organisation "Test-Orga"
2. Create a repository "repo1" in the Organisation
3. Commit to the repository

Now the dashboad shows an entry like  "dalito pushed to master at Test-Orga/repo1"

4. Rename the Orgnaisation: "Test-Orga" -> "Test-Orga-renamed"
5. Go back to dashboad

The dashboad still shows the same entry: "dalito pushed to master at Test-Orga/repo1" (clicking the link gives a 404 error). Obviously, the dashboard is not correctly regenerated after the renaming.

**Comment by ethantkoenig** [comment] 2017-07-28 03:28
@dalito I followed your steps on master (fd45a032a7752e4da7e0388eb9661a7c32ff5c85), and the name on the dashboard updated correctly. If you are able to reproduce this bug on master, please let me know, but otherwise it looks like this issue has already been fixed.

**Comment by dalito** [comment] 2017-08-22 15:42
Unfortunately I cannot easily test with master but this issue is still present in the recent release 1.1.3. - When 1.2.0 comes out I will try again to confirm the fix.

**Comment by lafriks** [comment] 2017-08-22 17:00
This is fixed in master so I'm closing it

**Closed as completed by lafriks** 2017-08-22 17:00 UTC
Labels: type/bug
