### ISSUE TITLE
Make default robots.txt

### ISSUE THREAD

**Issue by theel0ja** [go-gitea/gitea#6028] opened 2019-02-10 12:18 UTC
My gitea instance is seeing ton of requests from Googlebot to `/user/login` for example.

**Comment by lunny** [comment] 2019-02-11 12:00
see https://docs.gitea.io/en-us/customizing-gitea/

**Comment by lafriks** [comment] 2019-02-11 12:08
@lunny request was to provide one by default with recommended rules

**Comment by karthanistyr** [comment] 2019-05-29 12:17
I naively deployed a vanilla gitea image on a subdomain and lacked a robots.txt.
Bots hence came and hit a high number of `/archive` URLs, creating loads of artifacts and consuming a large space on the disk.

I think a default robots.txt forbidding access to this sort or URLs (and other sane defaults) would be really useful for ease of deployment.

**Comment by Mikaela** [comment] 2019-10-14 06:29
Is this a duplicate of https://github.com/go-gitea/gitea/issues/705 or the other way?

**Comment by lunny** [comment] 2019-10-14 07:00
@Mikaela you are right. Let's move to #705 to discuss further.

**Closed as completed by lunny** 2019-10-14 07:00 UTC
Labels: issue/duplicate
