### ISSUE TITLE
[MSSQL] Unable to upgrade from 1.7.6 to 1.8.0

### ISSUE THREAD

**Issue by Cellebyte** [go-gitea/gitea#6753] opened 2019-04-25 09:29 UTC
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [X] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:
```txt
2019/04/24 07:50:00 [...itea/routers/init.go:82 GlobalInit()] [E] ORM engine initialization failed: migrate: do migrate: Drop column failed: mssql: ALTER TABLE DROP COLUMN is_bare failed because one or more objects access this column
```
## Description
Cannot Migrate my MSSQL from version 1.7.6 to version 1.8.0.
Get the following error in the log.
What should I do?

**Comment by Cellebyte** [comment] 2019-04-25 09:30
#6718

**Comment by lafriks** [comment] 2019-04-25 09:31
That is different. This is duplicate of #6707

**Comment by Cellebyte** [comment] 2019-04-25 09:32
Thanks ;)

**Closed as completed by lafriks** 2019-04-25 09:31 UTC
Labels: issue/duplicate
