### ISSUE TITLE
Allow Ctrl+V to paste new images into Wiki

### ISSUE THREAD

**Issue by mappu** [go-gitea/gitea#17231] opened 2021-10-05 21:05 UTC
### Feature Description

When editing an issue comment, you can paste in new image attachments. It's a great low-friction way to make an issue more understandable, especially for screenshots.

It would be great to have this same capability to add images to Wiki documents.

Right now, you can only either (A) clone the git repo and add them manually, which is difficult for non-developer staff; or (B) create a dummy-issue for image uploads and copy the links into the wiki, which is a strange workaround

**Comment by KiaraGrouwstra** [comment] 2022-12-19 15:03
the wikis are just git repos, right? couldn't they store image files?

**Comment by ivptr** [comment] 2022-12-22 14:45
Yes, wikis are Git repos: https://github.com/go-gitea/gitea/issues/1426#issuecomment-290888504

The whole idea is to allow non-tech staff to edit documentation in Wiki, add screenshots, other attachments etc.

Currently this is not possible because images need to be committed to main repository first and then its path referenced in Wiki.

**Comment by wxiaoguang** [comment] 2023-04-25 16:27
It's duplicate of https://github.com/go-gitea/gitea/issues/574, as long as #574 could be done, there is no problem for Ctrl+V

**Closed as completed by wxiaoguang** 2023-04-25 16:27 UTC
Labels: topic/ui-interaction, topic/wiki
