### ISSUE TITLE
Merge Pull Request 500 error

### ISSUE THREAD

**Issue by xlouc** [go-gitea/gitea#7636] opened 2019-07-26 19:24 UTC
- Gitea version (or commit ref): 1.9.0-rc2
- Git version: 1.8.3.1
- Operating system: CentOS 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

```
2019/07/27 03:17:19 ...ters/private/hook.go:74:HookPreReceive() [E] Unable to detect force push between: 50c1b4fd7cba3172b4b0a72386708cf5a66a55eb and 8f9a3d87fbee0a03a94230aebd4b3c5fffd09b24 in 824741413200:yakcode/yak-ui Error: exit status 128 - fatal: Not a git repository (or any of the parent directories): .git

2019/07/27 03:17:19 routers/repo/pull.go:629:MergePullRequest() [E] Merge: git push: From /home/git/gitea/repositories/yakcode/yak-ui
         * [new branch]      develop    -> head_repo/develop
         * [new branch]      gh-pages   -> head_repo/gh-pages
         * [new branch]      master     -> head_repo/master
        Automatic merge went well; stopped before committing as requested
        remote: Gitea: Internal Server Error
        remote: Fail to detect force push: exit status 128 - fatal: Not a git repository (or any of the parent directories): .git
        remote:
        To /home/git/gitea/repositories/yakcode/yak-ui.git
         ! [remote rejected] master -> master (pre-receive hook declined)
        error: failed to push some refs to '/home/git/gitea/repositories/yakcode/yak-ui.git'
```

## Description

...

## Screenshots

![微信截图_20190727032358](https://user-images.githubusercontent.com/12823830/61976297-04f23380-b01e-11e9-9f5c-1b20c3b17b14.png)

**Comment by mamying** [comment] 2019-07-26 19:28
Errors occur only when branch protection is set
![微信截图_20190727032358](https://user-images.githubusercontent.com/12823830/61976502-84800280-b01e-11e9-8963-4b8e8a5faf86.png)

**Comment by zeripath** [comment] 2019-07-26 20:41
Hi! thanks for your report. I'm suspicious that this is a duplicate of #7611, which has been fixed in master with #7615 and 1.9 with #7618.

**Comment by lunny** [comment] 2019-08-06 09:00
The git version 1.8.3.1 is too low. Maybe it's related.

**Comment by lafriks** [comment] 2019-08-06 09:10
I think this is duplicate of #7754

**Comment by lunny** [comment] 2019-08-06 09:20
It should be.

**Closed as completed** 2019-08-06 12:47 UTC
Labels: issue/duplicate

**Comment by axeloz** [comment] 2019-08-08 12:20
Hello, I'm using Gitea 1.9.0 and I have the exact same issue. 
Trying to merge a pull request from "develop" to "master". Master branch is protected but I'm into the whitelist for merges. 

Error message:
```
2019/08/08 14:15:15 routers/repo/pull.go:629:MergePullRequest() [E] Merge: git push: From /home/git/repositories/xxxxxxxxx/webservices
         * branch            develop    -> FETCH_HEAD
         * [new branch]      develop    -> head_repo/develop
        Automatic merge went well; stopped before committing as requested
        remote: Gitea: Internal Server Error
        remote: Fail to detect force push: exit status 128 - fatal: Not a git repository (or any of the parent directories): .git
        remote:
        To /home/git/repositories/xxxxxxxxx/webservices.git
         ! [remote rejected] master -> master (pre-receive hook declined)
        error: failed to push some refs to '/home/git/repositories/xxxxxxxxx/webservices.git'
```

Thanks

**Comment by lunny** [comment] 2019-08-08 14:51
See #7754 and #7775

**Comment by axeloz** [comment] 2019-08-09 15:02
thanks @lunny, so we must wait for the #7775 fix to be merged if I understand right

**Comment by joseluisq** [comment] 2019-08-30 23:33
I'm facing the same issue for latest Gitea `v1.10.0+dev-232-gf1c414882` with Postgres.
Waiting for #7775.

**Comment by lucastucious** [comment] 2020-08-05 00:43
Same issue with gitea v1.11.1

**Comment by zeripath** [comment] 2020-08-05 05:49
@lucastucious it will not be the same issue.

Please update to 1.12 and open a new issue with logs and more detail
