### ISSUE TITLE
Intermittent CI Failures due TestIncomingEmail

### ISSUE THREAD

**Issue by zeripath** [go-gitea/gitea#22469] opened 2023-01-16 15:41 UTC
### Description

There are intermittent CI failures due to the new TestIncomingEmail/IMAP test: 

```
   --- FAIL: TestIncomingEmail/IMAP (10.00s)
        incoming_email_test.go:194: 
            	Error Trace:	/drone/src/incoming_email_test.go:194
            	Error:      	Received unexpected error:
            	            	gomail: could not send email 1: dial tcp 172.18.0.2:25: connect: connection refused
            	Test:       	TestIncomingEmail/IMAP
        incoming_email_test.go:196: 
            	Error Trace:	/drone/src/incoming_email_test.go:196
            	Error:      	Condition never satisfied
            	Test:       	TestIncomingEmail/IMAP
```

### Gitea Version

1.19-dev

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

See description

### Git Version

n/a

### Operating System

n/a

### How are you running Gitea?

n/a

### Database

None

**Comment by yardenshoham** [comment] 2023-01-16 20:31
@KN4CK3R

**Comment by KN4CK3R** [comment] 2023-01-16 22:24
There is a short discussion on Discord and I don't know why that container does not initialize sometimes. I will try to build an new image with the Docker file.

**Comment by lunny** [comment] 2023-01-17 03:43
> There is a short discussion on Discord and I don't know why that container does not initialize sometimes. I will try to build an new image with the Docker file.

Maybe it needs to wait some seconds.

**Comment by KN4CK3R** [comment] 2023-01-17 07:48
The container has several minutes to initialize and if I run it locally it takes seconds.

If the Drone console logs display this it will not work:
```
latest: Pulling from tabascoterrier/docker-imap-devel
Digest: sha256:bf744c42aeab47e8d1dda077780cd901ad92df59c898b6856137869298534541
Status: Downloaded newer image for tabascoterrier/docker-imap-devel:latest
```
if they display this it will work:
```
latest: Pulling from tabascoterrier/docker-imap-devel
Digest: sha256:bf744c42aeab47e8d1dda077780cd901ad92df59c898b6856137869298534541
Status: Image is up to date for tabascoterrier/docker-imap-devel:latest
   ...done.
```
I don't know where this `...done` is printed. From the Docker file (https://github.com/tabascoterrier/docker-imap-devel) the mail log is used as container output.

**Comment by lunny** [comment] 2023-01-17 08:22
So maybe we need to fix the version of `tabascoterrier/docker-imap-devel`

**Comment by silverwind** [comment] 2023-01-17 09:16
If the problem ist related to container startup, I can recommend adding a drone step to wait on the TCP port to become available:

```yaml
- name: wait-on-db
  image: willwill/wait-for-it
  commands:
    - /wait-for-it.sh servicename:25 -t 180

**Comment by KN4CK3R** [comment] 2023-01-17 09:25
I don't know if timing is a problem. The test which uses this container is run in the middle of our integration tests. So there should be plenty of time (~10min).

**Comment by lunny** [comment] 2023-06-21 08:13
As a note. This incoming tests are currently disabled from CI.

**Comment by yp05327** [comment] 2024-03-21 06:17
Did this issue occur when we was still using Drone?
As this test is disabled now, we can not know whether it will happen in GH Action?

**Comment by lunny** [comment] 2024-03-21 06:27
I think we can close it for now.

**Closed as completed by lunny** 2024-03-21 06:27 UTC
Labels: type/bug, type/testing
