### ISSUE TITLE
Can no more assign users to issues

### ISSUE THREAD

**Issue by GhaziTriki** [go-gitea/gitea#19039] opened 2022-03-09 14:29 UTC
### Gitea Version

1.16.3

### Operating System

Ubunutu 20.4 LTS

### How are you running Gitea?

Self-hosted binary.

### Database

PostgreSQL

### Can you reproduce the bug on the Gitea demo site?

No

### Description

We have 5 members in the project. I updated from 1.16.1 to 1.16.3 and I can no more assign team-mates to the issues. All issues can be assigned to the site admin only.

Was not able to create a repo on try.gitea.io

**Comment by AaronS8** [comment] 2022-03-09 15:03
@GhaziTriki, Does your team have write access on all units, not just issues? and what is the status of your team access attribute?, may be this's related to #18572.

**Comment by GhaziTriki** [comment] 2022-03-09 15:15
Hi @AaronS8 All the team members of the repo have write access, at least the ones we need to assign.

**Comment by qskousen** [comment] 2022-03-09 20:38
I am experiencing this as well, on the create issue screen I can not assign OR @ tag any other team members, after issue is created I was able to @ or assign one of the other team members only, not any of the others.

**Comment by noerw** [comment] 2022-03-09 22:04
duplicate of https://github.com/go-gitea/gitea/issues/18992, this will be fixed in 1.16.4

**Closed as completed** 2022-03-09 23:06 UTC
Labels: issue/duplicate
