### ISSUE TITLE
CentOS 8 - Systemd not working anymore after update

### ISSUE THREAD

**Issue by forgeOneHQ** [go-gitea/gitea#13848] opened 2020-12-04 15:33 UTC
- Gitea version (or commit ref):  1.13.0
- Git version: 2.18.4
- Operating system: CentOS 8
  Installed via binary.

- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No

- Log gist:

## Description
After the update from 1.12.5 to 1.12.6/1.13.0 systemd is not running anymore. I only get the info that it fails.

When I start the service just via console with the exec command, all is fine.

Were there any changes between the versions I didn't see?

**Comment by 6543** [comment] 2020-12-04 16:08
not related to systemd - if you had systemd logs it would help us to find the issue

**Comment by talheim-it** [comment] 2020-12-04 16:13
@6543 the problem is more that they are not really helpul:
● gitea.service - Gitea (Git with a cup of tea)
   Loaded: loaded (/etc/systemd/system/gitea.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2020-12-04 17:11:57 CET; 3s ago
  Process: 3443 ExecStart=/usr/local/bin/gitea web --config /etc/gitea/app.ini (code=exited, status=203/EXEC)
 Main PID: 3443 (code=exited, status=203/EXEC)

Dec 04 17:11:57 git01.talheim-it.at systemd[1]: gitea.service: Service RestartSec=100ms expired, scheduling restart.
Dec 04 17:11:57 git01.talheim-it.at systemd[1]: gitea.service: Scheduled restart job, restart counter is at 5.
Dec 04 17:11:57 git01.talheim-it.at systemd[1]: Stopped Gitea (Git with a cup of tea).
Dec 04 17:11:57 git01.talheim-it.at systemd[1]: gitea.service: Start request repeated too quickly.
Dec 04 17:11:57 git01.talheim-it.at systemd[1]: gitea.service: Failed with result 'exit-code'.
Dec 04 17:11:57 git01.talheim-it.at systemd[1]: Failed to start Gitea (Git with a cup of tea).

you can ignore the "request repeated too quickly", I just want to show there is not much.

**Comment by jolheiser** [comment] 2020-12-04 16:14
What does `journalctl` say? Or the gitea logs?

**Comment by talheim-it** [comment] 2020-12-04 16:14
From journal -u gitea

Dec 04 17:11:56 git01.talheim-it.at systemd[1]: gitea.service: Main process exited, code=exited, status=203/EXEC
Dec 04 17:11:56 git01.talheim-it.at systemd[1]: gitea.service: Failed with result 'exit-code'.
Dec 04 17:11:56 git01.talheim-it.at systemd[1]: gitea.service: Service RestartSec=100ms expired, scheduling restart.
Dec 04 17:11:56 git01.talheim-it.at systemd[1]: gitea.service: Scheduled restart job, restart counter is at 1.
Dec 04 17:11:56 git01.talheim-it.at systemd[1]: Stopped Gitea (Git with a cup of tea).
Dec 04 17:11:56 git01.talheim-it.at systemd[1]: Started Gitea (Git with a cup of tea).
Dec 04 17:11:56 git01.talheim-it.at systemd[1]: gitea.service: Main process exited, code=exited, status=203/EXEC
Dec 04 17:11:56 git01.talheim-it.at systemd[1]: gitea.service: Failed with result 'exit-code'.
Dec 04 17:11:57 git01.talheim-it.at systemd[1]: gitea.service: Service RestartSec=100ms expired, scheduling restart.
Dec 04 17:11:57 git01.talheim-it.at systemd[1]: gitea.service: Scheduled restart job, restart counter is at 2.
Dec 04 17:11:57 git01.talheim-it.at systemd[1]: Stopped Gitea (Git with a cup of tea).
Dec 04 17:11:57 git01.talheim-it.at systemd[1]: Started Gitea (Git with a cup of tea).
Dec 04 17:11:57 git01.talheim-it.at systemd[1]: gitea.service: Main process exited, code=exited, status=203/EXEC
Dec 04 17:11:57 git01.talheim-it.at systemd[1]: gitea.service: Failed with result 'exit-code'.
Dec 04 17:11:57 git01.talheim-it.at systemd[1]: gitea.service: Service RestartSec=100ms expired, scheduling restart.
Dec 04 17:11:57 git01.talheim-it.at systemd[1]: gitea.service: Scheduled restart job, restart counter is at 3.
Dec 04 17:11:57 git01.talheim-it.at systemd[1]: Stopped Gitea (Git with a cup of tea).
Dec 04 17:11:57 git01.talheim-it.at systemd[1]: Started Gitea (Git with a cup of tea).
Dec 04 17:11:57 git01.talheim-it.at systemd[1]: gitea.service: Main process exited, code=exited, status=203/EXEC
Dec 04 17:11:57 git01.talheim-it.at systemd[1]: gitea.service: Failed with result 'exit-code'.
Dec 04 17:11:57 git01.talheim-it.at systemd[1]: gitea.service: Service RestartSec=100ms expired, scheduling restart.
Dec 04 17:11:57 git01.talheim-it.at systemd[1]: gitea.service: Scheduled restart job, restart counter is at 4.
Dec 04 17:11:57 git01.talheim-it.at systemd[1]: Stopped Gitea (Git with a cup of tea).

**Comment by lunny** [comment] 2020-12-04 16:17
chmod +x /usr/local/bin/gitea

**Comment by talheim-it** [comment] 2020-12-04 16:20
@lunny  that would be the basic issue I think but it isn't:
Systemd file:
[Unit]
Description=Gitea (Git with a cup of tea)
After=syslog.target
After=network.target

[Service]
RestartSec=2s
Type=simple
User=gitea
Group=gitea
WorkingDirectory=/var/lib/gitea/
ExecStart=/usr/local/bin/gitea web --config /etc/gitea/app.ini
Restart=always
Environment=USER=git HOME=/home/git GITEA_WORK_DIR=/var/lib/gitea

[Install]
WantedBy=multi-user.target



Logs:
Dec 04 17:20:14 git01.talheim-it.at systemd[1]: Started Gitea (Git with a cup of tea).
Dec 04 17:20:14 git01.talheim-it.at systemd[1]: gitea.service: Main process exited, code=exited, status=203/EXEC
Dec 04 17:20:14 git01.talheim-it.at systemd[1]: gitea.service: Failed with result 'exit-code'.
Dec 04 17:20:16 git01.talheim-it.at systemd[1]: gitea.service: Service RestartSec=2s expired, scheduling restart.
Dec 04 17:20:16 git01.talheim-it.at systemd[1]: gitea.service: Scheduled restart job, restart counter is at 18.
Dec 04 17:20:16 git01.talheim-it.at systemd[1]: Stopped Gitea (Git with a cup of tea).
Dec 04 17:20:16 git01.talheim-it.at systemd[1]: Started Gitea (Git with a cup of tea).
Dec 04 17:20:16 git01.talheim-it.at systemd[1]: gitea.service: Main process exited, code=exited, status=203/EXEC
Dec 04 17:20:16 git01.talheim-it.at systemd[1]: gitea.service: Failed with result 'exit-code'.
Dec 04 17:20:19 git01.talheim-it.at systemd[1]: gitea.service: Service RestartSec=2s expired, scheduling restart.
Dec 04 17:20:19 git01.talheim-it.at systemd[1]: gitea.service: Scheduled restart job, restart counter is at 19.
Dec 04 17:20:19 git01.talheim-it.at systemd[1]: Stopped Gitea (Git with a cup of tea).
Dec 04 17:20:19 git01.talheim-it.at systemd[1]: Started Gitea (Git with a cup of tea).
Dec 04 17:20:19 git01.talheim-it.at systemd[1]: gitea.service: Main process exited, code=exited, status=203/EXEC
Dec 04 17:20:19 git01.talheim-it.at systemd[1]: gitea.service: Failed with result 'exit-code'.
Dec 04 17:20:21 git01.talheim-it.at systemd[1]: gitea.service: Service RestartSec=2s expired, scheduling restart.
Dec 04 17:20:21 git01.talheim-it.at systemd[1]: gitea.service: Scheduled restart job, restart counter is at 20.
Dec 04 17:20:21 git01.talheim-it.at systemd[1]: Stopped Gitea (Git with a cup of tea).
Dec 04 17:20:21 git01.talheim-it.at systemd[1]: Started Gitea (Git with a cup of tea).
Dec 04 17:20:21 git01.talheim-it.at systemd[1]: gitea.service: Main process exited, code=exited, status=203/EXEC
Dec 04 17:20:21 git01.talheim-it.at systemd[1]: gitea.service: Failed with result 'exit-code'.
Dec 04 17:20:23 git01.talheim-it.at systemd[1]: gitea.service: Service RestartSec=2s expired, scheduling restart.
Dec 04 17:20:23 git01.talheim-it.at systemd[1]: gitea.service: Scheduled restart job, restart counter is at 21.
Dec 04 17:20:23 git01.talheim-it.at systemd[1]: Stopped Gitea (Git with a cup of tea).
Dec 04 17:20:23 git01.talheim-it.at systemd[1]: Started Gitea (Git with a cup of tea).
Dec 04 17:20:23 git01.talheim-it.at systemd[1]: gitea.service: Main process exited, code=exited, status=203/EXEC
Dec 04 17:20:23 git01.talheim-it.at systemd[1]: gitea.service: Failed with result 'exit-code'.
Dec 04 17:20:25 git01.talheim-it.at systemd[1]: gitea.service: Service RestartSec=2s expired, scheduling restart.
Dec 04 17:20:25 git01.talheim-it.at systemd[1]: gitea.service: Scheduled restart job, restart counter is at 22.
Dec 04 17:20:25 git01.talheim-it.at systemd[1]: Stopped Gitea (Git with a cup of tea).
Dec 04 17:20:25 git01.talheim-it.at systemd[1]: Started Gitea (Git with a cup of tea).
Dec 04 17:20:25 git01.talheim-it.at systemd[1]: gitea.service: Main process exited, code=exited, status=203/EXEC
Dec 04 17:20:25 git01.talheim-it.at systemd[1]: gitea.service: Failed with result 'exit-code'.

**Comment by talheim-it** [comment] 2020-12-04 16:27
The issue is I did not get a clear error information out of it.

When I run the gitea via cmd => "/usr/local/bin/gitea web -c /etc/gitea/app.ini &" all runs smooth.

So I am not really sure what systemd is having an issue with.

All permissions are set correctly, otherwise I think there would be erros in the log:
[gitea@git01 run]$ /usr/local/bin/gitea web -c /etc/gitea/app.ini &

2020/12/04 17:26:45 cmd/web.go:108:runWeb() [I] Starting Gitea on PID: 4515
2020/12/04 17:26:45 ...dules/setting/git.go:91:newGit() [I] Git Version: 2.18.4, Wire Protocol Version 2 Enabled
2020/12/04 17:26:45 routers/init.go:130:GlobalInit() [T] AppPath: /usr/local/bin/gitea
2020/12/04 17:26:45 routers/init.go:131:GlobalInit() [T] AppWorkPath: /usr/local/bin
2020/12/04 17:26:45 routers/init.go:132:GlobalInit() [T] Custom path: /usr/local/bin/custom
2020/12/04 17:26:45 routers/init.go:133:GlobalInit() [T] Log path: /var/lib/gitea/log

**Comment by lunny** [comment] 2020-12-04 16:29
`GITEA_WORK_DIR=/var/lib/gitea` vs `AppWorkPath: /usr/local/bin`

**Comment by talheim-it** [comment] 2020-12-04 16:32
> `GITEA_WORK_DIR=/var/lib/gitea` vs `AppWorkPath: /usr/local/bin`

How you mean? Shall I please AppWorkPath into the Env?

**Comment by talheim-it** [comment] 2020-12-04 17:18
@lunny @6543  @jolheiser 
So, the issue means that systemd means that the gitea is not executable.

That happened not with 1.12.5, it started with 1.12.6

Any ideas?

**Comment by 6543** [comment] 2020-12-04 17:27
`chmod +x` ?

**Comment by talheim-it** [comment] 2020-12-04 17:30
@6543 
-rwxr-xr-x. 1 root root 115809720 Dec  2 07:01 gitea

Makes no sense. Maybe someone else who has centos 8 and the latest version up will maybe help.

The issue is clear for me, something happened between 1.12.5 and later

**Comment by talheim-it** [comment] 2020-12-04 17:59
@6543 

If I put back the 1.12.5 it works again.

I am not a programmer in GO, so I don't know if it is related with GO and systemd which is having any issues with it binary file.

Will read the changelog maybe I see anything. Since it happens already with 1.12.6 I will check that one out.

**Comment by 6543** [comment] 2020-12-04 18:02
it should not be related to go - if systemd would me more nice with showing the reason it crashes services ....

**Comment by talheim-it** [comment] 2020-12-04 18:07
I do it the simple way by now and run it via shell.

It's a workaround but not a solution.

**Comment by silverwind** [comment] 2020-12-04 22:24
`su` to the user, reproduce the environment and run the start command. Yes, systemd debugging sucks in general.

**Comment by iamdoubz** [comment] 2020-12-04 22:52
> @6543
> -rwxr-xr-x. 1 root root 115809720 Dec 2 07:01 gitea
> 
> Makes no sense. Maybe someone else who has centos 8 and the latest version up will maybe help.
> 
> The issue is clear for me, something happened between 1.12.5 and later

If your systemd user for running gitea is `User=gitea`, then the permissions on the file should also be "gitea". Maybe ` sudo chown gitea:gitea /usr/local/bin/gitea`?

**Comment by TsakiDev** [comment] 2020-12-04 23:12
Also in what port are you trying to run Gitea?
Because in order for an executable to bind to a port less than 1024 you need to run:
`setcap 'cap_net_bind_service=+ep' /exec/path/gitea`

**Comment by talheim-it** [comment] 2020-12-04 23:44
@TsakiDev I run it behind NGINX on port 3000.

It worked before I exchanged the binary from 1.12.5 to 1.12.6/1.13.0.

As soon as I move back to 1.12.5 all works fine as expected.

@iamdoubz 
-rwxr-xr-x.  1 gitea gitea 111M Dec  2 07:01 gitea

So you see, it already is. So that is not the point. I also checked if the issue is selinux but it is not.

**Comment by talheim-it** [comment] 2020-12-04 23:51
I moved back to gitea 1.12.5.

Maybe any depency changed in the meanwhile I didn't recognize. Strange behavior.

I will try to setup a test machine to recheck it with the same configuration setup and see what is happening. 

Will write an update at the weekend about it.

**Comment by iamdoubz** [comment] 2020-12-05 00:30
In your app.ini, can you enable trace for logging?

Then, attempt to start the service.

Then, show output of `sudo journalctl -feu gitea`

**Comment by talheim-it** [comment] 2020-12-05 00:32
@iamdoubz 

[log]
MODE                 = file
LEVEL                = critical
ROOT_PATH            = /var/lib/gitea/log
REDIRECT_MACARON_LOG = true
MACARON              = console
ROUTER               = console
COLORIZE	     = true
STACKTRACE_LEVEL     = 3


That how it look at the moment

**Comment by talheim-it** [comment] 2020-12-05 00:41
Ok, we can close it now.

I have no idea what happened but after I deleted the binary and downloaded it again it worked. (downloaded it 3 times earlier today)

I didn't change anything in systemd meanwhile.

I cannot reproduce it which is bad. 

Sorry for the troubles and thank you for the time.

**Closed as completed** 2020-12-05 00:41 UTC

**Comment by watthem** [comment] 2020-12-10 09:48
I tried a brand new install using install from binary on a CentOS 8 machine - but I can't set up gitea.service; it always exits with stauts=203

Sharing my output of `sudo journalctl -feu gitea`

```
Dec 10 07:56:57 gitp2phouse systemd[1]: gitea.service: Service RestartSec=10s expired, scheduling restart.
Dec 10 07:56:57 gitp2phouse systemd[1]: gitea.service: Scheduled restart job, restart counter is at 4.
Dec 10 07:56:57 gitp2phouse systemd[1]: Stopped Gitea (Git with a cup of tea).
Dec 10 07:56:57 gitp2phouse systemd[1]: Started Gitea (Git with a cup of tea).
Dec 10 07:56:57 gitp2phouse systemd[1]: gitea.service: Main process exited, code=exited, status=203/EXEC
Dec 10 07:56:57 gitp2phouse systemd[1]: gitea.service: Failed with result 'exit-code'.
```

I can run gitea fine from shell, even could install/demo configure a few repos and projects (issue board is great, btw)

I tried enable trace for logging ... but my /var/lib/gitea/log/ is empty?

- CentOS 8
- git version 2.27.0
- MySQL
- binary 1.13.0

Please let me know if I can provide anything else.

**Comment by 6543** [comment] 2020-12-10 09:58
@watthem I think this is unrelated to this issue, since it looks like you are setting up a new instance ...

the easyest way to find help for setup is via our discord server

---

> I can run gitea fine from shell

did you run with the same config & user, directorys ... / how did you start gitea ?
I guess this is a permission issue. what owner&permissinon /var/lib/gitea has?

**Comment by zeripath** [comment] 2020-12-10 12:24
@watthem https://docs.gitea.io/en-us/logging-configuration/#debugging-problems

**Comment by techknowlogick** [comment] 2020-12-10 20:03
I'm going to lock this as we shouldn't be commenting on closed tickets as the conversation will be lost.
