### ISSUE TITLE
JavaScript Error: Cannot Parse Date Format on Version 1.21.11 During Page Change in Milestones

### ISSUE THREAD

**Issue by CasperHK** [go-gitea/gitea#32291] opened 2024-10-18 09:37 UTC
### Description:
During the page change in the Milestones section, a JavaScript error is encountered that states:

```js
JavaScript error: Cannot parse: 10000-01-0
```

This error is thrown from the file webcomponents.js at the following URL:
https://10.11.20.95:3000/assets/js/webcomponents.js?v=1.21.11 at line 1,55713.

### Steps to Reproduce:
1. Navigate to the Milestones section.
2. Attempt to change the page.
3. Observe the error in the browser console.

### Expected Behavior:
The page should change without any JavaScript errors.

### Actual Behavior:
A parsing error occurs, but the milestone list is loaded correctly.

### Recommendation:
Check the date formatting in the data being passed to the JavaScript function. Ensure it conforms to a valid date format that can be parsed successfully.

### Note:
Open the browser console for more details on the error message and stack trace.

### Gitea Version

1.21.11

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/user-attachments/assets/011c7584-5850-47dd-b75a-1120125b2343)

### Operating System

Ubuntu

### How are you running Gitea?

The Gitea is running on Ubuntu 20.04.3 as a systemd service.

### Database

MySQL/MariaDB

**Comment by lunny** [comment] 2024-10-18 11:25
If you cannot reproduce this on the demo site with the same repository or page, that commonly means this has been resolved by Gitea new stable versions. So that maybe you can try upgrade to v1.22

**Comment by yardenshoham** [comment] 2024-10-18 17:20
Please run:

```sql
SELECT *
FROM "milestone"
```

**Comment by yardenshoham** [comment] 2024-10-21 14:26
Then it must not be the milestone deadline, probably another timestamp on that page.

**Comment by yardenshoham** [comment] 2024-10-21 15:04
How to reproduce it?

**Comment by wxiaoguang** [comment] 2024-10-21 16:07
Maybe related to "Fix due date rendering the wrong date in issue (#26268)" and "Fix date rendering by adding `<gitea-absolute-date>` (#29725)"

The deadline's date `9999-12-31` is not able to be handled by the new code.

**Comment by yardenshoham** [comment] 2024-10-21 16:11
cc @silverwind

**Comment by wxiaoguang** [comment] 2024-10-21 16:45
After reading more context, I think the real problem is the bad design of "Deadline", which uses "9999-12-31". The bad design triggers the frontend bug (say, frontend code is not right either).

A complete fix should start from refactoring the "Deadline" field of the Milestone model. A quick fix could only bypass some edge cases.

**Comment by lunny** [comment] 2024-10-21 19:31
Maybe we can use `0` for the `deadline_unix` in the `milestone` table as no deadline. As a migration, we could replace the value which is bigger than `253402099200` as `0` in the database.

**Comment by wxiaoguang** [comment] 2024-10-22 03:02
The year "9999" in web/api was introduced in year 2014 (it doesn't seem reasonable), at the moment there is no migration using such value.

And the worst thing is, when `253402300799` is stored in database, it would be read and converted again and affected by timezone, so it could become early or late values other than `9999-12-33 23:59:59`, and other logic also goes wrong.

![image](https://github.com/user-attachments/assets/07507f7f-07aa-428f-be78-83b2ab55cb5c)

**Comment by nnsee** [comment] 2024-10-22 10:14
Some more details: opening the "Edit milestone" page, the incorrect date can be seen as the due date.

![image](https://github.com/user-attachments/assets/3af6b203-9aa9-4564-a9a3-3edb433bb3ff)

The "clear" button works and clears the incorrect due date. This also resolves the frontend parse error.

**Comment by silverwind** [comment] 2024-10-22 10:23
> Maybe we can use `0` for the `deadline_unix` in the `milestone` table as no deadline. As a migration, we could replace the value which is bigger than `253402099200` as `0` in the database.

Even better would be to use SQL `NULL` / JSON `null` to indicate "no date".

**Comment by crackedmind** [comment] 2024-10-25 09:50
This bug also triggers when you migrating server to another timezone, eg. Gmt+3 to gmt+5

**Closed as completed** 2024-11-05 07:46 UTC
Labels: type/bug, issue/regression
