### ISSUE TITLE
PR comments can randomly get duplicated

### ISSUE THREAD

**Issue by delvh** [go-gitea/gitea#16565] opened 2021-07-27 20:47 UTC
- Gitea version (or commit ref): 1.14.4
- Can you reproduce the bug at https://try.gitea.io: Don't know, not enough information what might cause it in the first place. Tried what is known, so far unsuccessful.

## Description
For some totally unknown reason, it can randomly happen that when you edit a PR comment (especially in the `Files` tab), it gets edited, and the edit will be published as a new reply to the original comment. I have no idea when this occurs exactly, I only think that the action I took prior to the comment being duplicated was editing the original comment.

## Screenshots
![image](https://user-images.githubusercontent.com/51889757/127224614-816d65cf-09c0-4118-b70c-76b32dbf7fdd.png)
In this image, people not being me were cropped. Additionally, the actual review comment was obfuscated with pseudo text. It should hopefully not make a difference that there is a java code example in the screenshot.
You can see that suddenly the comment got duplicated, even though it was not manually entered.

**Comment by wxiaoguang** [comment] 2021-12-08 07:35
Duplicate of

* https://github.com/go-gitea/gitea/issues/17111 (with more details)

Still no agreement about how to fix it  elegantly.

* https://github.com/go-gitea/gitea/pull/16157

**Closed as completed by wxiaoguang** 2021-12-08 07:35 UTC
Labels: type/bug
