### ISSUE TITLE
Gitea Pages

### ISSUE THREAD

**Issue by ShalokShalom** [go-gitea/gitea#2208] opened 2017-07-24 17:03 UTC
You can provide Gitea pages, together with Caddy, a Go alternative to Apache and Nginx.

https://caddyserver.com/docs/http.git
https://caddyserver.com/

**Comment by bkcsoft** [comment] 2017-07-26 01:30
Duplicate of https://github.com/go-gitea/gitea/issues/302

**Comment by bkcsoft** [comment] 2017-07-26 01:30
And if not of that, then https://github.com/go-gitea/gitea/issues/1721

**Closed as completed by bkcsoft** 2017-07-26 01:30 UTC
Labels: issue/duplicate
