### ISSUE TITLE
Error updating Organization name

### ISSUE THREAD

**Issue by dxas90** [go-gitea/gitea#7537] opened 2019-07-19 16:15 UTC
- Gitea version (or commit ref):  1.8.3
- Git version: 2.17.1
- Operating system: GNU/Linux Ubuntu 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant

## Description

Hey guys I get this error when I miss a space at the end of the name updating the organization name
```template: org/settings/options:41:110: executing "org/settings/options" at <eq .CurrentVisibility 0>: error calling eq: invalid type for comparison```

## Screenshots

![](https://static.md/2cada49027f20d97ca3ab4b60ba00f25.png)

**Comment by jolheiser** [comment] 2019-07-19 16:21
This should be fixed in 1.9+ by #7385

**Comment by lafriks** [comment] 2019-07-19 17:38
Duplicate of #6755

**Closed as completed by lafriks** 2019-07-19 17:38 UTC
Labels: issue/duplicate
