### ISSUE TITLE
The "all" count on a user's Pull Requests page is misleading

### ISSUE THREAD

**Issue by parnic** [go-gitea/gitea#20574] opened 2022-07-31 19:18 UTC
### Description

When clicking around on the PRs from a user's Pull Requests page (the button in the main site header, e.g.: https://try.gitea.io/pulls), "All" is selected by default and shows the total count of all PRs in all repos.

<img width="712" alt="image" src="https://user-images.githubusercontent.com/888126/182041693-0b0f70bb-57b5-40b0-b5d5-f0c11fc4c354.png">

Clicking on one of the repos, however, causes the "All" count to change to whatever is highlighted instead of showing the composite total:

<img width="702" alt="image" src="https://user-images.githubusercontent.com/888126/182041700-43f85bb6-f164-408c-ab88-2618981fce19.png">

<img width="728" alt="image" src="https://user-images.githubusercontent.com/888126/182041708-ddafe1f8-e8ed-47c3-8b92-5916e58aeb4f.png">

<img width="691" alt="image" src="https://user-images.githubusercontent.com/888126/182041710-c08777e5-faab-4a17-b81a-cdf2e990e697.png">

I feel like All was always showing the total count in 1.16.9, but is exhibiting this behavior in 1.17.0. I am not sure if All is supposed to indicate "the number we're showing you based on your selection" or "the number we'd be showing you if you clicked on this". I tend to assume it should be the latter based on how the individual repos behave.

### Gitea Version

1.17.0, 1.18.0+dev-193-g335e918b1

### Can you reproduce the bug on the Gitea demo site?

Yes

### Git Version

2.37.1

### Operating System

Linux

### How are you running Gitea?

Ubuntu apt package

### Database

PostgreSQL

**Comment by noerw** [comment] 2022-07-31 19:54
This is a regression from https://github.com/go-gitea/gitea/pull/20454.
The code for generating this page is complex as fuck, so I'm not suprised this regressed :sweat_smile:

**Comment by lunny** [comment] 2022-08-16 04:20
> #20454

Since it's only in 1.18.0, I don't think it needs to be added to milestone 1.17.1

**Comment by parnic** [comment] 2022-08-16 04:25
> > #20454
> 
> Since it's only in 1.18.0, I don't think it needs to be added to milestone 1.17.1

This bug definitely exists in 1.17.0. I logged the big when I noticed it after our upgrade. I don't think the quoted pr is accurate for when this was introduced.

**Comment by noerw** [comment] 2022-08-16 10:25
> I don't think the quoted pr is accurate for when this was introduced.
I carefully did a `git bisect`, I'm certain it's that commit.

> Since it's only in 1.18.0, I don't think it needs to be added to milestone 1.17.1
The change [was backported](https://github.com/go-gitea/gitea/pull/20496) to 1.17, so 1.17.1 is the appropriate target.

**Comment by lunny** [comment] 2022-08-17 06:33
fixed by #20496

**Closed as completed by lunny** 2022-08-17 06:33 UTC
Labels: type/bug

**Comment by parnic** [comment] 2022-08-17 12:59
> fixed by #20496

#20496 is the one that caused the problem. The fix, #20785, is still waiting to be merged and then needs a backport. I'll get the backport posted today.
