### ISSUE TITLE
SVGs should always have the option to be displayed as image

### ISSUE THREAD

**Issue by delvh** [go-gitea/gitea#14943] opened 2021-03-10 12:33 UTC
- Gitea version (or commit ref): 1.14.0+dev-825-g5b94a07ab
- Can you reproduce the bug at https://try.gitea.io:
  - Yes: [PR](https://try.gitea.io/delvh/kanban-test/pulls/16/files) versus in [file view](https://try.gitea.io/delvh/kanban-test/src/commit/ded19ffe11ff1ced9321d36063aec208d82b0e1c/test.svg)

## Description
Gitea supports showing SVGs as image and not as text, but apparently that only applies when viewing the file in the file view [(example)](https://try.gitea.io/delvh/kanban-test/src/commit/ded19ffe11ff1ced9321d36063aec208d82b0e1c/test.svg).
When opening a new PR, a SVG will still only be displayed as text in the preview and later on in the existing PR.

## Expected behavior
Wherever in a repo a SVG image gets encountered, it should be displayed initially as image, not as text, but with the ability to convert it to raw text.

## Screenshots
Appearance in file view:
![image](https://user-images.githubusercontent.com/51889757/110629768-dac69880-81a4-11eb-9283-be9b1316d867.png)

Appearance in PR:
![image](https://user-images.githubusercontent.com/51889757/110629845-f0d45900-81a4-11eb-9510-fa171adbee52.png)

Appearance in PR preview:
![image](https://user-images.githubusercontent.com/51889757/110629979-1b261680-81a5-11eb-8dcc-02563877105d.png)

**Comment by zeripath** [comment] 2021-03-11 17:21
Look I don't think this is a bug - it's a missing feature.

**Comment by delvh** [comment] 2021-03-11 18:43
I see why you think so, but on the other hand I would expect, given that gitea is already able to display svg files as image, that they always offer the option to do so…
This is one of the rare cases where there seems not to exist any boundary between missing feature and bug.

**Comment by KN4CK3R** [comment] 2021-03-14 12:22
see #14867

**Comment by kdumontnu** [comment] 2021-03-17 15:41
Duplicate of #14329

**Closed as completed by kdumontnu** 2021-03-17 15:41 UTC
Labels: issue/duplicate
