### ISSUE TITLE
Incorrect aggregated status of commit statuses

### ISSUE THREAD

**Issue by harryzcy** [go-gitea/gitea#25776] opened 2023-07-09 02:36 UTC
### Description

The commit as part of PR is marked with green check, when some workflows is still running.

### Gitea Version

v1.19.4

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

<img width="477" alt="image" src="https://github.com/go-gitea/gitea/assets/37034805/5ab0a16e-0ec0-4ce3-853c-db26103bca8e">

### How are you running Gitea?

official docker image

### Database

PostgreSQL

**Comment by sebastian-sauer** [comment] 2023-07-10 16:59
What is the current "order" / priority for those states? 
If the expected behaviour is clear i'm happy to write a test & fix for this.

I'd assume the following :

Order (always if one state is available first, then this should be the combined state)

[Pending, Running, Error, Failure, Warning, Success]

so if one is pending -> show pending
if none is pending but 1 is running -> show pending 
and so on :)

**Comment by CaiCandong** [comment] 2023-07-11 04:14
https://github.com/go-gitea/gitea/blob/491cc06ffe3491242ad9ff6227423d99e673d0c2/modules/structs/commit_status.go#L26-L40

The truth table for the above function is as follows ， `CommitStatusSuccess` <=`CommitStatusRunning`  should be false?
| NoBetterThan(<=)    | CommitStatusError | CommitStatusFailure | CommitStatusWarning | CommitStatusPending | CommitStatusRunning | CommitStatusSuccess |
|---------------------|-------------------|---------------------|---------------------|---------------------|---------------------|---------------------|
| CommitStatusError   | true              | true                | true                | true                | true                | true                |
| CommitStatusFailure | false             | true                | true                | true                | true                | true                |
| CommitStatusWarning | false             | false               | true                | true                | true                | true                |
| CommitStatusPending | false             | false               | false               | true                | true                | true                |
| CommitStatusRunning | false             | false               | false               | false               | true                | true                |
| CommitStatusSuccess | false             | false               | false               | false               |true               | true                |

**Comment by CaiCandong** [comment] 2023-07-11 06:43
1.  For this issue solution, I noticed that the priority in the source code is [Error, Failure, Warning, Pending,Running,Success], but there might be a little problem in the implementation, which leads to `Success.NoBetterThan(Running) ` return `ture`, we just need to fix this little problem to resolve the issue.

2. Regarding the need to align  with github, @sebastian-sauer you mentioned the github implementation:.
```
Additionally, a combined state is returned. The state is one of:

- failure if any of the contexts report as error or failure
- pending if there are no statuses or a context is pending
- success if the latest status for all contexts is success
```
But I noticed that there are only 4 statuses for github [create-a-commit-status](https://docs.github.com/en/rest/commits/statuses?apiVersion=2022-11-28#create-a-commit-status)
```
state string Required
The state of the status.

Can be one of: error, failure, pending, success
```
The design of gitea is still somewhat different from github, so we can't fully align it with github.

3. I don't quite understand why @sebastian-sauer's priority is `[Pending, Running, Error, Failure, Warning, Success]`, according to github's documentation, I think github's priority should be `[error,failure, Pending,Success]`, and either `error` or `failure` returns `failure`.This contradicts your suggestion of `[Pending, Running, Error, Failure, Warning, Success]`, when both `Running` and `Failure` are present the When both `Running` and `Failure` are present, the combined state should be `Failure`, right? But depending on your priority, it will return `Running`.

**Comment by wolfogre** [comment] 2023-07-11 08:23
My idea is to remove `running` as a commit status. It was added because Gitea Actions has `running`, but it could be a mistake. I think `pending` is enough to express the `waiting`, `running` or `blocked` for Gitea Actions.

And `warning` may be  also a mistake too, I have no idea when to use `warning` instead of `failure`/`warning`.

**Closed as completed** 2023-07-21 08:24 UTC
Labels: type/bug
