### ISSUE TITLE
API /repos​/{owner}​/{repo}​/raw​/{filepath} fails if filepath is 40-char long

### ISSUE THREAD

**Issue by danielemoroni** [go-gitea/gitea#17179] opened 2021-09-29 12:41 UTC
### Gitea Version

1.12.3

### How are you running Gitea?

I deployed an official download to my server

### Can you reproduce the bug on the Gitea demo site?

Yes

### Description

The Gitea API GET /repos​/{owner}​/{repo}​/raw​/{filepath} fails with http error 404 (or "object does not exist" in the latest gitea version) if the filepath is 40-character long.

I replicated the issue on https://try.gitea.io/danielemoroni/raw_api:
. This fails:
https://try.gitea.io/api/v1/repos/danielemoroni/raw_api/raw/filename_40char_long_xxxxxxxxxxxxxxx.txt
. This succeeds:
https://try.gitea.io/api/v1/repos/danielemoroni/raw_api/raw/filename_41char_long_xxxxxxxxxxxxxxxx.txt

The files are actually identical. I can retrieve them both without problems with another API, e.g.
https://try.gitea.io/danielemoroni/raw_api/src/branch/master/filename_40char_long_xxxxxxxxxxxxxxx.txt

**Comment by lunny** [comment] 2021-09-29 13:10
Could you upgrade to latest stable version?

**Comment by noerw** [comment] 2021-09-29 17:01
what an odd bug :eyes:  maybe Gitea special-cases 40 chars, because git SHAs can have that length?

@lunny they reproduced with try.gitea.io, I guess that's good enough

**Comment by noerw** [comment] 2021-09-30 08:40
@danielemoroni this is a stupid bug, you can work around this by prefixing your filepath with `$repo_default_branch/`.

However, this way to specify a ref will possibly be deprecated in 1.16, and the way you currently use this will be fixed in 1.16.0 and 1.15.4. As your Gitea version 1.12 does not receive fixes anyway, you're probably best off to update Gitea to >=1.15.4 once released, instead of adapting your API client.

**Comment by danielemoroni** [comment] 2021-09-30 08:53
@noerw Thank you for the explanation, and the quick response.

We tend to upgrade our gitea once a year, so we'll pick this up in our next round. I'll bear in mind the deprecation, it's not too bad to change the API calls on our side, so we might do both at the same time.

**Comment by lunny** [comment] 2021-10-30 04:04
This has been resolved by #17212 in v1.15.4 but not in 1.16.

**Comment by yp05327** [comment] 2024-09-26 02:27
> This has been resolved by #17212 in v1.15.4 but not in 1.16.

There's a typo, it should be #17272.

**Comment by yp05327** [comment] 2024-09-26 02:29
And it is fixed in a special version, which is so strange.

**Comment by lunny** [comment] 2024-09-28 01:38
#17185 is the original PR but not merged.

**Comment by yp05327** [comment] 2024-09-30 23:37
What I want to say is that why original PR was not merged but the backport was merged first. This is so strange.

**Comment by wxiaoguang** [comment] 2024-11-04 04:09
You should use `http://localhost:3000/api/v1/repos/OWNER/REPO/raw/main/filename_40char_long_xxxxxxxxxxxxxxx.txt` (with a branch name or tag name) but not the ambiguous path.

**Comment by wxiaoguang** [comment] 2024-11-04 05:15
And it could be fixed like this:  Refactor RepoRefByType #32413

**Comment by wxiaoguang** [comment] 2024-11-05 06:41
For most use cases, this problem should have been fixed in 1.23

**Closed as completed by wxiaoguang** 2024-11-05 06:41 UTC
Labels: type/bug
