### ISSUE TITLE
Internal Server Error (500) after 1.16.6 upgrade

### ISSUE THREAD

**Issue by aleprovencio** [go-gitea/gitea#19492] opened 2022-04-25 15:34 UTC
### Description

After upgrading to `1.16.6` from `1.16.5`, gitea started to show Internal Server Error messages 

I'm getting this error while trying to use 'git push' or even when trying to access a repo owned by me via the web interface.

### Gitea Version

1.16.6

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

https://gist.github.com/aleprovencio/365299758c54ec3985115421f1534aa5#file-gitea-log

### How are you running Gitea?

Self-hosted Docker

### Database

MySQL

**Comment by techknowlogick** [comment] 2022-04-25 15:40
closing as dupe of https://github.com/go-gitea/gitea/issues/19455 (same root cause)

**Closed as completed by techknowlogick** 2022-04-25 15:40 UTC
Labels: issue/duplicate
