### ISSUE TITLE
Proposal: use https://github.com/src-d/go-git

### ISSUE THREAD

**Issue by typeless** [go-gitea/gitea#1511] opened 2017-04-19 06:08 UTC
Upside:
1. No dependency on particular versions of the on-site `git` command.
2. Better performance due to less fork/exec/IPC (measurement needed).
3. More reliable error handling (no stdout/stderr parsing).
4. Less complexities. (Pure Go function calls vs exec.Command + exec.Start + exec.Wait + stdout/stderr parsing).

If the is desired, then incrementally replacing some read-only Git operations will be a good start.

**Comment by strk** [comment] 2017-04-19 06:38
If I read correctly the code in its current version does not support merges ?
See https://github.com/src-d/go-git
Also, are you suggesting to use this as one of the implementations of the go-gitea/git interface as proposed somewhere else or as the primary API for git work ?
Did you test performance compared to libgit ?

**Comment by bkcsoft** [comment] 2017-04-19 07:17
Duplicate of #481. Please continue there

**Closed as completed by bkcsoft** 2017-04-19 07:17 UTC
Labels: type/feature
