### ISSUE TITLE
Odd node-red integration

### ISSUE THREAD

**Issue by anthrogan** [go-gitea/gitea#5109] opened 2018-10-18 16:23 UTC
- Gitea version (or commit ref): 1.5.1
- Git version: 
- Operating system: Windows 10 Pro
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

I'm not entirely sure this is something I'm doing with SSH pushes or its gitea/node-red, nothings actually giving me any error information. Its all in an internal network so we rarely use SSH but its becoming more common so we try to move to it where possible. Node-RED use is one of those cases so we setup SSH on Gitea and setup a deploy key.

We can see remote commits etc in node-red's UI, but nothing actually shows up in Gitea we still get the blank placeholder page. Hopefully the screenshots explain it better.

We can even clone the repo in Node-red and it recreates itself fine

## Screenshots

![image](https://user-images.githubusercontent.com/30973884/47167701-03f5de00-d2f7-11e8-80d4-3405d20ab77c.png)
![image](https://user-images.githubusercontent.com/30973884/47167767-27b92400-d2f7-11e8-9341-4a9feda7ee6d.png)

Node-red commit history (Its kind of like VSCodes git UI)
![image](https://user-images.githubusercontent.com/30973884/47167849-5505d200-d2f7-11e8-944b-f51ab58ea659.png)
remote url matches and it knows theres a push to go up
![image](https://user-images.githubusercontent.com/30973884/47167963-972f1380-d2f7-11e8-8a22-9c9ed55bc06f.png)

I can even clone the repo and see some files in it, node-red uses flow.json to rebuild itself I thought the README might actually show up though?
![image](https://user-images.githubusercontent.com/30973884/47168194-2e946680-d2f8-11e8-80b5-cb41dfefbba2.png)

**Comment by techknowlogick** [comment] 2018-10-18 16:48
@anthrogan thanks for reporting this 😄 
Deploy keys not updating the repo information page is an issue that Gitea has (so it's not an issue with node-red), and let me go find that issue so I can link it here. I'll close this issue so we can track this same issue all in one ticket.

**Closed as completed** 2018-10-18 16:48 UTC
Labels: issue/duplicate

**Comment by techknowlogick** [comment] 2018-10-18 16:50
The issue is #4424
