### ISSUE TITLE
Feature proposal: profile readmes

### ISSUE THREAD

**Issue by ptman** [go-gitea/gitea#12233] opened 2020-07-13 08:54 UTC
## Description

Basically a clone of github profile readmes. Such a good feature that's built on git. Hopefully easy to implement, as it builds on the ability to render README.md that already exists.

## Screenshots

This repository README.md https://github.com/simonw/simonw is visible at https://github.com/simonw

**Comment by hokkqi** [comment] 2020-11-07 16:12
This'd be a really neat feature!

I currently link my main Account on my own Instance, but it would be neat if I could write a profile readme to basically list all my works, since they're not in one place and not every account on my instance is mine.

i.e. I could do something like this:

```md

- [Account Name](LINK)
  - [Project](LINK)
  - [Project](LINK)

- [Account Name](LINK)
  - [Project](LINK)
  - [Project](LINK)
  - [Project](LINK)
  - [Project](LINK)
 ```

This would make it, for me personally, easier to even put my personal Gitea on a Résumé/CV and then make it easy for potential employers to look through my works

**Comment by jolheiser** [comment] 2021-06-18 20:35
What are thoughts on this simply being a field in profile settings?

Does it _need_ to be in a magical repo with the same name as your username? (It does on GH, but in terms of Gitea)

I suppose being in a repo allows users to hook it into CI, but a repo with a single README always struck me as hacky.

**Comment by ptman** [comment] 2021-06-21 13:55
Repo is much nicer, with history etc. Only put stuff in the DB when it needs to be queried.

**Comment by hokkqi** [comment] 2021-06-23 05:58
i like how github did it tbh

**Comment by CodeDoctorDE** [comment] 2021-08-22 04:44
It would be cool if it will be a thing in 1.16.
If it will be possible, it makes sense to have this functionality on orgs too.

**Comment by himbolion** [comment] 2021-08-22 12:27
Having it on Orgs would be AMAZING, ngl.

A Description is neat but a profile readme, with the same support as all other markdown files, would be even better because we could go way more in depth when it comes to saying what an Org is about, if we choose to do that

**Comment by cGIfl300** [comment] 2021-12-05 09:36
We are in 2021 and I strongly agree with this feature, I fond this webpage looking for a way to **use a README.md as profile on gitea**.  
This is absolutly a **great idea on github**, that **could be on gitea**.  
Thank you for the one who will change the world to me 👍🏻 .

**Comment by lunny** [comment] 2021-12-05 12:02
Where should we store the `README.md`? how about in a git repository named `<user_name>/-/profile`, so that you can git clone it and push to server?

**Comment by CodeDoctorDE** [comment] 2021-12-05 12:35
In github its github.com/Username/Username

**Comment by lunny** [comment] 2021-12-05 13:09
`github.com/Username/Usernam` maybe conflicted with user's repository. i.e. `gitea/gitea`. Or `/~<user_name>`, I think it's compatible with something.

**Comment by CodeDoctorDE** [comment] 2021-12-05 13:11
On orgs, github uses `.github` as repository name like https://github.com/LinwoodCloud/.github.
Maybe gitea.com/Username/.gitea repository?

**Comment by lunny** [comment] 2021-12-05 15:02
> On orgs, github uses `.github` as repository name like https://github.com/LinwoodCloud/.github. Maybe gitea.com/Username/.gitea repository?

That sounds also OK.

**Comment by cGIfl300** [comment] 2021-12-05 17:21
> 

Simply like that: https://github.com/cGIfl300 it is stored on https://github.com/cGIfl300/cGIfl300 indeed the repository using your own nickname is indicated as "special" and the README.md is show next to your profile. (you can see my profile, I do use it)

**Comment by lunny** [comment] 2021-12-06 01:43
Or we can reuse `repository_type`, so it's a profile repository, other types are `template` and etc.

**Comment by fortressia** [comment] 2021-12-28 03:34
Don't forget to also implement this on organizations.

**Comment by Akselmo** [comment] 2022-01-13 22:19
Really hope to see this, I think it makes exploring profiles more fun and especially now that federation is coming, it can help people find people easier.

**Comment by MisileLab** [comment] 2022-04-24 16:16
This feature would be great!

**Comment by mind-overflow** [comment] 2022-05-30 23:18
hey! no update on this?

**Comment by dikey0ficial** [comment] 2022-06-23 08:46
Also waiting for this :)

**Comment by pratik2315** [comment] 2022-07-02 13:39
Hey there! I saw this issue listed on bsource a year back. I would like to work on it if its still open :)

**Comment by justusbunsi** [comment] 2022-07-02 16:41
> Hey there! I saw this issue listed on bsource a year back. I would like to work on it if its still open :)

@pratik2315 Contributions are always welcome. The issue is still open, there is no PR referenced, so... grab yourself a cup of tea and create some magic, I'd say. 😉

Feel free to join the Gitea Discord server in case you have questions. There is also a develop channel.

**Comment by jolheiser** [comment] 2022-07-04 15:39
@pratik2315 this proposal is for implementing profile readme _in_ Gitea, not on GitHub _for_ Gitea.

**Comment by pratik2315** [comment] 2022-07-04 15:41
> @pratik2315 this proposal is for implementing profile readme _in_ Gitea, not on GitHub _for_ Gitea.

Well technically the profile readme will be in gitea. and will be displayed Gitea org.
But I may be misunderstanding something😅 Can you pls elaborate more.

**Comment by pratik2315** [comment] 2022-07-04 15:43
Im talking about implementing something like this:

.github repo: https://github.com/asyncapi/.github
organisation profile: https://github.com/asyncapi

**Comment by pratik2315** [comment] 2022-07-04 15:53
ahh! seems like i completely misunderstood what this proposal was about😅

**Comment by Tech1k** [comment] 2022-07-28 02:21
I would really love to see this be implemented! :D

**Comment by HackerDaGreat57** [comment] 2022-09-10 21:24
Oh yes, this is necessary. +1

**Comment by arlcrow** [comment] 2022-10-21 13:17
+1

**Comment by goodevilgenius** [comment] 2023-01-02 03:55
Implementation-wise, I think calling it `username/.profile` would be better than `username/username` or `username/.gitea`.

Problems with the former have already been mentioned. For the latter, I just think something more neutral than `.gitea` would be better.

Additionally, this could be the basis for future features, as GitHub allows an org to put org-wide issue templates in this repo also. Something like that might be a useful feature in the future.

**Comment by LAX18** [comment] 2023-03-02 03:50
Do we like something to the effect of this? I am starting to work on this preliminarily. 
![image](https://user-images.githubusercontent.com/34464552/222326526-00f7a2af-65d1-48c6-ab7d-b4b2797dfc1e.png)

**Comment by HackerDaGreat57** [comment] 2023-03-02 04:37
@LAX18 I suppose the message could be a bit more descriptive...

How about "`{username}/.profile`'s README.md will be displayed here."

**Comment by LAX18** [comment] 2023-03-02 04:40
I was meaning more about the placement. Eventually it won't be visible at all if there is not a ```username/.profile``` repository.

**Comment by HackerDaGreat57** [comment] 2023-03-02 04:52
Yeah, the placement is good.

**Comment by delvh** [comment] 2023-05-09 07:37
PR was merged but didn't close the issue.

**Closed as completed by delvh** 2023-05-09 07:37 UTC
Labels: type/proposal
