### ISSUE TITLE
Disabled collaborator still receiving notifications on private repo

### ISSUE THREAD

**Issue by tribly** [go-gitea/gitea#4149] opened 2018-06-06 09:10 UTC
- Gitea version (or commit ref): 1.4.1-1
- Operating system: Arch Linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
When you add a new collaborator to a **private** repository, he then sets it as watched, and you remove him as a collaborator afterwards, he still receives notifications for issues and is listed in the 'watching' list, but he himself is unable to unwatch it, since he can't access the repo anymore.

**Comment by lafriks** [comment] 2018-06-06 12:16
Duplicate of #3782

**Closed as completed by lafriks** 2018-06-06 12:16 UTC
Labels: issue/duplicate
