### ISSUE TITLE
Gitea Actions workflow status badge

### ISSUE THREAD

**Issue by belliash** [go-gitea/gitea#25867] opened 2023-07-13 08:13 UTC
### Feature Description

I would really like to see an integrated support for repository actions status badges. It should display the status for the latest build of the specified branch. 

It could be available under similar link available per workflow: https://try.gitea.io/group/repo/actions/workflows/build.yml/badge.svg?branch=main

Would be cool if it could show if the workflow succeeded, failed or if it is actually running. This request is similar to https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge or https://woodpecker-ci.org/docs/usage/badges

**Comment by silverwind** [comment] 2023-07-13 18:02
Duplicate of https://github.com/go-gitea/gitea/issues/23688.

**Closed as not planned by silverwind** 2023-07-13 18:02 UTC
Labels: type/proposal
